### ISSUE TITLE
keywords() function; usage?

### ISSUE THREAD

**Issue by lunelson** [sass/sass#1000]
**EDIT**

Looking again, I see that `create-map()` was just an example to demonstrate the `keywords()` function; but my question below still applies. This function doesn't seem to offer anything new (in any case it doesn't do what I was hoping it would do). In the given example, the `create-map()` function is non-dynamic and actually more verbose than simply writing out the map in the regular syntax...

``` scss
@function create-map($args...) {
  @return keywords($args);
}

create-map($foo: 10, $bar: 11); // returns (foo: 10, bar: 11)
```

**ORIGINAL POST**

I've been trying out map functions based on the info in the [changelog](https://github.com/nex3/sass/blob/master/doc-src/SASS_CHANGELOG.md) and @chriseppstein's [CSSConf.EU presentation](https://www.youtube.com/watch?v=-ZJeOJGazgE), but stumped on `create-map()`. It seems like it should be the complement to the ability to pass maps as splat-like arguments to functions, which breaks a map out in to individual `$`-named variables: that is, create-map would seem to allow you pack up a series of variables in to a map again. However in testing it at Sassmeister it doesn't seem to work. Is it not part of the current RC1 release?

This is what I'm testing:

``` scss
$test-map: (
    alpha: 5,
    beta: 6,
    gamma: 7
);
$alpha: 1;
$beta: 2;
$gamma: 3;
$new-map: create-map($alpha, $beta, $gamma);
.debug {
    out: map-debug($test-map);
    out: map-debug($new-map);
}
```

and this is what I get:

``` css
.debug {
  out: "( alpha: 5, beta: 6, gamma: 7 )";
  out: "( create-map(1, 2, 3): )";
}
```

...I'm using the following to debug maps (edit: no need for this, there's an `inspect()` function now)

``` scss
@function str-remove($str, $sub) {
    $i: str-index($str, $sub);
    @if $i == 0 { @return $str; }
    @else { @return str-remove(str-slice($str, 1, $i - 1) + str-slice($str, $i + 1, str-length($str)), $sub); }
}
@function map-debug($map) {
    $result: unquote("( ");
    @each $key, $value in $map {
        @if type_of($value) == 'map' {
            $result: unquote("#{$result} #{$key}: #{map-debug($value)}, ");
        } @else { $result: unquote("#{$result}#{$key}: #{$value}, "); } }
    $result: unquote("#{$result} )");
    $result: str-remove($result,",  )");
    $result: str-remove($result,"  ");
    @return quote($result); }

```
