### ISSUE TITLE
`@at-root` inside multiple selector generates repeated code

### ISSUE THREAD

**Issue by kizu** [sass/sass#1003]
When you have multiple selectors and then inside of the block you have `@at-root`, then you'd get a somewhat inoptimal ouput.

This:

``` Scss
.a,
.b,
.c,
.d {
    @at-root{
        .foo {
            width: 25px;
        }
    }
}
```

Renders now (using `gem install sass --pre`) to:

``` CSS
.foo, .foo, .foo, .foo {
  width: 25px; }
```

You can see how there is one `.foo` per selector in the original multiple selector.
