### ISSUE TITLE
@media and property querying in &

### ISSUE THREAD

**Issue by scottkellum** [sass/sass#1010]
It would be useful to query other contexts like `@meida` and style properties other than selectors using the new SassScript &.

Maybe something like this:

``` SCSS
@media (min-width: 40em) {
  body:before {
    content: "Context of: #{ &(media) }";
  }
}

// Will return this CSS

@media (min-width: 40em) {
  body:before {
    content: "Context of: (min-width: 40em)";
  }
}
```

And for style properties:

``` SCSS
foo {
  font: {
    @if &(property) == font {
      family: sans-serif;
    }
  }
}

// Will return this CSS

foo {
  font-family: sans-serif;
}
```

**Comment by chriseppstein** [comment]
How would you use this ability?

  Chris Eppstein  
 Sent via Intro for iPhone

**Comment by scottkellum** [comment]
@chriseppstein In Singularity we use Breakpoint to query media context. If my media query matches my medium breakpoint then use the grid associated with it. I use media a lot more for context querying than selectors.

Auto generating a fallback for things like rgba is a good one for property querying. If something has rgba I can query the selector and write a hex value fallback, then duplicate the property and write the rgba value.

**Comment by lolmaus** [comment]
I guess a code example of how you do it now and how you'll do it with subj would make things more clear.

**Comment by scottkellum** [comment]
``` scss
$breakpoints: (
  small: (
    breakpoint: 20em,
    columns: 3
  ),
  medium: (
    breakpoint: 40em,
    columns: 6
  ),
  large: (
    breakpoint: 60em,
    columns: 12
  )
);

@media (min-width: 40em) {
  article {
    // the grid span mixin can know the context, I won’t have to tell it the context is 6 columns because I can match it up with the map.
    @include grid-span(4);
  }
}
```

I tried abstracting a lot in the initial write up, but this is a general use case. Let me know if you need me to write up an entire thing, but hopefully I don’t have to for you to get the idea. Aint nobody got time for that.

**Comment by nex3** [comment]
I'd far prefer putting these queries into their own functions to rolling them into `&`.

Scott, what SassScript objects would you expect to be returned when requesting the media query context? What about other sorts of directive contexts?

**Comment by xzyfer** [comment]
We have a similar use case in our system, on example is responsive font sizes. This is a simplified example.

```
// Config for breakpoint
$breakpoints: (
    small: 0em 40em,
    medium: 40.063em 64em,
    large: 64.063em 90em,
    xlarge: 90.063em 120em,
    xxlarge: 120.063em,
);

$font-sizes: (
    h1: (
        all: 40px,
        medium: 35px,
        small: 30px,
    )
);

@include breakpoint(map-get($breakpoints, medium)) {
    h1 {
        // we need to pass the media query "context" to the mixin so it can find the right value
        @include h1(medium);
    }
}
```

If we could query the media context from within the mixin we wouldn't need to explicitly pass parameter to `h1()`. Potentially a silly example, but there a ton of similar approaches out in the wild to help with the pain that is the responsive web.

**Comment by jakob-e** [comment]
I know this question is a bit old – and perhaps no longer relevant.

To keep track of the current context simply use a global variable
in relation to your breakpoints/media mixin

**Update** - a more elaborate example is posted here: https://github.com/sass/sass/issues/1050#issuecomment-59134749

``` SCSS
// Define breakpoints   
$breakpoints:(
  all     : 'all',
  mobile  : '(max-width:480px)',
  tablet  : '(min-width:481px) and (max-width:960px)',  
  desktop : '(min-width:961px)'    
);  

// Variable to keep track of current context
$context:'';

// Simple media mixin 
@mixin media($breakpointkeys...){
  @each $key, $value in $breakpointkeys {
    $context:$key !global;  // update to current context on enter
    @media #{map-get($breakpoints,$key)}{ @content; }
    $context:'' !global; // ... and reset on exit 
  }
}

// Simple print context mixin 
@mixin print-media-context(){
  content: "Context is #{ $context }";
}

// Test 
@include media(all, mobile, tablet, desktop){
  body:before { @include print-media-context(); }
}


// Output:
@media all {
  body:before {
    content: "Context is all";
  }
}
@media (max-width: 480px) {
  body:before {
    content: "Context is mobile";
  }
}
@media (min-width: 481px) and (max-width: 960px) {
  body:before {
    content: "Context is tablet";
  }
}
@media (min-width: 961px) {
  body:before {
    content: "Context is desktop";
  }
}

```

PS. You can also use it to create **extends across media queries** 
http://codepen.io/jakob-e/pen/jKyuq 

Jakob E

**Comment by scottkellum** [comment]
@jakob-e I tend not to use set breakpoints and instead use explicit values on many projects. There are absolutely ways to architected this. I use [Breakpoints context](https://github.com/at-import/breakpoint/wiki/Breakpoint-Context) in my own projects.

Currently I am using the Breakpoint context API for responsive logic in plugins like Singularity and Modular Scale but it would be nice to do this natively and remove the dependencies around Breakpoint. This will allow for greater portability of frameworks that contain responsive logic.

**Comment by jakob-e** [comment]
@scottkellum I'm not sure I understand – why would you not use a centralized configuration of your breakpoints? You would need to create a relation between "medium" and eg. "(min-width: 20.0625em) and (max-width: 40em)" anyways... sorry if I'm just not getting it :-)

Test: http://sassmeister.com/gist/82c8ee37295f5015df49

``` SCSS

$breakpoints:(
      small   : '(max-width: 20em)'
    , medium  : '(min-width: 20.0625em) and (max-width: 40em)'
    , large   : '(min-width: 40.0625em) and (max-width: 60em)' 
);  



// context with a little function niceness
@function media-context(){
     @return $context; 
}

// A simple mixin (inline definition – just for testing)
@mixin grid(){
    $columns: map-get((
      small : 3
    , medium: 6
    , large : 12
    ), media-context());
    //  Test
    grid-columns:$columns;
}

/*
// You could also get the columns from your $breakpoints
// (using a more complex media mixin)
@function get-breakpoint-columns(){
  $breakpoint: map-get($breakpoints, media-context());
  @return map-get($breakpoint, columns);
}
@mixin grid(){
    $columns: get-breakpoint-columns();
    //  Test
    grid-columns: $columns;
}
*/

@include media(small){
     article { @include grid(); }
}
@include media(medium){
     article { @include grid(); }
}
@include media(large){
     article { @include grid(); }
}

//... or use the option of multiple breakpoints
// does the same as above
@include media(small, medium, large){
    article  { @include grid(); }
}


```

``` CSS

// Output 
@media (max-width: 20em) {
  article {
    grid-columns: 3;
  }
}
@media (min-width: 20.0625em) and (max-width: 40em) {
  article {
    grid-columns: 6;
  }
}
@media (min-width: 40.0625em) and (max-width: 60em) {
  article {
    grid-columns: 12;
  }
}

```

**Comment by lolmaus** [comment]
@jakob-e, do not try to manage breakpoints, that's impossible. Instead, only try to realize the truth: [there is no breakpoint](http://seesparkbox.com/foundry/there_is_no_breakpoint). Then you see that it is not you who determines the breakpoints, it is only the content.

**Comment by jakob-e** [comment]
@lolmaus - I get that –  but how then would you create a relation between a specific query and eg. a column? I don't see how a native context would be of much help.

To me it is about mapping the breakpoints you use - like "lok-at-me-im-retina"

**Comment by Snugug** [comment]
@jakob-e We're getting off topic, and the example you've included to bump this thread is more or less identical to what everyone else (including the post immediately above yours) has said.

As for your question, what @scottkellum is referring to is [Singularity's Responsive Contexts](https://github.com/at-import/singularity#responsive-grids) where Singularity doesn't need to know what your final queries are in order to know, through [Breakpoint's Query Context](https://github.com/at-import/breakpoint/wiki/Breakpoint-Context), what grid settings you'd like to be using when you call Singularity inside of a media query.

The gist of this issue isn't to see everyone's way of handling media queries or to suggest that we get a native form of one of the many `breakpoint` mixins, it's to be able to introspect a media query while inside it, what Breakpoint's query context allows for.

**Comment by jakob-e** [comment]
@Snugug I'm not here to pick a fight – just to understand and provide what little I have. IMO what you are asking for seems too complex and does not help to automate things. I could be wrong – but I'm failing to see how you would use such a feature generically while keeping it simple and understandable. 
Best to you and the guys – roger out :-)

**Comment by scottkellum** [comment]
For clarity, this is probably more of a toolmakers feature request instead of a site-builder request. There are absolutely solutions for this in projects as @jakob-e points out. As a tool builder we have no idea what your breakpoint configuration and mixins might look like on your projects.

This feature request would allow users of things like Singularity, Modular Scale, Susy, and other tools that behave differently depending on context to manage breakpoints in the way you specify or however else they want to manage breakpoints. It will also dramatically reduce complexity of these tools and their dependencies.

Your solution is solid @jakob-e, no one is arguing against it or suggesting it is a bad solution. The problem is just that not everyone manages their breakpoints this way and that causes problems for us tool makers.

**Comment by jakob-e** [comment]
@scottkellum :-) It may have been (very) unclear from my part – but I also wanted to add the question about mapping to the discussion. If we look at the [Multiple Context Query example](https://github.com/at-import/breakpoint/wiki/Breakpoint-Context): 

``` SCSS
@media (min-width: 700px), (min-width: 900px) and (orientation: landscape), (orientation: portrait) {
   @include tool();
}
```

The amount of handling needed in @mixin tool could be quite heavy - unit conversion, min-max-width ranges, how to handle in combination with orientation, resolution or...   

``` SCSS
@mixin tool() {
    // how to handle ?
    min-width: 700px;    
    orientation: false;     
    min-width: 900px;    
    orientation: landscape;
    min-width: false;
    orientation: portrait;
}
```

My thought was to steer clear of this menace by letting the user declare the relationship between a query and the expected tool output – and using keys seemed a little less verbose compared to queries:

``` SCSS
@mixin tool-media-context-wrap(){
    $value: map-get((
      small : 3
    , medium: 6
    , holy-moly : 187
    ), media-context()); 
    //  Test
   @include tool($value);
}

// If the user prefer to write the queries by hand
//  – I doubt calling tools with a value is a problem
@media (min-width: 700px), (min-width: 900px) and (orientation: landscape), (orientation: portrait) {
   @include tool(187);
}

```

You could also (and this is where I see the feature use case) provide a map to the tool with the media queries and a expected return value. But It still requires the mapping to be made – and I think you would like the user to be in control while keeping your tool simple (as in tool not framework)  

Did it make sense?

**Comment by scottkellum** [comment]
@jakob-e Ah, I am still not quite grokking your examples but, interesting. So you are expecting the output of the proposed `&(media)` or whatever to be a map of `@media` properties?

``` scss
.foo {
  @media (min-width: 20em) and (max-width: 40em) {
    $media: &(media);
  }
}
```

Where `$media` would be a map that looks like:

``` scss
$media: (
  min-width: 20em,
  max-width: 40em
);
```

I really like this, it’s really similar to how Breakpoint works. As a core language feature it may need some tweaking though to support comma separated media lists. This can get super complicated fairly quickly with an example like this:

``` scss
body {
  @media (max-width: 900px), (min-width: 1100px) {
    color: green;
    @media screen, print {
      color: red;
    }
  }
}
```

where you end up with a `@media` context of:

``` scss
@media screen and (max-width: 900px), screen and (min-width: 1100px), print and (max-width: 900px), print and (min-width: 1100px)
```

and your `&(media)` might return a map like:

``` scss
(
  (
    media: screen,
    max-width: 900px,
  ),(
    media: screen,
    min-width: 1100px,
  ),(
    media: print,
    max-width: 900px,
  ),(
    media: print,
    min-width: 1100px,
  ),
);
```

Again, not quite grokking your last post but going line by line for measure:

> The amount of handling needed in @mixin tool could be quite heavy - unit conversion, min-max-width ranges, how to handle in combination with orientation, resolution or...

It could be, but in most cases doesn’t need to be. In most cases just knowing the first `min-width` call in whatever units are specified by the user is more than sufficient. There will likely be a config for the tool itself and assuming the author keeps units the same in both places it is a straightforward process to adapt the tool output for the context.

> My thought was to steer clear of this menace by letting the user declare the relationship between a query and the expected tool output – and using keys seemed a little less verbose compared to queries

We do this already in our tools and it is what I am trying to avoid. Having the user manually insert a value is not usually a problem but it can be a hassle and it is something I would really like to automate. As I said in my last comment this is an elegant solution we can do today to curb this issue and we are doing it everywhere we can. I think we can do better though and I am frustrated by having to tell users how to set up their contexts and breakpoints. This is especially a problem when someone introduces a new tool to an old project where changing how contexts work may be a hassle. Again, I feel like I am going back to my previous argument so I may still be misunderstanding what you are trying to illustrate here.

### A concrete example of what I am trying to solve

I started this issue because I was having trouble applying responsive logic to modular-scale while upholding the install and setup standards I wanted. This is what I want people to do:

``` scss
$ms-ratio: 1.2;
// responsive settings:
$ms-respond: (
  20em: (
    $ms-ratio: 1.3;
  ), 40em: (
    $ms-ratio: 1.5;
  ), 60em: (
    $ms-ratio: 1.62;
  ),
);

@meida (min-width: 42em) {
  .foo {
    // The function knows what the context is so the ratio is 1.5 here
    font-size: ms(1);
  }
}
```

Even if `&(media)` was a string like `&` returns with selectors you could quickly query what a value is like this:

``` scss
$min-width: str-index($media, 'min-width: ');
$str: str-slice($media, $min-width + 11);
$str-end: str-index($str, ')');
$min-width: str-slice($str, 0, $str-end - 1);
```

Then use `>` or `<` logic to find where it is in relation to the tools configuration.

**Comment by jakob-e** [comment]
@scottkellum I think we are talking past each other – so I'll shift to talk about how a context feature could look and work... then someone smarter than me on the inner life of SASS can dismiss the idea :)

This is just a brainstorm - please fill in the blanks 

First I think it should be a introspection like function returning the entire context at the given point of use.
The returned value could be a list of string values (I think this would be the best fit considering the variety of contexts we could encounter)

``` SCSS
@media (max-width:42em){
    // get-context() => "@media (max-width:42em)"
    @media print {
    // get-context() => "@media (max-width:42em)", "@media print"
    }
    .foo {
    // get-context() => "@media (max-width:42em)",  ".foo"
    &:hover {
    // get-context() => "@media (max-width:42em)", ".foo:hover"
    }
    }
    .bar {
    // get-context() => "@media (max-width:42em)", ".bar"
    }
}
```

Calling a function would not change the context 

``` SCSS

@function ms(){ 
//  get-context() => ".foo"  when called form .foo  
//  get-context() => ".bar"  when called form .bar
}
.foo {
    width: ms(1); //  get-context() => ".foo"
}
.bar {
   width: ms(1)  // get-context() => ".bar"
}
```

Called in includes it would return the value at the time of render  

``` SCSS
@mixin menu(){
     // get-context() => "ul"
     li { 
     // get-context() => "ul", "li"
         a { 
             // get-context() => "ul", "li", "a"
             @include menu-link();  
        }
     }
     // get-context() => "ul", "..."  (context of @content structure)
     @content; 
}
@mixin menu-link(){
    // get-context() => "ul", "li", "a"
    &:hover {
        // get-context() => "ul", "li",  "a:hover"
    }
}

ul {
    // get-context() => "ul"
   @include menu(){  ..... }

}

```

Comma separated styles are placed in the same context group  

``` SCSS

.foo, .bar, .doh {
    // get-context() => ".foo, .bar, .doh" 
   &.active {
   // get-context() =>  ".foo.active, .bar.active, doh.active"
   }
   &.active:hover {
   // get-context() => ".foo.active:hover, .bar.active:hover, doh.active:hover"
       span { 
       // get-context() => ".foo.active:hover, .bar.active:hover, doh.active:hover", "span"
       }
   }
} 
```

**Comment by scottkellum** [comment]
@jakob-e You are describing the current behavior of `&` and it already exists: http://sassmeister.com/gist/a31765281413bde89032

I am simply proposing adding media query introspection to this.

**Comment by jakob-e** [comment]
@scottkellum 
& is a parent selector and media does not fit that description. That is why I'm suggesting a  function to   return the full context; directives, parents,...  

``` SCSS

// Example
@media all {
  #main {
    color: black;
    &-sidebar { border: 1px solid; }
  }
}

// Compiles to:
@media all {
  #main {
    color: black;
  }
  #main-sidebar {
    border: 1px solid;
  }
}

```

How would the output look if you add media?

A minor detail about the function I described is the concept of splitting the context into groups – it might come in handy if looking for ".grid" in parent selector only or... 

``` SCSS
".foo.active:hover, .bar.active:hover, doh.active:hover",  "span" 
// vs.
".foo.active:hover span, .bar.active:hover span, .doh.active:hover span"
```

 { creates a separator

you could add functions to handle both cases like get-context-list() and get-context-string() and maybe even a get-context-directive-list()...
