### ISSUE TITLE
[feature request] temporary classes

### ISSUE THREAD

**Issue by albeva** [sass/sass#102]
I would like to be able to generate temporary class selectors that would not be emitted in final css.

``` scss
.!tmp { // notice ! prefix. could be some other notation
    color: red;
}
.foo {
    @extend .tmp;
    background: yellow;
}
.bar {
    @extend .tmp
}
```

would generate following:

``` css
.foo, .bar {
    color: red;
}
.foo {
    background: yellow;
}
```

notice that without .tmp

Use case would be to drop unused css classes that might be generated automatically either my mixins or some external tools.
