### ISSUE TITLE
Any way to remove key/value pairs from a map?

### ISSUE THREAD

**Issue by mirisuzanne** [sass/sass#1032]
For now, I've written my own function as a work-around:

``` scss
@function map-unset(
  $map,
  $keys...
) {
  $return: ();

  @each $key, $value in $map {
    $return: if(index($keys, $key), $return, map-merge($return, ($key: $value)));
  }

  @return $return;
}
```

That seems like something that should be included, though.
