### ISSUE TITLE
Script parent selector interacts poorly with comma selectors

### ISSUE THREAD

**Issue by nex3** [sass/sass#1036]
The following SCSS behaves in a reasonable way:

``` scss
.foo, .bar {
  &.baz {
    a: b;
  }
}
```

It produces:

``` css
.foo.baz, .bar.baz {
  a: b;
}
```

However, when we use `@at-root` and script `&` to do the same thing, it behaves very poorly:

``` scss
.foo, .bar {
  @at-root #{&}.baz {
    a: b;
  }
}
```

It produces:

``` css
.foo, .bar {
  @at-root #{&}.baz {
    a: b;
  }
}
.foo, .bar.baz, .foo, .bar.baz {
  a: b; }
```

This is partly a consequence of the fact that `&` contains the full selector list; for example, in this context it's `((".foo"), (".bar"))` rather than just `(".foo")` or `(".bar")`. However, to fix this we'd need to make `&` "fork" the current rule; if you referred to it in the context of a comma rule, that rule would be split into two, each with `&` referring to one of the complex selectors.

It's possible the current behavior is acceptable, but I'm inclined to think that the different behavior between `&` and `#{&}` in addition to the uselessness of the current behavior in the context of comma selectors indicates that we should change it. In any case, we need to decide _before_ we release 3.3. @chriseppstein, what you think?

See also #1003.

**Comment by chriseppstein** [comment]
I think our current semantics are fine. They should have written

``` scss
.foo, .bar {
  #{append-to-selector(&, ".baz")} {a:b;}
}
```
