### ISSUE TITLE
Problem with repeated selectors in output.

### ISSUE THREAD

**Issue by kfalkiewicz** [sass/sass#1038]
Hi
Few days ago I found this interesting issue in sass - pre, and in stable version.
When I tried to change margin on few elements already styled I found that Sass compiles this rule:

``` SCSS
article > header + .element,
article > header + .element + .element,
article > header + .element2,
article > header + .element2 + .element2 {
  margin-top: 10px;
}
```

to this:

``` CSS
article > header + .element,
article > header + .element + .element,
article > header + .element2,
article > header + .element,
article > header + .element2 + .element2,
article > header + .element + .element2,
article > header + .element2 + .element,
article > header + .element + .element {
  margin-top: 10px;
}
```

As you see, some selectors are repeated and some shouldn't even be created. Tried and repeated this thing on codepen.io also:
http://codepen.io/anon/pen/LFHcI

**Comment by lolmaus** [comment]
That's how extends work in Sass. See http://blackfalcon.roughdraft.io/4693231 for explanations.

My rule of thumb: never extend real selectors, only extend silent selectors.

**Comment by kfalkiewicz** [comment]
Ok thx, but why something like this happens when I do only this ?:
SCSS:

``` SCSS
article > header + .element2,
article > header + .element2 + .element2 {
  margin-top: 10px;
}
```

CSS:

``` CSS
article > header + .element2,
article > header + .element,
article > header + .element2 + .element2,
article > header + .element + .element2,
article > header + .element2 + .element,
article > header + .element + .element {
  margin-top: 10px;
}
```
