### ISSUE TITLE
SASS: RegExp buffer overflow when parsing Sencha Touch's apple.css

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#104]
[Originally filed](https://github.com/nex3/haml/issues/373) against haml by @sylvinus and commented on by @LayerDownInc & @matthewee.

css/apple.css from Sencha Touch 1.1 (wasn't happening with 1.0)

latest sass

```
sylvain-zimmers-macbook-pro-2:sencha-touch sylvinus$ sass --scss --trace apple.css 
/Library/Ruby/Gems/1.8/gems/haml-3.0.24/bin/../lib/haml/../sass/scss/parser.rb:842:in `scan': regexp buffer overflow (StringScanner::Error)
    from /Library/Ruby/Gems/1.8/gems/haml-3.0.24/bin/../lib/haml/../sass/scss/parser.rb:842:in `tok'
    from /Library/Ruby/Gems/1.8/gems/haml-3.0.24/bin/../lib/haml/../sass/scss/parser.rb:410:in `selector_sequence'
    from /Library/Ruby/Gems/1.8/gems/haml-3.0.24/bin/../lib/haml/../sass/scss/parser.rb:332:in `ruleset'
    from /Library/Ruby/Gems/1.8/gems/haml-3.0.24/bin/../lib/haml/../sass/scss/parser.rb:356:in `block_child'
    from /Library/Ruby/Gems/1.8/gems/haml-3.0.24/bin/../lib/haml/../sass/scss/parser.rb:350:in `block_contents'
    from /Library/Ruby/Gems/1.8/gems/haml-3.0.24/bin/../lib/haml/../sass/scss/parser.rb:57:in `stylesheet'
    from /Library/Ruby/Gems/1.8/gems/haml-3.0.24/bin/../lib/haml/../sass/scss/parser.rb:26:in `parse'
    from /Library/Ruby/Gems/1.8/gems/haml-3.0.24/bin/../lib/haml/../sass/engine.rb:213:in `_to_tree'
    from /Library/Ruby/Gems/1.8/gems/haml-3.0.24/bin/../lib/haml/../sass/engine.rb:178:in `to_tree'
    from /Library/Ruby/Gems/1.8/gems/haml-3.0.24/bin/../lib/haml/../sass/files.rb:44:in `tree_for'
    from /Library/Ruby/Gems/1.8/gems/haml-3.0.24/bin/../lib/haml/exec.rb:370:in `process_result'
    from /Library/Ruby/Gems/1.8/gems/haml-3.0.24/bin/../lib/haml/exec.rb:41:in `parse'
    from /Library/Ruby/Gems/1.8/gems/haml-3.0.24/bin/../lib/haml/exec.rb:21:in `parse!'
    from /Library/Ruby/Gems/1.8/gems/haml-3.0.24/bin/sass:8
    from /usr/bin/sass:19:in `load'
    from /usr/bin/sass:19
```

**Comment by helloluis** [comment]
Don't know if this helps, but I get a similar error error while trying to run "compass watch" against our scss files with very long selectors, but only on Ruby 1.8.7. It seems to work fine when rvm-ing Ruby 1.9.2+.

StringScanner::Error on line 906 of /Library/Ruby/Gems/1.8/gems/sass-3.1.7/lib/sass/../sass/scss/parser.rb: regexp buffer overflow

**Comment by hgmnz** [comment]
I came across this after I upgraded to rails 3.1, on ruby 1.8.7. Details on this gist: https://gist.github.com/306f9ab406ab98649073

**Comment by webmat** [comment]
By the way, the same happens when trying to compile jQuery Mobile's CSS (using Ruby 1.8.7).

**Comment by webmat** [comment]
Let me take that back. jQuery Mobile's CSS goes through just fine with Sprockets on ruby 1.8.7.

I traced the source of the exception to two problems I had in my SCSS:
- I had a missing closing curly brace somewhere in a nested block;
- I had an "@extend .stylename" where ".stylename" was not defined anywhere at the top level, but was defined nested under other selectors. Creating a top level style with that selector didn't fix the issue, though. So I just removed the extend and the problem went away.

I hope this helps someone else figure out their version of this problem.

**Comment by redexp** [comment]
when I convert large css file on ubuntu with Sass 3.0.9 and ruby1.8 (1.8.7.299-2) I get same error, but on win7 with Sass 3.1.7 and ruby 1.9.2p290 everything is ok

Probably it's not because of ubuntu, just because on win I have newer ruby 1.9 and Sass 3.1.7

**Comment by webmat** [comment]
Ok, this is getting weird. I've tracked my instance of the problem further, since it kept happening again.

Our designer created the following style:

```
@font-face { font-family: "Univers"; src: $univers_font-url; }
.w_univers_font { font-family: "Univers", sans-serif; letter-spacing: 0.05em; }
```

This style has been problematic every once in a while. It's reused with `@extend .w_univers_font` in a few places but in some specific instances it fails.

Here's a few examples with dummy selectors (I've actually tried them as is)

```
.class1 .class2.class3 { @extend .w_univers_font }  // => fails
.class1 .class2        { @extend .w_univers_font }  // => works!
.class1 .class2.class3 { @extend .univers_font }  // => works!!1 (provided I rename my reuseable selector to .univers_font)
```

I've no idea if it's something that can be fixed to work on Ruby 1.8.7. I hope this helps SASS contributors track down this issue!

**Comment by a-chernykh** [comment]
Experiencing the same problem with '@extend' - assets:precompile fails with 'regexp buffer overflow' in unpredictable place.

**Comment by stevenklein** [comment]
Just experienced the same problem.

Problem:
font-family: Helvetica Neue", Helvetica, Arial;

Notice the missing " from before Helvetica Neue". If a quote is missing, it's like have a ridiculously long string that the regexp parser chokes on.

**Comment by kranzky** [comment]
We're hitting this on Rails 3.1.1 / Ruby 1.8.7 when running "rake assets:precompile"

**Comment by kranzky** [comment]
For us, the problem is that Sass::SCSS::RX::STATIC_SELECTOR fails on a long selector (with Rails 3.1.1 / Ruby 1.8.7). I can replicate the problem with this scss file:

``` scss
.aaa {
  background-color: white;
}
.aaa .aaa .aaa {
  background-color: black;
}   
.bbb {
  @extend .aaa;
} 
.xxx {
  @extend .bbb;
}
.yyy {
  @extend .bbb;
}
.zzz {
  @extend .bbb;
}
```

Running `rake assets:precompile` on this results in the following css being generated:

``` css
.aaa .aaa .aaa, .bbb .aaa .aaa, .xxx .aaa .aaa, .yyy .aaa .aaa, .zzz .aaa .aaa, .aaa .bbb .aaa, .bbb .bbb .aaa, .xxx .bbb .aaa, .yyy .bbb .aaa, .zzz .bbb .aaa, .aaa .xxx .aaa, .bbb .xxx .aaa, .xxx .xxx .aaa, .yyy .xxx .aaa, .zzz .xxx .aaa, .aaa .yyy .aaa, .bbb .yyy .aaa, .xxx .yyy .aaa, .yyy .yyy .aaa, .zzz .yyy .aaa, .aaa .zzz .aaa, .bbb .zzz .aaa, .xxx .zzz .aaa, .yyy .zzz .aaa, .zzz .zzz .aaa, .aaa .aaa .bbb, .bbb .aaa .bbb, .xxx .aaa .bbb, .yyy .aaa .bbb, .zzz .aaa .bbb, .aaa .bbb .bbb, .bbb .bbb .bbb, .xxx .bbb .bbb, .yyy .bbb .bbb, .zzz .bbb .bbb, .aaa .xxx .bbb, .bbb .xxx .bbb, .xxx .xxx .bbb, .yyy .xxx .bbb, .zzz .xxx .bbb, .aaa .yyy .bbb, .bbb .yyy .bbb, .xxx .yyy .bbb, .yyy .yyy .bbb, .zzz .yyy .bbb, .aaa .zzz .bbb, .bbb .zzz .bbb, .xxx .zzz .bbb, .yyy .zzz .bbb, .zzz .zzz .bbb, .aaa .aaa .xxx, .bbb .aaa .xxx, .xxx .aaa .xxx, .yyy .aaa .xxx, .zzz .aaa .xxx, .aaa .bbb .xxx, .bbb .bbb .xxx, .xxx .bbb .xxx, .yyy .bbb .xxx, .zzz .bbb .xxx, .aaa .xxx .xxx, .bbb .xxx .xxx, .xxx .xxx .xxx, .yyy .xxx .xxx, .zzz .xxx .xxx, .aaa .yyy .xxx, .bbb .yyy .xxx, .xxx .yyy .xxx, .yyy .yyy .xxx, .zzz .yyy .xxx, .aaa .zzz .xxx, .bbb .zzz .xxx, .xxx .zzz .xxx, .yyy .zzz .xxx, .zzz .zzz .xxx, .aaa .aaa .yyy, .bbb .aaa .yyy, .xxx .aaa .yyy, .yyy .aaa .yyy, .zzz .aaa .yyy, .aaa .bbb .yyy, .bbb .bbb .yyy, .xxx .bbb .yyy, .yyy .bbb .yyy, .zzz .bbb .yyy, .aaa .xxx .yyy, .bbb .xxx .yyy, .xxx .xxx .yyy, .yyy .xxx .yyy, .zzz .xxx .yyy, .aaa .yyy .yyy, .bbb .yyy .yyy, .xxx .yyy .yyy, .yyy .yyy .yyy, .zzz .yyy .yyy, .aaa .zzz .yyy, .bbb .zzz .yyy, .xxx .zzz .yyy, .yyy .zzz .yyy, .zzz .zzz .yyy, .aaa .aaa .zzz, .bbb .aaa .zzz, .xxx .aaa .zzz, .yyy .aaa .zzz, .zzz .aaa .zzz, .aaa .bbb .zzz, .bbb .bbb .zzz, .xxx .bbb .zzz, .yyy .bbb .zzz, .zzz .bbb .zzz, .aaa .xxx .zzz, .bbb .xxx .zzz, .xxx .xxx .zzz, .yyy .xxx .zzz, .zzz .xxx .zzz, .aaa .yyy .zzz, .bbb .yyy .zzz, .xxx .yyy .zzz, .yyy .yyy .zzz, .zzz .yyy .zzz, .aaa .zzz .zzz, .bbb .zzz .zzz, .xxx .zzz .zzz, .yyy .zzz .zzz, .zzz .zzz .zzz {
  background-color: black;
}
```

Clearly, the `.aaa .aaa .aaa` selector has been expanded to all possibilities according to the dependency hierarchy:

```
.aaa
|
+- .bbb
    |
    +- .xxx
    |
    +- .yyy
    |
    +- .zzz
```

This selector is long enough to cause the exception.  This explains why some people are hitting this problem at unpredictable places. Adding a new selector that extends an existing selector may be enough, if the parent is also extended from elsewhere. This is basically how we hit the bug (we essentially added `zzz` to the existing hierarchy).

The exception itself occurs because `STATIC_SELECTOR` uses the `(?=[{])` syntax to match on `{` without consuming it. For example, the following code prints `5460` on my machine (using Ruby 1.8.7):

``` ruby
REGEX = /.*(?=[x])/
(0..10_000_000).each do |i|
  begin
    REGEX.match("a" * i + "x")
  rescue RegexpError => e
    puts i ; break
  end
end
```

Removing the `?=` from `REGEX`, or using Ruby 1.9.x instead of Ruby 1.8.7, fixes things; even a string `10000001` characters long will be matched. So this bottoms out at what was presumably a bug in Ruby core.

The fix for Ruby 1.8.7, then (apart from [not parsing with regexes](http://www.faqoverflow.com/stackoverflow/1732348.html)), is to remove the `?=` from `STATIC_SELECTOR`. This isn't too difficult, as it is only ever used at the very end of a Regexp.

Here's one I prepared earlier: https://github.com/nex3/sass/pull/219
