### ISSUE TITLE
@extend doesn't work with pseudoclassed values

### ISSUE THREAD

**Issue by ghost** [sass/sass#1046]
``` scss
.color1 {
    color: red;
}
.color2 {
    color: blue;
}

.color1 .color2 {
    @extend .color2;
}

.color2 .color1 {
    @extend .color1;
}

a {
    .color1 & { color: red; }
    .color2 & { color: blue; }
    .color1 &:hover { color: green; }
    .color2 &:hover { color: yellow; }
}
```

Outputs:

``` css
.color1, .color2 .color1 {
  color: red; }

.color2, .color1 .color2 {
  color: blue; }

.color1 a, .color2 .color1 a {
  color: red; }
.color2 a, .color1 .color2 a {
  color: blue; }
.color1 a:hover {
  color: green; }
.color2 a:hover {
  color: yellow; }
```

And as you can see, rules for `.color1 .color2 a:hover` and `.color2 .color1 a:hover` are missing.
