### ISSUE TITLE
@extend descendant permutations

### ISSUE THREAD

**Issue by ghost** [sass/sass#1052]
## Intro

I declare some simple `@extend`-only selectors:

``` scss
%abstract-a { name: "abstract-a"; }
%abstract-b { name: "abstract-b"; }
```

Then I `@extend` them accordingly:

``` scss
.concrete-1 { @extend %abstract-a; }
.concrete-2 { @extend %abstract-b; }
.concrete-3 { @extend %abstract-b; }
```

Now, I noticed that when you nest a previously declared `@extend`-only selector, it compiles nicely:

``` scss
.container {
    %abstract-a { modified: "abstract-a in container"; }
    %abstract-b { modified: "abstract-b in container"; }
}
```

Will compile to:

``` css
.concrete-1 { name: "abstract-a"; }

.concrete-2, .concrete-3 { name: "abstract-b"; }

.container .concrete-1 { modified: "abstract-a in container"; }

.container .concrete-2,
.container .concrete-3 { modified: "abstract-b in container"; }
```

Which is great! Rather than rely on the implementations, I can rely on the abstractions, and the compiled CSS respects this containing all declared concretions as descendants of the container.
## Issue

However, if when declaring the concretions you also define descendant structure:

``` scss
.concrete-1 { 
    @extend %abstract-a; 
    .concrete-2 { @extend %abstract-b; }
    .concrete-3 { @extend %abstract-b; }
}
```

Everything kinda goes sour:

``` css
.concrete-1 { name: "abstract-a"; }

.concrete-1 .concrete-2,
.concrete-1 .concrete-3 { name: "abstract-b"; }

.container .concrete-1 { modified: "abstract-a in container"; }

/* here be the problem */
.container .concrete-1 .concrete-2,
.concrete-1 .container .concrete-2,
.container .concrete-1 .concrete-3,
.concrete-1 .container .concrete-3 { modified: "abstract-b in container"; }
```

The problem here is that it compiles various permutations of the descendants of `.container`. This _bloats_ the CSS unnecessarily, since the intent was:

``` css
.container .concrete-1 .concrete-2 { ... }
```

But not:

``` css
.concrete-1 .container .concrete-2 { ... }
```

The resulting CSS will still "work" when used, but can easily get out of hand with respect to the selector lists generated, especially given the fact that `@extend` can get out of hand if you're not careful anyway.

Now, I suspect this is essentially the same "expected behavior" as described by @chriseppstein in his gist https://gist.github.com/chriseppstein/6114279 (except that this doesn't involve the parent selector `&`, I don't know if that was relevant to the question that prompted the gist)

Anyway, I think it would be more sensible that this be controlled with a flag or similar mechanism, provided this is possible at all. Based on the gist, it sounds like the extraneous selectors are being purposefully generated, so it'd be nice to see that made optional. Whether such a flag should be inline or global, I'm not sure.
### SCSS

``` scss
%abstract-a { name: "abstract-a"; }
%abstract-b { name: "abstract-b"; }

.concrete-1 { 
    @extend %abstract-a; 
    .concrete-2 { @extend %abstract-b; }
    .concrete-3 { @extend %abstract-b; }
}

.container {
    %abstract-a { modified: "abstract-a in container"; }
    %abstract-b { modified: "abstract-b in container"; }
}
```
### Expected Output

``` css
.concrete-1 { name: "abstract-a"; }

.concrete-1 .concrete-2, 
.concrete-1 .concrete-3 { name: "abstract-b"; }

.container .concrete-1 { modified: "abstract-a in container"; }

.container .concrete-1 .concrete-2, 
.container .concrete-1 .concrete-3 { modified: "abstract-b in container"; }
```
### Actual Output

``` css
.concrete-1 { name: "abstract-a"; }

.concrete-1 .concrete-2, 
.concrete-1 .concrete-3 { name: "abstract-b"; }

.container .concrete-1 { modified: "abstract-a in container"; }

.container .concrete-1 .concrete-2, 
.concrete-1 .container .concrete-2, 
.container .concrete-1 .concrete-3, 
.concrete-1 .container .concrete-3 { modified: "abstract-b in container"; }
```
