### ISSUE TITLE
breaks slash (Sass 3.3.0.rc.2 (Maptastic Maple))

### ISSUE THREAD

**Issue by span88** [sass/sass#1056]
``` scss
@media secreen and (-o-min-device-pixel-ratio: #{$ratio}/1),
    secreen and (-o-min-device-pixel-ratio: #{$ratio}/#{1}),
    secreen and (-o-min-device-pixel-ratio: unquote('#{$ratio}/1')),
    secreen and (-o-min-device-pixel-ratio: '#{$ratio}'+'/'+'1') {
        color: red
}
```

compile

``` css
@media secreen and (-o-min-device-pixel-ratio: 1.3 / 1),
secreen and (-o-min-device-pixel-ratio: 1.3 / 1),
secreen and (-o-min-device-pixel-ratio: 1.3 / 1),
secreen and (-o-min-device-pixel-ratio: 1.3 / 1) {
  .widget {
    color: red;
  }
}
```

**Comment by Snugug** [comment]
I'm sorry, what is the question here?

I assume it is that  you need a fraction and that it's printing out the division? If that's the case, unfortunately it's a case of pre-Blink Opera deciding to go against the trend of all other implementors and the W3C itself and requiring `o-dpr` to be a string as opposed to a number, not an issue with Sass. When you write `1.3 / 1`, as pointed out by @nex3 in #1030, Sass assumes that a space followed by a mathematical operation followed by a space should, in fact, be a mathematical operation. When working in pre-processed land, that is the most logical thing to do. The answer is to simply print it out as a string.

If, on the other hand, the issue is that Sass should be smart enough to know you meant a fraction there and only there, I'm afraid you're going to be out of luck as A) that version of Opera's device pixel ratio feature doesn't exist in stable Opera any more and is actively being depreciated and B) Sass has a fairly strict rule of being blind to browser-specific problems and implementations in order to best be future friendly.

**Comment by span88** [comment]
> The answer is to simply print it out as a string.

``` scss
@media screen and (min-width: '0\0') {
    .widget {
        color:red;
    }
}
```

``` css
@media screen and (min-width: 0 \0) {
  .widget {
    color: red;
  }
}
```
