### ISSUE TITLE
`str-index` should return `null` for a non-existent element rather than `0`

### ISSUE THREAD

**Issue by mirisuzanne** [sass/sass#1060]
Shouldn't both be `false`?

``` scss
// input
.test {
  index: index(one two three, four);
  str-index: str-index('one two three', 'four');
}

// output
.test {
  index: false;
  str-index: 0;
}
```
