### ISSUE TITLE
Support passing single @content block to multiple mixins

### ISSUE THREAD

**Issue by borodean** [sass/sass#1065]
Here is what I mean:

``` scss
@include roses-are-red,
@include violets-are-blue {
  font-size: 14px;
}
```

I came up with this idea while working on styling for rich texts for my projects. I've needed same styles to be applied on each element like this:

``` css
.rich h2,
.rich_h2 {
  font-size: 24px;
}

.rich p,
.rich_p {
  margin-bottom: 12px;
}
```

so I can format things two ways, 1) using a wrapper:

``` haml
.rich
  %h2 Le heading
  %p A kingdom for a horse!
```

2) or targeting exact elements without affecting it's siblings:

``` haml
%h2.rich_h2
```

What I've did is a mixin to simplify writing selectors for it which works like this:

``` scss
@include rich-selector(h1, h2, h3) {
  line-height: 1.1;
}
// Outputs to:
// .rich h1, .rich h2, .rich h3, .rich_h1, .rich_h2, .rich_h3 {
//   line-height: 1.1;
// }
```

What I've wanted to do is not to over-bloat includes with arguments, but have multiple includes on separate lines having the same block passed to them -- as I've shown on the first code example.

**Comment by lolmaus** [comment]
This will be extremely helpful. For example, with media query helpers:

``` css
@include 'breakpoint-slicer';
@include at(1), between(3,4) {
  color: pink;
}
```

**Comment by chriseppstein** [comment]
You can accomplish this by passing a content block to other mixins. Example:

``` scss
@mixin  combinator($mixin1-arg1, $mixin1-arg2, $mixin2-arg1, $mixin2-arg2) {
  @include mixin1($mixin1-arg1, $mixin1-arg2) { @content }
  @include mixin2($mixin2-arg1, $mixin2-arg2) { @content }
}
```

**Comment by lolmaus** [comment]
As long as Sass does not allow interpolating mixin names, your workaround suggestion is extremely inconvenient to use.

But even if it were possible to interpolate, the suggestion is still very reasonable.

Please reopen.

**Comment by cjcenizal** [comment]
I have to agree with @lolmaus, this feature would be extremely convenient and seems to be consistent with the current syntax.

**Comment by nilssolanki** [comment]
Yes, this is still very relevant. My use-case: I want to show something either on hover or always when on a touch device. For both of the cases, I have a mixin:

```scss
.elem {
  opacity: 0.5;

  @include has-focus,
  @include has-touch {
    opacity: 1;
  }
}
```

Of course this is a minimal example and my real world use-cases are a lot more complex.
