### ISSUE TITLE
Using & with !global

### ISSUE THREAD

**Issue by airen** [sass/sass#1068]
I wrote such a use case with `&` and `!global`:

```
.block {
    $selector: & !global;
}
.view {
    $selector: & !global;
}

#{$selector}--element {
    color: green;
}
```

but compiled：

```
.view--element {
  color: green; 
}
```

and i wrote it like this:

```
.block,
.view {
    $selector: & !global;
}

#{$selector}--element {
    color: green;
}
```

then compiled ：

```
.block, .view--element {
  color: green; 
}
```

but i want need like this:

```
.block-element{...}
.view-element{...}
```

who can help me, tell me why?

**Comment by lolmaus** [comment]
When `&` is interpolated, it becomes a string.

When you do `#{$selector}--element`, you basically ask to concatenate `.block, .view` with `--element`, which results in `.block, .view--element`.

There's no simple way to do what you want. But if you don't mind another level of complexity in your stylesheets, consider iterating through `&`'s elements:

``` css
.foo, .bar {
  $selectors: & !global;
}

@each $selector in $selectors {
  #{$selector}--baz {
    color: pink;
  }
}
```

Result:

``` css
.foo--baz {
  color: pink; }

.bar--baz {
  color: pink; }
```

Why are you doing this in the first place?
