### ISSUE TITLE
Postfix loops and conditions

### ISSUE THREAD

**Issue by borodean** [sass/sass#1069]
Can find any existing proposal for this.

``` scss
.foobar {
  color: red !if $type == blood;
  #{$param}-color: green !each $param in border, background;
}
```

To be honest, I easily can't find such a simple use cases for `!for` and `!while`, but I suppose those can find their use in some kind of complex mixins.

**Comment by lolmaus** [comment]
Nice syntactic sugar suggestion.

Sass maintainers are very conservative and will almost surely turn this down.

**Comment by borodean** [comment]
Yes, I know about conservatism of nex3, and that, to be honest, is the thing I love in Sass. But I feel that proposed syntax is following closely the existing CSS standards and thus can be called considered conservative too: in CSS we have one (and the only) postfix operator called `!important`. Won't it be an accurate thing to extend that uncultivated field in an cautious manner?

**Comment by lolmaus** [comment]
There's currently a discussion on changing the internal structure of `!important`: #1040. You should probably join the discussion.

**Comment by cimmanon** [comment]
Sass already has syntactic sugar for your first example:

``` scss
$type: blood;

.foobar {
  color: if($type == blood, null, red);
}
```

Just because you can smush it all onto one line doesn't make it better or more readable:

``` scss
.foobar {
  @each $param in border, background { #{$param}-color: green; }
}
```
