### ISSUE TITLE
Is it posible to output sass variable as row css code ?

### ISSUE THREAD

**Issue by muxahuk** [sass/sass#1085]
for ex. i have `$var: 'body { color: black; }';`
can i somehow output `$var` in my style.css file ?

If yes than how ?
If no than may be there's some othere solution do accomplish that ?

Originaly i want to add all media query css code to a variable and then output it at the end of file..
something like:

``` scss
$var: '' !default;

$var: #{$var} + 'body{ color: black; }';

$var: #{$var} + 'a{ color: blue; }';

@media screen and ( min-width: 480px ) {
  // Do something with $var so that it outputs here
}
```

and i get css:

``` css
@media screen and ( min-width: 480px ) {
  body{ color: black; }a{ color: blue; }
}
```

**Comment by nex3** [comment]
No, it's not. You can't use variables to alter the structure of the document.

**Comment by muxahuk** [comment]
I'm now thinking about creating global variable that will contain sizes ( as list ) and each size vill contain tags (as list ) and each tag will contain property - value ( as lists ) and than will output everithing at the end ))

**Comment by lolmaus** [comment]
It is recommenthatded that you don't group your code by media queries. Instead, add a new media query where necessary and group your code by modules (e. g. page footer) and use cases (e. g. typography). Gzip handles duplicate media queries well, producing minimal increase in size.

Also be aware of media query bubbling. It is an awesome feature of Sass that lets you use media queries inside declarations.

This Sass:

``` sass
.element
  foo: bar

  @media (min-width: 400px)
    baz: quux
```

results in this CSS:

``` css
.element {
  foo: bar;
}
@media (min-width: 400px) {
  .element {
    baz: quux;
  }
}
```

Also, consider using a Sass library to make reusing media queries effortless. Have a look at [Breakpoint](http://breakpoint-sass.com/) and [Breakpoint Slicer](https://github.com/lolmaus/breakpoint-slicer/).

**Comment by muxahuk** [comment]
Yes, i know about `@medi` befavior, but for some reason i'm thinking how to group these..
I have thought about creating come extra to sass ( on ruby ), but i need to learn it first )))
the thing is that i will try to do will looke something like:

``` scss
// first we create some partial mixin
@mixin %partialmixin( $vars ) {
/// doing something
}

// then we add it to elements for ex.
// Wen we apply it it remembers it somehow
.col-1 {
width: 100%;
@include %partialmixin( tablet ){
 width: 50%;
};
@include %partialmixin( pc ){
 width: 25%;
};
}

.col-2 {
width: 50%;
@include %partialmixin( tablet ){
 width: 33%;
};
@include %partialmixin( pc ){
 width: 15%;
};
}

// And in these situation it echoes out the code that is crouped
@import %partialmixin;

```

And expected output will be ( with modefied partialmixin )

``` css
.col-1 {
width: 100%;
}
.col-2 {
width: 50%;
}

@media screen and (min-width: 480px ) {
.col-1 {
width: 50%;
}
.col-2 {
width: 33%;
}
}

@media screen and (min-width: 1000px ) {
.col-1 {
width: 25%;
}
.col-2 {
width: 15%;
}
}
```

Of course something like these i can't write right now, i don't have much knowlage, but may be in future )) or if someone likes that idea will already be done in future ))

**Comment by lolmaus** [comment]
There's an issue for automatic media query grouping: #116. Unfortunately, Sass devs are not going to implement it yet, because it's a very non-trivial thing to do and probably has no algorithmic solution.

But i like the idea that you store styles in a buffer and then output it.

My take:

``` scss
@memorize foo {
  color: red;
  a {
    text-decoration: underline;
  }
}

section {
  @memorize foo {
    background-color: purple;
  }
}

header {
  font-weight: bold;
  @recall foo;
}
```

Resulting CSS:

``` css
header {
  font-weight: bold;
  color: red;
}

header a {
  text-decoration: underline;
}

header section {
  background-color: purple;
}
```

I wonder whether there's an issue ticket for that already.
