### ISSUE TITLE
Compressed CSS output incorrectly converts named colours to hexcodes in selectors when written via a mixin

### ISSUE THREAD

**Issue by stowball** [sass/sass#1095]
I created a mixin that takes a series of colours as a list, iterates over them and outputs them as a class name with some rules. In compressed mode, this doesn't work.

I've put a live gist in Sassmeister here: http://sassmeister.com/gist/8704754

But, to describe it. The following code:

``` scss
@mixin colors-with-prefix($names...) {
  @for $i from 0 to length($names) {
    .color-#{nth($names, $i + 1)} {
      foo: bar;
    }
  }
}

@include colors-with-prefix(black, white, almond);
```

outputs:

``` css
.color-#000{foo:bar}.color-#fff{foo:bar}.color-almond{foo:bar}
```

Even worse, this code:

``` scss
@mixin colors-without-prefix($names...) {
  @for $i from 0 to length($names) {
    .#{nth($names, $i + 1)} {
      foo: bar;
    }
  }
}

@include colors-without-prefix(black, white, almond);
```

Simply errors with:

```
Invalid CSS after ".": expected class name, was "#000"
```

Using any of the other CSS output methods works as expected.

A workaround is to pass each value in as quoted strings.
