### ISSUE TITLE
sass-convert changes mixin parameter names 

### ISSUE THREAD

**Issue by badsyntax** [sass/sass#1096]
Hi there.

This issue was identified and replicated using sass 3.2.14.

I have the following sass in a file test.scss:

``` scss
@mixin fancy-mixin($max-width: 100%) {
  max-width: $max-width;
}
.hello {
  @include fancy-mixin($max-width: 200px);
}
```

I then use sass-convert on that sass:

``` shell
sass-convert test.scss --to scss
```

...and it outputs:

``` scss
@mixin fancy-mixin($max-width: 100%) {
  max-width: $max-width;
}

.hello {
  @include fancy-mixin($max_width: 200px);
}
```

Notice the parameter name when calling fancy-mixin changes from `$max-width` to `$max_width`.
