### ISSUE TITLE
Root properties automaticlly positioned at top, is this intended/configurable?

### ISSUE THREAD

**Issue by DracoBlue** [sass/sass#1098]
Hello,

we have scss code looking like this (input):

``` scss
.b-header {

  @media print {
    background-color: #ff0;
  }

  background-color: #fff;
}
```

Output:

``` css
.b-header {
  background-color: #fff;
}
@media print {
  .b-header {
    background-color: #ff0;
  }
}
```

Since sass(?) automatically "fixes" the order, the background-color for print media is working.

Is this behavior intended? I would expect sass to keep the order in the same way, like it was in the initial css source code.

```
$ sass --version
Sass 3.3.0.rc.2 (Maptastic Maple)
```

PS:

It does not work for child nodes:

``` scss
.b-header {

  @media print {
    background-color: #ff0;

    a {
      color: #ff0;
    }
  }

  background-color: #fff;

  a {
    color: #fff;
  }
}
```

becomes:

``` css
.b-header {
  background-color: #fff;
}
@media print {
  .b-header {
    background-color: #ff0;
  }
  .b-header a {
    color: #ff0;
  }
}
.b-header a {
  color: #fff;
}
```

PPS: My current workaround is this:

``` scss
.b-header {

  @media print {
    background-color: #ff0;

    a {
      color: #ff0;
    }
  }
}

.b-header {
  background-color: #fff;

  a {
    color: #fff;
  }
}
```

**Comment by cimmanon** [comment]
I understand that from a user expectation standpoint, that the output is confusing.  But from an authoring standpoint, there's no benefit to having output like this:

``` css
@media print {
  .b-header {
    background-color: #ff0;
  }
}
.b-header {
  background-color: #fff;
}
```

Adding a media query doesn't change the specificity of the selector, so the contents of your media query will never, ever apply (nope, not even if you're printing the page).

**Comment by nex3** [comment]
We do this because we don't want to make more top-level rules than are necessary. Consider the following SCSS:

``` scss
.parent {
  a: b;
  .child {x: y}
  c: d;
}
```

If we preserved the order of properties relative to nested rules, this would have to be compiled to

``` css
.parent {
  a: b;
}
.parent .child {
  x: y;
}
.parent {
  c: d;
}
```

Duplicating `.parent` here sucks, especially if it's replaced by a much larger selector. To avoid having to do so, we move all the properties in a rule above any nested rules.
