### ISSUE TITLE
Can't extend, if I import a sass file from within a class, because class is written twice in output... and again

### ISSUE THREAD

**Issue by donaldpipowitch** [sass/sass#1101]
I have the following two sass files.

```
// fileA.scss
.test-hello {
  color: red;
}

.test-world {
  @extend .test-hello;
}
```

```
// fileB.scss
.theme {
   @import "fileA";
}
```

What I would expect, if I compile `fileB.scss`:

```
.theme .test-hello,
.theme .test-world {
  color: red;
}
```

What I get:

```
.theme .test-hello,
.theme .theme .test-world,
.theme .theme .test-world {
  color: red;
}
```

**Comment by cimmanon** [comment]
I'm running 3.3.0.rc.2 (Maptastic Maple) and I get your expected results:

``` css
/* line 1, ../sass/_foo.scss */
.theme .test-hello, .theme .test-world {
  color: red;
}
```
