### ISSUE TITLE
Comments are removed when found between selector strings

### ISSUE THREAD

**Issue by badsyntax** [sass/sass#1104]
Hi there.

I can replicate this issue using Sass 3.2.14.

Let's say I have the following CSS in a file:

``` css
/* Cat */
.cat,
/* Dog */
.dog {
    color: red;
}
```

.. I then use sass-convert on that file to convert to Scss: `sass-convert --to scss test.css`

And it generates the following Scss:

``` scss
/* Cat */

.cat, .dog {
  color: red;
}
```

A more simple test case would be (in css): 

``` css
.cat /* this is a cat */ {
    color: red;
}
```

Comments are removed if found between selectors and the rules. (This is not limited to sass-convert, if i have the same style comments in a sass file, and compile that sass file. the comments are removed in the same manner).

I can appreciate the difficulty in converting the CSS selectors and keeping comments in place. If the selectors change (which is certainly possible, sass-convert could decide to nest selectors), then it can be difficult (perhaps impractical?) to try keep comments like this next to the relevant selectors. So I can totally understand if this a "wont fix" issue, but I thought I would try get some feedback if there are plans to fix this. 

Thanks.
