### ISSUE TITLE
Regression in hyphens when used in property lists

### ISSUE THREAD

**Issue by xzyfer** [sass/sass#1105]
I understand there has been a lot of talk about unintuitive hyphen behaviour recently (#1030, #1023, #853) but I feel like this a regression since `inset -1.5em 0 1.5em -0.75em rgba(0, 0, 0, 0.25)` is a valid css value. Needing to throw in extra `()`s to please sass is very unintuitive. Requiring the extra `()`s makes however make sense if variables were involved.

``` scss
// source.scss
a {
  box-shadow: inset -1.5em 0 1.5em -0.75em rgba(0, 0, 0, 0.25);
}
```

Output from 3.3.0rc2

``` scss
a {
  box-shadow: inset -1.5em 0 1.5em -0.75em rgba(0, 0, 0, 0.25);
}
```

Output from master 3.3.0_980eece359

``` scss
a {
  box-shadow: inset-1.5em 0 0.75em rgba(0, 0, 0, 0.25);
}
```

The space between `inset` and `-1.5em` has been removed, and  `1.5em -0.75em` has been turned into `0.75em`.
