### ISSUE TITLE
[Regression] `inspect` fails for lists containing empty lists

### ISSUE THREAD

**Issue by FWeinb** [sass/sass#1109]
In Sass 3.3.0.rc.3 `inspect` dosen't work for lists containing empty lists. It's working in 3.2.14 (inspect just drops the empty list)

See http://sassmeister.com/gist/8911262

**Comment by lunelson** [comment]
+1 ran across this today too; throws sass 3.3.rc3 in to a loop, at least on sassmeister:

``` scss
.test {
  output: inspect( alpha( beta ( gamma () ) ) );
}
```
