### ISSUE TITLE
Sass treats `_` and `-` in variable name are same?

### ISSUE THREAD

**Issue by hail2u** [sass/sass#1114]
The following code should return a compile error, “Undefined variable: "$foo_bar". (Sass::SyntaxError)”:

``` scss
$foo-bar: "foo-bar";

.test {
  content: $foo_bar;
}
```

But compile successfully without any warnings:

``` css
.test {
  content: "foo-bar"; }
```

Tested on:  Sass 3.3.0.rc.3 with ruby 2.0.0p353 (2013-11-22) [x64-mingw32]
