### ISSUE TITLE
Can I disable @media bubbling or is my css fundamentally incompatible?

### ISSUE THREAD

**Issue by davecranwell** [sass/sass#1115]
Say i've got a single stylesheet, in which i've laid out my CSS in a mobile-first order, namely the first rules (at the top of the file) are generic or mobile-specific, followed by media queries lower down in the file defining overrides for larger screen breakpoints.

Now say I've written a generic mixin in which I've nested a media query. Say for the sake of example the mixins adds a 20 pixel padding on a wrapper element for mobile, and increases that to 40px at higher breakpoints.

Now say that I want to manually increase that padding further in one specific situation, defined by a breakpoint at the bottom of my CSS. 

What SASS is doing is bubbling the mixin's media query _below_ the media query I've deliberately placed at the bottom of the file to be more specific . Since CSS specificity favours the the last rule over the rules before it, after compilation the mixin is trumping my deliberate override.

Am I just writing my CSS wrong for SASS? Can I disable this bubbling?

``` css

@mixin mypadding{
    padding:20px

    @media screen and (min-width:800px){
        padding:40px
    }
}

.wrapper{
    @include mypadding;
}

@media screen and (min-width:1000px){
    .wrapper{   
        padding:100px
    }
}

```

This compiles to:

``` css

.wrapper{
    padding:20px
}

@media screen and (min-width:1000px){
    .wrapper{   
        padding:100px
    }
}

@media screen and (min-width:800px){
     .wrapper{   
        padding:40px
    }
}
```
