### ISSUE TITLE
Suffixed placeholder classes don't get generated by those that extend them in 3.3

### ISSUE THREAD

**Issue by matthew-andrews** [sass/sass#1125]
I appreciate this feature has [only just landed](http://nex3.roughdraft.io/8050187) but I've come across some maybe expected behaviour.  I've tested this both in **master** and in **bleeding-edge** 6434174f39dccc92 - [Test case on SASS Meister](http://sassmeister.com/gist/9123594).

Original Scss:

``` scss
.foo {
  background-color: pink;

  &--bar {
    background-color: white;
  }
}

%fizz {
  background-color: pink;

  &--buzz {
    background-color: white;
  }
}

.the-fizz {
  @extend %fizz;
}
```

Actual output:

``` scss
.foo {
  background-color: pink;
}
.foo--bar {
  background-color: white;
}

.the-fizz {
  background-color: pink;
}
```

Expected:

``` scss
.foo {
  background-color: pink;
}
.foo--bar {
  background-color: white;
}
.the-fizz {
  background-color: pink;
}
.the-fizz--buzz {
  background-color: white;
}
```

Also - interestingly - if you try to `@extend %fizz--buzz;` that throws an error too.
