### ISSUE TITLE
Interpolation error with parent selector (&) in string literal

### ISSUE THREAD

**Issue by whizark** [sass/sass#1131]
An interpolation with parent selector throws a syntax error with Sass 3.3.0.rc.3+.

```
.test {
    $suffix: '-suffix';

    &#{$suffix} {
        content: 'test 1';
    }

    &#{$suffix} {
        content: 'test 2';
        content: '#{&}';    // The error occurs here.
    }
}
```

```
Syntax error: Invalid CSS after "...   content: '#{": expected expression (e.g. 1px, bold), was "&}';"
```

The code below had worked well untill 3.3.0.rc.2.

```
.test {
    $suffix: '-suffix';

    #{&}#{$suffix} {
        content: 'test 1';
    }

    #{&}#{$suffix} {
        content: 'test 2';
        content: '#{&}';
    }
}
```

Are there any way to reference parent selector in string literal with 3.3.0.rc.3+?

There is another case that works until 3.3.0.rc2 and doesn't work with 3.3.0.rc3+.

```
@function test-func($selector) {
    @return quote($selector);
}

.test {
    content: test-func(#{&});
}
```

**Comment by chriseppstein** [comment]
Starting in `3.3.0.rc.3` you should do this instead:

``` scss
.test {
    $suffix: '-suffix';

    &#{$suffix} {
        content: 'test 1';
    }

    &#{$suffix} {
        content: 'test 2';
        // This no longer works.
        // content: '#{&}';
    }
}
```

More details here: https://gist.github.com/nex3/8050187
