### ISSUE TITLE
output optimization for @extend and nesting

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#1136]
We can avoid the combinatorial explosion of nested selectors and nested extends by using the upcoming `:matches()` pseudo selector.

Example:

``` scss
.a, .b {
  .c, .d {
    color: red
  }
}
```

Currently compiles to:

``` css
.a .c, .a .d, .b .c, .b .d {
  color: red; }
```

But it could compile to:

``` css
:matches(.a, .b) :matches(.c, .d) {
  color: red; }
```

Which although more text in this contrived example would probably be more compact in real world use cases.

Similarly for `@extend`:

``` scss
.a .b { color: red; }
.x .y { @extend .a }
.m .n { @extend .b}
```

Currently compiles to:

``` css
.a .b, .x .y .b, .a .m .n, .m .a .n, .x .y .m .n, .m .x .y .n {
  color: red; }
```

could be compiled to:

``` css
:matches(.a, .x .y) :matches(.b, .m .n) {
  color: red; }
```

And would not require any of the heuristics we currently use to prune selectors.
