### ISSUE TITLE
Build time option

### ISSUE THREAD

**Issue by adi-ads** [sass/sass#1137]
Is it possible to print build time for sass compiler?

Possible feature can be to add --time as a option.

The scenario is I am writing some functions and want to compare their performance.

Currently wrapping it around a bash script to capture before and after time stamp and output the build time. Thus printing the build time.

Grunt also provides build time when used with watch, though its grunt task build time and not sass build time.

**Comment by chriseppstein** [comment]
Compass provides a `--time` option.

You could also write some simple ruby functions to return the current time in milliseconds and then do math and output the difference as a comment.

`sass_timing.rb`:

``` ruby
module Sass::Script::Functions
  def current_time
    Sass::Script::Number.new(Time.now.to_f)
  end
end
```

`code_to_test.scss`:

``` scss
@mixin timed {
/* Starting timing */
$before: current-time();
@content;
$after: current-time();
/* Elapsed Time: #{($after - $before) * 1000} milliseconds */
}

@include timed {
  // Code to be timed. E.g:
  $list: ();
  @for $i from 1 through 1000 {
    $list: append($list, $i);
  }
}
```

How to call this:

```
sass -r ./sass_timing.rb code_to_test.scss test_output.css
```

Results in:

``` css
/* Starting timing */
/* Elapsed Time: 92.37599 milliseconds */
```

I'm going to close this. I don't think this use case warrants a new command line option.
