### ISSUE TITLE
Invalid CSS error... Mixin not working

### ISSUE THREAD

**Issue by tobiasmuecksch** [sass/sass#1141]
Hey there,

I'm using ruby 2.0.0p247 and Sass 3.1.20 (Brainy Betty) on OSX 10.9.

In my custom_mixins.scss I have this mixin:

``` scss
@mixin input-placeholder {
    &::-webkit-input-placeholder    {@content}
    &:-moz-placeholder              {@content}
    &::-moz-placeholder             {@content}
    &:-ms-input-placeholder         {@content}
}
```

and in my main.scss I include this file and another one called login.scss :

login.scss:

``` scss
@import 'customMixins';

// Some other not related stuff //
// Line 27:
.myClass {
    @include input-placeholder {
        color: #FFF;
    }
}
```

Trying to compile this results in the following error:

```
error sass/main.scss (Line 28 of sass/login.scss: Invalid CSS after "...ut-placeholder ": expected "}", was "{")
```

Funny fact; it works flawless on another machine with the same software versions and the very same files. I'm really confused. I thought it could be an encoding problem but it is not.

Google unfortunately didn't turn out very helpful.
