### ISSUE TITLE
calc css rule doesn't support variable

### ISSUE THREAD

**Issue by tinganho** [sass/sass#1147]
``` sass
$horizontal-padding: 10px;
body {
  width: calc(100% - 2*$horizontal-padding);
}
```

yields:

``` sass
body {
  width: calc(100% - 2*$horizontal-padding);
}
```

instead of:

``` sass
body {
  width: calc(100% - 20px);
}
```

**Comment by lolmaus** [comment]
![interpolation](http://i.memeful.com/memes/wr3z9kM/Imagination-Spongebob.jpg)

``` scss
$horizontal-padding: 10px;
body {
  width: calc(100% - #{2*$horizontal-padding});
}
```

Demo: http://sassmeister.com/gist/9371942
