### ISSUE TITLE
&-generated selectors and @extend

### ISSUE THREAD

**Issue by KittyGiraudel** [sass/sass#1148]
I believe there is an issue when trying to extend a selector that has been dynamically generated using `&`. Maybe it's not part of the tree or something, I'm not sure.

``` scss
.a {
  &__b {
    property: value;
  }
}

.c {
  @extend .a__b;
}
```

Expected result:

``` css
.a__b, .c {
  property: value;
}
```

Actual result:

``` css
".c" failed to @extend ".a__b".
The selector ".a__b" was not found.
Use "@extend .a__b !optional" if the extend should be able to fail.
```
