### ISSUE TITLE
bug with sass and special char "\"

### ISSUE THREAD

**Issue by ghost** [sass/sass#117]
Hi,

I have problem with writing special char `\` in sass. I need write to mixin something like this syntax: 

```
$prefix + :\ + $tags
```

to this 

```
v:\article
```

But in need this syntax use in $each to: (this is ideal case and this doesn't work)

``` scss
    @each $vmlTags in
    rect, roundrect, line, polyline, oval, image, curve,
    arc, shapetype, vmlframe, callout, extrusion, fill, formulas,
    handles, imagedata, locks, path, shadow, skew, stroke, textbox, textpath {
        #{$prefix}:\#{$vmlTags} { behavior:url(#default#vml); }
    }
```

and **there is problem**:

I will write
`#{$prefix}:\#{$vmlTags}` error: **error sass/screen.scss (Line 16: Invalid CSS after "...ix}:#{$vmlTags": expected ":", was "} { behavior:ur...") overwrite stylesheets/screen.css**

I will write
`#{$prefix}:\\#{$vmlTags}` to compiled document `\\` <-- two times!

I will write
`#{$prefix}#{":\\"}#{$vmlTags}` error: **error sass/screen.scss (Line 16: Invalid CSS after "...ix}:#{$vmlTags": expected ":", was "} { behavior:ur...") overwrite stylesheets/screen.css**

I will write
`#{$prefix}#{":\"}#{$vmlTags}` <-- error
`#{$prefix}#{":\\"}#{$vmlTags}` <-- error

**I will use hecadecimal chars and it doesn't compile it to special char ...**

THANK YOU!

s.
