### ISSUE TITLE
why can't sass handle emoji?

### ISSUE THREAD

**Issue by dunn** [sass/sass#1170]
For my own inscrutable purposes I want to do this:

``` css
h1::before {
    content: "👻"
}
```

sass fails to compile with this error:

> `error sass/screen.scss (Line 56: Invalid US-ASCII character "\xF0")`

I can write that as regular CSS and it renders fine, at least in Safari.
