### ISSUE TITLE
@extend repeats current selector if used in referencing parent selector (&)

### ISSUE THREAD

**Issue by seyd** [sass/sass#1172]
When using `@extend` right in (not deeper) referencing parent selector (`&`) and placeholder selector (`%`) is defined in a same level, then it causes bad output.

Example:

``` scss
#main {
    %test {
        font-weight: normal; 
    }   
    &.last {
        @extend %test;
    }
}
```

Compiles to:

``` css
#main #main.last {
  font-weight: normal;
}
```

I should be just (am I wrong?):

``` css
#main.last {
  font-weight: normal;
}
```

**Comment by nex3** [comment]
This is expected. What you're writing is the same as

``` scss
#main %test {
  font-weight: normal;
}
#main.last {
  @extend %test;
}
```

So Sass replaces `%test` with `#main.last`, producing the output you see.
