### ISSUE TITLE
@font-face inside of @at-root blows up

### ISSUE THREAD

**Issue by Snugug** [sass/sass#1174]
There appears to be a conflict when wrapping an `@font-face` declaration inside of an `@at-root` declaration when it is already at the root of the document. Sass throws the following syntax error:

```
Syntax error: Properties are only allowed within rules, directives, mixin includes, or other properties.
```

A simple code example that will cause this error:

``` scss
@at-root {
  @font-face {
    font-family: 'Foo bar Baz';
    src: url('fonts/test.woff');
    font-weight: normal;
    font-style: normal;
  }
}
```

Moving that `@font-face` out of `@at-root` is OK. This is not constrained to `@font-face` either, `@viewport` (or really any `@directive` that can take properties directly) seems to fail with that error if wrapped inside `@at-root`.

Interestingly enough, simply moving the `@at-root` inside of a selector will solve this and produce the required result, although is insanely hackey. The following works fine:

``` scss
.font {
  @at-root {
    @font-face {
      font-family: 'Foo bar Baz';
      src: url('fonts/test.woff');
      font-weight: normal;
      font-style: normal;
    }
  }
}
```
