### ISSUE TITLE
Variable scope confusion.

### ISSUE THREAD

**Issue by timfayz** [sass/sass#1183]
Sorry for the mistakes I've made - I'm not Englishman.
I wrote a big amount of code at the top of 3.2 version and `@while` directive the most frequently used. After 3.3 release I'm faced with some confusion moments. For example the code below:

``` SCSS
$i: 1;
@while $i <= 10 {
    .class-#{$i} {...}

    $i: $i + 1;
}
```

thrown the warning: `Assigning to global variable "$i" by default is deprecated.` I've read one of the latest post about variable scope in 3.3. Is it mean that now the code above should be the following form:

``` SCSS
$i: 1 !global;
@while $i <= 10 {
    .class-#{$i} {...}

    $i: $i + 1 !global;
}
```

If so why it is not documented yet?

**Comment by timfayz** [comment]
Next example:

``` SCSS
@mixin additions() {
  $z: 1 !global;
  @while $z <= 5 {
    .nested-#{$z} {
      color: red;
    }

    $z: $z + 1 !global;
  }
}

$i: 1 !global;
@while $i <= 10 {
  .class-#{$i} {
    color: green;
  }

  @include additions();

  $i: $i + 1 !global;
}
```

if `additions()` mixins will use `$i` instead of `$z` variable increment, the main loop becomes infinite.
Version 3.2 has the same behavior.. I think, it means we will use `!global` flag very frequently!

**Comment by nex3** [comment]
Let's take this example-by-example.

> ``` SCSS
> $i: 1 !global;
> @while $i <= 10 {
>     .class-#{$i} {...}
> 
>     $i: $i + 1 !global;
> }
> ```

In this example, you only need to write `!global` in the inner loop. Variable assignments at the top level of your stylesheet are always implicitly global, since they aren't in any enclosing scope.

> ``` scss
> @mixin additions() {
>   $z: 1 !global;
>   @while $z <= 5 {
>     .nested-#{$z} {
>       color: red;
>     }
> 
>     $z: $z + 1 !global;
>   }
> }
> ```

You _shouldn't_ write `!global` here. By doing so, you're telling Sass that you want to write to the `$z` variable that everyone everywhere can see, rather than the one that's local to your function.

> if `additions()` mixins will use `$i` instead of `$z` variable increment, the main loop becomes infinite.

This is precisely why we're introducing `!global`. Sass 3.3 is in a transitional phase in order to provide backwards-compatibility with Sass 3.2; right now `!global` has no effect but to silence warnings. However, once Sass 3.4 is released, variables will be local by default. That means that if you use `$i` in `additions()` without `!global`, it will _shadow_ the global value. This means that assigning to it won't overwrite the global value, it will only be visible locally to the mixin itself.

**Comment by timfayz** [comment]
Thank you for the answer!

``` SCSS
@mixin additions() {
  $i: 1;
  @while $i <= 5 {
    .nested-#{$i} {
      color: red;
    }

    $i: $i + 1;
  }
}

$i: 1;
@while $i <= 5 {
  .class-#{$i} {
    color: green;
  }

  @include additions();

  $i: $i + 1 !global;
}
```

Is it means that after release of Sass 3.4 the example above will be correct? Because now the `$i` increment within `addition()` mixin _overwrites_ the global `$i` variable and main loop runs only once.
