### ISSUE TITLE
@only directive

### ISSUE THREAD

**Issue by meefox** [sass/sass#1187]
Idea is to define a block which will be used in particular selector if rule is true. 
And all other properties in whole selector should be skipped.
As a simple example:
main.scss

```
body {
    background: #000;
    @only $forIE8 {
        background: #FFF;
    }
    @only $forIE9 {
        background: #CCC;
    }
}
```

ie8.scss

```
$forIE8: true;
@import "main";
```

ie9.scss

```
$forIE9: true;
@import "main";
```

all.scss

```
$forIE8: false;
@import "main";
```

Output:
ie8.css

```
body {
  background: #FFF;
}
```

ie9.css

```
body {
  background: #CCC;
}
```

all.css

```
body {
  background: #000;
}
```

**Comment by lolmaus** [comment]
Why aren't you using `@if`?

**Comment by cimmanon** [comment]
Probably because he doesn't want to have to write an else.

``` scss
body {
    @if $forIE8 {
        background: #FFF;
    } @else if $forIE9 {
        background: #CCC;
    } @else {
        background: #000;
    }
}
```

It is worth noting that Sass doesn't eliminate duplicate property declarations.  If it did, we would have problems creating simple fallbacks like this:

``` scss
.foo {
    background: blue;
    background: rgba(blue, .5);
}
```
