### ISSUE TITLE
Can't combine @at-root directives

### ISSUE THREAD

**Issue by tillkruss** [sass/sass#1188]
This code below fails with: `Syntax error: Invalid CSS after ".foo &,": expected "{", was "@at-root .bar"`

```
.class {
    @at-root .foo &,
    @at-root .bar & {
        ...
    }
}
```

But this works:

```
.class {
    @at-root {
        .foo &,
        .bar & {
            ...
        }
    }
}
```

**Comment by xiwcx** [comment]
I believe that for the [inline syntax](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#at-root) to work you would have to write it like this:

``` scss
.class {
    @at-root .foo &, .bar & {
      background: red;
    }
}
```

or

``` scss
.class {
    @at-root .foo &,
    .bar & {
      background: blue;
    }
}
```

The double `@at-root` is a no go.
