### ISSUE TITLE
Defining functions or mixins within control directives

### ISSUE THREAD

**Issue by jslegers** [sass/sass#1193]
Javascript allows me to do the following :

``` js
if (!Date.now) {
  Date.now = function now() {
    return Number(new Date());
  };
}
```

PHP allows me to do the following :

``` php
if (!function_exists('array_column')) {
    function array_column($input = null, $columnKey = null, $indexKey = null){
       // [ polyfill code goes here ]
       return $resultArray;
    }
}
```

While this technique is typically used for writing polyfills, it can be used in other contexts as well. For example, it can also be useful to demonstrate features that don't exist in a language yet but may be added in the future to the language or a popular library/framework for that language.

The beauty of this technique is that it allows one to detect whether a feature exists and always use the default implementation when it already exists.

In Sass, I wanted to do do the following :

``` scss
@if not function-exists(str-replace) {
    @function str-replace($string, $old, $new : '') {
        @if type-of($string) != string {
            $string : '' + $string;
        } 
        $index: str-index($string, $old);
        @while $index and $index > 0 {
            $temp : $string;
            $string : $new;
            @if $index > 1 {
                $string : str-slice($temp, 1, $index - 1) + $string;
            }
            @if $index < str-length($string) {
                $string : $string + str-slice($temp, $index + 1);
            }
            $index: str-index($string, $old);
        }
        @return $string;
    }
}
```

This would allow me to define a string replacement function in Sass, named `str-replace`. In case any function defined as `@function str-replace($string, $old, $new)` already exists (eg. in a future version of Sass, Compass or Bourbon), it would automaticly skip my definition and not generate any errors.
