### ISSUE TITLE
complie multiline comment to new line

### ISSUE THREAD

**Issue by sunnyzhouy** [sass/sass#1197]
``` css
input[type="search"] {
  -webkit-box-sizing: content-box;/* 2 */
  -moz-box-sizing: content-box;
  box-sizing: content-box;
  -webkit-appearance: textfield;/* 1 */
}
```

is complie to 

``` css
input[type="search"] {
  -webkit-box-sizing: content-box;
  /* 2 */
  -moz-box-sizing: content-box;
  box-sizing: content-box;
  -webkit-appearance: textfield;
  /* 1 */
}
```
