### ISSUE TITLE
@extend-ing Selectors Containing Parent Selector References

### ISSUE THREAD

**Issue by ptlu** [sass/sass#1200]
Hello!

Looks like Sass isn't including the &selectors (parent selectors) of a class that is `@extend`-ed onto the `@extend`-ing class.

**Example 1**
Here is an example with .selectors (class selectors).

``` scss
.grid-row {
    width: 100%;
    margin-left: auto;
    margin-right: auto;
    margin-top: 0;
    margin-bottom: 0;
    max-width: 62.5rem;
    *zoom:1;
    &:before, &:after { content: " "; display: table; }
    &:after { clear: both; }
}

.settings-row {
    @extend .grid-row;
}

.score-row {
    @extend .grid-row;
}

.bar-chart-row {
    @extend .grid-row;
}
```

Sass 3.3.4 (Maptastic Maple) produces the following:

``` css
.grid-row, .settings-row, .score-row, .bar-chart-row {
    width: 100%;
    margin-left: auto;
    margin-right: auto;
    margin-top: 0;
    margin-bottom: 0;
    max-width: 62.5rem;
    *zoom: 1; 
}
/* the @extend-ing classes are not getting getting the pseudo-elements */
.grid-row:before, .grid-row:after {
    content: " ";
    display: table; 
}

/* the @extend-ing classes are not getting getting the pseudo-elements */
.grid-row:after {
    clear: both; 
}
```

Only the `.grid-row` selector gets the &selector styles, while the `.settings-row`, `.score-row`, and `.bar-chart-row` selectors are all missing the &selector styles.

I would expect:

``` css
.grid-row, .settings-row, .score-row, .bar-chart-row {
    width: 100%;
    margin-left: auto;
    margin-right: auto;
    margin-top: 0;
    margin-bottom: 0;
    max-width: 62.5rem;
    *zoom: 1;
 }

.grid-row:before, .grid-row:after, .settings-row:before, .settings-row:after, .score-row:before, .score-row:after, .bar-chart-row:before, .bar-chart-row:after, {
    content: " ";
    display: table; 
}

.grid-row:after, .settings-row:after, .score-row:after, .bar-chart-row:after {
    clear: both; 
}
```

This way all styles within the `.grid-row` are applied to the `@extend`-ing classes.

**Example 2**
This even gets worse when using the %selector (placeholder selector), as the final CSS still contains the %selector.

Here is an example:

``` scss
%grid-row {
    width: 100%;
    margin-left: auto;
    margin-right: auto;
    margin-top: 0;
    margin-bottom: 0;
    max-width: 62.5rem;
    *zoom:1;
    &:before, &:after { content: " "; display: table; }
    &:after { clear: both; }
}

.settings-row {
    @extend %grid-row;
}

.score-row {
    @extend %grid-row;
}

.bar-chart-row {
    @extend %grid-row;
}
```

Which produces the following:

``` css
.settings-row, .score-row, .bar-chart-row {
    width: 100%;
    margin-left: auto;
    margin-right: auto;
    margin-top: 0;
    margin-bottom: 0;
    max-width: 62.5rem;
    *zoom: 1;
 }

/* invalid selector with % */
%grid-row:before, %grid-row:after {
        content: " ";
        display: table; 
}

/* invalid selector with % */
%grid-row:after {
        clear: both; 
}
```

**Possible Solution**
Perhaps you need to run the `@extend` logic before the &selector logic is run?

In the second example if the `@extend` logic were run first, it would take an intermediary form like this:

``` scss
.settings-row, .score-row, .bar-chart-row {
    width: 100%;
    margin-left: auto;
    margin-right: auto;
    margin-top: 0;
    margin-bottom: 0;
    max-width: 62.5rem;
    *zoom: 1;

    &:before, &:after { content: " "; display: table; }
    &:after { clear: both; }
 }
```

This intermediary form then compiles correctly.

Please let me know if you have any questions!

Thanks,
Pete
