### ISSUE TITLE
Interpolating parent selector not working correctly 

### ISSUE THREAD

**Issue by ezekg** [sass/sass#1205]
~~Didn't mean to post this without any content. I was gathering together all of the code to help explain the issue correctly.~~ I've ran into a little problem, that looks as if it is a bug (?) because I am almost positive this very same situation used to work in an earlier `--pre` version of Sass.

Anyways, I am attempting to interpolate the `&` selector to keep a map of instances of a mixin, and have run into issues with doing just that. I did find a few issues that are related to this (though I did not keep track of the issue numbers), but upon reading them it seems like it had been implemented at one time, at least when looking at this gist, http://sassmeister.com/gist/7464997 -- if you recompile the Sass, it then breaks.

Here is the basic code, and a SassMeister gist of what I am attempting to accomplish.

``` scss
$instance-count: 0 !global;
$flint__instances: () !global;

@function instance($key, $span, $context, $gutter, $shift) {
    $instance-count: $instance-count + 1 !global;
    $flint__instance: (

      /*! Would love to interpolate #{&}, so that the need to type in a `context`
      * is oblitherated, thanks to Sass checking for the user. Would also open
      * up loads of opportunities to check if a `display: block` has been set on
      * that selector, so that there are no chances of outputting duplicate code 
      */

      // Simply changing `#{&}` to `#{parent-selector}-#{$instance-count}:`
      // will show you the desired output I'm looking to get

      "#{&}": (
        "instance-count": #{$instance-count},
        "key": #{$key},
        "breakpoint": get-value($key, breakpoint),
        "columns": get-value($key, columns),
        "span": #{$span},
        "context": #{$context},
        "gutter": #{$gutter},
        "shift": #{$shift},
      ),
    );

    @return map-merge($flint__instances, $flint__instance);
}

@mixin _ (
  $key: null,
  $span: null,
  $context: null,
  $gutter: null,
  $shift: null
  ) {

  $flint__instances: instance($key, $span, $context, $gutter, $shift) !global;

  // ...
}

.instance--one {
  @include _(laptop, 2, 3, alpha, 5);
}

.instance--two {
  @include _(desktop, 4, 6, row, 10);
  content: "#{$flint__instances}";
}
```

See the working code,
http://sassmeister.com/gist/9998080

Also, or a similar note... are there any future plans for allowing interpolation of the `@content` directive? It would be again, very helpful, even if it would simply output a stringified version of the content; allowing you then to loop over each item in the string and slice it accordingly, and store the values in a map. It would be helpful for doing things such as (which is just a crude example, not an actual use case), http://sassmeister.com/gist/9981683 -- and other use cases such as what I've ran into above with checking if a selector already has a style applied. Thanks guys!
