### ISSUE TITLE
Placeholder selector containing nested selector(s) generates valid, yet unexpected order of combined selectors

### ISSUE THREAD

**Issue by cookch10** [sass/sass#1209]
Given the following Sass:

``` sass
$orange: #f60;
$white: #ffffff;
$grey: #b5b5b5;

$orange: #f60;
$white: #ffffff;
$grey: #b5b5b5;

%button-placeholder {
    display: inline-block;
    padding: 0 10px;
    border: none;
    background-color: $orange;
    color: $white;
    &.grey {
        background-color: $grey;
    }
}
.button {
    @extend %button-placeholder;
    &.up { background-image: url('../images/up.png'); }
    &.right { background-image: url('../images/right.png'); }
}
```

The following CSS is generated:

``` css
.button {
  display: inline-block;
  padding: 0 10px;
  border: none;
  background-color: #ff6600;
  color: white;
}

.grey.button {
  background-color: #b5b5b5;
}

.button.up {
  background-image: url("../images/up.png");
}

.button.right {
  background-image: url("../images/right.png");
}
```

I would expect the .grey.button selector to actually output as

``` css
.button.grey {
  background-color: #b5b5b5;
}
```

I know both variations are equivalent, however I'd like to know if this is the expected behavior.
