### ISSUE TITLE
rounding function

### ISSUE THREAD

**Issue by mbrookes** [sass/sass#121]
Please could we have some sort of rounding or roundup function in SASS math? 

Ideas such as this... (fontsize proportional headers):

``` css
h1 {
    font-size: $font-size * 2.1;
}
h2 {
    font-size: $font-size * 1.9 ;
}
h3 {
    font-size: $font-size * 1.7;
}
```

...result in non-integer px sizes. They do work , but look... odd. Same issue with programatically derived column-widths, and no;doubt others. Thanks for Sass!
