### ISSUE TITLE
inspect() calculates font-size/line-height which should not be calculated

### ISSUE THREAD

**Issue by hagenburger** [sass/sass#1229]
``` scss
// Sass v3.3.5

$font: bold 18px/1.4 "Helvetica Neue", Helvetica, sans-serif;

#x {
  // works well:
  font: $font;

  // calculates 18px/1.4 = 12.85714px
  font: inspect($font);
}
```

``` css
#x {
  font: bold 18px/1.4 "Helvetica Neue", Helvetica, sans-serif;
  font: bold 12.8571428571px "Helvetica Neue", Helvetica, sans-serif;
}
```

See also: http://sassmeister.com/gist/11286844

Also it seems like the output sometimes is `12.85714px`, sometimes `12.8571428571px`. I noticed that change every time I updated in Sassmeister.
