### ISSUE TITLE
Doc: Mixins Variable Arguments example needs amendment

### ISSUE THREAD

**Issue by ruben-santacruz** [sass/sass#1234]
Link to section in file: https://github.com/nex3/sass/blob/48f29f8e106e85f469bd3084708fbc60e1284c17/doc-src/SASS_REFERENCE.md#variable-arguments

When in the compiled output says:

``` CSS
.secondary {
      color: #0000ff;
      background-color: #ff0000;
      border-color: #00ff00;
    }
```

it should say:

``` CSS
.secondary {
      color: #00ff00;
      background-color: #0000ff;
      border-color: #ff0000;
}
```
