### ISSUE TITLE
Multiple media queries in output when using for loop and @at-root

### ISSUE THREAD

**Issue by redodo** [sass/sass#1239]
I have encountered a problem in the CSS output generated by Sass 3.3.7 (Maptastic Maple).

---
##### The problem

I have the following SCSS:

``` scss
@media (max-width: 700px) {
    @for $column from 1 through $columns {
        .medium-#{$column} {
            width: 100% / $columns * $column;
            @at-root (without: media) {
                @extend %box;
            }
        }
    }
}
```

In this case, `%box` is an abstract representation of a floating element with some additional features. Which can only be extended by using `@at-root`.

The code is compiled to the following 'compressed' output:

``` css
/* %box is extended here perfectly */

@media (max-width: 700px) {
    .medium-1 {
        width: 12.5%; } }
/* more media queries for each element */
@media (max-width: 700px) {
    .medium-8 {
        width: 100%; } }
```

It basically creates a media block for each of the generated elements while the for-loop is contained _inside_ the media query.

When the code is compiled without the `@at-root` block, all the elements are contained inside a single media query.
