### ISSUE TITLE
automatic reordering of child selectors causes issues with cascading

### ISSUE THREAD

**Issue by pdaoust** [sass/sass#1243]
I know it was a design choice to put nested rules below the parent rule, regardless of source ordering, and I vaguely remember it being about reducing bloat. However, to me it doesn't follow the principle of least surprise: I would expect it to follow the ordering I chose. In cases like

``` scss
.parent {
  margin: 1em 0;
  .child { padding: 1em; }
  color: red;
}
```

My expected output would be

``` css
.parent { margin: 1em 0; }
.parent .child { padding: 1em; }
.parent { color: red; }
```

which duplicates the `.parent` selector, I know. But I feel like that should be my choice, so I can order my selectors in a predictable fashion. It can cause cascade surprises, especially when I'm doing something like this:

``` scss
@mixin reset-link-styles {
  &, &:visited, &:hover, &:active {
    text-decoration: none;
    color: inherit;
    // etc...
  }
}
.class {
  @include reset-link-styles;
  color: red;
}
```

Which unexpectedly puts the reset below the `color: red`, nullifying that declaration.

I've also noticed that it still reorders even when the child selector isn't preceded by any styles pertaining to the parent class, as in:

``` scss
.class1 {
  .class2 { color: green; }
  color: red;
}
```

Even though `.class2` isn't at risk of breaking `.class1` in half, it still gets output afterwards.

I realise that this is a subtle issue that requires careful thought, so I'm not expecting anyone to say "oh, we'll change that right away sir" -- just wanted to post my thoughts and inspire some conversation. I've got a workaround for the reset example -- putting all the styles that should appear afterwards in their own `&` selector:

``` scss
.class {
  @include reset-link-styles;
  & { color: red; }
}
```

but it feels finicky.

My inclination would be to dispense with optimisation and leave that responsibility to users, but I realise I'm just one user among many, some of whom might appreciate this feature!
