### ISSUE TITLE
Append the Sass version in the CSS.

### ISSUE THREAD

**Issue by emagnier** [sass/sass#1247]
In some cases, it could be helpful to append the Sass compiler version in the CSS.

sass / scss:

``` scss
/* 
 * Sass version: #{get-sass-version()}
 */
```

css:

``` css
/* 
 * Sass version: Sass 3.3.7 (Maptastic Maple)
 */
```

**Comment by nex3** [comment]
I could see exposing this as a global `$-sass-version` variable. @chriseppstein?

**Comment by chriseppstein** [comment]
In Compass 1.0 there is a function `compass-extensions()` that returns a map of extensions to their versions. Presently Sass has no automatically exposed global variables so I'm inclined to prefer a function. Would it return a bare string or a map with keys like `string`, `major-version`, `minor-version`, `patch-level`, `prerelease`, `name` etc.

**Comment by nex3** [comment]
I think a bare string is fine. We want to encourage users to use `sass-supports` for feature detection.

**Comment by yotamN** [comment]
It will be nice as option but not to show up on any compile file

**Comment by KittyGiraudel** [comment]
Having a map like @chriseppstein described would be cool, but I think I'm kind of nerdy about this. A string is probably well enough for most cases.

**Comment by chriseppstein** [comment]
I think if we're going to add `sass-version()` we should also add `sass-engine()` which would return `official` or something like that so that other implementations can return something else.

**Comment by KittyGiraudel** [comment]
Rather than having multiple functions (which could quickly become a mess), I think it would be easier to have:

``` scss
@function sass-info() {
  @return (
    engine: "official",
    version: (
      major: 3,
      minor: 3,
      patch: 6,
      string: "3.3.6"
    ),
    name: "Maptastic Maple",
    prerelease: false
  );
}

// Rather than `engine: "official"`, 
// I suppose we could have `implementation: "ruby"`.
```

Nope?

**Comment by chriseppstein** [comment]
I'm fine with exposing a single function instead. I'd probably favor a slightly different structure..

``` scss
@function sass-info() {
  @return (
    engine: "official",
    version: "3.3.6",
    parsed-version: (
      major: 3,
      minor: 3,
      patch: 6
    ),
    release-name: "Maptastic Maple"
    prerelease: false // when true it's "alpha.23" or "rc.3"
  );
}
```
