### ISSUE TITLE
Incorrect output iterating over a list containing a single map vs multiple maps

### ISSUE THREAD

**Issue by larrybotha** [sass/sass#1250]
##### Issue

When providing a list with a single map (this list's purpose is to be extended with additional maps as a site grows) and iterating over the map's values, the key is output correctly, but its value is not output, and then the value of each key is output on the next iteration in place of the key, and again with no output for where the value was specified in the `@each` declaration. The output is essentially twice the length it should be, with values not output as specified in the loop.

This is resolved by either adding more maps to the list, or adding an empty list to the list.
##### Example

I generate subsets of icons based on their functionality. This is done by creating a map for each subset, placing these subsets in a list, and then looping through key value pairs in each subset in the list.

``` scss
// icon map
$app-icons: (
    menu:     "\e000",
    grid:     "\e010",
    expand:   "\e020",
    close:    "\e030",
);

// list with 1 map
$icon-sets: $app-icons;

// loop over each item in the list
@each $icon-set in $icon-sets {
    // loop over each key-value pair in the map
    // key is used in class name, value is used in property value
    @each $icon-name, $icon-uni in $icon-set {
        .icon-#{$icon-name}:before {
            content: "#{$icon-uni}";
        }
    }
}
```

Expected:

``` css
.icon-menu:before { content: "\e000"; }
.icon-grid:before { content: "\e010"; }
.icon-expand:before { content: "\e020"; }
.icon-close:before { content: "\e030"; }
```

Actual:

``` css
.icon-menu:before { content: ""; }
.icon-\e000:before { content: ""; }

.icon-grid:before { content: ""; }
.icon-\e010:before { content: ""; }

.icon-expand:before { content: ""; }
.icon-\e020:before { content: ""; }

.icon-close:before { content: ""; }
.icon-\e030:before { content: ""; }
```
##### Resolution

``` scss
// if the list has only 1 item, append an empty list
$icon-sets: $app-icons, ();
```
