### ISSUE TITLE
Nested @font-face results in invalid syntax

### ISSUE THREAD

**Issue by atombender** [sass/sass#1251]
Input:

``` scss
.foo {
  @font-face {
   font-family: "Ionicons";
   src:url("../fonts/ionicons.eot?v=1.4.0");
   src:url("../fonts/ionicons.eot?v=1.4.0#iefix") format("embedded-opentype"),
    url("../fonts/ionicons.ttf?v=1.4.0") format("truetype"),
    url("../fonts/ionicons.woff?v=1.4.0") format("woff"),
    url("../fonts/ionicons.svg?v=1.4.0#Ionicons") format("svg");
   font-weight: normal;
   font-style: normal;
  }
}
```

Result:

``` css
@font-face {
  .foo {
    font-family: "Ionicons";
    src: url("../fonts/ionicons.eot?v=1.4.0");
    src: url("../fonts/ionicons.eot?v=1.4.0#iefix") format("embedded-opentype"), url("../fonts/ionicons.ttf?v=1.4.0") format("truetype"), url("../fonts/ionicons.woff?v=1.4.0") format("woff"), url("../fonts/ionicons.svg?v=1.4.0#Ionicons") format("svg");
    font-weight: normal;
    font-style: normal; } }
```

Could I put the font-face outside? Certainly, but what I am attempting here to wrap an entire stylesheet (imports and all) in an outer selector, to provide a stylesheet for an embeddable widget that must not clobber any other styles on the page. I can move fonts outside the top-level selector, but it does make my stylesheets more awkward, and I have to break them up more.

**Comment by apfelbox** [comment]
Does this work for you?

``` scss
.foo {
  @at-root {
    @font-face {
     font-family: "Ionicons";
     src:url("../fonts/ionicons.eot?v=1.4.0");
     src:url("../fonts/ionicons.eot?v=1.4.0#iefix") format("embedded-opentype"),
      url("../fonts/ionicons.ttf?v=1.4.0") format("truetype"),
      url("../fonts/ionicons.woff?v=1.4.0") format("woff"),
      url("../fonts/ionicons.svg?v=1.4.0#Ionicons") format("svg");
     font-weight: normal;
     font-style: normal;
    }
  }
}
```
