### ISSUE TITLE
Feature for @each directive

### ISSUE THREAD

**Issue by timfayz** [sass/sass#1262]
Example from documentation:

``` SCSS
//vertical assignment
@each $animal, $color, $cursor in
    (puma, black, default),
    (sea-slug, blue, pointer),
    (egret, white, move) {
//code
}
```

What about this?

``` SCSS
//horizontal assignment
@each
    $animal in (puma, sea-slug, egret),
    $color in (black, blue, white),
    $cursor in (default, pointer, move) {
//code
}
//provided that all lists have the same length
```

To make that I need as follows:

``` SCSS
$i: 1;
$animals: (puma, sea-slug, egret);
$colors: (black, blue, white);
$cursors: (default, pointer, move);
@while $i <= length($animals) {
  $animal: nth($animals, $i);
  $color: nth($colors, $i);
  $cursor: nth($cursors, $i);

  //code

  $i: $i + 1 !global;
}
```

What do you think?
