### ISSUE TITLE
Feature request - additional output options

### ISSUE THREAD

**Issue by peterwilsoncc** [sass/sass#1263]
Hello,

This comes from a short discussion I had with @chriseppstein on Twitter.

I'd like to be able to use the compact output style without including comments.

uncompiled code:

``` scss
/*! Each selector is placed on its own line and standard comments are removed */
.selector{
  foo: bar;
  blah: blah;
}

.some-selector,
.another-selector{
  /* for debug
  outline: 1px solid green /* */
  bar: foo;
  blah: blah;
}

.third-selector{
  bar: camp; /* are these still a thing? */
  etc: etc;
}
```

compiled code:

``` css
/*! Each selector is placed on its own line and standard comments are removed */
.selector{foo:bar;blah:blah}
.some-selector,.another-selector{bar:foo;blah:blah}
.third-selector{bar:camp;etc:etc}
```

At the time, there was a mentioned of more nuanced output options rather than a set of styles.

https://twitter.com/chriseppstein/status/468819519440297984

Cheers,
Pete
