### ISSUE TITLE
Invalid function names

### ISSUE THREAD

**Issue by KittyGiraudel** [sass/sass#1265]
A couple of months ago, I [opened an issue](https://github.com/nex3/sass/issues/1090) regarding functions called `true()`, `false()` and `null()` that didn't work as expected.

Today, I found out functions called `and()`, `or()` and `not()` are even worse. Both `and()` and `or()` returns a syntax error when _called_ (not declared):

``` scss
@function and() {
  @return "and"
}

test {
  and: and();
}
```

> Invalid CSS after "  and: ": expected expression (e.g. 1px, bold), was "and();"

``` scss
@function or() {
  @return "or"
}

test {
  or: or();
}
```

> Invalid CSS after "  or: ": expected expression (e.g. 1px, bold), was "or();"

The `not()` function on the other side partially works. It doesn't throw any error but it returns `false`, no matter what.

``` scss
@function not() {
  @return "not"
}

test {
  not: not();
}
```

``` css
test {
  not: false;
}
```

Tested on Sass 3.3.6 and 3.2.19. Curious things is everything works like a charm with LibSass.
