### ISSUE TITLE
@media in the variable

### ISSUE THREAD

**Issue by timfayz** [sass/sass#1266]
Hello, I can't escape the media query by variable. Please, see example:

``` SCSS
$string: "@media screen";
#{$string} {
  //css
}
//error
```

What do I wrong?
Please, do not ask me why is need for. It really useful to built several queries by map. Like this:

``` SCSS
$query-map: (
   tablet: "@media ...",
   moderniz: ".no-font-face",
);
//then apply them via map-get($query-map, tablet)
```

**Comment by lolmaus** [comment]
Just leave the `@media` part outside:

``` scss
$query: "screen";
@media #{$query} {
  html { foo: bar; }
}
```

Demo: http://sassmeister.com/gist/151e9b70f402e11f768c

**Comment by timfayz** [comment]
Sorry, but it is not solution.

**Comment by lolmaus** [comment]
Why not?

**Comment by timfayz** [comment]
``` SCSS
$query-map: (
   tablet: "@media screen",
   moderniz: ".no-font-face",
);

@mixin media($query-map, $device) {
       #{map-get($query-map, $device)} {
          @content;  
       }
}

.hello {
     content: 'asd';
    @include media($query-map, tablet);
}
```

Super simple example

**Comment by lolmaus** [comment]
And what is the problem?

http://sassmeister.com/gist/0bce3e6a007253d603e6

**Comment by timfayz** [comment]
what about styles under ".no-font-face"? "@media .no-font-face"?:)

**Comment by lolmaus** [comment]
@kalopsia, i'm not sure that's valid CSS.

Should be something like this, i think:

``` css
html.no-font-face .my-module {
  fallback: foo-bar;
}
```

**Comment by timfayz** [comment]
"@media .no-font-face" - was a joke. You absolutely can't understand me.. Let me give you example once again:

``` SCSS
$query-map: (
   tablet: "@media screen",
   modernizr: ".no-font-face",
);

@mixin media($query-map, $device) {
   #{map-get($query-map, $device)} {
       @content;  
   }
}

.hello {
     content: 'default';
    @include media($query-map, tablet) {
       content: 'under @media screen';
    }
    @include media($query-map, modernizr) {
       content: 'under .no-font-face';
    }
}

//output will be something like this:
.hello {
     content: 'default';
}

@media screen {
.hello {
     content: 'under @media screen';
}
}

.no-font-face .hello {
     content: 'under .no-font-face';
}
```
