### ISSUE TITLE
Allowing Nested Mixins

### ISSUE THREAD

**Issue by MarioRicalde** [sass/sass#127]
Nested mixins with nested functions, currently works (somehow) on github.com/kuroir/Survival-Kit

**Comment by MarioRicalde** [comment]
```
@mixin b() { @debug "b global"; }
@mixin a() { @debug "a global";
    @mixin b() { @debug "b inside a()"; }
    @include b();
}
@include b();
@include a();
@mixin a() { @debug "a override"; }
@include a();

Console:
DEBUG: b global
DEBUG: a global
DEBUG: b inside a()
DEBUG: a override
```

**Comment by byzg** [comment]
+

**Comment by chriseppstein** [comment]
The module system in Sass 4.0 will provide the ability to control a public API and avoid naming collisions across modules. Once we have that, I can't think of a use case for nested `@mixin` definitions.

**Comment by benjaminrobinet** [comment]
Hello, I come to re-open this issue as I found a use case that might show you.

```scss
@mixin font-face( $font-name, $font-path, $font-weight: 400, $font-style: normal ){
    @font-face {
      font-family: $font-name;
      font-style : $font-style;
      font-weight: $font-weight;
      src:
        url('#{$font-path}.woff2') format('woff2'),
        url('#{$font-path}.woff') format('woff'),
        url('#{$font-path}.ttf') format('truetype');
    }

  @mixin font-#{$font-name}-#{$font-weight}-#{$font-style}{
    font-family: $font-name;
    font-style: $font-style;
    font-weight: $font-weight;
  }
}
```

So here is a mixin to build font-faces like that:
```scss
@include font-face("Avenir", "../dist/fonts/Avenir-Roman", normal, normal);
```

And it (should) generates at the same time a mixin to use that font-face like that:
```scss
body{
  @include font-Avenir-normal-normal;
}
```

What do you think about it ?
