### ISSUE TITLE
Weird compilation bug

### ISSUE THREAD

**Issue by KittyGiraudel** [sass/sass#1270]
When compiling the following code (both Sass 3.3.8 and 3.2.19):

``` scss
$value: 1E5DF;

test {
  raw: 1E5DF;
  variable: $value;
}
```

I get this result:

``` css
test {
  raw: 1E5DF;
  variable: 1E 5DF;
}
```

Any reason there is a space inserted right after `E`? Problem seems to go away when quoting the value.
