### ISSUE TITLE
css color bug in sass maps

### ISSUE THREAD

**Issue by brewster1134** [sass/sass#1274]
i discovered that the key name in sass maps are replaced if they match css color names.  should this be restricted to the values only?

``` sass
$colors: (grey: #434c53)

@each $color, $hex in $colors
  .#{$color}
    background: $hex
```

generates

``` css
.gray {
  background: #434c53;
}
```
