### ISSUE TITLE
Not only @extend classes or placeholders but also @include them 

### ISSUE THREAD

**Issue by timfayz** [sass/sass#1284]
Again and again I (I think not only I) bump on the need to include properties from other classes (like in LESS). Let's take example:

``` SCSS
.shadow-out {
  box-shadow: ...pretty shadow...; 
}
%color-gray {
  color: ...gray...; 
}

textarea,
input:not([type]),
input[type="date"],
input[type="datetime"],
input[type="datetime-local"],
input[type="email"],
input[type="file"],
input[type="month"],
input[type="number"],
input[type="password"],
input[type="search"],
input[type="tel"],
input[type="text"],
input[type="time"],
input[type="url"],
input[type="week"] {
  @include .shadow-out;
  @include %color-gray;
  border: ...;
  //etc
}
```

Because mixins' names can't be started with . or % it make sense to parse this names differently.. Can this feature be implemented? From my point of view it is quite logical if we can do @extend, then we can do @include.
Like @extend this feature should work with dynamically generated classes and placeholders.

_For heaven's sake don't offer solutions like "you can do this...[your code], you can do that...[your code]"_
