### ISSUE TITLE
The words grey and gray

### ISSUE THREAD

**Issue by murderofmagpies** [sass/sass#1288]
I've just stumbled upon something strange.

I have a map:

```
$palette: (
    greyscale: (
        white: $palette_white,
        lightest-grey: lighten($palette_black, 90%),
        light-grey: lighten($palette_black, 75%),
        grey: lighten($palette_black, 50%),
        dark-grey: lighten($palette_black, 25%),
        darkest-grey: lighten($palette_black, 10%),
        black: $palette_black,
    ),
    rgb: (
        blue: #0000ff,
        green: #00ff00,
        red: #ff0000,
    ),
    //brand: (),
);
```

Then I have a mixin that i use to expand maps:

```
@mixin expand($map, $pf: 'expand', $attribute: 'attribute') {
    @each $k, $v in $map {
        @if type-of($v) == map {
            @include expand($v, $pf, $attribute);
        } @else {
            .#{$k}-#{$pf} {
                #{$attribute}: $v;
            }
        }
    }
}
```

Weird thing is, when I expand palette, the output is as follows:

``` css
.white-bg {
  background: white;
}

.lightest-grey-bg {
  background: #e6e6e6;
}

.light-grey-bg {
  background: #bfbfbf;
}

.gray-bg {
  background: gray;
}

.dark-grey-bg {
  background: #404040;
}

.darkest-grey-bg {
  background: #1a1a1a;
}

.black-bg {
  background: black;
}

.blue-bg {
  background: blue;
}

.green-bg {
  background: lime;
}

.red-bg {
  background: red;
}
```

Notice the naked .gray-bg class has a different US spelling of the word 'grey' - I could just rename my keys to 'gray' but it kinda irks me...
