### ISSUE TITLE
Looping over content directive

### ISSUE THREAD

**Issue by ezekg** [sass/sass#1289]
I'm not sure if this is an easily implementable option, but I think it would be great if we could loop over the content directive. This could potentially bring in similar functionality to LESS and Stylus' property lookup functions, at least in regards to mixin creation.
### Syntax

``` scss
@content as $property, $value {
    @if type-of($value) == "list" {
        // ...
    }
}

// Or

@content as $property, $value in $selector {
    @if $selector == & {
        // ...
    }
}

```

The syntax would be similar to using an each loop to iterate over a map. It would treat CSS lists as Sass lists, of course. This could be used along side a feature similar to the one mentioned in issue #871 to create mixins that are capable of responding to properties passed to the content directive. For example, for various grid systems, you could override a float property via the content directive and the mixin could respond to that and not output redundant code.

Using the original content directive might not be the best idea, but similar names such as `@each-content`, `@in-content`, etc. would also work nicely.

If this is something that you think would be worth doing, point me in the right direction and I'd be more than happy to fork the code and try my hand at implementing it.

**Comment by lolmaus** [comment]
Can you please provide suggested usage and output code?

**Comment by ezekg** [comment]
``` scss
@mixin foo() {
    // Default to float is undefined
    $float-is-defined: false;

    // Check content block for float value
    @content as $property, $value {
        // If float value exists, modify variable
        @if $property == "float" {
            $float-is-defined: true;
        }
    }

    @if not $float-is-defined {
        float: left;
    }

    @content;
}

// Use with content block
selector {
    @include foo() {
        float: right;
    }
}

// Outputs
selector {
    float: right;
}

// Use without content block
selector {
    @include foo();
}

// Outputs
selector {
    float: left;
}
```

The mixin can check if float is defined within the content directive, so that duplicate and redundant code is not outputted to the stylesheet. Now imagine this on a much grander scale and it could prove to be very, very useful.

**Comment by cimmanon** [comment]
How do you propose this will work in the case of using selectors in the `@content`?

``` scss
.foo {
    @include foo() {
        .bar {
            color: red;
        }
    }
}
```

**Comment by ezekg** [comment]
Hadn't thought that far ahead. Assuming a feature like this would be implemented after the SassScript ampersand returns, you could do something like this:

``` scss
@content as $property, $value in $selector {
    @if $selector == & {
        // ...
    }
}
```

**Comment by Anahkiasen** [comment]
I think it would be better if subselectors were just ignored in a first time.

**Comment by ezekg** [comment]
Although I originally thought the same, I could see some value in sub-selectors not being ignored. Imagine a use case for something similar to this:

``` scss
@mixin BEMify() {
    $root: &;

    @content as $property, $value in $selector {
        @if $selector == $root {
            // Do something with the root
        } @else {
            // BEMify the child selector
            $selector: #{$root}__#{$selector};

            // Continue to modify output
        }
    }
}

// Use
foo {
    property: value;

    @include BEMify() {
        bar {
            property: value;
        }

        baz {
            property: value;
        }
    }
}

// Outputs
foo {
    property: value;
}

foo__bar {
    property: value;
}

foo__baz {
    property: value;
}
```

Not sure how it would be handled the deeper you nest, but still a cool concept for abstracting away certain popular syntaxes. Also not sure how it should handle classes and ID's present in a selector.

**Comment by lolmaus** [comment]
I don't mind selector manipulation but i don't like the original idea of property manipulation. Instead of organizing your code to produce efficient CSS, you want to produce messy CSS and have Sass clean it after you.

The problem with the approach is that it is very inconsistent. There are so many edge cases that i believe it's near to impossible to address them all and at the same time make this feature understandable and predictable.

**Comment by ezekg** [comment]
I completely disagree. It gives authors the freedom to base mixin output on user input. Instead of requiring it as a variable to the mixin (which can get messy fast if you want multiple variable properties), you can make it easier for your users by modifying your mixins output based on their preference within the content block, as in my float example above.

**Comment by lolmaus** [comment]
Can you describe a use case for which this approach is justified? The float example is farfetched: a lot of scaffolding to do what can be done simply with an argument default, so it's not very persuasive.

Also, it sounds like you want to be able to create mixins that do lots of styling with a single call. Such an approach in programming is generally considered to be a bad practice. Maybe you could address this too.

**Comment by ezekg** [comment]
Maybe I am thinking too big or too extreme. I was thinking of something similar to the use-case above but more complex, however like you said, maybe what I'm thinking is a use-case is actually bad practice.

Although, I'd consider a mixin that does multiple things more of an API than a function, and I don't see that as _bad practice_ per se. Regardless, I haven't been a developer long enough to argue for it, so I won't bother. I would like to get more thoughts on the concept.

**Comment by lolmaus** [comment]
@ezekg, please describe a situation where an API mixin would accept user input with arbitrary styles and override some of them.

**Comment by chriseppstein** [comment]
This is actually an idea I've been mulling over for quite a while.

Basically, this capability boils down to: expose the a part of the syntax tree as a sass data structure.

It enables lots of features that Sass itself has historically said it wouldn't add. I've been on the fence about whether this is a bad thing or not. I am convinced there are a number of features (like automatic property expansion) is a bad thing for Sass itself to do it, but when the implementation is in Sass syntax and not magically hidden away in the compiler I find myself having fewer objections to such features because since the features are written in a language the user understands, it's altogether less magical for them -- they can, if they choose to, dig in to how the magic works and even change it.

Since introducing Maps, I am seeing a lot of code that is basically: We can't manipulate the CSS you write, so instead write a bunch of maps and we'll operate on that and output css for you. Susy does this, Archetype does this.  True needs this to test mixins. I'm sure there are other examples where any suffiently complex plugin eventually hits the CSS syntax barrier and cannot provide the API they think is the most user friendly. So we've now got to this strange place where everything that this feature provides is already possible, but with the downside that you are no longer writing CSS in CSS syntax, but instead using some less user-friendly syntax that is SassScript accessible.

Anyways, here's the idea I had thrown together a few months back:
https://gist.github.com/chriseppstein/5818878

**Comment by ezekg** [comment]
@lolmaus I'll use the example of a grid system. Assuming the grid system has a global config file, which lets you define a float direction. Let's say we chose a float direction of left, but for a few areas on our project, we need the float direction to be right. It's not logical to have a `$float` argument for the mixin if it would only be used in edge cases, so we can define an exception using the directive that would allow this:

``` scss
selector {
    @include column(4) {
        float: right;
    }
}
```

And then you wouldn't get redundant float declarations in your code if you chose to override it. It gives opportunity to create edge case exceptions without defining argument variables that are going to be virtually useless for the typical use case. Additionally, see the example below.

# 

@chriseppstein I agree, that's one of the reasons I created the issue. I'm currently using a similar system where I'm essentially using maps to accomplish this, but I feel like it is a hacky solution when we have a `@content` directive that has the ability to hold all these variables for us.

``` scss
// Passing in lists will allow us to fetch these values and store them through the foo() mixin
// ---

// Hacky solution using maps
selector {
    @include foo($args: (
        color: (baz, bar),
        border-color: (baz, bar),
    ), $map-to-fetch-from);
}

// When we could do
selector {
    @include foo($map-to-fetch-from) {
        color: (baz, bar);
        border-color: (baz, bar);
    }
}
```

The former doesn't seem like it's a solution, but rather a workaround for something that should be a directive. I really hope that isn't too confusing.

Here's the idea in context,
https://gist.github.com/ezekg/ccf842e5ee74287f1868
