### ISSUE TITLE
N% selectors not parsing on master

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#1290]
Broken in 7e552e747f1f8743fe1ce054cc17a8b2975f39b0

**Comment by chriseppstein** [comment]
This still gives an error because keyframes directives can be prefixed:

``` scss
@mixin keyframes($name) {
  @-moz-keyframes #{$name} { @content };
  @keyframes #{$name} { @content };
}

@include keyframes(foo) {
  0%, 100% {
    opacity: 1;
  }
  50% {
    opacity: 0.25;
  }
}
```

**Comment by chriseppstein** [comment]
Also, at-rules are supposed to be case-insensitive.

**Comment by joeytwiddle** [comment]
We are getting a bug that looks like this in 3.4.0

``` log
Sass::SyntaxError: Invalid CSS after "": expected selector, was "0%"
/Users/joey/.rvm/gems/ruby-2.1.0/gems/sass-3.4.0/lib/sass/scss/parser.rb:1163:in `expected'
/Users/joey/.rvm/gems/ruby-2.1.0/gems/sass-3.4.0/lib/sass/scss/parser.rb:1099:in `expected'
/Users/joey/.rvm/gems/ruby-2.1.0/gems/sass-3.4.0/lib/sass/scss/parser.rb:1079:in `expr!'
/Users/joey/.rvm/gems/ruby-2.1.0/gems/sass-3.4.0/lib/sass/scss/static_parser.rb:20:in `parse_selector'
/Users/joey/.rvm/gems/ruby-2.1.0/gems/sass-3.4.0/lib/sass/tree/visitors/perform.rb:406:in `visit_rule'
/Users/joey/.rvm/gems/ruby-2.1.0/gems/sass-3.4.0/lib/sass/tree/visitors/base.rb:36:in `visit'
/Users/joey/.rvm/gems/ruby-2.1.0/gems/sass-3.4.0/lib/sass/tree/visitors/perform.rb:152:in `block in visit'
```

The problem CSS (plain CSS, not SASS) looks like this:

``` css
@-webkit-keyframes glow-element {
  0% { box-shadow: none; }
  50% { box-shadow: 0 0 10px red;}
  100% { box-shadow: none; }
}
@-moz-keyframes glow-element {
  0% { box-shadow: none; }
  50% { box-shadow: 0 0 10px red;}
  100% { box-shadow: none; }
}
@-keyframes glow-element {
  0% { box-shadow: none; }
  50% { box-shadow: 0 0 10px red;}
  100% { box-shadow: none; }
}
@-o-keyframes glow-element {
  0% { box-shadow: none; }
  50% { box-shadow: 0 0 10px red;}
  100% { box-shadow: none; }
}
```

**Comment by chriseppstein** [comment]
The problem is this:

``` css
@-keyframes glow-element {
  0% { box-shadow: none; }
  50% { box-shadow: 0 0 10px red;}
  100% { box-shadow: none; }
}
```

There is no directive named `@-keyframes` it should be `@keyframes`.
