### ISSUE TITLE
Error thrown for this code

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#1294]
``` scss
%column {
  float: left;
}
@media screen and (min-width: 300px) {
  .span-10 {
    @at-root (with: rules) {
      @extend %column;
    }
    width: auto;
  }
}
```
