### ISSUE TITLE
keyframes dont work in master branch

### ISSUE THREAD

**Issue by Fudoshiki** [sass/sass#1301]
Invalid CSS after "": expected selector, was "0%"
  (in .../app/assets/stylesheets/common/pages.css.scss:158)

code:

``` scss
@include keyframes(blink) {
  0% {
    text-shadow: none;
  }
  50% {
    text-shadow: 0 0 10px white;
  }
  100% {
    text-shadow: none;
  }
}
```
