### ISSUE TITLE
selector-append does not accept double dash suffixes

### ISSUE THREAD

**Issue by micahgodbolt** [sass/sass#1310]
Works in 3.4.0.alpha

``` scss
 #{selector-append(".foo, .bar", "-suffix")} {
  color: purple
}
```

Doesn't work

``` scss
 #{selector-append(".foo, .bar", "--suffix")} {
  color: purple
}
```
