### ISSUE TITLE
Quote-removal doesn't propagate down through data structures

### ISSUE THREAD

**Issue by micahgodbolt** [sass/sass#1315]
"quote-removal doesn't propagate down through data structures"

The following throws an error in Sass 3.4. `unquote(".abc")`  is currently required for it to work. (And yes, I know this example is very contrived and unnecessary with selector-nest).

``` scss
nav{
  ul {
    li {
      $new-selector: append(nth(&, 1), ".abc");
      @at-root #{$new-selector} {
        color: pink;
      }
    }
  }
}
```
