### ISSUE TITLE
String concatenation in @-directive

### ISSUE THREAD

**Issue by KittyGiraudel** [sass/sass#1324]
This is somewhat an old issue since I recall trying to do something like this last year:

``` scss
@mixin keyframes($animation-name, $vendors: ()) {
  @each $vendor in $vendors {
    // Why is this not working?
    // For that matter, neither of this work:
    // #{'@-' + $vendor + '-keyframes}
    // #{'@-}#{$vendor}-keyframes
    @-#{$vendor}-keyframes #{$animation-name} {
      @content;
    }
  }

  @keyframes #{$animation-name} {
    @content;
  }
}

// Test

@include keyframes('spin', 'webkit' 'ms') {
  to { transform: rotate(1turn); }
}
```

Error:

> Invalid CSS after "    @": expected identifier, was "-#{$vendor}-key..."
