### ISSUE TITLE
Interpoation is not working as expected.

### ISSUE THREAD

**Issue by dev-mraj** [sass/sass#1329]
following snnipet is not working as expected.
can anyone please check this, it was working fine in prevois version of sass but its giving errors after i hit `gem install sass`

```
$breakpoint-very-small: "(min-width: 0) and (max-width: 200px})";

@mixin responsive($breakpoint, $media: all) {
    @media ($media) and (#{unquote($breakpoint)}) {
        @content;
    }
}

@include responsive($breakpoint-very-small){
    display: block;
    text-align: right;
}
```

errors are

```
    error app/styles/scss/test.scss (Line 6: Invalid CSS after "(all) and (": ex
pected expression (e.g. 1px, bold), was "(min-width: 0) ...")
overwrite app/styles/css/test.css
Compilation took 0.169s
```

**Comment by lolmaus** [comment]
Works for me after fixing all your mistakes:

``` scss
$breakpoint-very-small: "(min-width: 0) and (max-width: 200px)";

@mixin responsive($breakpoint, $media: all) {
    @media ($media) and #{unquote($breakpoint)} {
        @content;
    }
}

@include responsive($breakpoint-very-small){
    display: block;
    text-align: right;
}
```

Demo: http://sassmeister.com/gist/986de5ad4706f51b2e8d
