### ISSUE TITLE
Extend inside a mixin references the last element in a selector twice

### ISSUE THREAD

**Issue by rskaggs** [sass/sass#1359]
I have created a mixin to help me deal with responsive breakpoints in IE8 (I know I shouldn't worry about IE8 too much).

``` scss
@mixin bp($width) {
    $map: $bp;
    $larger: true;
    $index: 10;
    $unique: unique-id();
    $compareWidth: strip-units($width);
    @while $larger {
        @if (map-has-key($map, bp-#{$index})) {
            @if (map-get($map, bp-#{$index}) < $compareWidth) {
                $map: map-remove($map, bp-#{$index});
                @debug $map;
            } @else {
                $larger: false;
            }
            $index: $index + 10;
        } @else {
            $larger: false;
        }
    }
    %bpStatement-#{$unique} {
        @content;
    }
    @media only screen and (min-width: $width) {
        @content;
    }
    @each $class, $value in $map {
        .lt-ie9 .#{$class} & {
            @extend %bpStatement-#{$unique};
        }
    }
}
```

When I run:

``` scss
@include bp(150em) {
     margin-left: -80em;
}
```

It produces: 

``` scss
.lt-ie9 .bp-150 .hero img img, .lt-ie9 .bp-160 .hero img img {
  margin-left: -80px;
}
@media only screen and (min-width: 150em) {
  .hero img {
    margin-left: -80px;
  }
}
```

I can get around this temporarily by not using an extend and just putting content directly in the each statement. However, I was hoping to use extend to keep the repetition down.

**Comment by nex3** [comment]
It's hard to tell for sure since you haven't provided code that I can run, but it looks like you're defining the placeholder selector you're extending within the same context as the class you're extending it from. You're effectively writing

``` scss
img {
  %bp-Statement {margin-left: -80em}
  .lt-ie9 .bp-150 .hero img {@extend %bp-Statement}
}
```

Since the extender and the extendee are both nested within `img`, you end up with two `img`s in the result.
