### ISSUE TITLE
how to apply Placeholder for  @keyframes? 

### ISSUE THREAD

**Issue by xmlking** [sass/sass#1360]
both of the following syntax are not working:(

``` scss
//%@keyframes rollIn {
@keyframes %rollIn {
  0% { opacity: 0; transform: translateX(-100%) rotate(-120deg);}
  100% { opacity: 1; transform: translateX(0px) rotate(0deg);}
}
```
