### ISSUE TITLE
@keyframes interpolation

### ISSUE THREAD

**Issue by gespinha** [sass/sass#1363]
Hi there,

Is '@keyframes' interpolation planned for the future? If so, do you know when can we do something like this?

``` css
@mixin key($prefix)
    @#{$prefix}keyframes stuff
        background: #f00
```

Thanks ;)
