### ISSUE TITLE
Isolated Function Calls

### ISSUE THREAD

**Issue by joshuabambrick** [sass/sass#1370]
As it stands the line `myFunction($myParam);` is invalid. I think that this should be valid. You can create functions with useful side effects that do not return any useful value, such as `null`, however, the current syntax rules require that you use the value returned from a function for example as part of an assignment operation. 

An example, from my own project, of where this might be useful is setting up a colour map. I have a function in one file that allows you to add a colour to the map, whilst checking that it isn't already there:

```
$colours: ();

@function addColour($colourName, $colour) {
    @if (map-has-key($colours, $colourName)) {
        @warn "Colour `#{$colourName}` already set in $colours.";
    } @else {
        $colours: map-merge($colours, ($colourName: $colour));
    }

    @return null;
}
```

However, the simple line `addColour(fullWhite, #ffffff);` is not valid SASS, and instead to use this function we have to do something like an assignment. This could be made neater if we just permit isolated function calls.

**Comment by Snugug** [comment]
Duplicate of #1348

**Comment by chriseppstein** [comment]
This can be easily implemented as a mixin that creates no CSS output.

``` scss
$colours: ();

@mixin addColour($colourName, $colour) {
    @if (map-has-key($colours, $colourName)) {
        @warn "Colour `#{$colourName}` already set in $colours.";
    } @else {
        $colours: map-merge($colours, ($colourName: $colour)) !global;
    }
}

@include addColour(whimsical-red, #CCCCC0);
```
