### ISSUE TITLE
Nested `&` will result strange line break with `nested` or `extended` style

### ISSUE THREAD

**Issue by hail2u** [sass/sass#1373]
If I write nested `&` like this:

``` scss
.foo,
.bar,
.baz {
  .qux &:before {
    content: "test";
  }
}
```

I get:

``` css
.qux .foo:before, .qux
.bar:before, .qux
.baz:before {
  content: "test"; }
```

It should be:

``` css
.qux .foo:before,
.qux .bar:before,
.qux .baz:before {
  content: "test"; }
```

Tested on Sass 3.4.0.rc.3,  ruby 2.0.0p353 (2013-11-22) [x64-mingw32].

**Comment by brian-hay** [comment]
Ditto here, another example:

``` scss
.foo a,
.bar a {
  &:hover, &:focus {
    color: red;
  }
}
```

Results in:

``` css
.foo a:hover, .foo a:focus,
.bar a:hover,
.bar a:focus {
  color: red;
}
```

Note: Only the first 2 selectors in the rule are incorrectly on the single line.

Instead of:

``` css
.foo a:hover,
.foo a:focus,
.bar a:hover,
.bar a:focus {
  color: red;
}
```

**Comment by nex3** [comment]
@brian-hay I'd expect that to produce

``` scss
.foo a:hover, .foo a:focus,
.bar a:hover, .bar a:focus {
  color: red;
}
```
