### ISSUE TITLE
Invalid @keyframes syntax generated when importing a file containing keyframes into a nested class

### ISSUE THREAD

**Issue by F21** [sass/sass#1383]
I am using SCSS 3.4.0 on Ubuntu 14.04 64-bit.

I have the following files:

`main.scss`:

``` scss
.test{
    @import "_keyframe";
}
```

`_keyframe.scss`

``` scss
.test-spin {
  -webkit-animation: spin 2s infinite linear;
  -moz-animation: spin 2s infinite linear;
  -o-animation: spin 2s infinite linear;
  animation: spin 2s infinite linear;
}

@-moz-keyframes spin {
  0% { -moz-transform: rotate(0deg); }
  100% { -moz-transform: rotate(359deg); }
}
@-webkit-keyframes spin {
  0% { -webkit-transform: rotate(0deg); }
  100% { -webkit-transform: rotate(359deg); }
}
@-o-keyframes spin {
  0% { -o-transform: rotate(0deg); }
  100% { -o-transform: rotate(359deg); }
}
@keyframes spin {
  0% {
    -webkit-transform: rotate(0deg);
    transform: rotate(0deg);
  }
  100% {
    -webkit-transform: rotate(359deg);
    transform: rotate(359deg);
  }
}
```

This is the result (notice the invalid `@keyframe` syntax):

``` css
test-spin {
  -webkit-animation: spin 2s infinite linear;
  -moz-animation: spin 2s infinite linear;
  -o-animation: spin 2s infinite linear;
  animation: spin 2s infinite linear;
}
@-moz-keyframes spin {
  .test {
    0% {
      -moz-transform: rotate(0deg);
    }
    100% {
      -moz-transform: rotate(359deg);
    }
  }
}
@-webkit-keyframes spin {
  .test {
    0% {
      -webkit-transform: rotate(0deg);
    }
    100% {
      -webkit-transform: rotate(359deg);
    }
  }
}
@-o-keyframes spin {
  .test {
    0% {
      -o-transform: rotate(0deg);
    }
    100% {
      -o-transform: rotate(359deg);
    }
  }
}
@keyframes spin {
  .test {
    0% {
      -webkit-transform: rotate(0deg);
      transform: rotate(0deg);
    }
    100% {
      -webkit-transform: rotate(359deg);
      transform: rotate(359deg);
    }
  }
}
```

**Comment by DirtyHerri** [comment]
May be related:
SASS 3.4 converts 

``` css
@keyframes bounce_circleG {
  0% {
  }

  50% {
    background-color:#000000
  }

  100% {
  }
}
```

to

``` css
@keyframes bounce_circleG {
  0%;
  50% {
    background-color: #000000; }
  100%; }
```

This is ok for most browers. But not Safari (desktop and mobile).

SASS 3.3 converts it to

``` css
@keyframes bounce_circleG {
  50% {
    background-color: black; } }
```

Which seems to work for all browers i tested.
