### ISSUE TITLE
:not() with attribute selectors broken

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#1385]
This fails to parse:

``` scss
a:not([href^='http://']) {
    color: red;
}
```

Originally reported here: https://github.com/Compass/compass/issues/1777 by @ryanburnett.
