### ISSUE TITLE
Empty keyframes rules are generated incorrectly

### ISSUE THREAD

**Issue by nex3** [sass/sass#1391]
From [this comment](https://github.com/sass/sass/issues/1383#issuecomment-52856710):

SASS 3.4 converts 

``` css
@keyframes bounce_circleG {
  0% {
  }

  50% {
    background-color:#000000
  }

  100% {
  }
}
```

to

``` css
@keyframes bounce_circleG {
  0%;
  50% {
    background-color: #000000; }
  100%; }
```

This is ok for most browers. But not Safari (desktop and mobile).

SASS 3.3 converts it to

``` css
@keyframes bounce_circleG {
  50% {
    background-color: black; } }
```

Which seems to work for all browers i tested.
