### ISSUE TITLE
mixin not replacing $name with parameter

### ISSUE THREAD

**Issue by drgeoffreysimpson** [sass/sass#1399]
For the sass code:

``` scss
@mixin keyframes($name){
  @-webkit-keyframes $name{
    @content;
 }
}

@include keyframes(testingName){
 0%{
        opacity:0;
}
100% {
        opacity:1;
}
}
```

The following is the generated output for 3.4.1:

``` css
@-webkit-keyframes **$name** {
  0% {
    opacity: 0; }
  100% {
    opacity: 1; } }
```

Under previous versions (3.3.14 for example), the correct css is generated:

``` css
@-webkit-keyframes **testingName** {
  0% {
    opacity: 0; }
  100% {
    opacity: 1; } }
```
