### ISSUE TITLE
Extra arguments passed to fixed arity function don't cause error

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#1408]
This should be an error. 

``` scss
@mixin foo($a, $b) {
  .foo { #{$a}: $b; }
}
$args: (color, red, extra-arg, another-extra-arg);
@include foo($args...);
```

It should behave exactly like this:

``` scss
@mixin foo($a, $b) {
  .foo { #{$a}: $b; }
}
@include foo(color, red, extra-arg, another-extra-arg);
```

Which raises:

```
Syntax error: Mixin foo takes 2 arguments but 4 were passed.
        on line 4 of standard input, in `foo'
        from line 4 of standard input
  Use --trace for backtrace.
```
