### ISSUE TITLE
variables as default arguments for mixins

### ISSUE THREAD

**Issue by ghost** [sass/sass#141]
i think it's currently impossible to do this:

<pre>
   @mixin anything($color: $default-color-dark) {
  background-color: $color;
}
</pre>

It gives me an error on the include.

I don't see too much reason for default values, when they don't accept other variables.

Am I missing something?

**Comment by matthee** [comment]
i didn't figure this out either - anything changed since july?

if not i would appreciate this feature as well ;)

**Comment by chriseppstein** [comment]
It works for me.

``` scss

$default-color-dark: blue;
@mixin anything($color: $default-color-dark) {
  background-color: $color;
}
div { @include anything; }
```

becomes:

``` css
div {
  background-color: blue; }
```
