### ISSUE TITLE
@extend only extends first selector

### ISSUE THREAD

**Issue by pyronaur** [sass/sass#1414]
This makes no sense to me at all:

``` sass
%extendor
  color: blue
  &:hover
    color: red
.something
  &, .something-else &
    @extend %extendor
```

Compiles to:

``` css
.something, .something-else .something {
  color: blue;
}
.something:hover {
  color: red;
}

```

Where did `.something-else .something:hover` go ?
