### ISSUE TITLE
@extend within @media throws error if %selector also exists outside the @media

### ISSUE THREAD

**Issue by maranomynet** [sass/sass#1426]
Should this throw an error?

``` scss
@media screen {
  %foo { content: 'screen'; } 
  .button { @extend %foo; }
}
@media print {
  %foo { content: 'print'; }
}
```

It seems to me that `%foo` within print @media should just be silently ignored.

I realize that workarounds exist, but should workarounds be required at all?
