### ISSUE TITLE
SCSS and “:host([active])” (Web Components)

### ISSUE THREAD

**Issue by nazar-pc** [sass/sass#1436]
I need such construction in scss:

``` scss
:host {
    background: #fff;

    &([active]) {
        background: #000;
    }
}
```

meaning output like:

``` css
:host {
    background: #fff;
}
:host([active]) {
    background: #000;
}
```

But I can't get it working any way I've tried. Is there any way to escape parentheses I don't know or something not overcomplicated?

Just inserting piece of raw css like `code` in CoffeeScript would be great, but I do not see anything like this in documentation.

**Comment by Panya** [comment]
Something like:

``` scss
:host {
    background: #fff;

    @at-root #{&}([active]) {
        background: #000;
    }
}
```
