### ISSUE TITLE
":host()" causes error (Web Components)

### ISSUE THREAD

**Issue by nazar-pc** [sass/sass#1437]
``` scss
:host() {
   color : #000;
}
```

Simple and natural syntax for Web Components, causes error in SCSS, while:

``` scss
:host([some-attribute]) {
   color : #000;
}
```

works perfectly.
