### ISSUE TITLE
Extending is extending from multiple locations

### ISSUE THREAD

**Issue by Fernker** [sass/sass#1446]
I recently came across a weird situation and I'm not sure if this is how Sass should compile the code.  An example is below where the `.spinner` is extending `.icon` but `.icon` has been declared in two places (one place as a root declaration and another as a nested child).  The compiled code is not what I would have expected:

```
/*Sass*/
.icon{
  background-size: cover;
}
.btn{
  border: 5px;
  &--round{
    border: 50%;
    .icon{
      vertical-align: top;
    }
  }
}
.spinner{
  @extend .icon;
}


/*CSS*/
.icon, .spinner {
   background-size: cover;
}
.btn {
  border: 5px;
}
.btn--round {
  border: 50%;
}
.btn--round .icon, .btn--round .spinner {
  vertical-align: top;
}
```

As you can see in the compiled code, the last selector has a `.btn--round .spinner` when I wouldn't think that should be there since in reality I'm extending `.icon` not `.btn--round .icon`.

**Comment by cimmanon** [comment]
This is behavior is documented in the Sass documentation:

``` scss
#context a%extreme {
  color: blue;
  font-weight: bold;
  font-size: 2em;
}

.notice {
  @extend %extreme;
}
```

Compiles to:

``` css
#context a.notice {
  color: blue;
  font-weight: bold;
  font-size: 2em; }
```

http://sass-lang.com/documentation/file.SASS_REFERENCE.html#placeholders
