### ISSUE TITLE
:more-compact output style

### ISSUE THREAD

**Issue by ghost** [sass/sass#1447]
:compact

``` css
#main { color: #fff; background-color: #000; }
#main p { width: 10em; }
.huge { font-size: 10em; font-weight: bold; text-decoration: underline; }
```

:more-compact

``` css
#main{color:#fff;background-color:#000}
#main p{width:10em}
.huge{font-size:10em;font-weight:bold;text-decoration:underline}
```

This is how I always used to write my raw css and how I still write my scss.
Compact output style is not compact enough and compressed is not legible when deployed.
