### ISSUE TITLE
@charset stripped in :compressed output

### ISSUE THREAD

**Issue by mikefowler** [sass/sass#1449]
Yesterday I updated a project from 3.3 to 3.4 (specifically, 3.4.5), and it seems that `@charset "utf-8";` is being stripped from files compiled using `:compressed` style. I do not believe this is the intended result.
### Input

``` scss
body {
  font-family: "漢字仮名交じり文", sans-serif;
}
```
### Output (default)

`sass input.scss output.css`

``` scss
@charset "UTF-8";
body {
  font-family: "漢字仮名交じり文", sans-serif; }
```
### Output (compressed)

`sass --style=compressed input.scss output.css`

``` scss
body{font-family:"漢字仮名交じり文", sans-serif}
```
