### ISSUE TITLE
dynamic variables

### ISSUE THREAD

**Issue by brewster1134** [sass/sass#1450]
I am hoping someone with more sass knowledge can let me know if creating variables from a sass map is at all possible.  here is a contrived example of what i am trying to do...

``` scss
$colors-map: (
  "red": (
    dark: #aa142d
  ),
);

@each $name, $variations in $colors-map {
  @each $variation, $hex in $variations {
    $color-#{$name}-#{$variation}: $hex;
  }
}

.foo {
  background-color: $color-red-dark;
}
```

**Comment by lolmaus** [comment]
Duplicate.

PS Use maps.

**Comment by brewster1134** [comment]
could you link to a duplicate?

**Comment by brewster1134** [comment]
oops on closing..

I am using a map, however i want to dynamically create helper accessor variables for map values. Are you referring to different `maps`?

**Comment by nex3** [comment]
Duplicate of #132.

**Comment by brewster1134** [comment]
That issued resolved with using maps, and it sounds like my use case is not possible at the moment.  The reason I cant use maps is I need to keep support for existing variables names.  I was hoping to create those programmatically _from_ a map, but I will just maintain those manually for now.

thanks for the link!

**Comment by lolmaus** [comment]
@brewster1134, how come maps don't help you?

Instead of doing `$foo-#{$bar}`, you can do `map-get($foo, $bar)`.

If you find `map-get` too bulky, you can fix up a function to be used like this: `foo($bar)`.

**Comment by brewster1134** [comment]
they dont help because there is a large code base using colors as variables... `background-color: $color-black;`

this was previously just static variables... `$color-black: #000`

but i want to update to using a map to maintain our colors and generate those same variables

``` scss
$colors-map: (
  "black": #000
);
```

but in the end, i still need to support the `$color-black` style variables

**Comment by lolmaus** [comment]
@brewster1134, 

> but in the end, i still need to support the $color-black style variables

This is the root of your problem. Looks like you're dealing with legacy Sass 3.2 code that you have no power to refactor.

As a workaround, you can use a template engine to define variables dynamically. See how Compass [was doing it](https://github.com/Compass/compass/blob/0.12.7/lib/compass/sprite_importer/content.erb) in `v0.12`.

**Comment by brewster1134** [comment]
im just storing hex values in a variable so i wouldn't say its legacy, i just want a drop-in solution using maps that is easier to maintain.

is there any plans on supporting variable interpolation in the future?

**Comment by lolmaus** [comment]
> im just storing hex values in a variable so i wouldn't say its legacy, i just want a drop-in solution using maps that is easier to maintain.

Replace

``` scss
$color-red: #a00;
html { foo: $color-red; }
```

with

``` scss
$colors: ('red': #a00);
html { foo: map-get($colors, 'red'); }
```

or even better with:

``` scss
@function col($col) {
  @return map-get($colors, '#{$col}');
}

$colors: ('red': #a00);
html { foo: col(red); }
```

> is there any plans on supporting variable interpolation in the future?

This question has been asked many times since 2011. You've been linked to the [issue](https://github.com/sass/sass/issues/132) where this question is answered.

**Comment by brewster1134** [comment]
your suggestion isn't a drop-in replacement... the current code would need migrated to use the function instead of the variable.   many things depend on those variables, so I was looking for a smarter way to create them.  This is why the resolution of issue #132 doesnt help my issue.

I dont see the answer to future support in #132. It shows how to use maps, which again, is not what i am looking for.

**Comment by cimmanon** [comment]
@brewster1134  The answer to the "we want interpolation for variable names" feature request is "we're giving you mappings instead"  (see: https://github.com/sass/sass/issues/329#issuecomment-4625697).  There was never a promise that we would get variable variables or dynamic variable creation.

**Comment by brewster1134** [comment]
I have understood that since i posted this issue.  I have always been using a map to store the values actually, and have no problem with a helper function to access it.  The reason for my post was in hopes there was  a technique to get the same effect for my variable creation needs, but it looks like there isn't. 

I should have made it more clear in my original post that providing the variables was a necessity, and the map.function approach won't work for me. :smile:

**Comment by magbicaleman** [comment]
```scss
@function col($col) {
  @return map-get($colors, '#{$col}');
}

$colors: ('red': #a00);
html { foo: col(red); }
```

This is pretty cool, but now I'd have to make a function to access each map that I may have created. At the very least I was hoping I could do partial application, by having a function return a function so that I can use a @each directive to generate some things for me.

Alternatively, this would be kind of nice but doesn't solve what I mentioned above.

```scss
$map('key')
```
