### ISSUE TITLE
Parent selector inside of :not() isn't expanded out  

### ISSUE THREAD

**Issue by craigsssmith** [sass/sass#1464]
Given the following SCSS

``` scss
.baz {
  *:not(&) {
    color: blue;
  }
}
```

I would expect the following output:

``` css
.baz *:not(.baz) {
  color: blue;
}
```

However, the parent selector isn't expanded, giving:

``` css
.baz *:not(&) {
  color: blue;
}
```

What's more, if this is combined with a single usage of @extend then SASS throws an error – even when the extend is entirely separate. For example:

``` scss
.foo {
  color: red;
}
.bar {
  @extend .foo;
}
.baz {
  *:not(&) {
    color: blue;
  }
}
```

As of 3.4, this triggers the following error:

```
NoMethodError: undefined method `specificity' for &:Sass::Selector::Parent
```
