### ISSUE TITLE
Spaces between value and !important are preserved in compressed mode

### ISSUE THREAD

**Issue by KittyGiraudel** [sass/sass#1482]
Input:

``` scss
test {
  property: value                          !important;
}
```

Output:

``` css
test{property:value                          !important}
```
