### ISSUE TITLE
Using only 1 argument for if()

### ISSUE THREAD

**Issue by whaaaley** [sass/sass#1483]
I have a mixin like this to add a dash on the end of a value.

```
@mixin dash( $name: null ) {

    $name: if( $name != null, $name + '-' ); // MAYDAY!

    $name: if( $name != null, $name + '-', $name ); // I'm okay.

    @if $name != null { $name: $name + '-'; } // I'm okay.

}
```

I'd expect either a `null` value, or the default value, to be assigned if no other value is specified. I'm doing this often so it'd be nice to not have to add a null value every time.

Using `@if` isn't terrible, but it would be more readable when looking through my list of variables.

**Comment by andrewjtait** [comment]
Why not create your own `@function` which contains the logic you want to use? This could also tidy the mixin up even further.

Something along the lines of:

``` scss
@function add_dash($string) {
  @return if($string, $string + "-", null);
}

@mixin dash($name: null) {
  $name: add_dash($name);
  // ...
}
```
