### ISSUE TITLE
Floor function inside of a while loop returns wrong value

### ISSUE THREAD

**Issue by wguldin** [sass/sass#1490]
Hi, 

I could be doing something wrong here, but it appears that the floor() function isn't working in a while loop properly. I have the following code block, which is meant to give a list of selectors for rating stars on reviews.

```
$rating: 0.0;

@while $rating <= 5.0 {

  $wholeRating: floor($rating);
  $decimalRating: $rating - $wholeRating;

  .rating[data-rating="#{$rating}"]::after {  
     wholeNum: $wholeRating;
     deciNum: $decimalRating;
  }

  $rating: $rating + .1; // Increment the loop.
}
```

This works as expected, if the given rating is 2.0, 3.0 or 4.0: 

```
.rating[data-rating="2.0"]::after {
  wholeNum: 2;
  deciNum: 0.0;
}
```

But it reports $wholeNumber as 0 for the value of one:

```
.rating[data-rating="1.0"]::after {
  wholeNum: 0;
  deciNum: 1.0;
}
```

And it does something similar for 5:

```
.rating[data-rating="5.0"]::after {
  wholeNum: 4;
  deciNum: 1.0;
}
```

A gist showing the issue:

https://gist.github.com/wguldin/1c9d7d72acc4e54e74c6

I'm sure I'm doing something wrong, but it didn't make sense that this would work for some of the values and not others.

**Comment by cimmanon** [comment]
This isn't specific to Sass.  It is a well known issue surrounding floats in general (see: http://floating-point-gui.de/).  You'll want to multiply your initial value by 10 and then divide by 10 when you go to display it:

``` scss
$rating: 0;

@while $rating <= 50 {

  $wholeRating: floor($rating / 10);
  $decimalRating: $rating % 10;

  .rating[data-rating="#{$rating / 10}"]::after {  
     wholeNum: $wholeRating;
     deciNum: $decimalRating;
  }

  $rating: $rating + 1; // Increment the loop.
}
```
