### ISSUE TITLE
Deep extend loses selectors in certain cases

### ISSUE THREAD

**Issue by mgol** [sass/sass#1495]
The following SCSS input:

``` scss
%a {
    &::-webkit-scrollbar {
        color: green;
    }
}
%b {
    @extend %a;
}

.a {
    .b {
        @extend %a;
    }

    .c {
        .b {
            @extend %b;
        }
    }
}
```

is compiled via Ruby Sass (3.4.5) to:

``` css
.a .c .b::-webkit-scrollbar, .a .b::-webkit-scrollbar {
  color: green; }
```

and via libsass (using node-sass 1.1.4) to:

``` css
.a .b::-webkit-scrollbar {
  color: green; }
```

However, if I just change `::-webkit-scrollbar` in the source to, e.g., `.d`, Ruby Sass gives me:

``` css
.a .d.b {
  color: green; }
```

i.e. the same what libsass does.

Related libsass bug report: https://github.com/sass/libsass/issues/592

**Comment by nex3** [comment]
Note that the test case can be simplified considerably:

``` scss
%a::-webkit-scrollbar {
  color: green;
}

.a {
  .b {
    @extend %a;
  }

  .c .b {
    @extend %a;
  }
}
```

Anyway, the behavior you're seeing is intended. The selector `.a .c .d.b` is a subselector of `.a .d.b` (that is, everything the former matches is also matched by the latter). As such, it's safe to trim the latter.

The reason that this doesn't happen with `::-webkit-scrollbar` has to do with specificity. Sass guarantees that when you write `A {@extend B}`, the generated selectors will have specificity greater than or equal to the specificity of `A` (we call this the "extender"). When Sass looks at the generated selector `.a .c .d.b`, it remembers that its extender was `.a .c .b`. Because `.a .c .b` has the same specificity as `.a .d.b` **and** `.a .c .d.b` is a subselector of `.a .d.b`, it's safe to remove `.a .c .d.b`.

With `::-webkit-scrollbar`, on the other hand, the selector we're comparing against is `.a .b::-webkit-scrollbar`. Pseudoelements have lower specificity than classes, so this has less specificity than `.a .c .b`, which means that `.a .c .b::-webkit-scrollbar` can't be trimmed or we'd violate our guarantee.
