### ISSUE TITLE
Nested `:not` selectors don’t work

### ISSUE THREAD

**Issue by swashcap** [sass/sass#1499]
Sample code:

``` scss
.analytics__section-1,
.analytics__section-2,
.analytics__section-3 {
    a:not(.btn) {
        color: $blue;
        text-decoration: underline;

        &:focus,
        &:hover {
            color: $orange;
        }
    }
}
```

Expected result:

``` css
.analytics__section-1 a:not(.btn),
.analytics__section-2 a:not(.btn),
.analytics__section-3 a:not(.btn) {
  color: #98c5d9;
  text-decoration: underline;
}
.analytics__section-1 a:not(.btn):focus,
.analytics__section-1 a:not(.btn):hover,
.analytics__section-2 a:not(.btn):focus,
.analytics__section-2 a:not(.btn):hover,
.analytics__section-3 a:not(.btn):focus,
.analytics__section-3 a:not(.btn):hover {
  color: #e68f73;
}
```

(This is valid CSS, checked [here](http://jigsaw.w3.org/css-validator/#validate_by_input), and renders fine in at least Chrome.)

This throws the following Sass error:

``` shell
/Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/selector/abstract_sequence.rb:96:in `block in _specificity': undefined method `specificity' for [:not(.btn)]:Array (NoMethodError)
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/selector/abstract_sequence.rb:94:in `each'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/selector/abstract_sequence.rb:94:in `_specificity'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/selector/abstract_sequence.rb:86:in `specificity'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/selector/abstract_sequence.rb:96:in `block in _specificity'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/selector/abstract_sequence.rb:94:in `each'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/selector/abstract_sequence.rb:94:in `_specificity'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/selector/abstract_sequence.rb:86:in `specificity'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/selector/sequence.rb:550:in `block (3 levels) in trim'
  from /Users/username/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/set.rb:263:in `each_key'
  from /Users/username/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/set.rb:263:in `each'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/selector/sequence.rb:549:in `map'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/selector/sequence.rb:549:in `block (2 levels) in trim'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/selector/sequence.rb:544:in `reject'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/selector/sequence.rb:544:in `block in trim'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/selector/sequence.rb:543:in `each'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/selector/sequence.rb:543:in `each_with_index'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/selector/sequence.rb:543:in `trim'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/selector/sequence.rb:123:in `do_extend'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/selector/comma_sequence.rb:71:in `block in do_extend'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/selector/comma_sequence.rb:70:in `map'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/selector/comma_sequence.rb:70:in `do_extend'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/tree/visitors/extend.rb:44:in `visit_rule'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/tree/visitors/base.rb:36:in `visit'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/tree/visitors/extend.rb:28:in `visit'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/tree/visitors/base.rb:52:in `map'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/tree/visitors/base.rb:52:in `visit_children'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/tree/visitors/extend.rb:37:in `visit_children'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/tree/visitors/base.rb:38:in `visit'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/tree/visitors/extend.rb:28:in `visit'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/tree/visitors/extend.rb:15:in `visit'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/tree/root_node.rb:39:in `css_tree'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/tree/root_node.rb:29:in `render_with_sourcemap'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/engine.rb:368:in `_render_with_sourcemap'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/engine.rb:285:in `render_with_sourcemap'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/exec/sass_scss.rb:396:in `run'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/exec/sass_scss.rb:62:in `process_result'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/exec/base.rb:52:in `parse'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/lib/sass/exec/base.rb:19:in `parse!'
  from /Users/username/.rvm/gems/ruby-2.1.2/gems/sass-3.4.6/bin/sass:13:in `<top (required)>'
  from /Users/username/.rvm/gems/ruby-2.1.2/bin/sass:23:in `load'
  from /Users/username/.rvm/gems/ruby-2.1.2/bin/sass:23:in `<main>'
  from /Users/username/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
  from /Users/username/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```
- Operating System: **OS X 10.10**
- Ruby: **ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]**
- Sass: **Sass 3.4.6 (Selective Steve)**
