### ISSUE TITLE
Parent selector interpolation in @extend

### ISSUE THREAD

**Issue by garetht** [sass/sass#1503]
When attempting to reference the parent selector from within an extended placeholder, attempting to access its value through interpolation does not work:

``` scss
%foo {
  height: 20px;
  &.baz {
    width: 20px;
  }
  @at-root #{&}-baz {
    width: 20px;
  }
}

.bar {
  @extend %foo;
}
```

produces (in 3.4.7)

``` scss
.bar {
  height: 20px;
}
.baz.bar {
  width: 20px;
}
```

It seems the parent selector works fine to produce `.baz.bar`, but unexpectedly the rule `.bar-baz` is missing.
