### ISSUE TITLE
Custom selectors

### ISSUE THREAD

**Issue by gavinmcfarland** [sass/sass#1509]
When working with html attributes, CSS can be a bit messy. For example...

``` css
[am-button] {
   padding: 10px;
   background: green;
}

[am-button*="medium"] {
  padding: 15px;
  font-size: 1.2em;
}

[am-button*="large"] {
  padding: 20px;
  font-size: 1.4em;
}
```

I could create a mixin which will helps with this

``` sass
@mixin button($value: "") {
    @if $value != ""  {
        [am-button] {
            @content;
        }
    }
    [am-button="#{$value}"] {
        @content; 
    }
}

@include button() {
   padding: 10px;
   background: green;
}

@include button(medium) {
  padding: 15px;
  font-size: 1.2em;
}

@include button(large) {
  padding: 20px;
  font-size: 1.4em;
}
```

But it's not much cleaner and I'd need to create a different mixin for each alias I want to support.

Would you consider adding something to SASS which helps with this?

**Comment by lolmaus** [comment]
Hey @sevenupcan, your request is very vague and is likely to be shot down on sight.

Do you have any specific suggestion in mind?

PS Have you looked at the indented `.sass` syntax? Here's how it would look:

``` sass
+button(large)
  padding:   20px
  font-size: 1.4em
```

I can't imagine anything cleaner than that.

**Comment by nex3** [comment]
Mixins exist precisely to provide you with the ability to create your own shortcuts without them having to be built into the language. If you don't want to create a separate mixin for each attribute name, consider defining one that sets a context:

``` scss
$-attribute-context: null;
@mixin with-attribute($name) {
  $old-attribute-context: $-attribute-context;
  $-attribute-context: $name !global;
  @content;
  $-attribute-context: $old-attribute-context;
}

@mixin attr($value: null) {
  @if not $-attribute-context {
    @error "attr() must be used within with-attribute().";
  }

  $selector: if($value,
    '[#{$-attribute-context}="#{$value}"]', '[#{$-attribute-context}]');
  #{$selector} {
    @content;
  }
}

@include with-attribute(am-button) {
  @include attr() {
    padding: 10px;
    background: green;
  }

  @include attr(medium) {
    padding: 15px;
    font-size: 1.2em;
  }

  @include attr(large) {
    padding: 20px;
    font-size: 1.4em;
  }
}
```

**Comment by gavinmcfarland** [comment]
I didn't think my post was vague I just didn't want to propose a solution because I wanted to see what people thought before I put forward my own theories.

@nex3 While the example you've provided does do the job of solving the problem in my example, it still quite messy and with more complicated scenarios it doesn't replicate very well.

For example if you want to write lots of variants of the following:

``` css
[am-column*="2"] > *  {
  font-size: 1.2em;
}
```

It becomes difficult to read and as far as I know this is not possible to solve with mixins.

If you've used CSS Crush before you might have seen it has a feature which allows you to create [selector aliases](http://the-echoplex.net/csscrush/#core--selector-aliases) which helps when writing your styles.

They work like this:

```
/* Define the selector alias with arguments */
@selector am-column [am-column*="#(0)"];


/* Call the alias with arguments passed through */

:am-column(2) > * {
    font-size: 1.2em;
}
```

From your post though it sounds like you don't have any plans on expanding Sass to support something like this.

**Comment by cimmanon** [comment]
@sevenupcan You aren't restricted to mixins if what you're after is selector name reuse, you can use functions and variables for this purpose as well.

``` scss
@function button($count) {
    @return '[am-column*="#{$count}"]';
}

#{button(2)} > * {
    font-size: 1.2em;
}
```

or

``` scss
$sel-name: '.my-really-simple-but-long-selector';

#{$sel-name}, .foo {
  color: red;
}
```
