### ISSUE TITLE
How to update a global variable from mixin or function?

### ISSUE THREAD

**Issue by hittas** [sass/sass#1511]
For example:

``` scss
$flex-legacy: ();

@mixin my-flex($param) {
    @if $flex-support == false {
        $flex-legacy: map_merge($flex-legacy, (nth(&, 1): $param)); // need global
    } @else {
        @include flexbox($params, $version: 3); // mixin from compass
    }
}

#container {
    @include my-flex((display: flex));
}

@debug $flex-legacy; // now empty but I need (#container: (display: flex))
```

**Comment by nex3** [comment]
Use the `!global` flag:

``` scss
$flex-legacy: ();

@mixin my-flex($param) {
    @if $flex-support == false {
        $flex-legacy: map_merge($flex-legacy, (nth(&, 1): $param)) !global; // need global
    } @else {
        @include flexbox($params, $version: 3); // mixin from compass
    }
}
```
