### ISSUE TITLE
@supports doesn't maintain nested conditions

### ISSUE THREAD

**Issue by xzyfer** [sass/sass#1512]
Tested on 3.4.7.

Input

```
@supports ((foo: bar) and (foo: bar)) or (foo: bar) {
  foo: bar;
}
```

Expected output

```
@supports ((foo: bar) and (foo: bar)) or (foo: bar) {
  foo: bar;
}
```

Actually output

```
@supports (foo: bar) and (foo: bar) or (foo: bar) {
  foo: bar;
}
```

**Comment by nex3** [comment]
Sass only inserts parentheses when they're necessary to preserve the semantics. In this case, `(A and B) or C` is equivalent to `A and B or C`, so the parentheses aren't inserted.

**Comment by mgreter** [comment]
I just had a look at this and I actually agree with @xzyfer.

Take this example:

``` CSS
@supports ((foo: foo) or (bar: bar)) and (baz: baz)
```

Ruby Sass (3.4.12):

``` CSS
@supports (foo: foo) or (bar: bar) and (baz: baz)
```

Libsass:

``` CSS
@supports ((foo: foo) or (bar: bar)) and (baz: baz)
```

IMO the output of Ruby Sass changes the semantics. The original expression would only evaluate true if `baz: baz` is true. In the Ruby Sass output, the whole expression is also true if only `foo: foo` is true. Either the semantics of css for `and`/`or` is strange or am I missing something else? IMO `and` has always higher precedence than `or` operations!? Although I couldn't find anything specific in the [specs](http://dev.w3.org/csswg/mediaqueries/#mq-syntax).

**Comment by cimmanon** [comment]
I'm going to have to agree here.  Browsers are clearly following a different set of rules than you would expect when it comes to logical operators.

SQL:

```
chris=> select 1 where true and false or true;
 ?column?
----------
        1
(1 row)

chris=> select 1 where (true and false) or true;
 ?column?
----------
        1
(1 row)

chris=> select 1 where true and (false or true);
 ?column?
----------
        1
(1 row)
```

Haskell:

```
Prelude> True && False || True
True
Prelude> (True && False) || True
True
Prelude> True && (False || True)
True
```

CSS:

``` css
@supports (display: flex) and (foo: bar) or (flex-wrap: wrap) {
  body {
    background: goldenrod;
  }
}
/* false */

@supports ((display: flex) and (foo: bar)) or (flex-wrap: wrap) {
  .foo {
    background: tomato;
  }
}
/* true */

@supports (display: flex) and ((foo: bar) or (flex-wrap: wrap)) {
  .bar {
    background: pink;
  }
}
/* true */
```

http://codepen.io/cimmanon/pen/JoaqVB

Edit:  found it in the specs

> To avoid confusion between ‘and’ and ‘or’, the syntax requires that both ‘and’ and ‘or’ be specified explicitly (rather than, say, using commas or spaces for one of them). Likewise, to avoid confusion caused by precedence rules, the syntax does not allow ‘and’, ‘or’, and ‘not’ operators to be mixed without a layer of parentheses.

http://www.w3.org/TR/css3-conditional/

**Comment by mgreter** [comment]
Actually I'm not sure with whom you agree (you didn't clearly state that). But let me explain it a little more. The example given by @xzyfer is unfortunately not optimal, since the `and` comes before the `or`, and in this situation the parentheses don't make a difference, since the `and` will be evaluated first (as it should to its precedence). But this changes if you have the `or` first. The key here is that `and` has a higher precedence than `or`, so the parentheses are needed if we want to give `or` the highest precedence in the expression (and ruby sass seems to remove exactly these parentheses).

Take this haskell example:

``` haskell
Prelude> (True || False) && False
False
Prelude> True || False && False
True
```

Or in Perl

``` perl
perl -e 'print( (1 || 0) && 0, "\n");'
0
perl -e 'print( 1 || 0 && 0, "\n");'
1
```

I gave this example in my post above:

``` CSS
@supports ((foo: foo) or (bar: bar)) and (baz: baz)
```

Which ruby sass changes to:

``` CSS
@supports (foo: bar) or (foo: bar) and (foo: bar)
```

I actually created a test, and now comes the clue: It seems that the specs @cimmanon mentioned are implemented pretty strict, so that something like the following will always be ignored:

```
@supports (font-size: 10px) and (font-size: 10px) or (font-size: 10px) {
```

So take this example:

``` CSS
<html>
<head>
    <style>
        @supports ((font-size: 10px) and (font-size: 10px)) or (font-size: 10px) {
            .test:after { content: "works"; }
        }
        @supports (font-size: 10px) and (font-size: 10px) or (font-size: 10px) {
            .test:after { content: "unexpected"; }
        }
    </style>
</head>
<body>
    <div class="test"></div>
</body>
</html>
```

This actually shows `works` in every browser I tested (firefox, chrome, opera). That should prove that removing the parentheses actually does change the behavior, although in a different way than I expected!
//CC @nex3 @chriseppstein

**Comment by mgreter** [comment]
By the way, `@media` rules seem to have a slighly different rule, as they don't seem to allow any `or` ops at the top level ~~(although they seem to work when inside parantheses)~~.

``` CSS
<html>
<head>
    <style>
        @media ((min-width: 10px) or (min-width: 10px)), (min-width: 10px) {
            .test:after { content: "works"; }
        }
        @media (min-width: 10px) or (min-width: 10px) or (min-width: 10px) {
            .test:after { content: "unexpected"; }
        }
        @media (min-width: 10px) or (min-width: 10px) {
            .test:after { content: "nope"; }
        }
    </style>
</head>
<body>
    <div class="test"></div>
</body>
</html>
```

This also shows `works`. Looks like I've learned something new today;wouldn't have expected this. Anyway, these top `or`s could be converted to commas to create valid css (not sure if ruby sass wants to support that). Or you could give a warning for invalid rules.

Edit: The rules for `@media` seem to be even stranger. Actually they don't seem to allow any parentheses around "statements" at all, but "statements" can be or'ed by commas, even if some if the "statements" are wrapped in additional parentheses. Pretty weird actually, but browsers seem consistent in their behavior:

``` CSS
<html>
<head>
    <style>
        @media (min-width: 10px) and (min-width: 10px) {
            .test:after { content: "yes"; }
        }
        @media ((min-width: 10px)) and (min-width: 10px) {
            .test:after { content: "no"; }
        }
        @media (min-width: 10px) or (min-width: 10px) {
            .test:after { content: "nope"; }
        }
        @media (min-width: 10px) or (min-width: 10px) and (min-width: 10px) {
            .test:after { content: "not working"; }
        }
        @media ((min-width: 10px) and (min-width:11px) and (min-width:11px)) {
            .test:after { content: "not either"; }
        }
    </style>
</head>
<body>
    <div class="test"></div>
</body>
</html>
```

But the rules are slightly different for `@supports` as it would show `not either` with the example above, while `@media` shows `yes`. Very confusing indeed ...

**Comment by cimmanon** [comment]
@mgreter None of that validates, not the "or" operator, nor the nested parentheses with media queries.  The logical "or" and nested parentheses are only features of feature queries.  The logical "or" is done with a comma in media queries.

``` css
@media (min-width: 10px), (min-width: 11px) {
    .foo { color: red }
}
```
