### ISSUE TITLE
@content as map

### ISSUE THREAD

**Issue by hittas** [sass/sass#1514]
``` scss
$flex-list: ();

@mixin my-flex($flex: (), $no-flex: ()) {
    @if $flex-support == true {
        @include flexbox($flex, $version: 3);

    } @else {
        // now I use another param $no-flex
        $flex-list: map_merge($flex-list, ('#{nth(&, 1)}': $no-flex)) !global;
        // Is it possible to use @content for this in future?
        $flex-list: map_merge($flex-list, ('#{nth(&, 1)}': @content)) !global;
    }
}

#container {
    @include my-flex ((
            display: flex,
            flex-flow: row
        )) {
        overflow: hidden;
        position: relative;
    };
}

.noflex {
    @each $key, $value in $flex-list {
        #{$key} {
            @each $key2, $value2 in $value {
                #{$key2}: $value2;
            }
        }
    }
}
```
