### ISSUE TITLE
rgba() naively removes opacity value and casts to hex if it is 1

### ISSUE THREAD

**Issue by michaelfavia** [sass/sass#1518]
This is my first time delving into SASS source so please be gentle. The problem works like this:

For the purpose of animating something from transparent background to opaque you need to specify the color in rgba in css. Example:

rgba(0,0,0,0) transitioning to rgba(0,0,0,1) would fade to black.

unfortunately though SASS incorrectly assumes that because i specified a opacity value of 1 that i really wanted a hex value instead of the rgba color I specified. 

I understand why its doing it and I agree witht the principle just not the result in this case. From my case research I was able to see that preserving color formats is a bit of a touchy subject so i wanted to know if there was an opinion on the matter before I rolled a PR. 

The culprit line of code is in Color::to_s where the Color is cast to a string finally:
https://github.com/sass/sass/blob/84e55254674508a4006517fff636f750da39ed64/lib/sass/script/value/color.rb#L565

The short term workaround seems to be rgba(0,0,0,.999) but thats hard to swallow as a suggestion to give my guys.

**Comment by nex3** [comment]
`#000000` and `rgb(0, 0, 0, 1)` are considered identical by the spec. Is the current output just an issue of aesthetics, or is a browser actually treating the two syntaxes differently?

In general, we try to preserve the user's input format for colors, but `rgb()`, `rgba()`, `hsl()`, and `hsla()` are kind of special cases. The Sass functions support a superset of the input their CSS counterparts do, and in some cases allow users to use new CSS syntax and have it compiled to a form that older browsers will understand. Although there are probably some cases where preserving the input format of these functions is safe, in general it would be risky and inconsistent, so we just don't do it at all.

**Comment by tobymackenzie** [comment]
It _is_ treated differently by browsers (current FireFox and Chrome at least) for transitions.  A solution using a function and interpolation:

``` scss
@function forceRGBA($color, $opacity){
    $red: red($color);
    $green: green($color);
    $blue: blue($color);
    $open: 'rgba(';
    $close: ')';
    $comma: ',';
    @return #{$open}#{$red}#{$comma}#{$green}#{$comma}#{$blue}#{$comma}#{$opacity}#{$close};
}
div{
    background-color: rgba(#0f0, 0);
    transition: background-color 0.5s;
}
div:hover{
    background-color: forceRGBA(#0f0, 1);
}
```
