### ISSUE TITLE
Error: $map: null is not a map for 'map-get'

### ISSUE THREAD

**Issue by donaldallen** [sass/sass#1519]
I'm running `Sass 3.4.7 (Selective Steve)` through `gulp-ruby-sass`. I have a `_variables.scss` file with the following:

``` scss
$palettes: (
    grey: (
        base:       rgb(95, 96, 98),
        mid-light:  rgb(127, 128, 129),
        light:      rgb(159, 160, 161),
        x-light:    rgb(205, 205, 205),
        xx-light:   rgb(230, 230, 230)
    ),
    purple: (
        base: rgb(70, 22, 22),
        light: rgb(110, 33, 34)
    )
);

@function palette($palette, $tone: 'base') {
    @return map-get(map-get($palettes, $palette), $tone);
}
```

When I compile, I get the following error:

```
Error: $map: null is not a map for 'map-get'
    on line 16 of /var/folders/s5/919v_t0n4v590754yhdyddy0000gn/T/gulp-ruby-sass/base/_variables.scss
```

I'm lost as to why this is happening.

**Comment by cimmanon** [comment]
Duplicate: https://github.com/sass/sass/issues/1511

**Comment by nex3** [comment]
Works for me:

``` scss
// test.scss
$palettes: (
    grey: (
        base:       rgb(95, 96, 98),
        mid-light:  rgb(127, 128, 129),
        light:      rgb(159, 160, 161),
        x-light:    rgb(205, 205, 205),
        xx-light:   rgb(230, 230, 230)
    ),
    purple: (
        base: rgb(70, 22, 22),
        light: rgb(110, 33, 34)
    )
);

@function palette($palette, $tone: 'base') {
    @return map-get(map-get($palettes, $palette), $tone);
}

a {b: palette(grey)}
```

```
$ sass test.scss
a {
  b: #5f6062; }
```

**Comment by donaldallen** [comment]
I think it just might be something weird in my project. If I move to another project, and implement the same code, it works.

**Comment by gcasalett** [comment]
I know this has been closed for a while, but I wanted to chime in... I was having the same problem when I copied my color maps from one project to another (actually, I copied all the .scss files). I figured out that I was only getting that error when other .scss files were calling color palettes that did not exist in my new map. So if I was calling palette(brown), and that didn't exist on my new map, I got the error. 

Once I went through and removed all the calls to old colors, everything worked fine. Hope this helps someone!

**Comment by SammyDodgerr** [comment]
Anyone still having this problem, I ran into this issue and found a solution that has not been mentioned here.
Deleting all my unnecessary white space removed the error for some reason it doesn't compile properly with this white space in.
Hope this helps!

**Comment by ninest** [comment]
@gcasalett Thanks for the solution.

In my project, I had a function `raw-color` that takes a color and a variant, and returns a hexadecimal color.

I was getting the above error because I had tried to get the hexadecimal of a color that doesn't exist.

```scss
$raw-colors: (
  indigo: (
    50: #eef2ff,
    100: #e0e7ff,
    200: #c7d2fe,
  ),
  blue: (
    50: #eff6ff,
    100: #dbeafe,
    200: #bfdbfe,
  ),
  gray: (
    50: #f8fafc,
    100: #f1f5f9,
    200: #e2e8f0,
  ),
);

@function raw-color($color, $n) {
  @return map-get(map-get($raw-colors, $color), $n);
}
```

I had accidentally typed

```scss
.primary-container {
	background-color: raw-color(primary, 200);
}
```

when I should have typed

```scss
.primary-container {
	background-color: raw-color(indigo, 200);
}
```
