### ISSUE TITLE
Adding a tag selector with & generates bad CSS

### ISSUE THREAD

**Issue by jzila** [sass/sass#1520]
Looks like the parser just does a blind concatenation for nested selectors. Sometimes it should be more intelligent. For example:

``` css
.foo {
    .bar {
        &select {
            // stuff
        }
    }
}
```

generates:

``` css
.foo .barselect {
    // stuff
}
```

expected:

``` css
.foo select.bar {
    // stuff
}
```

My current workaround:

``` css
.foo {
    .bar {
    }
    select {
        @extend .bar;
    }
}
```

**Comment by Snugug** [comment]
What you're seeing here is the output of (is there an official name for this besides BEM which it isn't?) "selector name extension", specifically that a nested `&` with not space after it is treated like an in-place way to add to the parent selector name. It's most commonly used with the BEM pattern:

``` scss
.foo {
  &--bar {
    // stuff
  }
}
```

Sass has never supported nesting a tag and having the tag overqualify the parent. Maybe it should (I'd argue only by placing the `&` after the selector name directly, but that goes against the semantics of the `&`), but the current behavior is expected given the syntax you're using.

**Comment by jzila** [comment]
Fair enough. Feel free to close the bug. At least now there's a search result on GitHub that can help people who experience this issue.

**Comment by nex3** [comment]
The reasoning behind this, if you're curious, is that Sass treats `&` as syntactically equivalent to an element selector or a universal selector (`*`) since in general it could be replaced by either of those and we don't want to generate an invalid selector if that happens.

You can do this with selector functions if you want:

``` scss
.foo {
  .bar {
    @at-root #{selector-append("select", &)} {
      // stuff
    }
  }
}
```

**Comment by SilentSpammer** [comment]
Issue is closed, but not resolved, actually...

Furthermore, this code:
```scss
.foo {
  .bar {
    @at-root #{selector-append("select", &)} {
      color: black;
    }
  }
}
```
doesn't generate preferred output:
```css
/* preferred is .foo select.bar */
select.foo .bar {
  color: black;
}
```

My workaround is:
```scss
// declaration
@function selector-append-tag($selector, $tag) {
	$phantom-selector: '.phantom-selector-that-should-be-unique';
	$selector: selector-append($selector, $phantom-selector);
	$selector: selector-replace($selector, $phantom-selector, $tag);
	@return $selector;
}

// example
.foo {
  .bar {
    @at-root #{selector-append-tag(&, "select")} {
      // stuff
    }
  }
}
```
