### ISSUE TITLE
Feature suggestion: variables based on media queries

### ISSUE THREAD

**Issue by andrevinsky** [sass/sass#1521]
It would be great if SASS/SCSS just could determine whether a variable gets to change its value inside `@media` directives and produce output accordingly.

For instance, ZURB uses $topbar-height variable to control the height of the top bar.

How do I easily make different heights for small and medium, without overloading native code that is? It seems there's no way.

With the suggested feature, the below approach might become possible:

``` SCSS
$topbar-height: 39px;
@media #{$medium-up} {
    $topbar-height: 75px;;
}
// ...
.top-bar {
    height: $topbar-height;
}
```

to produce

``` CSS
.top-bar {
    height: 39px;
}
@media only screen and (min-width: 40.063em) {
    .top-bar {
        height: 75px;
    }
}
```

Thinking about implementation, pardon my uneducated say in this, I think along thу following approach. SASS could create a shadow variable with attributes marking the duplicated variable with the media-query adherence. And when the consecutive code requires this variable, the pre-processor has to determine whether the variable uses media-based shadows and if yes, generate versions of the code for each copy of the variable under its media query (with the due grouping, of course).

Please give this idea a second thought after you have rejected it at first. :)

**Comment by Snugug** [comment]
While you wouldn't be able to do this through just a variable, #1010 would allow you to write a mixin that can do this, turning it into `@include topbar-height` or something of the sort. You can also use [Breakpoint](https://github.com/at-import/breakpoint) today to do this.

As for variable shadowing like this, IMO it would break scoping hard and I don't think it should be included, not to mention the fact that there are so many different permutations of media queries and the actual semantics of those media queries that variable scope juggling would get super messy super quick. Is a variable scoped to `only screen and (min-width: 40.063em)` also valid with a `only screen and (max-width: 50em)` media query? For about `10em` it seems like it should be. What about `(min-width: 45em)` that is now available for all media types? Or `(orientation: landscape)` which may or may not match. Having Sass automagically change variable scope with all of the different options (these were just to name a few) will lead to unexpected results, but if you specify exactly what you mean in a mixin/function (like you'd be able to with media query context/can with Breakpoint context) then it's an author led decision.

**Comment by andrevinsky** [comment]
Once you start thinking about it, there seems to be two implementation paths that could both get achieved. Naturally, both paths are desirable.

First, if a.. let's call it a _split-variable_.. if a split-variable is present inside a `@media` directive, it's output value will be according to the media it is matched against.

``` SCSS
$topbar-height: 39px;
@media #{$medium-up} {
    $topbar-height: 75px;
}
// ...
.top-bar {
    height: $topbar-height;
}
@media #{$medium-up} {
    .top-bar {
        height: $topbar-height;
    }
}
```

to produce

``` CSS
.top-bar {
    height: 39px;
}
@media only screen and (min-width: 40.063em) {
    .top-bar {
        height: 75px;
    }
}
```

Second, a split variable itself could populate media queries. Like in the example from the initial request.

**Comment by andrevinsky** [comment]
@Snugug I totally undestand the repercussions of this. That's why I assumed the idea might get rejected at first. But bear with me for sec.

Let's consider the part of your answer about permutations. Cannot implementation be chosen to be conservative in this regard and thoughful of a way to minimize the amount of generated media queries? I mean, look, the `@extend` directive. It may also at first seem prone to expand your code with all permutations but it doesn't so much, right? So my point is when a though put into this a way can be found.

As to using the mixins.. 
Let's consider a common - and real - usage scenario. I bower-install a SASS-based package, say, Zurb Foundation (I already mentioned it). Okay, they provide variables to customize the look, say, height of a top bar. But they use only one(!) height variable for this. A single height for three visual variations (small, medium, large). So _without_ altering the Foundation code or overwriting parts of their code, it seems, I cannot achieve my goal (and my goal is to have varying heights based on the resolution). I cannot use mixins, for it means changing _thier_ code.

The way out seems to be in split-variables. Can you see my point now?

**Comment by andrevinsky** [comment]
@nex3, @chriseppstein, @thedarkone SASS people, may I draw your attention as well to this?

**Comment by cimmanon** [comment]
My opinion doesn't matter much, but I'm going to have to agree with Snugug.  Yes, people expect this to work (the question pops up on SO often enough), but it seems like it would be extremely easy to get unexpected results.

Sass already gives you the freedom to add extra styling on top of what's already provided by your 3rd party library of choice.

``` scss
// all the zurb stuff here
// now you add your own stuff
@media #{$medium-up} {
    .top-bar {
        height: 75px;
    }
}
```
