### ISSUE TITLE
Request: list-contains function

### ISSUE THREAD

**Issue by dgalarza** [sass/sass#1530]
The idea would be to have a sass function which checks if a given list contains a specified value. I started some initial work on this but wanted to open up the request for discussion.

Something like:

``` scss
$list: 1 2 3;

p {
  @if list-contains($list, 2) {
    /* ... */
  } @else {
    /* ... */
  }
}
```

CC @whmii who originally proposed this function.

**Comment by nex3** [comment]
The `index()` function returns null if a value isn't found in a list, so you can use it like a contains function:

``` scss
$list: 1 2 3;

p {
  @if index($list, 2) {
    /* ... */
  } @else {
    /* ... */
  }
}
```
