### ISSUE TITLE
Converting angles

### ISSUE THREAD

**Issue by KittyGiraudel** [sass/sass#1531]
I am not quite sure why Sass does not provide a built-in way to compare (therefore allow operations on) angles from different units (`deg`, `grad`, `rad`, `turn`). 

@chriseppstein wrote this function a while back to do it, but I can't see any reason for Sass not to be able to perform such operations given that there is no context involved whatsoever.

``` scss
/// Convert angle
/// @author Chris Eppstein
/// @param {Number} $value - Value to convert
/// @param {String} $unit - Unit to convert to
/// @return {Number} Converted angle
/// @throw Cannot convert `#{unit($value)}` to `#{$unit}`.
@function convert-angle($value, $unit) {
  $convertable-units: deg grad turn rad;
  $conversion-factors: 1 10grad/9deg 1turn/360deg 3.1415926rad/180deg;
  @if index($convertable-units, unit($value)) and index($convertable-units, $unit) {
    @return $value
             / nth($conversion-factors, index($convertable-units, unit($value)))
             * nth($conversion-factors, index($convertable-units, $unit));
  }

  @error "Cannot convert `#{unit($value)}` to `#{$unit}`.";
}
```

Do you think like this could be added so we don't have to move this function around?
