### ISSUE TITLE
Suffix selectors don't compile in a silent selector

### ISSUE THREAD

**Issue by ghost** [sass/sass#1535]
When using a suffixed sub-selector in a silent selector, the output omits the selector entirely.

Example:

```
%module {
      display: block;
      &__item {
               color: #000;
      }
}

.module {
       @extend %module;
}
```

Expected output:

```
.module {
      display: block;
}
.module__item {
      color: #000;
}
```

Actual output:

```
.module {
      display: block;
}
```

**Comment by nex3** [comment]
Parent selector resolution happens strictly before extending. Your example is equivalent to

``` scss
%module {
  display: block;
}

%module__item {
 color: #000;
}

.module {
  @extend %module;
}
```

**Comment by SWGFL** [comment]
Thank you for clarifying that, I was trying to make a sort of module and wanted to make one extend that add classes to all its sub-selectors, but I can see also that the outcome would be the same when extending a normal selector:

```
.module {
  display: block;
  &__item {
    color: red;
  }
}
.new-module {
  @extend .module;
}
```

I would be useful for it to also extend those sub selectors, of course I can use a mixin to do this:

```
@mixin module {
    display: block;
    &__item {
        color: red;
    }
}
.new-module {
    @include module;
}
```

But this will lead to code duplication as a multiple of how many times it is used, the solution I have come up with to achieve what I want is this:

```
%module {
  display: block;
  &__item {
    color: red;
  }
}
@mixin module {
  @extend %module;
  &__item {
    @extend %module__item;
  }
}
.module {
  @include module;
}
.module-2 {
  @include module;
}
.module-3 {
  @include module;
}
```

Would be useful if you could do this directly with selectors and silent selectors, but I guess that would probably break a lot of code out there, so I will stick with the above until a better solution appears.

Thank you for your time.

**Comment by nex3** [comment]
If you wanted to be really fancy, you could write a few mixins to do this for you:

``` scss
$sub-selectors: ();

@mixin module($name) {
  $current-sub-selectors: () !global;
  %#{$name} {
    @content;
  }
  $sub-selectors: map-merge($sub-selectors, ($name: $current-sub-selectors)) !global;
}

@mixin sub-selector($name) {
  $current-sub-selectors: append($current-sub-selectors, $name) !global;
  &__#{$name} {
    @content;
  }
}

@mixin module-extend($name) {
  @extend %#{$name};
  @each $sub in map-get($sub-selectors, $name) {
    &__#{sub} {
      @extend %#{$name}__#{$sub};
    }
  }
}

// =======

@include module(module) {
  display: block;
  @include sub-selector(item) {
    color: red;
  }
}

.module {
  @include module-extend(module);
}
```
