### ISSUE TITLE
sass-convert: interpolation syntax repeated in mixin arguments

### ISSUE THREAD

**Issue by badsyntax** [sass/sass#1537]
Hey there. I've reproduced this behaviour using Sass 3.4.8.

Let's say we have the following Sass in a file `styles.scss`:

``` scss
@mixin width($amount) {
  width: $amount;
}

.container {
  $var: 100px;
  @include width(calc(100% - #{$var}));
}
```

And we run sass-convert on that file: `sass-convert --from scss --to scss styles.scss`, we get the following:

``` scss
@mixin width($amount) {
  width: $amount;
}

.container {
  $var: 100px;
  @include width(calc(100% - #{#{$var}}));
}
```

The interpolation characters are repeated which results in invalid Sass.
