### ISSUE TITLE
How to encapsulate parent hover in child selector

### ISSUE THREAD

**Issue by kl3ryk** [sass/sass#1539]
I have created the following solution (https://gist.github.com/kl3ryk/1b4a750b1691ae7cd3e4):

``` scss
div {
  $parent: &;

  h1 {
    @at-root #{$parent} {
      &:hover h1 {
        color: green;
      }
    }
    color: red;
  }
}
```

And the result is:

``` css
div h1 {
  color: red;
}
div:hover h1 {
  color: green;
}
```

I want to encapsulate all styles for h1 inside it. Is there any easier way to do that ?
It is referenced to https://github.com/sass/sass/issues/286
