### ISSUE TITLE
Properly handle escapes in identifiers

### ISSUE THREAD

**Issue by nex3** [sass/sass#1542]
- [x] [Proposal](https://github.com/sass/language/blob/master/accepted/identifier-escapes.md)
- [x] [Specs](https://github.com/sass/sass-spec/pull/1272)
- [x] [Documentation](https://github.com/sass/sass-site/commit/efc113ec)
- [x] [Dart Sass](https://github.com/sass/dart-sass/issues/425)
- [ ] [LibSass](https://github.com/sass/libsass/issues/2700)
- [x] [Ruby Sass](https://github.com/sass/ruby-sass/issues/76)

---

With 3.4, Sass started handling escapes in quoted strings per the CSS spec, but it's still not quite there with identifiers. Any escaped characters are stored as escapes, rather than as the characters they represent, which causes inconsistencies like the following:

``` scss
.\!foo {a: b}
.\21 foo {c: d}

.bar {@extend .\!foo}
.baz {@extend .\21 foo}
```

This should produce

``` scss
.\!foo, .bar, .baz {
  a: b; }

.\!foo, .bar, .baz {
  c: d; }
```

but instead produces

``` scss
.\!foo, .bar {
  a: b; }

.\21 foo, .baz {
  c: d; }
```
