### ISSUE TITLE
!optional for parent placeholder

### ISSUE THREAD

**Issue by maxmarkup** [sass/sass#1546]
now:

``` scss
%placeholder {
    @if somecondition {
        border: 1px solid #000;
    }
}
.one { @extend %placeholder !optional; }
.two { @extend %placeholder !optional; }
.three { @extend %placeholder !optional; }
```

but so would be better:

``` scss
%placeholder !optional {
    @if somecondition {
        border: 1px solid #000;
    }
}
.one { @extend %placeholder; }
.two { @extend %placeholder; }
.three { @extend %placeholder; }
```

**Comment by lolmaus** [comment]
A: Why didn't you come up to me when i was calling you?

B: I didn't hear you calling me.

A: Then you should've come and tell that you weren't.

**Comment by maxmarkup** [comment]
ok:

``` scss
%shadow {
    @if $ie > 8 {
        box-shadow....
    }
}
%opacity($var) {
    @if $ie > 8 {
        opacity: .5;
    }
}

```

_main.scss

``` scss
.rule1
    @extend %shadow !optonal;
    @extend %opacity !optonal;
.rule2
    @extend %shadow !optonal;
    @extend %opacity !optonal;
.rule3
    @extend %shadow !optonal;
    @extend %opacity !optonal;
.ruleN
    @extend %shadow !optonal;
    @extend %opacity !optonal;

and more-more times !optional
```

style.scss

``` scss
$ie: 9;
@import 'main';
```

ie8.scss

``` scss
$ie: 8;
@import 'main';
```

**Comment by lolmaus** [comment]
1. Why do you need `!optional` in this example?
2. What i meant was that your initial suggestion is impossible. The only way to implement it wpuld be to remove the `!optional` flag entirely and make all extends optional.

**Comment by Snugug** [comment]
You can extend from within a mixin. I'd rewrite as the following (or similar):

``` scss
%shadow {
      box-shadow....
}
%opacity {
      opacity: .5;
}

@mixin ie {
  @if $ie > 8 {
    @extend %shadow !optional;
    @extend %opacity !optional;
  }
}

.rule1
    @Include ie;
.rule2
    @Include ie;
.rule3
    @Include ie;
.ruleN
    @Include ie;


and more-more times !optional
```

style.scss

``` scss
$ie: 9;
@import 'main';
```

ie8.scss

``` scss
$ie: 8;
@import 'main';
```

Alternatively, only create separate stylesheets to add fallback code to your full stylesheet instead of two whole different stylesheets. These properties will simply be ignored by the parser, no need to serve a separate stylesheet with them removed.
