### ISSUE TITLE
Mixin Names: dash character and underscore character seem to be treated as equals

### ISSUE THREAD

**Issue by tbremer** [sass/sass#1549]
See the [sassmeister link](http://sassmeister.com/gist/cab1a23d03c1b7d143da) for a working example.

But essentially, these are treated as equals:

``` scss
@mixin under_score {
  content: 'under_score';
}

html {
  @include under_score;
  @include under-score;
}
```

Is this purposeful?
