### ISSUE TITLE
Mixin parameter not replaced correctly (needs interpolation) after upgrading to 3.4.9

### ISSUE THREAD

**Issue by andry-tino** [sass/sass#1554]
I have the following code:

``` scss
@mixin keyframes($anim) {
  @-webkit-keyframes $anim {
    @content;
  }
  @keyframes $anim {
    @content;
  }
}

@include keyframes(myanim) {
  0% {
    left: 0px;
  }
  100% {
    left: 100%;
  }
}
```

When I was using SASS prior to 3.4.7 this compiled well into:

``` scss
@-webkit-keyframes myanim {
  0% {
    left: 0px;
  }
  100% {
    left: 100%;
  }
}
@keyframes myanim {
  0% {
    left: 0px;
  }
  100% {
    left: 100%;
  }
}
```

However after upgrading to 3.4.7 and 3.4.9 it compiles into:

``` scss
@-webkit-keyframes $anim {
  0% {
    left: 0px;
  }
  100% {
    left: 100%;
  }
}
@keyframes $anim {
  0% {
    left: 0px;
  }
  100% {
    left: 100%;
  }
}
```

Which is obviously not correct. To have it rendered properly I need to interpolate:

``` scss
@mixin keyframes($anim) {
  @-webkit-keyframes #{$anim} { /* INTERPOLATION NEEDED */
    @content;
  }
  @keyframes #{$anim} { /* INTERPOLATION NEEDED */
    @content;
  }
}

@include keyframes(myanim) ...
```

Can you tell me more about this? It seems that the new version of SASS broke some syntax right? Can you confirm me this is a bug? Or maybe the new version introduces a different syntax for which interpolation is required? Thank you
