### ISSUE TITLE
Group prefixed and unprefixed selectors

### ISSUE THREAD

**Issue by nazar-pc** [sass/sass#1564]
I'm using web components.
For proper css for Chrome and other browsers that do not support Web Components natively I heed to get from

``` css
selector {
    color: #fff;
}
```

such thing

``` css
selector,
/deep/ selector {
    color: #fff;
}
```

I have a huge piece of ready CSS (not mine) and want just wrap it with something to get such result, unfortunately I can't get it in any way I've tried. The most obvious doesn't work:

``` css
'',
/deep/ {
    selector {
        color: #fff;
    }
}
```

Is there any way get what I want? Already tried different combinations with mixins, extending and nesting.

The problem is to get selectors grouped together in order to avoid content duplication.

**Comment by whaaaley** [comment]
I'm not sure I understand. Why can't you use `selector, /deep/ selector` explicitly?

Also, if you don't want to touch the original `selector`, what's wrong with this?

```
selector {
  color: #fff;
}

/deep/ selector {
  @extend selector;
}
```

Outputs

```
selector, /deep/ selector {
  color: #fff;
}
```

**Comment by nazar-pc** [comment]
The problem is that I have few thousands lines of CSS code and it is pretty difficult to copy all selectors manually.

**Comment by whaaaley** [comment]
Gotcha. How about this?

```
@mixin deep {
  .wrap {
    @at-root {
      %deep, /deep/ {
        @content
      }
    }

    @extend %deep;
  }
}

@include deep {
  .foo {
    color: red;
  }
  .bar {
    color: green;
  }
  .baz {
    color: blue;
  }
  .qux {
    color: white;
  }
}
```

Outputs:

```
.wrap .foo, /deep/ .foo {
  color: red;
}
.wrap .bar, /deep/ .bar {
  color: green;
}
.wrap .baz, /deep/ .baz {
  color: blue;
}
.wrap .qux, /deep/ .qux {
  color: white;
}
```

I'm not sure if this is a bug or if it's just me, but I can't get it to work without the extra `.wrap` class. It's not a complete solution, but it might get you started on something better.

**Comment by nazar-pc** [comment]
That was the question:), otherwise your example can be much simpler:

``` css
@mixin deep {
 .wrap, /deep/ {
        @content
  }
}

@include deep {
  .foo {
    color: red;
  }
  .bar {
    color: green;
  }
  .baz {
    color: blue;
  }
  .qux {
    color: white;
  }
}
```

I've played with `@at-root` already

**Comment by whaaaley** [comment]
Ah, definitely gotcha now. If there were a `selector-unnest` function or if `selector-replace` would take a null value, we would have a solution.

**Comment by nex3** [comment]
This is a lot easier to do as a mixin that goes inside a selector:

``` scss
@mixin deep {
  &, /deep/ & {
    @content;
  }
}

selector {
  @include deep {
    color: #fff;
  }
}
```

If you really want to limit the nesting, you could also make the selector a parameter to the mixin:

``` scss
@mixin deep($selector) {
  #{$selector} {
    &, /deep/ & {
      @content;
    }
  }
}

@include deep("selector") {
  color: #fff;
}
```
