### ISSUE TITLE
Inspect function printing too many parenthesis

### ISSUE THREAD

**Issue by KittyGiraudel** [sass/sass#1565]
Test:

``` scss
$map: (
  'a': 1,
  'b': (
    'c': 'd'
  )
);

.test {
  content: inspect($map);
}
```

Expected:

``` css
.test {
  content: ("a": 1, "b": ("c": "d"));
}
```

Output:

``` css
.test {
  content: ("a": 1, "b": (("c": "d")));
}
```
