### ISSUE TITLE
Improper expression result with zero-value numerator

### ISSUE THREAD

**Issue by davidkpiano** [sass/sass#1572]
When doing division in an expression, if the numerator is zero unitless, the value of the division part of the expression is `0/[unit]`, where `[unit]` is (I believe to be) any unit (I tested it with `px`, `ms`, `s`, etc.):

``` scss
$value: (0 / 3000px);
// Expected: $value == 0
// Result: $value == 0/px
```

**Comment by ghost** [comment]
That's not how units work. Units in the denominator stay in the denominator. 0 with units should still equal 0 though, so, I'd consider that a bug.

**Comment by KittyGiraudel** [comment]
I'd expect `0` divided by `n` to be `0` as far as I'm concerned. No matter the unit.

**Comment by ghost** [comment]
Yeah, as I said, there are two "issues" with this. One is the expectation that `0 / 3000px == 0`, which apparently is deprecated, even though it's valid. The other is that `n / (m * 1px) == (n / m) * 1px`, which is incorrect and just a misunderstanding of how algebra works.

**Comment by davidkpiano** [comment]
Yeah, sorry about that. Originally I stated the issue with a zero-value numerator; the value with a non-zero numerator is that it results in something like `0.0033/px`, which is an invalid expression. It's a little too much to expect Sass to return something like 0.0033px<sup>-1</sup>, so I'll just chalk that up to being a developer error.

**Comment by ghost** [comment]
SCSS doesn't actually allow any invalid units to be printed, out, but in case you want to do any weird unit math with intermediate conversion factors of odd units, it's allowed. Inverse pixels is a unit which makes sense mathematically, although you'd never actually find an actual quantity with that amount.

**Comment by chriseppstein** [comment]
This is working as designed. An expression that works because the numerator happens to be 0 and then fails later when the numerator changes would be a very strange behavior.

**Comment by davidkpiano** [comment]
@chriseppstein This seems to go against the [W3C spec for distance units](http://www.w3.org/TR/css3-values/#lengths) which states:

> ...for zero lengths the unit identifier is optional (i.e. can be syntactically represented as the <number> ‘0’).

It seems unnatural to put a unit for a zero value, and I feel that expressions should allow zero values to have optional unit identifiers, at least for distance values.

``` scss
// This *should* be permitted
$foo: 0; // Unit optional for zero-length distance value
$bar: 10px;

.baz {
  width: ($foo / $bar); // 0/px isn't a valid CSS value.
}

// This is unnatural, but fine
$foo: 0px;
$bar: 10px;

.baz {
  width: ($foo / $bar); // 0
}
```
