### ISSUE TITLE
Property mixins

### ISSUE THREAD

**Issue by victorherraiz** [sass/sass#1573]
I would be nice to write standard css and fix it for "old" browsers  without using the mixin syntax, by directly pointing the property. This could be helpful for new sass developers and css to sass conversions. 

In the following example I use "!property" flag to stop recursive calls.
SCSS:

``` scss
@property display($value) {
    @if $value == flex {
        display: -webkit-box !property;
        display: -moz-box !property;
        display: -ms-flexbox !property;
        display: -webkit-flex !property;
        display: flex !property;
    } @else {
        display: $value !property;
    }
}

.example {
    display: flex;
}
```

CSS Output: 

``` css
.example {
    display: -webkit-box;
    display: -moz-box;
    display: -ms-flexbox;
    display: -webkit-flex;
    display: flex;
}
```

**Comment by lolmaus** [comment]
What you suggest is wrong in several ways.

What's wrong with mixins?

``` sass
=flex
  display: -webkit-box
  display: -moz-box
  display: -ms-flexbox
  display: -webkit-flex
  display: flex

.foo
  +flex
```

Also, have a look at [autoprefixer](https://github.com/postcss/autoprefixer) which can be integrated into Compass.

**Comment by victorherraiz** [comment]
There is nothing wrong about mixins and I know about autoprefixer. But there are several scenarios related to property support.

Autoprefixer is great to add every needed prefix but a different solution is needed to add rem unit support in old browsers. If sass let us attach a hook at any property, autoprefixer is not logger need it.

``` scss
@property font-size($value) {
    @if unit($value) == rem {
        font-size: #{($value / $base) * 16}px !property;
    }
    font-size: $value !property;
}

.example{
    font-size: 1.2rem;
    line-height: 1.5em;
}
```

I think is nice to write standard css and fix it (as autoprefixer does or JavaScripts polyfills do). Another nice feature of this approach is that when the property mixin in not required anymore, just delete it, with no other changes.

@lolmaus, could you be more specific on: "What you suggest is wrong in several ways."

**Comment by cimmanon** [comment]
I would not want this under any circumstance for one major reason:  Flexbox.  To blanket add all prefixes every time I use any Flexbox property is going to raise all kinds of hell depending on the effect I am going for.  Do you know what happens when a browser supports `display: flex` but _doesn't_ support `flex-wrap: wrap`?  Configuring browser support on the project level is unacceptable, since I might want to include those old prefixes occasionally throughout the project.

I do not want Sass to guess what I mean, ever.

**Comment by victorherraiz** [comment]
This request is not for flexbox but for a new language feature thats allow to attach a mixin-like behaviour to a CSS property. This is not a mixin replacement.

@cimmanon, Autoprefixer exists for a reason but you are the one who choose if you want to use it or not. if you use rem units,  woff/woff2 fonts, svg backgrounds...  you have to use fallbacks at some point and  this feature could help us. You could still have exceptions with "!property flag".

It could also help you to detect bad property usage (or just undesired) and deliver warn messages at compilation time.

It could help in my projects but is my humble opinion.

**Comment by cimmanon** [comment]
@victorherraiz That's just it, I don't _want_ Autoprefixer.  Never did and never will.  Clearly you do, because you're the one asking for it to be added to Sass.

**Comment by Snugug** [comment]
Duplicate of #366 

That issue wound up turning into a discussion of a property like way of using a mixin, which I believe to be the crux of this issue and not really a new directive that's identical to a mixin in every way except the way it's called, which is a bad thing.

**Comment by victorherraiz** [comment]
I don't think this is a duplicate of #366. The important part of my request was not invoking a mixin with other syntax  but decorate standard CSS properties. Stylus calls this feature "transparent mixins". I do not like Stylus syntax, I prefer to use something closer to CSS (SCSS) anyway.

I choose  `@property` for my example because I do not like the idea of unwanted, present or future, collisions (Stylus). When I write `@property`  I am pointing to a known css property and when a write a `@mixin` I do not expect such behaviour.  The syntax is the less important part of the request but I tried to show a visual difference.

**Comment by stephnr** [comment]
My vote is to just stick with plain old use of mixins or autoprefixer. :-1:

**Comment by victorherraiz** [comment]
@Stephn-R, I would like to know the reasons for your decision.

**Comment by Snugug** [comment]
You are asking for a new directive to be created and a new abstraction be learned with additional indirection to be tied exclusively to properties thus tightly coupling Sass to knowledge of CSS properties in order to have slightly nicer syntactical sugar over mixins for an issue that can be resolved now using mixins for which there is a proposal that essential covers your use case in a more broad way in order to solve a problem that is going away as browsers drop vendor prefixes that are currently out there and in the future.

I'm not in favor.

**Comment by victorherraiz** [comment]
@Snugug, you are right. Mixins can do this right now. But what is wrong with the following CSS:

``` CSS
.foo {
  font-size: 1.2rem;
}
```

If we have to support old browsers (e.g. IE8), we have to include a fallback to px or other unit.  We could add a mixin, for example, to add that support. That is going change all the selectors that use rem units. When the support for old browsers drops you end up with a mixin that do nothing but write the same it was written in the original CSS.

Polyfills address these problems attaching fallbacks and behaviours to the missing features. I would like to have the same tools in SASS language for properties. But it is only my opinion.

**Comment by Snugug** [comment]
There is nothing wrong with the CSS you've written. It's CSS.

The proposal in #366 would allow you to write your original proposal as the following:

``` scss
@mixin display($value) {
    @if $value == flex {
        display: -webkit-box;
        display: -moz-box;
        display: -ms-flexbox;
        display: -webkit-flex;
        display: flex;
    } @else {
        display: $value;
    }
}

.example {
    display +: flex;
}
```

The advantage of doing it as mixins, as you've shown in your original proposal, is not only do you need to introduce a new directive, `@property` that has identical syntax as a mixin, but you don't need a `!propery` flag to say "no I want this property to be a property, not a magic property".

Your most recent example doesn't even follow from your original proposal. When talking about `rem` fallbacks, you're talking about unit level, not a property level, a whole different proposal than what you've originally discussed. Either way, you have the same problem with your `@property` proposal that you say with `@mixin` in that the fallback is human written and therefore would need to be updated as your browser support changes.

As an aside, the flexbox example you are using [is out of date](http://caniuse.com/#feat=flexbox). `-moz` isn't needed any longer, and for most levels of support for flexbox, legacy `-webkit` isn't needed either.
