### ISSUE TITLE
unquote affects colors differently if they're quote

### ISSUE THREAD

**Issue by xzyfer** [sass/sass#1574]
Sass: 3.4.9
ruby: ruby 2.1.1p76

``` scss
foo {
  color: unquote("red") + green;
  color: unquote(red) + green;
}
```

Expected output

``` css
foo {
  color: #ff8000;
  color: #ff8000; }
```

Actual output

``` css
foo {
  color: redgreen;
  color: #ff8000; }

```
