### ISSUE TITLE
Interpolation removes spaces preceding it, in a short syntax

### ISSUE THREAD

**Issue by piouPiouM** [sass/sass#158]
The following code

``` scss
div {
  $font-size: 1em;
  font: bold #{$font-size}/1.5 Arial, Verdana, Helvetica, Geneva, sans-serif;
}
```

generate

``` css
div {
  font: bold1em/1.5 Arial, Verdana, Helvetica, Geneva, sans-serif;
}
```

Expected value:

``` css
div {
  font: bold 1em/1.5 Arial, Verdana, Helvetica, Geneva, sans-serif;
}
```

Version: Sass 3.1.1

**Comment by nex3** [comment]
I can't reproduce this in either Sass 3.1.1 or the latest version, 3.1.7. What version of Ruby are you using? What OS and OS version?

**Comment by piouPiouM** [comment]
I can reproduce it with this code:

```
div {
  // é
  $font-size: 1em;
  font: bold #{$font-size}/1.25 Arial, Verdana, Helvetica, Geneva, sans-serif;
}
```

It's seems that the comment with a accented character throws the bug.

**Comment by jenshedqvist** [comment]
I get this as well with this code:

``` CSS
.mod {
  > header,
  > .header {
      margin: -#{$module_padding} -#{$module_padding} $module_padding -#{$module_padding};
      padding: $module_padding;
      border-bottom: 1px solid $module_border_color;
  }
}
```

The outputed CSS for this is:

``` CSS
.mod > header,
.mod > .header {
  margin: -14px -14px 14px-14px;
  padding: 14px;
  border-bottom: 1px solid #e3e3e3;
}
```

Im using Ruby 1.9.2, Compass 0.11.5, SASS 3.1.4 on Win 7.
