### ISSUE TITLE
Parse issue with sass variable (containing a function) passed as an argument to another function.

### ISSUE THREAD

**Issue by ankur-goel** [sass/sass#1581]
We need to pass a SASS variable (containing a function) as an argument to another function. While parsing the variable, the parenthesis (of the containing function) are getting removed resulting in an incorrect value.

Here are the SASS and CSS properties:

``` scss
//Common SASS
$bg-gradient: linear, left top, left bottom, color-stop (50%, #FFFFFF), color-stop (100%, #F2F2F2);

//Component-specific SASS
div {
background: -webkit-gradient($bg-gradient);
}

//Actual CSS
div {
background: -webkit-gradient(linear, left top, left bottom, color-stop 50%, #FFFFFF, color-stop 100%, #F2F2F2);
}

//Expected CSS
div {
background: -webkit-gradient(linear, left top, left bottom, color-stop (50%, #FFFFFF), color-stop (100%, #F2F2F2));
}
```

Any thoughts on what could be the issue?
