### ISSUE TITLE
Rule without semicolon followed by nested rule not throw error

### ISSUE THREAD

**Issue by mateusvahl** [sass/sass#1588]
I was coding with Jekyll.rb and and found that:

``` sass
.post {
        h2 {
            position: relative;
            margin: 15px 0;
            font-weight: 700 // Miss semi-colon
            a {
               position: absolute;
           }
       }
}
```

Output

``` sass
.post h2{
    position:relative;
    margin:15px 0;
    font-weight:700 a;
    font-weight-position:absolute
}
```

I believe it'i a error.
Sass 3.4.9 (Selective Steve)

T. you

**Comment by jakob-e** [comment]
Missing semi-colons in CSS will break too – I don't think it's a job for Sass to fix. 

``` CSS
h2 {
  position: relative;
  margin: 15px 0;
  font-weight: 700
  color:red;  /* This will not work */
}

```

**Comment by cimmanon** [comment]
I cannot reproduce.  Sass throws an error in both instances.

**Comment by mateusvahl** [comment]
@cimmanon : I Missed an `}` at input example. Pls paste on http://sassmeister.com/, exactly same output

@jakob-e : isn't about compile, it's an wrong output(in my opinion) without any alert/throw

**Comment by jakob-e** [comment]
@mateuspv My point was it would require Sass to evaluate **content (and order)** and IMO that would be wrong. If you move a { } to the top everything is fine.         

``` SCSS
.post {
    h2 {
        a  {
            position: absolute;
        }          
        position: relative;
        margin: 15px 0;
        font-weight: 700 // Miss semi-colon
    }
}

```
