### ISSUE TITLE
Duplicate classes are removed from selector when extending

### ISSUE THREAD

**Issue by justinryder** [sass/sass#1596]
[Gist Issue Example](https://gist.github.com/justinryder/71c3ee504f6e1809b35c)

SCSS

``` scss
%my-placeholder {
  color: red;
}

.foo.foo {
  @extend %my-placeholder;
  background-color: blue;
}
```

Expected

``` css
// @extend's output
.foo.foo {
  color: red;
}

// regular property output
.foo.foo {
  background-color: blue;
}
```

Actual

``` css
// @extend's output
.foo {
  color: red;
}

// regular property output
.foo.foo {
  background-color: blue;
}
```

When using @extend in the context of a selector that uses the same class twice on the same element, the duplicate class is removed in the output of the @extend (.foo.foo becomes .foo). This is not the case for any other styles declared in the same context, for those, the selector is preserved as typed.

A common technique for increasing specificity without over-qualifying is to just duplicate the same class multiple times. This technique cannot be used with extend, because it removes the duplicate classes, thus reducing the specificity that was intentionally added.

**Comment by stephnr** [comment]
I just ran another test in Sassmeister: [See here](http://sassmeister.com/gist/c9ca9cb87e654633f29e)

If the following is used:

Code:

``` scss
.foo.bar {
  @extend %placeholder;
  background-color: green;
}
```

Result:

``` css
.foo.bar {
  color: red;
}

.foo.bar {
  background-color: green;
}
```

**_@extend**_ has no problem reading it. It might look like a bug but in fact, this is an **_expected**_ result. Try and think what `.foo.foo` would look like in an HTML file:

``` html
<div class="foo foo">...</div>
```

Both `.foo.foo` and `.foo` would still target the same elements.

**Comment by lolmaus** [comment]
Hey @Stephn-R, you're missing the point here.

You're right that @nex3 added removal of duplicate classnames as an optimization. The `.foo.foo` selector indeed targets the same elements as `.foo`.

But @justinryder has pointed out that a `.foo.foo` CSS selector has specificity different from `.foo`, and reducing `.foo.foo` to `.foo` may actually change the looks and/or layout of the page.

Consider this [example](http://sassmeister.com/gist/6fd6837ebacf730e3f57):

``` sass
.foo.foo
  background-color: red

.foo
  background-color: blue
```

A `<div class='foo'></div>` element will be red. But if you replace `.foo.foo` with `.foo` in Sass, then the element will be blue.

This is a neat technique to override the default looks of elements styled with third-party CSS, without caring for the order of imports.

@nex3, looks like this feature was intended as an optimization to remove redundancy but it actually modifies CSS semantics, huh?

**Comment by chriseppstein** [comment]
None of the use cases here make any sense to me. But if you really need to double the specificity it should be done at the extended selector, not at the extending selector. That is:

``` scss
%red%red { color: red; }
.foo { @extend %red; }
```

In this case, I think the output should be a selector that is `.foo.foo` but Sass still simplifies it down to `.foo`.

**Comment by nex3** [comment]
@justinryder is right that this violate's Sass's specificity guarantees, as strange as the input seems.

@chriseppstein that would be next to impossible to dedup without completely tearing out every optimization Sass does here.

**Comment by nex3** [comment]
After digging into this a bit, it looks like changing it will be quite difficult. The assumption that there are no duplicates in a compound selector goes very deeply into the `@extend` machinery. It'll take more time than I have right now to fix.

**Comment by stephnr** [comment]
Thank you @lolmaus for the clarification and @chriseppstein for the example. Those are completely valid reasons for having a repeated selector like that.

**Comment by Stav88** [comment]
Same issue for other override:

``` scss
%link {
    color: red;
}
a, 
a:link {
    @extend %link
}
.foo, 
.foo.bar {
    @extend %link
}
```

Actual results:

``` css
a, 
.foo {
    color: red
}
```

Expected results:

``` css
a, 
a:link, 
.foo, 
.foo.bar {
    color: red
}
```
