### ISSUE TITLE
Reject invalid function names

### ISSUE THREAD

**Issue by nex3** [sass/sass#1598]
Sass has special parse rules for functions named `calc`, `element`, `expression`, and `url` that mean that user-defined functions with those names can never be run. We should emit an error when those functions are defined rather than allowing the user to define them and be unable to use them, as in #1571.

`calc` and `element` may also have vendor prefixes.

**Comment by jakob-e** [comment]
:-1:  
@nex3 Not saying not true – but in the case of url the following does work and is a major FTW when it comes to deployment on shifting path structures.  

``` SCSS
// Re-defined url function
@function url($src, $path-type: $paths-default){
  // ... string replacement on $src etc....  
  @return unquote('url(#{map-get($paths, $path-type)}#{$src})');
}

// Config 
$paths:(
  url    : '',
  img    : '../img/',
  fonts  : '../fonts/'
);
$paths-default: img;

// SCSS
.image {
  background: url('image.jpg');
}
@font-face {
  src : url('font.woff', fonts);
}

// CSS Output 
.image {
  background: url(../img/image.jpg);
}

@font-face {
  src: url(../fonts/font.woff);
}

```
