### ISSUE TITLE
Not work @for and nth-child

### ISSUE THREAD

**Issue by 6pm** [sass/sass#1601]
Code:
// vars
$linkColor1: #ccc;
$linkColor2: #ddd;
$linkColor3: #aaa;
// for
@for $i from 1 through 3 {
&:nth-child(3n+{$i}){
    color: $linkColor{$i};
  }
}

**Comment by cimmanon** [comment]
It isn't _supposed_ to work.  Duplicate of https://github.com/sass/sass/issues/132

**Comment by KittyGiraudel** [comment]
Dynamic variables do not exist. Maps are to be used instead.

**Comment by chriseppstein** [comment]
You don't even need maps for this example, a list will suffice.

``` scss
// vars
$linkColors: #ccc, #ddd, #aaa;

// for
.something {
  @for $i from 1 through length($linkColors) {
    &:nth-child(3n+#{$i}) {
      color: nth($linkColors, $i);
    }
  }
}
```
