### ISSUE TITLE
Get value of another element

### ISSUE THREAD

**Issue by levani** [sass/sass#1603]
```
#sidebar {
    float: left;
    width: 300px;
}

#container {
    margin-left: #sidebar.width;
}
```

Is it possible something like this to be implemented in sass?

**Comment by davidkpiano** [comment]
Consider the cases when `#sidebar.width` is either:
- Not defined
- Defined after `#container`
- Does not have a `width` property set
- Changes its `width` property later
- etc.

I can imagine this would be pretty difficult (if not impossible) to implement.

**Comment by whaaaley** [comment]
@davidkpiano To answer those questions:
- Not defined == null / error
- Defined after `#container` == I'm not sure what you mean - it wouldn't make a difference
- Does not have a `width` property set == null / error
- Changes its `width` property later == It would behave the same as a variable would

I disagree that this would be impossible because it's basically just a variable. I'd opt for a function looking syntax though, because using a selector as a value seems weird to me.

``` scss
// Imaginary function:
@function property-value($property, $selector: null) {
    @return $magic;
}

#sidebar {
    float: left;
    width: 300px;
}

#container {
    margin-left: property-value(width, #sidebar);
}
```

All that said, this is pretty much what variables were made for. If it's really important, you should give it a name and you could use it anywhere.

**Comment by cimmanon** [comment]
I know people expect this to work all the time, but I think it would only make things more confusing.  What happens when you throw media queries or feature queries into the mix?  If the property is specified inside and outside of the query, which value is returned?

What about properties that have prefixed values?

``` css
.foo {
    display: -webkit-flex;
    display: flex;
}
```

Or providing fallbacks for unsupported values?

``` scss
.foo {
    background: red;
    background: rgba(255, 0, 0, .5); /* old browsers don't support rgba */
}
```

**Comment by levani** [comment]
@cimmanon 

I don't think media queries are big deal in this case. Values defined inside them are intended only for that particular case so only properties defined outside media queries should be copied. If no properties are defined an exception should be thrown.

Properties that are defined several times may look a bit confusing at first but since you expect the property value to be the same as the source, I think it would make more sense to copy all the properties.

``` css
.foo {
    display: -webkit-flex;
    display: flex;
}

.bar {
    display: .foo->display
}
```

so after compiling .bar would become:

``` css
.bar {
    display: -webkit-flex;
    display: flex;
}
```
