### ISSUE TITLE
Selector as variable not working when on multiple lines

### ISSUE THREAD

**Issue by ryanburnette** [sass/sass#1604]
I use the Sass syntax and I've noticed that when selectors are in variables they don't seem to work when on multiple lines.

``` sass
// doesn't work
textarea,
#{$all-text-inputs},
select[multiple=multiple]
```

``` sass
// works
textarea, #{$all-text-inputs}, select[multiple=multiple]
```

This is especially a problem because `sass-convert` always seems to put selectors on multiple lines. I'm using `sass-convert` in a feature addition for a Sass library and I need a way to mitigate the issue. Is there an option in sass-convert to perhaps avoid putting selectors on multiple lines when they won't actually work?

Or is the issue possibly in the variable itself?

**Comment by ryanburnette** [comment]
I just tested this more thoroughly and the presence of the variable seems to make it and all following selectors get ignored.

``` sass
textarea,
#{$all-text-inputs},
select[multiple=multiple]
  background: red
```

becomes

``` css
textarea {
  background: red;
}
```

while

``` sass
textarea, #{$all-text-inputs}, select[multiple=multiple]
  background:red
```

becomes

``` css
textarea, input[type="email"], input[type="number"], input[type="password"], input[type="search"], input[type="tel"], input[type="text"], input[type="url"], input[type="color"], input[type="date"], input[type="datetime"], input[type="datetime-local"], input[type="month"], input[type="time"], input[type="week"], select[multiple=multiple] {
  background: red;
}
```

Here's [the source](https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/addons/_html5-input-types.scss) on the `$all-text-inputs` selector that I'm using. It's from [Bourbon](http://bourbon.io/) which is a pretty popular Sass library.
