### ISSUE TITLE
Possibility to skip interpolation in comments

### ISSUE THREAD

**Issue by willemdewit** [sass/sass#1605]
I'm using [sassdoc](http://sassdoc.com/) and while documenting the following SCSS:

```
/**
 * The CSS selector for a special button.
 *
 * @example
 *   #{$special-button-selector} {
 *     font-weight: bold;
 *   }
 * 
 */
$special-button-selector: '.button.special-button';
```

I get the following error: `Undefined variable: "$special-button-selector".`

I want the example to be correct so I think I need a way to skip the interpolation.

**Comment by lolmaus** [comment]
The solution is simple: use line comments instead of block comments.

**Comment by KittyGiraudel** [comment]
``` scss
/// The CSS selector for a special button.
///
/// @example
/// #{$special-button-selector} {
///     font-weight: bold;
/// }

$special-button-selector: '.button.special-button';
```
