### ISSUE TITLE
extra line breaks

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#161]
https://gist.github.com/1182542

Sass adds line breaks that weren't in the source (seen on line 18 and 27) which breaks the visual grouping desired by the original author (@simplebits).

**Comment by nex3** [comment]
The Sass output format, including line breaks between rules, is based entirely on the output style chosen and the parse tree of the document. The whitespace in the original document is completely ignored.

I'm pretty skeptical that there's a way to consistently match the whitespace of the output document with that of the input document if we're going to support this for every output style. This is a pretty simple case, but whitespace can be used anywhere in a document, and preserving all of that through the various transformations Sass does on the document seems likely to be quite difficult.

If we did support this, it would almost certainly have to be its own output style. I suspect such an output style would be possible, but require a substantial amount of engineering to get right. I doubt it would be worth working on in the near future over bugs or useful features such as output optimization.

**Comment by alanhogan** [comment]
Wouldn’t a super close approximation be taking the Sass `:expanded` output and piping it through a filter that simply removes all lines that are exactly blank?

**Comment by nex3** [comment]
What I took from the gist was that the empty line shouldn't be there because it wasn't there in the source, not that there should be no empty lines between CSS rules. If the latter is what they're looking for, yes, that would be easy to do automatically.

**Comment by chriseppstein** [comment]
It's fundamentally about visual grouping. The goal in my mind is not to mimic the exact source spacing, but rather to have the output be able to have 0, 1, or 2 separating line breaks. I will poke around and see how hard it is.

**Comment by necolas** [comment]
Related issues with the expanded ouput:
1. Removal of blank lines between comments and rules. The way you format your SASS/SCSS code should be better preserved in the compiled output, IMO. Increasingly, projects use pre-processors to provide a CSS output for developers who want to stick to native CSS. And when working on client work, the end-client will usually expect CSS code.
2. Not being able to specify the number of spaces used in the indentation (as far as I know). This is related to the first point about people consuming the expanded CSS output. If your editor is set to use 4 spaces for indentation (or anything other than 2), or your coding standards elsewhere in a project use a specific indentation setting, then the expanded CSS won't conform to it.

**Comment by simplebits** [comment]
I'll echo necolas' comments. Excellent points about the output being something that's still important in many situations. The blank lines around comments and indentation preference are all part of the authors style—the more that can be preserved, the better (and potentially more hand-coding folks would be attracted to Sass in general—and there are many).

**Comment by ChrisWojcik** [comment]
Sorry to bump this topic, just found this issue. I agree with the above comments that any way to preserve more of the author's style would be great.

Unlike the first poster, I actually want more blank lines than get output sometimes. For example, a blank line after a comment used to break the document up into sections. Very minor, but does get on my nerves.

**My Authored SCSS File:**

``` css
/* ==========================================================================
Base styles: opinionated defaults
========================================================================== */

html,
button,
input,
select,
textarea {
    color: #222;
}
```

**What Sass Outputs (expanded):**

``` css
/* ==========================================================================
Base styles: opinionated defaults
========================================================================== */
html,
button,
input,
select,
textarea {
  color: #222;
}
```

I wrote a snippet of ruby code into the config.rb file to add those blank lines back in, but it's specific to my covention and this situation.

If I minify the output, it's not really an issue anymore, but sometimes for one reason or another, I want the css to be human-readable and formatted a certain way.

**Comment by jamiebuilds** [comment]
I know it's been awhile on here, but I'd really like to see this happen. For [one of my projects](https://github.com/tctcl/objective) I provide a compiled CSS file for distribution in case someone doesn't want to use sass and the comments are all squished together.

In the future I want to made the files into a living documentation which would be heavy on the comments. So it'd be great if they were formatted nicely.

**Comment by allthosehumans** [comment]
Just to add a bit more perspective to this conversation. I'm not as hardcore as you guys so I apologise in advance if the following comment makes no sense for some reason:

It seems the sass-convert command is often used  by people who develop plugins for code editors. They use it to create "beautification" commands.

https://github.com/drewhamlett/brackets-beautify/blob/fbc4398237ce905c094ec959d0ebde3ff357958a/node/SassFormatDomain.js

AFAIK the code is formatted according to the output options such as expand, etc. Is that correct?

If so, it may be an argument for trying to preserve blank lines. I follow some conventions that Harry Roberts uses and sometimes have 5 blank lines between certain blocks of code. If I use a beautification command I'd sure love it if the lines were preserved.

**Comment by hayatbiralem** [comment]
I have an idea for this and I am already using for solving my issue.

If you use the Grunt you can solve your problem with [grunt-replace](https://github.com/outaTiME/grunt-replace):

### Gruntfile.js

``` javascript
module.exports = function (grunt) {
  grunt.loadNpmTasks('grunt-contrib-sass');
  grunt.loadNpmTasks('grunt-replace');
  grunt.initConfig({
    sass: {
      dist: {
        options: {
          style: 'expanded'
        },
        files: {
          'src/css/main.css': 'dist/css/main.scss'
        }
      }
    },
    replace: {
      css: {
        options: {
          usePrefix: false,
          patterns: [
            {
              match: '/**/',
              replacement: ''
            }
          ]
        },
        files: [
          {expand: true, flatten: true, src: ['dist/css/main.css'], dest: 'dist/css'}
        ]
      }
    }
  });
  grunt.registerTask('default', ['sass', 'replace:css']);
};
```

### main.scss

``` scss
/* Table of Content
============================================================================
   #Colors
   #etc
*/

/**/

/* ==========================================================================
#Colors
========================================================================== */

/**/

.red {
  color: red;
}

/* ==========================================================================
#etc
========================================================================== */

/**/

.etc {
  content: ":)";
}
```

### main.css

``` css
/* Table of Content
============================================================================
   #Colors
   #etc
*/

/* ==========================================================================
#Colors
========================================================================== */

.red {
  color: red;
}

/* ==========================================================================
#etc
========================================================================== */

.etc {
  content: ":)";
}
```

Hope this helps :)
