### ISSUE TITLE
sass-convert strips parenthesis

### ISSUE THREAD

**Issue by badsyntax** [sass/sass#1614]
I have tested this with version 3.4.10.

I have a Scss file with the following contents:

``` scss
.test {
  $val: 2px;
  padding: ($val / 2) ($val / 2) ($val * 3.5) ($val / 2);
}
```

I run the following command:

```
sass-convert --from scss --to scss style.scss
```

I get the following output:

``` scss
.test {
  $val: 2px;
  padding: $val / 2 $val / 2 $val * 3.5 $val / 2;
}
```

This does not result in any issues as part of the compilation process, but it results in less readable code. Is this an intentional optimisation? Would you consider changing this behaviour to prevent the parenthesis being removed?

**Comment by Arcovion** [comment]
May I suggest:

``` scss
.test {
  padding: $val / 2;
  padding-bottom: $val * 3.5;
}
```

No parentheses, no repetition and it's easier to tell which side differs.
