### ISSUE TITLE
Support Shadow DOM >>> operator

### ISSUE THREAD

**Issue by KittyGiraudel** [sass/sass#1619]
New Shadow DOM syntax for `/deep/` does not work properly in everything-but-compressed mode:

``` scss
.foo >>> .bar {
  color: red;
}
```

Expected:

``` css
.foo >>> .bar {
  color: red;
}
```

Result:

``` css
.foo > > > .bar {
  color: red;
}
```

I don't know if the spaces between operators are relevant or not, but the [specs](http://dev.w3.org/csswg/css-scoping-1/#deep-combinator) mention `>>>` as a whole, so Sass should probably stick to this. Or at least print it as authored, rather than spacing them all.
