### ISSUE TITLE
tag#{&__child} produces space between parent and child names

### ISSUE THREAD

**Issue by efender** [sass/sass#1627]
**sass 3.4.11 / compass 1.0.3**

SCSS

``` scss
.parent {
    &__child {
        color: #000;
    }

    @at-root div#{&__child} {
        color: #000;
    }
}
```

Expected

``` css
.parent__child {
  color: #000;
}
div.parent__child {
  color: #000;
}
```

Actual

``` css
.parent__child { /* good */
  color: #000;
}
div.parent __child { /* bug */
  color: #000;
}
```

**Comment by KittyGiraudel** [comment]
I don't think this is a bug per se. I am pretty sure this is how core designers have intended things to work at the moment. I might be wrong though.

**Comment by davidkpiano** [comment]
@HugoGiraudel is right. The `&` character in Sass (at least in the latest versions), in your usage, is treated as a variable.

``` scss
.foo {
  $foo: &;

  // This is legal
  div#{&__child} { ... }

  // And is interpreted like this
  div#{$foo __child} { ... }

  // Because this is not legal
  div#{$foo__child} { ... } // $foo__child does not exist
}
```

To fix your code, you can just concatenate: `div#{&+__child}`
