### ISSUE TITLE
Compress to shorthand when possible

### ISSUE THREAD

**Issue by LaurentGoderre** [sass/sass#1635]
I was curious to know what you think about this. In the optics of a framework where you want to offer flexibility to implementers you may use code such as this:

``` scss
.class {
 border: {
   width: $myclass-border-width
   style: $myclass-border-style;
   color: $myclass-border-color;
 };
}
```

This allows implementer to control each edge of the element. For example `$myclass-border-width` could be `2px 0 2px 0`. However, it likely that the implementer will choose not to use that level of control and use simple values for these variables which could be compressed to a shorthand value (e.g. `border: 1px solid #000`).

I was wondering if there is interest in possible compressing these when possible or is this out of scope of sass?
