### ISSUE TITLE
Define SASS variables within @media directives

### ISSUE THREAD

**Issue by banacan** [sass/sass#1639]
I have noticed that it is not possible to define SASS variables within @media directives. To give you an idea how useful this is, Foundation comes with basic styling out of the box, with design elements determined by variables.  For example, top-bar (their navigation menu) has variables for background color, link color, top-level bg color, lower-level bg color. etc., etc.  Changing the value of one variable can affect many selectors due to inheritance.  As it is now, to change the background color of child (dropdown) navigation items on desktop, one must add the following CSS rule within an @media directive:

@media #($large-up) {
.top-bar-section .dropdown li:not(.has-form):not(.active) > a:not(.button) {background-color:#333;}
}

If SASS allowed defining (or re-defining) variables within @media directives, one would only have to change the value of the variable:

@media #($large-up) {
$topbar-dropdown-bg:#333;
 }

In the above examples you can see just how difficult it is to find the correct selector(s) to make the change(s), but how easy it is to change one variable.  I do hope you will consider this small but significant enhancement for a future release.

**Comment by lolmaus** [comment]
Which media query to use is determined by browser. Browser works with compiled CSS. You want Sass to know before compilation which media query a user will hit after compilation.

That'll require some holy cow super magic powers. Until someone sends a holy PR, we have to provide explicit CSS for every possible media query.

**Comment by banacan** [comment]
No, I want SASS to output CSS (including my re-defined variable value) based on the screen max-width I choose.  What is the difference between my two examples above?  They both define a max-width and subsequently change the background color – or would if the second were possible.

**Comment by lolmaus** [comment]
What CSS do you want your second example to produce?

**Comment by banacan** [comment]
$topbar-dropdown-bg is defined by default as #222 for all screen sizes.  I want to change that color for screens larger that 64em for example.  Of course, it's not just that one value that I will need to change, there will be many changes needed to create the nav style I want for desktop vs mobile.  The point is, I can't understand why Sass won't allow the value of a variable to be defined when inside an @media directive.  This seems like such a logical use of variables. 

To answer your question directly, I want the CSS to be what is shown in my first example, and any other cascaded elements.  Basically whatever Zurb defines by that variable in Foundation.

**Comment by Snugug** [comment]
Duplicate of #340

**Comment by banacan** [comment]
One of the advantages of using a framework like Foundation or Bootstrap is having many selectors pre-defined.  The disadvantage is not always knowing (without a lot of sleuthing) what combination of selectors a given variable controls.  The whole point of defining and using variables is that it simplifies that process.  Again, looking at my first example, who would ever guess how complicated the selector would be to make the change that a simple variable value could alter?

**Comment by cimmanon** [comment]
You're only thinking in terms of simple cases.  Once you start allowing those, you get into problems with more complex cases where people expect variables within media queries to start working like it's CSS.

If you set this variable:

``` scss
@media (min-width: 15em) {
    $foo: green;
}

@media (max-width: 20em) {
    $foo: red;
}
```

What should be the output of the following Sass?

``` scss
@media (max-width: 19em) {
    .bar {
        color: $foo;
    }
}

@media (min-width: 15em) and (max-width: 20em) {
    .bar {
        color: $foo;
    }
}

@media screen and (max-width: 20em) {
    .bar {
        color: $foo;
    }
}
```

**Comment by banacan** [comment]
Foundation establishes default variable values:
$topbar-bgr: $oil !default;

You can change the value in _setting.scss.   Later in their components Zurb has something like this:
@media #{$topbar-media-query} {
      .top-bar {
        background: $topbar-bg;
        @include clearfix;
        overflow: visible;
        ...
So why can't the value of $topbar-bg be different based on breakpoints/media queries?

**Comment by banacan** [comment]
Cimmanon,

You raise a valid point.  However, SASS should not exclude usefulness to protect us from ourselves.  It should be up to the designer to ensure that there is no conflict in media queries.

**Comment by cimmanon** [comment]
My point is that adding this feature is going to make determining the compiled results difficult to reason, something the authors of Sass have historically been opposed to (see: https://github.com/sass/sass/issues/525#issuecomment-8995033).

Besides, Sass already offers a feature that will do what you're asking for:

``` scss
%foo-background {
    background-color: #333;

    @media #{$large-up} {
        background-color: #666;
    }
}

.top-bar-section .dropdown li:not(.has-form):not(.active) > a:not(.button) {
    @extend %foo-background;
}
```

**Comment by serkon** [comment]
I have tried this then i fixed my issue. It will calculate all media-breakpoint automatically by given rate (base-size/rate-size)

```scss

$base-size: 16;
$rate-size-xl: 24;

    // set default size for all cases;
    :root {
      --size: #{$base-size};
    }

    // if it's smaller then LG it will set size rate to 16/16;
    // example: if size set to 14px, it will be 14px * 16 / 16 = 14px
    @include media-breakpoint-down(lg) {
      :root {
        --size: #{$base-size};
      }
    }
    
    // if it is bigger then XL it will set size rate to 24/16;
    // example: if size set to 14px, it will be 14px * 24 / 16 = 21px
    @include media-breakpoint-up(xl) {
      :root {
        --size: #{$rate-size-xl};
      }
    }
    
@function size($px) {
   @return calc(#{$px} / $base-size * var(--size));
}

div {
  font-size: size(14px);
  width: size(150px);
}
```
