### ISSUE TITLE
rgba(#hex, 1) compiles to hex again

### ISSUE THREAD

**Issue by tatze** [sass/sass#1642]
sass versions tested: 3.2.19 and 3.4.12
### compiling error

```
background: rgba(#cccccc, 1)
```

compiles to

```
background: #cccccc;
```
### workaround:

```
background: rgba(#cccccc, 0.999999)
```

compiles to the desired

```
background: rgba(204, 204, 204, 1.0);
```
### ~~important for e.g. inline-svgs in FF~~

~~Even though it makes no difference for the usual background the `rgba()` value is important when it comes to colors inside a path in inline-svgs (e.g. Firefox can only handle rgb/rgba there).~~

Also when I ask for a rgba value I expect to get a rgba value, no matter what. :)

**Comment by stephnr** [comment]
Just a note, you can use the `red($color)` `green($color)` and `blue($color)` functions to extract these colors from a Hexadecimal value and insert them naturally into the `rgba()` function.

**Comment by tatze** [comment]
I know and I tested that too... same result when I insert them to `rgba()` with alpha=1

**Comment by cimmanon** [comment]
Sass tries to maximize browser compatibility when it comes to colors, so your only choice is to create a function specifically for this.  

``` scss
@function safe-rgba($color, $alpha: 1.0) {
    @return unquote("rgba(#{red($color)}, #{green($color)}, #{blue($color)}, #{$alpha})");
}

.foo {
  background: safe-rgba(red);
}
```

Output:

``` css
.foo {
  background: rgba(255, 0, 0, 1);
}
```
