### ISSUE TITLE
@extend + :not results in invalid css selector

### ISSUE THREAD

**Issue by eli-collins** [sass/sass#1643]
I ran across a weird border case where `@extend` + `:not` result in an invalid selector being generated, causing the browser to discard the rule entirely...

When a class selector is extended by a compound selector, and another selector explicitly excludes the class selector...

``` scss
.foo { color: red; }
li.bar { @extend .foo; }
a:not(.foo) { color: blue; }
```

... then the resulting output ends up containing an invalid `:not` selector: 

``` css
.foo, li.bar { color: red; }
a:not(.foo):not(li.bar) { color: blue; }
```

This behavior is consistent across 3.2 - 3.4.  While silently generating an invalid selector probably isn't the right choice, I can't say for sure _what_ the right behavior should be... omit the `:not(li.bar)`, issue a warning / error, or something else?

**Comment by davidkpiano** [comment]
The syntax `:not(li.bar)`, where `:not()` contains a complex selector, will be valid in **CSS 4**, so it doesn't make sense to exclude it now. Source: http://www.w3.org/TR/selectors4/#negation-pseudo

Proper usage of `@extend` here would be to set up extensions as a directed graph from the extendee to the extenders, `.foo` and `li.bar`:

``` scss
%foo { color: red; }

.foo { @extend %foo; }
li.bar { @extend %foo; }
a:not(.foo) { color: blue; }
```

**Result:**

``` scss
// Result:
.foo, li.bar {
  color: red;
}

a:not(.foo) {
  color: blue;
}
```
