### ISSUE TITLE
Block `!important`

### ISSUE THREAD

**Issue by monolithed** [sass/sass#1644]
``` scss
.foo !important {
    color: red;   
    text-align: right;   
}
```
###### Output:

``` scss
.foo {
    color: red !important;
    text-align: right !important;
}
```

Perhaps this is a very special case but may be useful not only for me ... :ghost: 

Sorry, it looks like a joke (
