### ISSUE TITLE
&& support

### ISSUE THREAD

**Issue by monolithed** [sass/sass#1645]
###### Source

``` sass
.foo {
    &&_bar:hover {
        color: red;
    }
}
```
###### Result

```
Invalid CSS after "&": expected "{", was "&_bar:hover"

"&_bar:hover" may only be used at the beginning of a compound selector.
```
###### Expected

```
.foo.foo_bar:hover {
    color: red;
}
```

**Comment by akellbl4** [comment]
:+1:

**Comment by cimmanon** [comment]
You can already do this.

``` scss
.foo {
    &#{&}_bar:hover {
        color: red;
    }
}
```
