### ISSUE TITLE
Cannot use percentage in @keyframe rule

### ISSUE THREAD

**Issue by clehnert-psl** [sass/sass#1657]
When I attempt to convert this CSS

``` css
@keyframes dash {
  0% {
    stroke-dasharray: 1,200;
    stroke-dashoffset: 0;
  }
  50% {
    stroke-dasharray: 89,200;
    stroke-dashoffset: -35;
  }
  100% {
    stroke-dasharray: 89,200;
    stroke-dashoffset: -124;
  }
}
```

...using sass-convert, I get `Error on line 2 of (css): Invalid CSS after "": expected selector, was "0%"`

I know I can change the '`0%`' to '`from`' and  '`100%`' to '`to`', but I don't think there are any other values I can use for a percentage other than 0 or 100.
