### ISSUE TITLE
UTF-8 encoding not working

### ISSUE THREAD

**Issue by thany** [sass/sass#1663]
An empty scss stylesheet containing just this:

```
a:after { content: ' ›'; }
```

Compiles to this:

```
a:after { content: ' ÔÇ║'; }
```

So, not good. Even when I add `@charset "utf-8";` to the top of my scss, it still outputs the same stuff. My scss really is saved as UTF-8, but without a BOM though (using Brackets as my editor, there's no option for it, as far as I'm aware).

Escaping it:

```
a:after { content: ' \203a'; }
```

Outputs:

```
a:after { content: ' \203a'; }
```

Kind of expected really. But:

```
a:after { content: " #{'\203a'}"; }
```

Kind of a mess, but it outputs what I want:

```
a:after { content: " ›"; }
```

But I really want to be able to use non-ANSI characters straight in my scss files. It makes things much more readable. So this looks like a double-encoding bug that needs fixing, or the `@charset` directive in need of fixing.

I'm using Sass version 3.4.13, Gem system 2.4.6, Ruby 2.1.3p242 x64, Windows 7 x64.

**Comment by nex3** [comment]
What do you get when you run `ruby -e 'puts "#{Encoding.default_internal}, #{Encoding.default_external}"'`? Can you upload your input and output files (with `@charset`) somewhere and link them here?

**Comment by thany** [comment]
First part:

```
>ruby -e 'puts "#{Encoding.default_internal}, #{Encoding.default_external}"'
, CP850
```

Second part:
No time right now. If it's still neccesary, I might to it tomorrow.

**Comment by thany** [comment]
Sorry for the delay, I got ill. So [here is a test case](https://drive.google.com/file/d/0B7XtJOKUO04la3pfZ0tzM0ozRzQ/view?usp=sharing) with files and everything.

Command I use to compile: (in a plain vanilla command prompt)

```
sass scss\default.scss css\default.css
```

**Comment by jg-digital-media** [comment]
Has this been resolved at all.

I'm currently using a web app called Sassmeister to compile this code.  where the following SCSS code. 

``` css
//list of icon names stored in a variable
$icon-names: (strategy '\e002') (twitter '\e003') (github '\e004');

//use interpolation syntax to loop through the list,
//a variable in singular to loop through the plural variable 

@each $icon-name in $icon-names {
  //pull each value from icon names to be a class selector
 .icon-#{nth($icon-name, 1)}:after {
      content: nth($icon-name, 2);  //works in libsass 3.1.0 and 
                                    //sass 3.3.14 but NOT 3.4.12

 } 
}
```

Outputs the following

``` css
@charset "UTF-8";
.icon-strategy:after {
  content: "";
}


.icon-twitter:after {
  content: "";
}

.icon-github:after {
  content: "";
}
```
