### ISSUE TITLE
Can't nest inside pseudo element.

### ISSUE THREAD

**Issue by whaaaley** [sass/sass#1669]
You can't nest selectors inside a pseudo element, like this.

``` scss
a::before {
  color: blue;

  &.toggled {
    color: red;
  }
}
```

Which would output this.

``` css
a::before {
  color: blue;
}

a.toggled::before {
  color: red;
}
```

Instead I get this CSS, which is not valid.

``` css
a::before {
  color: blue;
}

a::before.toggled {
  color: red;
}
```

I'm going to go ahead and admit this is probably more edge case-y, but I've thought about wanting to do this more than once when using pseudo elements.

**Comment by davidkpiano** [comment]
+1

I'm in agreement that this should essentially behave equivalently to `selector-unify()`:

```scss
a::before {
  color: blue;

  @at-root #{selector-unify(&, '.toggled')} {
    color: red;
  }
}

// output:
a::before {
  color: blue;
}
a.toggled::before {
  color: red;
}
```

**Comment by davidkpiano** [comment]
+1

I'm in agreement that this should essentially behave equivalently to `selector-unify()`:

``` scss
a::before {
  color: blue;

  @at-root #{selector-unify(&, '.toggled')} {
    color: red;
  }
}

// output:
a::before {
  color: blue;
}
a.toggled::before {
  color: red;
}
```
