### ISSUE TITLE
Invalid RGBA gets translated to HEX value instead of throwing error

### ISSUE THREAD

**Issue by aljopro** [sass/sass#1670]
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
Sass 3.4.13 (Selective Steve)

I have the following rule:

``` css
.conditional-asset-label {
    text-transform: uppercase;
    font-size: 40px;
    margin: 0 auto;
    width: 281px;
    position: relative;
    top: 50%;
    transform: translateY(-50%);
    text-shadow: 1px 1px 0 rgba(200,200,200,0.6) , -1px -1px 1px rgba(150,150,150,150.67);
  }
```

The 2nd improper rgba in the text-shadow gets interpreted as a hex value e.g. `text-shadow: 1px 1px 0 rgba(200, 200, 200, 0.6), -1px -1px 1px #969696;`

Expected Behavior:
this should throw an error like in older versions of sass
