### ISSUE TITLE
Placeholder not extending child anchor of a class

### ISSUE THREAD

**Issue by Simounet** [sass/sass#1684]
Hi,
I've got an issue when I'm trying to extend an anchor that is a child of a class. Here is a test with the hover pseudo-class but I had the same problem with others elements (.
## Given

``` SCSS
%link-base {
  color: green;

  &:hover {
    color: white;
    text-decoration: none;
    background-color: red;
  }
}

a {
  @extend %link-base;
  color: red;
}

.wont-extend-hover a {
  @extend %link-base;
  background-color: white;
}
#will-extend-hover a {
  @extend %link-base;
  background-color: white;
}
```
## Result

``` SCSS
a, .wont-extend-hover a, #will-extend-hover a {
  color: green;
}
a:hover, #will-extend-hover a:hover {
  color: white;
  text-decoration: none;
  background-color: red;
}

a {
  color: red;
}

.wont-extend-hover a {
  background-color: white;
}

#will-extend-hover a {
  background-color: white;
}
```
## Expected

``` SCSS
a, .wont-extend-hover a, #will-extend-hover a {
  color: green;
}
a:hover, .wont-extend-hover a:hover, #will-extend-hover a:hover {
  color: white;
  text-decoration: none;
  background-color: red;
}

a {
  color: red;
}

.wont-extend-hover a {
  background-color: white;
}

#will-extend-hover a {
  background-color: white;
}
```

It is worse if I use an id instead of the &:hover. .will-extend-hover won't be extended anymore.

Have a nice day.
