### ISSUE TITLE
Can't get a simple Sass function working

### ISSUE THREAD

**Issue by corysimmons** [sass/sass#1688]
So I found this Sass string split function here: https://github.com/at-import/Sassy-Strings/blob/master/compass/lib/sassy-strings.rb#L14

I include the function at the bottom of my Compass config.rb, and when I try to store it's demo as a var and echo it out it returns false. I'm confused. New to Sass/Compass...

``` scss
$foo: split-string('Hello World', ' ');

* {
  background: $foo; // returns background: false; why??
}
```
