### ISSUE TITLE
Transparent shims for bleeding-edge technologies

### ISSUE THREAD

**Issue by hon2a** [sass/sass#1689]
_This is a feature request (wish)._

Sass mixins make it pretty easy to use new CSS features that still require different syntax (like prefixes) in different browsers. Using a mixin like [`opacity`](http://compass-style.org/reference/compass/css3/opacity/) makes for code with similar size (and lack of duplicities) as using the native property. It has just a small drawback - syntax. Using the mixin means:
1. the developer needs to remember all of the mixins that need to be used instead of properties (it's easy to accidentally use the property instead),
2. use of a mixin makes for a less readable code, even though in this case the mixin has exactly the same meaning as the property,
3. removal of the mixin (when all relevant browsers already support the feature) requires replacing all of its uses as well.

These points could be used to argue for different mixin use syntax in general, but I don't want to get into _that_ discussion here. I just wish that there was some additional syntax for creation of these "property shim mixins", like:

``` scss
@shim flex-wrap($args...) {
   -webkit-flex-wrap: $args;
   @original;
}
```

which could be used transparently in SCSS:

``` css
.foo {
   flex-wrap: nowrap;
}
```

to produce CSS:

``` css
.foo {
   -webkit-flex-wrap: nowrap;
   flex-wrap: nowrap;
}
```
