### ISSUE TITLE
Escaping regression in 3.4.13

### ISSUE THREAD

**Issue by xzyfer** [sass/sass#1703]
Discovered in https://github.com/sass/libsass/issues/1115.

``` scss
$x: "y"; 
li:before { content: "#{$x}\00a0"; }
```

Ruby Sass 3.3.14

``` css
li:before {
  content: "y\00a0"; }
```

Ruby Sass 3.4.13

``` css
@charset "UTF-8";
li:before {
  content: "y "; }
```
