### ISSUE TITLE
Inheritence with variable overrides.

### ISSUE THREAD

**Issue by Gisleburt** [sass/sass#1708]
I'm not sure if this is a bug, or a feature request. Essentially what I'd like to do is create simple classes, and then extend them and modify their properties (aka variables).

Here is an example:

``` HTML
<div class="base"></div>
<div class="child"></div>
```

SCSS:

``` SCSS
.base {
  $myColor: blue;
  width: 100px;
  height: 60px;
  background-color: $myColor;
  margin:5px;
}

.child {
  @extend .base;
  $myColor: red;
}
```

[If you run this](http://jsfiddle.net/Gisleburt/p80j6Lqk/), you'll see both boxes are blue.

While it's easy enough to add `background-color: red;` to `.child` here, as shown in this [updated example](http://jsfiddle.net/Gisleburt/p80j6Lqk/1/), when you have multiple variables being repeated multiple times, this quickly becomes impractical.

I've read about using mixins as a work around, but writing the entire class and all it's subclasses into a mixin seems like overkill, when all I really want to do is change the color.

Is there another way to get this sort of functionality?

If it helps, this is _roughly_ what I'm working on: http://jsfiddle.net/Gisleburt/pycu9uw1/
