### ISSUE TITLE
@page directive compiling incorrectly?

### ISSUE THREAD

**Issue by slwfleming** [sass/sass#1714]
Current compass output with selector inside the parenthesis:

``` css
@page{.myclassname{margin:0cm}}
```

Uncompiled scss:

``` scss
.myclassname {
  @media print {
    @page {
      margin: 0cm;
    }
  }
}
```

w3 documents the `@page` directive should be written like this with the selector outside of the parenthesis:

``` css
@page .myclassname {
  margin:0cm;
}
```

This is an unfortunate inconsistency in formatting from w3. Other directives are written with selectors inside the parenthesis. Confusing:

``` css
@media print {
    .myclassname {
        margin:0cm;
    }
}
```
