### ISSUE TITLE
Conditional variable assignment (assign-if-not-set)

### ISSUE THREAD

**Issue by flying-sheep** [sass/sass#1717]
Hi, it would be awesome to have a `variable ?: value` syntax that only assigns to a variable if it’s not already defined.
### Motivation

the theme system of [hakimel/reveal.js](https://github.com/hakimel/reveal.js) works like this:

``` scss
@import "template/settings"; //set variables to defaults

$varToOverride: some-value; //override variables

@import "template/theme"; //use variables in template/skeleton theme
```

this is
1. unwieldy and
2. inflexible: there’s no way to inherit from a theme and just change some variable overrides.

you’d have to make every theme a (i.e. the middle part of overrides) into _yet another_ file, and then change it to:

``` scss
@import "template/settings";
@import "foobar-theme-body";
@import "template/theme";
```

and an inheriting theme would be `baz-theme-body.scss`

``` scss
@import "foobar-theme-body";
$varToOverride: value;
```

and

``` scss
@import "template/settings";
@import "baz-theme-body";
@import "template/theme";
```

which is complex. i’m sure i’ve lost some of you already
### Gain of proposal

a theme `foobar-theme.scss` would be:

``` scss
$varToOverride ?: value;
@import "template/theme";
```

and a inheriting theme would be

``` scss
$varToOverride ?: value;
@import "foobar-theme";
```

or (if `foobar-theme` didn’t use `?:`)

``` scss
@import "foobar-theme";
$varToOverride: value;
@import "template/theme";
```
### Syntax

`?:` is just a strawman. i’m not in any way attached to it.

**Comment by cimmanon** [comment]
Sass already has such a feature, it's called [the `!default` flag](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#variable_defaults_).  You should petition the maintainers of reveal.js to start using it.

``` scss
$content: "First content";
$content: "Second content?" !default;
$new_content: "First time reference" !default;

#main {
  content: $content;
  new-content: $new_content;
}
```

Compiles to

``` css
#main {
  content: "First content";
  new-content: "First time reference"; }
```
