### ISSUE TITLE
nth to return null if out of list range

### ISSUE THREAD

**Issue by jakob-e** [sass/sass#1721]
This may be more of a question than a request but is there a special reason why asking for a nth item outside the list range throws an error rather than returning null? 

Returning null would be very helpful when e.g. evaluating  arguments:

``` SCSS

@mixin cover($arglist... /* $top, $right, $bottom, $left */){
  $map: keywords($arglist);
  top     : map-get($map, top)    or nth($arglist, 1) or 0;
  right   : map-get($map, right)  or nth($arglist, 2) or nth($arglist, 1) or 0;
  bottom  : map-get($map, bottom) or nth($arglist, 3) or nth($arglist, 1) or 0;
  left    : map-get($map, left)   or nth($arglist, 4) or nth($arglist, 2) or nth($arglist, 1) or 0;
  position: absolute;
}

```

... now we need to replace nth with something like this: 

``` SCSS
@function nth-or-null($list, $index) {
  @return if(length($list) >= $index, nth($list, $index), null);
}
```
