### ISSUE TITLE
Backslashes are retained in unquoted text

### ISSUE THREAD

**Issue by jzempel** [sass/sass#1723]
SCSS:

``` sass
$foo: 'baz';
$bar: 'qux';
$test: "foo(\"#{$foo}\") bar(\"#{$bar}\")";

sass {
  test: unquote($test);
}
```

CSS:

``` css
sass {
  test: foo(\"baz\") bar(\"qux\");
}
```

Is this the expected result? I believe this changed somewhere between 3.2 and 3.3. I can workaround by using `$test: 'foo("#{$foo}") bar("#{$bar}")';`.
