### ISSUE TITLE
Regression in @keyframes

### ISSUE THREAD

**Issue by xzyfer** [sass/sass#1724]
``` scss
@mixin keyframes($animation-name) {
  @keyframes $animation-name {
    @content;
  }
}

@include keyframes(bounce) {
  0%, 20%, 50%, 80%, 100% {transform: translateY(0);}
  40% {transform: translateY(-30px);}
  60% {transform: translateY(-15px);}
}
```

Sass 3.3.14

``` css
@keyframes bounce {
  0%, 20%, 50%, 80%, 100% {
    transform: translateY(0); }

  40% {
    transform: translateY(-30px); }

  60% {
    transform: translateY(-15px); } }
```

Sass 3.4.13

``` css
@keyframes $animation-name {
  0%, 20%, 50%, 80%, 100% {
    transform: translateY(0); }
  40% {
    transform: translateY(-30px); }
  60% {
    transform: translateY(-15px); } }
```
