### ISSUE TITLE
BEM-style elements and @extend

### ISSUE THREAD

**Issue by TheEponymousBob** [sass/sass#1725]
Not sure if this is intended behaviour, but seems odd. I want several concrete blocks that have most sub-elements in common, but with some variations, so am looking at @extends. Trying something like the following:

```
%top-level {
  background: white;
  &__sub-item {
    background: none;
  }
}

.concrete {
  @extends %top-level;
}
```

Expecting: 

```
.concrete {
  background: white;
}
.concrete__sub-item {
  background: none;
}
```

but geting only

```
.concrete {
  background: white;
}
```

If I replace the nested selector with (for example) `& .child`, I get what I'd expect - an HTML child selector correctly shared by the @extends. Also, if I turn `%top-level` into a concrete class, the concatenated class works for it, but not its extension. I.e.:

```
.top-level {
    background: white;
    &__sub-item {
        background: none;
    }
    & .child {
        background: blue;
    }
}
.concrete {
    @extend .top-level;
}
```

gives:

```
.top-level, .concrete {
  background: white;
}
.top-level__sub-item {
  background: none;
}
.top-level .child, .concrete .child {
  background: blue;
}
```

**Comment by cimmanon** [comment]
Change it to a class and you'll see what's actually happening:

``` scss
.top-level {
  background: white;
  &__sub-item {
    background: none;
  }
}

.concrete {
  @extend .top-level;
}
```

Output:

``` css
.top-level, .concrete {
  background: white;
}
.top-level__sub-item {
  background: none;
}
```

The only thing that makes an extend only selector different from any other selector is that it is suppressed in the final output.
