### ISSUE TITLE
Change list separator

### ISSUE THREAD

**Issue by thany** [sass/sass#1728]
It doesn't seem possible to change the seaprator of a list.
I propose a function `change_separator` or similar.

I found a need for this, as sometimes one is not in control where a list comes from or how it's created. Using a framework, or using a built-in function that builds you a list like `map_values`. Sometimes you just _always_ get one separator, when you need to other.

Another option is to give control over how a list is rendered to the output. That is to say, allow overriding the separator when outputting it.

**Comment by nex3** [comment]
You can do this via `join($list, (), space)`.

**Comment by thany** [comment]
I though you might say that, but it doesn't feel right to join one list with another empty one just to change the separator. I bet it makes a copy, and tries to actually join stuff, which is needlessly complicated for just changing the separator. Also, the join-method doesn't _look_ like it changes the seaparator, i.e. not good for maintenance.

**Comment by nex3** [comment]
If you don't like the name, write a wrapper function.

**Comment by thany** [comment]
And how do I change ONLY the separator, without putting the list through a join function?

Look, I understand you don't want to cencern yourself with petty issues like this, I get it. But you make it look like I'm just whining. I'm trying to suggest ways to make Sass nicer to work with. If you prefer keeping Sass a more verbose and potentially less efficient language, fine, but then just say so up front.

**Comment by davidkpiano** [comment]
``` scss
@function set-separator($list, $separator: list-separator($list)) {
  @if $separator == 'comma' or $separator == 'space' {
    @return join($list, (), $separator);
  }
  @error 'Not a valid separator: #{$separator}';
}

$foo: set-separator(1 2 3, comma);
// => 1, 2, 3
```
