### ISSUE TITLE
Regression in interpolation in @supports

### ISSUE THREAD

**Issue by xzyfer** [sass/sass#1729]
The behaviour of interpolation in `@supports` has changed 3.4.14. I expect the new behaviour is the intended behaviour given previous similar issues.

``` css
$query: "(feature1: val)";
$feature: feature2;
$val: val;
@supports #{$query} and ($feature: $val) or (not ($feature + 3: $val + 4)) {
  foo {a: b}
}
```

Ruby Sass 3.4.13

``` css
@supports (feature1: val) and (feature2: val) or (not (feature23: val4)) {
  foo {
    a: b; } }
```

Ruby Sass 3.4.14

```
Error: Invalid CSS after "...feature: $val) ": expected "{", was "or (not ($featu..."
```

**Comment by cimmanon** [comment]
According to the specification, the feature query you're trying to generate is invalid:  you can't mix `and` with `or`, you must use parentheses to remove ambiguity.

``` scss
$query: "(feature1: val)";
$feature: feature2;
$val: val;
@supports (#{$query} and ($feature: $val)) or (not ($feature + 3: $val + 4)) {
  foo {a: b}
}
```

Output:

``` css
@supports ((feature1: val) and (feature2: val)) or (not (feature23: val4)) {
  foo {
    a: b;
  }
}
```
