### ISSUE TITLE
Regression in colour name evaluation

### ISSUE THREAD

**Issue by xzyfer** [sass/sass#1730]
This behaviour has changed in 3.4.14.

``` css
div {
  foo: mix(#f00, #00f); }
```

Ruby Sass 3.4.13

``` css
div {
  roo: #7f007f; }
```

Ruby Sass 3.4.14

``` css
div {
  roo: purple; }
```

The hex value for the CSS colour purple is `#800080`.
