### ISSUE TITLE
Merging and Checking Sass Maps seems to not work in 3.4

### ISSUE THREAD

**Issue by stowball** [sass/sass#1731]
I'm attempting to reduce the class output of a framework's mixin by counting duplicates with a map. This works perfectly in 3.3.14, Libass 3.24 works mostly except `inspect`ing & debugging the map says it is the empty default, but 3.4.13 doesn't work at all: the map remains completely empty; nothing is map-merged, no classes are generated, and if you uncomment the custom `debug-map()` call, it returns `() isn't a valid CSS value.`

Here's a link to a Sassmeister demo in 3.3.14: http://sassmeister.com/gist/f9307987f1b3b4f6546f or you see the SCSS below:

I'll explain what the code is trying to do:
1. Loop through each of the 12 `$mixin-denominator-number`s
2. For each, loop through again from 1 up to what ever the current `$mixin-denominator-number` is
3. Generate a `u-XXXpc` percentage class `$selector` by dividing the `$numerator` by `$denominator` & multiply by 100.
4. For the the first time that this `$selector` is found, insert it into the`$_percentage-class-instances` map with a value of `1`
5. If the `$selector` already exists as a key in the map, increment its value by `1`. This allows me to find duplicates.
6. If there is only one instance of the `$selector` in the map, output the actual class.

``` scss
/*
  LINE 20 - CHECKING & SETTING MAPS FAILS IN 3.4.x
*/

$mixin-denominator-numbers:               (1 2 3 4 5 6 7 8 9 10 11 12) !default;

$_percentage-class-instances:             () !default;

@mixin generate-percentage-classes() {
  @each $denominator in $mixin-denominator-numbers {
    @for $numerator from 1 through max($denominator - 1, 1) {

      $selector: ".u-#{ceil(($numerator/$denominator) * 100)}pc";

      @if (map-has-key($_percentage-class-instances, $selector)) {
        $_percentage-class-instances: map-merge($_percentage-class-instances, ($selector: map-get($_percentage-class-instances, $selector) + 1));
      }
      @else {
        $_percentage-class-instances: map-merge($_percentage-class-instances, ($selector: 1));
      }

      a { content: "#{map-get($_percentage-class-instances, $selector)} instance(s) of #{$selector}"; }

      @if (map-get($_percentage-class-instances, $selector) == 1) {
        #{$selector} {
          width: percentage($numerator/$denominator);
        }
      }
    }
  }
}

@include generate-percentage-classes();

.inspect-map {
  content: "#{inspect($_percentage-class-instances)}";
}
```

The desired output should be:

``` css
a {
  content: "1 instance(s) of .u-100pc";
}

.u-100pc {
  width: 100%;
}

a {
  content: "1 instance(s) of .u-50pc";
}

.u-50pc {
  width: 50%;
}

a {
  content: "1 instance(s) of .u-33pc";
}

.u-33pc {
  width: 33.33333%;
}

a {
  content: "1 instance(s) of .u-67pc";
}

.u-67pc {
  width: 66.66667%;
}

a {
  content: "1 instance(s) of .u-25pc";
}

.u-25pc {
  width: 25%;
}

a {
  content: "2 instance(s) of .u-50pc";
}

a {
  content: "1 instance(s) of .u-75pc";
}

.u-75pc {
  width: 75%;
}

a {
  content: "1 instance(s) of .u-20pc";
}

.u-20pc {
  width: 20%;
}

a {
  content: "1 instance(s) of .u-40pc";
}

.u-40pc {
  width: 40%;
}

a {
  content: "1 instance(s) of .u-60pc";
}

.u-60pc {
  width: 60%;
}

a {
  content: "1 instance(s) of .u-80pc";
}

.u-80pc {
  width: 80%;
}

a {
  content: "1 instance(s) of .u-17pc";
}

.u-17pc {
  width: 16.66667%;
}

a {
  content: "2 instance(s) of .u-33pc";
}

a {
  content: "3 instance(s) of .u-50pc";
}

a {
  content: "2 instance(s) of .u-67pc";
}

a {
  content: "1 instance(s) of .u-83pc";
}

.u-83pc {
  width: 83.33333%;
}

a {
  content: "1 instance(s) of .u-14pc";
}

.u-14pc {
  width: 14.28571%;
}

a {
  content: "1 instance(s) of .u-29pc";
}

.u-29pc {
  width: 28.57143%;
}

a {
  content: "1 instance(s) of .u-43pc";
}

.u-43pc {
  width: 42.85714%;
}

a {
  content: "1 instance(s) of .u-57pc";
}

.u-57pc {
  width: 57.14286%;
}

a {
  content: "1 instance(s) of .u-71pc";
}

.u-71pc {
  width: 71.42857%;
}

a {
  content: "1 instance(s) of .u-86pc";
}

.u-86pc {
  width: 85.71429%;
}

a {
  content: "1 instance(s) of .u-13pc";
}

.u-13pc {
  width: 12.5%;
}

a {
  content: "2 instance(s) of .u-25pc";
}

a {
  content: "1 instance(s) of .u-38pc";
}

.u-38pc {
  width: 37.5%;
}

a {
  content: "4 instance(s) of .u-50pc";
}

a {
  content: "1 instance(s) of .u-63pc";
}

.u-63pc {
  width: 62.5%;
}

a {
  content: "2 instance(s) of .u-75pc";
}

a {
  content: "1 instance(s) of .u-88pc";
}

.u-88pc {
  width: 87.5%;
}

a {
  content: "1 instance(s) of .u-11pc";
}

.u-11pc {
  width: 11.11111%;
}

a {
  content: "1 instance(s) of .u-22pc";
}

.u-22pc {
  width: 22.22222%;
}

a {
  content: "3 instance(s) of .u-33pc";
}

a {
  content: "1 instance(s) of .u-44pc";
}

.u-44pc {
  width: 44.44444%;
}

a {
  content: "1 instance(s) of .u-56pc";
}

.u-56pc {
  width: 55.55556%;
}

a {
  content: "3 instance(s) of .u-67pc";
}

a {
  content: "1 instance(s) of .u-78pc";
}

.u-78pc {
  width: 77.77778%;
}

a {
  content: "1 instance(s) of .u-89pc";
}

.u-89pc {
  width: 88.88889%;
}

a {
  content: "1 instance(s) of .u-10pc";
}

.u-10pc {
  width: 10%;
}

a {
  content: "2 instance(s) of .u-20pc";
}

a {
  content: "1 instance(s) of .u-30pc";
}

.u-30pc {
  width: 30%;
}

a {
  content: "2 instance(s) of .u-40pc";
}

a {
  content: "5 instance(s) of .u-50pc";
}

a {
  content: "2 instance(s) of .u-60pc";
}

a {
  content: "1 instance(s) of .u-70pc";
}

.u-70pc {
  width: 70%;
}

a {
  content: "2 instance(s) of .u-80pc";
}

a {
  content: "1 instance(s) of .u-90pc";
}

.u-90pc {
  width: 90%;
}

a {
  content: "1 instance(s) of .u-9pc";
}

.u-9pc {
  width: 9.09091%;
}

a {
  content: "1 instance(s) of .u-18pc";
}

.u-18pc {
  width: 18.18182%;
}

a {
  content: "1 instance(s) of .u-27pc";
}

.u-27pc {
  width: 27.27273%;
}

a {
  content: "1 instance(s) of .u-36pc";
}

.u-36pc {
  width: 36.36364%;
}

a {
  content: "1 instance(s) of .u-45pc";
}

.u-45pc {
  width: 45.45455%;
}

a {
  content: "1 instance(s) of .u-55pc";
}

.u-55pc {
  width: 54.54545%;
}

a {
  content: "1 instance(s) of .u-64pc";
}

.u-64pc {
  width: 63.63636%;
}

a {
  content: "1 instance(s) of .u-73pc";
}

.u-73pc {
  width: 72.72727%;
}

a {
  content: "1 instance(s) of .u-82pc";
}

.u-82pc {
  width: 81.81818%;
}

a {
  content: "1 instance(s) of .u-91pc";
}

.u-91pc {
  width: 90.90909%;
}

a {
  content: "1 instance(s) of .u-8pc";
}

.u-8pc {
  width: 8.33333%;
}

a {
  content: "2 instance(s) of .u-17pc";
}

a {
  content: "3 instance(s) of .u-25pc";
}

a {
  content: "4 instance(s) of .u-33pc";
}

a {
  content: "1 instance(s) of .u-42pc";
}

.u-42pc {
  width: 41.66667%;
}

a {
  content: "6 instance(s) of .u-50pc";
}

a {
  content: "1 instance(s) of .u-58pc";
}

.u-58pc {
  width: 58.33333%;
}

a {
  content: "4 instance(s) of .u-67pc";
}

a {
  content: "3 instance(s) of .u-75pc";
}

a {
  content: "2 instance(s) of .u-83pc";
}

a {
  content: "1 instance(s) of .u-92pc";
}

.u-92pc {
  width: 91.66667%;
}

.inspect-map {
  content: '(".u-100pc": 1, ".u-50pc": 6, ".u-33pc": 4, ".u-67pc": 4, ".u-25pc": 3, ".u-75pc": 3, ".u-20pc": 2, ".u-40pc": 2, ".u-60pc": 2, ".u-80pc": 2, ".u-17pc": 2, ".u-83pc": 2, ".u-14pc": 1, ".u-29pc": 1, ".u-43pc": 1, ".u-57pc": 1, ".u-71pc": 1, ".u-86pc": 1, ".u-13pc": 1, ".u-38pc": 1, ".u-63pc": 1, ".u-88pc": 1, ".u-11pc": 1, ".u-22pc": 1, ".u-44pc": 1, ".u-56pc": 1, ".u-78pc": 1, ".u-89pc": 1, ".u-10pc": 1, ".u-30pc": 1, ".u-70pc": 1, ".u-90pc": 1, ".u-9pc": 1, ".u-18pc": 1, ".u-27pc": 1, ".u-36pc": 1, ".u-45pc": 1, ".u-55pc": 1, ".u-64pc": 1, ".u-73pc": 1, ".u-82pc": 1, ".u-91pc": 1, ".u-8pc": 1, ".u-42pc": 1, ".u-58pc": 1, ".u-92pc": 1)';
}
```

but in 3.4.13, the result is this:

``` css
/*
  LINE 39 - CHECKING & SETTING MAPS FAILS IN 3.4.x
*/
a {
  content: " instance(s) of .u-100pc";
}

a {
  content: " instance(s) of .u-50pc";
}

a {
  content: " instance(s) of .u-33pc";
}

a {
  content: " instance(s) of .u-67pc";
}

a {
  content: " instance(s) of .u-25pc";
}

a {
  content: " instance(s) of .u-50pc";
}

a {
  content: " instance(s) of .u-75pc";
}

a {
  content: " instance(s) of .u-20pc";
}

a {
  content: " instance(s) of .u-40pc";
}

a {
  content: " instance(s) of .u-60pc";
}

a {
  content: " instance(s) of .u-80pc";
}

a {
  content: " instance(s) of .u-17pc";
}

a {
  content: " instance(s) of .u-33pc";
}

a {
  content: " instance(s) of .u-50pc";
}

a {
  content: " instance(s) of .u-67pc";
}

a {
  content: " instance(s) of .u-83pc";
}

a {
  content: " instance(s) of .u-14pc";
}

a {
  content: " instance(s) of .u-29pc";
}

a {
  content: " instance(s) of .u-43pc";
}

a {
  content: " instance(s) of .u-57pc";
}

a {
  content: " instance(s) of .u-71pc";
}

a {
  content: " instance(s) of .u-86pc";
}

a {
  content: " instance(s) of .u-13pc";
}

a {
  content: " instance(s) of .u-25pc";
}

a {
  content: " instance(s) of .u-38pc";
}

a {
  content: " instance(s) of .u-50pc";
}

a {
  content: " instance(s) of .u-63pc";
}

a {
  content: " instance(s) of .u-75pc";
}

a {
  content: " instance(s) of .u-88pc";
}

a {
  content: " instance(s) of .u-11pc";
}

a {
  content: " instance(s) of .u-22pc";
}

a {
  content: " instance(s) of .u-33pc";
}

a {
  content: " instance(s) of .u-44pc";
}

a {
  content: " instance(s) of .u-56pc";
}

a {
  content: " instance(s) of .u-67pc";
}

a {
  content: " instance(s) of .u-78pc";
}

a {
  content: " instance(s) of .u-89pc";
}

a {
  content: " instance(s) of .u-10pc";
}

a {
  content: " instance(s) of .u-20pc";
}

a {
  content: " instance(s) of .u-30pc";
}

a {
  content: " instance(s) of .u-40pc";
}

a {
  content: " instance(s) of .u-50pc";
}

a {
  content: " instance(s) of .u-60pc";
}

a {
  content: " instance(s) of .u-70pc";
}

a {
  content: " instance(s) of .u-80pc";
}

a {
  content: " instance(s) of .u-90pc";
}

a {
  content: " instance(s) of .u-9pc";
}

a {
  content: " instance(s) of .u-18pc";
}

a {
  content: " instance(s) of .u-27pc";
}

a {
  content: " instance(s) of .u-36pc";
}

a {
  content: " instance(s) of .u-45pc";
}

a {
  content: " instance(s) of .u-55pc";
}

a {
  content: " instance(s) of .u-64pc";
}

a {
  content: " instance(s) of .u-73pc";
}

a {
  content: " instance(s) of .u-82pc";
}

a {
  content: " instance(s) of .u-91pc";
}

a {
  content: " instance(s) of .u-8pc";
}

a {
  content: " instance(s) of .u-17pc";
}

a {
  content: " instance(s) of .u-25pc";
}

a {
  content: " instance(s) of .u-33pc";
}

a {
  content: " instance(s) of .u-42pc";
}

a {
  content: " instance(s) of .u-50pc";
}

a {
  content: " instance(s) of .u-58pc";
}

a {
  content: " instance(s) of .u-67pc";
}

a {
  content: " instance(s) of .u-75pc";
}

a {
  content: " instance(s) of .u-83pc";
}

a {
  content: " instance(s) of .u-92pc";
}

.inspect-map {
  content: "()";
}
```

I also tried to recreate a further reduced test case of a simple for loop (http://sassmeister.com/gist/e60ec25e9d7734b7bb49).

The following code:

``` scss
$_map: (
  0: 0
);

@for $i from 1 through 5 {
  $_map: map-merge($_map, ($i: $i));
}

a {
  content: "#{inspect($_map)}";
}

// This breaks in Ruby Sass
b {
  content: "#{$_map}";
}
```

works in LibSass 3.2.14 with the output being:

``` css
a {
  content: "(0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5)";
}

b {
  content: "(0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5)";
}
```

but both 3.3.14 and 3.14.13 of Ruby Sass both error with:

``` css
(0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5) isn't a valid CSS value.
```

Any help in indentifying and/or rectifying this issue would be greatly appreciated.

**Comment by nex3** [comment]
Can you reduce this to a smaller reproduction? It's hard to tell what's going on with so much content there. If you can figure out exactly which function isn't behaving how you expect and how it's behaving wrong, that would be very helpful.

**Comment by stowball** [comment]
Sure! I've updated the issue to reduce it a single, simpler mixin, described what it's trying to do and updated the Sassmeister link. HTH

**Comment by stowball** [comment]
Ummm so my update to the issue didn't stick? Awkward. I'll write it again soon

**Comment by stowball** [comment]
Updated!

**Comment by chriseppstein** [comment]
a map is not a value that can be output to css and understood. This error catches many common coding mistakes. The inspect function is provided to return a string for values that cannot be understood by css. By using this function, you're saying that you you know what you're doing so we don't need to give you an error.

Libsass should be giving an error.  I have filed a bug to let them know about this inconsistency.

https://github.com/sass/libsass/issues/1246

**Comment by stowball** [comment]
But I don't want to output a map value to CSS. The `a { content: "" }` in my primary example was just a debugging attempt since Sassmeister doesn't support `@debug`.

The issue is that trying to dynamically set a map's key value (or increment it if it exists) and then check to see if it's 1 doesn't work.

**Comment by nex3** [comment]
If the debugging isn't what's going wrong, what is? The original SassMeister is still way too much code to wade through. Can you produce a smaller reproduction that avoids the map-debugging issue?

**Comment by stowball** [comment]
I can't make it any simpler than this: http://sassmeister.com/gist/415d43ce191c38546e7f

``` scss
$mixin-denominator-numbers:               (1 2 3) !default;
$_percentage-class-instances:              () !default;

@mixin generate-percentage-classes() {
  @each $denominator in $mixin-denominator-numbers {

    $selector: ".u-#{$denominator * 100}pc";

    @if (map-has-key($_percentage-class-instances, $selector)) {
      $_percentage-class-instances: map-merge($_percentage-class-instances, ($selector: 2));
    }
    @else {
      $_percentage-class-instances: map-merge($_percentage-class-instances, ($selector: 1));
    }

    @if (map-get($_percentage-class-instances, $selector) == 1) {
      #{$selector} {
        width: percentage($denominator);
      }
    }
  }
}

@include generate-percentage-classes();
```

The output of which should be:

``` css
.u-100pc {
  width: 100%;
}

.u-200pc {
  width: 200%;
}

.u-300pc {
  width: 300%;
}
```

For some reason, the `@if (map-has-key($_percentage-class-instances, $selector)) {` line, although it will now never match because I removed the other loop (so shouldn't make any difference), breaks in 3.4.

If you remove the if/else and just have the `$_percentage-class-instances: map-merge($_percentage-class-instances, ($selector: 1));` then the `$selector` key will be 1, and the selector output because `@if (map-get($_percentage-class-instances, $selector) == 1) {` matches.

But for some reason, the check for `map-has-key` breaks the map in 3.4, but works in 3.3 and LibSass

**Comment by cimmanon** [comment]
It's not a problem with map-get, it's a problem with global variables.  If you want to modify a global variable, you have to use the `!global` flag.

``` scss
@mixin generate-percentage-classes() {
  @each $denominator in $mixin-denominator-numbers {

    $selector: ".u-#{$denominator * 100}pc";

    @if (map-has-key($_percentage-class-instances, $selector)) {
      $_percentage-class-instances: map-merge($_percentage-class-instances, ($selector: 2)) !global;
    }
    @else {
      $_percentage-class-instances: map-merge($_percentage-class-instances, ($selector: 1)) !global;
    }

    @if (map-get($_percentage-class-instances, $selector) == 1) {
      #{$selector} {
        width: percentage($denominator);
      }
    }
  }
}
```

Sass 3.3 emits a deprecation warning when you try to modify global variables, but you don't see that from Sassmeister.
