### ISSUE TITLE
Zero-width space results in error

### ISSUE THREAD

**Issue by mendelk** [sass/sass#1735]
Paste this in [sassmeister](http://sassmeister.com/) to see what I mean:

``` scss
.test {
  color: pink
}​
```

The [Zero-width space](https://en.wikipedia.org/wiki/Zero-width_space) causes it to error out.
