### ISSUE TITLE
BEM and placeholder selectors

### ISSUE THREAD

**Issue by alexanderbuhler** [sass/sass#1736]
Hi.

So I'm using BEM in multiple projects now and stumbled upon a quite dissatisfying behavior. I used to extend placeholder selectors using normal child-selectors like `&.bar`. Now, with BEM in mind, the nested children will more likely be `&__bar` or `&_bar`. 

In the compiled view, I'd expect something like this:

SASS:

``` sass
%foo {
    color: red;
    &_bar {
        font-size: 12px;
    }
}

.elem {
    @extend %foo;
}
```

CSS:

``` css
.elem {
    color: red;
}

.elem_bar {
    font-size: 12px;
}
```

instead I just get...

``` css
.elem {
    color: red;
}
```

with `%foo_bar` as an extra placeholder selector made available in my sass environment.

Bug or Feature?

Regards
alex
