### ISSUE TITLE
Error when trying to pass a map variable within a @each loop to a function

### ISSUE THREAD

**Issue by cheryllaird** [sass/sass#1756]
I have a function that returns the most contrasted colour of a given value. However, I have encountered a problem when iterating over a Sass Map and trying to pass through a variable.

``` css
@function contrast-color($bg-color, $dark-color:#000000, $light-color:#ffffff, $threshold:70) {
    @if (lightness($bg-color) > $threshold) {
        @return $dark-color;
    }
    @else {
        @return $light-color;
    }
}

$themes: (
    red: '#DC3522',
    blue: '#263248',
    green: '#1F8A70'
);

.textbox {
  padding: 20px;

  @each $theme, $color in $themes {
    &.theme--#{$theme} {
      background-color: #{$color};
      color: contrast-color(#{$color});
    }
  }
}
```

This produces the following error:

``` css
$color: "#DC3522" is not a color for `lightness'
```

However, if I was to pass `color: contrast-color(#DC3522);` no error is thrown.

Live example can be found here:
http://codepen.io/cheryllaird/pen/oXoYvM
