### ISSUE TITLE
Radial gradient position being doubled on compile

### ISSUE THREAD

**Issue by ryanantonydunn** [sass/sass#1758]
Just a little doubling bug when the radial gradient syntax is compiled.

``` css
.test {
  background: radial-gradient(at top right, #fff, #000);
}
```

Compiles to:

``` css
.test {
  background: radial-gradient(at top right at top right, #ffffff, #000000);
}
```
