### ISSUE TITLE
Get property value from parent selector

### ISSUE THREAD

**Issue by afonsomatos** [sass/sass#1759]
Is this possible?

``` css
.parent {
    height: 20px;
    .child {
        height: parent(height) / 2;
    }
}
```

**Comment by davidkpiano** [comment]
Unfortunately (well, for very good reasons), it's not possible. Use variables:

``` scss
.parent {
  $parent-height: 20px;
  height: $parent-height;
  .child {
    height: $parent-height / 2;
  }
}
```
