### ISSUE TITLE
combining ampersand as class of same element selector doesn't work

### ISSUE THREAD

**Issue by Zxurian** [sass/sass#1760]
when trying to reference a parent selector using an element to include parent selector as a class, it errors out. 
## Expected css compilation:

``` css
.stamp {
    color: rgb(255, 0, 0);
    background-color: rgb(0, 0, 255);
}
a.stamp {
    color: rgb(0, 255, 0);
    background-color: rgb(0, 0, 255);
}
```
## What I've tried

``` sass
.stamp {
    color: rgb(255, 0, 0);
    background-color: rgb(0, 0, 255);
    a& {
        color: rgb(0, 255, 0);
    }
}
```

sassmeister reports as `invalid selector after a on line 4 at column 3`

``` sass
.stamp {
    color: rgb(255, 0, 0);
    background-color: rgb(0, 0, 255);
    a.& {
        color: rgb(0, 255, 0);
    }
}
```

sassmeister reports as `property "a" must be followed by a ':' on line 4 at column 3`
## Working alternatives

The only way I can accomplish what I'm looking for right now that I can see is

``` sass
.stamp {
    color: rgb(255, 0, 0);
    background-color: rgb(0, 0, 255);
}
a.stamp {
    @extend .stamp;
    color: rgb(255, 0, 0);
}
```

which seems unecessary to me given that the `&` can be used as parent references in other contexts. (`&:hover`, `a &`, etc...)
