### ISSUE TITLE
incorrect error message $map when passing variable as an argument

### ISSUE THREAD

**Issue by petermakowski** [sass/sass#1763]
I am running `Sass 3.4.15 (Selective Steve)`.
When I try to pass a variable as an argument to a sass map:

```
@function palette($palette, $shade: 'base') {
  @return map-get(map-get($palettes, $palette), $shade);
}

color: palette($color-primary, dark);
```

I get an error message pinpointing the function line number instead of actual source of the problem:
`$map: null is not a map for 'map-get'`

I was trying to figure it our for a while, thought it's a Sass bug.
Error message could be more helpful than that, really!

Related to: https://github.com/sass/sass/issues/1519

**Comment by nex3** [comment]
Without further information, I assume that either `$palettes` or `map-get($palettes, $palette)` is `null`. Given that, Sass doesn't have the context to tell you any more information about what went wrong. It doesn't keep a detailed history of where each object came from; as far as it knows, the place you passed `null` to `map-get` _is_ the source of the problem.

If you want better error handling in that function, you're welcome to add it yourself:

``` scss
@function palette($palette, $shade: 'base') {
  $palette-map: map-get($palettes, $palette);
  @if $palette-map == null {
    @error "#{$palette} is not a valid palette name.";
  }

  @return map-get($palette-map, $shade);
}

color: palette($color-primary, dark);
```
