### ISSUE TITLE
variable doesnt get override when in class

### ISSUE THREAD

**Issue by julestruong** [sass/sass#1777]
Why can't we do this ? 
I know there is work around but i think this is huge lack.

``` css
$height: 16px;

.small {
   $height : 8px;
}

.medium {
   $height : 12px;
}

.div {
   height : $height;
}
```

**Comment by cimmanon** [comment]
Directly related to https://github.com/sass/sass/issues/1227 (and many others)

**Comment by chriseppstein** [comment]
I assume that you'd like sass to output something like:

``` css
.div.small { height: 8px; }
.div.medium {height: 12px; }
```

Obviously for this simple use case, it's easy to imagine Sass doing this for you. However, In a complex project, the permutations will expand exponentially. This happens with certain uses of `@extend` and it's why people tend to avoid it.

In such cases, browser which know the current document structure can resolve these value much more efficiently instead of precomputing all possible selectors like Sass would need to do.

This is, in fact, exactly what CSS Variables do and you can use them _right now_ in firefox and soon in chrome. http://caniuse.com/#feat=css-variables
