### ISSUE TITLE
`@keyframe` bugs when inside of a placeholder/silent selector

### ISSUE THREAD

**Issue by tjbenton** [sass/sass#1779]
There're 2 bugs I found when `@keyframe`s are nested inside of a placeholder selector.
1. They will always be compiled, even if you don't extend onto the placeholder selector. 
2. When you do extend onto the placeholder selector, it returns an error saying the following.
   
   ```
   ".u-animation--pulse" failed to @extend "%keyframes--pulse".
   The selector "%keyframes--pulse" was not found.
   ```
   
    I know this error happens because there isn't a property defined outside the `@keyframe`. But it shouldn't error because there aren't properties defined out in the `@keyframe`.

Here's a [live example](http://sassmeister.com/gist/bcfd5f396754e5eb6066)

This improvement would be invaluable to keep file size down, by not adding every single keyframe animation from libraries like [animate.css](https://daneden.github.io/animate.css/), and only add them when they're actually used.

**Comment by cimmanon** [comment]
Keyframes are supposed to bubble (see: https://github.com/sass/sass/issues/870).

Your extend is failing because a) you're referencing the wrong selector and b) even if you were referencing the correct selector, it is empty (because the "contents" have bubbled out like they're supposed to).  What's actually happening is a lot more clear once you use regular classes instead of the placeholder selector:

``` scss
.keyframes{
  color: red;

  &--pulse{
    color: blue;

    @keyframes pulse{
      0%{
        left: 0;
      }
      100%{
        left: 100%;
      }
    }
  }
}

.u-animation--pulse{
  @extend .keyframes--pulse;
}
```

Output:

``` css
.keyframes {
  color: red;
}
.keyframes--pulse, .u-animation--pulse {
  color: blue;
}
@keyframes pulse {
  0% {
    left: 0;
  }
  100% {
    left: 100%;
  }
}
```
