### ISSUE TITLE
darken() can't be used with @each elements

### ISSUE THREAD

**Issue by bcoughlan** [sass/sass#178]
I suspect the issue is a type conversion one but won't hazard a guess.

The following snippet does not work:

``` css
@each $color in #59a80f, #9ede3f, #e2ff9e, #f2fed6,
                #ad8109, #f4be29, #fae3a2, #fdf3d8,
                #0991ad, #29d1f4, #a2ebfa, #d8f7fd,
                #ac0b0b, #f32a2a, #faa3a3, #fdd8d8 {
    .levelxx {
        background-color: #{$color};
        border: darken(#{$color}, 20%);
    }
}
```

The error given is "Syntax error: "#59a80f" is not a color for `darken`". However, `border:  darken(#59a80f, 20%);` parses as expected.

**Comment by nex3** [comment]
This is happening because you're using `#{}`. This causes `$color` to be converted to a string, which `darken()` doesn't understand. You just want to be doing

``` SCSS
@each $color in #59a80f, #9ede3f, #e2ff9e, #f2fed6,
                #ad8109, #f4be29, #fae3a2, #fdf3d8,
                #0991ad, #29d1f4, #a2ebfa, #d8f7fd,
                #ac0b0b, #f32a2a, #faa3a3, #fdd8d8 {
    .levelxx {
        background-color: $color;
        border: darken($color, 20%);
    }
}
```
