### ISSUE TITLE
Lazy evaluation of arguments in functions and mixins.

### ISSUE THREAD

**Issue by whaaaley** [sass/sass#1781]
In SCSS function and mixin arguments are evaluated before being used (most of the time). I understand why it works this way, but should it? I don't think arguments should be evaluated until the logic requires them to be. There's a few reasons why I think this should be changed:
- Errors will be thrown even if an if statement says the code is invalid (like shown below).
- While maybe not by much in my examples, but this could also improve compile times by not compiling unnecessary stuff in larger projects.
- This wouldn't break any existing code.

---

Here are some functions that don't really have anything to do with my specific problem, but they're referenced by my example.

``` scss
// Returns true if $list contains x or null, otherwise returns null
@function is-null($list) {
  @return if(index($list, x) or index($list, null), true, null);
}

// Returns null if $value is null, otherwise returns $result
@function pass-null($value, $result) {
  @return if(is-null($value), null, $result);
}
```

---

This function works because the `if` function by design (#798) doesn't evaluate arguments until they're needed, which is great! In this case `$value: null`, so the logic never reaches `round($value * 16) / 256` and no error is thrown.

``` scss
@function safe-convert($value) {
  @return if(is-null($value), null, round($value * 16) / 256);
}
```

---

This function doesn't, because arguments are evaluated first before being passed. In this case `$value: null`, an error is thrown.

``` scss
@function safe-convert($value) {
  @return pass-null($value, round($value * 16) / 256);
}
```

---

So my reasoning for wanting to do things this way is that, In my global variables file sometimes I'd like to remove things like colors, borders, border-radius, box-shadow, etc entirely in all components by setting a global variable to `null`, but when using variables inside functions that do math, Sass throws an error because you can't multiply by `null`. It'd be great to have my functions already in place knowing what to do when a null value is passed so the property gets removed.

My other alternative would be that I'd have to set up if statements in all of my components when I want to turn on or off each one of these things to ensure the property doesn't get output. I have a lot of components and properties that I'd like to be toggle-able and putting an if statement on each one of them doesn't sound like the most desirable thing to read though again once I have it in place.

**Comment by cimmanon** [comment]
Lazy evaluation in programming languages isn't very common, and the only reason why it was changed specifically on the `if` function is because it is commonly treated as a ternary operator (and in other languages, the ternary operator allows you to short circuit the expression based on the truthiness of the first part of the expression).

You _can_ work around the lack of lazy evaluation by using the `call` function:

``` scss
@function pass-null($value, $function) {
  @return if($value == null, null, call($function, $value));
}

@function my-expression($v) {
  @return round(($v * 16) / 256);
}

@function safe-convert($value) {
  @return pass-null($value, 'my-expression');
}

.foo {
  null: safe_convert(null);
  value: safe_convert(2000);
}
```

Output:

``` css
.foo {
  value: 125;
}
```

**Comment by chriseppstein** [comment]
We actually discussed this at length when we created the `if()` function because I disliked that it had special behavior that wasn't accessible to authors. It's a very complex set of functionality, and usually only LISPs have support for it.

We'd have to introduce special syntax, closures, and an eval-like capability. Something like:

``` scss
@function pass-null($value, $$result) {
  @return if(is-null($value), null, evaluate($$result));
}
```

Where a "variable variable" is an expression and a context/closure that becomes a standard value only after evaluation.

I don't know if the above code is confusing. I also don't know if it should only be valid in a function call context. Should any expression can be captured into an unevaluted variable? Should it be possible to evaluate them against a different closure/binding? Should it be possible to construct the expressions from a string?

Anyways, yeah, I still lean towards not introducing this feature.

**Comment by whaaaley** [comment]
@cimmanon Thanks for that! That works great and it won't be too hard to add into my current stuff.

@chriseppstein I'm not experienced with using lazy evaluation, but while researching about it, it looked like the answer I needed and only seemed to solve problems. I was thinking this would be a new behavior that would extend the current behavior for all arguments without requiring new syntax, since, as far as I'm aware, it wouldn't hurt any existing user code. The only thing that would change is the point in time something gets evaluated, which would be from, "as soon as I can", to, "only when/until I have to". I have no idea about how much work it would be to implement it in this way. If a new syntax were required for this I think that would open up a whole new can of issues.

In general though, I'm fairly happy with the work around @cimmanon provided.

**Comment by chriseppstein** [comment]
> "as soon as I can", to, "only when/until I have to"

Ah I see. TBH, I don't know how to do that and so I don't understand the ramifications.

**Comment by whaaaley** [comment]
I suppose you could just follow the logic used in cimmanon's workaround. I'd imagine the general logic would be as follows, though, I'm not nearly as skilled as you guys in ruby or the backend of sass (obviously) so I'm probably skipping over some chunks, but...
1. The arguments in a function call would be stored in an expression, though in memory
2. The variables used in an argument would get added to the arguments in the expression
3. The variables would be passed to the function
4. Every time a variable would be used within the function it would call the expression passing the variables from the function into the call
5. Finally compile the result for each variable

~~But since this is functionality is all doable in Sass, I'm not sure it's worth it anymore. I think I'm satisfied with this answer, but automating this would be cool too :). So feel free to close this.~~ :+1:

...I changed my mind a little bit. After experimenting with the work-around it was pretty apparent to me that this would be a super nice thing to have. Also, I agree with your example; a new syntax for authors to decide when to evaluate would definitely be the easiest/best solution.

---

Here's a way better example than what I had above using your syntax:

``` scss
$font-size: null;

@function check-type($value, $$expression) {
  @if type-of($value) == string or type-of($value) == null {
    @return $value;
  }
  @else {
    @return evaluate($$expression);
  }
}

@function em($value) {
  @return check-type($value, ($value / 16) * 1em);
}

// Unitless
@function un($value) {
  @return check-type($value, $value / 16);
}
```

Input

``` scss
.block {
  font-size: em($font-size);
  line-height: un($font-size);
}
```

Output

``` scss
// $font-size: 24;
.block {
  font-size: 1.5em;
  line-height: 1;
}
```

``` scss
// $font-size: inherit;
.block {
  font-size: inherit;
  line-height: inherit;
}
```

``` scss
// $font-size: null;
// Nothing! Because it's null.
```

---

It could even make something like this valid, though maybe not practical:

``` scss
$border-radius-default: 8px;
$border-radius: null;

@function example($$value) {
  @if $border-radius == null {
    @return $border-radius-default;
  }
  @else {
    @return evaluate($$value);
  }
}
```

Input

``` scss
.block {
  border-radius: example($border-radius * 2); // Would normally error
}
```

Output

``` scss
.block {
  border-radius: 8px;
}
```
