### ISSUE TITLE
A case where slash is incorrectly interpreted as division

### ISSUE THREAD

**Issue by andrew-skybound** [sass/sass#1786]
Test Case (Sass 3.4.16):

``` sass
div {
    foo: (1 (1/2) 2px/3px 2px/3px);
    foo: ((1/2) 2px/3px 2px/3px);
}
```

Output CSS:

``` css
div {
  foo: 1 0.5 2px/3px 2px/3px;
  foo: 0.5 0.66667 2px/3px;
}
```

Notice that removing the `1` from the start of the list causes the `/` in the 3rd item to be computed as division instead of left as a delimiter.

Is this behavior expected?  The third value doesn't seem to meet any of the criteria for division as explained in the documentation, and even if I misread the documentation and it did meet the criteria, wouldn't the 4th item also be computed as division?
