### ISSUE TITLE
Nested extend produces wrong selector

### ISSUE THREAD

**Issue by PeterBaltruschat** [sass/sass#1789]
Issue tested with 3.4.13 and 3.4.16

SCSS

``` scss
%test { color:red; }

%test2
{
    > fieldset > table, > table
    {
        > tbody > tr > td, > tr > td
        {
            a, b, c, d { @extend %test; }
        }
    }
}

.class
{
    root { @extend %test2; }
}
```

Expected output:

``` css
.class root > fieldset > table > tbody > tr > td a, 
.class root > fieldset > table > tbody > tr > td b, 
.class root > fieldset > table > tbody > tr > td c, 
.class root > fieldset > table > tbody > tr > td d, 
.class root > fieldset > table > tr > td a, 
.class root > fieldset > table > tr > td b, 
.class root > fieldset > table > tr > td c, 
.class root > fieldset > table > tr > td d, 
.class root > table > tbody > tr > td a, 
.class root > table > tbody > tr > td b, 
.class root > table > tbody > tr > td c, 
.class root > table > tbody > tr > td d, 
.class root > table > tr > td a, 
.class root > table > tr > td b, 
.class root > table > tr > td c, 
.class root > table > tr > td d {
  color: red; }

/*# sourceMappingURL=test.css.map */
```

Actual output:

``` css
.class root > table > tr > td a, 
.class root > table > tr > td b, 
.class root > table > tr > td c, 
.class root > table > tr > td d {
  color: red; }

/*# sourceMappingURL=test.css.map */
```

If %test is inlined into %test2 like

```
...
            a, b, c, d { color:red; }
...
```

the expected output is achieved.

Likewise if the direct child selector ( > ) before fieldset and tbody is removed the expected output (sans direct child selector) is produced.

Also, if the root tag is removed like

```
...
.class { @extend %test2; }
...
```

the output is correct, too (except for the missing root tag, of course).
