### ISSUE TITLE
Referencing the top-most parent selector

### ISSUE THREAD

**Issue by jacksleight** [sass/sass#1804]
At the moment `&` gives you the parent selector. I would like to propose a similar shortcut that will return the top-most parent selector, which would be very useful when using BEM style syntax. For example, this:

``` sass
.block {
  &--modifier {
    ^__element {
      color: red;
    }
  }
}
```

Could give you:

``` sass
.block--modifier .block__element {
  color: red;
}
```

Obviously using `^` would not make your selector start at the root, like `&` does.

Doesn't have to be `^` of course, I'm just using that as an example.

**Comment by cimmanon** [comment]
Directly related to https://github.com/sass/sass/issues/1790

**Comment by chriseppstein** [comment]
This is supported right now and is much more clear about what's going on:

``` scss
.block {
  &--modifier &__element {
      color: red;
  }
}
```

**Comment by jacksleight** [comment]
Ah yeah, hadn't thought of that! :-)

An alternative would help avoid duplication though, as with that method you'd need to do this when you have multiple elements under the same modifier:

``` scss
.block {
  &--modifier &__element1 {
      color: red;
  }
  &--modifier &__element2 {
      color: red;
  }
  &--modifier &__element3 {
      color: red;
  }
}
```

I realise there are ways around that (such as the example below), but it feels a bit hacky, so I just thought a shortcut of some kind would make it cleaner and be a nice convenience.

``` scss
.block {
  $b: &;
  &--modifier {
    #{$b}__element1 {
      color: red;
    }
    #{$b}__element2 {
      color: red;
    }
    #{$b}__element3 {
      color: red;
    }
  }
}
```

**Comment by chriseppstein** [comment]
There's really too many possible selector operations for us to make special syntax for them. Instead, we made sure you can write functions that operate on your current selector. In this case, I would suggest that you write this code like so:

``` scss
@function current-block($selector: null) {
  $selector: & !default;
  $primary: nth(nth($selector, 1), 1);
  $delimiter: str-index($primary, "--") or str-index($primary, "__");
  @if ($delimiter) {
    $primary: str-slice($primary, 1, $delimiter - 1);
  }
  @return $primary;
}

.block {
  &--modifier {
    #{current-block()}__element1 {
      color: red;
    }
    #{current-block()}__element2 {
      color: red;
    }
    #{current-block()}__element3 {
      color: red;
    }
  }
}
```

Granted, this is more verbose, but it's also a lot easier for a casual reader who understands BEM to figure out what's going on.
