### ISSUE TITLE
No error reported when @extend fails and the extender contains certain combinators

### ISSUE THREAD

**Issue by andrew-skybound** [sass/sass#1816]
I believe this should be an error, since the `!optional` flag is not specified here and no rules are actually being extended.  The `a > b.foo` rule cannot be extended by `c > .bar` because `a` is not mergeable (wrong word?) with `c`.

It's worth noting that the same problem occurs—no error is reported—when the `+` combinator is used in place of the `>`.

Input SASS:

``` scss
a > b.foo {a: b}
c > .bar {@extend .foo}
```

Output CSS (should just be an error):

``` css
a > b.foo {
  a: b;
}
```
