### ISSUE TITLE
Nested selector with namespaced import use-case

### ISSUE THREAD

**Issue by glebm** [sass/sass#1817]
Hi,

This just came up on boostrap-sass tracker (https://github.com/twbs/bootstrap-sass/issues/958):

---

Bootstrap uses the `&` selector quite a bit, often trailing, like this:

``` sass
.jumbotron {
  .container &,
  .container-fluid & {
    ...
  }
}
```

Which should generate CSS like 

``` css
.container .jumbotron, .container-fluid .jumbotron { ... }
```

If you want to nest all bootstrap classes under a single namespace class, the generally-recommended solution is to do something like this:

``` sass
.my-wrapper {
  @import "bootstrap-sprockets";
  @import "bootstrap";
}
```

However, given the way the bootstrap-sass is currently compiled, that means you get CSS like

``` css
.container .my-wrapper .jumbotron, .container-fluid .my-wrapper .jumbotron { ... }
```

which ends up not selecting anything. 

---

Can anything be done about this? Is there a workaround short of giving up on such parent selectors, adding the option to check for them to sass-lint and educating everyone that they are incompatible with namespacing?

**Comment by chriseppstein** [comment]
Hi, when you need to ensure your selector context is injected at a particular point in the selector hierarchy then you have to use SassScript to modify the selector more intelligently.

source code: https://gist.github.com/chriseppstein/476836b0488e293b258e

The gist above defines a mixin called `grandparent` that injects a grandparent just above the current context:

``` scss
#context {
  .jumbotron {
    @include grandparent(".container, .container-fluid") {
      color: red;
    }
  }
}

.jumbotron {
  @include grandparent(".container, .container-fluid") {
    color: red;
  }
}
```

This code will now output what you're looking for:

``` css
#context .container .jumbotron, #context .container-fluid .jumbotron {
  color: red; }

.container .jumbotron, .container-fluid .jumbotron {
  color: red; }
```

Or you could just not use `&` here.

**Comment by chriseppstein** [comment]
re-opening for consideration of import v2. I actually think there's an expectation that import context does not work the same as selector nesting and I'd like to think about changing this. @nex3 what do you think about making the selector context outside the import not be a standard nesting for imported selectors. This would also allow those imported selectors to still define top-level constructs like mixins, etc.

**Comment by nex3** [comment]
My current thinking on the new import is that it will work less like a generic statement than the current one does—in particular, it won't be nestable. This goes hand-in-hand with it working more declaratively—"make these definitions visible" rather than "include the contents of this file". Then there would be a way to wrap the selectors in the context as a mixin. For example:

``` scss
@use "bootstrap" as mixin boostrap;

#context {
  @include bootstrap();
}
```

Given that model, I'm not sure it really makes sense to say that these mixins are "special" in the same sense that you were proposing for nested imports.

If we had something like #1582, we could implement this in user-space:

``` scss
@mixin block-parent() {
  $content-at-root: null;
  @at-root {$content-at-root: content()}
  @include content($content-at-root);
}
```
