### ISSUE TITLE
percentage function - 0%

### ISSUE THREAD

**Issue by efender** [sass/sass#1825]
Are there any cases to return zero with "%"-symbol?

``` scss
percentage(0) > 0%
```

**Comment by glebm** [comment]
Consider:

``` console
> 0% + 50
50%
```

vs

``` console
> 0 + 50
50
```

Although good Sass code should always specify the units (`50%`), changing this would break backwards compatibility.

Removing these is handled by all CSS minifiers by the way.

**Comment by efender** [comment]
> Removing these is handled by all CSS minifiers by the way.  

Yes, I know, but not all people use these useful things )

> 0% + 50
> 50%

Is it no more logical?

``` scss
.el { width: percentage( expr(return 0) + 50 ); } => .el { width: 50%; }
```

but now:

``` scss
.el { width: percentage( expr(return 0) ); } => .el { width: 0%; }
```

**Comment by cimmanon** [comment]
Given how many people use FrameworkFlavorOfTheMonth, it is impractical to expect everyone to have control over the order of operations.

**Comment by davidkpiano** [comment]
Here's a practical use-case (albeit a little contrived):

``` scss
@keyframes foo {
  @for $i from 0 through 10 {
    #{percentage($i / 10)} {
      transform: translateX($i * 1rem);
    }
  }
}
```

If `percentage(0/10)` (or `percentage(0)`) evaluated to `0`, you'll get this error: **Invalid CSS after "": expected keyframes selector (e.g. 10%), was "0"**. A non-percent value is not a valid keyframe selector.
