### ISSUE TITLE
Nested media queries using the "not" keyword should not be merged

### ISSUE THREAD

**Issue by jaydenseric** [sass/sass#1831]
*Edited by @nex3*

Specs: https://github.com/sass/sass-spec/pull/1267

- [x] https://github.com/sass/dart-sass/pull/410
- [ ] https://github.com/sass/libsass/issues/2694

---

Nested media queries using the `not` keyword should not be merged. According to [the spec](http://www.w3.org/TR/mediaqueries-4/#mq-not), `not` flips the result for the entire query and does not apply to specific chunks.

For example:

``` scss
@media (min-width: 500px) {
  @media not all and (min-width: 800px) {
    background: red;
  }
 }
```

Should compile to the same:

``` css
@media (min-width: 500px) {
  @media not all and (min-width: 800px) {
    background: red;
  }
 }
```

At 400px the background is expectedly not red.

Instead it compiles to:

``` css
@media not all and (min-width: 500px) and (min-width: 800px) {
  background: red;
}
```

At 400px the background is unexpectedly red.

**Comment by chriseppstein** [comment]
I had the thought "Since CSS allows nested media queries now, I wonder whether it's better to just remove the media merging feature from Sass." Then I discovered IE11 still doesn't support nested media queries. (IE9-11 is 8% of global users)

Noting that here in case someone else thinks it.

**Comment by jaydenseric** [comment]
Wow! Didn't know that about IE11 either.

**Comment by andrew-skybound** [comment]
Since browser support for nested `@media` queries is not ubiquitous, how about requiring the "not" keyword to appear on either _all_ media queries in a rule (if the parent has it) or on _none_ of them (if the parent does not).  That would make the intent explicit, and future-proof the style sheet for the day when manually nesting `@media` rules is no longer necessary.

Not nesting media queries _sometimes_ does not seem like a good idea.  At the very least it will lead to unexpected failures on IE.

So the example above would be an error.  This would be required:

``` CSS
@media not all and (min-width: 500px) {
  @media not all and (min-width: 800px) {
    background: red;
  }
}
```
