### ISSUE TITLE
Polymer mixin syntax is incompatible with Sass

### ISSUE THREAD

**Issue by voondo** [sass/sass#1832]
From https://github.com/Polymer/polymer/issues/1373: 

Running the following through the Sass compiler:

```
:host {
  --my-toolbar-theme: {
    background-color: green;
    border-radius: 4px;
    border: 1px solid gray;
  }
}
```

Results in:

```
:host {
  --my-toolbar-theme-background-color: green;
  --my-toolbar-theme-border-radius: 4px;
  --my-toolbar-theme-border: 1px solid gray;
}
```

Which is obviously unwanted.

Reference: https://www.polymer-project.org/1.0/docs/devguide/styling.html#custom-css-mixins

**Comment by mprins** [comment]
--my-toolbar-theme is not a valid selector, so it's not handled as such, you need to escape it in scss to get what you want:

``` scss
--my-toolbar-theme: #{'{
    background-color: green;
    border-radius: 4px;
    border: 1px solid gray;
}'};
```

see also
-  #1128
- http://www.w3.org/TR/css3-selectors/#w3cselgrammar
