### ISSUE TITLE
Sass allows illegal selectors

### ISSUE THREAD

**Issue by kareems** [sass/sass#1836]
Example here: http://sassmeister.com/gist/81d7b9fee673e3db77e6

This compiles properly to `.my-element ~ .some-sibling {…}`:

``` scss
.my-element {
  ~ .some-sibling {
    background: green;
  }
}
```

But if it looks like this:

``` scss
.my-element {
  ~ & {
    background: green;
  }
}
```

it'll compile to `~ .my-element {…}`, which doesn't mean anything.

This is reproducible in 3.4.14.

**Comment by davidkpiano** [comment]
What do you intend for `.my-element { ~ & { ... } }` to produce? This is the correct behavior, as far as I know.

For example:

``` scss
.foo {
  .parent & {
    // ...
  }
}
```

will produce `.parent .foo` as a selector, which is expected. No different than what you're trying to do.

**Comment by kareems** [comment]
Ideally I'd like it to produce the selector `.my element ~ .my-element`. That would match the behavior in my first example, which already works. It's just that it stops working if you replace `.some-sibling` with `&`.

I'm not sure if there are subtleties here that make this unwise though.

**Comment by davidkpiano** [comment]
Oh, just do this:

``` scss
.my-element {
  & ~ & {
    // sibling styles, woot!
  }
}
```

**Comment by kareems** [comment]
Yeah, I was just trying to save typing the extra character :smiley:

**Comment by cimmanon** [comment]
No, if anything, the appropriate behavior would be for Sass to raise an error.  However, I don't believe the maintainers would like to do that, just in case selectors with a leading tilde actually becomes valid in the future.

When you write this:

``` scss
.my-element {
  ~ .some-sibling {
    background: green;
  }
}
```

What you're actually writing is this:

``` scss
.my-element {
  & ~ .some-sibling {
    background: green;
  }
}
```

By using the parent selector, you're telling Sass to disregard the default behavior.  If you want to generate `.some-sibling ~ .my-element`, you need to write it like this:

``` scss
.my-element {
  .some-sibling ~ & {
    background: green;
  }
}
```

**Comment by kareems** [comment]
Thanks, makes sense.

**Comment by chriseppstein** [comment]
>  just in case selectors with a leading tilde actually becomes valid in the future.

In the beginning Sass didn't even parse selectors, we just grabbed a string of stuff until the curly brace and said "this is a selector". As sass matured, our parsing of selectors has grown to support the features we've added (E.g. `@extend`) but our errors tend to be very simple like "you can't have a . without a classname that follows it" and these are mostly generated by our parser just being confused based on the selector grammar. Sass's selector grammar allows leading combinators because nested selectors allows leading combinators. This is to say, that we aren't raising an error here because we just don't raise selector errors unless Sass is confused. Sass generally doesn't raise errors because we think a browser will be confused. Usually Sass gets confused on behalf of browsers because we're all on the same CSS team but not always.

All that said, @kareems there is an easy way to get the behavior you seek:

``` scss
.my-element {
  ~ #{&} {
    background: green;
  }
}
```

Sass does not remove the parent selector when the parent reference (`&`) is used in SassScript contexts. usually this is just a pain in the ass requiring the use of `@at-root` but in this case it's helpful.

So. The larger issue here is "Should Sass raise errors for clearly invalid selectors?" For example, Sass will happily pass `~ ~ ~ .foo { ... }` along to a browser. I don't know why we don't raise an error for combinators that aren't combinating other than "we just never wrote that code". Since @nex3 wrote most, if not all, of the selector code I'd like her to weigh in.
