### ISSUE TITLE
Function to round a value to a precision rather than an integer?

### ISSUE THREAD

**Issue by blixt** [sass/sass#1847]
I propose a rounding function that is better at handling decimal numbers. Basically, something that mirrors JavaScript's `Number.prototype.toPrecision` function:

``` javascript
var a = 0.16, b = 1.6;
a.toPrecision(1) // gives 0.2
b.toPrecision(1) // gives 2
```

Just using `round` in the two above cases would give `0` and `2` instead.

**Comment by cimmanon** [comment]
You can already do this yourself.  Don't know that this needs to be part of the standard library.

``` scss
@function to-precision($val, $places) {
    $x: pow(10, $places);
    @return round($val * $x) / $x;
}

.foo {
  bar: to-precision(10.55555, 2);
}
```

Note that this requires a function for determining the power of something.  Compass provides one and so do a few other libraries.
