### ISSUE TITLE
Inconsistent null result when using type-of?

### ISSUE THREAD

**Issue by whaaaley** [sass/sass#1848]
``` scss
@debug type-of(null); // outputs: null
@debug null == null; // outputs: true
@debug type-of(blue) == color; // outputs: true
@debug type-of(null) == null; // outputs: null
```

Considering the first three results, why is the fourth not also true?

The reason this came to be an issue is because I'm looping through a list of `type-of` results (color, number, string, null) and I'm using a variable with one of those results within `type-of()`. I'd like null to be an option I can pass to this. I can work around this, but having to do so seems inconsistent.

``` scss
// work around fix:
@function foo-type-of($value) {
  @if $value == null {
    @return null;
  }
  @return type-of($value);
}

@function contains-one-of-type($list, $type-list) {
  @each $item in $list {
    @each $type-item in $type-list {
      // @if foo-type-of($item) == $type-item {
      @if type-of($item) == $type-item {
        @return true;
      }
    }
  }
  @return null;
}

$list: null blue 'string' 1 null;
@debug contains-one-of-type($list, number color); // outputs: true;

$list: null blue 'string' 1 null;
@debug contains-one-of-type($list, null); // outputs: null;
```

**Comment by davidkpiano** [comment]
Since `null` is a keyword in Sass, it has to be a string when comparing it to the `type-of()` a value (which also returns a string).

``` scss
test {
  not-string: type-of(null) == null; // false
  string: type-of(null) == 'null'; // true
}
```

**Comment by whaaaley** [comment]
Ah. I see the reasoning now, but I'm not sure I like it. `type-of(null)` should no doubt return `null` and not a string `'null'` in my mind because `null` would lack a type at all because... it's null. I don't imagine this has any chance of being changed though because the problem is solved if I just add quotes.

**Comment by davidkpiano** [comment]
Even JavaScript defines `typeof null` to be an `"object"` ;-)

**Comment by whaaaley** [comment]
It just feels wrong in Sass when functions return null as a string and can only be compared to with a quoted null. I don't quote null any where else when I'm checking for it so it seems odd that it's required in this case, but I get why.

I also don't have to quote any other results of `type-of`.

``` scss
@debug type-of(blue) == color; // true
```

**Comment by cimmanon** [comment]
This is no different than how Sass handles color keywords (eg. `red != #{red}`).  If you want an explicit string, you have to quote it.  Otherwise, Sass will infer the type for you.

```
$null: null;

.foo {
  one: type-of(null);
  two: type-of(type-of(null));
  three: type-of(#{null});
  four: $null;
  five: null;
  six: type-of(null) == null;
}
```

Output:

``` css
.foo {
  one: null;
  two: string;
  three: string;
  five: null;
  six: false;
}
```

The string `null` is not the same as the null type.
