### ISSUE TITLE
Nested share code

### ISSUE THREAD

**Issue by basvandenheuvel** [sass/sass#1851]
Hi, I would like to share code with multiple nested classes, how to achieve this?

Lets say this is my current css:

``` css
.top-nav > li > a:hover,
.top-nav > li > a:focus,
.top-nav > .open > a,
.top-nav > .open > a:hover,
.top-nav > .open > a:focus {
    color: #fff;
    background-color: #000;
}
```

Using sass you can nest stuff, so i don't need 5 times `.top-nav`:

``` sass
.top-nav {
    > li > a:hover,
    > li > a:focus,
    > .open > a,
    > .open > a:hover,
    > .open > a:focus {
        color: #fff;
        background-color: #000;
    }
}
```

This is better, but i still have 2 times `li` and 3 times `.open`. 
So the question is: How to improve this code (using nesting?)?

UPDATE:

I thought something like this would be possible:

``` sass
.top-nav {
    > li { a:hover, a:focus},
    > .open { a, a:hover, a:focus } {
        color: #fff;
        background-color: #000;
    }
}
```

Ofcourse this silly code doesn't work. (and ideally you would also like to nest the `a` stuff)

**Comment by davidkpiano** [comment]
At this point, you'd probably want to make the declaration block a mixin:

``` scss
@mixin dark-bg() {
  color: #fff;
  background-color: #000;
}

.top-nav {
  > li, > .open {
    a:hover, a:focus { @include dark-bg; }
  }

  > .open a { @include dark-bg; }
}
```

(Sidenote: is it expected (when `@extend`ing or otherwise) to allow impossible selectors to be unified such as `li:not(li)`?)

**Comment by basvandenheuvel** [comment]
@davidkpiano Thanks for the answer. I gues that looks like the best "sass" way of doing it. I guess i just keep my code in this case since i think thats more readable.

**Comment by chriseppstein** [comment]
You can use the `selector-nest()` function to accomplish this:

``` scss
#{selector-nest(".top-nav > li", "a:hover, a:focus")},
#{selector-nest(".top-nav > .open", "a, a:hover, a:focus")} {
  color: #fff;
  background-color: #000;
}
```
