### ISSUE TITLE
Request implementation of an @clone or @copy command

### ISSUE THREAD

**Issue by elistone** [sass/sass#1852]
Due to older browsers not being able to process some newer selectors, this can  cause a whole line to be ignored.

**SASS**

``` sass
.nav-bar {
 height: 100px;
 background-color: black;
 li {
    &:last-child,
    &.end-col {
      color: red;
      background-color: green;
    }
  }
}
```

**Resulting CSS**

``` CSS
.nav-bar {
  height: 100px;
  background-color: black;
}

.nav-bar li:last-child, .nav-bar li.end-col { /* Ignored in IE8 due to :last-child selector */
  color: red;
  background-color: green;
}
```

Using the `@extend` command does not fix this as it outputs same resulting CSS.
Creating a mixin is a kind of fix: 

**SASS**

``` sass

@mixin last-child() {
  color: red;
  background-color: green;
}

.nav-bar {
 height: 100px;
 background-color: black;
 li {
    &:last-child {
      @include last-child();
    }
    &.end-col {
      @include last-child();
    }
  }
}
```

**Resulting CSS**

``` CSS
.nav-bar {
  height: 100px;
  background-color: black;
}

.nav-bar li:last-child{
  color: red;
  background-color: green;
}

.nav-bar li.end-col {
  color: red;
  background-color: green;
}
```

A possible fix would be the creation of a `@clone` or `@copy` command which would work as follows:

**SASS**

``` sass

.nav-bar {
 height: 100px;
 background-color: black;
 li {
    &.end-col {
       color: red;
       background-color: green;
    }
    &:last-child {
      @copy .end-col;
    }
  }
}
```

**Resulting CSS**

``` CSS
.nav-bar {
  height: 100px;
  background-color: black;
}

.nav-bar li:last-child{
  color: red;
  background-color: green;
}

.nav-bar li.end-col {
  color: red;
  background-color: green;
}
```
