### ISSUE TITLE
Generate Variable with interpolation , sass need a new boost

### ISSUE THREAD

**Issue by mhdcodes** [sass/sass#1855]
it would be awesome if we can generate variables with interpolation 
for ex 
@for $i from 6 through 1 {
    $h#{$i}-font-size : $i;
    $h#{$i}-font-size-reduction: $i \* 0.5;
  }

@for $i from 1 through 6 {
    h#{$i}{
      font-size: $h#{$i}-font-size - $h#{$i}-font-size-reduction;
    }
  }

**Comment by davidkpiano** [comment]
Try using a list or map instead; that's what they're for.

``` scss
$headings: ();

@for $i from 6 through 1 {
  $headings: map-merge($headings, (
    #{$i}-font-size: $i,
    #{$i}-font-size-reduction: $i * 0.5
  )) !global;
}

test {
  font-size: map-get($headings, '3-font-size');
  // => font-size: 3;
}
```
