### ISSUE TITLE
Allow trailing ampersand for parent selector

### ISSUE THREAD

**Issue by adamreisnz** [sass/sass#1856]
In LESS, it is possible to write:

``` less
.foo {
  color: red;
  a& {
    color: blue;
  }
}
```

To do the same in SASS, we need:

``` sass
.foo {
  color: red;
  @at-root a#{&} {
    color: blue; 
  }
}
```

This strikes me as overly complicated and ugly. Could support for trailing ampersand parent selectors be added so that we don't have to resort to using @at-root and interpolation? E.g. just as `&.foo` or `&__bar` are valid, why can't `a&` work?
