### ISSUE TITLE
Proposal of defining the same value for several properties

### ISSUE THREAD

**Issue by long-lazuli** [sass/sass#1859]
Like we can do for selectors in CSS :

``` SCSS
input, button { ... }
```

It would be excellent to be able to select many properties :

``` SCSS
.absolute {
  margin: auto;
  top, right, bottom, left: 0;
}
```
