### ISSUE TITLE
@extend behaves inconsistently when extender and extended classes are nested

### ISSUE THREAD

**Issue by anEffingChamp** [sass/sass#1862]
Take the following code for example.

``` scss
%placeHolder { width: 50% }
.block {
  &Element1 {
    @extend %placeHolder;
    height: 20px
  }
  &Element2 { @extend .blockElement1 }
}
```

When I compile this code .blockElement2 extends the width declaration in %placeHolder, but without inheriting the subsequent declaration in .blockElement1 without throwing an error. However if I modify the code as such:

``` scss
%placeHolder { width: 50% }
.blockElement1 {
  @extend %placeHolder;
  height: 20px
}
.block {
  &Element2 { @extend .blockElement1 }
}
```

In this case .blockElement2 inherits styles from .blockElement1 as expected.
