### ISSUE TITLE
Variable scope in @for loops

### ISSUE THREAD

**Issue by Sphinxxxx** [sass/sass#1863]
There appears to be an inconsistency regarding what scope a `@for` loop operates under. It's all explained with an example here: http://stackoverflow.com/questions/33157052/variable-scope-in-sass-for-loops

Baslically, the body of the loop operates in the parent scope (which one would expect), but the loop counter variable is in some other private scope. Is this expected behavior? I can't find anything about it in the documentation.

**Comment by chriseppstein** [comment]
Control structures in Sass use a semi-global scope. Semi-global scoping, when the parent is the global scope, allows you to set existing globals without using `!global` but any new variables created inside the control structure are created as locals.

The counter is reset in the local scope because each iteration sets the local var to the next value but the other local vars are preserved across iterations.

Here's a Sass snippet that demonstrates how the scoping works:

``` scss
// global variable
$g: 2px;
@for $i from 1 to 10 {
  $index-was: $i;
  $i: $i * 2; // you can change it, but it will keep being reset
  // initializes the local variable
  $l: false !default;
  // alternates between true and false because the local env is preserved across each iteration.
  $l: if($l, false, true);
  // this is changing the global because the loop's parent environment is the global scope.
  // This is the *only* thing that is special about how scopes work in control structures.
  $g: $g + 2px; 
  .iteration-#{$index-was} {
    global: $g;
    mutated-index: $i;
    local: inspect($l); 
  }
}
.after-iteration {
  outside-global-still-defined: variable-exists(g);
  outside-global: $g;
  outside-counter-still-defined: variable-exists(i);
  loop-local-still-defined: variable-exists(l);
}
```

Which generates:

``` css
.iteration-1 {
  global: 4px;
  mutated-index: 2;
  local: true; }

.iteration-2 {
  global: 6px;
  mutated-index: 4;
  local: false; }

.iteration-3 {
  global: 8px;
  mutated-index: 6;
  local: true; }

.iteration-4 {
  global: 10px;
  mutated-index: 8;
  local: false; }

.iteration-5 {
  global: 12px;
  mutated-index: 10;
  local: true; }

.iteration-6 {
  global: 14px;
  mutated-index: 12;
  local: false; }

.iteration-7 {
  global: 16px;
  mutated-index: 14;
  local: true; }

.iteration-8 {
  global: 18px;
  mutated-index: 16;
  local: false; }

.iteration-9 {
  global: 20px;
  mutated-index: 18;
  local: true; }

.after-iteration {
  outside-global-still-defined: true;
  outside-global: 20px;
  outside-counter-still-defined: false;
  loop-local-still-defined: false; }
```
