### ISSUE TITLE
Base-level rules cannot contain the parent-selector-referencing character '&'.

### ISSUE THREAD

**Issue by FWSimon** [sass/sass#1873]
Hey guys,

after updating sass i got this error
`Error: Base-level rules cannot contain the parent-selector-referencing character '&'.`

The line it tells me is for this code

```
&:focus {
  outline: none;
}
```

What can it be? it worked before i updated sass

**Comment by chriseppstein** [comment]
This error has existed since 3.0 which was released in May 2010.

It's nonsensical to refer to a parent selector at the base-level of a stylesheet. Inferring that `&` should be the universal selector at the root level is not at all a safe assumption. Additionally, this is often indicative of a coding mistake. So we consider it an error.

If this was part of a mixin that is sometimes included at the base level and sometimes nested, you can write the mixin like this:

``` scss
@mixin break-accessibility {
  #{if(&, "&", "*")}:focus {
    outline: none;
  }
}
@include break-accessibility;
.foo {@include break-accessibility;}
```
