### ISSUE TITLE
@extend in @at-root adds unwanted namespace

### ISSUE THREAD

**Issue by bpaugam** [sass/sass#1877]
Hello !

I encounter a problem: why is this

``` scss
#myApp {
  %raised {
    box-shadow: 1px 1px 5px grey;
  }

  @at-root {
    .button {
      background: green;
      @extend %raised;
    }
  }
}
```

Transpiled into this:

``` scss
#myApp .button {
  box-shadow: 1px 1px 5px grey;
}

.button {
  background: green;
}
```

I mean, why does Sass add the #myApp selector when extending ? Or rather, is there any way I can get this result: 

``` scss
.button {
  background: green;
  box-shadow: 1px 1px 5px grey;
}
```

Thanks alot!

**Comment by davidkpiano** [comment]
The selector you're extending is actually `#myApp %raised`, which is to say, it has the constraint "These raised styles apply when I have an ancestor `#myApp`.

The selector `#myApp .button` fulfills that constraint, because it has the `#myApp` ancestor.

Move `%raised` outside of the `#myApp` body to get your expected result. =)

**Comment by bpaugam** [comment]
Thanks for the reply David,

But the eventual goal is to do something like this:

``` scss
#app1 {
  $modal-namespace: 'app-1';

  .raised {
    box-shadow: 1px 1px 5px grey;
  }

  @at-root {
    .modal.#{$modal-namespace} {
      @extend .raised;
    }
  }
}

#app2 {
    $modal-namespace: 'app-2';

  .raised {
    box-shadow: 1px 1px 5px red
  }

    @at-root {
    .modal.#{$modal-namespace} {
      @extend .raised;
    }
  }
}
```

In order to get this result (namespacing of two projects: the first one should not bleed on the second one):

``` scss
#app1 .raised,
.modal.app-1 {
  box-shadow: 1px 1px 5px grey;
}
#app2 .raised,
.modal.app-2 {
    box-shadow: 1px 1px 5px red
}
```

Instead, I get  this:

``` scss
#app1 .raised,
#app1 .modal.app-1, #app1 #app2 .modal.app-2,
#app2 #app1 .modal.app-2, .modal.app-1 {
  box-shadow: 1px 1px 5px grey;
}

#app2 .raised,
#app2 #app1 .modal.app-1,
#app1 #app2 .modal.app-1, #app2 .modal.app-2, .modal.app-2 {
  box-shadow: 1px 1px 5px red;
}
```

I don't think your solution can be applied here ? But I might be mistaken ? Or maybe I am biased (coming from .less where this approach works) and my approach is wrong ?

**Comment by davidkpiano** [comment]
You're still extending both "namespaced" versions of `.raised`, which is why you're getting the selector explosion. If you want a specific `.raised`, try this approach:

``` scss
#app2 {
  $modal-namespace: 'app-2';

  @at-root {
    %raised-#{$modal-namespace} {
      box-shadow: 1px 1px 5px red;
    }
  }

  .raised {
    @extend %raised-#{$modal-namespace};
  }

  @at-root {
    .modal.#{$modal-namespace} {
      @extend %raised-#{$modal-namespace};
    }
  }
}
```

Works in Ruby Sass.
