### ISSUE TITLE
Clarification on documentation

### ISSUE THREAD

**Issue by ghost** [sass/sass#1881]
Following http://sass-lang.com/documentation/file.SASS_REFERENCE.html#division-and-slash:

I assume this is working as intended, but it would be helpful if the issues that occur from utilizing a percentile based operand, mixin, or variable when using a division operator where a little more fleshed out. Currently there is only this mention

---

If you want to use variables along with a plain CSS /, you can use #{} to insert them. For example:

```
p {
  $font-size: 12px;
  $line-height: 30px;
  font: #{$font-size}/#{$line-height};
}
```

is compiled to:

```
p {
  font: 12px/30px; 
}
```

---

This was the implementation that gave the desired output. I'm not saying anything is wrong. I am only stating that it would be nice if the documentation addressed this a little more.

Before compiling

```
 @for $i from 1 through 20 {
   &:first-child:nth-last-child( #{$i} ),
   &:first-child:nth-last-child( #{$i} ) ~ & {
     width: unquote((100 / $i + "%"));
   }
 }
```

   }

After compiling 

```
 .ll_bottom-bar-item:first-child:nth-last-child(1),
 .ll_bottom-bar-item:first-child:nth-last-child(1) ~ .ll_bottom-bar-item {
   width: 100%; }
 .ll_bottom-bar-item:first-child:nth-last-child(2),
 .ll_bottom-bar-item:first-child:nth-last-child(2) ~ .ll_bottom-bar-item {
   width: 50%; }
  ...etc...
```

**Comment by cimmanon** [comment]
It seems like the problem you're having is due to adding the percentage unit (%) to your integer. The correct way to add a unit is via arithmetic (using the plus operator with a string is always concatenation, not addition, and always results a string).  Alternately, there is the `percentage()` function.

``` scss
.foo {
  @for $i from 1 through 20 {
   &:first-child:nth-last-child( #{$i} ),
   &:first-child:nth-last-child( #{$i} ) ~ & {
     // arithmetic
     width: 100% / $i;
     // percentage function
     width: percentage(1 / $i);
   }
 }
}
```
