### ISSUE TITLE
Rounding should respect precision

### ISSUE THREAD

**Issue by mgreter** [sass/sass#1883]
This catched my eye when I tried to re-implement the epsilon rounding by ruby sass. I hope I can illustrate what I mean by showing an example:

`# cat test.scss`

``` scss
$a: 0.499999;
div {
  a: $a;
  b: round($a);
}
```

`# sass test.scss --precision=5`

``` scss
div {
  a: 0.5;
  b: 1; }
```

`# sass test.scss --precision=6`

``` scss
div {
  a: 0.499999;
  b: 1; }
```

IMO it should not round up in the second case for `b`, since I explicitly requested a precision of 6 digits. Given the final output for `a`, this feels unintuitive if not even wrong, but not sure if this is intended?

As a side note, I also see something related in error messages and other places (AFAIR `@debug`).

``` scss
// # sass test.scss  --precision 6
$a: 'foo'; $b: 'foo';
$map: ($a: 1, c: 4.999999);
foo { bar: map-get($map, c); }
// => foo { bar: 4.999999; }

$map: ($a: 1, $b: 2, c: 4.999999);
// Duplicate key "foo" in map ($a: 1, $b: 2, c: 5.0).
```
