### ISSUE TITLE
Feature request: Declaration map "comprehension" for nested properties

### ISSUE THREAD

**Issue by davidkpiano** [sass/sass#1892]
Recalling nested properties, I had a thought regarding the use of maps in CSS. Currently, according to the docs:

> They have no direct parallel in CSS... Maps cannot be converted to plain CSS. 

That's fine, and expected. We know that maps can be used in Sass variables and functions, but not directly output to CSS as a usable value, unlike lists.

But given we can do this:

``` scss
animation: {
  name: flip;
  duration: 2s;
  iteration-count: infinite;
}

// produces
animation-name: flip;
animation-duration: 2s;
animation-iteration-count: infinite;
```

Consider this:

``` scss
$my-animation: (
  name: flip,
  duration: 2s,
  iteration-count: infinite
);

 // a map being assigned directly to a property
animation: $my-animation;

// produces the same result as above
```

Compare it to this (for dynamic values):

``` scss
$my-animation: (
  name: flip,
  duration: 2s,
  iteration-count: infinite
);

@mixin add-animation($animation-map) {
  @each $key, $value in $animation-map {
    animation-#{$key}: $value;
  }
}

@include add-animation($animation-map);
```

A little bit verbose, but currently the "right" way to do this.

Further, and even more powerful, Sass could "comprehend" a list of maps for valid properties, like so:

``` scss
$anim-1: (
  name: flip,
  duration: 2s,
  iteration-count: infinite
);

$anim-2: (
  name: rotate,
  duration: 1s
);

$animations: ($anim-1, $anim-2);

animation: $animations;

// produces...
animation-name: flip, rotate;
animation-duration: 2s, 1s;
animation-iteration-count: infinite, initial;
```

I know this can be accomplished with functions/mixins, but having Sass be able to comprehend maps and list of maps in valid properties would be a huge time-saver, and lower the number of required mixins and functions to make it work. What do you think?

**Comment by chriseppstein** [comment]
Mixins can be included inside a property expansion block.

This use case is not common enough to warrant dedicated syntax for what amounts to the `map-to-rules` mixin below. 

``` scss
@mixin map-to-rules($map) {
  @each $k, $v in $map {
    #{$k}: $v;
  }
}

$animation: (
  name: flip,
  duration: 2s,
  iteration-count: infinite
);

.foo {
  animation: {
    @include map-to-rules($animation);
  }
}
```

And yes, I get that I glossed over the merging of several maps into a single property value. I leave writing a function that merges maps into a new map of that form to the reader.
