### ISSUE TITLE
Strange behavior when inspecting single parent selector

### ISSUE THREAD

**Issue by mgreter** [sass/sass#1901]
From https://github.com/sass/libsass/issues/1583:

``` scss
foo {
  length: length(&);
  string: inspect(&);
  length: str-length(inspect(&));
}

foo, bar {
  length: length(nth(&, 1));
  string: inspect(nth(&, 1));
  length: str-length(inspect(nth(&, 1)));
}
```

Results in:

``` css
foo {
  length: 1;
  string: (foo,); /* expected: foo */
  length: 6; /* expected: 3 */
}
foo, bar {
  length: 1;
  string: foo;
  length: 3;
}
```

Is this intentional?

**Comment by cimmanon** [comment]
If I am reading the description of the inspect function correctly, it is supposed to return a string containing the exact thing you have to write in order to create that variable/value, similar to the `show` function in Haskell.  Using a trailing comma is how you would do that.

``` scss
$foo: (foo,);

foo {
  foo: $foo;
  string: inspect($foo);
  type: type-of($foo);
  type: type-of(nth($foo, 1));
}
```

Output:

``` css
foo {
  foo: foo;
  string: (foo,);
  type: list;
  type: string;
}
```

If we remove the trailing comma, we don't get the same results:

``` scss
$foo: foo;

foo {
  foo: $foo;
  string: inspect($foo);
  type: type-of($foo);
  type: type-of(nth($foo, 1));
}
```

Output:

``` css
foo {
  foo: foo;
  string: foo;
  type: string;
  type: string;
}
```

The only other way to create a list of strings with a single value in it is to use something like append(), but the inspect function doesn't return a result you can use to get the same value you passed in:

``` scss
$foo: append((), foo);

foo {
  foo: $foo;
  string: inspect($foo);
  type: type-of($foo);
  type: type-of(nth($foo, 1));
}
```

Output:

``` css
foo {
  foo: foo;
  string: foo;
  type: list;
  type: string;
}
```

If anything, I would say the bug is here with the last example, not with the examples you've provided.
