### ISSUE TITLE
Increase strictness about whitespace around minus sign

### ISSUE THREAD

**Issue by akaScooter** [sass/sass#1912]
* [x] [Proposal](https://github.com/sass/sass/blob/main/accepted/strict-unary.md)
* [x] [Migrator](https://github.com/sass/migrator/issues/225)
* [x] [Documentation](https://github.com/sass/sass-site/issues/644) (https://github.com/sass/sass-site/pull/670)

**Deprecation**
* [x] [Tests](https://github.com/sass/sass-spec/issues/1792) (https://github.com/sass/sass-spec/pull/1823)
* [x] [Dart Sass](https://github.com/sass/dart-sass/issues/1721) (https://github.com/sass/dart-sass/pull/1800)

**Removal**
* [x] Update deprecation (https://github.com/sass/sass/pull/4177)
* [x] [Tests](https://github.com/sass/sass-spec/issues/1792) (https://github.com/sass/sass-spec/pull/2102)
* [x] [Dart Sass](https://github.com/sass/dart-sass/issues/1721) (https://github.com/sass/dart-sass/pull/2718)
* [ ] Documentation

---

The following code:

```
$value : 12px;

.my-class {
    margin: 0 auto -$value;
}
```

results in the following CSS output:

```
.my-class {
    margin: 0 auto-12px; }
```

with no space between the `auto` and the `-12px` values. My browser (Firefox v42.0) doesn't recognize `auto-12px` as a valid value and ignores the rule.

Is this an issue where Sass's rules for compressing the output aren't taking the combination of `auto` (or any keyword string value) with a numeric value into account?

(The following is an example of the work-around I am using in these instances, but there should really be a space left between those values)

```
$value : 12px;

.my-class {
    margin: 0 auto;
    margin-bottom: -$value;
}
```

[Sass 3.4.19 (Selective Steve)]

**Comment by HamptonMakes** [comment]
ooof! That's pretty not-fun to have to track down in production code.

Does that happen in compressed mode, or just standard, like you show in your example?

**Comment by cimmanon** [comment]
If you add parentheses, it doesn't do that:

``` scss
$value: 10px;

.my-class {
    margin: 0 auto (-$value);
}
```

Note that you should be doing this to prevent the expression from being evaluated as subtraction rather than negation.

# Without parentheses

``` scss
$value: 10px;

.my-class {
    margin: 0 -$value;
}
```

Output:

``` css
.my-class {
  margin: -10px;
}
```

# With parentheses

```
$value: 10px;

.my-class {
    margin: 0 (-$value);
}
```

Output:

``` css
.my-class {
  margin: 0 -10px;
}
```

**Comment by davidkpiano** [comment]
@cimmanon Yes, but that's counter-intuitive - you shouldn't need to add parentheses.

These should all produce the same result:

``` scss
$value : 12px;
$neg-value: -$value;

.my-class {
  margin: 0 auto -$value;
  margin: 0 auto (-$value);
  margin: 0 auto $neg-value;
  margin: 0 auto -12px;
}
```
