### ISSUE TITLE
Using 2 variables in a String leads to wrong compilation

### ISSUE THREAD

**Issue by sergej2705** [sass/sass#1918]
I have following code:

```
...
background-image: url('data:image/svg+xml;utf8,<svg width="50" height="50" xmlns="http://www.w3.org/2000/svg"><g><circle r="31" cy="43" cx="42" stroke-linecap="null" stroke-linejoin="null" fill="#{$gray}"/><circle r="14" cy="17" cx="17" stroke-linecap="null" stroke-linejoin="null" fill="#{$gray-light}"/></g></svg>');
...
```

see full example on http://sassmeister.com/gist/3e9f961fd8eb4b3cc074

after compiling the SCSS I get

```
background-image: url("data:image/svg+xml;utf8,<svg width=\"50\" height=\"50\" xmlns=\"http://www.w3.org/2000/svg\"><g><circle r=\"31\" cy=\"43\" cx=\"42\" stroke-linecap=\"null\" stroke-linejoin=\"null\" fill=\"#333333'/><circle r=\"14\" cy=\"17\" cx=\"17\" stroke-linecap=\"null\" stroke-linejoin=\"null\" fill='#999999\"/></g></svg>");
```

so after the first variable `#{$gray}` the quotation mark isn't `\"` but `'` and before the second variable `#{$gray-light}` it's the same. The generated CSS is not valid because of this.

Is this a SASS compilation-error?

**Comment by cimmanon** [comment]
That looks like an issue with LibSass, you should file a bug report with that repo.

Output with the Ruby Sass compiler:

``` css
div.second {
  background-image: url('data:image/svg+xml;utf8,<svg width="50" height="50" xmlns="http://www.w3.org/2000/svg"><g><circle r="31" cy="43" cx="42" stroke-linecap="null" stroke-linejoin="null" fill="#333333"/><circle r="14" cy="17" cx="17" stroke-linecap="null" stroke-linejoin="null" fill="#999999"/></g></svg>');
}
```

Also relevant: https://github.com/sass/sass/issues/1642
