### ISSUE TITLE
Sourcemaps pointing to mixin calls instead of definitions

### ISSUE THREAD

**Issue by danielguillan** [sass/sass#1920]
Source maps become (almost) useless when used alongside mixins that dynamically generate or modify selecctors ([modernizr-mixin](https://www.github.com/danielguillan/modernizr-mixin), [bem-constructor](https://github.com/danielguillan/bem-constructor)) because they point to the mixin definition instead of where it's called.

Is there any way to map to the call instead of the definition?

``` scss
@mixin foo($selector) {
 .#{$selector} { // Mapping for the .bar selector points here
   @content;
 }
}

@include foo('bar') { // But I want it to point here
  color: red;
};
```
