### ISSUE TITLE
Extending with dynamically generated selectors containing the same name takes forever

### ISSUE THREAD

**Issue by cimmanon** [sass/sass#1923]
Came across this code yesterday and Sass will never finish compiling it (the user who had the problem claims that it sometimes made Sass crash):

``` scss
h1, h2, h3, h4, h5, h6 {
  font-size: 22px;
}

@for $i from 1 through 6 {
  @for $j from 1 through 6 {
    $s: 'h' + $i;
    $ss: 'h' + $j;
    @debug $s, $ss;

    #{$ss}.#{$s}-style {
      @extend #{$s};
    }
  }
}
```

On the surface, it doesn't look like an infinite loop, but it certainly behaves like one.  If you turn the inner loop down to 2, it compiles but it's not clear to users why there's an issue.  Here's the output:

``` css
h1,
h1.h1-style,
h2.h1-style,
h2,
h1.h2-style,
h2.h2-style,
h3,
h1.h3-style,
h2.h3-style,
h4,
h1.h4-style,
h2.h4-style,
h5,
h1.h5-style,
h2.h5-style,
h6,
h1.h6-style,
h2.h6-style {
  font-size: 22px;
}
```
