### ISSUE TITLE
Inconsitent output for numbers near zero in compressed mode

### ISSUE THREAD

**Issue by mgreter** [sass/sass#1931]
This is against latest ruby sass 3.4.20
`sass-spec/misc/negative_numbers`

``` css
a {
  near: (0.000001);
  plus: (+ 0.0000001);
  minus: (- 0.0000001);
  near: (0 - 0.0000001);
  near: (0.0000001 * -1);
}
```

Results in

``` css
a{near:.0;plus:0;minus:0.0;near:.0;near:.0}
```

It should output `.0` instead of `0.0` also for the unary negation operation in compressed mode.

**Comment by mgreter** [comment]
Another related issue:
`libsass-closed-issues/issue_550/operator`

``` css
$x: .03;
$y: 0.7;

#foo {
  color: saturate($x);
  color: saturate($y);
  filter: grayscale(.03);
  filter: grayscale(0.7);
}
```

Results in

``` css
#foo{color:saturate(.03);color:saturate(.7);filter:grayscale(0.03);filter:grayscale(0.7)}
```

**Comment by mgreter** [comment]
Also slightly related:
`libsass-closed-issues/issue_1098`
```css
div {
 color: #f00000\9\0\;
}
```

Results in
```css
div{color:#f00000\9\0\}
```

Unsure if it really should omit the semicolon here, since output in other modes is
```css
div {
  color: #f00000\9\0\;; }
```

**Comment by chriseppstein** [comment]
The output should be:

``` css
a{near:0;plus:0;minus:0;near:0;near:0}
```

While testing this, I discovered issue #1938.

I'm going to file a separate issue to track the numeric output differences of the filter functions -- it's not the same root cause.
