### ISSUE TITLE
Escaped semicolon gets removed in compressed mode

### ISSUE THREAD

**Issue by mgreter** [sass/sass#1932]
This is against latest ruby sass 3.4.20
Some regression in existing spec test
`libsass-closed-issues/issue_1098`

``` css
div {
 color: #f00000\9\0\;
}
```

Results in

``` css
div{color:#f00000\9\0\}
```

It should not omit the escaped semicolon here, since output in other modes is

``` css
div {
  color: #f00000\9\0\;; }
```

I guess the compression is not smart enough to see the escape sequence ...
