### ISSUE TITLE
Selectors starting with dashes get compressed

### ISSUE THREAD

**Issue by mgreter** [sass/sass#1933]
Not sure if this is to be considered a bug, since I don't see a use case for such selectors.
Nonetheless the compressed behavior has changed in a recent sass version:

This is against latest ruby sass 3.4.20
`extended-tests/069_test_attribute_unification`
I simplified the spec here for easier testability

``` css
a -b {
  c: d;
}
```

Results in

``` css
a-b{c:d}
```

All other modes result in

``` css
a -b{c:d}
```

Not sure why sass does that and it seems wrong to me.
Note: we can/do compress `+` since it is a combinator.
