### ISSUE TITLE
@extend placeholders with siblings

### ISSUE THREAD

**Issue by artch** [sass/sass#1934]
We'd like to use `@extend` and `%placeholder` mechanics to create semantic stylesheet which will look something like that:

``` scss
%btn {
  display: block;
}
.person-edit {
  @extend %btn;
}
.person-create {
  @extend %btn;
}
.person-delete {
  @extend %btn;
}
```

It works well until we start using sibling selectors:

``` scss
%btn {
  display: block;
}
%btn + %btn {
  margin-left: 10px;
}
```

This will produce the following CSS: 

``` css
.person-edit, .person-create, .person-delete {
  display: block;
}

.person-edit + .person-edit, .person-create + .person-edit, .person-delete + .person-edit, .person-edit + .person-create, .person-create + .person-create, .person-delete + .person-create, .person-edit + .person-delete, .person-create + .person-delete, .person-delete + .person-delete {
  margin-left: 10px;
}
```

Every extended placeholder class bloats into huge number of all possible combinations so that it will generate `button_count ^ 2` total selectors.

Are there any ways to optionally disable such combinations generation for placeholder extended classes?

**Comment by davidkpiano** [comment]
The `@extend` directive is working as expected here. You're basically saying "these three classes should be styled as if they were all `%btn`" and then saying "whenever any of those `%btn` classes are adjacent to another `%btn` class, give them a `margin-left: 10px`".

So the problem is that essentially, `.person-edit, .person-create, .person-delete` are all considered the same type of entity, with regard to `%btn`. There are a few ways you can refactor this, by limiting the number of selectors that are extending `%btn`.

Try having a single `.btn` class extend `%btn`, and then in your markup, have both classes: `<button class="btn person-edit">` for example. Or you can even do `[class^="person-"] { @extend %btn; }` if you don't want to add extra classes.

**Comment by chriseppstein** [comment]
What @davidkpiano said.

FWIW, once the CSS `:matches()` pseudo selector is well supported, Sass will be able to emit a much more elegant output selector here: `:matches(.person-edit, .person-create, .person-delete) + :matches(.person-edit, .person-create, .person-delete)`

**Comment by artch** [comment]
I do realize it is the expected behavior. I'm not saying it's a bug which have to be fixed. Instead, I'm asking is there any chance to get this behavior configurable, so that I would be able to create a regression on this mechanic, in case if I wish to take the risk.

**Comment by chriseppstein** [comment]
@artch Extend semantics are very well defined -- there's no reasonable way to configure them without meaningfully changing the definition of extend. The solution here is to not use extend for the places where you don't want this behavior.

**Comment by andreev-artem** [comment]
@chriseppstein let me describe the possible use case: you have to use some SCSS framework. You almost can't change it. In your project you want to use BEM and you want to build semantic naming scheme. I.e. you want to have:

```
.items-controls
    .item-control.item-control--disabled
    .item-control
```

On other page:

```
.project-controls
    .project-control.project-control--disabled
    .project-control
```

Today `item-control` and `project-control` are buttons, tomorrow some of them may be links, etc. There is no chance that `item-control` and `project-control` will be siblings.

Which solution is better here? How it's possible to implement that without `@extend` and to not get a lot of extra CSS?

**Comment by artch** [comment]
@chriseppstein By the way, `:matches` is now supported in every browser except IE. Any chance to enable it in this case, if IE is not vital for our project?

**Comment by davidkpiano** [comment]
@andreev-artem To do that, remove the rule that gives styling to adjacent buttons. That is a constraint that doesn't match your intended constraint.
- `%btn + %btn` says "**Any** button next to **any** button"
- `.project-control + .project-control` says "**Only** `.project-control` next to **only** `.project-control`

In this case, it's better (IMO) to have a placeholder selector describing the styling for your intended constraint outside of the context of `%btn`:

**SCSS:**

``` scss
%btn {
  // ... button styles
}

%btn-adjacent {
  // styling for a button adjacent to another button
}

.project-control, .item-control {
  @extend %btn;
}

.project-control + .project-control,
.item-control + .item-control {
  @extend %btn-adjacent;
}
```

Generates this **CSS**:

``` css
.project-control, .item-control {
  // button styles
}

.project-control + .project-control,
.item-control + .item-control {
  // adjacent button styles
}
```

@artch Sass will already output `:matches(...)` selectors correctly, so feel free to use it with `@extend`! :tada:

**Comment by andreev-artem** [comment]
@davidkpiano I can't remove/refactor that - it's contained in external framework. And I think that's quite general situation. Just not all want to fight with that and just use what framework has. And looks like SASS can't help here.

**Comment by artch** [comment]
@chriseppstein You wrote this:

> FWIW, once the CSS :matches() pseudo selector is well supported, Sass will be able to emit a much more elegant output selector here: :matches(.person-edit, .person-create, .person-delete) + :matches(.person-edit, .person-create, .person-delete)

The question is, when is this expected?

**Comment by artch** [comment]
@davidkpiano chriseppstein wrote this few comments above:

> FWIW, once the CSS :matches() pseudo selector is well supported, Sass will be able to emit a much more elegant output selector here: :matches(.person-edit, .person-create, .person-delete) + :matches(.person-edit, .person-create, .person-delete)

My question was about when is this expected.

**Comment by davidkpiano** [comment]
@artch You still have to be explicit about it.

``` scss
%heading {
  font-weight: bold;
}

// This will still (and always) produce selector explosion
section {
  h1, h2, h3 { @extend %heading; }
}

// This will not, because you explicitly use :matches()
section {
  :matches(h1, h2, h3) { @extend %heading; }
}
```

**Comment by artch** [comment]
@davidkpiano Yes, but is not supported by SASS yet. This SCSS:

``` scss
%btn + %btn {
  margin-left: 10px;
}
:matches(.person-edit) {
  @extend %btn;
}
:matches(.person-create) {
  @extend %btn;
}
```

Generates this CSS:

``` css
:matches(.person-edit) + :matches(.person-edit), :matches(.person-create) + :matches(.person-edit), :matches(.person-edit) + :matches(.person-create), :matches(.person-create) + :matches(.person-create) {
  margin-left: 10px;
}
```

Which is just an overkill, since it is identical to:

``` css
:matches(.person-edit, .person-create) + :matches(.person-edit, .person-create) {
  margin-left: 10px;
}
```

It would be great if SASS can handle `@extend` this way.
