### ISSUE TITLE
Strange numeric output differences with image filter functions

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#1939]
Initially filed by @mgreter on issue #1931:

From: `libsass-closed-issues/issue_550/operator`

``` css
$x: .03;
$y: 0.7;

#foo {
  color: saturate($x);
  color: saturate($y);
  filter: grayscale(.03);
  filter: grayscale(0.7);
}
```

Results in

``` css
#foo{color:saturate(.03);color:saturate(.7);filter:grayscale(0.03);filter:grayscale(0.7)}
```
