### ISSUE TITLE
Feature Request: Support For Multiple Content Blocks

### ISSUE THREAD

**Issue by Undistraction** [sass/sass#1943]
There are lots of situations where people are using mixins to render templated styles out with some configurable parameters, for example I use a [mixin](https://gist.github.com/Undistraction/fc89e19d364fa786d308)  to render floated lists which allows me to configure the direction of float, spacing, whether the spacing is added before or after the element, and the element or class to use for list items. In this situation, being able to pass in a content block is great and means I don't have to repeat the selector to add additional styles for the list item that haven't been provided by the mixin, for example `color` or `outline`.

However what if I want to style the last item slightly differently, or the first? I am left having to repeat the selector to target these elements. The same is true of many mixins, for example a mixin that generates buttons, which might handle `background-color` and `color` for each state, but might not handle `text-decoration`.  Again, the mixin might support a content block, but only for the button's default state. I have to write new selectors for `:hover` etc.

I think these issues could be solved by adding support for named content blocks, much as you can pass multiple lambdas to a method in Ruby. For example (I'm not suggesting this particular syntax, but include it to show what I mean):

```
@include floated-list(left, 20px, before) {
    border-left: 1px solid black;
} [first-child] {
    border-left: none;
} [last-child] {
    color: grey;
}
```

**Comment by whaaaley** [comment]
Maybe I'm not understanding your issue, but could you not use the parent selector for this? This is valid:

``` scss
@mixin floated-list($foo, $bar) {
  &:first-child {
    border-left: none;
  }

  &:last-child {
    color: grey;
  }
}

li {
  @include floated-list(foo, bar);
}
```

Edit: Wait, I get what you mean now. Something like this?

``` scss
@mixin floated-list($foo, $bar) {
  @content;

  .start, .both, &:first-child {
    background: red;
    @content start;
  }

  .end, .both, &:last-child {
    background: green;
    @content end;
  }
}

li {
  @include floated-list(foo, bar) {
    margin: 20px; // @content

    @content start {
      margin: 40px;
    }
  }
}
```

**Comment by Undistraction** [comment]
Yep. Something like that, though I'm not so much thinking about its use in terms of overriding (in your example you would render `background` twice in the `first-child` selector), more in the sense that a focused mixin can generate a series of selectors, not just a single selector. Allowing extra props to be passed into these slots would be really powerful. In my example, the `floated-list` mixin just deals with layout, but rather than having to redeclare selectors it already renders to add properties that have nothing to do with layout, why not expose them as slots? With the right syntax I think it would be perfectly readable.

**Comment by whaaaley** [comment]
I updated my previous example to use multiple selectors, like you said. I'm starting to see the benefit. It's a neat idea, but what about using placeholders sort of backwards instead? It's not as pretty, but it's close.

``` scss

@mixin foobar {
  @content;

  &.start {
    background: red;
    @extend %start !optional;
  }

  &.end {
    background: blue;
    @extend %end !optional;
  }
}

li {
  @include foobar {
    margin: 25px;

    @at-root { // at-root to scope the use of the placeholders to li and to remove li from output
      %start {
        margin: 50px;
      }

      %end {
        margin: 100px;
      }
    }
  }
}
```

 Outputs:

``` css
li.start {
  margin: 50px;
}

li.end {
  margin: 100px;
}

li.start {
  background: red;
}

li.end {
  background: blue;
}
```

**Comment by chriseppstein** [comment]
The way I want to handle this is my allowing the content block to be passed arguments from the mixin. In this way, the mixin could pass information about which part it is rendering, and the content block could return different content conditionally based on that parameter. See #871.

**Comment by Undistraction** [comment]
@chriseppstein Interesting. Very interesting.

**Comment by Undistraction** [comment]
Although on second thoughts, I think that solves a different issue. The beauty of passing multiple blocks is exactly that you aren't constricted to a set of predefined arguments. Unless I'm missing a use case?

By supporting named blocks, a mixin can both render and allow customisation of selectors. At the moment, if a mixin renders more than one selector, the only way to add additional props to additional selectors is by duplicating the selectors outside the mixin (or within the `@content` block).

For example, I can use `@content` in a simple mixin:

```
@mixin example(){

    .alpha {
        // Mixin supplies props
        // …
        // User supplies props
        @content;
    }

}
```

But what about:

```
@mixin example(){

    .alpha {
        // Mixin supplies props
        // …
        // User supplies props
        @content;
    }

    .beta {
        // Mixin supplies props
        // …
        // No way for user to supply props other than a duplicate selector
    }

}
```

But with named blocks:

```
@mixin example(){

    .alpha {
        // Mixin supplies props
        // …
        // User supplies props
        @content[alpha];
    }

    .beta {
        // Mixin supplies props
        // …
        // User supplies props
        @content[beta];
    }

}
```

**Comment by chriseppstein** [comment]
@Undistraction I think you're missing something. This exact example would work like so (syntax is all placeholder obviously)

``` scss
@mixin example {
    .alpha {
        @content(alpha);
    }

    .beta {
        @content(beta);
    }
}

@include example accepting($slot) {
  @if $slot == alpha {
    /* Alpha content */
  } @else if $slot == beta {
    /* Beta content */
  }
}
```

Granted this is a little more verbose, but this is also a lot more powerful than simply allowing names.

**Comment by Undistraction** [comment]
Thanks. That’s what I needed. The penny has dropped.

**Comment by brookjordan** [comment]
I would actually still like to have a built-in way of doing this.
We are using a similar method to do this in Ember's handlebars right now, and not having a standard way of doing it is tripping developers up.

I would love to have some standard sytax, possibly something similar to custom elements, like this:

```scss
// _bem-theme-mixin.scss
@mixin theme-element($class-definitions, $parent-class-name: null) {
  @each $class-name, $class-definition in $class-definitions {
    &--#{$class-name} {
      @content ($class-definition);
    }

    &--#{$class-name} & {
      @content children ($class-definition);
    }
  }
}

// _foo__bar.scss
$my-themes: (
  "red": (
    color: #f00,
  ),
  "green": (
    color: #0f0,
  ),
  "blue": (
    color: #00f,
  ),
);

.foo {
  @include theme-element($my-themes) using ($theme) {
    color: map-get($theme, color);

    @slot children {
      &__bar {
        border-color: map-get($theme, color);
      }
    }
  }
}
```

This would allow the `@mixin` to be used without the need for the `@if`: the `@contents` would go inside the unnamed `@slot`.

Requiring the `@if` is confusing to use and forgetting it has the unexpected side-effect of having all of the code go inside of both "slot"s. This could go unnoticed for a long time and then suddenly appear and be hard to debug.

As such, right now we are splitting this code into two mixins: `theme-self` and `theme-children`. It would be great to have a clean way to put this into one.
