### ISSUE TITLE
Placeholder selector inside :not()

### ISSUE THREAD

**Issue by andreev-artem** [sass/sass#1944]
[Minimal repro](http://www.sassmeister.com/gist/a2865309e9fc4f6ba6b4):

``` CSS
%not {
  color: red;
}

.not {
  @extend %not;
}

div:not(%not) {
  color: black;
}
```

CSS output:

``` CSS
.not {
  color: red;
}

div:not(%not) {
  color: black;
}
```

Expected output:

``` CSS
.not {
  color: red;
}

div:not(.not) {
  color: black;
}
```

Is that a bug?
