### ISSUE TITLE
Feature request - first-class declaration blocks

### ISSUE THREAD

**Issue by davidkpiano** [sass/sass#1956]
Apologies if this is a duplicate (possibly related to https://github.com/sass/sass/issues/1582 ?), but I'd like to propose a feature to Sass that would make non-nested declaration blocks be treated as a first-class citizen, with the same (or similar) operations as maps. Essentially, declaration blocks could be considered equivalent to flat maps with strings as keys and any valid Sass value type as values.

Here's a simple (slightly contrived) use case:

``` scss
// without first-class declaration blocks
$type-setting: (
  font-size: 16px,
  line-height: 1.2
);

.my-paragraph {
  @each $property, $value in $type-setting {
    #{$property}: $value;
  }
}

// with first-class declaration blocks
$type-setting: {
  font-size: 16px;
  line-height: 1.2;
}

.my-paragraph {
  @include $type-setting;
}
```

The **major difference between first-class declaration blocks and `@mixins`** is that the declaration blocks are treated as maps with iterable values, whereas values output by a `@mixin` cannot be manipulated. So, they can be considered constant `@mixin`s whose values can be iterated.

This is especially useful for tasks where the declaration blocks have an unambiguous structure, such as `@keyframe` blocks:

``` scss
$fade-in-out: {
  from { opacity: 0; }
  50% { opacity: 1; }
  to { opacity: 0; }
}

$slide-up: {
  from { transform: translateY(100%); }
  to { transform: translateY(0); }
}

// not a real function (yet?) - similar to lodash's _.merge()
$fade-slide: map-deep-merge($fade-in-out, $slide-up);

@keyframes fade-slide {
  @include $fade-slide;
}
```

**Result:**

``` css
@keyframes fade-slide {
  from {
    opacity: 0;
    transform: translateY(100%);
  }
  50% {
    opacity: 1;
  }
  to {
    opacity: 0;
    transform: translateY(0);
  }
}
```

For reference, if I wanted to do that today, I would have to convert each keyframe ruleset to a Sass map value and use a library to get the expected result:

``` scss
@import 'sassdash';

$fade-in-out: (
  from: ( opacity: 0 ),
  50%: ( opacity: 1 ),
  to: ( opacity: 0 )
);

$slide-up: (
  from: ( transform: translateY(-100%) ),
  to: ( transform: translateY(0) )
);

@keyframes fade-slide {
  @include _rules(_merge($fade-in-out, $slide-up));
}
```
