### ISSUE TITLE
Interpolation fails in head of media query

### ISSUE THREAD

**Issue by felixhayashi** [sass/sass#1957]
Hi,

in both cases below, the output will not be valid css but in case of the media query, it completely fails. My Sass version is 3.4.13.

```
$x: unquote("<<macro>>");

a {
  b: $x; // works and outputs b: <<macro>>
}

@media (max-width: #{$x}) { // throws an invalid css error
  .tc-sidebar-scrollable {
    .tmap-desktop-editor {
      display: none;
    }
  }
}
```

This looks like an inconsistency. Maybe a bug? – If not, is there any way I can get this work, i.e. to get the `<<macro>>` instructions treated as literals that are simply dumped at this place in the output file (they will be evaluated later in a javascript environment by another interpreter)?

Many thanks
Felix

**Comment by chriseppstein** [comment]
Interpolation happens before the media query is parsed. That is not valid syntax for a media query, so you get an error.

**Comment by felixhayashi** [comment]
Hi @chriseppstein 

Thanks for your answer

> That is not valid syntax for a media query, so you get an error.

But `b: $x;` is also interpolated, the result is also not valid css syntax and it still works, i.e. it is substituted and nothing fails. Is this interpolation done at a later stage or why is there not error here?

Maybe you could be so kind and give me a hint on how to circumvent the Sass parser here to receive `@media (max-width: <<macro>>)` in the output? Or is this not possible under any circumstances?

**Comment by davidkpiano** [comment]
@felixhayashi If you are able to format the at-rule after it has been parsed and output by the Sass compiler (which, if you're using macros, it seems like this is feasible for your use-case), you can use custom at-rules to get around Sass' proprietary handling of `@media` at-rules:

``` scss
$x: unquote("<<macro>>");

a {
  b: $x; // works and outputs b: <<macro>>
}

@--media (max-width: #{$x}) { // custom at-rule
  .tc-sidebar-scrollable {
    .tmap-desktop-editor {
      display: none;
    }
  }
}
```

Successfully compiles (in Ruby Sass) to:

``` scss
a {
  b: <<macro>>;
}

@--media (max-width: <<macro>>) {
  .tc-sidebar-scrollable .tmap-desktop-editor {
    display: none;
  }
}
```

**EDIT:** You just need to remember to change the `@--media` custom at-rules to normal `@media`.
