### ISSUE TITLE
Value in if (logical eq) clause incorrectly triggers invalid css value

### ISSUE THREAD

**Issue by mgreter** [sass/sass#1960]
IMO the following sample should be valid sass:

``` scss
foo {
  @if (10 == 5px*2px) {
    result: true;
  }
}
```

But I get `Error: 10px*px isn't a valid CSS value.`.
Also happens with: `foo { bar: 10 == 5px*2px; }`.
