### ISSUE TITLE
Minor discrepancy for `any` selectors in compressed mode

### ISSUE THREAD

**Issue by mgreter** [sass/sass#1962]
`spec/basic/50_wrapped_pseudo_selectors` (3.4.16)

``` scss
div {
  :-moz-any(a, b) {
    foo: foo;
  }
  :foo(a, b) {
    bar: bar;
  }
}
```

With ~~2.4.20 and~~ current master:

``` css
div :foo(a, b) {bar:bar}
div :-moz-any(a,b) {foo:foo}
```

Before it always produced spaces after `,` in the wrapped selector list. I can update libsass easily to go either way, but having these two different cases is a bit more difficult to support ;)

**Comment by cimmanon** [comment]
I can't reproduce this on Sassmeister (checked with 3.4.20 and 4.0.0.alpha.1)?

Expanded:

``` css
div :-moz-any(a, b) {
  foo: foo;
}
div :foo(a, b) {
  bar: bar;
}
```

Nested:

``` css
div :-moz-any(a, b) {
  foo: foo; }
div :foo(a, b) {
  bar: bar; }
```

Compact:

``` css
div :-moz-any(a, b) { foo: foo; }
div :foo(a, b) { bar: bar; }
```

Compressed:

``` css
div :-moz-any(a,b){foo:foo}div :foo(a,b){bar:bar}
```
