### ISSUE TITLE
List as map keys are only parsed when wrapped in parentheses

### ISSUE THREAD

**Issue by mgreter** [sass/sass#1970]
Related to https://github.com/sass/libsass/issues/1537

The following sass

``` scss
$map: (
  foo, bar: baz
);
```

Results in

```
Error: Invalid CSS after "  foo, bar": expected ")", was ": baz"
        on line 2 of foo.scss
  Use --trace for backtrace.
```

While

``` scss
$map: (
  (foo, bar): baz
);
foo {
  bar: map-get($map, (foo, bar));
}
```

Produces:

``` css
foo {
  bar: baz; }
```

IMO if lists are allowed keys, the first syntax should also be valid?
Currently libsass does happily parse both, so I wanted to clarify!
