### ISSUE TITLE
Commenting out undefined SCSS variables

### ISSUE THREAD

**Issue by CodyCahoon** [sass/sass#1971]
When you comment out an undefined variable using /\* */ in your SCSS file, sass does not compile.

``` css

/*
    .test-class{
        background:#{$undefinedVariable};
    }
*/

```

``` unix
$user: sass test.scss 
Error: Undefined variable: "$undefinedVariable".
        on line 3 of test.scss
  Use --trace for backtrace.
```

**Comment by davidkpiano** [comment]
That's because in CSS comments, which are `/* these comments */` and not `// these comments`, variables can be interpolated:

``` scss
$component: button;

/* The #{$component} component */
.button {
  display: block;
}
```

**Output:**

``` css
/* The button component */
.button {
  display: block;
}
```
