### ISSUE TITLE
Ampersand and multi line parent rule set parse error

### ISSUE THREAD

**Issue by davidzoli** [sass/sass#1976]
Multi line parent rule set may parsed incorrectly. Next rule start right after the coma char and contains the `\n` char too.
In outputStyle nested and expanded the generated css will a bit weird (but valid even so, I hope).

Example:

``` sass
.a,
.b {
    color: red;

    .c & {
        color: green;
    }
}
```

In this case the parent `.b` will be `\n.b`, so the compiled css will be:

``` css
.a,
.b {
  color: red;
}

.c .a, .c
.b {
  color: green;
}
```

Notice the new line after the second `.c`
