### ISSUE TITLE
Sass doesn't maintain order of selectors when using loops

### ISSUE THREAD

**Issue by mmase** [sass/sass#1979]
I'll demonstrate this quickly with an example.

This:

``` scss
  .photo {
    @for $i from 1 through 3 {
      &-#{$i} {
        background: url('#{$i}.jpg') center center #ccc no-repeat;
      }
    }
    background-size: cover;
  }
```

Compiles to:

``` css
.photo {
  background-size: cover;
}

.photo-1 {
  background: url("1.jpg") center center #ccc no-repeat;
}

.photo-2 {
  background: url("2.jpg") center center #ccc no-repeat;
}

.photo-3 {
  background: url("3.jpg") center center #ccc no-repeat;
}
```

For HTML:

``` html
<div class="photo photo-1"></div>
<div class="photo photo-2"></div>
<div class="photo photo-3"></div>
```

As you can tell, this is a problem because the `background-size` property will be ignored by the browser unless I use `!important`.

Shouldn't sass maintain this order?

**Comment by chriseppstein** [comment]
Pretty sure this is a duplicate but I can't find it. This is how Sass has worked since before I got here. I don't like it, but changing it is a big deprecation -- though maybe worth doing at 4.0. Maybe @nex3 can weigh in. 

For now, the direct properties of a selector are not split up by child selectors when nesting. If you need to maintain this order, you'll need to repeat the `.photo` selector or toss in a `&` selector like so:

``` scss
.photo {
  @for $i from 1 through 3 {
    &-#{$i} {
      background: url('#{$i}.jpg') center center #ccc no-repeat;
    }
  }
  & {background-size: cover; }
}
```
