### ISSUE TITLE
Allow extending within loops and if statements

### ISSUE THREAD

**Issue by MCTaylor17** [sass/sass#1982]
I'm trying to build utility classes for styling tables.  My basic classes consist of the following:

```
// Width
@for $i from 1 through 100 {
    table .width#{$i} { width: 1% * $i; }
}
// Height
@for $i from 1 through 20 {
    $var: $i * 25;
    table .height#{$var} { height: 1px * $var; }
}
```

This works as expected, however, I want to fill the gaps between height classes with the following: 

```
@for $i from 1 through 500 {
    @if $i % 25 != 0 {
        $int: ((floor($i/25) * 25) + (25 - ($i % 25)));
            @extend table .height#{$int};
    }
}
```

Practicality aside, why would this be prohibited?

**Comment by cimmanon** [comment]
It's not restricted because you're using a loop or an if statement, it's restricted because you're extending outside of a selector.  The purpose of extend is to consolidate selectors and you don't have one here.

``` scss
.foo {
  @for $i from 1 through 500 {
    @if $i % 25 != 0 {
        $int: ((floor($i/25) * 25) + (25 - ($i % 25)));
            @extend table .height#{$int};
    }
  }
}
```

Once you put it inside of a selector, you get a different error instead:

> Can't extend table .height24: can't extend nested selectors

Which, of course, is solved by removing `table` from your extend statement.

**Comment by MCTaylor17** [comment]
Thank you @cimmanon.  Clearly I locked onto the wrong problem.  My final code looked like this: 

``` scss
table {
    // Width
    @for $i from 1 through 100 {
        .width#{$i} { width: 1% * $i; }
    }

    // Height
    @for $i from 1 through 20 {
        $var: $i * 25;
        .height#{$var} { height: 1px * $var; }
    }
    // Height Gaps
    @for $i from 1 through 500 {
        @if $i % 25 != 0 {
            $int: (ceil($i/25) * 25);
            .height#{$i} {
                @extend .height#{$int};
            }
        }
    }
}
```
