### ISSUE TITLE
Feature: factorise the same values

### ISSUE THREAD

**Issue by mr21** [sass/sass#2000]
Hi :)

I didn't find an issue about this, but why can't we do something like this:

``` scss
.element {
    position: absolute;
    width:
    height: 100%;
    top:
    left: 0;
}
// inline
.element {
    position: absolute;
    width: height: 100%;
    top: left: 0;
}
```

Or maybe something like:

``` scss
.element {
    position: absolute;
    top, right, bottom, left: 10px;
}
```
