### ISSUE TITLE
comma in parent cause duplicate class name when inside of pseudoclass

### ISSUE THREAD

**Issue by alesak** [sass/sass#2005]
`section.map, section.results {
            .fa:not(.fa-inverse) {
                color: black;
            }
    }`

results in :not(.fa-inverse, .fa-inverse) 

`body section.map .fa:not(.fa-inverse, .fa-inverse), body section.results .fa:not(.fa-inverse, .fa-inverse) {
    color: black; }`

sassc: 3.3.0-10-g8d3d-dirty  
libsass: 3.3.3-13-g5069  
sass2scss: 1.0.5

**Comment by cimmanon** [comment]
I cannot reproduce this with version 3.4.20.  If you are using LibSass, you need to file your bug report with that repo.

``` css
section.map .fa:not(.fa-inverse), section.results .fa:not(.fa-inverse) {
  color: black;
}
```
