### ISSUE TITLE
[question] How can I prepend a selector to the current scope?

### ISSUE THREAD

**Issue by fritx** [sass/sass#2018]
Sorry for my poor sass experience.
I mean something like this:

``` sass
.cont {
  .login { top: 8px; }
  ^.mac .login { top: 6px; }
}
```

``` css
.cont .login { top: 8px; }
.mac .cont .login { top: 6px; }
```
