### ISSUE TITLE
Programmatic usage of the Engine

### ISSUE THREAD

**Issue by vecerek** [sass/sass#2019]
Hi Guys!
I am working on an AST-based Less to Sass converter for my bachelor's thesis. I'm just studying how your code works and I would like to closer examine the Sass AST structure, as well. I managed to get a part of the AST with the following code:

```
require "sass"
require "yaml"

engine = Sass::Engine.new(File.read(ARGV[0]), {:syntax => :scss})
puts engine.to_tree.to_yaml
```

However, if I pass a file containing an import statement, the import node in the AST has no children.
**I'd like to ask you 2 questions:**
1. What do I do wrong? Is there an option to be passed to the Engine's constructor? Maybe a FileImporter object?
2. How do I generate Sass code out of the AST? I know, that there are `to_sass()` and `to_scss()` methods that return the code as a String. That's why I doubt it would be the right way for me to generate the code.

Thank you :)

The passed file's content:
`@import "import/this-is-valid.scss"`

import/this-is-valid.scss:
`$my-var: black;`

The output:

```
--- !ruby/object:Sass::Tree::RootNode
children:
- !ruby/object:Sass::Tree::ImportNode
  imported_filename: import/this-is-valid.scss
  children: []
  template: 
  line: 1
  source_range: !ruby/object:Sass::Source::Range
    start_pos: !ruby/object:Sass::Source::Position
      line: 1
      offset: 9
    end_pos: !ruby/object:Sass::Source::Position
      line: 1
      offset: 36
    file: 
    importer: 
  options: &1
    :style: :nested
    :load_paths: []
    :cache: true
    :cache_location: "./.sass-cache"
    :syntax: :scss
    :filesystem_importer: !ruby/class 'Sass::Importers::Filesystem'
    :original_filename: 
    :cache_store: !ruby/object:Sass::CacheStores::Chain
      caches:
      - !ruby/object:Sass::CacheStores::Memory
        contents: {}
      - !ruby/object:Sass::CacheStores::Filesystem
        cache_location: "./.sass-cache"
    :line_comments: 
    :property_syntax: 
  imported_file: 
template: '@import "import/this-is-valid.scss";

'
line: 1
source_range: !ruby/object:Sass::Source::Range
  start_pos: !ruby/object:Sass::Source::Position
    line: 1
    offset: 1
  end_pos: !ruby/object:Sass::Source::Position
    line: 1
    offset: 1
  file: 
  importer: 
has_children: true
options: *1
```
