### ISSUE TITLE
Bug in extending pseudo elements with the universal selector

### ISSUE THREAD

**Issue by TxHawks** [sass/sass#2022]
The following:

``` scss
%foo {
  &,
  &:before,
  &:after {
    bar: baz;
  }
}

* {
  @extend %foo;
}
```

Produces:

``` scss
*,
:before,    // Notice the missing `*`
:after {
  bar: baz;
}
```

Expected result:

``` scss
*,
*:before,
*:after {
  bar: baz;
}
```

``` scss
a {
  @extend %foo;
}
```

 does produce the expected output.
