### ISSUE TITLE
Feature Request: Import with named parameters

### ISSUE THREAD

**Issue by amonger** [sass/sass#2025]
I've started looking at implementing a colour map for certain projects, which is a nice way of grouping colours based on a base colour.

I was looking at being able to set parameters based on the @content block. 

For instance:

``` scss
    $colour-map: (
        green: (
                primary-color: $green,
                contrasting-color: $dark-blue-low
        ),
        yellow: (
                primary-color: $yellow,
                contrasting-color: $dark-blue-low
        ),
    );
```

If I wanted to add these colours as a button block, id have to do something like the following:

``` scss
.btn{
        @each $label, $map in $colour-map {
                $primaryColour: map_get($map, primary-color);
                $contrastingColour: map_get($map, contrasting-color);
                &--#{$label} {
                    background-color: $primaryColour;
                    color: $contrastingColour;
                }
        }
}
```

This would be nicer, and more reusable if we could do this via a mixin like:

``` scss
    @mixin colours () {
        @each $label, $map in $colour-map {
                $primaryColour: map_get($map, primary-color);
                $contrastingColour: map_get($map, contrasting-color);
                &--#{$label} {
                    @content;
                }
        }
    }

    .btn{
        @include colours() {
             background-colour: $primaryColour;
             color: $contrastingColour;
         }
    }
```

This would mean we would have the option of selecting the colour, and defining it based on the block type.
