### ISSUE TITLE
Request: Allow nesting under selector without class/id name

### ISSUE THREAD

**Issue by paulozoom** [sass/sass#2030]
I was writing a mixin that would namespace a selector by prefixing it with a  breakpoint name. However, I also want to output a non-prefixed version, that works across all viewports. As I see it, this is a very common RWD situation.

Example:

``` scss
@include each-bp {
  &left { float: left; }
  &right { float: right; }
}
```

Output:

``` css
.left { float: left; }
.right { float: right; }

@media screen and (min-width: 500px) {
  .s-left { float: left; }
  .s-right { float: right; }
}
```

For this, I tried to write such a mixin:

``` scss
@mixin each-bp {
  // Unprefixed selector
  #{.} {
    @content;
  }
  // Prefixed selectors
  @each $bp, $size in $bps {
    @media screen and (min-width: $size) {
      .#{$bp}- {
        @content;
      }
    }
  }
}
```

However, the third line, `#{.} {`, isn’t valid Sass, because it expects a class name.

There isn’t, to my knowledge, an alternative for this that isn’t setting a global variable for the `#{$bp}-` prefix at each loop iteration and prepending it to each selector in the block passed to the mixin call, which is both inelegant — unnecessary pollutes the global namespace — and not very maintainable — changing the global variable’s name would imply an update to every selector in every call of this mixin.

Considering the lack of alternatives, and how common of a situation this is these days (see frameworks such as Bass, Intuit, Solid, etc.), I’d argue that for selectors with nested selectors, this requirement of a class name should be dropped, so this common use case becomes valid sass.

**Comment by cimmanon** [comment]
No, only bad designers write selectors like you're trying to write.  What you're trying to do is worse than "pollute[s] the global namespace", you're bloating your markup with unsemantic selectors with an added twist of having to modify your markup when your design changes.  You've created an unmaintanable mess in your CSS _and_ the markup.

The best case scenario for doing this in Sass is going to force you to generate a lot of selectors.  [Source for selector-nth](https://github.com/cimmanon/selector-nth).

``` scss
@import "selector-nth";

@function prefix-class($sel, $prefix) {
    @return #{str-slice($sel, 1, 1)}#{$prefix}-#{str-slice($sel, 2)};
}

@mixin each-bp($bps) {
    // Unprefixed selector
    & {
        @content;
    }

    // Prefixed selectors
    @each $bp, $size in $bps {
        @media screen and (min-width: $size) {
            @at-root #{selector-nth(&, -1, prefix-class, $bp)} {
                @content;
            }
        }
    }
}

$bps: (s, 500px),;
.foo, #bar {
    @include each-bp($bps) {
        float: left;
    }
}
```

Output:

``` css
.foo, #bar {
  float: left;
}
@media screen and (min-width: 500px) {
  .s-foo, #s-bar {
    float: left;
  }
}
```

In short, don't do this.
