### ISSUE TITLE
How to handle new interpolation near operators

### ISSUE THREAD

**Issue by kuon** [sass/sass#2031]
I have the following warning on my sass file:

```
Error: DEPRECATION WARNING on line 65 of /var/folders/bl/b749qrqj0vd8f287dgc1zhq00000gn/T/atom-linter_24875h4rNsbm19ESf/browser_container.scss: #{} interpolation near operators will be simplified in a future version of Sass. To preserve the current behavior, use quotes:

unquote("-n+#{$i}")
```

My code is the following:

``` scss
.asset-block:nth-child(-n+#{$i}) {
}
```

but if I replace with

``` scss
.asset-block:nth-child(unquote("-n+#{$i}")) {
}
```

as suggested by the error message, it does not produce the right output.

For example, with `$i: 20` I want:

```
.asset-block:nth-child(-n+20)
```

**Comment by chriseppstein** [comment]
I cannot reproduce the deprecation warning locally using your code example. I only get it if I use it in a SassScript expression like so:

``` scss
$i: 20;
.asset-block:nth-child(-n+#{$i}) {
 foo: -5 + #{$i};
}
```

**Comment by kuon** [comment]
I should have posted the complete code, here it is:

``` scss
@for $i from 1 through 20 {
    $base: $label-list-width + $info-box-width;
    $min: $base + 200px * $i;
    $max: $base + 200px * $i + 200px;

    @if $i == 1 {
        $min: 00px;
    }

    @media (min-width: $min) and (max-width: $max) {
        .browser-container {
            .asset-block:nth-child(#{$i}n),
            .asset-block:last-child {
                border-right-width: 1px;
            }

            .asset-block:nth-child(-n+#{$i}) {
                border-top-width: 1px;
            }

            .asset-block {
                width: percentage(1 / $i);
            }
        }
    }
}
```
