### ISSUE TITLE
[FR] Explode/expand wrapped selectors (`:not`)

### ISSUE THREAD

**Issue by mgreter** [sass/sass#2036]
LibSass will [merge a change](https://github.com/sass/libsass/pull/2032) that fixes the most urgent issues with handling `:not` wrapped selectors. Unfortunately I'm not able to avoid a breaking\* change. For illustration see the following sample:

``` scss
:not(.asd, .qwe) {
  content: test;
}
:not(.foo) {
  content: test;
}
.bar, .baz {
  @extend .foo;
}
```

Compile to (with ruby sass):

``` css
:not(.asd, .qwe) {
  content: list; }
:not(.foo):not(.bar):not(.baz) {
  content: test; }
```

With libsass this will yield:

``` css
:not(.asd):not(.qwe) {
  content: list; }
:not(.foo):not(.bar):not(.baz) {
  content: test; }
```

The only difference is that `:not(.asd, .qwe)` is expanded to `:not(.asd):not(.qwe)`. My argument to merge this breaking\* change in libsass is simply that this is [invalid css](https://developer.mozilla.org/en-US/docs/Web/CSS/:not) anyway.

> The negation CSS pseudo-class, :not(X), is a functional notation taking a simple selector X as an argument. It matches an element that is not represented by the argument. X must not contain another negation selector.

Therefore I would like to ask if ruby sass would be willing to adopt this behavior?
IMO it makes specially sense if you look at what happens with the `@extend` above.
