### ISSUE TITLE
@while inside @each, doesn't work

### ISSUE THREAD

**Issue by adamstac** [sass/sass#204]
Here's something I was working on to automate some color themes in a button set I'm working on and I'm wondering why we don't allow `@while` in `@each` directives.

``` scss
// `Colors mixin

// What colors do we support?
$colors: red green blue;

@mixin button-colors {
  @each $color in $colors {

    .button.#{$color} {

     @while $color != "red" { background-color: $color; }
     @while $color == "red" { background-color: darken($color, 15%); }

   }

  }
}

@include button-colors;
```
