### ISSUE TITLE
Nested calc(var()) and SASS variables doesn't substitute variables

### ISSUE THREAD

**Issue by nazar-pc** [sass/sass#2048]
``` sass
$avatar-size : 4em;
$padding : .5em;
#img {
    height : var(--cs-comments-avatar-size, $avatar-size);
    width  : var(--cs-comments-avatar-size, $avatar-size);
}

.details {
    min-height   : calc(var(--cs-comments-avatar-size, $avatar-size) + var(--cs-comments-padding, $padding));
    padding-left : var(--cs-comments-padding, $padding);
}
```

Code above compiles to:

``` css
#img {
    height : var(--cs-comments-avatar-size, 4em);
    width  : var(--cs-comments-avatar-size, 4em)
}

.details {
    min-height   : calc(var(--cs-comments-avatar-size,$avatar-size) + var(--cs-comments-padding,$padding));
    padding-left : var(--cs-comments-padding, .5em)
}
```

While expected result is:

``` css
#img {
    height : var(--cs-comments-avatar-size, 4em);
    width  : var(--cs-comments-avatar-size, 4em)
}

.details {
    min-height   : calc(var(--cs-comments-avatar-size, 4em) + var(--cs-comments-padding, .5em));
    padding-left : var(--cs-comments-padding, .5em)
}
```

However, workaround like this results in proper compiled CSS:

``` sass
$avatar-size : 4em;
$padding : .5em;
#img {
    height : var(--cs-comments-avatar-size, $avatar-size);
    width  : var(--cs-comments-avatar-size, $avatar-size);
}

.details {
    min-height   : calc(var(--cs-comments-avatar-size, #{$avatar-size}) + var(--cs-comments-padding, #{$padding}));
    padding-left : var(--cs-comments-padding, $padding);
}
```

But it is quite ugly.
