### ISSUE TITLE
Invalid order of properties defined after nested media query

### ISSUE THREAD

**Issue by marek-saji** [sass/sass#2052]
# Input

``` sass
foo
{
    @media screen
    {
        bar: 2;
    }
    bar: 1;
}
```
# Expected output

``` css
@media screen {
  foo {
    bar: 2; } }

foo {
  bar: 1; }
```
# Output

All of the following produce the same output:
- sass-3.4.22
- libsass-3.3.6 (node-sass-3.6.0)
- libsass-3.3.6 ([via source map inspector](http://libsass.ocbnet.ch/srcmap/#Zm9vCnsKICAgIEBtZWRpYSBzY3JlZW4KICAgIHsKICAgICAgICBiYXI6IDI7CiAgICB9CiAgICBiYXI6IDE7Cn0K))

``` css
foo {
  bar: 1; }
  @media screen {
    foo {
      bar: 2; } }
```

Note that `bar: 1` has been moved before media query.
# Use case

The example code may seem nonsensical, so I'm attaching a less simplified use case:

``` sass
.foo
{
    padding: 0;
    @media all and (min-width: 20em)
    {
        margin: 2em;
    }
    margin-bottom: 1em;
}
```
# Workaround

Splitting media query and the property after it into separate blocks produces output as expected:

``` sass
foo
{
    @media screen
    {
        bar: 2;
    }
}
foo
{
    bar: 1;
}
```

**Comment by cimmanon** [comment]
Duplicate of https://github.com/sass/sass/issues/1751

**Comment by chriseppstein** [comment]
Knowing what I know now, I prefer Sass to work how you suggest, but for better or worse, this is how Sass has worked for a very long time and for reasons that seemed good at the time. 
Changing this would require an onerous deprecation process and the work that people would need to do for that isn't (imo) justified by the net benefit.

Note: there is a more trivial work around than you posted. Just add a `&` around the properties that need to stay below the other nested selectors:

``` scss
.foo
{
    padding: 0;
    @media all and (min-width: 20em)
    {
        margin: 2em;
    }
    & {margin-bottom: 1em; }
}
```
