### ISSUE TITLE
Function doesn't support keyword arguments

### ISSUE THREAD

**Issue by Kasheftin** [sass/sass#2056]
I try to compile input.scss to output.scss (both in scss format, that's preparation for future work that's not under my control).
This is input.scss content (there's undefined function in it):

``` scss
.test {
  padding: myundefinedfunc(100);
}
```

It compiles successfully, the result is:

``` scss
.test {
  padding: myundefinedfunc(100);
```

It means compiler does not know about undefined function and just includes it as is. That's the expected behavior.

Next, let's change input.scss to:

``` scss
.test {
  padding: myundefinedfunc($n:100);
}
```

This case compiler throws an error `Function myundefinedfunc doesn't support keyword arguments`. I think this is the bug, because compiler does not know undefined function and does not know if it supports keyword argument or not. It should include it as is.
Expected result: 

``` scss
.test {
  padding: myundefinedfunc($n:100);
}
```

version info:

``` cmd
$ sass -v
Sass 3.2.19 (Media Mark)
$ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
```
