### ISSUE TITLE
Error report: Extend inside directives

### ISSUE THREAD

**Issue by vecerek** [sass/sass#2058]
According to the Sass language specification, the use of _&#64;extend_ within _&#64;media_ (or other CSS directives) may only extend selectors that appear within the same directive block. However, if the referenced selector by the &#64;extend is also present in the outer scope, it fails applying the &#64;extend rule and throws an error message.

An example SCSS code:

``` scss
@media print {
  .selector { // this should be matched - it is in the same directive
    color: black;
  }
  .screenClass{
    @extend .selector;
  }
}
.selector {
  color: red;
}
```

The error message received:

```
You may not @extend an outer selector from within @media.
You may only @extend selectors within the same directive.
From "@extend .selector" on line 6.
```
