### ISSUE TITLE
@at-root with #{&} inside a comma-separated selector generates wrong code

### ISSUE THREAD

**Issue by keichinger** [sass/sass#2059]
**Tested versions**: v3.3.6 via node-sass (sorry, I can't run/test it against the ruby implementation directly)

Given the following input:

``` css
.class-a {
    .class-b,
    .class-c {
        color: yellow;

        @at-root .something-at-root#{&} {
            color: pink;
        }
    }
}
```

You'll get the following output:

``` css
.class-a .class-b,
.class-a .class-c {
    color: yellow;
}

.something-at-root.class-a .class-b,
.class-a .class-c {
    color: pink;
}
```

The problem here is that `#{&}`, which I used here in this example to prepend some selector (`.something-at-root`) right at the beginning, which causes the compiler to generate wrong output.

I'd expect the following output for the second block:

``` css
.class-a .class-b,
.class-a .class-c {
    color: yellow;
}

.something-at-root.class-a .class-b,
.something-at-root.class-a .class-c {
    color: pink;
}
```

Clearly one could argue that I've abused `#{}` and `&` here though I couldn't find another way to achieve the same result (apart from the potential bug). I've just expected that the compiler would treat string interpolation with the same rules as the rest.

To me it looks like the entire string is just pasted into its destination without honoring the `,`.
