### ISSUE TITLE
Support embedding other selectors

### ISSUE THREAD

**Issue by gligoran** [sass/sass#2076]
It would be very handy to have an alternative to `@extend`, that imports the ruleset from another selector. LESS does this in this way:

``` less
.wrap {
  text-wrap: wrap;
  white-space: -moz-pre-wrap;
  white-space: pre-wrap;
  word-wrap: break-word;
}

pre { .wrap }
```

Output:

``` css
.wrap {
  text-wrap: wrap;
  white-space: -moz-pre-wrap;
  white-space: pre-wrap;
  word-wrap: break-word;
}
pre {
  text-wrap: wrap;
  white-space: -moz-pre-wrap;
  white-space: pre-wrap;
  word-wrap: break-word;
}
```

P.S. I hope this is not a duplicate, but I didn't find a name for this functionality, so it was rather hard to search for it.
