### ISSUE TITLE
Nesting type selector with reference to its parent

### ISSUE THREAD

**Issue by ghost** [sass/sass#2081]
Apologies if this has been discussed before, I couldn't find it in the issues section.

I'm after a feature, which would allow nesting a type selector (plain element) and chain it with a parent using the `&` notation to produce the following output:

``` css
.button { ... }
a.button { ... }
button.button { ... }
```

Obviously the following example is invalid, but it illustrates the issue:

``` scss
.button {
  &a { ... } // or a&
  &button { ... } // or button&
}
```

I have always worked around this by writing out the chained selectors manually, but I wonder if a feature this common to CSS should be supported in Sass, compared to supporting the opinionated BEM syntax nesting.

**Comment by chriseppstein** [comment]
Duplicate of #282.

This works right now:

``` scss
@mixin append-element($element-name) {
  @at-root #{selector-append($element-name, &)} {
    @content;
  }
}

.button {
  @include append-element(a) { color: red; }
  @include append-element(button) { color: blue; }
}
```

It's not as concise, but it's a decent work around.
