### ISSUE TITLE
Feature request: Optimize out dead code media queries

### ISSUE THREAD

**Issue by jnvsor** [sass/sass#2097]
When nesting code it might be nice to optimize out dead code. Example:

main.scss

``` scss
@media (max-width: 900px){
  @import "stuff";
}
```

_stuff.scss

``` scss
@media (min-width: 1000px){
  #stuff {
    color: blurple;
  }
}
```

output:

``` scss
@media (max-width: 900px) and (min-width: 1000px) {
  #stuff {
    color: blurple;
  }
}
```

Needless to say, the output is dead code and can be omitted entirely
