### ISSUE TITLE
Sass mixin that references parent styles

### ISSUE THREAD

**Issue by hatzipanis** [sass/sass#2101]
I [posted this to SO](http://stackoverflow.com/questions/38469682/sass-mixin-that-references-parent-styles) and after sharing it with a few people they suggested posting it here for your feedback.

We can reference parent selectors using the ampersand `&` but do we have a solution for referencing parent styles?

I'd like to be able to do something like this:

``` scss
 @mixin copy {
    &-copy {
        @media (min-width: 300px) {
            @context; // directive doesn't exist but illustrates the point
        }
    }
}

.foo {
    font-size: 18px;
    color: red;

    @include copy;
}
```

and output:

``` css
.foo {
    font-size: 18px;
    color: red;
}

@media (min-width: 300px) {
    .foo-copy {
        font-size: 18px;
        color: red;
    }
}
```

I can get somewhere quite close with:

``` scss
@mixin copy ($parent) {
    &-copy {
        @media (min-width: 300px) {
            @extend #{$parent};
        }
    }
}

.foo {
    font-size: 13px;
    color: red;

    @include copy(&);
}
```

...but because Sass doesn't allow us to `@extend` an outer selector from within `@media` that won't work. It would if I wasn't using media queries however. [Someone else posted a solution](http://stackoverflow.com/a/38474952/4794461) which takes a different approach by using `@content` and while it's close, it's still not quite there.

Is this something that has ever come up? And are there roadblocks for implementing it?

**Comment by chriseppstein** [comment]
I don't think extend is the right tool for this job. You are not creating an inheritance relationship between these two selectors, you're trying to duplicate them. That means you should be using mixins.

How about this:

``` scss
@mixin copy {
  @content;
  &-copy {
    @media (min-width: 300px) {
      @content;
    }
  }
}

.foo {
  @include copy {
     font-size: 18px;
     color: red;
  }
}
```

produces:

``` css
.foo {
  font-size: 18px;
  color: red;
}
@media (min-width: 300px) {
  .foo-copy {
    font-size: 18px;
    color: red;
  }
}
```

Aaaand I just realized that's the exact solution that you don't think is "quite there" so I guess I don't understand why you think that. Again, `@extend` defines an "is-a" relationship between two selectors. This just doesn't seem appropriate to your use case.
