### ISSUE TITLE
Selector Sequences issue.

### ISSUE THREAD

**Issue by srinivashappy** [sass/sass#2105]
in below id of #fake-link color not applied to the id, its taking the a selector properties only link [here](https://jsfiddle.net/srinivashappy/8x3Ln8x5/).

```
<div id="fake-links">fake link <a href="">hey i am too working</a></div>
<a href="">hello this testing</a>
```

```
#fake-links{
color:red;
@extend a;

}
a {
  color: blue;
  &:hover {
    text-decoration: underline;
    color:yellow;
  }
 }
```

**Comment by oleksandrmaksymenko** [comment]
Try write a{} before @extend;
As a result, it should come out in
a{ color: blue ... }
#fake-links { @extend a; }

**Comment by chriseppstein** [comment]
If you look at the generated css you will see why:

``` css
#fake-links {
  color: red; }

a, #fake-links {
  color: blue; }
  a:hover, #fake-links:hover {
    text-decoration: underline;
    color: yellow; }
```

Basically you've got

``` css
#fake-links {
  color: red; }

a, #fake-links {
  color: blue; }
```

So, of course, because of how the CSS cascade resolution works, the second selector takes precedence. As @GabeJonson noted, if you do your extended selector after the base selector this will work.
