### ISSUE TITLE
[BUG] /deep/ with @extend abstract classes

### ISSUE THREAD

**Issue by lifaon74** [sass/sass#2136]
I detected some kind of bug while using /deep/ keyword (used in shadow DOM) :

``` sass
:host /deep/ {
  @extend %abstract-test;
 .test {
    @extend %abstract-test;
  }
}

%abstract-test {
  background: red;
}
```

Will result in :

``` css
:host, :host /deep/ .test {
  background: red; }
```

But should be :

``` css
:host /deep/, :host /deep/ .test {
  background: red; }
```

In a general nammer, if we write

``` sass
:host /deep/ {
  @extend %abstract-test;
}
```

/deep/ is not taken in account

With angular 2 this bug became a real pain :( 

Thanx for your help.

**Comment by maciej-ka** [comment]
Hi, I confirm, however the result is an error:

``` scss
:host /deep/ {
  @extend %abstract-test;
}

%abstract-test {
  background: red;
}
```

ends with

```
$ ~/sass/bin ./scss /tmp/test.scss
Error: :host /deep/ can't extend: invalid selector
        on line 2 of /tmp/test.scss
  Use --trace for backtrace.
```

The error is gone, when /deep/ selector is deleted from scss file.
