### ISSUE TITLE
Feature: Print Function: Print into SCSS output

### ISSUE THREAD

**Issue by acarlstein** [sass/sass#2140]
**Summary**

New Feature: @print function which allows for example a string generated in a function to be print in the output CSS file that SASS will generate. Similar to print in C or PrintStream in Java.

**Description**

Let's say we have the following:

```scss
$color-map: (
  red: #FF0000,
  blue: #00FF00,
  green: #0000FF,
  white: white,
  black: #000000
);

@function map-colors-to-boxes($color-map){
  $str: '';
  $index: 0;
  @each $name, $hex in $color-map { 
    $str: $str 
        + " #box-#{$index}:after {"
        + "  content: ' #{$name}'; "
        + "  color: #{$hex};"
        + " }";
    $index: $index + 1;
  }
  @return $str;
}
```

This function will generate:

```css
# box-0:after {  content: ' red';   color: #FF0000; } #box-1:after {  content: ' blue';   color: #00FF00; } #box-2:after {  content: ' green';   color: #0000FF; } #box-3:after {  content: ' white';   color: #CCCCCC; } #box-4:after {  content: ' black';   color: #000000; }
```

However, I can't use this output because there is no keyword or function that allows me to use it in this fashion:

```scss
.box { 
  border: 1px solid black;
  padding: 10px;
  margin: 20px;
  text-align: center;
}

@print map-colors-to-boxes($color-map);
```

so we can have SASS generate this CSS output:

```css
.box { 
  border: 1px solid black;
  padding: 10px;
  margin: 20px;
  text-align: center;
}
# box-0:after {  content: ' red';   color: #FF0000; } #box-1:after {  content: ' blue';   color: #00FF00; } #box-2:after {  content: ' green';   color: #0000FF; } #box-3:after {  content: ' white';   color: #CCCCCC; } #box-4:after {  content: ' black';   color: #000000; }
```

If there is a way to do it, please let me know

**Comment by jakob-e** [comment]
@acarlstein – try using mixins – this works for me 

``` SCSS
$color-map: ( 
    red: #FF0000, 
    blue: #00FF00, 
    green: #0000FF, 
    white: white, 
    black: #000000
);

@mixin map-colors-to-boxes($color-map: $color-map) {
    @each $name, $hex in $color-map {
        #box-#{index(map-keys($color-map), $name) - 1}:after {
            content: $name;
            color: $hex;
        }
    }
}

@include map-colors-to-boxes;
```

Output:

``` CSS
#box-0:after {
  content: red;
  color: #FF0000;
}

#box-1:after {
  content: blue;
  color: #00FF00;
}

#box-2:after {
  content: green;
  color: #0000FF;
}

#box-3:after {
  content: white;
  color: white;
}

#box-4:after {
  content: black;
  color: #000000;
}

```
