### ISSUE TITLE
Bug – wrong conversion of resolution units   

### ISSUE THREAD

**Issue by jakob-e** [sass/sass#2143]
In CSS  [1dppx equals 96dpi](https://www.w3.org/TR/2012/WD-css3-values-20120308/#dppx) why you would expect: 

``` SCSS
$should-be-true: 1dppx == 96dpi;     //  fail   false
$should-be-1dppx: max(1dppx, 95dpi); //  fail   95dpi 
$should-be-97dpi: max(1dppx, 97dpi); //  pass   97dpi
$should-be-96dpi: 0dpi + 1dppx;      //  fail   0.01041667dpi
$should-be-2dppx: 0dppx + 192dpi;    //  fail   18432dppx
```

It seems like conversion is somehow flipped

``` SCSS
dpi-to-dpcm: 0dpcm + 1dpi;  // 2.54dpcm     should be 0.3937dpcm
                                         ⤮  
dpcm-to-dpi: 0dpi + 1dpcm;  // 0.3937dpi    should be 2.54dpi    
```

... or just uses px, in, cm conversion (missing the "per" part)   

``` SCSS
in-to-cm: 0cm + 1in;   // 2.54cm; 
cm-to-in: 0in + 1cm;   // 0.3937in


```

**Comment by jakob-e** [comment]
To quick fix the conversion part (does not solve the problem) you could do:
````SCSS
@function dpi($input){
    @return if(1dppx < 95dpi, 0dpi + 1dpi/(0dpi + $input), 0dpi + $input);
}
@function dpcm($input){
    @return if(1dppx < 95dpi, 0dpcm + 1dpcm/(0dpcm + $input), 0dpcm + $input);
}
@function dppx($input){
    @return if(1dppx < 95dpi, 0dppx + 1dppx/(0dppx + $input), 0dppx + $input);
}

test { 
    dpi-to-dpi : dpi(1dpi); 
    dpcm-to-dpi: dpi(1dpcm); 
    dppx-to-dpi: dpi(1dppx); 
    dpi-to-dpcm : dpcm(1dpi); 
    dpcm-to-dpcm: dpcm(1dpcm); 
    dppx-to-dpcm: dpcm(1dppx); 
    dpi-to-dppx : dppx(1dpi); 
    dpcm-to-dppx: dppx(1dpcm); 
    dppx-to-dppx: dppx(1dppx); 
}
`````
````CSS
/* Output: */
test {
  dpi-to-dpi: 1dpi;
  dpcm-to-dpi: 2.54dpi;
  dppx-to-dpi: 96dpi;
  dpi-to-dpcm: 0.3937dpcm;
  dpcm-to-dpcm: 1dpcm;
  dppx-to-dpcm: 37.79528dpcm;
  dpi-to-dppx: 0.01042dppx;
  dpcm-to-dppx: 0.02646dppx;
  dppx-to-dppx: 1dppx;
}

**Comment by jakob-e** [comment]
To fix the conversion problem (does not solve min, max etc.) here is a small set of functions to first flip then switch units:

``` SCSS
@function dpi($input)  { @return convert-resolution-unit($input, dpi); }
@function dpcm($input) { @return convert-resolution-unit($input, dpcm); }
@function dppx($input) { @return convert-resolution-unit($input, dppx); }
@function strip-unit($input) { @return $input/($input * 0 + 1); }
@function convert-resolution-unit($input, $to-unit) {
    $units: (dppx: 0dppx, dpcm: 0dpcm, dpi: 0dpi);
    $input-unit: map-get($units, unit($input));
    $to-unit: map-get($units, $to-unit);
    @return $to-unit + if(1dppx < 95dpi, 
         strip-unit($input-unit + (strip-unit($input) + $to-unit)), 
         $input
    );
}



test { 
    dpi-to-dpi : dpi(1dpi);    //  1dpi;
    dpcm-to-dpi: dpi(1dpcm);   //  2.54dpi;
    dppx-to-dpi: dpi(1dppx);   //  96dpi;

    dpi-to-dpcm : dpcm(1dpi);  //  0.3937dpcm
    dpcm-to-dpcm: dpcm(1dpcm); //  1dpcm
    dppx-to-dpcm: dpcm(1dppx); //  37.79528dpcm

    dpi-to-dppx : dppx(1dpi);  //  0.01042dppx
    dpcm-to-dppx: dppx(1dpcm); //  0.02646dppx
    dppx-to-dppx: dppx(1dppx); //  1dppx
}



```
