### ISSUE TITLE
Access to the ROOT namespaces

### ISSUE THREAD

**Issue by hitmands** [sass/sass#2145]
is there a plan to implement **the way to access the current `root namespace`** ?
example: 

``` scss
.foo {
  &-baz {
    color: red;

    #{super} &-foobaz {
      color: green;
    }
  }
}
```

where, in this case, `#{super}` stands for `.foo`.

`.foo .foo-baz-foobaz { color: green }`

**Comment by deckdom** [comment]
See at the [Official Function Reference](http://sass-lang.com/documentation/Sass/Script/Functions.html#selector_functions) if there's something fitting for your situation

**Comment by KittyGiraudel** [comment]
There is no way to do, especially since `.foo` does not exist in itself. The top level select is `.foo-baz`, not `.foo`. Otherwise, have a look at the selector manipulation functions if you can do something with it, yup.

**Comment by joneff** [comment]
You could, if you want to, always safe a reference to `.foo` and reuse it later on e.g.:

``` scss
.foo {
  $super: &;
  &-baz {
    color: red;

    #{$super} &-foobaz {
      color: green;
    }
  }
}
```

Of course that's like the simplest scenario ever. Making it work for an entire already built in project will require some tweaking
