### ISSUE TITLE
variables not works in nth-child() and calc()

### ISSUE THREAD

**Issue by madvik** [sass/sass#2166]
I'm surprise that my code don't work in scss  : 

```
@for $i from 1 through 6 {
  $n: 1.5em * $i;
        .step:nth-child($i) {
            input[type="radio"]:checked + label:after {
                width: calc(100% + $n);
            }
        }
    }
```

**Comment by KittyGiraudel** [comment]
You need to interpolate your variables.

``` css
@for $i from 1 through 6 {
  $n: 1.5em * $i;
  .step:nth-child(#{$i}) {
    input[type="radio"]:checked + label:after {
      width: calc(100% + #{$n});
    }
  }
}
```
