### ISSUE TITLE
Getting Process finished with exit code -1073741571 (0xC00000FD)

### ISSUE THREAD

**Issue by SuperDJ** [sass/sass#2171]
I have the following SCSS:

```
$drawer-padding: rem-calc(16px);
$drawer-profile-img: rem-calc(40px);
$drawer-profile-top: $drawer-padding;
$drawer-profile-content-height: rem-calc(56px);
$drawer-profile-bottom-padding: rem-calc(8px);
$drawer-profile-height: #{$drawer-padding} + #{$drawer-profile-img} + #{$drawer-profile-content-height} + #{$drawer-profile-bottom-padding};
```

When I use `$drawer-profile-height` I get the following error: `Process finished with exit code -1073741571 (0xC00000FD)`

If I would remove `#{}` around each variable it does work. 
I use Gulp with gulp-sass. I hope someone can tell my why I'm getting this error.

**Comment by KittyGiraudel** [comment]
> If I would remove #{} around each variable it does work. 

Why don’t you do that then? The interpolation is not necessary here anyway. Also it’s hard to figure out where the problem is without seeing `rem-calc`.

**Comment by SuperDJ** [comment]
The reason I'm not removeing `#{}` is because it works as in I'm not getting errors but the css it produces isn't valid `height:calc(1.14286rem2.85714rem4rem.57143rem)`.

You can take a look at the code:
https://github.com/SuperDJ/smaterial/blob/master/stylesheets/scss/components/_navigation-drawer.scss line 17 and 324. I know the `calc()` isn't there in the source but that was from testing.

rem-calc:

```
@function rem-calc( $size, $font-size : 14 ) {
   $font-size: $font-size + 0px;
   $remSize: $size / $font-size;
   @return #{$remSize}rem;
}
```

**Comment by KittyGiraudel** [comment]
Could you try:

``` scss
@function rem-calc($size, $font-size: 14px) {
  @return $size / $font-size * 1rem;
}
```

**Comment by SuperDJ** [comment]
Tried it but still gives me the same error

**Comment by SuperDJ** [comment]
@HugoGiraudel After some more fiddling with it I found that when I would remove one of the variables from `$drawer-profile-height` that it would work. It looks as if there is a limit of how many variables you can use on one line.

**Comment by KittyGiraudel** [comment]
> It looks as if there is a limit of how many variables you can use on one line.

This is really unlikely. Can you please reproduce the problem with your code on Sassmeister? I’ll have a look.

**Comment by SuperDJ** [comment]
@HugoGiraudel I'm not exactly sure of how to share but:

<p class="sassmeister" data-gist-id="e90a4beee6e957158a05541c066600b8" data-height="480" data-theme="tomorrow"><a href="http://sassmeister.com/gist/e90a4beee6e957158a05541c066600b8">Play with this gist on SassMeister.</a></p><script src="http://cdn.sassmeister.com/js/embed.js" async></script>

Don't know if it's important to know which version I'm using:
SCSS: 3.4.22
Gulp: 3.9.1
gulp-sass: 2.3.1

I run Gulp trough PHPStorm

**Comment by KittyGiraudel** [comment]
I cannot reproduce your issue on your gist. But I tried with the code I mentioned above and it seems to work fine:

``` scss
@function rem-calc( $size, $font-size : 14 ) {
  @return $size / ($font-size + 0px) * 1rem;
}

$drawer-padding: rem-calc(16px);
$drawer-profile-img: rem-calc(40px);
$drawer-profile-content-height: rem-calc(56px);
$drawer-profile-bottom-padding: rem-calc(8px);
$drawer-profile-height: $drawer-padding + $drawer-profile-img + $drawer-profile-content-height + $drawer-profile-bottom-padding;

.sc-drawer {
  &-temporary {
    .sc-drawer-header {
      height: $drawer-profile-height;
    }
  }
}
```
