### ISSUE TITLE
Treat CSS color functions with CSS variables inside as literals

### ISSUE THREAD

**Issue by AmeliaBR** [sass/sass#2175]
See this demo & tweet thread from Ana Tudor: https://twitter.com/anatudor/status/788787341854969856

The issue: Sass tries to parse `hsl()` and other color functions, instead of passing them to the browser.  A CSS variable call (`var(--value)`) inside that color function therefore causes a parse error in Sass/SCSS, despite being perfectly valid CSS.

There are work-arounds, using either string interpolation, or by using a `calc` function to wrap the variable call:

``` scss
    /* parse error *
    background: linear-gradient(
        hsl(var(--hue), 100%, 75%), 
        hsl(var(--hue), 100%, 25%));
    /**/
    /* works (string interpolation) */
    background: #{'linear-gradient(
        hsl(var(--hue), 100%, 75%), 
        hsl(var(--hue), 100%, 25%))'};
    /**/
    /* works (calc function wrapper) */
    background: linear-gradient(
        hsl(calc(var(--hue)), 100%, 75%), 
        hsl(calc(var(--hue)), 100%, 25%));
    /**/
```

But if `calc()` is recognized by Sass & causes the `hsl` function to be passed to the browser, it shouldn't be too hard to make `var()` do the same.
