### ISSUE TITLE
Immediate parent selector

### ISSUE THREAD

**Issue by shuber** [sass/sass#218]
Since nested `&` references are fully resolved, what do you think about creating a selector like `&&` which references the immediate parent selector?

``` scss
body.foo {
  color: #eee;

  .wrapper {
    width: 980px;

    #header && {
      padding: 0 10px;
      width: 960px;
    }
  }
}
```

``` css
body.foo { color: #eee; }
body.foo .wrapper { width: 980px; }
body.foo #header .wrapper { padding: 0 10px; width: 960px; }
```

**Comment by nex3** [comment]
I'm not convinced this is sufficiently useful. I don't think the cases where you really want it come up very often.

**Comment by parkr** [comment]
I've got a situation for you.

I am styling a webpage that holds a lot of quotes, but they need to be modified if they're contained in a certain parent element.

Instead of:

``` scss
p.left {
    blockquote {
        margin: 10px 20px;
    }
    div.block blockquote {
        margin: none;
    }
}
```

... I could have:

``` scss
p.left {
    blockquote {
        margin: 10px 20px;
        div.block && {
            margin: none;
        }
    }
}
```

Producing the output:

``` css
p.left blockquote { margin: 10px 20px; }
p.left div.block blockquote { margin: none; }
```
