### ISSUE TITLE
Wish a way to add namespace for child selectors.

### ISSUE THREAD

**Issue by zheeeng** [sass/sass#2191]
I have searched many articles and asked my friends, may there is no any perfect solution on adding scope and not pollute the ampersand in old scss file.  Look at the example below.

```scss
// in main.scss
.scope {
  @import 'list';
}

// in list.scss
.list { 
  &-item { color: red; }
  &:hover &-item { color: green; }
}

// output
.scope .list-item {
  color: red;
}
.scope .list:hover .scope .list-item {
  color: green;
}

// my wish:  Make the `@import` works like a real import. Not just works like include a mixin.
.scope .list-item {
  color: red;
}
.scope .list:hover .list-item {
  color: green;
}
```

A more common situation:
```scss
// ugly.css: written in old time
.boostrap {
  // not compatible with IE 9+
}

// amazing.scss: written in new age
.boostrap {
  // many new feature!
}

// main.scss

@import 'amazing.scss'; // if ugly.scss have the same selectors as amazing.scss.

// higher css selector weight, override the output of amazing.scss
body.lt-ie9 {
  @import 'ugly.scss';
}
```
