### ISSUE TITLE
CSS Grid `repeat()` function not working properly

### ISSUE THREAD

**Issue by jdsteinbach** [sass/sass#2208]
### Problem:

Sass attempts to evaluate `repeat()` (CSS Grid notation) as a Sass function & fails.

### Environments:

Per Sassmeister test, it fails in Ruby 4.0.0α, 3.4.21, 3.3.14, and Libsass 3.3.6: http://www.sassmeister.com/gist/7618bc7b7feba905f035fd0203bba185

### Example:

```scss
.grid {
  grid-template-columns: repeat(8, [col] 1fr);
}
```

### Error:

```
Invalid CSS after "...umns: repeat(8,": expected expression (e.g. 1px, bold), was "[col] 1fr );" on line 6 at column 35
```

### Hacky Workaround:

You can trick Sass into repeating the string instead trying to evaluate the function with:

```scss
.grid {
  grid-template-columns: unquote("repeat(8, [col] 1fr )");
}
```
