### ISSUE TITLE
Interpolation #{$x}00ms gobbles one 0?

### ISSUE THREAD

**Issue by asottile** [sass/sass#2209]
Bit by this after upgrading libsass (3.3.7 -> 3.4), though it appears they've simply made the behaviour there the same as sass.  Unclear if this is a bug or if it is intended, it certainly seems strange:

## Input scss

```scss
$x: 1;
a {
  b: #{$x}00ms;
}
```

## Output css

```css
a {
  b: 10ms;
}
```

## Expected

```css
a {
  b: 100ms;
}
```

## Workaround

obviously this scss is slightly silly, this is a working version:

```scss
$x: 1;
a {
  b: #{$x}#{'00ms'};
}
```

or the actually sane solution:

```scss
$x: 1;
a {
  b: $x * 100ms;
}
```
