### ISSUE TITLE
nesting properties properly

### ISSUE THREAD

**Issue by googol7** [sass/sass#2215]
I'd prefer to write padding, margin, border like this:

```
padding: {
   top, bottom: 12px;
   left, right: 24px;
}
```

or like this:
```
padding: {
   top, right: 2px;
   bottom: 4px;
}
```
so I don’t have to remember what the 1, 2, 3 or 4 numbers mean and also don’t have to enter them twice.

**Comment by angrybacon** [comment]
I think you really should be able to remember the order in which you have to provide the values. The only case which may or may not be natural is for 3 values. Even then, you can still use `padding-top/right/bottom/left`.

More generally, what you're looking for is a [`mixin`](http://sass-lang.com/guide#topic-6).

```scss
@mixin mypadding($top: null, $right: null, $bottom: null, $left: null) {
  @if $top {padding-top: $top;}
  @if $right {padding-right: $right;}
  @if $bottom {padding-bottom: $bottom;}
  @if $left {padding-left: $left;}
}
```

Then use it with named parameters (or not).

```scss
.element {
  @include mypadding(0, 15px, 0, 15px);
  @include mypadding($left: 15px, $right: 15px);
}
```

Keep in mind that this mixin is incomplete as you cannot really skip values if they are not named.

Play around with it on http://www.sassmeister.com/ and see if you can make a mixin that is closer to what you're asking (have values apply to several properties like left and right at once).
