### ISSUE TITLE
a nested @import with an @if inside removes the nesting

### ISSUE THREAD

**Issue by wardpeet** [sass/sass#2219]
Whenever you nest an @import and have @if in the root of the file it will lose its nesting.

index.scss
```scss
.nested {
  @import 'nesting';
}
```
_nesting.scss
```scss
@if true {
  .selector {
      color: #fff
  }
}
```

results into
```css
.selector {
color: #fff;
}
```

This works though
```scss
& {
@if true {
  .selector {
      color: #fff
  }
}
}
```

**Comment by nex3** [comment]
Ruby Sass is on the path to deprecation, so we aren't working on purely-cosmetic issues. I'm marking this as "on ice" so that if we get a maintainer, they can revive it.

**Comment by xzyfer** [comment]
@nex3 is this purely-cosmetic? Looks like it changes the semantics of the output CSS

```css
.nested {
  .selector {
    color: #fff;
  }
}
```
vs
```css
.selector {
  color: #fff;
}
```
