### ISSUE TITLE
sass-convert bug with $important variable when converting from .sass to .scss

### ISSUE THREAD

**Issue by bzerangue** [sass/sass#222]
Hello. I'm running Sass 3.1.11 (Brainy Betty).

When I run a sass-convert --from sass to --scss...

It converts the $important variable to !important... 

Here's the .sass markup that I want converted (to scss)

``` sass
@mixin font-size($size, $important: false)
  @if $important
    font-size: $size + px !important
    font-size: ($size / 10) + rem !important
  @else
    font-size: $size + px 
    font-size: ($size / 10) + rem
```

Here's what happens when I run the sass-convert command:  `sass-convert -R templates/project/sass --from sass --to scss`...

``` scss
@mixin font-size($size, !important: false) {
  @if !important {
    font-size: $size + px !important;
    font-size: $size / 10 + rem !important; }
  @else {
    font-size: $size + px;
    font-size: $size / 10 + rem; } }
```

It converts the `$important` variable to `!important`
