### ISSUE TITLE
Using a @for loop within a mixin and calling that mixin twice affects output in undesired ways

### ISSUE THREAD

**Issue by jwandrews** [sass/sass#2220]
I've encountered a bug it seems where consecutive calls to a mixin using a `@for` loop is outputting the same CSS selector chain when it is expected to output the intended limit for the selectors.

Is this a limitation of the language and how it compiles loops? ie async vs sync running of @for loops?

Would a Sass function be better suited for this than a mixin?

Any insight helps.

### Source
```scss
// ----
// Sass (v3.4.21)
// Compass (v1.0.3)
// ----

$base: (
  spacing: 16px
);

@mixin headings($from: 1, $to: 6) {
  %base-heading {
    @content;
  }
  
  @if $from >= 1 and $to <= 6 {
    @for $i from $from through $to {
      h#{$i} {
        @extend %base-heading;
      }
    }
  }
}

@include headings(1, 3) {
  margin-bottom: map-get($base, spacing) / 2;
}

@include headings(4, 6) {
  margin-bottom: map-get($base, spacing) / 4;
}
```

### Expected Output
```css
h1, h2, h3 {
  margin-bottom: 8px;
}

h4, h5, h6 {
  margin-bottom: 4px;
}
```

### Actual Output
```css
h1, h2, h3, h4, h5, h6 {
  margin-bottom: 8px;
}

h1, h2, h3, h4, h5, h6 {
  margin-bottom: 4px;
}
```

Here is a link to a Sassmeister example.
[Link to Sassmeister](http://www.sassmeister.com/gist/5633b2047ab68e6c3e968904d50e3a35)

**Comment by nex3** [comment]
The issue is that you're extending the same selector, `%base-heading`, from all of the h# rules you're generating. Your code is equivalent to:

```scss
$base: (spacing: 16px);

%base-heading {margin-bottom: map-get($base, spacing) / 2}

h1 {@extend %base-heading}
h2 {@extend %base-heading}
h3 {@extend %base-heading}

%base-heading {margin-bottom: map-get($base, spacing) / 4}

h4 {@extend %base-heading}
h5 {@extend %base-heading}
h6 {@extend %base-heading}
```

You could use the `unique-id()` function to generate a unique placeholder selector for each mixin invocation, but it would probably be simpler to just create a selector full of h# tags directly:

```scss
@mixin headings($from: 1, $to: 6) {
  $selector: ();
  @for $i from $from through $to {
    $selector: append($selector, "h#{$i}", comma);
  }

  #{$selector} {
    @content;
  }
}
```
