### ISSUE TITLE
Error caused by repeat function in CSS Grid module  

### ISSUE THREAD

**Issue by jakob-e** [sass/sass#2233]
I'm not sure if this has been fixed – sorry in advance.
The CSS Grid `repeat` function breaks when switching from CSS to SCSS
````SCSS
.container{
  grid-template-columns: repeat(3, 20px [col-start]) 5%;
} 
````
Errors thrown: 

**Libsass 3.4.3** 
Error: Invalid CSS after "... repeat(3, 20px": expected expression (e.g. 1px, bold), was "[col-start]) 5%;"

**Ruby 3.4.23**
Error: Invalid CSS after "...repeat(3, 20px ": expected ")", was "[col-start]) 5%;"

Ref: https://css-tricks.com/snippets/css/complete-guide-grid/
