### ISSUE TITLE
@extend issue with extending child selectors

### ISSUE THREAD

**Issue by CupOfTea696** [sass/sass#2239]
I found a bug in the `@extend` directive, it occurs when extending a child selector of a selector that has children. Below is a simple code example to illustrate the issue.

### Example
```scss
%margin-policy {
  color: red;
  
  &:first-child {
    margin-top: 0;
  }
  
  &:last-child {
    margin-bottom: 0;
  }
}

h1 {
  margin: 36px 0;
  @extend %margin-policy;
}

.component {
  h1 {
    margin: 8px 0;
    @extend %margin-policy;
  }
}
```

### Expected result:
```css
h1, .component h1 {
  color: red;
}
h1:first-child, .component h1:first-child {
  margin-top: 0;
}
h1:last-child, .component h1:last-child {
  margin-bottom: 0;
}

h1 {
  margin: 36px 0;
}

.component h1 {
  margin: 8px 0;
}
```

### Actual result:
```css
h1, .component h1 {
  color: red;
}
/* Missing `.component h1:first-child` */
h1:first-child {
  margin-top: 0;
}
/* Missing `.component h1:last-child` */
h1:last-child {
  margin-bottom: 0;
}

h1 {
  margin: 36px 0;
}

.component h1 {
  margin: 8px 0;
}
```
