### ISSUE TITLE
Why is this simple @extend rule generating longer selectors than expected

### ISSUE THREAD

**Issue by wheresrhys** [sass/sass#224]
``` scss
.media .carousel-wrap img {
  @extend .banner-dimensions;
}

.xlarge .banner-dimensions {
  width: 1490px;
  height: 365px;
}
```

generates

``` css
.xlarge .banner-dimensions, 
.xlarge .media .carousel-wrap img, 
.media .carousel-wrap .xlarge img {
  height: 365px;
  width: 1490px;
}
```

where the third selector isn't needed. I would expect this behaviour if I was using 

``` scss
.media .carousel-wrap {
  img {
    @extend .banner-dimensions;
  }
}
```

but not when using a single string, un-nested selector.

I'm using v3.1.11 (and it was also happening in 3.1.7)
