### ISSUE TITLE
Question: function and space

### ISSUE THREAD

**Issue by alexander-akait** [sass/sass#2244]
I have code
```scss
a {
    background: url ("../../containers/app/images/select2-spinner.gif");
                // ^ Space here
}
```
After compilation i have
```css
a {
    background: url("../../containers/app/images/select2-spinner.gif");
}
```
This is normal behavior or bug?
