### ISSUE TITLE
Extending placeholder selector with nested selector with &-suffix doesn't work

### ISSUE THREAD

**Issue by pepa-linha** [sass/sass#2262]
When using this placeholder selector (compare with mixin - https://gist.github.com/pepa-linha/43ffbce8e60d96e04c7bbe3d22923169)

```sass
%component {
  background: red;
  &-sub {
    background: orange;
  }
}

.Component {
    @extend %component;
}
```

I get this output

```css
.Component {
    background: red;
}
```

but I would expect this output

```css
.Component {
    background: red;
}

/* This selector is missing */
.Component-sub {
    background: orange;
}
```

**Comment by chriseppstein** [comment]
You're expectation is incorrect. Placeholders are a kind of selector and they work exactly like classes. You defined two different placeholders and you only extended one of them.

Mixins may work better for you in this case, or you'll need to extend both placeholders:

```scss
.Component {
    @extend %component;
    &-sub { @extend %component-sub; }
}
```

Alternatively, if you used two classes this would work fine:

```scss
%component {
  background: red;
  &.sub {
    background: orange;
  }
}

.Component {
    @extend %component;
}
```

And then of course your markup would need to use `class="Component sub"` instead of `class="Component-sub"`.
