### ISSUE TITLE
scope of function and mixin definitions

### ISSUE THREAD

**Issue by yoannisj** [sass/sass#2268]
When defining a mixin or function inside a ruleset or inside an `@`-directive, the mixin/function can only be invoked inside that ruleset/directive. As such, the following throws an error:

`````scss
@media print
{
    @mixin float($side) {
      float: unquote($side);
    }

    .pull-right {
      @include float('right'); // float: right;
    }
}

.pull-left {
  @include float('left'); // throws 'no mixin named float' error
}
`````

I would agree that you shouldn't define functions/mixins inside rulesets or directives anyway, but I than I ran into a use-case where this can happen undeliberatly when using `@import` and the very useful custom importer [node-sass-import-once](https://github.com/at-import/node-sass-import-once).

I use `node-sass-import-once` to organize my sass mixins and modules in separate files, and make sure dependencies are always loaded correctly (without needing to know which modules depend on which mixins in the main sass file).

**in "main.scss" entry file:**
`````scss
@media print {
  @import "modules/bar";
}

@import "modules/foo"
``````

**in "modules/_bar.scss" partial file**
`````scss
@import "mixins/float"; // imports the mixin in the scope of the `@media` directive

.bar {
  @include float('right');
}
`````

**in "modules/_foo.scss" partial file**
`````scss
@import "mixins/float"; // doesn't get re-imported by `node-sass-import-once`

.foo {
  @include float('left'); // throws 'no mixin named float' error
}
`````

Shouldn't mixins and functions always be defined globally, and accessible as long as they are imported in the compiled stylesheet?

**PS**: Importing the mixin/function definition files inside an `@at-root` directive doesn't help, and still throws the same error:

`````scss
@at-root (without:all) {
  @import "mixins/float";
}
``````

**Comment by yoannisj** [comment]
The current implementation seems to actually scope `@mixin` and `@function` exactly like variable declarations, and uses the same shadowing. This allows to re-define a mixin inside a given scope:

`````scss
@mixin float($side) {
  float: unquote($side);
}

@page
{
    @mixin float($side) {
      float: unquote($side) !important;
    }

    .pull-right {
      @include float('right'); // float: right !important;
    }
}

.pull-left {
  @include float('left'); // float: left;
}
`````

I suspect this to be the reason for the current behaviour, but I can't think of any use-case justifying it, as you can easily define an alternative version of the mixin, or use some arguments to control the mixin's output.

Or is this a bug?
