### ISSUE TITLE
Formatting numbers during interpolation

### ISSUE THREAD

**Issue by compwright** [sass/sass#2270]
The following snippet:

```scss
$n: 0;
@while $n <= 10 {
    .cls-#{n} { /* ... */ }
    $n: $n + 1;
}
```

Produces a list of classes like:

```css
.cls-0 {}
.cls-1 {}
.cls-2 {}
...
.cls-10 {}
```

Is there any way to zero-pad the numeric interpolation such that the list of classes have a consistent number of digits like this?

```css
.cls-00 {}
.cls-01 {}
.cls-02 {}
...
.cls-10 {}
```
