### ISSUE TITLE
Why does the mixin function not support nesting?

### ISSUE THREAD

**Issue by annder** [sass/sass#2274]
In the less，we can write this code :

```less
.a(){
.b (){
color:red
}
}
.c {
.a;
}
```
But sass why can not this write?

And scss version 3.4.23

**Comment by annder** [comment]
Less code  corrected to:

```less
.a(){
.b (){
color:red
}
.b;
}
.c {
.a;
}
```
