### ISSUE TITLE
Unexpected extend side-effects

### ISSUE THREAD

**Issue by alexbowers** [sass/sass#2276]
We are getting unexpected `:not` extends in sass

Here is a quick reproduction piece of code:

```scss
.btn-default {
  color: red;
}

li {
  display: inline-block;
  float: none;
  a:not(.btn-default) {
    padding: 10px;
  }
}

.input-group-addon {
  @extend .btn-default;
}
```

that is producing this:

```css
.btn-default, .input-group-addon {
  color: red;
}

li {
  display: inline-block;
  float: none;
}
li a:not(.btn-default):not(.input-group-addon) {
  padding: 10px;
}
```

To me, I wouldn't (and am not), expecting the additional `:not(.input-group-addon)` to be applied.

That is creating a line of CSS that does not apply what I would expect it to.
