### ISSUE TITLE
Storing Ampersand Bug in Sass 3.4

### ISSUE THREAD

**Issue by ChurnM4c** [sass/sass#2278]
Hi

I found a bug of the `&` in the current Sass implementation as you can see on this [codepen](https://codepen.io/claudiobmgrtnr/pen/JNRRxm)

SCSS Code
```css
@mixin test1() {
  html body & {
     @content;
  }
}

@mixin test2() {
  #{&} {
    @content;
  }
  
  & {
    @content;
  }
}

.demo {
  @include test1() {
    @include test2() {
      background: orange;
    }
  }
}
```

Generates the following CSS code:

```css
html body .demo html body .demo {
  background: orange;
}
html body .demo {
  background: orange;
}
```

Behaviour:

As you can see the selector is added twice for `#{&}` which causes issues when storing ampersand in a variable.

Expected behavior: 

`#{&}` === `&`

Is this a known bug?
