### ISSUE TITLE
Run user defined functions inside maps

### ISSUE THREAD

**Issue by lodybo** [sass/sass#2328]
I'd like to maintain the colors in my projects in two separate maps:
* a `$brand-colors` map containing all the brand colors
* a `$color-scheme` map containing all the UI elements with their colors

I then write a `color($color-name)` function, where `$color-name` is the name of a color in (usually) the `$color-scheme` map. To keep it DRY, I want to reference brand colors in the `$color-scheme` map directly from the `$brand-colors` map:

````scss
$brand-colors: (
  "primary":    rgb(0,138,201),
  "secondary":  rgb(0,81,145),
  "tertiary":   rgb(26,23,27)
);

$color-scheme: (
  "header": map-get($brand-colors, 'secondary')
);
````

The `color()` function gets called with a `$color-name`, which will try to find it in the `$color-scheme` map. If found, it will return it, and else it will throw an error:

````scss
@function color($color) {
  @if(map-has-key($color-scheme, $color)) {
    @return map-get($color-scheme, $color);
  } @else {
    // Error handling
  }
}
````
Which can be used like this in my code:
````css
p {
  color: color('header');
}
````

What I'd like to do is get rid of the `map-get()` call inside my `$color-scheme` map, because it is more verbose than calling my user defined function, and I can gracefully handle errors in it.

What I'd like to do is this:
````scss
$color-scheme: (
  "header": color('secondary')
);

@function color($color) {
  @if(map-has-key($color-scheme, $color)) {
    @return map-get($color-scheme, $color);
  } @else if(map-has-key($brand-colors, $color)) {
    @return map-get($brand-colors, $color);
  } @else {
    @return unquote("red");
  }
}

p {
  color: color('header');
}
````
But if I do this, the styles that will be applied will be:
````css
p {
  color: color("secondary");
}
````

I made a [SassMeister gist](https://www.sassmeister.com/gist/e9620e59f5655c5e5f897c432d9ea14a) to illustrate this.
