### ISSUE TITLE
In webpack2, use @import load scss file.img path error.

### ISSUE THREAD

**Issue by h330894169** [sass/sass#2346]
eg:

```
a/
  a.scss
  a.png
b/
  b.scss
```

a.scss  code like:

```scss
 div{
    background-image: url('./a.png');
 }
```

b.scss

```scss
   @import '../a/a.scss'
```

webpack build error,   
Can't resolve './a.png' in 'b'

How to solve in webpack2?
