### ISSUE TITLE
Anchor in parent selector for nested selectors insertion

### ISSUE THREAD

**Issue by nazar-pc** [sass/sass#2354]
This is a more generic feature that will resolve #xxx very nicely.
The idea is that following:
```scss
::slotted(button&) {
    color: red;

    &:active {
        color: blue;

        img {
            border: none;
        }

        :host([strict]) & {
            color: black;
        }
    }

    &:hover& { // Keep insertion anchor
        color: pink;

        &[type=submit] {
            cursor: crosshair;
        }
    }
}
```
Compiles to:
```css
::slotted(button) {
    color: red;
}
::slotted(button:active) {
    color: blue;
}
::slotted(button:active) img { /* Not valid, just to give an idea how syntax works */
    border: none;
}
:host([strict]) ::slotted(button:active) {
    color: black;
}
::slotted(button:hover) {
    color: pink;
}
::slotted(button[type=submit]:hover) {
    cursor: crosshair;
}
```

Essentially when nesting selectors are referencing parent selectors, they are essentially inserted somewhere in the middle, not at the end or at the start which are both currently supported.

Limitations:
* this should only work for `&whaever`, not for `& whatever` and `whatever &` (otherwise it seems to cause more harm that good)
* should only have effect for direct children when used
