### ISSUE TITLE
Extending Variables

### ISSUE THREAD

**Issue by natewiebe13** [sass/sass#2355]
## Problem
When building a theme/framework, setting the value of a variable to another variable, then later updating the parent doesn't update the child. Gist to help illustrate: https://www.sassmeister.com/gist/4f254deaa001bf9a020b57f683854164

## What Happens
It appears that the value of the parent variable is set to the child, instead of a reference to the parent variable.

## Possible Solution
Keep the reference to the parent variable, and return the value of the parent. If the value of the parent variable is changed after it's already called, it should not update previous usages.

**Comment by ArmorDarks** [comment]
You can replace `$button-padding` with a function `button-padding()`. That way it will recalculate value each time you invoke it.

```scss
// Theme
$global-padding: 10px !default;

@function button-padding() {
  @return $global-padding
}

// Project
$global-padding: 20px;

a {
  padding: button-padding(); // 20px
}
```

I don't think that will ever change, since it's just how most languages works — primitives are immutable, they aren't references, and thus you can not change them with simple reassignment and expect further instances of that variable to change.

For that purpose already exists functions, which can be invoked anytime to recalculate value. They are sort of an extend, you're asking for.
