### ISSUE TITLE
SASS Timeout during compiling - CentOS 6/Cloudlinux 6.9

### ISSUE THREAD

**Issue by MB-Jan** [sass/sass#2360]
Hi there,

We love Sass and we think we found a bug. We are able to recreate a situation where Sass does not respond until the process is manually killed. When it is processing a process with application Ruby is using 100% of the CPU usage.

We used the following two commands for testing and believe instead of timing out, Sass should respond with an error:
1. `sass --update path_to_sass_dir`
2. `sass path_to_scss_file`

The issue happens when the following Sass code is present:

```scss
body {
	&.en {
		.mm-page {
			font-family: 'MyFont', sans-serif;
			font-size: 14px;
			font-weight: 300;
			h1 {
				@extend .mm-page;
				font-size: 32px;
				text-transform: uppercase;
			}
			h2 {
				@extend .mm-page;
				font-size: 24px;
				text-transform: uppercase;
				font-weight: 400;
			}
			h3 {
				@extend .mm-page;
				font-size: 18px;
				text-transform: uppercase;
			}
			h4 {
				@extend .mm-page;
				font-size: 18px;
				text-transform: none;
			}
			h5 {
				@extend .mm-page;
				font-size: 14px;
				text-transform: uppercase;
			}
			h6 {
				@extend .mm-page;
				font-size: 10px;
				text-transform: uppercase;
				font-weight: 700;
			}
			p {
				@extend .mm-page;
				font-size: 12px;
				font-weight: 300;
			}
			a, span {
				@extend p;
			}
			strong, b {
				@extend p;
				font-weight: 700;
			}
		}
	}
	&.th {
		*:not(.lnr) {
			font-family: 'MyFont', sans-serif;
			font-size: 14px;
		}
	}
}
```

We can confirm that the `@extend` commands are causing this issue, but again we believe instead of just running indefinitely, Sass should return an error. 

We use Sass 3.5.1 (Bleeding Edge) with ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux] on CloudLinux Server release 6.9 (Igor Volk)

Please let me know if you need to know anything else.

Thank you.

- Jan
