### ISSUE TITLE
Sass compilation error when reading the src property within mixin

### ISSUE THREAD

**Issue by magwalk** [sass/sass#2364]
Hi there! 

I am creating a mixin to change the font path in my @font-face declarations depending on the environment that our SCSS is being used in. My code for the mixin is as follows:

```scss
@mixin chs-font-src($env, $path) {
  @if $env == 'middleman' {
    src: url("#{$path}") format('woff'),
         url("#{$path}") format('truetype');
  } @else if $env == 'hanami' {
    src: url("assets/fonts/#{$path}.woff")) format('woff'),
         url("assets/fonts/#{$path}.ttf")) format('truetype');
  }
}
```

But I get this error:

```Invalid CSS after "...#{$path}.woff")": expected ";", was ") format('woff'),"```

It seems like Sass doesn't know the format that is allowed within the src property when it is reading a mixin. To be clear, this is the src property in an @font-face declaration (not related to the src property on an image, for example). A working example of an @font-face declaration is here: 

```css
@font-face {
  font-family: 'Muli';
  src: url('muli/muli.woff') format('woff'),
       url('muli/muli.ttf') format('truetype');
  font-weight: 400;
  font-style: normal;
}
```

**Comment by nex3** [comment]
You've got extra `)`s after your `url()`s in the second clause. This should work:

```scss
@mixin chs-font-src($env, $path) {
  @if $env == 'middleman' {
    src: url($path) format('woff'),
         url("$path) format('truetype');
  } @else if $env == 'hanami' {
    src: url("assets/fonts/#{$path}.woff") format('woff'),
         url("assets/fonts/#{$path}.ttf") format('truetype');
  }
}
```

(I've also changed `url("#{$path}")` to `url($path)`; the extra quotes there aren't necessary)
