### ISSUE TITLE
Unable to use operator on join when single value

### ISSUE THREAD

**Issue by gunnx** [sass/sass#2369]
**Version: Sass v3.4.21**

## SCSS
```css
.foo {
  margin: 2 * join((), 0.5rem);
}
```

## Expected
```css
.foo {
  margin: 1rem;
}
```

## Actual
`Undefined operation: "2 times 1rem".`
