### ISSUE TITLE
A case that @extend doesn't work correctly

### ISSUE THREAD

**Issue by neeg2** [sass/sass#2372]
Hi,
I have a case that @extend doesn't work correctly.

example:
There is .blackString css class and trying to create new .redString class by @extend.

### SCSS
````scss
.redString{
  @extend .blackString;
  color: red;
}

.blackString{
  color: black;
}
````
### compiled CSS
````css
.redString {
  color: red;
}

.blackString, .redString {
  color: black;         // redString would be BLACK.
}
````
redString would be black.

Of course, I know the reason and it's understandable.
But I think that it need be considered that this behavior is properly or not, as purpose of SCSS.
At least, some( error, warning and so on) messages would be helpful for users.

Please consider this issue.

Thank you.
