### ISSUE TITLE
compile error: percent after interpolation

### ISSUE THREAD

**Issue by fvignals** [sass/sass#2375]
sass-4.2.0:
bug:
```scss
$pcs: map-get($settings, "percent");
@each $pc in $pcs {
  .w-#{$pc}pc {
    width: #{$pc}%
  }
}
```
work well:
```scss
@each $pc in $pcs {
  .w-#{$pc}pc {
    width: #{$pc}px or any other css units
  }
}
```
Error: `Invalid CSS after \"...width: (#{$pc}%\": expected expression (e.g. 1px, bold), was \")\"\A   `

**Comment by vladislav251990** [comment]
If you still need percents
`$settings:(percent:5);`
`$pcs: map-get($settings, 'percent');`
`@each $pc in $pcs {`
`  .w-#{$pc}pc {`
`    width:percentage($pc/100);`
`  }`
`}`

**Comment by fvignals** [comment]
Thx so much, I tried lot of things but I forgot function.
So, for next readers: 
```scss
$settings: ( percent: (10, 20, 25, 50, 75, 80, 100) ); 
$pcs: map-get($settings, "percent");
@each $pc in $pcs {
  .w-#{$pc}pc {
    width: percentage($pc/100);
  }
}
```
output:
```css
.h-10pc { height: 10%; }
.h-100pc { height: 100%; }
```

**Comment by RdeWilde** [comment]
Would be nice to get fixed, ugly workaround.

**Comment by nex3** [comment]
This isn't a bug; it's never a good idea to use interpolation to add units to numbers, so we don't want to make it easier in this case.

**Comment by fvignals** [comment]
I agree with nex3 but : this rule should work for all css units. 
Functions px, vw, rem, em don't exists ... so interpolation is the only solution. And the absolute way was to calculate with numbers then convert them to string and add the units ... boring. 
But for me not important or urgent. 

> The easiest rule is the best.

**Comment by fvignals** [comment]
I wrote : .h-10pc { height: 10%; } and not .h-100%{ ... }

**Comment by mirisuzanne** [comment]
You can add any units to a number with multiplication. Make that generic with map of units-to-multiplier, named however you like:

```scss
$units: (
  px: 1px,
  em: 1em,
  pc: 1%,
  rem: 1rem,
);

$settings: ( 
  pc: (10, 20, 25, 50, 75, 80, 100),
  rem: (1, 1.5, 2, 4, 8), 
);

@each $unit, $set in $settings {
  @each $val in $set  {
    .w-#{$val}#{$unit} {
      width: $val * map-get($units, $unit);
    }
  }
} 
```
