### ISSUE TITLE
Something went wrong in mixin

### ISSUE THREAD

**Issue by vladislav251990** [sass/sass#2376]
I have mixin and I use it in code below.
```scss
@mixin tableMixin($classTable, $nTable, $i, $prefix){
    #{$classTable}.table2>li:nth-child(#{$i}) {
        background: transparent url('images/#{$prefix}#{$i}.png') no-repeat center center;
        background-size: contain;
        @if ($i == 1 and $prefix == d) or ($i == 2 and $prefix != d){
            width: 6vw;
        }
    }
}
.inCellTable {
    list-style-type: none;
    >li {
        display: inline-block;
        width: 4vw;
        height: 4vw;
        margin: 0 0.5vw;
        @for $i from 1 through 3{
            &:nth-child(#{$i}) {
                background: transparent url('images/q#{$i}.png') no-repeat center center;
                background-size: contain;
            }
        }
    }
    $prefixes:(t, ag ,d);
    $thisTable:&;
    @for $i from 1 through 2{
        @for $j from 2 through 4{
            @include tableMixin($thisTable, $j, $i, nth($prefixes,$j - 1))
        }
    }
}
```

I got unexpectable two times class .inCellTable adding after compiling CSS but one time expected. Why?
```css
//right CSS
//.....

//wrong CSS below
.inCellTable .inCellTable.table2 > li:nth-child(1) {
  background: transparent url("images/t1.png") no-repeat center center;
  background-size: contain;
}
.inCellTable .inCellTable.table2 > li:nth-child(1) {
  background: transparent url("images/ag1.png") no-repeat center center;
  background-size: contain;
}
// and other
```
