### ISSUE TITLE
SASS should remove unneccesary * selectors

### ISSUE THREAD

**Issue by CupOfTea696** [sass/sass#2380]
I'm just gonna illustrate this with an example because I think that'd make more sense.

**SCSS:**
```scss
#container > * {
  margin: 32px 0;
  
  &:first-child {
    margin-top: 0;
  }
  
  &:last-child {
    margin-bottom: 0;
  }
}
```

**Expected/Desired Result:**
```css
#container > * {
  margin: 32px 0;
}
#container > :first-child {
  margin-top: 0;
}
#container > :last-child {
  margin-bottom: 0;
}
```

**Actual Result:**
```css
#container > * {
  margin: 32px 0;
}
#container > *:first-child {
  margin-top: 0;
}
#container > *:last-child {
  margin-bottom: 0;
}
```
