### ISSUE TITLE
sass compile bug

### ISSUE THREAD

**Issue by omreal** [sass/sass#2391]
this sass file:
```sass
$background-color: #998BE0

.form-field
  border: $border-color 1px solid
  border-radius: 2px
  width: 200px
  height: 25px
  background-color: $background-color

  .form-field:active
  background-color: $background-color
```

compiles to:
```css
.form-field { border: #1B1632 1px solid; border-radius: 2px; width: 200px; height: 25px; background-color: #998BE0; background-color: #44387F; }
```

why don't create  `.form-field:active`?  how to fix it?
