### ISSUE TITLE
Missing ability to break parent selector chain for ampersand

### ISSUE THREAD

**Issue by aczekajski** [sass/sass#2401]
I am using some external `scss` file. Let's assume I want to isolate the external styles to work only for elements that are wrapped in some additional element. In effect, I end up with
```scss
.my-wrapper {
  @import "external";
}
```
In general this works ok, until trailing ampersand selector happens to be used in external styles. We then end up with a structure like this:
```scss
.my-wrapper {
  .external-children {
    .external-parent & {
      color: red;
    }
  }
}
```
which in turn gets compiled to this:
```css
.external-parent .my-wrapper .external-children {
  color: red;
}
```
while in fact I wanted to achieve this:
```css
.my-wrapper .external-parent .external-children {
  color: red;
}
```

Of course current behavior is correct, but it seems that currently there is no way to achieve what I wanted without editing `external.scss`. I tried experimenting with `@at-root` but it removes `.my-wrapper` completely from the selector chain. A directive similar to `@at-root` might be needed to do that. So I can type something like this:
```scss
.my-wrapper {
  @reset-parent {
    .external-children {
      .external-parent & {
        color: red;
      }
    }
  }
}
```
which will cause `&` to not see the part of parent selector that happened before `@reset-parent` but still be output as style inside the wrapper.
