### ISSUE TITLE
Expand selectors from list variables

### ISSUE THREAD

**Issue by ygoe** [sass/sass#2420]
Consider the following selectors to match all text-link input fields. There are alternative ways to write this but all of them require multiple alternatives.

```css
input:not([type]),
input[type=text],
input[type=number],
input[type=email]
{
    background: yellow;
}
```

And there's more input types that this.

Now when these items appear in another element, or in several other situations, all of these selectors must be repeated.

```css
form
{
    input:not([type]).error,
    input[type=text].error,
    input[type=number].error,
    input[type=email].error
    {
        background: orange;
    }
}
```

I'd like to have a way to define these selectors in a list and use them in multiple places.

```css
$textInputs: input:not([type]), input[type=text], input[type=number], input[type=email];

$textInputs
{
    background: yellow;
}

form
{
    $textInputs.error
    {
        background: orange;
    }
}
```

That would compile to:

```css
input:not([type]),
input[type=text],
input[type=number],
input[type=email]
{
    background: yellow;
}

form input:not([type]).error,
form input[type=text].error,
form input[type=number].error,
form input[type=email].error
{
    background: orange;
}
```

So if the variable contains more than one selector, all selectors that use the variable need to expand to _n_ resulting selectors. When using multiple variables in one selector expression, this works comparable with nested foreach loops, one for each variable.

Maybe the specific samples here can be written simpler, but there are scenarios where they cannot be simplified and need to be repeated all the time. And since HTML has such an unlogical structure and CSS doesn't provide a single selector for this type of elements, somebody else must do it. Right now, it's the programmer. Programmers use tools to do their work, so it should be Sass instead.

**Comment by nex3** [comment]
You can write your example using interpolation like this:

```scss
$textInputs: "input:not([type]), input[type=text], input[type=number], input[type=email]";

#{$textInputs} {
  background: yellow;
}

form {
  #{$textInputs} {
    &.error {
        background: orange;
    }
  }
}
```

You can also use selector functions like [`selector-nest()`](http://sass-lang.com/documentation/Sass/Script/Functions.html#selector_nest-instance_method) to do complex operations on selector strings:

```scss
$textInputs: "input:not([type]), input[type=text], input[type=number], input[type=email]";

#{$textInputs} {
  background: yellow;
}

form {
  #{selector-nest($textInputs, "&.error")} {
    background: orange;
  }
}
```
