### ISSUE TITLE
extend fails

### ISSUE THREAD

**Issue by ygoe** [sass/sass#2421]
This is my SCSS code:

```css
.field .input-container
{
	display: block;
	width: 100%;
}

input[type^=date],
input[type=email],
input[type=month],
input[type=number],
input[type=password],
input[type=search],
input[type=tel],
input[type=text],
input[type=time],
input[type=url],
input[type=week],
textarea
{
	&::placeholder
	{
		font-style: italic;
	}
	.field &
	{
		@extend .field .input-container;
	}
}
```

This gives me the error in the line where `@extend` occurs. Other extends work fine. I have no idea what this error wants to tell me.

```
Can't extend .field .input-container: can't extend nested selectors

Backtrace:
	wwwroot/css/_form.scss:125
```

I'm using the [Web Compiler](https://github.com/madskristensen/WebCompiler) extension for Visual Studio. Where is the bug, in the SCSS language, in something from this site used in the other tool, or in the Web Compiler extension?
