### ISSUE TITLE
@viewport nested inside selector produces unexpected CSS

### ISSUE THREAD

**Issue by eternoendless** [sass/sass#2428]
I have the following SCSS:
```scss
.bootstrap {
  @-ms-viewport {
    width: device-width;
  }
}
```

I would expect it to produce:
```css
.bootstrap @-ms-viewport {
  width: device-width;
}
```

But instead, it produces:
```css
@-ms-viewport {
  .bootstrap {
    width: device-width;
  }
}
```
