### ISSUE TITLE
[Bug] @font-face accidental prefixing

### ISSUE THREAD

**Issue by deleonio** [sass/sass#2442]
Before
```sass
.class-selector
  @font-face
    font-family: 'icons'

  @keyframes inv-ajax-loader-spin
    0%
      transform: scale(1) rotate(0deg)

    50%
      transform: scale(1.2) rotate(180deg)

    100%
      transform: scale(1) rotate(360deg)
```

After
```css
@font-face {
  .class-selector {
    font-family: "icons"; } }
@keyframes inv-ajax-loader-spin {
  0% {
    transform: scale(1) rotate(0deg); }
  50% {
    transform: scale(1.2) rotate(180deg); }
  100% {
    transform: scale(1) rotate(360deg); } }

/*# sourceMappingURL=icons.css.map */
```

Correct
```css
@font-face {
    font-family: "icons"; } 
@keyframes inv-ajax-loader-spin {
  0% {
    transform: scale(1) rotate(0deg); }
  50% {
    transform: scale(1.2) rotate(180deg); }
  100% {
    transform: scale(1) rotate(360deg); } }

/*# sourceMappingURL=icons.css.map */
```

**Comment by nex3** [comment]
This is the intended behavior. As a rule, Sass includes as little knowledge as possible about the specific semantics of CSS like property names and at-rules, so that it doesn't have to constantly update to follow the spec. This includes knowledge of what at-rules can contain what types of content. Sass doesn't know that `@font-face` can't contain selectors, so when it's nested within a selector it falls back on the default behavior of bubbling it up (the same way it does for a `@media` rule).

The reason `@keyframes` works differently here is that its contents aren't parsed like anything else in CSS, so Sass *has* to know what `@keyframes` means in order to support it.

**Comment by deleonio** [comment]
Compare with less (https://lesstester.com)

```less
.class-selector{
  @font-face{
    font-family: 'icons'}
  

  .kjh{
    display : none
  }}
```

After

```css
@font-face {
  font-family: 'icons';
}
.class-selector .kjh {
  display: none;
}
```
