### ISSUE TITLE
& in placeholder not working

### ISSUE THREAD

**Issue by timkraut** [sass/sass#2445]
Hi there,

I've just found an issue (not sure it it's a bug or a known limitation) with the `&` selector in a placeholder. The following code shows the issue:

```scss
%some-placeholder {
  color: blue; // Sass doesn't compile if no rules are defined here
  
  &--some-modifier {
    color: green;
  }
}

.some-class {
  @extend %some-placeholder;
}
```

See https://codepen.io/timkraut/pen/YYLZLV?editors=1100 for a live example.

The compiled CSS is:

```css
.some-class {
  color: blue;
}
```

I would have expected to see the following result:

```css
.some-class {
  color: blue;
}

.some-class--some-modifier {
  color: green;
}
```
