### ISSUE TITLE
scss compression bug

### ISSUE THREAD

**Issue by RobinClowers** [sass/sass#245]
Leading commas in scss files will cause spaces to be incorrectly removed from selectors.

This scss:

``` css
li.some_class a
, li.some_class a {
padding-left: 24px;
}
```

will incorrectly produce this when compiled with the compressed option:

``` css
li.some_classa ,li.some_class a{padding-left:24px}
```
