### ISSUE TITLE
Unify pseudo-elements with equivalent pseudo-class syntax

### ISSUE THREAD

**Issue by mgreter** [sass/sass#2454]
There is IMO a small edge case not correctly handled in Sass:

```scss
%a, %a::after {a: b}
a:after {@extend %a}

%b, %b:before {a: b}
a::before {@extend %b}

%c, %c::first-line {a: b}
a:first-line {@extend %c}

%d, %d:first-letter {a: b}
a::first-letter {@extend %d}

%e, %e::other {a: b}
a:other {@extend %e}
```

Results to the follwoing with Sass 3.5.5 (Bleeding Edge):

```css
a:after, a:after::after {
  a: b; }

a::before, a::before:before {
  a: b; }

a:first-line, a:first-line::first-line {
  a: b; }

a::first-letter, a::first-letter:first-letter {
  a: b; }

a:other, a:other::other {
  a: b; }
```

AFAICS LibSass handles this already correctly:

```css
a:after {
  a: b; }

a::before {
  a: b; }

a:first-line {
  a: b; }

a::first-letter {
  a: b; }

a:other, a:other::other {
  a: b; }
```

Side Note: Not sure if we should force either one or two colons in this case.
