### ISSUE TITLE
How to call mixin with default arguments?

### ISSUE THREAD

**Issue by marnen** [sass/sass#2459]
I'm using Sass 3.5.5.

I am having an issue with calling one mixin (call it `inner`) from another (call it `outer`), when both mixins have optional arguments:

```scss
@mixin inner($margin: 2px) {
  margin: $margin;
}

@mixin outer($color: red, $margin: null) {
  @include inner($margin: $margin); // desired effect: call inner with default value unless outer($margin) overrides it
  color: $color;
}
```

Unfortunately, the `null` default value for `$margin` is passed to `inner` as an actual `null` argument (leading to `margin: null`), not as absence of an argument. What value should I pass to `inner` in order to get it to use its default value for the argument? (No, I don't want to use `2px` as the default on `outer`, because I only want to maintain that in one place.) So far the best I've managed is to add `$margin: if($margin, $margin, 2px)` at the beginning of `inner`, but that seems clumsy.

If a Ruby analogy for the desired behavior helps:
```ruby
def inner(margin: 2)
  {margin: margin}
end

def outer(color: :red, margin: nil)
  inner({margin: margin}.compact).merge({color: color})
end
```

Let me know if this isn't clear, and I'll explain further. If you want to see the actual use case for this, check out https://github.com/marnen/contraq/blob/214110db54d4578915eef81a408767b3d2ec5e59/app/assets/stylesheets/_buttons.scss, specifically how the [`button-edit` mixin](https://github.com/marnen/contraq/blob/214110db54d4578915eef81a408767b3d2ec5e59/app/assets/stylesheets/_buttons.scss#L29) calls the more general [`button` mixin](https://github.com/marnen/contraq/blob/214110db54d4578915eef81a408767b3d2ec5e59/app/assets/stylesheets/_buttons.scss#L4).

**Comment by nex3** [comment]
If I could do it over again, I'd make passing `null` to an optional parameter be equivalent to not passing it at all. Hindsight!

Here's how I'd write this:

```scss
@mixin inner($margin: 2px) {
  margin: $margin;
}

@mixin outer($color: red, $args...) {
  @include inner($args...);
  color: $color;
}
```

The `$args...` argument captures all arguments that aren't explicitly declared, including keyword arguments, and forwards them to `inner()`.

**Comment by marnen** [comment]
@nex3: First of all, thanks for all your work on Sass over the years!
> If I could do it over again, I'd make passing null to an optional parameter be equivalent to not passing it at all. 

I know it would be a breaking change, but is there a reason that we can't have it in a future version, either by changing the semantics of `null` or by using a new value such as `()` or `pass-through`? (I'd be willing to try to implement it if it seems like something that's wanted.)

Good to know about `$args...`. I wasn't sure that it would even work in this case. I don't much like it here, though, because it doesn't have documentary value. In my example, when I look at the code for `outer`, I can tell right away that it takes `$color` and `$margin`. In your example, I have no idea what is meaningful in `$args...` until I look at the definitions of both `outer` and `inner`, which is a lot more work.

So right now, I think I'll stick with the `if()` solution I mentioned above, but I'd really love it if we could figure out a way to address it in the language.

**Comment by nex3** [comment]
You can keep it self-documenting by passing in an explicit map as keyword parameters. It gets a little more complex, but it pretty closely matches the behavior of your Ruby example:

```scss
@mixin inner($margin: 2px) {
  margin: $margin;
}

@mixin outer($color: red, $margin: null) {
  @include inner(compact-map(("margin": $margin))...);
  color: $color;
}

@function compact-map($map) {
  @each $key, $value in $map {
    @if $value == null {
      $map: map-remove($map, $key);
    }
  }
  @return $map;
}
```

> I know it would be a breaking change, but is there a reason that we can't have it in a future version, either by changing the semantics of `null` or by using a new value such as `()` or `pass-through`? (I'd be willing to try to implement it if it seems like something that's wanted.)

Breaking changes are a *lot* of work, and entail a *lot* of potential pain for users. On our side, we need to detect all the cases where semantics will change and emit a warning that concisely explains to users what's changing, why, and what they can do to their code to make it better. And in this case, fixing the issue requires rewriting the mixin they're *calling* to have `null` not be meaningfully distinct from passing no value, which may not be possible if it's upstream code.

Ultimately, although this behavior kind of sucks, I don't think it's a big enough issue to pay that price. Nor is it big enough to make the very substantial language change of adding a new value type just to work around this issue.
