### ISSUE TITLE
How to insert a variable into text in mixin

### ISSUE THREAD

**Issue by ghost** [sass/sass#2460]
Here is my code

```scss
@mixin box-shadow($y, $x, $blur, $stretch, $color)
{
	box-shadow: $y $x $blur $stretch $color;
	-webkit-box-shadow: $y $x $blur $stretch $color;
	-moz-box-shadow: $y+px $x $blur $stretch $color;
	filter: progid:DXImageTransform.Microsoft.dropshadow(offX=$x, offY=$y, color=$color);
}
p {
@include box-shadow(10, 10, 10, 0, #fff);
}
```

Why is the result obtained here by the result?

```css
  webkit-box-shadow: 10 10 10 0 #fff;
  -moz-box-shadow: 10px 10 10 0 #fff;
  filter: progid:DXImageTransform.Microsoft.dropshadow(offX=$x, offY=$y, color=$color);
```

I need to get this result:

```css
  webkit-box-shadow: 10 10 10 0 #fff;
  -moz-box-shadow: 10px 10 10 0 #fff;
  filter: progid:DXImageTransform.Microsoft.dropshadow(offX=10, offY=10, color=$color);
````
