### ISSUE TITLE
Undefined math operations on mixin "NaN times 100"

### ISSUE THREAD

**Issue by nguyenmv2** [sass/sass#2462]
We recently migrated from Sass v3.2.10 to the latest version of Sass ( Rails 3 -> Rails 4). During the assets compilation, we encounter this error
```
SassC::SyntaxError: Error: Undefined operation: "NaN times 100".
        on line 101 of .../_mixins.scss
>>  $min-breakpoint: $min / $responsive-unitless * 100;
```
Here is the mixin declartion
```scss
@mixin responsive-property($property, $CSSvalue, $min, $max: false) {
 $CSSvalue2: get-vw($CSSvalue);
 $responsive-unitless: $CSSvalue2 / ($CSSvalue2 - $CSSvalue2 + 1);
 $dimension: if(unit($CSSvalue2)=='vh', 'height', 'width');
 $min-breakpoint: $min / $responsive-unitless * 100;
 @media (max-#{$dimension}: #{$min-breakpoint}) {
  #{$property}: $min;
 }
 @if $max {
  $max-breakpoint: $max / $responsive-unitless * 100;
  @media (min-#{$dimension}: #{$max-breakpoint}) {
   #{$property}: $max;
  }
 }
 $fallback: $CSSvalue+px;
 #{$property}: $fallback;
}
```
I understand that this is caused by the variable not being intialized. Is there a way I could set the default value of the variables to avoid this issue ?
