### ISSUE TITLE
[Feature Request] Merge equal selectors

### ISSUE THREAD

**Issue by lucas-viewup** [sass/sass#2464]
Why Sass doesn't have an option to merge equal selectors like:

**file.scss**
```css
.foo{
 font-size: 14px !1;
}
```
**file2.scss**

```css
.foo{
 width: 150px;
font-size: 12px;
}
```

**output.css**
```css
.foo{
width: 150px;
font-size: 14px;
}
```
Just an idea, !1 is the number of priority, by default, all properties have priority zero, the priority is something like z-index thing, the major it is, more priority it will have, so the most higher priority property will be rendered.
