### ISSUE TITLE
Weird results with `&` parent/root selector.

### ISSUE THREAD

**Issue by spAnser** [sass/sass#2465]
Getting weird results with `&` parent/root selector.

---
This first example is what I expect to happen in the rest.
```scss
.parent
{
  .child
  {
    .orange &
    {
      color: orange;
    }
  }
}
```
```css
.orange .parent .child {
  color: orange;
}
```
---
I get the expected result but doesn't feel right to make a mixin for this.
```scss
@mixin orange
{
    .orange &
    {
      color: orange;
    }
}
.parent
{
  .child
  {
    @include orange;
  }
}
```

```css
.orange .parent .child {
  color: orange;
}
```
---
It has the expect result but then it also has extra output here. It has `.orange` at the root and as an immediate parent of `.child`. As you can also see using `@at-root` doesn't make a difference.
```scss
%orange
{
    .orange &
    {
      color: orange;
    }
    @at-root .orange &
    {
      color: orange;
    }
}

.parent
{
  .child
  {
    @extend %orange;
  }
}
```
```css
.orange .parent .child, .parent .orange .child {
  color: orange;
}
.orange .parent .child, .parent .orange .child {
  color: orange;
}
```
---
Well in this one I managed to cut down on the output using a `>`. However it is missing the selector order I wanted, also I don't really want the `>`, it might not be an immediate child element.
```scss
%orange-2
{
    .orange > &
    {
      color: orange;
    }
    @at-root .orange > &
    {
      color: orange;
    }
}
.parent
{
  .child
  {
    @extend %orange-2;
  }
}
```
```css
.parent .orange > .child {
  color: orange;
}
.parent .orange > .child {
  color: orange;
}
```
---
Using `>` inline instead of inside an extend functions differently than using it inside an extend.
```scss
.parent
{
  .child
  {
    @at-root .orange > &
    {
      color: orange;
    }
    .orange > &
    {
      color: orange;
    }
  }
}
```
```css
.orange > .parent .child {
  color: orange;
}
.orange > .parent .child {
  color: orange;
}
```

**Comment by nex3** [comment]
> It has the expect result but then it also has extra output here. It has `.orange` at the root and as an immediate parent of `.child`. As you can also see using `@at-root` doesn't make a difference.
> ```scss
> %orange
> {
>     .orange &
>     {
>       color: orange;
>     }
>     @at-root .orange &
>     {
>       color: orange;
>     }
> }
> 
> .parent
> {
>   .child
>   {
>     @extend %orange;
>   }
> }
> ```
> ```css
> .orange .parent .child, .parent .orange .child {
>   color: orange;
> }
> .orange .parent .child, .parent .orange .child {
>   color: orange;
> }
> ```

The first thing to remember here is that **`&` is resolved before `@extend`**. `&`is part of the execution phase of Sass compilation, and `@extend` happens in a separate phase afterwards, so `@extend` only sees selectors as the exist after `&` has been removed. Your example (minus `@at-root`) is equivalent to:

```scss
.orange %orange {color: orange}

.parent .child {@extend %orange}
```

When you write `@extend` here, you're telling Sass "style all elements that match `.parent .child` as though they also matched `%orange`". What do elements that match `%orange` look like? Well, your other style rule says that if they have a parent that matches `.orange`, their text is orange. So we want all elements that match `.parent .child` *and* that have a parent that matches `.orange` to have orange text. There are three ways this could happen:

* ```html
  <div class="orange"><div class="parent"><div class="child">foo</div></div></div>
  ```
* ```html
  <div class="parent"><div class="orange"><div class="child">foo</div></div></div>
  ```
* ```html
  <div class="parent orange"><div class="child">foo</div></div>
  ```

These correspond to the selectors `.orange .parent .child`, `.parent .orange .child`, and `.parent.orange .child`. Sass doesn't generate the third selector because doing so in general would produce way too much output and it's unlikely to match, but it doesn't know which order `.orange` and `.parent` actually appear in the document so it generates both of them.

It sounds like you know that in your HTML, `.orange` is always outside `.parent`. But Sass doesn't know anything about your HTML, and (where it's possible to do so without generating way too much output) it assumes that anything is possible. That's the only safe thing to do. If you only want selectors that are relevant to the HTML you're actually writing, you need a tool that can look at that HTML--something I know @chriseppstein is hard at work on right now.

*Aside:* It's also worth noting that `@at-root` isn't doing anything in any of your examples. All `@at-root` means is "don't implicitly add `&` at the beginning of this selector." But if you're explicitly using `&`, that already disables the implicit `&`. So the `@at-root`s are redundant.

**Comment by spAnser** [comment]
I guess it makes sense but I saw the point of extending `%orange` in place of just extending another class `.orange` is that you don't create the original output.

**Comment by nex3** [comment]
And indeed you aren't; the text `%orange` never appears anywhere in your output.

**Comment by spAnser** [comment]
Yes true but at the same time why is wasting time compiling the `%orange` to give it a parent selector ahead of time then? Is this because it is creating the place where it adds the selectors later on when it gets extended?

It just seems confusing because you said the `&` resolves before the extend but then it also resolves again after the extend since it is in both places afterwards. All I am wanting is one or the other to be the defined output not multiple outputs from one statement.

**Comment by nex3** [comment]
> Yes true but at the same time why is wasting time compiling the `%orange` to give it a parent selector ahead of time then? Is this because it is creating the place where it adds the selectors later on when it gets extended?

Yes.

> It just seems confusing because you said the `&` resolves before the extend but then it also resolves again after the extend since it is in both places afterwards. All I am wanting is one or the other to be the defined output not multiple outputs from one statement.

The parent selector `&` is only ever resolved before the `@extend`. Everything after that behaves exactly the same as if you had written

```scss
.orange %orange {color: orange}

.parent .child {@extend %orange}
```

by hand.

**Comment by spAnser** [comment]
Yes but in my example where the extend is nested it is creating 2 things not 1

`.orange .parent .child` and `.parent .orange .child`

**Comment by nex3** [comment]
That doesn't have anything to do with `&`. You'd get the same output from the SCSS I wrote above.

**Comment by spAnser** [comment]
That is because you didn't nest it the same level I did. I will repeat the 2 examples that show different output.

The two following outputs do not generate the same final CSS
---
This first example is what I expect to happen.
```scss
.parent
{
  .child
  {
    .orange &
    {
      color: orange;
    }
  }
}
```
```css
.orange .parent .child {
  color: orange;
}
```
---
It has the expect result but then it also has extra output here. It has `.orange` at the root and as an immediate parent of `.child`.
```scss
%orange
{
    .orange &
    {
      color: orange;
    }
}

.parent
{
  .child
  {
    @extend %orange;
  }
}
```
```css
.orange .parent .child, .parent .orange .child {
  color: orange;
}
```
---
