### ISSUE TITLE
background-size px to Percentage

### ISSUE THREAD

**Issue by huzedong2015** [sass/sass#2467]
**# Sass Code**
```scss
$with: 100;
$height: 200;
$size: (
  1001: (10 20, 30, 40),
  1002: (20 30, 30, 30)
);

.test {
  @each $key, $value in $size {
    &-#{$key} {
      // pending...
      clip-path: $value;
    }
  }
}
```

**# Want The Result**
```scss
.test-1001 {
  clip-path: (10% 10%, 30% 20%);
}
.test-1002 {
  clip-path: (20% 30%, 30% 15%);
}
```

**# 1001 computing method**
```scss
clip-pth:(
    percentage(10 / $width) percentage(20 / $height),
    percentage(30 / $width) percentage(40 / $height)
  );
```

## The title is wrong, but the way to deal with it is the same.
