### ISSUE TITLE
Bug with mixins declared within mixins

### ISSUE THREAD

**Issue by ArmorDarks** [sass/sass#2469]
Encountered it within `node-sass@4.7.2`, but I'm not sure is it `libsass` error or Ruby Sass has the same one. Unfortunately, I don't have a Ruby environment right now to check it.

Usually, mixins are not allowed to be declared within mixins.

Such code will throw an error:

```scss
@mixin test () {
  @mixin hey () {
    hey: value;
  }

  .test {
    border: 1px;

    @include hey();
  }
}
```

Strangely enough, if we move the code to a standalone file, it will suddenly work:

```scss
// _test.scss

@mixin test () {
  @mixin hey () {
    hey: value;
  }

  .test {
    border: 1px;

    @include hey();
  }
}
```

```scss
// style.scss — the file, which we're actually compiling
@import 'test';

@include test();
```

Compiling `style.scss` will return

```css
.test {
  border: 1px;
  hey: value; }
```

This is a rare case when I'd wish that bug actually wasn't a bug, but a feature. Declaring functions and mixins within each other sometimes makes sense and improves code readability in case of utility functions and mixins.
