### ISSUE TITLE
skipping optional variables in @fucntion or @mixin

### ISSUE THREAD

**Issue by kien5436** [sass/sass#2474]
I have this @mixin to handle a `<a>` tag looks like a button:
```scss
@mixin btn($padding, $bgc: transparent, $c: #fff, $bd: 1px solid $c) {
    padding: $padding;
    background-color: $bgc;
    color: $c;
    border: $bd;
}

a {
    @include btn(1rem, #000);
}
```
And they turn into:
```scss
a {
  padding: 1rem;
  background-color: #000;
  color: #fff;
  border: 1px solid #fff;
}
```
Now if I want to set default values for every variables and use some of them, such as _color_, I have to rewrite default values of in front of variables:
```scss
@mixin btn($padding: 1rem, $bgc: transparent, $c: #fff, $bd: 1px solid $c) {
    padding: $padding;
    background-color: $bgc;
    color: $c;
    border: $bd;
}

a {
    @include btn(1rem, transparent, #ccc);
}
```
It obviously isn't optimal and convenient. I have tried to customize a fuction to do this.
```scss
@function val($val, $def) {
  @if($val == null) {
    $val: $def;
  }
  @return $val;
}

@mixin btn($padding, $bgc, $c, $bd) {
  padding: val($padding, 1rem);
  background-color: val($bgc, transparent);
  color: val($c, #fff);
  border: val($bd, 1px solid val($c, #fff));
}

a {
  @include btn(null, #000, null, null);
}
```
It worked but I had to declare null for all parameters or else it was error. And when I used this:
```scss
@mixin btn($padding, $bgc, $c, $bd) {
  padding: val($padding, 1%);
  background-color: val($bgc, transparent);
  color: val($c, #fff);
  border: val($bd, 1px solid $c);
}

a {
  @include btn(null, black, null, null);
}
```
The result was that, missing _color_ at _border_:
```scss
a {
  padding: 1%;
  background-color: black;
  color: #fff;
  border: 1px solid;
}
```
Then I tried another way:
```scss
@mixin btn($padding: 1rem, $bgc: transparent, $c: #fff, $bd: 1px solid $c) {
  padding: val($padding, 1rem);
  background-color: val($bgc, transparent);
  color: val($c, #fff);
  border: val($bd, 1px solid val($c, #fff));
}

a {
  @include btn(null, #000, #ccc);
}
```
It worked well! Wow! The _color_ parameter appeared! Rewrite default values is very tired and I couldn't find anyway to reduce them. I wish SASS can do this:
```scss
@mixin btn($padding: 1rem, $bgc: transparent, $c: #fff, $bd: 1px solid $c) {
  padding: $padding;
  background-color: $bgc;
  color: $c;
  border: $bd;
}

a {
  @include btn(#000, #ccc);
}

// and the result is:
a {
  padding: 1rem;
  background-color: #000;
  color: #ccc;
  border: 1px solid #ccc;
}
```
Can anyone help me?

**Comment by ArmorDarks** [comment]
Just use named parameters:

```scss
@mixin btn($padding: 1rem, $bgc: transparent, $c: #fff, $bd: 1px solid $c) {
    padding: $padding;
    background-color: $bgc;
    color: $c;
    border: $bd;
}

a {
  @include btn($bgc: black);
}

// result
a {
  padding: 1rem;
  background-color: black;
  color: #fff;
  border: 1px solid #fff;
}
```
