### ISSUE TITLE
Sass removes `not` from media query

### ISSUE THREAD

**Issue by YodasWs** [sass/sass#2477]
I have the following SCSS:
```scss
@mixin responsive {
  @media not (pointer: fine) {
    @content;
  }
}
input {
  @include responsive {
    background: red;
  }
}
```

However, the keyword `not` is being removed and the compiled CSS comes out like this:
```css
@media (pointer: fine) {
  input {
    background: red;
  }
}
```

This is obviously the opposite of what I wanted.

Even without the use of a mixin, the `not` is being removed:
```scss
input {
  @media not (pointer: fine) {
    background: red;
  }
}
```

I'm using `libsass` version `3.5.0.beta.2` and `node-sass` version `4.5.3`
