### ISSUE TITLE
Using uninterpolated "&" in pseudoselector is inconsistent

### ISSUE THREAD

**Issue by blairwilcox** [sass/sass#2487]
The behavior when using the "&" in a pseudo-selector or element is inconsistent. When I write it as 

```scss
.option {
    :not(&-selector) {
        background-color: red;
    }
}
```

I get this output:

```css
:not(.option-selector) {
  background-color: red;
}
```

But when I interpolate it

```scss
.option {
    :not(#{&}-selector) {
        background-color: orange;
    }
}
```

I get this

```css
.option :not(.option-selector) {
  background-color: orange;
}
```

As it stands, the uninterpolated result produces invalid CSS. We should either produce the interpolated result, or throw an error.

https://www.sassmeister.com/gist/d40e8a3b576f1eafe5747946112fce36

**Comment by nex3** [comment]
This is intentional. Sass can't tell in general if a script value you interpolate is somehow derived from `&` or not, so it doesn't even try. If you want to avoid explicitly adding the parent selector, you can use `@at-root`:

```scss
.option {
    @at-root :not(#{&}-selector) {
        background-color: orange;
    }
}
```
