### ISSUE TITLE
Ability to merge multi-value properties

### ISSUE THREAD

**Issue by miracle2k** [sass/sass#249]
I sometimes wish there where a way to extend a multi-value property by defining it again, and have the two occurrences be merged rather than the latter replacing the former.

```
#note
   // ... define styles for when the box is moving ...
   transition: top 2s

   // ...define styles for when the box is expanding ....
   transition: height 0.4s
```

If the other style definitions are large enough, then this allows you to keep each transition with the block of code where it belongs.

Another case would be usage within mixins, which could add transitions without conflicting with user-defined ones.

Not sure what a good syntax would be. Maybe:

```
 transition +:
 transition ::
```

Another approach might be the referencing properties as variable suggestion made here: https://github.com/nex3/sass/issues/109#issuecomment-1582701

```
transition: top 2s
transition: transition, height 0.4s
```

**Comment by nex3** [comment]
I agree that this should be supported one way or another. The mixin use case is the most convincing; semantically, it makes sense for a mixin to add a transition without clobbering existing ones, but this currently isn't possible syntactically.

It's possible that this is the use case that's always been missing for dynamically referencing properties. The syntax couldn't just be `property-name`, of course, since that's extremely difficult to distinguish from normal CSS, but we could do it in a function or something like that.

It's also possible, though, that this case could be addressed without resorting to property references. It's not possible to just merge all repeated definitions of properties like `transition`, since that violates CSS semantics, but we could merge those in mixins with those in the primary definition. This means that we have to know how to merge arbitrary properties, though... for `transition` it's easy, but most properties just can't be meaningfully merged, and I'm loath to try to maintain a list of those that can.

As it stands, I'm not sure what the right way of supporting this is. I'd like to hear some more brainstorming.

**Comment by miracle2k** [comment]
I don't see a problem with maintaining a list of such mergable properties per se. Not having read the CSS spec, I would nevertheless assume that multiple-value properties are a clearly distinct class. If the approach is to deal with multi-value properties differently if they occur in mixins, then keeping such a list is what it takes. "color" would simply be overridden, "transition" would be merged (though what about shorthand properties like "background")?

In any case, I'm not a fan of the idea, because it sounds like essentially a huge regression: Right now, if a mixin sets a transition property that I don't like,  I can override it (maybe it's third party code, or it's just how my code legitimately works, instead of an argument to the mixin).

With auto-merging, that would no longer be possible. And while I can suspect that from a "simple is beautiful" mindset some might conclude that overwrite capability is maybe not strictly required, it would entail a regression to the current feature set, which is, I think, not worth it.

**Comment by miracle2k** [comment]
In case any one else wants to do this, I just tried to refactor a rather big selector to use a $transition variable to collect multiple values, and then include them at the end. This was more complicated than I expected.

I had a hard time trying to make a variable start with an empty string (btw $temp: ""; $transition: #{$temp} seems to do the job), and arriving at a result where there would be no superfluous commas at the beginning or the end of the final string. In the end, it turns out that when initializing the variable as a list, the unwanted comma simply does not appear:

```
$transition: ()
$transition: $transition, top 1s
transition: $transition
```

yields:

```
transition: top 1s;
```

I hope it's not just a quirk.

**Comment by nex3** [comment]
You can make an empty unquoted string like so: `$transition: unquote("")`.

The removal of empty list elements is an intended feature; you can rely on it.

**Comment by jleclanche** [comment]
How about reusing &? eg:
height: 10px;
width: &height;

That way you can have a $height variable without the engine confusing the two.

**Comment by nex3** [comment]
@Adys That's a neat idea. It's a little weird, though, that `&` is a prefix here and a standalone expression in selectors.

**Comment by Anahkiasen** [comment]
I'm saying it again as I said on another thread but really, one thing missing from SASS is the ability to reuse/combine properties. This is the real thing that will put SASS far beyond LESS, it opens a world of mixins and will ease everyone's life. And I like the & idea, because it means you can do both `width: &height` and `width: (&height + 10px)` or from a mixin use the compass contrast function to set the proper text color just by referencing the background-color, without having the user to give it.

**Comment by jleclanche** [comment]
By the way, I ran into this situation the other day. What happens if you have the following scenario?

``` scss
.foo {
  width: 10px;
}
...
.foo {
  height: &width / 2;
}
```

Does the compiler figure it out? What if the first statement is included from another file? And what if it's like this:

``` scss
@mixin bar() {
  background-color: &color;
}
.foo { color: orange; @include(bar) }
```

**Comment by jleclanche** [comment]
@nex3 I don't really know what makes most sense. Semantically, you could argue that & means "this element", and &width means "this element's width", especially since you would never have (afaik) a case where, currently, you would write &foo or &-prefix-foo.

However, and this is just a random thought because I don't know if it's already possible in sass, we could expand this to include more properties. A function might make more sense.

``` scss
#foo { color: orange; }
#bar { background-color: prop(#foo, color, blue) }
```

`prop(element, property[, default])` where element can be &. This might be doable with syntax but unsure how. Maybe &->color, #foo->color, (#foo input)->color but sounds weird, and introduces a new selector.

**Comment by joeyhoer** [comment]
I'd like to point out that Less has support for this feature, and we may be able to learn something from their implementation(s) - there is a different syntax for comma and space delimited lists, which would probably be unnecessary in Sass.

http://lesscss.org/features/#merge-feature

**Comment by nex3** [comment]
That's a very Less-like solution, for sure.

**Comment by mahdaen** [comment]
I've looking that way but not get lucky. :(

How about this?

``` sass
$tmp-box-shadow-value: none;

@mixin box-shadow($value, $append: false) {
    @if ($tmp-box-shadow-value == none) {
        $tmp-box-shadow-value: $value !global;
    }
    @else {
        $tmp-box-shadow-value: ($tmp-box-shadow-value, $value) !global;
    }

    @if ($append == false) {
        @include prefixer(box-shadow, $tmp-box-shadow-value, true);

        $tmp-box-shadow-value: none !global;
    }
}
```

``` sass
.shadow-elem {
    // Appending values.
    @include box-shadow(0 0 1px #ccc, true);
    @include box-shadow(0 0 1px #ddd, true);

    // Append and write the style.
    @include box-shadow(0 0 1px #eee);
}
```

**Comment by davidkpiano** [comment]
Here, play around with this (non-standard) mixin + function for now:

```scss
$__property-append-map__: () !global;

@mixin \+($property, $value: null) {
  $selector: selector-parse(&);
  @if not map-has-key($__property-append-map__, $selector) {
    $__property-append-map__: map-merge($__property-append-map__, ($selector: ())) !global;
  }
  
  $property-list: map-get($__property-append-map__, $selector);
  $__property-append-map__: map-merge($__property-append-map__, ($selector: append($property-list, unquote($value), comma))) !global;
}

@function \+($property) {
  $property-list: map-get($__property-append-map__, selector-parse(&));
  @return $property-list;
}
```

**Usage:**
.foo {
  @include \+(animation-name, foo-active-1);
  @include \+(animation-name, foo-active-2);
  
  animation-name: \+(animation-name);
}

.bar {
  @include \+(transition-property, opacity);
  @include \+(transition-property, transform);
  
  transition-property: \+(transition-property);
}

// CSS output:
.foo {
  animation-name: foo-active-1, foo-active-2;
}

.bar {
  transition-property: opacity, transform;
}
```
