### ISSUE TITLE
Minification leads to semantically different result

### ISSUE THREAD

**Issue by ghost** [sass/sass#2493]
It appears the color compression step of minification happens before function application (??), with the following result:

```scss
:root {
	--black: 0,0,0;
	$rgb-string: "rgb(var(--" + black + "))";
	color: unquote($rgb-string);
}
```

is correctly minified to

```css
:root{--black:0,0,0;color:rgb(var(--black))}
```

but

```scss
@function RGB($variable) {
	$rgb-string: "rgb(var(--" + $variable + "))";
	@return $rgb-string;
}
:root {
	--black: 0,0,0;
	color: unquote(RGB(black));
}
```

is minified to

```scss
:root{--black:0,0,0;color:rgb(var(--#000))}
```

which is clearly different, and in this case leads to a bug only occuring in the minified version.
