### ISSUE TITLE
Please add subtract_color(minuend, subtrahend) to allow porting code relying on color subtraction to sass-4 more easily

### ISSUE THREAD

**Issue by binki** [sass/sass#2501]
When I try to compile this on sass-4 (dart-sass), I get an error:

```scss
.a {
  x: white - grey;
}
```

```
Error: Undefined operation "white - grey".
  x: white - grey;
     ^^^^^^^^^^^^
  - 2:6  root stylesheet
```

I found that to port my code, I had to write this, which is quite WET (see how many times I have to write grey) and tedious:
```scss
.a {
  x: adjust_color(white, $red: -(red(grey)), $green: -(green(grey)), $blue: -(blue(grey)));
}
```

May a `subtract_color(minuend, subtrahend)` be added which implements the sass-3 `color minus color` support to enable easier porting of sass-3 code to sass-4? I can always write one myself for my own code, but I think it should be core.

Thanks.

**Comment by binki** [comment]
I think I would expect such functions to match the behavior provided by the following:

```scss
@function add_color($a, $b) {
  @return adjust_color($a, $red: red($b), $green: green($b), $blue: blue($b));
}
@function subtract_color($minuend, $subtrahend) {
  @return adjust_color($minuend, $red: -(red($subtrahend)), $green: -(green($subtrahend)), $blue: -(blue($subtrahend)));
}

@function multiply_color($a, $scalar) {
  @return rgba($scalar * red($a), $scalar * green($a), $scalar * blue($a), alpha($a));
}
@function divide_color($a, $scalar) {
  @return rgba(red($a) / $scalar, green($a) / $scalar, blue($a) / $scalar, alpha($a));
}

.a {
  x: subtract_color(white, grey);
  y: add_color(green, red);
  z: multiply_color(grey, 2);
  w: divide_color(green, 2);
}
.b {
  x: subtract_color(rgba(255, 254, 253, .4), grey);
  y: add_color(rgba(0, 254, 253, .4), red);
  z: multiply_color(rgba(255, 254, 253, .4), 2);
  w: divide_color(rgba(255, 254, 253, .4), 2);
}
```

output:
```css
.a {
  x: #7f7f7f;
  y: #ff8000;
  z: white;
  w: #004000;
}

.b {
  x: rgba(127, 126, 125, 0.4);
  y: rgba(255, 254, 253, 0.4);
  z: rgba(255, 255, 255, 0.4);
  w: rgba(128, 127, 127, 0.4);
}
```
