### ISSUE TITLE
CSS4 variables not working with functions

### ISSUE THREAD

**Issue by rraziel** [sass/sass#2516]
Hello,

Not sure whether this has been reported (or whether it's not supposed to work by design) but the following:

```css
@function testfunc($x) {
    @return $x;
}

body {
    --test: testfunc(42);
    -test: testfunc(42);
    test: testfunc(42);
}
```

Turns into the following CSS:

```css
body {
    --test: testfunc(42);
    -test: 42;
    test: 42;
}
```

Is there any reason why the CSS variable one does not work?
