### ISSUE TITLE
Question: Can I change a parent element when a certain class is present?

### ISSUE THREAD

**Issue by younusmahmood** [sass/sass#2526]
I want to change the main tag background color but only on certain pages where a certain .theme class is being used. Is there any way for me to access that main so it doesn't change it for every single page?

**Comment by ArmorDarks** [comment]
There is no way to access parent, but your issue completely solvable by the CSS:

```css
main { background: blue; }
.red-theme main { background: red; }
```

Or a Sass way:

```scss
main {
  background: blue;

  .red-theme & { background: red; }

}
```

You can use [a mixin](https://github.com/ArmorDarks/ekzo/blob/master/tools/_mixins.themes.scss#L61), which basically doing same thing, but slightly more (ignore everything related to `ekzo-set-temp` function, your case doesn't need that).

Another way is to use CSS variables, but browsers support isn't great yet.
