### ISSUE TITLE
null without !default. the value with !default should't override the null

### ISSUE THREAD

**Issue by LinboLen** [sass/sass#2527]
```scss
$heading-color          : null;

$heading-color          : rgba(#000, 0.85) !default;

body {
  color: $heading-color;
}
```

current output 
```scss
body {
  color: rgba(0, 0, 0, 0.85);
}

```

I don't want body compiled with color style
