### ISSUE TITLE
I wanna this pattern

### ISSUE THREAD

**Issue by pgit-b2coin** [sass/sass#2530]
```scss
$menu-item-height: ~;
$depth-2-height: ~;

@include responsive(desktop){
    $menu-item-height: 80px;
}

@include responsive(mobile) {
    $menu-item-height: 40px;
}
...

header { .item { height: $menu-item-height } }
```

media query <-> variable changes

**Comment by nex3** [comment]
This is a great use-case for [CSS custom properties](https://drafts.csswg.org/css-variables/):

```css
@include responsive(desktop){
  :root {
    --menu-item-height: 80px;
  }
}

@include responsive(mobile) {
  :root {
    --menu-item-height: 40px;
  }
}
...

header { .item { height: var(--menu-item-height) } }
```

Sass generally doesn't add features that have a lot of overlap with features that are already in CSS. However, there are [CSS-to-CSS polyfills available](https://github.com/MadLittleMods/postcss-css-variables) for supporting this if you're targeting browsers that don't support custom properties natively.
