### ISSUE TITLE
Sass Variables need interpolation inside CSS variables

### ISSUE THREAD

**Issue by sturobson** [sass/sass#2532]
Original source of issue:

https://codepen.io/leaverou/pen/ZRPqMZ?editors=0100#0

https://twitter.com/LeaVerou/status/1014046898670333952

## input.scss

```scss
$magenta: hsl(330, 100%, 50%);

div {
	color: $magenta;
	--color: $magenta;
	--color: #{$magenta};
}
```

## Actual results

[todo]: # (update version info!)

RubySass 3.5.6
```css
div {
  color: #ff0080;
  --color: $magenta;
  --color: #ff0080;
}
```

## Expected result

[todo]: # (update version info!)

```css
div {
  color: #ff0080;
  --color: #ff0080;
  --color: #ff0080;
}
```

## Other Sass Versions 

note in Ruby Sass 3.5.5 it works:

```css
div {
  color: #ff0080;
  --color: #ff0080;
  --color: #ff0080;
}
```

But ...

libsass 3.5.3 [issue here](https://github.com/sass/libsass/issues/2685)

```css
div {
  color: #ff0080;
  --color: $magenta;
  --color: #ff0080;
}
```

Dart Sass 1.6.2 [issue here](https://github.com/sass/dart-sass/issues/396)

```css
div {
  color: #ff0080;
  --color: $magenta;
  --color: #ff0080;
}
```

(above tested via Sassmeister)
