### ISSUE TITLE
Background layers merger

### ISSUE THREAD

**Issue by rentalhost** [sass/sass#2537]
I don't know if it is a feature that could be solved by SASS or maybe it could be done with some kind of mixin. Well, `background` property is very complex and it supports comma separated backgrounds. So basically we can have:

```css
.something {
    background: url('x.png'), linear-gradient(...);
}
```

It is a bit hard to "reuse" this code (for instance, if image changes on hover, but gradient should be keeped) due to CSS limitations. Basically, you should duplicates the CSS in this case:

```css
.something {
    background: url('x.png'), linear-gradient(...);

    // Just changed the image, not the gradient:
    &:hover { background: url('y.png'), linear-gradient(...); }
}
```

With that on mind, I think that maybe we can have some new feature that could do this job automatically, by merging the "layers" of background into one. Something like:

```css
.something {
    @layer (1) { background: url('x.png'); }
    @layer (2) { background: linear-gradient(...); }

    &:hover {
        @layer (1) { background: url('y.png'); }
    }
}
```

And the result should be exactly like the previous one, but without need repeat the gradient (once that it is not modified). The CSS result will be the same too.

It could be applied to a lot of another complex properties, like `box-shadow`, for instance.
