### ISSUE TITLE
adjust-hue() doesn't accept interpolated degree as argument

### ISSUE THREAD

**Issue by fionnachan** [sass/sass#2542]
I was trying to pass an interpolated value as the degree for the `adjust-hue()` but it didn't work. I tried to change `#{$i}deg` to `20deg` or `1deg` or whatever hardcoded deg and it works fine.

```
$bgcolor: #62cbe2;
$bgcolor-hsl: hsl(hue($bgcolor), saturation($bgcolor), lightness($bgcolor));

@keyframes bg {
  @for $i from 1 to 360 {
    #{100/$i}% {
      background-color: adjust-hue($bgcolor-hsl, #{$i}deg);
    }
  }
}
```

**Comment by nex3** [comment]
When you write `#{$i}deg`, you're not creating a number; you're creating an unquoted string whose value happens to look like a number. In order to create a number with the unit `deg`, you have to use [unit arithmetic](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#number_operations). For example:

```scss
$bgcolor: #62cbe2;

@keyframes bg {
  @for $i from 1deg to 360deg {
    #{$i * (100%/360deg)} {
      background-color: adjust-hue($bgcolor, $i);
    }
  }
}
```

Here, the variable `$i` always has the unit `deg`. When we write `$i * (100%/360deg)`, we're effectively telling it the ratio of percentage points per degree so that it can convert `deg` into `%`.

It's also worth noting that you don't need to manually write `hsl()`--Sass color values always support both HSL and RGB operations.
