### ISSUE TITLE
Static assertions?

### ISSUE THREAD

**Issue by xmo-odoo** [sass/sass#2545]
Existing working sass/scss code can easily get broken based on upstream changes of a variable's implementation details (either third-party or careless first-party): say upstream defines a `$foo: 25px`, `left: $foo + 5px` will generate `left: 30px`.

Now upstream / a colleague decides to change the original definition to `$foo: calc(50% - 2px)`, scss will not produce any warning but the former computation now yields a nonsensical `left: calc(50% - 2px)5px;`.

Is there a way to protect the original expression somehow such that it fails to compile?

**Comment by nex3** [comment]
You could write a function to do this, I suppose:

```scss
@function assert-number($value) {
  @if type-of($value) != "number" {
    @error "Expected #{$value} to be a number.";
  } @else {
    @return $value;
  }
}

// ...

.foo {
  left: assert-number($foo) + 5px;
}
```

In general, be aware that changing a variable's value from one SassScript type to another (`calc()` returns a string) is a dangerous operation.
