### ISSUE TITLE
Include a Map as css properties

### ISSUE THREAD

**Issue by thany** [sass/sass#2548]
This seems to me like it would be a useful feature:

```scss
$test: (
  color: red,
  background: yellow
);

div { @include $test; }
```
Would result in:
```css
div {
  color: red,
  background: yellow
}
```

The use-case is to be able to specify a dynamic list of sets of properties, and have some function to choose between them.

The current workaround is to define mixins, but mixins cannot exist in a List or Map, and (because of that) one cannot dynamically include one. At least not without the code becoming too verbose.

Having multiple snippets of similar css as Maps can be useful, so to give a simple more realworld-ish example:
```scss
$themes: (
  dark: ( color: #ddd, background: #222 ),
  light: ( color: #222, background: #eee ),
  blue: ( color: #229, background: #ddf )
);
@each $name,$props in $themes {
  .widget-#{$name} {
    @include $props;
  }
}
```

Now, mind you, I *know* what it says in the documentation:
> Maps cannot be converted to plain CSS.

So it's by design. But that's why I'm requesting it. In other words, this is a feature request, not a bug report.
