### ISSUE TITLE
Suggestion. Qt QSS support in sass.

### ISSUE THREAD

**Issue by Guitarheroua** [sass/sass#2549]
In the Qt framework, [QSS](http://doc.qt.io/qt-5/stylesheet-reference.html) style language is used. It is a bit modified version of old CSS. It is possible to use your sass for Qt, but it required couple modifications. There are two things, that different in QSS, that does not support by sass from the box:

1. Custom "!" (not) before pseudo classes:

```css
QTabBar::tab:!selected {
    margin-top: 2px; /* make non-selected tabs look smaller */
}
```
2. Custom named argument for gradient functions:

```css
QListView::item:selected:!active {
    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,
                                stop: 0 #ABAFE5, stop: 1 #8588B2);
}
```
I made two fixes for [libSASS](https://github.com/Guitarheroua/libsass-for-qt) to support this, you can check my commits [here](https://github.com/Guitarheroua/libsass-for-qt/commit/c6882ccd5600d3749b7ab5355386ba60e592186b) and [here](https://github.com/Guitarheroua/libsass-for-qt/commit/d1b284557339a9e18dda6721a874326fbb9d7024). I tested them on pretty huge qss files ([here one example](https://github.com/ColinDuquesnoy/QDarkStyleSheet/blob/master/qdarkstyle/style.qss)), and everything works as expected.

My suggestion is to add QSS support to SASS from the box. 

Thanks in advance!
