### ISSUE TITLE
Missing semicolon not detected in SASS >= 3.4.*

### ISSUE THREAD

**Issue by rowild** [sass/sass#2551]
1. Use this SCSS code:

```scss
// ----
// Sass (v3.4.25)
// Compass (v1.0.3)
// ----
.x-change {
  &-enter {
    transform: translateX(100%)  // <== here a semicolon is missing, but it is not detected

    &-to {
      transform: translateX(0);
    }
  }
}
```

EXPECTED RESULT:
SCSS detects the missing semicolon after translateX(100%) and refrains from compiling

WHAT REALLY HAPPENS
SCSS does not throw an error, and instead compiles to wrongful CSS:

```css
.x-change-enter {
  transform: translateX(100%) .x-change-enter -to; // <== this is a mess!
  transform-transform: translateX(0);
}
```

SPECIAL SCENARIO THAT WORKS:
If SASS compiler 3.3.14 is used, the missing semicolon is detected and an error message is thrown.

Sources for easier reproduction:

Sassmeister:
https://www.sassmeister.com/gist/5cca12508ca3e2b499e7e80bba0a50a2

Gist:
https://gist.github.com/rowild/5cca12508ca3e2b499e7e80bba0a50a2

**Comment by nex3** [comment]
I understand why this is confusing, but it's actually the expected behavior. SCSS is not a whitespace-sensitive language, which means that your stylesheet is equivalent to:

```scss
.x-change {
  &-enter {
    transform: translateX(100%) &-to {
      transform: translateX(0);
    }
  }
}
```

`translateX(100%) &-to` is a valid property declaration (`&` in a property value refers to [the parent selector](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#parent-script)), and property declarations may have [both values and children](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#nested_properties).

This threw an error in Sass 3.3 because `&` wasn't yet a valid expression, so `translateX(100%) &-to` wasn't a valid property value and Sass was able to tell that you intended it to be a selector.
