### ISSUE TITLE
extend not working well in coma separated selectors list

### ISSUE THREAD

**Issue by tigrr** [sass/sass#2553]
This sass:
```sass
%foo {
  &,
  &:hover,
  &:focus {
    background: green;
  }
}

.foo {
  @extend %foo;
}
```
instead of expected:
```css
.foo,
.foo:hover,
.foo:focus {
  background: green;
}
```

compiles to this css:
```css
.foo {
  background: green;
}
```

Whereas this sass:
```sass
%foo {
  &:hover,
  &:focus {
    background: green;
  }
}

.foo {
  @extend %foo;
}
```

correctly compiles to this css:
```css
.foo:hover,
.foo:focus {
  background: green;
}
```

Sass version: 1.13.0.
