### ISSUE TITLE
Units of numbers equal to 0

### ISSUE THREAD

**Issue by veronQ** [sass/sass#2556]
``` scss
@mixin test($value) {
  @if $value == 0 {
    color: blue;
  }
}

.foo {
  @include test(0k);
}

```

Expected result shouldn't be *true*.

(I am using Ruby sass)
