### ISSUE TITLE
Incorrect selector class aggregation.

### ISSUE THREAD

**Issue by gitwaver** [sass/sass#2569]
Original code (.scss):

```scss
%ph-base-subtle-border {
  border-bottom-style: solid;
  border-bottom-width: 1px;
}

%ph-no-default-appearance {
  appearance: none;
  border: none;
  background: none;
}

.class1 {
  @extend %ph-no-default-appearance;
  @extend %ph-base-subtle-border;
  (...)
}

.class2 {
  @extend %ph-base-subtle-border;
  (...)
}
```

gets transpiled to (.css):

```scss
.class1, class2 {
  border-bottom-style: solid;
  border-bottom-width: 1px; }

.class1 {
  appearance: none;
  border: none;
  background: none; }
```

As you can see, the precedence order causes my border override to be, well, re-overriden.
Either find a cleverer way to define precedence order OR do not aggregate classes under the same selector when one of them contains overrides.
