### ISSUE TITLE
Inconsistent `@extend` output when using > vs. space (?)

### ISSUE THREAD

**Issue by nategreen** [sass/sass#2572]
These two very similar situations seem to be working inconsistently...

```scss
%child {
  %parent%state & {
    color: green;
  }
}

.parent {
  @extend %parent;
  
  &.state {
    @extend %state;
  }
  
  > .child {
    @extend %child;
  }
}
```
```css
/* Definitely would not match the markup I'm writing for, considering ".parent > .child" and "%parent%state %child"... */
.parent.state .parent > .child {
  color: green;
}
```

But...

```scss
%child {
  %parent%state & {
    color: green;
  }
}

.parent {
  @extend %parent;
  
  &.state {
    @extend %state;
  }

  // Add descendant selector...
  .child {
    @extend %child;
  }
  
  > .child {
    @extend %child;
  }
}
```
```css
.parent.state .child {
  color: green;
}
```

Based on my confusion related to #2570 I don't trust that I know how `@extend` _should_ work, but it seems like these two are definitely inconsistent with one another, right? When the descendant selector is extending `%child`, Sass seems to understand that `.parent<space>` also works for `.parent > `, but when that part isn't there, that understanding is gone, and I get an extra `.parent` thrown into the selector.

I see that I can "fix" it by changing the first part to `%parent%state > &`; however, it seems like whatever logic is taking place with the classes here should also be applied to the constraints from the placeholders. 🤕 Either way, I know that if I were to use this in our library and other contributors or users ran into this, it's just going to confuse the heck out of them because it's so unpredictable.
