### ISSUE TITLE
Possibility to evaluate custom variables before executing functions

### ISSUE THREAD

**Issue by abaracedo** [sass/sass#2579]
Is it possible to evaluate a `css` custom variable when this is used in a function?

For example:

```scss
:root {
    --blue: #5bc0eb;
}


$dark-blue: darken(var(--blue), 20%);
```

When the script runs to build the `css` code, it throws an error saying `var(--blue)` is not a valid color.
