### ISSUE TITLE
CSS Vars quotes removed

### ISSUE THREAD

**Issue by pacifier007** [sass/sass#2586]
I am using gulp-sass / node-sass and have problem with SASS stripping out quotes. Is there any way to preserve the quotes? Seeing same on https://www.sassmeister.com/

```scss
$body-font: "PT Serif", serif;

:root {
  --body-font: #{$body-font};
}
```
Result:

```css
:root {
  --body-font: PT Serif, serif;
}
```

**Comment by nex3** [comment]
There are two ways to work around this behavior. You could either pass the list to the `inspect()` function, which will return an unquoted string that contains the representation of the list:

```scss
$body-font: "PT Serif", serif;

:root {
  --body-font: #{unquote($body-font)};
}
```

or you can use interpolation in the property name so that Sass's special custom property parsing behavior (which is necessary for CSS compatibility) doesn't activate:

```scss
$body-font: "PT Serif", serif;

:root {
  #{--body-font}: $body-font;
}
```
