### ISSUE TITLE
Escape a tab character as \9 rather than a literal tab

### ISSUE THREAD

**Issue by hiz8** [sass/sass#2590]
- [x] [Proposal](https://github.com/sass/language/pull/43)
- [x] [Specs](https://github.com/sass/sass-spec/pull/1332)
- [x] [Documentation](https://github.com/sass/sass-site/pull/264)
- [x] [Dart Sass](https://github.com/sass/dart-sass/issues/552)
- [x] [Ruby Sass](https://github.com/sass/ruby-sass/issues/103)

LibSass hasn't yet implemented the feature that this is modifying (https://github.com/sass/libsass/issues/2700).

---

I found that the dart-sass broke css hack for ie.

## Reproduce error
```sass
body {
  color: #000 \9; // for IE hack
}

@import "import";
```

## Error
```css
body {
  color: #000 \	;  /* broken */
}

body {
  color: #000 \	; /* @import is also the same */
}
```

This is hack for ie10 or earlier, I think that it is rare to use this, but it is used in some famous libraries and it may be affected. (Especially in case of minifying css.)

I would be happy if you could consider dealing with this problem.
Thanks.
