### ISSUE TITLE
reconsider de-quoting of strings

### ISSUE THREAD

**Issue by lunelson** [sass/sass#2597]
AFAICT dart-sass implements a general policy of de-quoting strings, a few exceptions; I'm wondering what the consequences would be if this was inverted and strings were left quoted as a general rule, with possible exceptional de-quoting for certain contexts? It seems the edge cases of missing quotes are more dangerous than having them, which is usually innocuous.

Consider the following case where I want to set font-feature-settings in a custom property, which is set from a Sass variable. In both dart-sass and libsass I've no choice but to double quote the variable, in order to preserve the right quoting, which precludes handling the `$settings` value as a Sass list:

```scss
$settings: 'kern' 1, 'ss01' on;

.test {
  font-feature-settings: $settings; /* will work */
  font-feature-settings: var(--font-feature-settings);
  --font-feature-settings: #{$settings}; /* won't work */
}

$settings: "'kern' 1, 'ss01' on";

.test {
  --font-feature-settings: #{$settings}; /* will work */
}
```
```css
.test {
  font-feature-settings: "kern" 1, "ss01" on; /* will work */
  font-feature-settings: var(--font-feature-settings);
  --font-feature-settings: kern 1, ss01 on; /* won't work */
}

.test {
  --font-feature-settings: 'kern' 1, 'ss01' on; /* will work */
}
```
