### ISSUE TITLE
Is it possible to compile only mixins in scss?

### ISSUE THREAD

**Issue by midorikocak** [sass/sass#2598]
I have a scss file with some partial mixins. I want to compile only that mixin, without converting it to CSS. Let me show you the code.

```scss
@mixin baseButton() {
  position: relative;
  display: inline-block;

  &:disabled {
    background-color: gray;
  }
}

@mixin button($classname:".midori-button") {
  #{$classname} {
    color: gray;
    @include baseButton();
  }
}

@include button();
```
Is it possible compile this code into SCSS like the above but not into CSS like:

```scss
.midori-button {
  color: gray;
  position: relative;
  display: inline-block;

  &:disabled {
    background-color: gray;
  }
}
```
Thanks.

P.S: Not native.
