### ISSUE TITLE
@extend is extending more than it should

### ISSUE THREAD

**Issue by hefler** [sass/sass#260]
When extending a selector with the same name but in a different context, the parser thinks that selector is meant to be extended as well. Making it clear, take this example for instance:

``` scss
p {
    font-size: 1em;
    font-weight: bold;
    text-transform: uppercase;
}

ul, ol {
    @extend p;
}

.my-other-rule-context {
    margin: 10px;
    p {
        color: red;
    }
}
```

Outputs:

``` CSS
p, ul, ol, ul .my-other-rule-context, ol .my-other-rule-context   {
    font-size: 1em;
    font-weight: bold;
    text-transform: uppercase;
}

.my-other-rule-context {
    margin: 10px;
}

.my-other-rule-context p {
    color: red;
}
```

As far as I understand <code>ul .my-other-rule-context, ol .my-other-rule-context</code> shouldn't be created by the parser. Agreed?

**Comment by nex3** [comment]
I get considerably different output on Sass 3.1.12:

``` css
p, ul, ol {
  font-size: 1em;
  font-weight: bold;
  text-transform: uppercase;
}

.my-other-rule-context {
  margin: 10px;
}

.my-other-rule-context p, .my-other-rule-context ul, .my-other-rule-context ol {
  color: red;
}
```

What version are you using?
