### ISSUE TITLE
sass/scss variable inheritance

### ISSUE THREAD

**Issue by Media-Evil** [sass/sass#2600]
The idea is to make it so that selector's variables and their values are getting inherited by an extension:
```
%extended {
    $myHeight: 2rem;
    $myWidth: 10rem;

    height: $myHeight;
    width: $myWidth;
}

.extension {
    @extend %extended;
    $myHeight: 4 rem;
}

```
this should be parsed to:

```
.extension {
    height: 4rem;
    width: 10rem;
}
```
Very convenient thing to build libraries. #

**Comment by nex3** [comment]
This isn't possible. Extends must be resolved strictly after variables, since you can use variables to affect extensions. If you want to configure how re-usable styles work, you have two options. You could either use mixins with parameters:

```scss
@mixin rectangle($height: 2rem, $width: 10rem) {
  height: $height;
  width: $width;
}

.extension {
  @include rectangle($height: 4rem);
}
```

or, if you want to take advantage of the cascade, you could use CSS custom properties:

```scss
%extended {
  --my-height: 2rem;
  --my-width: 10rem;

  height: var(--my-height);
  width: var(--my-width);
}

.extension {
  @extend %extended;
  --my-height: 4rem;
}
```
