### ISSUE TITLE
Extending with & and pseudo class omits pseudo class 

### ISSUE THREAD

**Issue by andraaspar** [sass/sass#2603]
Using `"sass": "1.17.0"` in Node `v10.15.0` on Windows 10:

# Input
```SCSS
.foo {
  &,
  &:visited {
    color: red;
  }
}

.bar {
  @extend .foo;
}

```

# Expected result
```CSS
.foo, .bar, .foo:visited, .bar:visited {
  color: red;
}
```

# Actual result
```CSS
.foo, .bar, .foo:visited {
  color: red;
}
```
