### ISSUE TITLE
"Can't extend &: can't extend parent selectors"

### ISSUE THREAD

**Issue by webmatrixxxl** [sass/sass#2605]
Hello guys!

I'm trying to use @extend with parent selector "&", but not sure is this a bug or not.

```
.card {
  color: red;

  &__button {
    background: gray;
    color: red;
    font-size: 12px;

    &-disabled {
      @extend &;

      background: black;
    }
  }
}

```
and I hope to get this:

```
.card {
  color: red;
}
.card__button, .card__button-disabled {
  background: gray;
  color: red;
  font-size: 12px;
}
.card__button-disabled {
  background: black;
}

```

But I'm getting this error: "Can't extend &: can't extend parent selectors"

https://www.sassmeister.com/

**Comment by nex3** [comment]
This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.

**Comment by ebubekirtabak** [comment]
You can use the parent class as a variable.

```css
 .card {
  color: red;

  &__button {
    background: gray;
    color: red;
    font-size: 12px;
    $parent_button: &;

    &-disabled {
      @extend #{$parent_button};
      background: black;
    }
  }
}
```

Good luck.
