### ISSUE TITLE
scss equivalence of CSS { height:calc(100% - 68px);}

### ISSUE THREAD

**Issue by maylin2019** [sass/sass#2610]
Before I switched to SASS, I have my.css and in it I have :

```css
.routingInstructionDiv {
                width:100%;
                height:calc(100% - 68px);
}
```

I realized SCSS does not support calc(….).
So I have this in my newly created my.scss:

```scss
.routingInstructionDiv {
                width:100%;
                height:100% - 68px;
}
```

When I run sass to convert my.scss I got the following error:
`Error: Incompatible units px and %.`

Would you please let me know how to fix this issue???

Thanks,
Michael Zhu
