### ISSUE TITLE
css and bootstrap problem

### ISSUE THREAD

**Issue by samdawit** [sass/sass#2615]
```css
.owl-carousel .owl-item {
  position: relative;
  min-height: 1px;
  float: left;
  -webkit-backface-visibility: hidden;          /* error is here green underline*/
  -webkit-tap-highlight-color: transparent;
  -webkit-touch-callout: none;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}
```
