### ISSUE TITLE
Allow  CSS custom properties - var() in darken, lighten, mix, red, green, blue functions.

### ISSUE THREAD

**Issue by Rajkovich** [sass/sass#2616]
Allow  CSS custom properties - var() in darken, lighten, mix, red, green, blue functions.

**Comment by nex3** [comment]
It's not possible to know the value of a `var()` expression at compile-time, since it can vary based on the structure of the HTML document. As such, there's no way for Sass functions to access or modify properties of colors stored in CSS variables.

**Comment by muuvmuuv** [comment]
This may be rejected but I would like to add something. I think it would be possible. Most people `@import` variables before everything else so custom properties would be accessible like any other SASS variable and therefore could be extracted, If one is not found print an error.

The way it is now, it is not possible to use custom properties properly. I have switched most of my SASS variables to custom properties (e.g. for easy dark mode) and it would get a mess to have duplicate variables because I need a SASS variable for global functions. Sure they are compiled and editing the prop would have no effect but at least I could use them.

```scss
//variables.scss
$color: #2d2d2d;
:root {
  --color: #2d2d2d;
}

//base.scss
h1 {
  color: #{rgba(var(--color), 0.7)};
  color: #{rgba($color, 0.7)};
}

// main.scss
@import 'variables';
@import 'base';
```

Prints:

```css
h1 {
  color: #2d2d2d;
  color: #2d2d2d;
}
```
