### ISSUE TITLE
@try/@catch operator

### ISSUE THREAD

**Issue by damienwebdev** [sass/sass#2619]
> Moved from https://github.com/sass/sass/issues/2596

# Proposal: 
Add a try/catch operator to sass to handle `@error` directives more cleanly without hard compiler crashes.

## Use Case
As a developer, I'd like to be able to write test code to cover my sass functions. I'm unable to test all branches of my code as my `node-sass` compiler crashes if it reaches an `@error` directive. While I am glad that the `@error` worked as intended and crashed while I was using the function, I'd like to be able to catch the exception during "test" mode and make an assertion about the message that was thrown.

See: https://github.com/oddbird/true/issues/92 for an example.

### Side comments
With `sass` as popular as it is, and new sass code being written every day, I find that the number of projects that I've worked on without tests for functional code to be high. Testing is necessary for maintenance and confidence in code. As sass is becoming a de-facto "language" for writing stylesheets, it seems that the `@error` operator necessitates a partnering try/catch directive. Even if `@error` is a weakly typed error, and try/catch doesn't have exception types, having the ability to catch an exception and handle it (if only for testing purposes) allows me to be confident that the code that I write is working the way I intend.

**Comment by mirisuzanne** [comment]
@damienwebdev I'd be happy to start working on a proposal here. My first thought is something like…

```scss
@try {
  // potential error
} @catch <optional-variable-for-error-message> {
  // what to do if there's an error
}
```

So in the True use-case, you could do:

```scss
@try {
  @error "that doesn't work for me";
} @catch $error {
  @if $testing {
     // mixins could output a custom property here, rather than return…
     @return $error;
  } @else {
    @error $error;
  }
}
```

There's not a great way to set a variable like `$testing` globally, but it can be passed around as needed. On the other hand, you could write the try/catch logic inside the tests, rather than the code being tested, without any need for a global variable:

```scss
@try {
  $test: my-function($bad-data);
} @catch $error {
  @include assert-equal($error, "that doesn't work for me");
}
```

Going a bit deeper: I imagine `@warn` would also catch? In that case, we might need a second variable for the type of throw? That could either happen via destructuring:


```scss
@try {
  $test: my-function($bad-data);
} @catch $error, $type {
  @include assert-equal($type, 'error');
  @include assert-equal($error, "that doesn't work for me");
}
```

I think that's simpler than adding new data-types and doing `type-of($error)`? 

Am I missing anything else here? Would there be a strong use-case for adding `@finally`?
