### ISSUE TITLE
@extend fails in combination with child selector

### ISSUE THREAD

**Issue by samuelvogel** [sass/sass#262]
When using `@extend` in a declaration which is itself using the child selector, the generated extension selector contains the parent class twice.

For example this

``` scss
div.container {
    > span.base {
        color: red;
    }

    // Using the child selector here breaks the extension
    > span.version {
        @extend span.base;

        font-size: 2em;
    }
}
```

compiles to this:

``` scss
// should be: div.container > span.base, div.container > span.version
div.container > span.base, div.container > div.container > span.version {
  color: red;
}
div.container > span.version {
  font-size: 2em;
}
```
