### ISSUE TITLE
Should extensions be lexically or dynamically scoped?

### ISSUE THREAD

**Issue by nex3** [sass/sass#2622]
Draft 2 of the proposal defines behavior for `@extend` relative to "the module in which the `@extend` appears", but it's not made explicit how that module is defined. In particular, if an `@extend` is written in a mixin that's included in a different module than the one where the mixin is defined, does it "appear in" the module that defines the mixin (lexical scope) or the module that includes it (dynamic scope)?

This becomes particularly relevant in light of https://github.com/sass/language/issues/6, where we may decide to *not* make extensions affect downstream stylesheets. In that case, the following example would fail under a strict interpretation of lexical scope:

```scss
// upstream.scss
@mixin my-font {
  .my-font {
    font: MyFont;
  }

  .my-red-font {
    color: red;
    @extend .my-font;
  }
}
```

```scss
// downstream.scss
@include my-font;
```

Because the `@extend` was defined in the upstream module while the `.my-font` style rule belongs to a downstream module, the `@extend` wouldn't work. I think this points to making `@extend` dynamically-scoped, even though the module system generally pushes other Sass features in a lexically-scoped direction.
