### ISSUE TITLE
How does variable scoping work?

### ISSUE THREAD

**Issue by lunelson** [sass/sass#2641]
Concerning [@content Arguments: Draft 1](https://github.com/sass/language/blob/master/proposal/content-args.md), initial questions / observations.

Firstly @nex3, thanks for moving this forward. 

So as I understand it, the shape this feature is taking is that the `@content` directive can be thought of as a callback function, and the `@include` with `using` syntax as a function-with-callback invocation pattern, more or less.

In my own work I use the 'hack' approach to providing values to `@content` blocks (setting and unsetting a global variable before/after the `@content` directive, respectively) quite extensively, and I'm curious whether this proposed official pattern will support the same use-cases.

For example in the hacked approach, code inside the block of a `@content`-accepting mixin can make reference to 'globally toggled' variables as I described above transparently, without needing to declare them in any way nor explicitly pass them to functions, and may also make use of other functions or mixins (including ones that pass their `@content` on to other `@content`-accepting mixins) that refer to those globals. This becomes like a kind of temporary 'block scope'.

In the proposed syntax however, I am wondering if the 'callback-style' nature means that variables need to be declared (with `using`) and explicitly passed to any functions, or if there is a way to make things a bit more like the effects I describe above. Implicitly I guess this is also a question about how global vs local (block) scopes play out in the proposed syntax pattern.

For example, in the following code what would the output be?

```scss
$bar: 'bar';

@mixin bar-content { @content($bar); }

@mixin bar-setter($foo) {
  $bar: $foo + 'bar';
  @include bar-content using ($bar) {
    @content;
  }
}

@function bar-getter { @return $bar; }

.test {
  @include bar-setter('baz') {
    bar: bar-getter();
  }
}
```
