### ISSUE TITLE
Passing and accepting arguments by name

### ISSUE THREAD

**Issue by natewiebe13** [sass/sass#2642]
Does this draft allow for naming arguments? How I would like to use this is having a mixin that has the ability to pass many passed/computed values, but when adding content doesn't have to declare all of the arguments. The biggest concern driving this is developing frameworks/libraries, where if we want to add more arguments to what the mixin can pass to the content block, we should be able to add them, without having to go to all mixin usages and updating the declaration.

For example, I would like to be able to do the following:

```scss
@mixin accepts-content {
  $random: random();
  @content($number: $random, $degrees: floor(360deg * $random), $size: floor(40px * $random));
}

@include accepts-content using ($degrees: $hue, $size: $padding) {
  .color {
    background-color: hsl($hue, 75%, 90%);
    padding: $padding;
  }
}
```

The order isn't necessarily clear by keeping a familiar syntax, it could be more clear by using something like:

```scss
@include accepts-content using ($degrees as $hue, $size as $padding) { ... }
```
