### ISSUE TITLE
Define whether extensions work across diamond dependencies

### ISSUE THREAD

**Issue by nex3** [sass/sass#2651]
The current proposal's procedure for [resolving extensions](https://github.com/sass/language/blob/master/accepted/module-system.md#resolving-extensions) applies downstream extends to an upstream module iteratively, with one downstream module applying its extends, then another, and so on. This suggests that if two downstream modules extend the same upstream module in a diamond dependency, one of them might be able to extend the other's selectors. For example:

```scss
// upstream.scss
.upstream {a: b}

// left.scss
@use "upstream";
.left {@extend .upstream}

// right.scss
@use "upstream";
.right {@extend .left}
```

Under the current proposal, [if `left.scss` appears before `right.scss` in the reverse topological order](https://github.com/sass/language/issues/53), `upstream.scss`'s selector will become `.upstream, .left` before `right.scss`'s extension is applied, ultimately producing `.upstream, .left, .right`.

This violates the intuitive understanding of how extensions are supposed to be scoped in the module system, and so should be fixed. *All* downstream modules's extensions should be applied in parallel, without affecting one another (although they may be trimmed relative to one another).
