### ISSUE TITLE
Property Shorthand synthax

### ISSUE THREAD

**Issue by alexandreDavid** [sass/sass#2659]
Sometimes, the variable names have the explicit name of the property. Ex: $border.
Following ES6, it could be practical to have this shorthand synthax:

```scss
$border: 1px solid gray;

div {
  $border
}
```
SCSS => CSS
```css
div {
  border: 1px solid gray;
}
```
