### ISSUE TITLE
Support for native CSS variables with fallback values

### ISSUE THREAD

**Issue by cawa-93** [sass/sass#2675]
**Note**: I am not referring to full support, but only to get the value when possible when a fallback values is set.

Here is a simple example of actual work:
```scss
div {
    $width: 2px;
    $double-width: $with * 2
    padding: $width $double-width;
}
```
Compiled to:
```scss
div {
    padding: 2px 4px;
}
```
OK. There is nothing unusual here. Now add native variables to be able to handle them in the product on the client.
```scss
div {
    $width: var(--with, 2px);
    $double-width: var(--double-width, #{$width * 2})
    padding: $width $double-width;
}
```
Unfortunately, this will lead to an exception.

My suggestion is as follows:
When compiler get variable value then check it; If there is string `var()` and fallback values is set return fallback value else return as usually.

Examples:
```scss
div {
    $width: var(--with, 2px);
    $double-width: var(--double-width, #{$width * 2})
    padding: $width $double-width;
}

// output
div {
    padding: var(--with, 2px) var(--double-width, 4px);
}
```

```scss
div {
    $width: var(--with /* fallback value not set */);
    $double-width: var(--double-width, #{$width * 2})
    padding: $width $double-width;
}

// output
// Works as before. Creates a compilation error
```

**Comment by nex3** [comment]
This is a *very* specific circumstance where the results of a `var()` call would work differently than they'd work everywhere else. Adding special-case behavior ends up being quite confusing for Sass users who don't know the language inside and out (which is most of them). They might see a stylesheet doing math on a `var()` and assume that they can use that to refer to the runtime value of CSS variables at compile-time, which is definitely not true.

Also, it's very confusing that `$width * 2` only multiplies the variable if it's not set. If I were reading that stylesheet without any other context, I'd expect it to produce something like:

```scss
div {
    padding: var(--width, 2px) var(--double-width, calc(var(--width, 2px) * 2));
}
```
