### ISSUE TITLE
Inconsistent handling of "e" numbers across all implementations

### ISSUE THREAD

**Issue by stowball** [sass/sass#2688]
I inadvertently ran in to an issue where my hex code variable didn't have the `#` and experienced somewhat unexpected results due to it not being treated as a string or color.

Given this code:

```scss
$hex-no-hash: 483e40;

a {
  color: $hex-no-hash;
}
```

You will get the following, inconsistent output:

```css
// ruby 3.5.6
a {
  color: 4830000000000000000000000000000000000000000;
}
```

```css
// libsass 3.5.4
a {
  color: 4829999999999999741738502159341997581664256;
}
```

```css
// dart 1.18.0
a {
  color: 4.8300000000000004e+42;
}
```
