### ISSUE TITLE
Bug relating to use of parent selector within extended placeholder

### ISSUE THREAD

**Issue by johngrimes** [sass/sass#2716]
I am experiencing some strange behavior relating to the parent selector and extends:

```scss
.foo {
  @extend %bar;
  color: red;
  
  &__a {
    color: purple;
  }
}

%bar {
  &.b {
    color: orange;
  }
  
  & c {
    color: yellow;
  }
  
  &-d {
    color: white;
  }
  
  &__e {
    color: green;
  }
  
  &f {
    color: brown;
  }
}
```

Compiles to the following CSS:

```css
.foo {
  color: red;
}
.foo__a {
  color: purple;
}

.b.foo {
  color: orange;
}
.foo c {
  color: yellow;
}
```

It seems that adding to the parent selector within the extended placeholder only works if the parent selector is followed by a `.` or a space.

The non-placeholder selector doesn't seem to work this way, it quite happily deals with arbitrary suffixes.

Tested on https://www.sassmeister.com/ (dart-sass v1.18.0, libsass v3.5.4, Sass v3.5.6, Sass v3.4.25, Sass v3.3.14)

**Comment by johngrimes** [comment]
Not sure if this issue belongs against one of the implementation repositories.

I get the same results against all of the implementations, maybe I am misunderstanding some aspect of the specification.

**Comment by nex3** [comment]
Check out the first "Heads up!" in [the `@extend` documentation](https://sass-lang.com/documentation/at-rules/extend) for an explanation of why this happens.

**Comment by johngrimes** [comment]
Thanks!

I still don't understand one part of this, however. Why do b and c still work, but not d, e and f?

I would have thought that if parent selectors were resolved before extends, that none of the selectors  b-f would work.

**Comment by nex3** [comment]
`b` and `c` work because parent selectors are resolved to produce:

```scss
%bar.b {
  color: orange;
}
  
%bar c {
  color: yellow;
}
```

Those selectors still contain placeholder selectors with the name `bar`, which are extended by `.foo`. On the other hand, `%bar-d` is a placeholder selector with the name `bar-d`. To extend that, you'd need to specifically write `@extend %bar-d`.
