### ISSUE TITLE
Removing @import should be stopped

### ISSUE THREAD

**Issue by dtvn** [sass/sass#2753]
I agree that we need local vars. But at the same time, global var does bring benefit for certain reason. Moreover, `@use` does not have some good features like `@import`, which it supposed to have. For instance, nesting is a very important one that `@use` should have. But it doesn't.

On the global, we need it to set global configuration (a fixed one). Please refer #2750 

For now, I decide to use both for whatever convenient for me. But I sure hope that we didn't remove `@import` and add nesting to `@use`. Or I will have a tons of extra lines in my code.

**Comment by mirisuzanne** [comment]
Nesting is still supported with the [`load-css()`](https://sass-lang.com/documentation/modules/meta#load-css) mixin - even *improved* because that mixin supports custom configuration and *dynamic* importing:

```scss
@use 'sass:meta';

@each $theme, $file in $themes {
  [data-theme="#{$theme}" {
    @include meta.load-css("themes/#{$file}",
      $with: ("base-color": $brand));
    }
  }
}
```
