### ISSUE TITLE
Import and export mixins, functions, extend

### ISSUE THREAD

**Issue by dmitrach** [sass/sass#2754]
I want to expand *.scss, but expansion may not be implemented.
This problem was solved using @import, @mixin and @include. Can it be solved with @use?
Passing only variables limits the possibilities.

```scss
// _alpha.scss
$primary-color: #333;
$secondary-color: #444;

%button {
  // new styles
}

@mixin **hook-button** {
  // new styles from hook-button 
}
```

```scss
// _button.scss {
  $primary-color: #333 !default;

  %button {
    // default styles
  }

  .button {
    background-color: $primary-color;

   // @extend %button; or @include hook-button;
  }
}
```

```scss
// main.scss
@use "themes/alpha";

@use "button" with (
  $primary-color: alpha.$primary-color
  // Here I want to pass data to expand the code, but not variables, but mixins or code
  // example %button and hook-button
);
```

**Comment by nex3** [comment]
What do you mean by "expanding"?

**Comment by dtvn** [comment]
> What do you mean by "expanding"?

Maybe he meant add more props or selectors to a scss file like `@import` worked. 

I still not fully understand new features, but I think `@use` can do that, only not able to use in the middle of a file. But `@forward` can. Am I right?

**Comment by dmitrach** [comment]
Sorry for my English.

Using the @use se selector we can pass variables.

```scss
@use "button" with (
  $variable: 'value'
);
```
I would like to pass mixins, functions and css code to *.scss, so that they can be used in scss files.
This is similar to PHP traits and OOP.

```scss
// themes/alpha/_newcode.scss:
%css-alpha {
  // any styles
}

@mixin mixin-alpha ($param) {
  // any code

  @parent // call the parent mixin if possible
}
```

```scss
// main.scss
@use "themes.alpha.newcode";

@use "button" with (
  $variable: 'value',

  // export raw css
  %css: {
    // any styles
    @parent // call the parent placeholder if possible
  }, 

  // export CSS from scss file
  %css-2: @extend %newcode.css-alpha,

  // export mixins
  @mixin mixin-name: @include newcode.mixin-alpha,
  @mixin mixin-name-2: @mixin ($param) {
    // any code
  },
); 
```

```scss
// _button.scss
$variable: red !default;

%css !default {
  // default styles
}

@mixin mixin-name($param) !default* {
  // any code
}

@function func($param) !default {
  // any code
  return $result;
}

.button {
  @extend %css;

  @include mixinName('value');

  @if mixin-exists("mixin-name-2") {
    @include mixin-name-2('value');
  }

  @if placeholder-exists("css-2") {
    @extend %css-2;
  }
}
```
