### ISSUE TITLE
Trouble converting css to sass (not scss)

### ISSUE THREAD

**Issue by ryanisinallofus** [sass/sass#276]
``` css
div.round {
  background:
    -moz-radial-gradient(0 100%, circle, rgba(204,0,0,0) 14px, #c00 15px),
    -moz-radial-gradient(100% 100%, circle, rgba(204,0,0,0) 14px, #c00 15px),
    -moz-radial-gradient(100% 0, circle, rgba(204,0,0,0) 14px, #c00 15px),
    -moz-radial-gradient(0 0, circle, rgba(204,0,0,0) 14px, #c00 15px);
  background:
    -o-radial-gradient(0 100%, circle, rgba(204,0,0,0) 14px, #c00 15px),
    -o-radial-gradient(100% 100%, circle, rgba(204,0,0,0) 14px, #c00 15px),
    -o-radial-gradient(100% 0, circle, rgba(204,0,0,0) 14px, #c00 15px),
    -o-radial-gradient(0 0, circle, rgba(204,0,0,0) 14px, #c00 15px);
  background:
    -webkit-radial-gradient(0 100%, circle, rgba(204,0,0,0) 14px, #c00 15px),
    -webkit-radial-gradient(100% 100%, circle, rgba(204,0,0,0) 14px, #c00 15px),
    -webkit-radial-gradient(100% 0, circle, rgba(204,0,0,0) 14px, #c00 15px),
    -webkit-radial-gradient(0 0, circle, rgba(204,0,0,0) 14px, #c00 15px);
}
```

How would I convert this? I feel like Iv'e tried everything but of course I haven't.

Ryan

**Comment by chriseppstein** [comment]
I'd do it like this:

``` scss
@import "compass/css3";
div.round {
  @include background(
             radial-gradient(0 100%, circle, rgba(#c00,0) 14px, #c00 15px),
             radial-gradient(100% 100%, circle, rgba(#c00,0) 14px, #c00 15px),
             radial-gradient(100% 0, circle, rgba(#c00,0) 14px, #c00 15px),
             radial-gradient(0 0, circle, rgba(#c00,0) 14px, #c00 15px)
           );
}
```

You'll get this output:

``` css
div.round {
  background: -webkit-gradient(radial, 0 100%, 0, 0 100%, 15, color-stop(93.333%, rgba(204, 0, 0, 0)), color-stop(100%, #cc0000)), -webkit-gradient(radial, 100% 100%, 0, 100% 100%, 15, color-stop(93.333%, rgba(204, 0, 0, 0)), color-stop(100%, #cc0000)), -webkit-gradient(radial, 100% 0, 0, 100% 0, 15, color-stop(93.333%, rgba(204, 0, 0, 0)), color-stop(100%, #cc0000)), -webkit-gradient(radial, 0 0, 0, 0 0, 15, color-stop(93.333%, rgba(204, 0, 0, 0)), color-stop(100%, #cc0000));
  background: -webkit-radial-gradient(0 100%, circle, rgba(204, 0, 0, 0) 14px, #cc0000 15px), -webkit-radial-gradient(100% 100%, circle, rgba(204, 0, 0, 0) 14px, #cc0000 15px), -webkit-radial-gradient(100% 0, circle, rgba(204, 0, 0, 0) 14px, #cc0000 15px), -webkit-radial-gradient(0 0, circle, rgba(204, 0, 0, 0) 14px, #cc0000 15px);
  background: -moz-radial-gradient(0 100%, circle, rgba(204, 0, 0, 0) 14px, #cc0000 15px), -moz-radial-gradient(100% 100%, circle, rgba(204, 0, 0, 0) 14px, #cc0000 15px), -moz-radial-gradient(100% 0, circle, rgba(204, 0, 0, 0) 14px, #cc0000 15px), -moz-radial-gradient(0 0, circle, rgba(204, 0, 0, 0) 14px, #cc0000 15px);
  background: -o-radial-gradient(0 100%, circle, rgba(204, 0, 0, 0) 14px, #cc0000 15px), -o-radial-gradient(100% 100%, circle, rgba(204, 0, 0, 0) 14px, #cc0000 15px), -o-radial-gradient(100% 0, circle, rgba(204, 0, 0, 0) 14px, #cc0000 15px), -o-radial-gradient(0 0, circle, rgba(204, 0, 0, 0) 14px, #cc0000 15px);
  background: -ms-radial-gradient(0 100%, circle, rgba(204, 0, 0, 0) 14px, #cc0000 15px), -ms-radial-gradient(100% 100%, circle, rgba(204, 0, 0, 0) 14px, #cc0000 15px), -ms-radial-gradient(100% 0, circle, rgba(204, 0, 0, 0) 14px, #cc0000 15px), -ms-radial-gradient(0 0, circle, rgba(204, 0, 0, 0) 14px, #cc0000 15px);
  background: radial-gradient(0 100%, circle, rgba(204, 0, 0, 0) 14px, #cc0000 15px), radial-gradient(100% 100%, circle, rgba(204, 0, 0, 0) 14px, #cc0000 15px), radial-gradient(100% 0, circle, rgba(204, 0, 0, 0) 14px, #cc0000 15px), radial-gradient(0 0, circle, rgba(204, 0, 0, 0) 14px, #cc0000 15px); }
```
