### ISSUE TITLE
Hex color in sass

### ISSUE THREAD

**Issue by adminbmbc** [sass/sass#2767]
I have defined some color variables in global css root

how can i get the hex color in my sass files and not var(color).

this is needed in order to apply color functions which does not work in the case above.

**Comment by mirisuzanne** [comment]
CSS variables are not available to Sass, because their value is processed by the browser in relation to the DOM. If you want a variable available both in Sass and CSS, you have to start from a Sass variable that is used to define the CSS variable (and can also be used in functions):

```scss
$my-color: #966;

:root {
  --my-color: #{$my-color};
  --adjusted-color: #{adjust($my-color, $lightness: -15%)};
}
```
