### ISSUE TITLE
lack of Extension Scope example

### ISSUE THREAD

**Issue by Guo-dalu** [sass/sass#2768]
I've read the documentation in the official site about extension scope, but I really cannot understand  the difference between `@use` and `@import`. Could someone please show me some examples?

**Comment by nex3** [comment]
It means that an `@extend` doesn't affect style rules that are defined in modules that use the module containing the `@extend`. For example:

```scss
// _upstream.scss
.a {@extend .b}
.b {c: d}
```

```scss
// downstream.scss
@use "upstream";
.b {x: y}
```

This will produce:

```css
.b, .a {
  c: d;
}

.b {
  x: y;
}
```

Whereas if the `@use` were an `@import`, it would produce:

```css
b, .a {
  c: d;
}

.b, .a {
  x: y;
}
```
