### ISSUE TITLE
Variables behind a @forward aren't configurable through an @import

### ISSUE THREAD

**Issue by jathak** [sass/sass#2772]
- [x] [Proposal](https://github.com/sass/sass/pull/2773)
- [x] [Specs](https://github.com/sass/sass-spec/pull/1497)
- [x] [Documentation](https://github.com/sass/sass-site/issues/410)
- [x] [Dart Sass](https://github.com/sass/dart-sass/issues/882)
- [ ] [LibSass](https://github.com/sass/libsass/issues/3040)

---

If a library like the following:
```scss
// _library.scss (original)
$lib-color: red !default;
a { color: $lib-color; }
```
removes the `lib-` prefix when migrating to the module system, it will add an import-only stylesheet like so to preserve the manually prefixed names for downstream users still using `@import`.
```scss
// _library.scss (migrated)
$color: red !default;
a { color: $color; }

// _library.import.scss
@forward "library" as lib-*;
```
But this currently breaks downstream stylesheets like:
```scss
// downstream.scss
$lib-color: green;
@import "library";
```
which compiled to `a { color: green; }` prior to migration and `a {color: red; }` after.

It seems like this is due to `@import`-style configuration not propagating through a `@forward`.
