### ISSUE TITLE
Unable to @use peer modules

### ISSUE THREAD

**Issue by jacobScripts** [sass/sass#2774]
Windows 10 | Node v12.13.0 | npm 6.12.0 | sass v1.23.2 compiled with dart2js 2.5.2
``` scss
// index.scss
@forward "function";
@forward "variable";
```
``` scss
// _function.scss
@use "variable" as *;

@function displayOpposite() {
  @if $display == block { @return inline; }
  @else if $display == inline { @return block; }
  @else { @return none; }
}
```
``` scss
// _variable.scss
@use "function" as *;

$display: block;

p {
  display: displayOpposite();
}
```
```
Error: Module loop: this module is already being loaded.
  ╷
1 │ @use "function" as *;
  │ ^^^^^^^^^^^^^^^^^^^^
  ╵
  _variable.scss 1:1  @use
  _function.scss 1:1  @forward
  index.scss 1:1      root stylesheet
```
Would like to have "peer modules" referencing each other with `@use`, either by default or the use of a flag, i.e. `!local`.  The above is only an example, not a real use case.

**Comment by nex3** [comment]
I'm sorry, but this isn't possible. Because loading a file must be fully executed in order to be loaded, you can't have two files both depend on one another (note that this was true for `@import` as well).

**Comment by kerryj89** [comment]
nex3's answer is the answer in your situation, but if you landed here without package restrictions like I did and are able to edit the files (whether directly or through patch-package), you may be able to skirt around this issue by creating another file (I called it `_variable-module-loop-fix.scss` in my example) and move all variables that need to be defined before using the function.


```scss
// index.scss
@forward "variable";

// ↓ "sass index.scss styles.css" output ↓
p {
  display: inline;
}
```
⬆️
```scss
// _variable.scss
@forward "function"; // aka "I'll *forward* my functions so it can be used in index.scss (or anything that @use's index.scss)"
@use "function" as *; // aka "But I also need to *use* the function here for my <p> element"

p {
  display: displayOpposite();
}
```
⬆️
```scss
// _function.scss
@use "variable-module-loop-fix" as *; // aka "Let me be able to *use* variables I need ahead of the function call"

@function displayOpposite() {
  @if $display == block { @return inline; }
  @else if $display == inline { @return block; }
  @else { @return none; }
}
```
⬆️
```scss
// _variable-module-loop-fix.scss

// Move variables from _variable.scss that your functions need to be able to access before it runs
$display: block !default;
```

### But what if I need to change `$display` from the start?

```scss
// index.scss
@forward "variable" with (
    $display: flex !default // FYI displayOpposite() returns 'none' if not 'block' or 'inline'... output confused me for a sec
);

// ↓ "sass index.scss styles.css" output ↓
p {
  display: none;
}
```

### Can I apply a different value for another element?
```scss
// index.scss
@forward "variable" with (
    $display: flex !default
);
@use "function" as *;

$display: 'block';

table {
  display: displayOpposite(); // FYI displayOpposite() returns 'inline' when set to 'block'
}

// ↓ css output ↓
p {
  display: none;
}

table {
  display: inline;
}
```

Feel free to correct me on my understanding of `@use` and `@forward`.  I know using wildcards isn't the best approach, but it can be the most frictionless when dealing with another large library and helps simplify this example a bit.
