### ISSUE TITLE
Properly parse child selectors in sass-convert

### ISSUE THREAD

**Issue by nex3** [sass/sass#278]
``` css
/* input.css */
a>:first-child {b: c}
a>:last-child {b: d}
```

``` scss
// output.scss
a> {
  &:first-child {
    b: c;
  }
  &:last-child {
    b: d;
  }
}
```

``` scss
// expected.scss
a > {
  :first-child {
    b: c;
  }
  :last-child {
    b: d;
  }
}
```

The `a>:foo` selector isn't parsed fully enough to determine that `>` is a combinator. We should actually parse it rather than treating it as a string.
