### ISSUE TITLE
Support for module reconfiguration with inheritance

### ISSUE THREAD

**Issue by kevinreilly** [sass/sass#2789]
I'm trying to migrate a framework over to the module system and I've come across an issue I can't seem to workout a solution to. I need to be able to reconfigure variables from a module multiple times and inherit previously configured variables along the way. For example, this is what I'd like to accomplish:
```scss
//_module1.scss
$font: 'serif' !default;
$color: 'black' !default;
.selector {
  font-family: $font;
  color: $color;
}

//theme.scss
@use 'module1' with (
  $font: 'san-serif'
);
@forward 'module1';

//subtheme.scss
@use 'theme' with (
  module1 (
    $color: 'white'
  )
);
```
I'm not sure if this would be the best way to structure a solution to this problem but it's what I came up with quickly. Here's what the compiled CSS files would look like:
```scss
//theme.css
.selector {
  font-family: san-serif; //configured in theme.scss
  color: black; //inherited from _module1.scss
}

//subtheme.css
.selector {
  font-family: san-serif; //inherited from theme.scss
  color: white; //configured in subtheme.scss
}
```
Reconfiguring previously configured variables could also be possible with this method (in the example above, changing the `$color` variable to `'blue'` in subtheme.scss for example).

I can't imagine I'm the only one to run into an issue like this with the new module system so if anyone has a solution, please let me know. Thanks.

**Comment by mirisuzanne** [comment]
It looks like your use-case can be solved with the [`load-css()` mixin](https://sass-lang.com/documentation/modules/meta#load-css), which was designed for exactly this situation:

```scss
//theme.css
@use 'sass:meta';
.selector {
  @include meta.load-css('module1', $with: ('font': 'sans-serif'));
}

//subtheme.css
@use 'sass:meta';
.selector {
  @include meta.load-css('module1', $with: ('color': 'white'));
}
```

I guess that doesn't give you inheritance between the two, but you could forward a configuration variable from one to the other.

**Comment by kevinreilly** [comment]
@mirisuzanne The same thing can be accomplished without the `load-css()` mixin.
```scss
//theme.scss
@use 'module1' with (
  $font: 'san-serif'
);

//subtheme.scss
@use 'module1' with (
  $color: 'white'
);
```
However, this still doesn't allow for inheritance or reconfiguration.

**Comment by jathak** [comment]
Would `@forward with` (not yet supported, but coming soon) work for your use case?

e.g.

```scss
//_module1.scss
$font: 'serif' !default;
$color: 'black' !default;
.selector {
  font-family: $font;
  color: $color;
}

//theme.scss
@forward 'module1' with (
  $font: 'san-serif' // add !default flag here if you want `$font` to be overriddable in subtheme
);

//subtheme.scss
@use 'theme' with (
  $color: 'white'
);
```

**Comment by mirisuzanne** [comment]
I thought of that too, but that results in both files using the same final configuration – and this use-case is specifically about getting different configurations in each file…

**Comment by jathak** [comment]
I thought that `theme.scss` and `subtheme.scss` were being compiled separately in this case (which would be the only way [this example](https://github.com/sass/sass/issues/2789#issuecomment-561394622) would work)

**Comment by kevinreilly** [comment]
I've managed to figure out a solution, though it is a bit strange:
```scss
//_module1-config.scss
$module1-config: (
  font: 'serif',
  color: 'black',
);

//_module1.scss
@use 'sass:map';
@use 'module1-config' as *;

$config: $module1-config !default;

.selector {
  font-family: map.get($config, font);
  color: map.get($config, color);
}

//_theme-config.scss
$module1-config: (
  font: 'sans-serif'
);

//theme.scss
@use "sass:map";
@use "sass:meta";
@use 'theme-config';
@use 'module1-config';
@use 'module1' with (
  //merge module1's original configs with the theme's configs
  $config: map.merge(map.get(meta.module-variables(module1-config), module1-config), map.get(meta.module-variables(theme-config), module1-config))
);

//_subtheme-config.scss
$module1-config: (
  color: 'white'
);

//_subtheme.scss
@use "sass:map";
@use "sass:meta";
@use 'module1-config';
@use 'theme-config';
@use 'subtheme-config';

//get module1's original configs
$module1-config: map.get(meta.module-variables(module1-config), module1-config);
//merge module1's original configs with the theme's configs
$module1-theme-config: map.merge(map.get(meta.module-variables(module1-config), module1-config), map.get(meta.module-variables(theme-config), module1-config));
//merge the module1's original configs, the theme's configs, and the subtheme's configs
$module1-subtheme-config: map.merge($module1-theme-config, map.get(meta.module-variables(subtheme-config), module1-config));

@use 'module1' with (
  $config: $module1-subtheme-config
);
```
This results in the desired output below:
```scss
//theme.css
.selector {
  font-family: "sans-serif";
  color: "black";
}

//subtheme.css
.selector {
  font-family: "sans-serif"; //inherited from theme.scss
  color: "white";
}
```
Hopefully there's a better solution than this.
