### ISSUE TITLE
Dynamically define mixin in mixin

### ISSUE THREAD

**Issue by benjaminrobinet** [sass/sass#2795]
Hello, I come to re-open this issue #127 as I found a use case that might show you.

```scss
@mixin font-face( $font-name, $font-path, $font-weight: 400, $font-style: normal ){
    @font-face {
      font-family: $font-name;
      font-style : $font-style;
      font-weight: $font-weight;
      src:
        url('#{$font-path}.woff2') format('woff2'),
        url('#{$font-path}.woff') format('woff'),
        url('#{$font-path}.ttf') format('truetype');
    }

  @mixin font-#{$font-name}-#{$font-weight}-#{$font-style}{
    font-family: $font-name;
    font-style: $font-style;
    font-weight: $font-weight;
  }
}
```

So here is a mixin to build font-faces like that:
```scss
@include font-face("Avenir", "../dist/fonts/Avenir-Roman", normal, normal);
```

And it (should) generates at the same time a mixin to use that font-face like that:
```scss
body{
  @include font-Avenir-normal-normal;
}
```

What do you think about it ?
