### ISSUE TITLE
Provide a way of calling a function that errors when the function is not defined

### ISSUE THREAD

**Issue by BernieSumption** [sass/sass#2810]
If I `@include no-mixin-with-this-name()` then I get an error as expected. If I call `no-function-with-this-name()` it is not an error, but emits the function call source in the CSS output. This makes sense in light of Sass's decision that Sass function calls and CSS function calls share the same syntax. But if I intend to call a Sass function, it would be nice to get some protection against typos or forgetting to include the file where a function is defined.

Some options:

1. Implicit detection of intent to call a Sass function:

```
// this could issue a warning, since presumably you'd only write this code if
// you expect the function to be defined in Sass. Doesn't cover all use cases but
// avoids adding new syntax
@if no-function-with-this-name() {
    // this is always true
}
```

2. Explicit declaration of intent:

```scss
.foo {
    // this would error if the function doesn't exist
    border: @call make-border(red)
}
```

3. Whitelist of allowed CSS functions

Sass could ship with (or accept as a compiler option) a whitelist of valid CSS functions and issue a warning when an unknown function is emitted to CSS.

**Comment by chriseppstein** [comment]
You can build this yourself by defining a new function. E.g. `invoke()` that uses [`call`](https://sass-lang.com/documentation/modules/meta#call) and [`function-exists`](https://sass-lang.com/documentation/modules/meta#function-exists) to ensure it exists prior to calling the function. If using dart-sass you can even name this function `call` because it will be in a different namespace than the `meta.call` function.

**Comment by BernieSumption** [comment]
Thanks for the response @chriseppstein. I'm afraid that solution doesn't work. The issue is that user defined functions can't be called safely, so making a new user-defined function to call a function safely is a non-starter. If you see this code:

```scss
h1 {
    @if invoke(has-borders, headers) {
        border: solid 1px black;
    }
}
```

Then you don't know whether the `@if` condition is going to be always true because it's testing the truthiness of a CSS function call value. It's really easy to forget to include the file that defines the function, or maybe you're switching projects a lot and this project doesn't have an `invoke` function.

If Sass provided a built in "invoke" function, that would fulfil this requirement because it would be reliably available in every file and every project.

The best workaround I've been able to come up with on top of current Sass featrues is a mixin that checks if a function exists:

```scss
h1 {
    @include require-function(has-borders);
    @if has-borders(headers) {
        border: solid 1px black;
    }
}
```

Ugly and verbose, but at least you can tell that it works just by looking at the call site, because if the mixin require-function isn't defined it will be an error.
