### ISSUE TITLE
Overriding variables through nested `@use` doesn't seem possible

### ISSUE THREAD

**Issue by taurean** [sass/sass#2811]
I'm not 100% sure I'm in the right place but this seems like something that should be possible but isn't as far as I can tell. I'm having trouble figuring out how people will override the default values for variables in a framework thing I'm building. Here's a loose example:

```scss
// framework/_variable.scss - operates like a set of design tokens

$variable-1: red !default;
```

```scss
// framework/_module.scss - is dependent on the design tokens

@use "variable" as *;

@mixin mixin-one {
  color: $variable-1;
}
```

```scss
// framework/index.scss - bundles up the framework to be imported together

@forward "module";
```

```scss
// project.scss - a developer using the framework in their own project

@use "framework" as * with (
  $variable-1: blue,
);
```

This gives me an error because `$variable-1` has already been imported by `framework/_module.scss` and cannot be overridden by a new import. Is it possible to circumvent this so that users of the framework can override the variables of the framework with their projects own properties?

**Comment by nex3** [comment]
`framework/_module.scss`'s module doesn't include a variable named `$variable-1`. When you `@use` a module, its variables become available *to use* within your module, but they don't become *part of* your module. You need to use `@forward` for that.

In other words, you need to have a chain of `@forward`s all the way from `framework/_variable.scss` to `framework/index.scss`:

```scss
// framework/_module.scss - is dependent on the design tokens

@forward "variable";
@use "variable" as *;

@mixin mixin-one {
  color: $variable-1;
}
```
