### ISSUE TITLE
:root delcaration issue

### ISSUE THREAD

**Issue by drawcard** [sass/sass#2814]
Hi,

When I write:

```scss
// SCSS

$red: #ff0000;

:root {
--primary-colour: $red;
}
```

I expect to see:

```css
/* CSS */
:root {
--primary-colour: #ff0000;
}
```

But instead I get:

```css
/* CSS */
:root {
--primary-colour: $red;
}
```

It seems like sass or gulp-sass isn't recognising the variable, within a :root declaration?
