### ISSUE TITLE
Extend @content-exists with passing arguments

### ISSUE THREAD

**Issue by markvanwijnen** [sass/sass#2818]
_Consider the following code:_
```scss
@mixin sample(){
    @if content-exists( 'boxed-width' ) {
        .boxed-width, .is-style-boxed-width {
            @content('boxed-width');
        }
    }
    @if content-exists( 'full-width' ) {
        .full-width, .is-style-full-width {
            @content('full-width');
        }
    }
}

@include sample() using ( $size ) {
   @if $size == 'boxed-width' {
        background: red;
    }
}
```
In human language this would mean. If the content exists and is not empty, like boxed-width, add the selectors with the css content and if the content exists but is empty, like full-width, ignore. This would lead to all sorts of powerful combinations.

I noticed a few things:

1. `@if content-exists() {}` within a `@mixin` will result in the error **Libsass: Error: Cannot call content-exists() except within a mixin**
2. `content-exists()` will only check if the `@include` has content attached or not. I would expect if content at all is returned, as in not empty.
3. You can't pass arguments in` content-exists()`;

Am I correct, or am I missing something?
