### ISSUE TITLE
Element.parent selector

### ISSUE THREAD

**Issue by shkm** [sass/sass#282]
For lack of the words for a better title.

Basically, allowing the parent selector to be used as such:

``` scss
.parent-class {
    p& {
        background-color: black;
    }
}
```

to output

``` css
p.parent-class {
    background-color: black;
}
```

Idea & example taken from [StackOverflow](http://stackoverflow.com/questions/9293891/sass-css-target-parent-class-from-child).
