### ISSUE TITLE
@use doesn't fail even if it can't find the file. @use is broken (at-least with webpack)

### ISSUE THREAD

**Issue by nojvek** [sass/sass#2827]
```scss
// _vars.scss
$some-const: 1

// index.scss
@use "somegarbage"
```

this compiles fine. It seems @use doesn't work in sass as promised.

I'm doing

```scss
// _vars.scss
$rem-size: 16px

// index.scss
@use "vars"

html {
  font-size: $rem-size;
}
```

This fails. It says $rem-size not found.

It seems like a basic thing but not working.

----

@import works great, so it seems @use is broken.
```scss
// _vars.scss
$rem-size: 16px

// index.scss
@import "vars"

html {
  font-size: $rem-size;
}
```

I am using the following versions.

```json
"node-sass": "4.13.1"
"sass-loader": "8.0.2",
```

This is the webpack config

```
  {
    test: /\.scss$/,
    include: frontendDir,
    use: [
      {loader: `style-loader`}
      {loader: `css-loader`}
      {loader: `sass-loader`},
    ],
  },
```

Please halp!

**Comment by nex3** [comment]
`@use` doesn't work the same way as `@import`—by default, it makes all members available through a namespace, so you need to write:

```scss
// index.scss
@use "vars";

html {
  font-size: vars.$rem-size;
}
```

See [the documentation](https://sass-lang.com/documentation/at-rules/use) for details.
