### ISSUE TITLE
How to deal with multiple "@media screen"

### ISSUE THREAD

**Issue by yunyuyuan** [sass/sass#2839]
Suppose the following Sass codes:
```sass
@mixin screen_handle{
  @media screen and (max-width: 1200px) and (min-height: 900px) {
    @content
  }
}

#container{
    width: 100%;
    @include screen_handle{
        width: 95%;
    }
    .c1{
        .c2{
            ...many nesting...
            .content{
                padding: 1rem 2rem;
                @include screen_handle{
                    padding: 1rem;
                }
            }
        }
    }
}
```
**The generated CSS is as follows**
```css
#container{
    width: 100%;
}
@media screen and (max-width: 1200px) and (min-height: 900px) {
    #container{
        width: 95%;
    }
}
#container .c1 .c2 ...many nesting... .content{
    padding: 1rem 2rem;
}
@media screen and (max-width: 1200px) and (min-height: 900px) {
    #container .c1 .c2 ...many nesting... .content{
        padding: 1rem;
    }
}
```
This leads to unnecessary repetition of `@media screen and (max-width: 1200px) and (min-height: 900px)`

**Is there any good way to solve it?**
