### ISSUE TITLE
Length of sass ampersand

### ISSUE THREAD

**Issue by ghost** [sass/sass#2844]
Suppose I have this piece of code:

```scss
@mixin test-mixin($argument: &) {
  
  // $argument is ".test" but the length result 1, why?
@debug $argument;
@debug length($argument);  

 @at-root #{$argument} {
    @content
  }
}





// 
.test {
  @include test-mixin{
    color: yellow;
  }
}

```

As you can see $argument output ".test" while the length output 1 (the length of the ampersand). Why this behavior? Why length function doesn't output "5" (the length of the class)?
