### ISSUE TITLE
New Idea for Ampersand

### ISSUE THREAD

**Issue by gisu** [sass/sass#285]
First, I like it with the ampersand Selector to work, little sign big effect;)

But I have an idea, perhaps that will come in order to improve working with mixins and class combinations.

``` sass
=test
    .mixinClass
        height: 20px

.combinatedClass
    background: red
    +test 
```

I got this

``` css
.combinatedClass { background: red; }
.combinatedClass .mixinClass { height: 20px; }
```

This is already sufficient in most cases, but sometimes you want the class of mixins combine with the parent class, like so:

``` css
.combinatedClass { background: red; }
.combinatedClass.mixinClass { height: 20px; } 
```

The Idea is this

``` sass
@mixin test
    .mixinClass
        height: 20px

.combinatedClass
    background: red
    & +test 
```

Nest so they could be used two ways a mixin, as usual, once it comes in a different class or to combine it with the other class. And with the least effort. I do not know what you think, I personally would find it not bad.
