### ISSUE TITLE
Some variable scoping make it impossible to do full static optimization

### ISSUE THREAD

**Issue by mgreter** [sass/sass#2854]
Second attempt trying to illustrate the issue I currently have doing static variable lookup optimizations for LibSass. For some insight what I try to accomplish see older (partially wrong) issue at https://github.com/sass/sass/issues/2852.

I believe, after testing it with my latest branch, that there are mainly 3 issues that make this optimization impossible. One will go away once global variables are forced to be explicitly created (currently it gives a deprecation warning), but there are at least two other situations.

```scss
@mixin import-google-fonts() {
  @import url("http://fonts.googleapis.com/css?family=#{$family}");
}
$family: unquote("Droid+Sans");
@include import-google-fonts();
```

During parsing the variable used in the mixin isn't yet known to the compiler. IMO most programing languages will therefore throw an error. So my question would be if it is OK for LibSass to force the variable declaration before it is mentioned in the mixin?

The second issue is how variables are referenced in control-loops.
```scss
$y: 0;
div {
  for {
    @for $z from 1 through 5 {
      $y: $y + 1;
      local: $y;
    }
    lexical: $y;
  }
  global: $y;
}
```

The only culprit is the `$y: $y + 1;` assignment. In Sass the `$y` references the lexical `$y` in the first iteration and on all other runs it references the local `$y` that was created in the first run. I tried to visualize this a bit better with a screenshot:

![image](https://user-images.githubusercontent.com/282293/80865674-370a8300-8c8b-11ea-94be-3b3face90883.png)

IMO most programming languages will always reference the lexical `$y`. Basically the scope will always be newly initialized on consecutive runs. I see that this is a breaking change, but I could probably detect this to deprecate it properly it in LibSass, if it is OK to for an implementation to change this detail?

**Comment by mgreter** [comment]
FWIW I made some more tests and also took a few more specific benchmarks. First I think this might not be such a big issue for LibSass after all. It looks like I need dynamic variable lookup during runtime anyway, since the C-API should be able to query it. There are also the `variable-exists` functions, although those could be optimized during compile time too AFAICT.

So I can't get rid of the memory, and since I move the lookup maps from parser to evaluation, the overhead might not be that big anyway. I then benchmarked what this means in real-world. Note that this optimization should most notably kick in when we re-use the same stylesheet, e.g. it is imported multiple times. Another use-case is with long-running processes like when you have a file-watcher during development (which is something I want to make possible for LibSass 4).

The benchmark was done with [bolt-bench][1]. I simply included the main file multiple times. It's probably not the best way to do it, but it gave some estimations. The partial optimizations means that I disabled the static optimization inside loops, as it IMO is the only way to trigger the mentioned issues from above.

```
with full optimization
1: 1.11s
3: 2.72s
9: ~8.1s

with partial optimization
1: 1.11s
3: 2.72s
9: ~8.1s

with no optimizations
1: 1.15s
3: 2.93s
9: ~8.9s
```

IMO the performance gain is quite noticeable and it seems loops are not that often used that it will have much impact (can of course be different if loops are heavily utilized). I think the questions in the initial post are still somewhat valid to look into though. 


[1]: https://github.com/sass/sass/files/3587253/bolt-bench.zip

**Comment by mgreter** [comment]
Sorry to hijack this a little, but I'm still finding out details I would like to document. Looked again at the `while` rule and there it dawned to me why this behavior is necessary. Consider the following loop:

```scss
$z: 1;
while {
  @while $z < 4 {
    z: $z;
    $z: 5;
  }
  z: $z;
}
```
Here the `$z < 4` will first check against the outer `$z`, and on consecutive runs it will check against the inner `$z`, that was created in the first run. Without this behavior, it would be impossible to alter the variable used in the condition, since you can not assign to any lexical variable in Sass, since the syntax will always create a local variable. So that seems to explain why this behavior exists.

But it surely can lead to some strange stuff. Consider the following example:

```scss
$z: 1;
while {
  @while $z < 4 {
    z: $z;
    $z: $z;
    $z: 5 !global;
  }
  z: $z;
}
```

Not that easy to spot why this never completes. Anyway, that kinda clears things up a little for me. 

Just to be complete, I also checked out something with `@for` rules:

```scss
$to: 5;
$from: 1;
for {
  @for $z from $from through $to {
    from: $from;
    to: $to;
    z: $z;
    $to: 8;
    $to: 8 !global;
    $from: 4;
    $from: 4 !global;
  }
  from: $from;
  to: $to;
}
```

Conclusion here is that both `from` and `through` arguments cannot be overridden.
Somewhat expected but wanted to be sure.
