### ISSUE TITLE
selector name transformations and scoping?

### ISSUE THREAD

**Issue by dakom** [sass/sass#2857]
What do y'all think about adding the ability for selector name transformations? The use case I have in mind is controlling scope and not polluting the global namespace - something like the way the webpack css-loader [does it with modules](https://webpack.js.org/loaders/css-loader/#modules)?

I think this flows pretty naturally from the semantics in the spec and could be done with a simple `@rename` at-rule. I only looked at the spec briefly, so I won't propose the exact language, but something like this:

```css
/* path/to/main-menu.css */
@rename nav {
  ul {
    margin: 0;
    padding: 0;
    list-style: none;
  }
}
```

could transform to this:

```css
nav__path-to-main-menu ul {
  margin: 0;
  padding: 0;
  list-style: none;
}
```

The `path-to-menu-menu` part of the appended string could instead be a hash of the path, and accept similar options to [loader-utils](https://github.com/webpack/loader-utils#interpolatename) - though if the concept here is approved I'd rather have the simple pathname concatenation soon, or maybe with base64 as a config option, and then add the other hash options in the future.

One might ask - "why do this if there's already webpack plugins?"

Well - I'm not using webpack but do want to use sass (via the Dart binary) :)
