### ISSUE TITLE
Can't @use mixin, but can @import

### ISSUE THREAD

**Issue by dakom** [sass/sass#2858]
I have a top-level file that only has:

```css
@mixin bg_img($path) {
  background-image: url("http://localhost:4102/app/ui/" + $path);
}
```

If I `@import` it, everything is fine. If I `@use` it, then it doesn't come through. For example, this fails, but if I change the `@use` to `@import`, it succeeds:

```css
@use 'mixins';

.bg {
    @include bg_img("photo.jpg");
}
```

Side point: the file is minimal on purpose - I plan to rewrite it just before running `sass` so that the string can be replaced (depending on whether it's in production or dev environment). Is there a better way to do that?
