### ISSUE TITLE
[Feature Request] Defining dynamic variables.

### ISSUE THREAD

**Issue by sugoidesune** [sass/sass#2864]
According to the official Sass documentation:
### Users occasionally want to use interpolation to define a variable name based on another variable. 

Sounds good to me!

Possible Syntax, but the Syntax can be any.
```
.global {
    @each $key, $value in $theme-light {
        '$'+#{unquote($key)}: $value !global;
      }
}
```

### Sass doesn’t allow this, because it makes it much harder to tell at a glance which variables are defined where.

- Crippling users abilities is arguably even worse because it creates manual work and ->.
-  Forces developers to adapt strange and obscure workarounds and hacks that create 10x the logical overhead.
- It is a completely arbitrary to draw the line here.
- If it makes sense to allow the creation of hundreds of helper classes like `.text-green-darken5` then generating variables should be even more so allowed.
- Also Generating variables is free. They don't end up in the compiled code.

One of my usecases:

```scss
$yellow: yellow; // perfect global variables
$green: green;

// lets export them to javascript:
export: {
yellow: $yellow;
green: $green;
}
// well now thats ugly, will i have to copy paste it each time i make changes?
// lets try this:

$colors: (
 yellow: $yellow;
 green: $green;
)

:export {
  @each $key, $value in $colors {
    #{unquote($key)}: $value;
  }
}

// Now i lost my global variables and am stuck using this clunky syntax map.get($colors, "yellow");
// Thats even worse!

```
I either give up on global variables or copy paste things 2 lines below each other.
