### ISSUE TITLE
Issue in css output

### ISSUE THREAD

**Issue by Unknow-max** [sass/sass#2869]
Hi everyone,

I have a small issue in my compiled css file. Suppose that my scss is like this:

```scss
/*
* 1. Set base font properties.
* 2. Remove highlight color on mobile (webkit).
* 3. Improve font rendering.
* 4. Make the footer stick to the bottom of the page.
* 5. Costumize the site's scrollbar (webkit).
----------------------------------------------------*/

body {
  font: 1.8rem/1.15 fn-family(standard); /* 1 */
  background-color: color(black, bg);
  color: color(white);
  -webkit-tap-highlight-color: transparent; /* 2 */
  -webkit-font-smoothing: antialiased; /* 3 */
  -moz-osx-font-smoothing: grayscale; /* 3 */
  display: flex; /* 4 */
  flex-direction: column; /* 4 */
  height: 100%; /* 4 */
  
}

```

The expected output is:

```scss
/*
* 1. Set base font properties.
* 2. Remove highlight color on mobile (webkit).
* 3. Improve font rendering.
* 4. Make the footer stick to the bottom of the page.
* 5. Costumize the site's scrollbar (webkit).
----------------------------------------------------*/

body {
  font: 1.8rem/1.15 fn-family(standard); /* 1 */
  background-color: color(black, bg);
  color: color(white);
  -webkit-tap-highlight-color: transparent; /* 2 */
  -webkit-font-smoothing: antialiased; /* 3 */
  -moz-osx-font-smoothing: grayscale; /* 3 */
  display: flex; /* 4 */
  flex-direction: column; /* 4 */
  height: 100%; /* 4 */
  
}

```
As you can see, the same.

But the real behavior is:

```scss
/*
* 1. Set base font properties.
* 2. Remove highlight color on mobile (webkit).
* 3. Improve font rendering.
* 4. Make the footer stick to the bottom of the page.
* 5. Costumize the site's scrollbar (webkit).
----------------------------------------------------*/
body {
  font: 1.8rem/1.15 fn-family(standard);
  /* 1 */
  background-color: color(black, bg);
  color: color(white);
  -webkit-tap-highlight-color: transparent;
  /* 2 */
  -webkit-font-smoothing: antialiased;
  /* 3 */
  -moz-osx-font-smoothing: grayscale;
  /* 3 */
  display: flex;
  /* 4 */
  flex-direction: column;
  /* 4 */
  height: 100%;
  /* 4 */
}

```

You can cleary see that sass wrap the line comments, like they were properties.
Is this a bug?
