### ISSUE TITLE
Should placeholders be scoped/namespaced like other module members?

### ISSUE THREAD

**Issue by nategreen** [sass/sass#2872]
```scss
// library/_button.scss
%root {
  --button-background: red;

  background: var(--button-background);
}

%label {
  --button-color: white;
}

%hover {
  --button-background: pink;
}

// _downstream.scss
@use "library/button" as button;

.special-button {
  @extend button.%default;

  border-radius: 4px;

  &:hover {
    @extend button.%hover;
  }
}
```

Why aren't placeholders scoped and namespaced like the rest of a module's members? (Especially considering that they can be made private like other types of members can.)

It seems like if nothing else, the namespacing benefits that other module members enjoy would extend also to placeholders (no pun intended). With `@use` we can now write considerably more terse names for mixins, functions, and variables, but placeholders still need to be painfully long and specific, or they'll get conflated with others in downstream modules.

Sort of related to #2871 but seemed separate since it's a question you might be able to easily answer and close.
