### ISSUE TITLE
Import css file into the sass tree

### ISSUE THREAD

**Issue by Hideman85** [sass/sass#2874]
Hi sass community,

I'm trying to find a solution to that simple case.

I want to be able to import a css file (that I can't modify) into my sass tree basically for having it applied only in a part of my document.
```sass
.myContainer {
  @import 'path/to/myfile.css'
}
```

Only solutions that I currently found is by using Mixin the idea is not bad but you have to modify your css file into a sass mixin that for my case I can't.

Do you guys have a solution for that?

**Comment by Awjin** [comment]
You can import plain css files by excluding the file extension. https://sass-lang.com/documentation/at-rules/import#importing-css

**Comment by Hideman85** [comment]
Dammit it was the extension, alright that solve my mistake thank you!

Maybe in the doc the example can be improved to also show that behavior:
```scss
// link.css
a {
  color: red;
}
// main.scss
.myClass {
  @import './link';
}
// Compiled to 
.myClass a {
  color: red;
}
```
