### ISSUE TITLE
box-shadow inside a mixin does not produce the correct output

### ISSUE THREAD

**Issue by rickyhopkins** [sass/sass#2877]
I have a mixin to produce a bottom border on an element using a `box-shadow` instead of `border`, it looks a little something like this:
```scss
@mixin border-bottom($weight: 1px) {
	box-shadow: inset 0 -$weight 0 0 blue;
}
```

But when I use this in my class the leading 0 drops off the output:

```scss
.class {
	@include border-bottom()
}
```
Compiles to:
```css
.class {
	box-shadow: inset -1px 0 0 blue;
}
```

This puts the shadow on the right hand side instead of the bottom as it would if I used `box-shadow: inset 0 -1px 0 0 blue;`

If I add an additional leading 0 it seems to work correctly.

[Codepen example](https://codepen.io/rickyhopkins/pen/pogpozW)
