### ISSUE TITLE
Unused placeholder selector still outputs empty `@media` block

### ISSUE THREAD

**Issue by hail2u** [sass/sass#288]
Unused placeholder selector should not be rendered to CSS.

Input:

``` scss
%placeholder {
  @media screen {
    outline: 1px solid #f0f;
  }
}

.foo {
  margin: 1em;
}
```

Output:

``` css
@media screen { }

.foo {
  margin: 1em; }
```

Tested on Sass 3.2.0.alpha.76 (Bleeding Edge) on ruby 1.9.3p0 (2011-10-30) [i386-mingw32].
