### ISSUE TITLE
Forward same file multiple times, but with different configurations

### ISSUE THREAD

**Issue by johannpinson** [sass/sass#2880]
Hello,

I try to use the same SCSS file but to generate different CSS, by using specific configurations on each "import".
This is a minimal setup for example:

```scss
// _components.scss
$name: "test" !default;
$color: red !default;

.#{$name} {
  color: $color;
}

// index.scss
@forward "component" with (
  $name: "link",
  $color: blue
);
@forward "component" with (
  $name: "external",
  $color: purple
);


// Expected CSS
.link {
  color: blue;
}
.external {
  color: purple
}

```

But i get this error:

```
Error: This module was already loaded, so it can't be configured using "with".
   ╷
52 │ ┌ @forward "../../src/components/component" with (
53 │ │   $name: "link",
54 │ │   $color: blue,
55 │ │ );
   │ └─^ original load
56 │ ┌ @forward "../../src/components/component" with (
57 │ │   $name: "external",
58 │ │   $color: purple,
59 │ │ );
   │ └─^ new load
   ╵
  app/styles/index.scss 56:1  root stylesheet
```

I already try with `@use` rule but I got the same result.
It may not be possible giving the current behavior of Sass Modules, but there is maybe a workaround to make it work.

I'm using the v1.26.10 of `sass` package (with gulp-sass).

Thanks for the help and advices 👍

**Comment by mirisuzanne** [comment]
The purpose of module configuration is to provide an _initial_ or default value for the entire compilation, set & compiled only once. Your use-case is a better fit for mixins, which are designed for re-compiling the same code over and over, with different parameters. You can use both together, but they serve different functions:

```scss
// _components.scss
$color: red !default;

@mixin build($name, $color: $color) {
  .#{$name} {
    color: $color;
  }
}

// index.scss
/* change global default configuration using "with" */
@use "components" with ($color: blue);

/* use mixins for re-compiling the same code with different parameters */
@include components.build(
  $name: "external",
  $color: purple
);
@include components.build(
  $name: "default"
);
```
