### ISSUE TITLE
Handling of unterminated CSS custom properties

### ISSUE THREAD

**Issue by rich-clark** [sass/sass#2884]
I'm using Sass in an application that also uses CSS custom properties and I've noticed that uncompiled Sass is making it through the Sass compiler if a Sass declaration follows a CSS custom property declaration that has not been properly terminated with a semicolon (examples below). 

Short term, I can fix these issues in my codebase, but in my opinion, expected behavior is that the Sass compiler throws an `expected ";"` error if a CSS custom property declaration is not properly terminated, as it does when any other declaration is not terminated. 

I realize that the syntax for custom property declarations in the [CSS spec](https://drafts.csswg.org/css-variables-1/#syntax) is "extremely permissive", but it seems like there should be some way to detect if a custom property declaration has not been properly terminated, since the browser can process these correctly, and the PostCSS parser will throw an error. Prettier will also add the missing semicolon. (The other parsers I've tested through [astexplorer](https://astexplorer.net/)—cssom, csstree, and rework—treat these as the Sass compiler does currently though.)

---

These were all tested using dart-sass installed through npm:

```
sass --version
1.26.10 compiled with dart2js 2.8.4
```

### Spec 1

Input:

```scss
foo {
  --bar: yellow
  // a comment
}
```

Actual output:

```css
foo {
  --bar: yellow
  // a comment ;
}
```

Expected output:

```
expected ";".
  ╷
2 │   --bar: yellow
  │        ^
  ╵
  stdin 2:8  root stylesheet on line 2 at column 8
```

### Spec 2

Input:

```scss
@mixin blue {
  color: blue;
}

foo {
  --bar: yellow
  @include blue;
}
```

Actual output:

```css
foo {
  --bar: yellow
  @include blue;
}
```

Expected output:

```
expected ";".
  ╷
2 │   --bar: yellow
  │        ^
  ╵
  stdin 6:8  root stylesheet on line 6 at column 8
```

**Comment by mirisuzanne** [comment]
@rich-clark I'm not sure what you mean by "the browser can process these correctly". Your samples are valid CSS, so "correct" in this case is treating both lines as part of the custom property value, which is what we do, and what I see in Firefox dev tools without any pre-processing: `--bar: yellow // a comment ;`

Sass is designed to be a superset of CSS, and needs to support all valid CSS. It makes sense to me that parsers also need to allow all valid CSS. Like them, our goal is not to be an opinionated linter, or catch typos (we also won't error if you misspell  the `color` property, like a linter often would). Tools like Prettier seem like the proper place for that to happen.

**Comment by rich-clark** [comment]
Thanks for looking into this! You're right in that the browser treats these differently than I thought it would. I can use a linter, but it's still not clear to me why the Sass compiler should throw an error if you forget to add a semicolon to the end of most property declarations but not custom property declarations; the Sass compiler prevents me from writing:

```scss
$blue: blue;
foo {
  color: red
  background-color: $blue
}
```

I don't understand why it shouldn't also prevent me from writing:

```scss
$blue: blue;
foo {
  --color: red
  background-color: $blue
}
```

Especially since the latter results in a Sass variable (`$blue`) showing up in compiled CSS. It might "correct", but it's certainly not what the developer intended `color: red background-color: $blue` seems identical in terms of correctness to me as `--color: red background-color: $blue` does.
