### ISSUE TITLE
Error: There is no module with the namespace

### ISSUE THREAD

**Issue by MH15** [sass/sass#2885]
I have a file named `_variables.scss` with variables defined at the root level. I `use` this file in my main file `main.scss`, and attempt to reference the variables defined in `_variables.scss` by doing:
```scss
@use "variables"

body {
    background: variables.$background-color;
}
```
This doesn't work, and throws the error "Error: There is no module with the namespace "variables"".
