### ISSUE TITLE
Property with null value is not omitted if it has !important flag.

### ISSUE THREAD

**Issue by mihkeleidast** [sass/sass#2886]
Given the following code:
```
// null value example
$some-value: null !default;

.class {
  color: $some-value;
  color: $some-value !important;
}
```
The first color property is omitted since it's value is `null`. The second is not omitted and invalid CSS is outputted: `color: !important;`. I'd expect the `!important` flag not to matter when the value is null and both properties to be omitted, but it's not that clear to me what the expected result should be from the [null page](https://sass-lang.com/documentation/values/null).

This can be worked around by using an if rule around the property using important and checking for the variable, so it's not a huge issue.

Playground: https://www.sassmeister.com/gist/b04fe1d7b7902c62593b2afac2516e26

**Comment by connorskees** [comment]
The issue here is that Sass treats `!important` as a value, rather than as a flag. It would likely not be possible to recognize this case without causing backwards-incompatible changes.

Perhaps a cleaner workaround for your use case would be to have a function,
```scss
@function important-if-not-null($value) {
    @if $value {
        @return $value !important;
    }

    @else {
        @return null;
    }
}

$some-null-value: null;
$some-non-null-value: foo;

a {
    color: important-if-not-null($some-null-value);
    color: important-if-not-null($some-non-null-value);
}
```

**Comment by bcbcbcbcbcl** [comment]
@connorskees Do you have any idea why this function `important-if-not-null` is showing an error in visual studio code?

![image](https://user-images.githubusercontent.com/39854319/146546709-109763eb-cfcc-4172-8f8d-00ab550be962.png)

**Comment by connorskees** [comment]
@bcbcbcbcbcl seems like a bug in vscode related to `!important` after `@return`. that's valid SCSS and it compiles in the playground. 
<img width="1401" alt="Captura de Pantalla 2021-12-17 a la(s) 10 25 34 a  m" src="https://user-images.githubusercontent.com/39542938/146567510-6f7f0fd1-ae49-4d15-aef6-090fad55c9b1.png">

**Comment by connorskees** [comment]
if you need a workaround to get rid of the errors, you can assign to a variable before returning,

```scss
@function important-if-not-null($value) {
    @if $value {
        $return: $value !important;
        @return $return;
    } @else {
        @return null;
    }
}

$some-null-value: null;
$some-non-null-value: foo;

a {
    color: important-if-not-null($some-null-value);
    color: important-if-not-null($some-non-null-value);
}
```
