### ISSUE TITLE
:focus-within parsed as attribute selector

### ISSUE THREAD

**Issue by vis97c** [sass/sass#2887]
I'm experiencing a problem with my styles where some pseudo selector are not being parsed correctly.

This for example:

```scss
.x-searchBox-bar {
	width: 100%;
	z-index: 1;
	&:not(:focus-within) ~ .x-searchBox-suggestions:not(:hover) {
		display: none;
	}
}
```

while the expected selector is this:

```scss
.x-searchBox-bar:not(:focus-within) ~ .x-searchBox-suggestions:not(:hover){}
```

instead i'm getting this:

```scss
.x-searchBox-bar:not([focus-within]) ~ .x-searchBox-suggestions:not(:hover){}
```

What i'm doing wrong?

this is what im using in my node enviroment:
node: 12.18.2
```json
{
"sass": "^1.26.10",
"sass-loader": "^9.0.3",
}
```
