### ISSUE TITLE
Variable scope bug

### ISSUE THREAD

**Issue by k-utsumi** [sass/sass#2894]
ref. https://sass-lang.com/documentation/variables#shadowing

```scss
.foo {
  $space: 10px;
  margin: $space;
  
  .bar {
    $space: 15px; // local variable
    margin: $space;
  }
  
  .baz {
    margin: $space;
  }
}
```
　↓↓↓

```css
.foo {
  margin: 10px;
}
.foo .bar {
  margin: 15px;
}
.foo .baz {
  margin: 15px; /* Affected by local variables */
}
```

**Expected behavior**

```css
.foo {
  margin: 10px;
}
.foo .bar {
  margin: 15px;
}
.foo .baz {
  margin: 10px;
}
```

Web service that can test: https://www.sassmeister.com/
