### ISSUE TITLE
CSS variables only support plain strings.

### ISSUE THREAD

**Issue by K4rakara** [sass/sass#2898]
For whatever reason, CSS variables only support plain strings. Even if this is intended behavior, its a very limiting behavior, and should probably be revisited.

Heres a few examples:

scss:
```scss
$foo: #111111;
div {
  --my-value: $foo;
}
```
css:
```css
div {
  --my-value: $foo;
}
```

scss:
```scss
@function my-function($v) {
  @return ""+$v+"px";
}

div {
  --my-value: my-function(5);
  left: --my-value;
}
```
css:
```css
div {
  --my-value: my-function(5);
  left: --my-value;
}
```
