### ISSUE TITLE
How to use `currentColor` with `rgba` ?

### ISSUE THREAD

**Issue by vortesnail** [sass/sass#2907]
index.html :
```html
<div class="btn">button</div>
```

index.scss :
```css
.btn {
    color: #0069ff;
    border: 1px solid currentColor;
    background: rgba(currentColor, 0.1);
}
```

As shown above, I hope to set a transparent background color to `currentColor` through `rgba` , but code like this does not work, what should i do to achieve it? Thanks .

My solution : 
```css
.btn {
    color: #0069ff;
    border: 1px solid currentColor;
    position: relative;

    &::before {
        position: absolute;
        left: 0;
        top: 0;
        content: '';
        width: 100%;
        height: 100%;
        background: currentColor;
        opacity: 0.1;
    }
}
```

but this adds a lot of unnecessary code...

**Comment by mirisuzanne** [comment]
This will not be possible in Sass, because `currentColor` is a variable calculated by the browser at run-time. As a pre-processor, Sass cannot know the value of `currentColor`, and can't adjust it using color functions. Your solution is the best I can think of at this point, besides using JS to do the calculations live in the browser and override your style sheet.

When browsers implement the CSS Color Module Level 5 built-in color functions, that should also make it possible in plain CSS.

**Comment by Alexandre-Fernandez** [comment]
> This will not be possible in Sass, because `currentColor` is a variable calculated by the browser at run-time. As a pre-processor, Sass cannot know the value of `currentColor`, and can't adjust it using color functions. Your solution is the best I can think of at this point, besides using JS to do the calculations live in the browser and override your style sheet.
> 
> When browsers implement the CSS Color Module Level 5 built-in color functions, that should also make it possible in plain CSS.

Just tested the new `color-mix` CSS function on chrome 112 and it doesn't seem to work with `currentColor`.

**Comment by mirisuzanne** [comment]
This is working for me on 112:

```css
html {
  color: red;
  background: color-mix(in oklab, currentColor, blue);
}
```

And all the [Web Platform Tests](https://wpt.fyi/results/css/css-color?label=experimental&label=master&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label:interop-2022-color%20or%20label:interop-2023-color) for `color-mix` with `currentColor` are passing.

**Comment by andrewkuryan** [comment]
Here is the formula for arbitrary `alpha` based on `color-mix`:

```css
html {
    color: red;
    --alpha: 0.2;
    background: color-mix(in srgb, currentColor, rgb(255, 255, 255) calc((1 - var(--alpha)) * 100%));
}
```
