### ISSUE TITLE
Should a placeholder referenced before declaration result in an error?

### ISSUE THREAD

**Issue by mangelozzi** [sass/sass#2908]
I know guys are aware of the shortcommings of `@extend`, but here's the issue (before the proposed solution):
- I expect `.aaa` to have a color of `lime`, but its actually `red`. 
- On a large project, it's hard to know which appears first.

```scss
// SASS                                 CSS
// ----                                 ---
.aaa {
    @extend %placeholder;               .aaa {
    color: lime;                            color: lime;
}                                       }

%placeholder {                          .bbb, .aaa { 
   color: red;                              color: red;    // WARNING: .aaa is actually red, not lime!
}                                       }

.bbb {                                  .bbb {
    @extend %placeholder;                   color: blue;
    color: blue;                         }
}                   
```
If there was an error, that would prevent this unexpected behaviour. A simple error would remove the downside to using @extend. The error could be something like "Placeholder referenced before declaration".

**Comment by jathak** [comment]
This is expected behavior. `@extend` is declarative (similar to CSS itself), where it doesn't matter whether the selector being extended appears before or after the `@extend` rule (or both). Think of extension less as including the extended selector's CSS in the current scope, but instead as the extending selector appearing every where the extended selector does.

In your example, `.aaa` and `.bbb` are used in place of `%placeholder`.

It seems like you want `@extend %placeholder` to be replaced with `color: red`, which isn't really how extend works.

You could achieve the desired effect with a mixin instead:

```scss
.aaa {
    @include placeholder;
    color: lime;
}

@mixin placeholder {
    color: red;
}

.bbb {
    @include placeholder;
    color: blue;
}
```

This would error. Moving the mixin declaration before the `.aaa` rule would result in your expected output of

```css
.aaa {
  color: red;
  color: lime;
}

.bbb {
  color: red;
  color: blue;
}
```
