### ISSUE TITLE
CSS variables/custom-properties division interfered by SCSS

### ISSUE THREAD

**Issue by yairEO** [sass/sass#2924]
https://stackoverflow.com/q/64352873/104380
https://jsbin.com/zaduhiq/1/edit?html,css,js,output

```css
div{
  --a: 100 / 2;
  height: calc(var(--a) * 1px);
  background: red;
}
```

will not work in SCSS but works well without SCSS.
definition of "work" is that the `height` is set as expected (`50px`)
