### ISSUE TITLE
Increased compatibility with CSS custom properties

### ISSUE THREAD

**Issue by calebdwilliams** [sass/sass#2928]
First off, I love SASS/SCSS and have been using it for years; however, as browsers have continued to evolve some of the core features of SASS have made their way into vanilla CSS. I'd love to see a new variable type in SASS (maybe with a different sigil prefix than `$` that would be automatically output as a CSS variable with a fallback value. For example:

```scss
#primaryColor: tomato;

.selector {
  background: #primaryColor;
}
```

could be output as

```css
.selector {
  background: tomato;
  background: var(--primaryColor, tomato);
}
```

This is matching some of the behavior in PostCSS and would make the transition to using CSS custom properties much easier for a large portion of SCSS users.

The question I still have is how to declare the variable scope (do we write the value to `:root` or `:host`, etc.).
