### ISSUE TITLE
Access the map value from within the map itself

### ISSUE THREAD

**Issue by babakfp** [sass/sass#2930]
_Hello_.
```scss
@use "sass:map";

$my-map: ( // what I want...
  color: gray, // ...is access to this...
  background-color: map.get($my-map, color), // ...from hire.
) // is it possible?
```

**Comment by fromaline** [comment]
@babakfp, I am pretty sure we need some analog of `this` (like in JS) to do it this way. 
Basically a pointer to place in memory where the object is stored, because when you accessing `$my-map` from inside, it doesn't exist yet.

**Comment by babakfp** [comment]
Let's have an example from Bootstrap 5. It has a `$colors` map. In the `$utilities` map, `$colors` gets called. What if I want to write the colors and utilities inside one single map? I kinda solved it but it's not the same and it takes a lot of work.

```scss
@use "sass:map";

$my-map: (
  color: gray,
);

$my-map: map.merge($my-map, (
  background-color: map.get($my-map, color),
));

.my-map {
  color: map.get($my-map, color);
  background-color: map.get($my-map, background-color);
}

// output
// .my-map {
//   color: gray;
//   background-color: gray;
// }


// - deep maps


$my-deep-map: (
  test: (
    color: gray,
  )
);

$my-deep-map: map.deep-merge($my-deep-map, (
  test: (
    background-color: map.get($my-deep-map, test, color),
  )
));

.my-deep-map {
  color: map.get($my-deep-map, test, color);
  background-color: map.get($my-deep-map, test, background-color);
}

// output
.my-deep-map {
  color: gray;
  background-color: gray;
}
```

This is a very useful feature and I'm wondering that what should I do to sass developer/developers make it happen?

**Comment by jathak** [comment]
Unfortunately, this feature is probably more trouble than it's worth (both in terms of implementation cost, and in terms of complexity of the language as a whole for users to understand). This would require allowing maps to be referenced before they are finished being created.

If you do need to use the same value for multiple keys in a map, you should factor out that expression into a variable and then reference the variable twice. e.g.:
```scss
$color: gray;
$my-map: (
  color: $color,
  background-color: $color
);
```

**Comment by babakfp** [comment]
Hello again.
Yes, it's true. There is another scenario too. What if, later I what to change to value of the map or merge it, then the value of the variable going to be the old value. Example:

```scss

@use "sass:map";

$map: (
  keyOne: valueOne
);

$mapRef: $map;

$map: map.deep-merge($map, (
  keyOne: valueOneEdited
));

.test {
  test: map.get($mapRef, keyOne);
}

// Output:
.test {
  test: valueOne;
}


```

### What is the solution?
You can use a function to refer to that map. Example:
```scss
@use "sass:map";

$map: (
  keyOne: valueOne
);

@function getMap() {
  @return $map;
}

$map: map.deep-merge($map, (
  keyOne: valueOneEdited
));

.test {
  test: map.get(getMap(), keyOne);
}

// Output:
.test {
  test: valueOneEdited;
}

```

If you don't want to use functions for this, after the `map.deep-merge`, you can set the value of `$mapRef` again. this will do the trick.
```scss

@use "sass:map";

$map: (
  keyOne: valueOne
);

$mapRef: $map;

$map: map.deep-merge($map, (
  keyOne: valueOneEdited
));

$mapRef: $map;

.test {
  test: map.get($mapRef, keyOne);
}

// Output:
.test {
  test: valueOneEdited;
}

```

Right now I don't have any problem, then who am I write this for:neutral_face:?
Thank you for reading this, have an awesome day/night.

**Comment by kerryj89** [comment]
@babakfp 

Maps are immutable, so when you do `$mapRef: $map` you are simply making a copy of `$map` at that point in time and assigning it to `$mapRef` and there is no variable pointer/reference being made between the two.  Side note: Variables _inside_ the map are parsed and saved down as values at that point in time as well and thus do not "update" in the map if re-assigned at a later point.

All you need to do to have your example working in your last post is move `$mapRef: $map;` to below the `$map: map.deep-merge(...)` statement.

```scss
@use "sass:map";

$map: (
  keyOne: valueOne
);

$map: map.deep-merge($map, (
  keyOne: valueOneEdited
));

$mapRef: $map;

.test {
  test: map.get($mapRef, keyOne);
}

// Output:
.test {
  test: valueOne;
}
```

**Comment by mirisuzanne** [comment]
If anyone is interested, I've used various workarounds for this over the years. I even maintain a tool that is built around exactly this feature: https://www.oddbird.net/accoutrement/. It works by adding a `#key (<functions>)` syntax that is computed whenever the map is called:

```scss
$colors: (
  'brand': rgb(13, 127, 165),
  'accent': '#brand',
  'text': '#accent' ('shade': 75%),
);

html (
  color: color('text');
);
```

That gives us both internal map reference, and dynamic calculation when values change. The downsides are a new syntax, and a slightly slower compile. (The latter should be helped by having Sass nested-map functions available now, just need to make the update).

But lately I've been moving away from that, and using Sass modules to auto-construct maps from variables. Rather than a `colors` map, I start with a `_colors.scss` partial, with variables that can reference each other easily:

```scss
// _colors.scss
$brand: rgb(13, 127, 165);
$accent: $brand;
$text: shade($accent, 75%);
```

Then I convert the module-variables to a map on-import, whenever I need it in map-form (for loops, etc):

```scss
@use 'colors';
@use 'sass:meta';

// a map of all the color variables, with variable names converted to map keys
$colors: meta.module-variables('colors');
```

That covers most of the use-cases for us, without any dependencies. Hope that's helpful.

**Comment by kerryj89** [comment]
Thank you for posting your solutions @mirisuzanne.  I wish the first example were a native feature, but the second example will do well.  Posting my silly story here, perhaps Google will pick up on it because my searches for sass map self-referencing workarounds were met with roadblocks.

--

Sass maps do not allow its members to reference other members.

This won't work...
```scss
$map: (
  a: red,
  b: map.get($map, a)
);
```

So then you try...
```scss
$a: red;
$b: $a;

map: (
  a: $a,
  b: $b
);
```

Hah, that works!  But now you need to change `$a` to blue.  Easy enough right?

`$a: blue;`

You then compile:
```scss
.test {
  color: map-get($map, a);
}
```

Wait, why is it still outputting red?

Hmm, there's a map-merge function, maybe this is what I need to update the map.

`$map: map-merge($map, (a: $a))`

So you test again:
```scss
.test {
  color: map-get($map, a);
}
```

Aha! You get blue - Woo! You then go on your merry way until you need to retrieve b...
```scss
.test-2 {
  color: map-get($map, b);
}
```

And see that it is outputting red. Why is it outputting red when `$b` is supposed to reference `$a`?

Well, when you do the following:
```scss
$a: red;
$b: $a;

$map: (
  a: $a,
  b: $b
);
```

You aren't actually storing the variable references to the map. You are storing the variables resolved value at that point in time:
```scss
$map: (
  a: red,
  b: red
);
```

Hence why `b` is continuing to output red below even though you've map-merged with `$map: $map-merge($map, (a: blue))` and expected `$b` to point to the updated a value:
```scss
$map: (
  a: blue,
  b: red
);
```

Because in your mind, the map looks like this and holds internal references:
```scss
$map: (
  a: blue,
  b: map.get($map, a) // 'blue'
)
```

**Comment by kerryj89** [comment]
Sorry to ping you again @mirisuzanne but I can't get your second example to resolve the references after updating one of its values.  I guess my assumption was wrong in thinking using `meta.module-variables()` would "reparse" the file before storing it into a map?

```scss
// _colors.scss
$brand: rgb(13, 127, 165);
$accent: $brand;
$text: shade($accent, 75%);
```

```scss
@use 'colors';
@use 'sass:meta';

// a map of all the color variables, with variable names converted to map keys
$colors: meta.module-variables('colors');

@debug $colors;
// Outputs as expected: ("brand": #0d7fa5, "accent": #0d7fa5, "text": shade(#0d7fa5, 75%))

colors.$brand: red;

$colors: meta.module-variables('colors');

@debug $colors;
// Outputs: ("brand": red, "accent": #0d7fa5, "text": shade(#0d7fa5, 75%))
// Expected: ("brand": red, "accent": red, "text": shade(red, 75%))
```

--

In my situation I have an input that is defined something like this:

```scss
// _variables.scss

$input-bg:           white !default;
$input-color:        black !default;
$input-icon-color:   $input-color !default;
$input-border-color: $input-color !default;
```

In a programmatic sense I am trying to create a constructor/template to instantiate variances from.  Let it have sane defaults with minimal effort needed to create a variation of it (thanks to variable referencing), yet allow the user a chance to make their own changes to the default references if needed.

I tried using a map at first but unfortunately it seems that maps don't save variables as references but saves their resolved value.

Any advice?  Thanks!

**Comment by mirisuzanne** [comment]
Yeah, that's a common pattern in Sass, and there are multiple solutions outside using self-referential maps.

Modules with `!default` do give users the ability to customize the values dynamically *before compilation*. If the tool only needs to be configured once per entrypoint/compilation-path, this approach works great.

```scss
@use 'variables' with ($input-color: blue);
// $input-bg: white; $input-color: blue; $input-icon-color: blue; $input-border-color: $input-blue;
```

If users need to redefine the variables multiple times per compile, mixins and functions are designed for exactly that: pass in any set of arguments, and re-generate return/output values based on the new input. You can even create a mixin that updates global variables with the `!global` flag, or a function that generates your initial map, and can be called to re-generate that map based on new inputs.

```scss
@function input-colors($bg: white, $color: black, $icon: $color, $border: $color) {
  @return (
    bg: $bg,
    color: $color,
    icon: $icon,
    border: $border,
  );
}

$default-map: input-colors();
$user-map: input-colors(papayawhip, maroon);
```
