### ISSUE TITLE
The unit of the variable for @for is inconsistent between implementations

### ISSUE THREAD

**Issue by stof** [sass/sass#2931]
With this input

```scss
test {
    @for $i from 12px to 13px {
        content: unit($i);
    }
}
```

I get the following output on ruby-sass 3.7.4 and libsass 3.5.5 (these are the versions available on https://www.sassmeister.com/):

```css
test {
  content: "px";
}
```

But I get this output on dart-sass 1.26.10 and 1.26.11

```css
test {
  content: "";
}
```

IMO, the behavior of ruby-sass and libsass is more logical, as the values for `from` and `to` are handled as unit numbers (including coercing compatible units).
