### ISSUE TITLE
Allow &.&* selector

### ISSUE THREAD

**Issue by fromaline** [sass/sass#2932]
Hi! First of all thanks for a such useful tool! <br>
I am using Sass for quite a while now and usually write class names following BEM methodology. (It's most popular methodology in Russia btw)

My typical HTML looks like this:
```HTML
<div class="foo">
  <div class="foo__bar"></div>
  <div class="foo__bar foo__bar--another"></div>
</div>
```
And sometimes (in niche cases) I want to have such code in CSS:
```css
.foo__bar {
  color: coral;
}

.foo__bar.foo__bar--another {
  color: blue;
}
```
So basically I need to increase selector specificity and in Sass I want to do it this way:
```scss
.foo {
  &__bar {
    color: coral;
    
    &.&--another {
      color: blue;
    }
  }
} 
```
But currently I can't do it, because it causes `Expected identifier` error. <br>
I think it needs to be allowed, especially because it **drastically differes** from [issue#1425](https://github.com/sass/sass/issues/1425)
The key difference is that it could not produce an invalid selector, because the second part `&*` appended to the first part `&.` produces a valid selector even if `&` is an element (not a class).
I could not find any major reason why this may be unwanted behaviour. But I also could be wrong, so any feedback would be greatly appreciated!

**Comment by babakfp** [comment]
Nice.
I tried for almost 30min and could not find any solution.
```scss
// this two works fine.
.foo__bar {
  & + &--another {
    color: blue;
  }
  & &--another {
    color: blue;
  }
}

// output
.foo__bar + .foo__bar--another {
  color: blue;
}
.foo__bar .foo__bar--another {
  color: blue;
}
```

**Comment by babakfp** [comment]
Wait a minute, I'm confused. Why do you want to do such a thing? The risen for using BEM is that to not write such nasty selectors.
In these 30min you literally killed my brain cells.

**Comment by cpoftea** [comment]
You can use `sass:selector` module with `@at-root` rule to create such complex selector.

**Comment by fromaline** [comment]
@babakfp, generally speaking, you are right, BEM is out there to restrict such nasty selector.
So maybe I am just a bad developer but in my experience, you need to have such control over selector specificity on comprehensive projects especially if multiple people work on the frontend part. <br>
For example consider such code
```scss
.button {
  background-color: coral;

  &--unnoticeable {
    background-color: rgba(#ccc, 0.5);

    &:hover {
      background-color: rgba(#ccc, 0.6);
    }
  }

  &--primary {
    color: white;
    background-color: green;
    border-radius: 5px;
    border: 2px solid greenyellow;

    &:hover {
      background-color: orange;
      border-color: palegoldenrod;
    }
  }

  &--secondary {
    color: bisque;
    background-color: saddlebrown;
    border-radius: 7px;
    border: 1px solid yellow;

    &:hover {
      background-color: orchid;
      border-color: royalblue;
    }
  }
}
```
Here `.button--primary` and `.button--secondary`  are used for two main buttons and could have lots of different properties and rules. 
At the same time `.button--unnoticeable` should override only `background-color` of any button (also `background-color` on `hover`), so that you could create `<button class="button button--primary button--unnoticeable"></button>` or add `button--unnoticeable` class from JS at runtime and unnoticeable-related styles would take precedence.

**Comment by fromaline** [comment]
@cpof-tea, you mean something like this?
```scss
@at-root #{selector-append(&, ".button--unnoticeable")} {
  background-color: rgba(#ccc, 0.5);

  &:hover {
    background-color: rgba(#ccc, 0.6);
  }
}
```
If yes, I think it's too verbose for such simple goal. 
Also, I am pretty sure it's unintuitive for newcomers.

**Comment by cpoftea** [comment]
Sure, because it's an advanced selector nesting technique. At least, for now
```scss
@use "sass:selector";

.foo {
  &__bar {
    color: coral;
    
    &#{selector.append(&, '--another')} {
      color: blue;
    }
  }
}
```

**Comment by fromaline** [comment]
@cpof-tea, I get your point it's an advanced technique **on purpose**

**Comment by cpoftea** [comment]
Also, I would recommend you to avoid suffix unions with parent selector. I understand the magic `&` do for those who builds stylesheets with BEM methodology. But overusing `&` can result to complex nesting in source code
```scss
.block {
  $self: &;

  &__elem {
     &_mod_value {
       ...
       @media (...) { ... } // jesus, that nesting level...
     }
  }

  &--mod {
    &__elem { ... } // <- won't work
    #{$self}__elem { // <- meh, but works
      &_mod_value {
        @media (...) { ... } // again?
      }
    }
  }
}
```
And, in general, the purpose of `&` is not for that.

**Comment by fromaline** [comment]
I agree with the first part of your statement, abusing `&` definitely will lead to too much nesting.
But I can't figure out why the purpose of `&` is not nesting, what the purpose then?

**Comment by cpoftea** [comment]
@fromaline Nesting is purpose, right. I mean suffix union classes is not purpose)

**Comment by fromaline** [comment]
Oh, I misunderstood you)

**Comment by russo97** [comment]
> 

Hello from future

You can solve it doing this way

```SCSS
.foo {
  &__bar {
    color: coral;
    
    &#{&}--another {
      color: blue;
    }
  }
}
```

and this will compile the exact snippet you provided in the topic

```CSS
.foo__bar {
  color: coral;
}
.foo__bar.foo__bar--another {
  color: blue;
}
```

Sorry for any mistakes, English is not my native language.
