### ISSUE TITLE
String wrapped in quotes disappears when using it CSS attribute selector in the Each loop

### ISSUE THREAD

**Issue by seahindeniz** [sass/sass#2943]
## input.scss

```scss
$states: (
  accepted: #e3f7ed,
  rejected: #ffe8e5,
  already: #fff3d6,
);

div {
  @each $stateName, $bg-color in $states {
    &[data-status="#{$stateName}"] {
      background: $bg-color;
    }
  }
}
```

## Actual results

```css
div[data-status=accepted] {
  background: #e3f7ed;
}
div[data-status=rejected] {
  background: #ffe8e5;
}
div[data-status=already] {
  background: #fff3d6;
}
```

## Expected result

```css
div[data-status="accepted"] {
  background: #e3f7ed;
}
div[data-status="rejected"] {
  background: #ffe8e5;
}
div[data-status="already"] {
  background: #fff3d6;
}
```

```bash
$ npx sass --version
1.29.0 compiled with dart2js 2.10.3
```

**Comment by seahindeniz** [comment]
I have also tried this odd approach as well 

## Input
```scss
$states: (
  accepted: #e3f7ed,
  rejected: #ffe8e5,
  already: #fff3d6,
);

@function createStatusSelector($state) {
  @return '[data-status="' + quote($state) + '"]';
}

div {
  @each $stateName, $bg-color in $states {
    &#{createStatusSelector($stateName)} {
      /* #{createStatusSelector($stateName)} */
      background: $bg-color;
    }
  }
}
```

## Output 
```css
div[data-status=accepted] {
  /* [data-status="accepted"] */
  background: #e3f7ed;
}
div[data-status=rejected] {
  /* [data-status="rejected"] */
  background: #ffe8e5;
}
div[data-status=already] {
  /* [data-status="already"] */
  background: #fff3d6;
}
```

**Comment by seahindeniz** [comment]
I also tried this and output is really weird

## Input
```scss
div {
  &[data-status="accepted"] {
    background: #e3f7ed;
  }
  &[data-status="rejected"] {
    background: #ffe8e5;
  }
  &[data-status="already"] {
    background: #fff3d6;
  }
}
```

## Output
```css
div[data-status=accepted] {
  background: #e3f7ed;
}
div[data-status=rejected] {
  background: #ffe8e5;
}
div[data-status=already] {
  background: #fff3d6;
}
```

![image](https://user-images.githubusercontent.com/5789670/98411536-44b02380-2087-11eb-9b98-704e2d983dba.png)
