### ISSUE TITLE
remove hyphen(-) if map has key called null?

### ISSUE THREAD

**Issue by devhoussam** [sass/sass#2948]
remove **hyphen(-)** if map $spacers has key called **null**. means it return only the **className** is this case it called **m** without **hyphen(-).**

```
$spacers: (
  0: 0,
  1: 1px,
  2: 2px,
  null: 3px,
  4: 4px,
  8: 8px
) !default;

@each $prop, $abbrev in (margin: m) {
   @each $size, $length in $spacers {
      .#{$abbrev}-#{$size} {
         #{$prop}: $length !important;
      }
   }
}
```

_the result that I get after compiling :_ 

```
.m-0 {
  margin: 0 !important;
}

.m-1 {
  margin: 1px !important;
}

.m-2 {
  margin: 2px !important;
}

// hyphen(-) shouldn't be here
.m- {
  margin: 3px !important;
}

.m-4 {
  margin: 4px !important;
}

.m-8 {
  margin: 8px !important;
}
```

**Comment by zaydek** [comment]
You can use `if()` as a functional expression to trigger conditional behavior. You can always use `@if ... { ... }` and create a conditional block, but I think you want something more subtle like this:

```scss
$spacers: (
  0: 0,
  1: 1px,
  2: 2px,
  null: 3px,
  4: 4px,
  8: 8px
) !default;

@each $shorthand, $prop in (m: margin, p: padding) {
    @each $k, $v in $spacers {
      .#{$shorthand}#{if(not $k, "", "-" + $k)} {
         #{$prop}: $v !important;
      }
    }
}
```

```css
.m-0 {
  margin: 0 !important;
}

.m-1 {
  margin: 1px !important;
}

.m-2 {
  margin: 2px !important;
}

.m {
  margin: 3px !important;
}

.m-4 {
  margin: 4px !important;
}

.m-8 {
  margin: 8px !important;
}

.p-0 {
  padding: 0 !important;
}

.p-1 {
  padding: 1px !important;
}

.p-2 {
  padding: 2px !important;
}

.p {
  padding: 3px !important;
}

.p-4 {
  padding: 4px !important;
}

.p-8 {
  padding: 8px !important;
}
```
