### ISSUE TITLE
@if side effects in @function

### ISSUE THREAD

**Issue by cpoftea** [sass/sass#2949]
There's something wrong with `@if` side effects in `@function`.
A little reproduce below (sass 1.29.0)

`test-module.scss`
```scss
@use "sass:list";

@function get-list($arg) {
  $list: (0, 1, 2);

  @if $arg {
    list.append($list, $arg);
  }

  @return $list;
}
```
`sass -i`
```
>> @use "test-module"
Error: expected "$".
  ╷
7 │     list.append($list, $arg);
  │          ^
  ╵
  test-module.scss 7:10  @use
  - 1:1                  root stylesheet
>>
```

Expected output
```
>> @use "test-module"
>> $a: test-module.get-list(3)
0, 1, 2, 3
>> $b: test-module.get-list()
0, 1, 2
```
