### ISSUE TITLE
Inline if function without @if-false

### ISSUE THREAD

**Issue by babakfp** [sass/sass#2964]
Hello
This is how the inline `if` function works:

```scss
// @function if($condition, $if-true, $if-false) {}

$a: a;
$a: if($a == a, b, a);
@debug $a; // b
```

#### Problem
What if I don't want to rewrite the `$a` with the same value?

I need to inline `if` function, act like the reqular if statment:

```scss
@if $a == a {
  $a: b;
}
```

The logic is if the condition was false, nothing happens and the code inside brackets does not even get read.

#### What is needed

```scss
$a: if($a == a, b); // This code...

$v: null;
.text {
  color: $v // Act like what happens hire
}
```

#### Pleaseeeeee

**Comment by zaydek** [comment]
Even if you wrote something like this:

```scss
@function or($a, $b) {
  @if $a {
    @return $a;
  }
  @return $b;
}
```

Once you do `or($a == a, $b)`, the left-side of the expression evaluates to `true`, not `$a`. You may need to repeat yourself in order to not losing the meaning of `$a`.

**Comment by mirisuzanne** [comment]
I think the first option is what you're looking for, but both of these are valid:

```scss
$a: a;

// use the existing `$a` value when false
$a: if($a == a, b, $a);

// return null (no output) when false
.text {
  color: if($a == a, b, null);
}
```

Closing the issue, since I don't think any new/different behavior is needed here.
