### ISSUE TITLE
Use the "Inline if function" with just 2 arguments

### ISSUE THREAD

**Issue by babakfp** [sass/sass#2966]
#2964 | @mirisuzanne 
OMG, why you closed my issues!. **You misunderstood what I meant**.

```SCSS
$city: "New York";
$city: if($city == "New York", "Los Angeles", "New York"); // be able to write this...
$city: if($city == "New York", "Los Angeles"); // ...like this.
```

- Be possible to use the "inline if function" with 2 arguments.
- If the condition was `true`, you want to do something, if it's not `true`, do nothing. I don't want to rewrite the `$city` with the same value because it's wrong.

```SCSS
// There is a big difference between this:
@if $city == "New York" {
  $city: "Los Angeles";
}
// and this:
$city: if($city == "New York", "Los Angeles", "New York");
```

## Another issue:
This is about one of your pull requests @mirisuzanne. I don't know if anyone sawed this problem or not.
https://github.com/sass/sass/pull/2836#issuecomment-735310573
