### ISSUE TITLE
Generate CSS selector with a slash

### ISSUE THREAD

**Issue by Frzk** [sass/sass#2967]
Hi,

I'd like Sass to automatically create some CSS selectors with a slash in their names, such as `.w-1\/2` (which can seem weird but is very useful, and valid CSS :) ).

My goal is to have something like:

In `_base.scss`, declare:

```
$width_ratios: 1/2, 1/3, 1/4, 1/8, 1/16;
```

Then:

```
@each $r in base.$width_ratios {
    .w-#{$r} {
        width: ($r * 100%);
    }
}
```

I tried a billions things (escaping, replacing, casting, transforming from string to number, ...) without success.

Is there a way to do this ? If not, would it be possible to add _something_ that would allow this kind of construction ?

Thanks a lot :)

**Comment by jathak** [comment]
`/` is not a valid character in a [CSS identifier](https://www.w3.org/TR/css-syntax-3/#ident-token-diagram), so you can't include it in a class name.

**Comment by jathak** [comment]
Looking at your example in particular, the issue is that your ratios are being evaluated into decimals, so you end up with selectors like `.w-0.5` which is invalid (as `.5` is not a valid class selector) and is not what you want anyway.

To include an escaped slash in a selector, you could try something like this instead:

```scss
$width_denoms: 2, 3, 4, 8, 16;

@each $d in $width_denoms {
    .w-1\/#{$d} {
        width: 1/$d * 100%;
    }
}
```

If you have any ratios with numerators other than 1, you could use a list of lists, e.g.

```scss
$widths: 1 2, 1 3, 1 4, 1 8, 1 16;

@each $n, $d in $widths {
    .w-#{$n}\/#{$d} {
        width: $n/$d * 100%;
    }
}
```
