### ISSUE TITLE
Add an implicit $arguments variable for mixins and functions

### ISSUE THREAD

**Issue by richthegeek** [sass/sass#297]
Similar to the Javascript "arguments" variable, it is occasionally useful to have a variable-length number of arguments in a function/mixin.

The only solution that I can think of for this is setting an $arguments variable of type List[Literal] which can then be accessed in at least two ways:
- `@each $arg in $arguments`
- `nth($arguments, 4)`

A sample use case might be linear gradients:

``` scss
@mixin linear-gradient() {
$value: '';
   @each $arg in $arguments {
      $value: $value + $arg;
   }
   @include prefix($value);
}
```

I'm sure there are other times it could be useful as well, but that's the one that interests me for now!
