### ISSUE TITLE
Bug: Overriding variable in shared package doesn't work

### ISSUE THREAD

**Issue by koga73** [sass/sass#2996]
I have a React Storybook application consisting of component packages such as a Button and a Theme package. I am trying to allow the client application to overwrite a brand color in the shared Theme package.

## Storybook Components
theme / button are separate packages

### theme/_colors.scss
```css
$brand: red !default;
```

### theme/theme.scss
This is the main package export for the theme
```css
@forward "colors" as color_*;
```

### button/Button.scss
```css
@use "theme" as theme;

button {
    background-color: theme.$color_brand;
}
```

### button/Button.jsx
```js
import "./Button.scss";

//Component code below
```

### App.scss
```css
@use "theme" as theme with (
    $color_brand: blue
);

h1 {
    color: theme.$color_brand;
}
```

### App.jsx
```js
import React from "react";
import ReactDOM from "react-dom";

import "./App.scss";

import Button from "button";

class App extends React.Component {
	constructor(props) {
		super(props);
	}

	render() {
		return (
			<div>
				{/* Correct: h1 appears blue */}
                                <h1>Example</h1>

                                {/* Problem: Button background is still red */}
				<Button>Submit</Button>
			</div>
		);
	}
}

let domContainer = document.querySelector("#app");
ReactDOM.render(<App />, domContainer);
```

**Description:**
In this example the App sets the brand color to blue (default is red) in the Theme package. Both the Button package and our App use the shared Theme package. 

**Actual:**
The h1 appears blue however the button background appears red

**Expected:**
The h1 and button background should appear blue
