### ISSUE TITLE
CRA: @use with node_modules doesn't work

### ISSUE THREAD

**Issue by baeharam** [sass/sass#3002]
I'm using CRA and dart-sass. I installed some style packages and wanna import style files using `@use` from `node_modules`. However, I cannot resolve path by prefix `~` and `.env` file. How can I solve it? Is this CRA problem?

```scss
@use 'some-style-package' as *;

.test {
  background-color: $blue-50;
}
```

Above code causes error like "Cannot find stylesheet...", but below code works fine.

```scss
@use 'node_modules/some-style-package' as *;

.test {
  background-color: $blue-50;
}
```

Should I add prefix `node_modules` to `@use` when importing from package?

**Comment by Awjin** [comment]
That works. The common solution is to add `node_modules` to [included paths](https://sass-lang.com/documentation/js-api#includepaths), which then lets you write `@use "some-style-package"` without pre-fixing each `@use` path with `node_modules/`.

At a high-level, we want to design and build a native way for Sass to import packages, to better support your use case. See https://github.com/sass/sass/issues/2739 for more context.

**Comment by baeharam** [comment]
@Awjin Thanks for the reply, I retried after removing `node_module` and it works. However, I had to specify specific file name even if that package folder includes `_index.scss`. You can see below `_index` should be included in `@use`.

```scss
@use 'some-style-package/_index' as *;

.test {
  background-color: $blue-50;
}
```

Official document says that `_index.scss` can be skipped.

> If you write an _index.scss or _index.sass in a folder, the index file **will be loaded automatically** when you load the URL for the folder itself.

Then, why it doesn't work like `@use 'some-style-package' as *`?
