### ISSUE TITLE
Silently fail content block arguments if using is omitted.

### ISSUE THREAD

**Issue by jakob-e** [sass/sass#3003]
**Feature request** 
Passing arguments to content blocks is a nice feature but it requires **using** _even if not needed_. 

Example (from the [documentation](https://sass-lang.com/documentation/at-rules/mixin#passing-arguments-to-content-blocks))
```scss
@mixin media($types...) {
  @each $type in $types {
    @media #{$type} {
      @content($type);
    }
  }
}

@include media(screen, print) using ($type) {
  h1 {
    font-size: 40px;
    @if $type == print {
      font-family: Calluna;
    }
  }
}
```

If we want to re-use the media mixin but does not need the passed **$type** we still have to define **using** or it will throw an error _"0 arguments allowed 1 were passed"_
```scss

// Throws error "0 arguments allowed 1 were passed"
@include media(screen, print) {
  h1 {
    font-size: 40px;
  }
}
```

To allow using variables to be optional (provided if present) Sass could **silently fail the error** or as a less preferred alternative provide a method to allow test and switching - eg. (sorry about the naming)

```scss
@if meta.using-exists() { @content($type); }
@else { @content; }
```

I hope you will consider adding this as it will make it even more flexible – e.g. if provided as added value on an existing implementation - old includes will still work as always but new can chose to use the enhancement.

Thank you :-)
