### ISSUE TITLE
Unquote not working on colour string

### ISSUE THREAD

**Issue by MacroMan** [sass/sass#3006]
I am passing in variables to sass using gulp-sass-variables, which will always inject a string.

Unquote doesn't seem to have any effect on my string.

```
$primary: "#ffffff"; // <- Passed in via gulp-sass-variables

$anchor: scale-color(unquote($primary), $lightness: -14%); // Error: $color: #ffffff is not a color.
```

Am I using unquote in the wrong way?

**Comment by Awjin** [comment]
This is because `unquote` still returns a `string`, but without quotes.

**Comment by MacroMan** [comment]
Thanks. 

Is there a way to cast the string to a color? I've searched extensively, but have been unable to find out how.

**Comment by jathak** [comment]
This seems like a bug in gulp-sass-variables. Strings and colors are two different types in Sass, so gulp-sass-variables shouldn't emit colors as strings.

If there's a really compelling reason for adding a function to Sass that parses strings into colors, we might consider doing so, but this is something that should be fixed in gulp-sass-variables instead.

**Comment by abdullahseba** [comment]
@jathak A string to colour function would definitely be useful - to me anyway! 

I have a 'template' which is looped over for all possible combinations and the placeholder value is replaced with the actual value using the following function from CSS tricks:
``` scss
@function str-replace($string, $search, $replace: '') {
  $index: string.index($string, $search);

  @if $index {
    @return string.slice($string, 1, $index - 1) + $replace + str-replace(string.slice($string, $index + string.length($search)), $search, $replace);
  }

  @return $string;
}

```

The problem with this as I discovered is that a string is returned which is usually what you want.  But in the case of colours, there is no way that I can figure to later cast a `string` to `color` hex value. `unquote` and interpolation do not appear to work.
