### ISSUE TITLE
meta.include-context() / meta.mixin-context() 

### ISSUE THREAD

**Issue by jakob-e** [sass/sass#3007]
When assembling a large number of components/mixins into a stylesheet it would be very useful to be able to trace the including context. E.g. a button mixin can be used in multiple places, why the effect of a change to this particular mixin can be hard to predict. 

By exposing a list of including mixins we can trace usage and also create exceptions based on where a mixin is included

It is possible to emulate include-context by using a mixin – but having it out of the box would be awesome 😃
Example: https://www.sassmeister.com/gist/545e474e05b61f518566e5cb777db153

````SCSS
@mixin button {
  button { 
    @debug meta.include-context();

    @if index(meta.include-context(), log-in){
      message: 'login buttons are special';
    }
  }              
}

@mixin card {
  .card { @include button; }
}

@mixin collection {
  .collection { @include card; }
}

@mixin sign-up {
  .sign-up { @include button; }
}

@mixin log-in {
  .log-in { @include button; }
}

@mixin modal {
  .modal { @include log-in; }
}

@mixin sidebar {
  .sidebar {
    @include collection;
    @include button;  
  }
}


//  Assemble
@include button;    //  => button
@include log-in;    //  => log-in, button
@include card;      //  => card, button  
@include collection;//  => collection, card, button
@include sign-up;   //  => sign-up, button
@include sidebar;   //  => sidebar, collection, card, button
                    //  => sidebar, button
@include modal;     //  => modal, log-in, button

````

If included using _dot syntax_ the module could be included  `@include form.button  => 'form.button'` but I'm open to suggestions 😃

**Comment by mirisuzanne** [comment]
This strikes me as exactly the purpose of providing arguments to your mixins:

```css
@mixin button($type: default) {
  button { 
    /* base button styles */

    @if ($type == log-in) {
      message: 'login buttons are special';
    }
  }              
}

@mixin log-in {
  .log-in { @include button(log-in); }
}
```
