### ISSUE TITLE
Using quoted color strings as paramters with map-get returns null

### ISSUE THREAD

**Issue by mdurchholz** [sass/sass#3010]
Stack Overflow: https://stackoverflow.com/questions/66018856/sass-string-to-non-string

I have a scenario where I am using a JSON file in order to dynamically create SASS variables. The plugin ([Gulp-json-css](https://www.npmjs.com/package/gulp-json-css)) can retain the map and array properties, but does not add quotations onto the map keys:

```
$palettes : (color-1: #FF0000, white: #ffffff, grey: (lite: #aaaaaa, base: #999999, dark: #666666), black: #000000);
```

I am running into an issue where map-get() is not able to find the appropriate value if a quoted string is used for the parameter rather than using a unquoted "non-string".

```
map-get($palettes, white) => #ffffff

map-get($palettes, "white") => null
```

Conclusion : `white != "white"`

Sure, you might also think that my conclusion obviously makes sense because `white` is a color.

BUT

The same issue occurs whenever I use the term `grey` as well, which is NOT a color. `gray` with an "a" is the spelling browsers use for their color code.

```
map-get($palettes, grey) => (lite: #aaaaaa, base: #999999, dark: #666666)

map-get($palettes, "grey") => null
```

HOWEVER

What really blows my mind is that `color-1` is working exactly as how I would expect the other two scenarios to work:

```
map-get($palettes, color-1) => #FF0000

map-get($palettes, "color-1") => #FF0000
```

Is this a bug with the Sass code base?

OR

Is there anyway to convert a string into a "non-string"?  I need a way to turn "white" into white in order to appropriately retrieve the correct value using the map-get() function.

----

After doing a little more debugging, I have concluded that there is a bug when a color is used as a "non-string" or "unquoted" map key. 
```
map-get($palettes, "color") => This will always produce null 
```

**Comment by mirisuzanne** [comment]
Keys are allowed to be any data type – but you have to match the type when you set the key, and when you call it. If you use a color for the map key, you cant use a string to call it. The same is true in reverse. You'll find that both `grey` & `gray` are [valid color keywords](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#color_keywords) (one since CSS1, the other since CSS3). When you add quotes to a color keyword, it becomes a string. But `color-1` is a string with or without quotes - so there is no change in type.

```scss
$palettes: (
  gray: color,
  grey: another color,
  'gray': string,
  'grey': another string,
);

map-get($palettes, gray) => color
map-get($palettes, grey) => another color
map-get($palettes, "gray") => string
map-get($palettes, "grey") => another string
```

**Comment by mdurchholz** [comment]
I'm not sure why you closed this so quickly. I am in a scenario where I don't have total control over whether I have quotes included in my variable map.

**Comment by mdurchholz** [comment]
Why is there not a way to go from a string to a "non-string"? Is that something that can be built?

**Comment by mdurchholz** [comment]
Your response does not help with the issue. You only further verified that there is a bug with both `grey` and `gray` since they are both considered colors. 

The `$palettes` variable is automatically generated from a JSON file:
```
{

    "palettes" : {
        "color-1": "#FF0000",
        "white" : "#ffffff",
        "grey" : {
             "litest" : "#e3e3e3",
              "liter" : "#cccccc",
               "lite" : "#aaaaaa",
               "base" : "#999999",
               "dark" : "#666666",
             "darker" : "#333333",
            "darkest" : "#191919"
        },
        "black" : "#000000"
    }
}
```
This JSON object will become:
```
$palettes : (color-1: #FF0000, white: #ffffff, grey: (lite: #aaaaaa, base: #999999, dark: #666666), black: #000000);
```
There is no option to add quotations with the plugin I am using. Maybe I should bring this up with their plugin support team as well.

HOWEVER

Let's use the grey example again:
```
$palettes : ( grey: (lite: #aaaaaa, base: #999999, dark: #666666) );

map-get($palettes, grey) => (lite: #aaaaaa, base: #999999, dark: #666666)

map-get($palettes, "grey") => null
```

I tested it, and the same output happens for `gray`:
```
$palettes : ( gray: (lite: #aaaaaa, base: #999999, dark: #666666) );

map-get($palettes, gray) => (lite: #aaaaaa, base: #999999, dark: #666666)

map-get($palettes, "gray") => null
```

But when I changed the variable name to something like `gruy` which is NOT a color.... it began to work as expected:
```
$palettes : ( gruy: (lite: #aaaaaa, base: #999999, dark: #666666) );

map-get($palettes, gruy) => (lite: #aaaaaa, base: #999999, dark: #666666)

map-get($palettes, "gruy") => (lite: #aaaaaa, base: #999999, dark: #666666)
```

Notice that both the string and the "non-string" versions work here because the term is not a color reference. There is definitely a bug here whenever the term is a color.

**Comment by mirisuzanne** [comment]
In your case, since the generated map does not use quoted keys, the most reliable solution is to also avoid quotes when calling `map-get`. If you consistently use `map-get($palettes, gray)` & `map-get($palettes, color-1)` (both without quotes), your code will work for both color & string values.

This is the expected behavior. CSS color keywords are considered `color` values, unless quoted. Non-keywords are _always strings_, with or without quotes. "Gruy" does not have a non-string version - it is always a string. This is not a bug, but special behavior for CSS color keywords. 

```
grey => color
"grey" => string
gray => color
"gray" => string
gruy => string
"gruy" => string

red => color
"red" => string
rod => string
"rod" => string
```

Sass does not currently provide a way to coerce a string value back into a color value. It would be possible to write a function that does the conversion, if you wanted. Here's how I would do it:

```scss
$css-color-keywords: (
  'gray': gray,
  'red': red,
  // etc, for all CSS colors
);

// converts a keyword string to a color value, using the map above
// or returns null if the string is not a color keyword
@function string-to-color($string) {
  @return map-get($css-color-keywords, $string);
}

// accept quoted or unquoted values
// if the value is a string, but could be a color, convert it
// otherwise return the value as given
@function get-json-key($value) {
  @return string-to-color($value) or $value;
}

// accept quoted or unquoted values
// and always return the right thing from our JSON $palette
@function from-palette($value) {
  @return map-get($palette, get-json-key($value));
}
```
