### ISSUE TITLE
Importing a file containing @page into a class

### ISSUE THREAD

**Issue by ahmetelgun** [sass/sass#3011]
Hi.

I have variables-light.scss, variables-dark.scss, custom.scss and bootstrap.scss files. bootstrap.scss file contains @page. I wrote code like this:
```
html.light{
    @import "variables-light";
    @import "bootstrap";
    @import "custom";
}
html.dark {
    @import "variables-dark";
    @import "bootstrap";
    @import "custom";
}
```
When I compile this code, my output file contains code like this:
```
@page {
    html.dark {
        size: a3;
    }
}
```

How do I fix this?

Thanks.

**Comment by Awjin** [comment]
Sass is correctly compiling your code into valid CSS. CSS doesn't support nesting rules, so Sass is rewriting the `@page` rule to encapsulate your `html.dark` styles.

In other words, this Sass:
```scss
html.dark {
  @page {
    size: a3;
  }
}
```
has the same behavior as this CSS:
```css
@page {
  html.dark {
    size: a3;
  }
}
```
even though the syntax differs.
