### ISSUE TITLE
Null selectors

### ISSUE THREAD

**Issue by Ksengine** [sass/sass#3019]
I am writing a utility framework. I want to do something like this.

```css
.border-blue {
  border-color: blue;
}
.border-red {
  border-color: red;
}
@media (min-width: 700px)
  .sm-border-blue {
    border-color: blue;
  }
  .sm- border-red {
    border-color: red;
  }
}
```

my sass is
```scss
@mixin style() {
  .border-
    &blue {
      border-color: blue;
  }
  &red {
    border-color: red;
  }
}

.{
    @include style;
}

@media (min-width: 700px) {
  .sm-{
    @include style;
  }
}
```

But error empty top level selector raised 
```scss
.{
    @include style;
}
```
This code also failed
```scss
.#{null} {
    @include style;
}
```
And this... Failed
```scss
.#{""} {
    @include style;
}
```

**S I need Top level null selectors.**
This is just an example. My Library is huge. It has four responsive media queries and dark mode.
