### ISSUE TITLE
Selector &.&* doesn't work

### ISSUE THREAD

**Issue by nikas-belogolov** [sass/sass#3028]
I using BEM methodology in my css, but when I try to do this:

```scss
.flip-card {
  &.&--left { ... }
}

// .flip-card.flip-card--left
```

It doesn't work. It only works when the last selector is a class (without &):
```scss
.flip-card {
  &.flip-card--left { ... }
}

// .flip-card.flip-card--left
```

How my code looks like without this feature:
```scss
&--left#{&} &__back,
&--left#{&}:hover &__inner,
&--left#{&}:focus &__inner {
    transform: rotateY(-180deg);
}

// vs

&.&--left &__back,
&.&--left:hover &__inner,
&.&--left:focus &__inner {
    transform: rotateY(-180deg);
}
```
