### ISSUE TITLE
Generate :is() selectors for nesting to match CSS

### ISSUE THREAD

**Issue by mirisuzanne** [sass/sass#3030]
The [CSS Nesting specification](https://drafts.csswg.org/css-nesting/) is moving quickly towards a First Public Working Draft, and potential implementation. We have some time before it will stabilize and land in browsers, but there is a lot of syntax overlap with some key differences in output. I wanted to document some of the ways it will conflict with (and give different results compared to) Sass nesting.

The spec is based very much on our feature, using the same `&` syntax, but adjusted to ensure that browsers only need single-character look-ahead. That means:

1. Every nested selector requires the `&` parent reference
2. Our syntax is supported directly _when the nested selector starts with_ `&`

## Sass-only

There are a few use cases we support, but CSS does not:

```scss
.block {
  p { … } /* CSS requires the implied & prefix for a descendant combinator */
  main & { … } /* CSS requires & to be the first character for this syntax */
  &_element { … } /* CSS does not support string-concatenation */
}
```

## CSS-only

CSS provides a second syntax that has no current meaning with Sass. The `@nest` rule allows more complex combinations, while still avoiding infinite-lookahead.

```css
/* required in cases such as… */
.block {
  @nest main & { … }
  @nest :not(&) { … }
}

/* optional in some cases… */
.block {
  @nest & p { … }
  @nest &.active { … }
}
```

## CSS/Sass overlap

Then there are some rules supported by both Sass & CSS syntax, such as:

```scss
.foo, .bar {
  color: blue;
  & + .baz, &.qux { color: red; }
}

.foo {
  color: blue;
  & .bar & .baz & .qux { color: red; }
}
```

While the syntax is the same, these cases are interpreted in slightly different ways. Sass generates all the possible combinations:

```css
.foo, .bar { color: blue; }
.foo + .baz, 
.foo.qux, 
.bar + .baz, 
.bar.qux { color: red; }

.foo { color: blue; }
.foo .bar .foo .baz .foo .qux { color: red; }
```

While CSS relies on the `:is()` selector for a simpler reading:

```css
   .foo, .bar { color: blue; }
   :is(.foo, .bar) + .baz,
   :is(.foo, .bar).qux { color: red; }

   .foo { color: blue; }
   .foo .bar .foo .baz .foo .qux { color: blue; }
```

In those examples the output has a different structure, but generally the same meaning – both in terms of _matching_ and _specificity_. But there are some cases where the specificity is significantly different. The `:is()` pseudoclass takes on the _highest specificity of any selector inside it_, even if that selector is not matched. Compiled selector lists, on the other hand, take the specificity of the _highest matching selector_. For example:

```scss
.error, #e404 {
  & > .baz { color: red; }
}
```

In CSS, this is equivalent to:

```css
:is(.error, #e404) > .baz /* specificity: [1, 1, 0] */
{ color: red; }
 ```

While Sass generates:

```css
.error > .baz, /* specificity: [0, 2, 0] */
#e404 > .baz /* specificity: [1, 1, 0] */
{ color: red; }
```

## Thoughts...

We don't generally add internal functionality around new CSS features before they have been implemented by several browsers – but the overlapped-syntax-with-different-meaning use-cases could cause a problem here.

- Uses of `@nest` can likely be passed through without modifications
  - It might be possible short-term to require `@nest` as a marker for accessing the native CSS feature?
  - Long-term we will need to define how this syntax integrates (or doesn't) with our selector functions
- At some point we'll need to change our output to use `:is()` or pass-through/generate the appropriate CSS nesting syntax
  - In some cases that can happen smoothly without any change for authors
  - In some cases that will be a specificity-breaking change
- For Sass-only syntax, we have to decide what CSS is generated in each case
  - Implicit ancestor `&` could be added to the output or compiled according to the spec
  - Non `&`-prefixed selectors could add `@nest` to the output, or be compiled according to spec
  - We could continue to compile concatenation basically as-is?

I've likely missed some things here, but thought it was worth starting the conversation.

**Comment by nex3** [comment]
This is certainly a complex and difficult issue. Generally speaking, I support trying to converge on the specified CSS semantics, but even *generating* `:is()` selectors is fraught—[many browsers](https://caniuse.com/css-matches-pseudo) still don't support it at all, any many more have only partial prefixed support with likely incorrect specificity rules. So we're stuck between a rock and a hard place: we can either support the newest CSS semantics and break compatibility with older browsers; or we can continue to support our existing semantics and be subtly incompatible with standard CSS.

I think we should follow a two-phase plan:

1. For the time being, we keep the Sass semantics as-is. As you point out, users can opt into the latest CSS behavior using `@nest` which we will always pass through as-is. It is unfortunate to violate our CSS-superset policy here, but preserving backwards-compatibility for such a widely-used feature is more important.

2. Once more than 98% of the global browser market supports unprefixed `:is()` (as per our [browser compatibility policy](https://github.com/sass/dart-sass#browser-compatibility)), switch `&` to generate `:is()` rather than multiple different selectors. Ideally, we can align this with a 2.0.0 release, but that may or may not be realistic based on timings.

**Comment by romainmenke** [comment]
There is one more (tricker) case when the complex selectors are nested :/

```scss
.alpha > .beta {
	& + & {
		order: 2;
	}
}
```

With sass :

```css
.alpha > .beta + .alpha > .beta {
  order: 2;
}
```

Following the current spec :

```css
:is(.alpha > .beta) + :is(.alpha > .beta) {
	order: 2;
}
```

Both results match different html.
When we changed [postcss-nesting](https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-nesting) to match this part of the spec we got a lot of feedback because the result is unexpected.

**Comment by korenevskiy** [comment]
Hey
Why would NESting use the nested type?
You can do the same syntacticly without nesting, but have a nesting.

```CSS
div.alfa{
	color: blue;
}
:& .title{
	color: red;
}
:& .info{
	color: green;
}
:&(1) .content{
	color: gray;
}
:&(1) .content:maxwidth(600px){
	color: gray;
}
```

Equivalent CSS
```CSS
div.alfa{
	color: blue;
}
div.alfa .title{
	color: red;
}
div.alfa .info{
	color: green;
}
div.alfa  .info  .content{
	color: gray;
}
@media(width < 600px){
div.alfa  .info  .content{
	color: gray;
}
}
```
As you can see, syntactic compatibility is observed.
But at the same time it has all the advantages of a new way.

It is also convenient to make an attachment of any depth without changing the parser.

**Comment by nex3** [comment]
I don't think adopting an entirely new syntax for nesting is a good way forward. It would be a massively breaking change and I think many users would find it much less visually appealing.

**Comment by korenevskiy** [comment]
@nex3  You are right. This is a new syntax. He needs to develop new habits. But these are just habits. And we can reason not in the plane of habits, but try to evaluate the new syntax in the plane of flexibility, opportunity.
 Do not get me right. Modern CSS turns into a lot of level. We have the investment of media expressions, and now we will have the nesting of styles. This is an erroneous path in the wrong direction. It seems that we need it, but let's think about how to solve the possibilities of attachments but without making complex cascades.
.
I have the next idea, We can come up with the use of variables inside class names. Which will allow for the inheritance of styles. But do not make a multidimensional cascades loaded for understanding.

Before taking a new NESTING nesting syntax. Let's fantasize about using variables in style names. Perhaps we will get something new and solve the problems of nesting. But we get something more than just a nesting.
```CSS
div.card.first  = $firstCard{
	display: flex;
}

$firstCard .title{
	text-align: center;
}
$firstCard img{
	width: 50%;
}

header $firstCard{
	margin-top: 10px;
}
footer $firstCard{
	margin-bottom: 10px;
}
```
