### ISSUE TITLE
Loud comments stripped in value

### ISSUE THREAD

**Issue by strarsis** [sass/sass#3031]
Loud comments in CSS values - although valid - are completely stripped by SASS.
```scss
.test {
  background: /*! loud comment */ linear-gradient(blue, red);
}
````
The loud comment also doesn't end up as CSS value, it is just stripped.
These kinds of comments are very useful and the only way to pass annotation to CSS post-processors like PostCSS that run in a second step (e.g. to transparently apply polyfills).
