### ISSUE TITLE
null does not follow its list semantic when used as a rest argument

### ISSUE THREAD

**Issue by stof** [sass/sass#3057]
```scss
@function testArgs($args...) {
    @return length($args);
}

$a: null;
a {
    b: testArgs($a...);
}
```

Both dart-sass and libsass show `1` here.

However, this is not consistent with the behavior of `null` treated as a list, which should be an empty list, and so pass 0 arguments to `testArgs`.
[The documentation](https://sass-lang.com/documentation/at-rules/function#passing-arbitrary-arguments) only covers the behavior for maps and lists, not for other types of values. But I would have expected it to be consistent with their list behavior (and that's actually how I implemented it in scssphp, which returns `0` for that testcase in the 1.5.1 version, because I missed this inconsistency when working on the implementation)
