### ISSUE TITLE
` SassError: Undefined function.` for `math.divide`

### ISSUE THREAD

**Issue by yaquawa** [sass/sass#3061]
I'm getting error when using the `math.divide`

using:

```json
"sass": "^1.33.0",
"sass-loader": "^10.0.0-rc.0",
```

```scss
@use "sass:math";

.leading--loose {
    line-height: math.divide(23, 13);
    margin-top: -0.5em;
    margin-bottom: -0.5em;
}
```
