### ISSUE TITLE
@supports with AND/OR

### ISSUE THREAD

**Issue by prathamesh-gharat** [sass/sass#3088]
The following CSS seems valid as per https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Conditional_Rules/Using_Feature_Queries
```css
@supports (
  not (backdrop-filter: blur(50px)) and (-webkit-backdrop-filter: blur(50px))
) {
  background: rgba(255, 255, 255, 0.95);
}
```

But getting validation errors
```
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):                                                                                                 friendly-errors 11:52:27  
SassError: expected ")".
not (backdrop-filter: blur(50px)) and (-webkit-backdrop-filter: blur(50px))
```
