### ISSUE TITLE
Forbid compound selector extensions in selector functions

### ISSUE THREAD

**Issue by nex3** [sass/sass#3089]
Several years ago, coinciding with the release of Dart Sass, we dropped support for compound selector extendees for the `@extend` rule, for reasons [explained here](https://sass-lang.com/documentation/breaking-changes/extend-compound). However, we didn't deprecate the corresponding behavior in the `selector.extend()` or `selector.replace()` rules. I no longer recall why that was—[this commit](https://github.com/sass/dart-sass/commit/0ae7372d75b226527a38e7cd8cc4516e90ba7b4f) clearly indicates that it was intentional, but it doesn't describe the reasoning for the decision.

In any case, the current state of the world is confusingly inconsistent—`selector.extend()` is documented as having the same behavior as the `@extend` rule, and the logic behind selector extension *should* treat compound selectors the same as list selectors, but `selector.extend()` does not. As such, we should deprecate the use of compound selectors here and eventually remove it entirely.

**Comment by Jogai** [comment]
If I may revive this topic; The advice in the error when using a compound selector seems wrong to me. Consider this example (simple for example's sake, but I have a real world issue that has the same problem and relies on a css framework).

```html
<div class="simple">
  <div class="color">
  </div>
</div>
<div class="simple color"></div>
<div class="width"></div>
```

```scss
.simple {
  min-height: 4rem;
  background-color: grey;
  margin: 1rem;
  padding: 1rem;
  .color {
    min-height: 2rem;
    background-color: red;
  }
}

.color {
  background-color: #efefef;
}

.width {
  @extend .simple.color; 
  max-width: 80%;
}
```
Error:
```
Error: compound selectors may no longer be extended.
Consider `@extend .simple, .color` instead.
```

But I want to have my third div in red and a bit less height. How can this still be done?
