### ISSUE TITLE
Feature Request: Automated conversion between Sass variables and CSS custom properties

### ISSUE THREAD

**Issue by MichaelKilbane** [sass/sass#3093]
# Proposal

I find the syntax for using a CSS custom property to be tedious, and much prefer the Sass syntax. So, I propose that there be a new way to assign CSS custom properties using Sass/SCSS syntax.

This would enable designated variables to be changed at runtime (among other advantages), while maintaining the benefits of Sass variables.

I'm not sure what the precedent for something like this would suggest, but this option could perhaps be enabled in a CLI flag, an environment variable, or as a variation of the current variable declaration syntax.

# Examples

### Basic Example

```scss
$foo: 10px; // or any alternate syntax

.bar {
    width: $foo;
    height: $foo;
}
```
```css
:root {
    --foo: 10px;
}

.bar {
    width: var(--foo);
    height: var(--foo);
}
```

### Example with media query

```scss
$foo: 10px; // or any alternate syntax

@media screen and (min-width: 768px) {
    $foo: 20px;
}

.bar {
    width: $foo;
    height: $foo;
}
```

```css
:root {
    --foo: 10px;
}

@media screen and (min-width: 768px) {
    :root {
        --foo: 20px;
    }
}

.bar {
    width: var(--foo);
    height: var(--foo);
}
```

# Namespacing

I understand that there could be the possibility of collisions since Sass variables are contained to the working file whereas CSS custom properties defined in the root selector are not. So, it might be necessary to map the given Sass variable names to a more obscure property name.

For example, mapping `$foo` to `--[directory/file]-foo-[hash]`.

Thanks.

**Comment by mirisuzanne** [comment]
Sass variables & CSS custom properties are fundamentally different – I don't think it will ever be safe for us to _implicitly_ generate one from the other. 

And if the goal is only to save a few keystrokes, I'm not sure Sass is the right place for that to happen – at the expense of very useful CSS custom property features like the fallback value of the `var()` function. I'd recommend using text snippets in your code editor.

The best I could imagine here is something more explicit (like a mixin) for generating CSS props from Sass variables, without needing to duplicate the name, or call a variable with a Sass-defined fallback:

```scss
@use 'sass:vars'; /* I made this is up for the sake of pseudo-code */
$brand: blue;

html {
  /* --brand: #{$brand}; */
  @include vars.create($brand);
}

.logo {
  /* color: var(--brand, $brand); */
  color: vars.use($brand);
}
```

compiling too:

```css
html {
  --brand: blue;
}

.logo {
  color: var(--brand, blue);
}
```

I might find something like that useful as a shortcut - especially if the "create" mixin could accept any number of variables.

**Comment by tannerdolby** [comment]
@mirisuzanne I really like what your brainstorming with `sass:vars` and generating CSS custom properties with the fallback values. 

Here is what I arrived with:

- `create` mixin for converting sass variable to css custom property
- `use` function for returning the css custom property as `var(--prop, val)`

```scss
@use "sass:meta";
@use "sass:map";
@use "sass:list";
@use "variables";

@mixin create($vars...) {
    $args: meta.module-variables("variables"); // map
    $keys: map.keys($args); // list
    $values: map.values($args); // list
    $argsLength: list.length($vars);

    @if $argsLength == 1 and nth($vars, 1) != null {
        // get the index of sass var value from values in module
        // variables map, to get property name from $keys
        $index: index($values, nth($vars, 1));
        $prop: nth($keys, $index);
        $value: nth($vars, 1); // or nth($values, $index)
        @if $prop == null or $value == null {
            @error("Invalid property or value. Cannot be null.");
        }
        --#{$prop}: #{$value};
    } @else {
        @each $prop, $value in $args {
            @if $prop == null or $value == null {
                @error("Invalid property or value. Cannot be null.");
            }
            --#{$prop}: #{$value};
        }
    }
}

// Use the CSS custom variable
@function use($var, $fallback...) {
    $args: meta.module-variables("variables");
    $keys: map.keys($args);
    $values: map.values($args);
    $index: index($values, $var);
    $prop: nth($keys, $index);
    $fallbackLength: list.length($fallback);

    @if $args == null {
        @error("No Sass variables in the given module.");
    }

    @if $fallbackLength == 1 {
        @return var(--#{$prop}, #{nth($fallback, 1)});
    } @else if $fallbackLength == 0 {
        @return var(--#{$prop}, $var);
        @error("Only one value permitted for custom property fallback.");
    } @else {
        @error("Only one value permitted for custom property fallback.");
    }
}
```

**Comment by tannerdolby** [comment]
The above implementation is a very rough base foundation, it works for a few cases but I'm going to fine tune this weekend and see if I can spin up something sturdy enough to use for `sass:vars` or something similar.

**Comment by tannerdolby** [comment]
We would then utilize the mixin and function like this:

```scss
// var/_variables.scss

$width: 50px;
$height: 25px;
$color: #f06; 
```

then load the stylesheet:

```scss
// var/_index.scss

@forward "vars";
```
now we include the mixins/variables with `@use "var"` and utilize the create mixin and use function to convert Sass variables to custom properties:

```scss
// demo.scss

@use "var";

$width: var.$color;
$height: var.$length;
$color: var.$color; 

// Converting a single Sass variable at a time
.demo-one {
    @include var.create($width);
    @include var.create($height);
    @include var.create($color);

    width: var.use($width);
    height: var.use($height);
    color: var.use($color);
}

// Converting many Sass variables at a time
.demo-many {
    @include var.create($width, $height, $color);

    width: var.use($width);
    height: var.use($height);
    color: var.use($color);
}
```
compiles to:

```scss
.demo {
    --width: 50px;
    --height: 25px;
    --color: #f06;
    width: var(--width, 50px);
    height: var(--height, 25px);
    color: var(--color, #f06);
}

.demo-many {
    --width: 50px;
    --height: 25px;
    --color: #f06;
    width: var(--width, 50px);
    height: var(--height, 25px);
    color: var(--color, #f06);
}
```

The above lays some groundwork for potentially having a really useful `sass:vars` module with built-in function `use` and mixin `create`. I created a repo [sass-variable-converter](https://github.com/tannerdolby/sass-variable-converter) if you want to have a closer look at the code and it can also be a place to iterate on this feature, if it were to make it into Sass.

**Comment by cpoftea** [comment]
If there would be this feature, I think it would cause another pain to control which variables should not be compiled to custom properties.
Maybe it would be good to have some different type of Sass variable for custom properties only that can hold only simple types (no map), which would work with module system and can be prefixed with `$--`, for example, which compile variable as custom property to the `root:` or to style declaration blocks where it is used. 

As for now, let me show an example, where we have control over what we really want to be compiled as custom properties (only what our code really needs).

Let's create an image component with some public variables:
```scss
// components/_image.scss

$v--size: --image-size !default; // 1

$size: 128px !default; // 2

.image {
  display: block;
  width: var(#{$v--size}, #{$size});
  height: var(#{$v--size}, #{$size});
}
```
1. That Sass variable holds the local custom property name like some kind of public component API (thx to Sass module system). Also, we can mark it with `!default` to make it to be configurable (in case of custom properties names conflict). It is prefixed with `v--` to distinguish from an ordinary configurable variable with default value (2).

Then we have some comment component which uses our image as nested block (not element), but thx to Sass module system and custom properties we can do like this:
```scss
// components/_comment.scss

@use "image";

.comment {
  #{image.$v--size}: 32px;

  @media (...) {
    #{image.$v--size}: 64px;
  }
}
```
Then maybe we have some card component which uses image too, but as element:
```scss
// components/_card.scss

@use "image";

$--image-size: --card-image-size; // 2

.card {
  #{$--image-size}: 64px;

  @media (...) {
    #{$--image-size}: 256px;
  }
}

.card__image {
  #{image.$v--size}: var(#{$--image-size}); // 1
}
```
1. Writing everywhere `image.$v--size` could seem boring for someone, so we can reassign image custom property name with local one. It's not necessary, but, as for example, we can do that, and it's a good thing, I think.
2. In order we want local custom property name to be private for Sass module system, we can just remove `v`.

Done. Then we create entry point. We don't care about ordering (Sass module system will handle it instead).
```scss
// style.scss

@use "components/card";
@use "components/comment";
@use "components/image" with (
  $size: 512px, // 2
  $v--size: --custom-image-size, // 1
);
```
1. We have name conflict? It's not a problem for us
2. Just in case, why not

Magic-time
```css
/* style.css */

.image {
  display: block;
  width: var(--custom-image-size, 512px);
  height: var(--custom-image-size, 512px);
}

.card {
  --card-image-size: 64px;

  @media (...) {
    --card-image-size: 256px;
  }
}

.card__image {
  --custom-image-size: var(--card-image-size);
}

.comment {
  --custom-image-size: 32px;

  @media (...) {
    --custom-image-size: 64px;
  }
}
```
No need to `root:` custom properties. But I know it's depends on different cases. But for most of the time you don't need to be all variables compiled to custom properties.
