### ISSUE TITLE
::slotted(<compound-selector>) grammar not supported when nesting rules

### ISSUE THREAD

**Issue by justinwilaby** [sass/sass#3097]
sass appears to ignore nuances with `::slotted()` and treats it like any other selector which produces non-working [postfixed css combinators](https://github.com/WICG/webcomponents/issues/889) in the output.

e.g. The input:
```css
::slotted(input) {
  color: blue;
  &:invalid {
    color: red;
    }
}
```

produces the incorrect output:
```css
::slotted(input) {
  color:blue
}
::slotted(input):invalid {
  color:red
}
```
The expected correct output is:
```css
::slotted(input) {
  color:blue
}
::slotted(input:invalid){
  color:red
}
```

This leads me to conclude that `::slotted()` as [defined in the spec](https://drafts.csswg.org/css-scoping/#slotted-pseudo) is not currently supported by sass but sass parses and produces invalid css when encountering `::slotted()`
