### ISSUE TITLE
Support the `::slotted(<compound-selector)` grammar

### ISSUE THREAD

**Issue by justinwilaby** [sass/sass#3099]
Currently, SASS will parse `::slotted(<compound-selector)` but produces invalid output when nesting anything, forcing the developer to bail out of using nesting which is a primary benefit of using SASS. This enhancement request is to support the nuances of `::slotted()`.

 **note:** To keep the example below as simple as possible, `&` is used but other nesting strategies fail to produce valid css as well.

e.g. The input:
```css
::slotted(input) {
  color: blue;
  &:invalid {
    color: red;
  }
  &.hidden {
    display: none;
  }
}
```
produces the incorrect output:
```css
::slotted(input) {
  color:blue
}
::slotted(input):invalid {
  color:red
}
::slotted(input).hidden {
  display: none;
}
```
The expected correct output is:
```css
::slotted(input) {
  color:blue
}
::slotted(input:invalid){
  color:red
}
::slotted(input.hidden) {
  display: none;
}
```

Thank you.
