### ISSUE TITLE
Error while using variable with percentage inside conic-gradient

### ISSUE THREAD

**Issue by jcubic** [sass/sass#3113]
This code looks valid, but gives an error:

```css
@for $percent from 0 through 99 {
    progress[value="#{$percent}"]::-webkit-progress-bar {
            background: conic-gradient(
                var(--progress-color) 0% #{$percent}%,
                var(--rest-color) #{$percent}% 100%
            );
    }
}
```

I think that is an error in the syntax this seems valid. It works at https://beautifytools.com/scss-compiler.php but fails on CodePen and https://www.sassmeister.com/.

The fix is to wrap % with `#{"%"}`, note that the first percent only need for sassmeister tool but for CodePen (I'm not sure what compiler it uses) both % need to be escaped like this.
