### ISSUE TITLE
Feature request - Responsive variables like CSS variables

### ISSUE THREAD

**Issue by babakfp** [sass/sass#3114]
#### CSS variables
```sass
:root
  --space-x: 32px
  @media (min-width: 768px)
    --space-x: 40px
```

#### SASS variables
```
$space-x: 32px
@media (min-width: 768px)
  $space-x: 40px

.my-class
  margin-left: $space-x
```
Output
```CSS
.my-class {
  margin-left: 32px;
}
@media (min-width: 768px) {
  .my-class {
    margin-left: 40px;
  }
}
```
