### ISSUE TITLE
Odd behaviour when extending compound selectors.

### ISSUE THREAD

**Issue by dawaltconley** [sass/sass#3121]
Apologies if this has been raised before, but I'm not sure exactly what to call this. Possibly related to #2570.

### What makes sense

The following scss extends as I would expect:
```scss
a:hover, a:visited {
    color: blue;
}

.subtle-link {
    @extend a;
    color: gray;
}
```

`.subtle-link` gets the same styles applied as `a` as well as those of its `:hover` and `:visited` pseudo classes:

```css
a:hover, .subtle-link:hover, a:visited, .subtle-link:visited {
  color: blue;
}

.subtle-link {
  color: gray;
}
```

### What doesn't make sense

However, if you add the base selector to the original comma-ed selector rule...

```scss
a, a:hover, a:visited {
    color: blue;
}

.subtle-link {
    @extend a;
    color: gray;
}
```

`.subtle-link` will _not_ extend the `:hover` and `:visited` styles of `a`.

```css
a, .subtle-link, a:hover, a:visited {
  color: blue;
}

.subtle-link {
  color: gray;
}
```
It _will_ extend `:hover` and `:visited` though if you declare `a` before them:

```scss
a {
    color: blue;
}

a:hover, a:visited {
    color: blue;
}

.subtle-link {
    @extend a;
    color: gray;
}
```
I assume this is a case of sass trying to be clever: "I see a lone anchor selector, and I know you'll never find `.subtle-link:hover` and `.subtle-link:visited` in places where you wouldn't _also_ find `.subtle-link`, so that's all I need to generate." But this doesn't account for the specificity of `a:hover` and `a:visited`, which overrides `.subtle-link`.

I think it would be better for sass to err on the side of generating extra css in at least _some_ cases like this, since compound selectors cannot be extended directly. Possibly by accounting for specificity, possibly just when using pseudo classes, since pseudo classes _can_ be extended on their own but that is almost never something you'd want to do.

I understand this may not be a convincing use case, and can describe my specific situation if it helps but wanted to try to point out the strangeness of this behavior in a very basic way.
