### ISSUE TITLE
Feature request: Support nesting of :host selectors

### ISSUE THREAD

**Issue by gfellerph** [sass/sass#3129]
With more and more browsers supporting web components and the shadow dom, styling the :host pseudo element becomes more and more important. The current syntax allows to style the :host element based on classes and other selectors within brackets:

```css
:host {
  color: black;
}

:host(.color-green) {
  color: green;
}
```

As far as I can see, there is no possibility to nest those rules undter one :host selector like:

```scss
:host {
  color: black;

  &(.color-green) {
    color: green;
  }
}
```

Spec: https://drafts.csswg.org/css-scoping/#host-selector
MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/:host()
Related issues: https://stackoverflow.com/questions/25825541/scss-and-hostactive
