### ISSUE TITLE
selector doesn't unify compound-selector-list correctly

### ISSUE THREAD

**Issue by yinonov** [sass/sass#3134]
It's not possible to selector.**unify** with _pseudo-class function_ selectors (`:is()` `:not()` `:host()` etc'...)

the following
```css
@use 'sass:selector';

$selector: ':host';

$selector: selector.unify($selector, '[type="bluish"]');

#{$selector} {
    color: lightblue;
}
```

will produce
```css
[type=bluish]:host {
  color: lightblue;
}
```

### expected behavior
sass selector module should recognize selector format and produce
```css
:host([type=bluish]) {
  color: lightblue;
}
```

if it was a string module I wouldn't expect it to have any recognition of its context and plainly concatenate the 2, but it being a selector module should probably have more awareness of selector type.

am I missing something? couldn't find similar issues on the topic and that usually should raise a flag for doing something wrong...
