### ISSUE TITLE
Fix simplification of calc() expressions

### ISSUE THREAD

**Issue by echocrow** [sass/sass#3147]
Dart Sass 1.40.0 introduced a new feature that simplifies `calc()` expressions. Unfortunately, at least part of that simplification logic seems to yield incorrect results.

Example input:
```scss
.example {
  opacity: calc(1 - (1 - var(--my-var, 0)));
}
```

Expected output:
```scss
.example {
  opacity: calc(1 - 1 + var(--my-var));
}
// or ideally:
.example {
  opacity: var(--my-var);
}
```

Actual output (as of v1.40.0 – v1.40.1):
```scss
.example {
  opacity: calc(1 - 1 - var(--my-var));
}
```

Seems like there is missing logic around resolving brackets `()` in the subtrahend (right-hand side of a substraction); here, `+` and `-` may need to be flipped.
For example, `a - (b - c)` can be simplified to `a - b + c`, but **must not** be simplified to `a - b - c`.
