### ISSUE TITLE
New SASS datatype? Dictionary or Hash

### ISSUE THREAD

**Issue by jonjaques** [sass/sass#315]
From what I can tell, I have sort of a unique need - was wondering if I could get some feedback.

I want to be able to define a dictionary of property and value pairs.

The use for this would be to create style presets that could be mapped to different html structures.

This is the _really_ inefficient way I'm doing it right now.

``` scss
$default-color: black;
$default-border: 1px solid black;
$default-background: white;

$widget-color: $default-color;
$widget-border: $default-border;
$widget-background: $default-background;

.box1 {
  color: $default-color;
  border: $default-border;
  background: $default-background;
}

.box2 {
  color: $widget-color;
  border: $widget-border;
  background: $widget-background;
}
```

``` css
.box1 {
  color: black;
  border: 1px solid black;
  background: white;
}
.box2 {
  color: black;
  border: 1px solid black;
  background: white;
}
```

You can see that by default I have one set of values that will apply to all the places where i've assigned variables.
If I want to make `box2` different, I can do so. But the problem is this is terribly inefficient. For each new style i want to create, I have to duplicate the variables. In addition, what if a style has more variables than that. In practice, I'm using something like 10 vars per style.

Now, I know the argument is, why don't you create a style1/style2 class, and then use @extend to apply them like that?

Well, @extend doesn't let you interpolate variables. Also, because of the issues/behavior with nested selectors - this tends to generate a huge list of selectors, among other problems.

Anyways, here is my idea of how this would work.

``` scss
$style1: [
  color => red,
  border => 1px solid blue,
  background => green
]

$style2: [
  color => white,
  border => 1px solid black,
  background => black
]

$box1: $style1
$box2: $style1
$box3: $style2

.box1 {
  color: $box1['color'];
  border: $box1['border'];
  background: $box1['background'];
}
.box2 {
  color: $box2['color'];
  border: $box2['border'];
  background: $box2['background'];
}
.box3 {
  color: $box3['color'];
  border: $box3['border'];
  background: $box3['background'];
}
```

Which would output:

``` css
.box1 {
  color: red;
  border: 1px solid blue;
  background: green;
}
.box2 {
  color: red;
  border: 1px solid blue;
  background: green;
}
.box3 {
  color: white;
  border: 1px solid black;
  background: black;
}

```

**Comment by jonjaques** [comment]
So in thinking about what objections this would create, I found a flaw in my thinking. The example could be accomplished with a mixin. However, my needs involve needing to be able to specify extra properties. 

That brings up two problems.

1) For added properties, how does sass know what to map them to?
2) What to do about Compass mixins. The example below highlights a flaw. Even if we figured out how to assign the extra properties, what to do about adding mixins into these? In fact they seem like incompatible ideas.

``` scss
$style3: [
  color => red,
  border => green,
  background => blue,
  border-radius => 5px
]

$box4: $style3;

.box4 {
  color: $box4['color'];
  border: $box4['border'];
  background: $box4['background'];
  $box4[extras]
}
```

Anyways, I guess i'm just sort of crowd sourcing ideas - maybe somebody has a more elegant solution?
