### ISSUE TITLE
Can't use CSS variables or SCSS variables based on CSS variables in module configurations

### ISSUE THREAD

**Issue by petervatler** [sass/sass#3152]
If one would like to use dynamic variables the best practice is to have them as CSS variables and then use them as values for SCSS variables, the following example works fine. If the --primary variables is manipulated by JavaScript the header's background color changes.
```scss
:root {
--primary: red;
}

$primary: var(--primary);

header {
background-color: $primary;
}
```
Although if one thinks in modular it's better to multiple files and module configurations but it just doesn't work the way it should. If this is get compiled, fails immediately even if using SCSS variables is skipped and only CSS variables are used:

Colors partial
```scss
$primary: var(--primary);
```

Header partial
```scss
$header-bg: grey !default;
header {
background-color: $header-bg;
}
```
Body style
```scss
@use 'colors' as colors;
@use 'header' as header with {
$header-bg: colors.$primary;
}
```
Main style
```scss
:root {
--primary: red;
}
```
