### ISSUE TITLE
Parentheses left out in compiled CSS since 1.40.0 (causing order of operations problems)

### ISSUE THREAD

**Issue by Eliasvdb** [sass/sass#3153]
I bumped into an issue that seems to be present since 1.40.0 and is still present in the latest 1.41.0.

Given the folowing `scss`:
```scss
my-element {
  &::before{
    padding-bottom: calc(100% / (var(--aspect-ratio, 16/9)));
  }
```

This is compiled starting from 1.40.0 as:
```css
my-element::before {
  padding-bottom:calc(100%/var(--aspect-ratio, 16/9));
}
```

Notice the missing `()` parentheses around the `var(...)` statement. When `--aspect-ratio` is not defined and the fallback value is used this causes the outcome to be `100%/16/9`. Due to the missing parentheses and the order of operations, the calculation is wrong.

Before 1.40.0 this was compiled correctly to:
```css
my-element::before {
  padding-bottom:calc(100%/(var(--aspect-ratio, 16/9)));
}
```

Notice the parentheses around `var(...)` are present here. When `--aspect-ratio` would not be defined the outcome would (correctly) be `100%/(16/9)`.
