### ISSUE TITLE
Nested calc() inside min() gets wrongly discarded

### ISSUE THREAD

**Issue by lehni** [sass/sass#3163]
The title says it all. With this input:

```scss
.test {
  width: min(
    6em,
    calc((100vw - var(--padding)) / 2)
  );
}
```

I get the following output with `v1.42.1`:

```css
.test {
  width: min(6em, (100vw - var(--padding)) / 2);
}
```

The expected output:

```css
.test {
  width: min(6em, calc(100vw - var(--padding)) / 2);
}
```

As you can see, the `calc()` gets currently removed, the rest remains. `calc()` should be preserved too.
