### ISSUE TITLE
Extraneous selectors created by @extend

### ISSUE THREAD

**Issue by nex3** [sass/sass#317]
The following snippet produces numerous unnecessary selectors:

``` scss
.a {
  h1 {a: b}
  h2 {@extend h1}
}
.b {@extend .a}
```

This produces the following output:

``` css
.a h1, .b h1, .a h2, .b .a h2, .a .b h2, .a .b h2, .b .a h2, .b h2 {
  a: b; }
```

The expected output is:

``` css
.a h1, .b h1, .a h2, .b h2 {
  a: b; }
```

Note that the following SCSS, which should be semantically identical, does produce the expected output:

``` scss
.a {
  h1, h2 {a: b}
}
.b {@extend .a}
```
