### ISSUE TITLE
When using a wrapper, sass inadvertantly wraps css @ constructs

### ISSUE THREAD

**Issue by hawkeye64** [sass/sass#3170]
I don't know if I am doing this wrong and there is an alternative way, but I will explain.

I am using Carbon Charts and need to wrap their SCSS to avoid CSS pollution.

Here is an example of the sass file:

```css
.q-carbon-charts
  @import '@carbon/charts/styles/styles-white.scss'
```

I get output like this:

```css
.q-carbon-charts .bx--cc--alluvial polygon.arrow-down {
  fill: black;
}
```

This is fine, but it created an issue as well, for instance:

```css
@font-face {
  .q-carbon-charts {
    font-display: auto;
    font-family: "IBM Plex Sans";
    font-style: italic;
    font-weight: 300;
    src: local("IBM Plex Sans Light Italic"), local("IBMPlexSans-LightItalic"), url(https://fonts.gstatic.com/s/ibmplexsans/v6/zYX7KVElMYYaJe8bpLHnCwDKhdTmvIRcdvfo.woff) format("woff");
  }
}
```

This is illegal CSS.

Am I doing something wrong? Is there an alternative to this? Or, is this a potential bug? I would also imagine @media queries are also not allowed.

I guess what I am wondering is if you can wrap as I have done above, then should sass create "bad" CSS?
