### ISSUE TITLE
First-class plain CSS functions

### ISSUE THREAD

**Issue by asyncliz** [sass/sass#3176]
Similar to the new [calculation](https://sass-lang.com/documentation/values/calculations) type, it would be fantastic to add first-class support for the [`var()` function](https://developer.mozilla.org/en-US/docs/Web/CSS/var()) as a new `variable` type.

### Meta type recognition

```scss
$custom-prop: var(--foo);
@debug meta.type-of($custom-prop); // "variable"
```

### Inspection of name and values

```scss
$custom-prop: var(--foo, 8px);
@debug meta.var-name($custom-prop); // "--foo"
@debug meta.var-value($custom-prop); // 8px
```

### Interpolation

```scss
$length: 8px;
$custom-prop: var(--bar, red);

.foo {
  color: var(--foo, $custom-prop);
  padding: var(--baz, $length);
}
```
```css
.foo {
  color: var(--foo, var(--bar, red));
  padding: var(--baz, 8px);
}
```

## Motivation

This would be of particular use to the Material Web team, which uses a custom [Map data structure](https://github.com/material-components/material-components-web/blob/master/packages/mdc-theme/_custom-properties.scss) to manage CSS variables. This is necessary since a `var()` is a string and the type of the value is lost when attempting to parse/inspect it.
