### ISSUE TITLE
Interpolation of custom properties and its values

### ISSUE THREAD

**Issue by cpoftea** [sass/sass#3185]
For a while, I'm using sass variables to hold module's custom properties as public variables to configure component's behavior in different contexts. Assigning value to this kind of interpolated custom property doesn't require interpolate value itself. On the other hand, assigning value to a non interpolated custom property requires interpolate value, which is [mentioned in the docs](https://sass-lang.com/documentation/style-rules/declarations#custom-properties). Is the reason just a `$` symbol, which is valid for declaration value of custom property?

From the compiler point of view, custom property it still a "property", isn't it? For example, for some reason, user needs a `$` as value of his properties: for the simple property - he will use `string.unquote("$")`, but for the custom property - he can leave `$` just as is. Maybe it was good, if parser would treat these "assignments" equally, which could be more obvious and usage could be less verbose?

Even more, there are few odd cases:
#### input.scss
```scss
$custom-prop: --a;
$test: value;

:root {
  #{$custom-prop}: $test;
  --b: $test; // nope
  --c: #{$test}; // :(
  #{"--d"}: $test;
  -#{"-e"}: $test;
  --#{"f"}: $test; // nope
  --#{"g"}: #{$test}; // :(
}
```
#### output.css
```css
:root {
  --a: value;
  --b: $test;
  --c: value;
  --d: value;
  --e: value;
  --f: $test;
  --g: value;
}
```

Also, prior to version **`v1.40`** we have to interpolate variables at `calc` expressions:
#### input.scss
```scss
$test: 1px;

:root {
  --a: calc($test + 1px - 1em);
  --b: calc(#{$test} + 1px - 1em); // :(
  c: calc($test + 1px - 1em);
  d: calc(#{$test} + 1px - 1em); // :(
}
```
#### output.css
```css
:root {
  --a: calc($test + 1px - 1em);
  --b: calc(1px + 1px - 1em);
  c: calc($test + 1px - 1em);
  d: calc(1px + 1px - 1em);
}
```

Meanwhile, after **`1.40`** we can throw interpolation away, but not in custom properties)
```scss
$test: 1px;

:root {
  --a: calc($test + 1px - 1em); // won't work
  --b: calc(#{$test} + 1px - 1em); // works, but calc is not evaluated
  --c: #{calc($test + 1px - 1em)}; // :( , but works
  d: calc($test + 1px - 1em);
}
```
#### output.css
```css
:root {
  --a: calc($test + 1px - 1em);
  --b: calc(1px + 1px - 1em);
  --c: calc(2px - 1em);
  d: calc(2px - 1em);
}
```
