### ISSUE TITLE
string concatenation to form hex color

### ISSUE THREAD

**Issue by fecou** [sass/sass#3189]
I have webpack with sass loader.
I'm trying to convert a string to define hex color.
This code should work
`
$primaryBg0: "#"; 
$primaryBg1: "5a8"; 
$primaryBg2: "264"; 
$primaryBg: unquote(#{$primaryBg0}#{$primaryBg1}#{$primaryBg2});
@debug "primaryBg: #{$primaryBg}";
$test:darken(#{$primaryBg}, 10%);
`
The @debug returns DEBUG: primaryBg: #5a8264
But I get an error :  SassError: SassError: argument `$color` of `darken($color, $amount)` must be a color.
What am I doing wrong ?

**Comment by KasparRosin** [comment]
Unrelated to darken method, but having the same issue with rbga() function.
```css
background-color: rgba($primary-color, 0.02);
SassError: argument `$color` of `rgba($color, $alpha)` must be a color
```

**Comment by cpoftea** [comment]
I'm not sure Sass support type conversions.
For now, unquoted string is still a string.
You can debug your variable with module `sass:meta` function `meta.type-of($variable)`.

By the way, [first link](https://kittygiraudel.com/2014/01/27/sassycast-type-conversion-in-sass/) at the google dated 2014. Color section redirects to [git repository](https://github.com/KittyGiraudel/SassyJSON/tree/master/stylesheets/decode/helpers/color). I tested it - works.
Here's updated code with everything you need:
```scss
@use "sass:string";
@use "sass:list";

/// Convert an hexadecimal number to a decimal number
/// @access private
/// @param {String} $string - hexadecimal value
/// @return {Number} - decimal number
@function _hex-to-dec($string) {
  $hex: "0" "1" "2" "3" "4" "5" "6" "7" "8" "9" "a" "b" "c" "d" "e" "f";
  $string: string.to-lower-case($string);
  $length: string.length($string);

  $dec: 0;
  @for $i from 1 through $length {
    $factor: 1 + (15 * ($length - $i));
    $index: list.index($hex, string.slice($string, $i, $i));
    $dec: $dec + $factor * ($index - 1);
  }

  @return $dec;
}

/// Cast a JSON encoded string into a hexadecimal color
/// @access private
/// @param {String} $string - JSON string
/// @return {Color | String} - string or hex color depending on the match
/// @require {function} _hex-to-dec
@function from-hex($string) {
  $string-lower: string.to-lower-case($string);
  $r: "";  $g: ""; $b: "";
  $hex: "0" "1" "2" "3" "4" "5" "6" "7" "8" "9" "a" "b" "c" "d" "e" "f";
  $length: string.length($string);
  $max: if($length == 4, 1, 2);

  // Check for length accuracy
  @if $length != 4 and $length != 7 {
    @return $string;
  }

  // Loop from the second character (omitting #)
  @for $i from 2 through $length {
    $c: string.slice($string-lower, $i, $i);

    // If wrong character, return
    @if list.index($hex, $c) == null {
      @return $string;
    }

    @if string.length($r) < $max {
      $r: $r + $c;
    } @else if string.length($g) < $max {
      $g: $g + $c;
    } @else if string.length($b) < $max {
      $b: $b + $c;
    }
  }

  @if $length == 4 {
    $r: $r + $r;
    $g: $g + $g;
    $b: $b + $b;
  }

  @return rgb(_hex-to-dec($r), _hex-to-dec($g), _hex-to-dec($b));
}
```
