### ISSUE TITLE
Thousandth Precision of Percentage Function Inadequate

### ISSUE THREAD

**Issue by Ottergoose** [sass/sass#319]
The percentage function currently generates output with precision down to the thousandth of a percent, which, in some cases, will cause some browsers to render elements a pixel narrower than desired. I understand and agree that mathematically it should be adequate, however some browsers need more precision in order to work properly. 

Consider an element with a width of 980px and 14px margins, within a container that has a width of 1008px:

``` css
.container{
   width 1008px;
}

.content{
   margin: 14px;
   width: 980px;
}
```

``` html
<div class="container">
   <div class="content">
      <p>I should be 980px wide!</p>
   </div>
</div>
```

If we make this simple layout responsive, we'd use the following SCSS:

``` css
.container{
   width: 100%;
   max-width: 1008px;
   margin: 0 auto;
}

.content{
   margin: percentage(14px / 1008px);
   width: percentage(980px / 1008px);
}
```

Which produces CSS output something like this:

``` css
.container{
   width: 100%;
   max-width: 1008px;
   margin: 0 auto;
}

.content{
   margin: 1.389%;
   width: 97.222%;
}
```

97.222% of 1008 is 979.99776, which means the browser should render it with a width of 980px (IE and Firefox do), but, if you inspect the content element in the latest Chrome (17.0.963.79) in Windows 7 or OS X, the computed width is 979px. That's not really an issue for elements with text, but, if the element contains a 980px wide graphic getting squished to a width of 979px, it looks unacceptably soft.

In any event, Chrome will not correctly render the content element in this example until there's precision up to a hundred thousandth:

``` css
.container{
   width: 100%;
   max-width: 1008px;
   margin: 0 auto;
}

.content{
   margin: 1.38889%;
   width: 97.22222%;
}
```

So, while I agree that this rendering issue is a bug with Chrome, it'd be nice if the default precision of the percentage function went out to at least five places beyond the decimal point, or, perhaps more appropriately, if there was an option where the precision could be set when compiling the CSS.

In Ethan Marcotte's Responsive Web Design book, he routinely went 5-7 places beyond the decimal point, although from looking at his CSS source (http://unstoppablerobotninja.com/-/css/screen/core.css) he's going out 5 places now; so, if I'm crazy for wanting this, at least I'm in good company.
