### ISSUE TITLE
How do I use the time variable in mixin

### ISSUE THREAD

**Issue by zhoufanglu** [sass/sass#3196]
// normal
```css
animation: move 3s 1s linear infinite;
```
// use mixin

```css
  @mixin move-round($color, $path, $duration, $delay) {
    position: absolute;
    left: 0;
    border-radius: 50%;
    background-color: $color;
    width: 10px;
    height: 10px;
    //move
    offset-path: path($path);
    animation: move $durations $delays linear infinite;
  }
  div{
    @include move-round("blue", "M21,17s88.229,128.335,309,142", 3s, 1s);
  }
  
    @keyframes move {
    100% {
      offset-distance: 100%;
    }
  }
```
* error
` animation: move $durations $delays linear infinite;`
