### ISSUE TITLE
new directive proposal - @use

### ISSUE THREAD

**Issue by gillyb** [sass/sass#320]
Using this directive, it will allow me to extend classes from another file, but without importing the whole file contents into my file.

Example :

``` scss
// common.scss
.bold { font-weight:bold; }
.cool-style { font-size:10px; }
```

``` scss
// other.scss
@use "common"
.other-cool-style { @extend .bold; }
```

This will generate 2 files.
1. The common.css file - as sass would generate it now
2. The other.css file which will only have the 'other-cool-style' class with the 'bold' definition in it, but without importing the other styles in the common file.
