### ISSUE TITLE
Addition of native functions to match JavaScript counterparts

### ISSUE THREAD

**Issue by brandonmcconnell** [sass/sass#3205]
I have implemented several JavaScript core functions/methods in Sass/SCSS which has been very useful when working with different types and has actually made working with Sass even simpler for me as it feels just like JavaScript, another web language most Sass developers are familiar with.

I think it would be worthwhile to add these to Sass/SCSS core for the same reason. Including the few I've already made, my proposal would be to extend all the Sass built-in types with methods to make them as powerful—and as familiar—as their JavaScript counterparts.

These (JavaScript methods) include:
* `String.repeat()` as `str-repeat()`
* `String.padStart()` as `pad-start()`
* `String.padEnd()` as `pad-end()`
* `Array.flat()` as `list-flat()`
* `Array.map()` as `list-map()`
* `Array.flatMap()` as `list-flat-map()`
* `Array.filter()` as `list-filter()`
* `Array.reduce()` as `list-filter()`
* `Array.sort()` as `list-sort()`
* `Array.some()` as `list-some()`
* `Array.every()` as `list-every()`
* `!Array.some()` as `list-none()`
* `!Array.every()` as `list-not-every()`
* `Array.copyWithin()` as `list-copy-within()`
* `Array.find()` as `list-find()`
* `Array.reverse().find()` as `list-find-last()`
* `Array.findIndex()` as `list-find-index()`
* `Array.reverse().findIndex()` as `list-find-last-index()`
* `Array.indexOf()` as `list-index-of()`
* `Array.lastIndexOf()` as `list-last-index-of()`
* `Array.includes()` as `list-includes()`
* `!Array.includes()` as `list-not-includes()`
* `Array.pop()` as `list-unappend()`
* `Array.unshift()` as `list-prepend()`
* `Array.shift()` as `list-unprepend()`

I would be happy to help build and implement each of these to extend Sass's built-in types if there is an opportunity for me to do so. Otherwise, please accept this as a feature request.

# Specification Examples

**str-repeat**
```scss
@function str-repeat($repeat-string, $repeat-length) {
    $string: "";
    @for $i from 0 to $repeat-length {
        $string: $string + $repeat-string;
    }
    @return $string;
}
```

**pad-start**
```scss
@function pad-start($original-string, $target-length, $pad-string: " ") {
    $original-string: stringify($original-string);
    $pad-string: stringify($pad-string);
    @return str-slice(str-repeat($pad-string, $target-length) + $original-string, -1 * max($target-length, str-length($original-string)));
}
```

**pad-end**
```scss
@function pad-end($original-string, $target-length, $pad-string: " ") {
    $original-string: stringify($original-string);
    $pad-string: stringify($pad-string);
    @return str-slice($original-string + str-repeat($pad-string, $target-length), 0, max($target-length, str-length($original-string)));
}
```

# Example Use Cases

## Leading zeroes
This logic precedes each article's content with a 4-digit counter, with leading [stringified] zeroes for lower numbers, so in a list of 1,000 items, each of these strings below would be rendered based on nth-child (omitting all the in-between values):

```html
#0001. Article title
<!-- items 0002–0009 omitted for conciseness -->
#0010. Article title
<!-- items 0011–0099 omitted for conciseness -->
#0100. Article title
<!-- items 0101–0999 omitted for conciseness -->
#1000. Article title
```

```scss
main > article {
    @for $i from 1 through 1000 {
        &:nth-child(#{$i})::before {
            content: "##{pad-start($i, 4, 0)}. ";
        }
    }
}
```

## "Table of Contents" formatting
Sometimes when working with monospace fonts, it's helpful to use a character such as a space, period, or dash to separate left-side and right-side strings. This is common practice in tables of contents and in restaurant menus. Here is an example:

```html
Entree

Chicken Dinner .......... $24.99
Garlic Butter Salmon .... $19.39
Ratatouille (vegan) ..... $17.59


Appetizer

Pea Soup ................. $4.79
Potatoes au Gratin ....... $7.89
```

The below example will render this exact output (above) in the content property, making use of all `stringify`, `pad-start`, `pad-end`, and `str-repeat`:

```scss
$menu: (
    "Entree": (
        "Chicken Dinner": 24.99,
        "Garlic Butter Salmon": 19.39,
        "Ratatouille (vegan)": 17.59
    ),
    "Appetizer": (
        "Pea Soup": 4.79,
        "Potatoes au Gratin": 7.89
    )
);
$longest-item-length: 0;
$longest-price-length: 0;
@each $category, $items in $menu {
    @each $item, $price in $items {
        $longest-item-length: max($longest-item-length, str-length($item) + 1);
        $longest-price-length: max($longest-price-length, str-length(stringify($price)) + 2);
    }
}
$character-padding-char: ".";
$character-padding: 2;
$br: "\A";
$menu-text: "";
$category-counter: 1;
@each $category, $items in $menu {
    $menu-text: $menu-text + $category + str-repeat($br, 2);
    $item-counter: 1;
    @each $item, $price in $items {
        $menu-text: $menu-text + pad-end($item + " ", $longest-item-length + $character-padding, $character-padding-char) + pad-start(" $" + $price, $longest-price-length + $character-padding, $character-padding-char);
        @if $item-counter != length($items) {
            $menu-text: $menu-text + $br;
            $item-counter: $item-counter + 1;
        }
    }
    @if $category-counter != length($menu) {
        $menu-text: $menu-text + str-repeat($br, 3);
        $category-counter: $category-counter + 1;
    }
}
body {
    font-family: consolas, monospace;
    white-space: pre;
    &::before {
        content: $menu-text;
    }
}
```
