### ISSUE TITLE
How to override placeholders?

### ISSUE THREAD

**Issue by jd-solanki** [sass/sass#3206]
I want to allow overriding placeholders.

Sample code:
```scss
%colorify {
    color: red;
}

%colorify {
    background: red;
}

.red {
    @extend %colorify;
}
```

I expect it to generate:
```css
.red {
  background: red;
}
```

but it generates:
```css
.red {
  color: red;
}

.red {
  background: red;
}
```

**Comment by stof** [comment]
placeholders work like CSS selectors in that aspect: reusing the same one with new rules does not disable the previous rules.

**Comment by jd-solanki** [comment]
Can we somehow override or replace content then?

**Comment by Awjin** [comment]
@stof is correct about the behavior of placeholders.

One way to achieve the behavior you want is with mixins:

```scss
@mixin colorify {
    color: red;
}

@mixin colorify {
    background: red;
}

.red {
    @include colorify;
}
```
