### ISSUE TITLE
Multiplying by a negative number with compressed causes different results

### ISSUE THREAD

**Issue by maoxiaoke** [sass/sass#3207]
Here is my code: 

```scss
$videox-range-thumb-height: 12px;
$videox-range-track-height: 6px;

.test {
  right: calc(#{$videox-range-thumb-height} / 2 * -1);
  top: calc((#{$videox-range-thumb-height} - #{$videox-range-track-height}) / 2 * (-1));
}
```

Then I compile it with `style: compressed`: 

```bash
→ sass test.scss index.css --style compressed 
```

I got the unexpectable result:

```css
.test{right:calc(12px / 2 * -1);top:calc((12px - 6px)/2*-1)}/*# sourceMappingURL=index.css.map */
```

While no space before negative number may cause a compile error according to https://github.com/facebook/create-react-app/issues/10880#issuecomment-905426538
