### ISSUE TITLE
Percentage, division, and deprecation warnings

### ISSUE THREAD

**Issue by ygoe** [sass/sass#3209]
I've got an issue with the big deprecation warning about the division slash. After reading all of the documentation, I understand the problem. I'm not sure if I find that good but for now I just try to get rid of the warning message without patching the source code.

Here's my code:

```scss
@function strip-unit($number)
{
	@if type-of($number) == 'number' and not unitless($number)
	{
		@return $number / ($number * 0 + 1);
	}
	@return $number;
}

@function mix($color1, $color2, $amount)
{
	$amount: strip-unit($amount) * 0.01;   // initially was: strip-unit($amount) / 100, warning resolved
	@return rgb(
		red($color1) * (1 - $amount) + red($color2) * $amount,
		green($color1) * (1 - $amount) + green($color2) * $amount,
		blue($color1) * (1 - $amount) + blue($color2) * $amount);
}

div
{
	background: mix(#ff0000, #ffff00, 75%);
}
```

Source: https://css-tricks.com/snippets/sass/strip-unit-function/

The problem is the division used to get rid of the percentage unit. While there is a `percentage` function (that can be easily avoided by multiplying with `100%`), the language sadly lacks a non-replacable "unpercentage" function.

I tried to replace it with this:

```scss
		@return calc($number / ($number * 0 + 1));
```

> Error: 0% and 1 are incompatible.

```scss
		@return math.div($number, ($number * 0 + 1));
```

> Error: There is no module with the namespace "math".

(My compiler is sass 1.44.0 compiled with dart2js 2.14.4.)

Are there any other less known workarounds to avoid using deprecated code? Or are divisions not used anymore today? In the second case (see comment) I could work around that by expressing the division as multiplication but that can't be done everywhere, and it's not as readable.
