### ISSUE TITLE
No provision to check sass function exists in outer module

### ISSUE THREAD

**Issue by sandeeppatidar30** [sass/sass#3210]
We have a requirement where we are checking if function exists or not in outer module.

This was working fine with `@import` because it allows to define a function before `@import`.

Working scenario --

```scss
 // styles.scss

@function get-overridden-config($theme, $factor) {
    $accent:  map-get($theme, accent);
    $foreground: map-get($theme, foreground);
    @return (
         button-primary-color: red
    );
}

@import './my-custom.theme';
```

```scss
// my-custom.theme.scss

$theme: mat-light-theme();
$factor: 1;
$overridden-config-store: ();


@if function-exists(get-overridden-config) {
     @debug 'function exists';
     $overridden-config-store: get-overridden-config($theme, $factor);
}

.button-primary {
   background-color: map-get($overridden-config-store, button-primary-color);
}
```

After upgrading it to sass module system my scenario is completely breaking -

Breaking scenario -

```scss
 // styles.scss

@function get-overridden-config($theme, $factor) {
    $accent:  map-get($theme, accent);
    $foreground: map-get($theme, foreground);
    @return (
         button-primary-color: red
    );
}

@use'./my-custom.theme'; // @use should be the first statement but i want to define `get-overridden-config` above the @use.
```

```scss
// my-custom.theme.scss
@use 'sass:map';
@use 'sass:meta';

$theme: mat-light-theme();
$factor: 1;
$overridden-config-store: ();


@if meta.function-exists(get-overridden-config) {
     @debug 'function exists';
     $overridden-config-store: get-overridden-config($theme, $factor);
}

.button-primary {
   background-color: map-get($overridden-config-store, button-primary-color);
}
```
Please check this scenario and let me know if i can achieve same thing in new sass module system,
