### ISSUE TITLE
Bubble @keyframes directives

### ISSUE THREAD

**Issue by dominic** [sass/sass#323]
Let @keyframe directives (and the browser specific alternatives) bubble to the top of the tree like @media or @import.

For example, the following mixin defines a custom animation for stepping through a series of frames:

``` scss
@mixin keyframes($name) {
  @-webkit-keyframes #{$name} {
    @content;
  }
  @-moz-keyframes #{$name} {
    @content;
  }
  @-ms-keyframes #{$name} {
    @content;
  }
  @keyframes #{$name} {
    @content;
  }
}

@mixin animate ($filename, $frames: 1, $loop: true, $onHover: false) {
  @include replace-text-with-dimensions($filename);
  width: (image-width($filename) / $frames);
  background-position: 0px 0px;

  @include keyframes($filename) {
    from {
      background-position: 0px;
    }
    to {
      background-position: image-width(filename);
    }
  }

  &:hover {
    -webkit-animation: $filename 0.5s steps($frames) 1;
  }
}
```

This fails to work since the mixin outputs the @keyframes block within whatever selector it was called on, instead of at the root of the document.
