### ISSUE TITLE
Stack Overflow Bug

### ISSUE THREAD

**Issue by jake-thomas-1** [sass/sass#3249]
## File
`crasher.scss`:
```scss
$carbon--theme--white: (
  interactive-01: #0062ff
);

@mixin carbon--theme--white {
  @include carbon--theme--white;
}

nav ul {
  @include carbon--theme--white;
}
```
## Command & Error
`sass -w crasher.scss:boom.css`
Unexpected exception:
Stack Overflow

../.nvm/versions/node/v15.14.0/lib/node_modules/sass/sass.dart.js 39544:39  Environment.scope$1$3$semiGlobal$when
../.nvm/versions/node/v15.14.0/lib/node_modules/sass/sass.dart.js 39562:19  Environment.scope$1$1
../.nvm/versions/node/v15.14.0/lib/node_modules/sass/sass.dart.js 62838:30  _EvaluateVisitor__runUserDefinedCallable__closure.call$0
../.nvm/versions/node/v15.14.0/lib/node_modules/sass/sass.dart.js 61389:25  _EvaluateVisitor._withEnvironment$1$2
../.nvm/versions/node/v15.14.0/lib/node_modules/sass/sass.dart.js 61394:19  _EvaluateVisitor._withEnvironment$2
../.nvm/versions/node/v15.14.0/lib/node_modules/sass/sass.dart.js 62827:17  _EvaluateVisitor__runUserDefinedCallable_closure.call$0
../.nvm/versions/node/v15.14.0/lib/node_modules/sass/sass.dart.js 61492:25  _EvaluateVisitor._withStackFrame$1$3
../.nvm/versions/node/v15.14.0/lib/node_modules/sass/sass.dart.js 61498:19  _EvaluateVisitor._withStackFrame$3
../.nvm/versions/node/v15.14.0/lib/node_modules/sass/sass.dart.js 61041:19  _EvaluateVisitor._runUserDefinedCallable$1$4
../.nvm/versions/node/v15.14.0/lib/node_modules/sass/sass.dart.js 60621:15  _EvaluateVisitor.visitIncludeRule$1
