### ISSUE TITLE
[FEATURE] Introduce a compiler flag that disables implicit conversion of colors

### ISSUE THREAD

**Issue by Delta-official** [sass/sass#3261]
I think that there should be a compilation flag which disables the implicit conversion of color formats from one to another (e.g rgb(0,0,0) -> #000) because there can be some situation where the conversion of colors in variables and functions just impedes what you're trying to do. I think this is a good example:
```scss
@use "sass:color";

$color: rgb(207, 100, 154);

:root {
    --color-but-css: #{color.scale($color, $lightness: 5%)};
}

body {
    background-color: rgba(var(--color-but-css), 0.5);
    // Expected output: rgba(209, 108, 159, 0.5)
    // Actual output: rgba(#d16c9f, 0.5)
}
```
