### ISSUE TITLE
Add a convenient way to reference class name from other files.

### ISSUE THREAD

**Issue by deadalnix** [sass/sass#3265]
I'm currently mollifying an existing codebase and there is a recurring pattern that turn out to be a problem: there is a need to start referencing a class name from another module. As in:

modulea.scss:
```scss
.class-a {
    // CSS properties.
}
```

moduleb.scss:
```scss
@use "modeulea";
:import("modulea.scss") {
    class-a-from-modulea: class-a;
}

.class-b {
    .class-a-from-modulea {
        // CSS properties.
    }
}
```

Now, I understand this goes against the philosophy of modern module and this probably shouldn't be encouraged, on the other hand, there is a ton of code out there that wasn't written by philosopher, but that would benefit from modularization anyways.

What about adding a shorthand for the following stunt? The current way is ugly, fragile, and sometime lead to breaking abstractions, such as when `_index.scss` is involved. This could simply reuse the existing `:import` syntax, for instance:

moduleb.scss:
```scss
@use "modeulea" {
    class-a-from-modulea: class-a;
}

.class-b {
    .class-a-from-modulea {
        // CSS properties.
    }
}
```

And voila! Considering the number of issue mentioning similar problems either on stackoverflow, css-modules and numerous other places, I do think this is a legitimate pain point that shouldn't be ignored.
