### ISSUE TITLE
🛑 [BUG] `:is(&)` ⇒ compiling BUT `:where(&)` don't

### ISSUE THREAD

**Issue by nitin2953** [sass/sass#3270]
SCSS
```scss
main {
   background-color: yellow;

  :is(& > *) {
     background-color: blue;
  }

  :where(& > *) {
     background-color: red;
  }
}
```

Compiled CSS
```css
main {
   background-color: yellow;
}

:is(main > *) {
   background-color: blue;
}

main :where(& > *) {
   background-color: red;
}
```

Using `"sass": "^1.49.8"`
