### ISSUE TITLE
Passing aspect-ratio values flagged as using / for division

### ISSUE THREAD

**Issue by benjibee** [sass/sass#3274]
Consider the following valid sass using the relatively recent `aspect-ratio` property:

```scss
@mixin shaped-image($aspect-ratio: 4/5, $border-radius: 1rem) {
    aspect-ratio: $aspect-ratio;
    border-radius: $border-radius;
    object-fit: cover;
}
```
This is erroneously reported as attempted division using `/` and dumps the following in the console:

`DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.`

Additionally, passing the value as a string avoids this warning but creates invalid CSS.
