### ISSUE TITLE
Configuring a module (@use/@forward) using variables from that module?

### ISSUE THREAD

**Issue by slaarti** [sass/sass#3310]
Okay, so, as a notional example, suppose I have one project for a library:

```scss
// _functions.scss
// Borrowed this code from the Sass docs just to have an example.
@function pow($base, $exponent) {
  $result: 1;
  @for $_ from 1 through $exponent {
    $result: $result * $base;
  }
  @return $result;
}

// _variables.scss
@use "functions";

$thing1: "abc" !default;
$thing2: "def" !default;
$thingy: $thing1 !default;
$foo: 3 !default;
$bar: 2 !default;
$baz: functions.pow($foo, $bar) !default;

// library.scss
@forward "functions";
@forward "variables";
// Additional @forward rules for more fixins, functions,
// styles, etc., most of which will @use "variables" and
// "functions" to use their contents for various purposes.
```

And then a second project (and possibly eventually a third, fourth, etc., which is why the solution here isn't just "merge the two things together") that uses it:

```scss
// project2.scss
@use "library";
// Other stuff here.
```

This is all well and good, and it's cool that I'd be able to configure the library by doing:

```scss
// project2.scss
@use "library" with (
  $foo: 5,
);
```

However, all of the documented examples of module configuration presume you want to set a variable to a literal value. (I think you might _possibly_ be able to use a variable you get from some other `@use` rule before this one, but that's a guess and not something I've seen explicitly stated.) What if instead, I want to configure `library` so that `$thingy` is set to get its value from `$thing2` instead of `$thing1`? I know that the simplistic answer would be:

```scss
// project2.scss
@use "library" with (
  $thingy: "def",
);
```

But if, for some reason, I need to update the `library` project to change `$thing2` to `"ghi"`, then suddenly my `project2` configuration is out of sync with what `library` is doing, unless I manually also change `project2` to match, at which point what's the point in having libraries? Since the namespace doesn't properly exist until the `@use` rule is fully executed, I can't do:

```scss
@use "sass:map";
@use "sass.meta";
@use "library" with (
  $thingy: $thing2,
  // I've also tried:
  $thingy: library.$thing2,
  // and even:
  $thingy: map.get(meta.module-variables("library"), "thing2"),
);
```

I've also tried:

```scss
@use "library" as libvars;
@use "library" with (
  $thingy: libvars.$thing2,
  // and also the map/meta thing above
);
```

And that falls afoul of how the module system wants to only ever load something once, failing with:

```
Error: This module was already loaded, so it can't be configured using "with".
  ┌──> scss/library.scss
1 │   @forward "functions";
  │   ^^^^^^^^^^^^^^^^^^^^ new load
  ╵
  ┌──> scss/_variables.scss
1 │   @use "functions";
  │   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━ original load
  ╵
  ┌──> scss/project2.scss
2 │ ┌ @use "library" with (
3 │ │   $thingy: libvars.$thing2,
4 │ │ );
  │ └─^ configuration
  ╵
  scss/_variables.scss 1:1  @forward
  scss/library.scss 1:1     @use
  scss/project2.scss 2:1    root stylesheet
```

Is there _any_ way to make something like this work? _Should_ there _be_ a way to make this work? Or is this a case of "no, sorry, you're SOL, just don't do that" ?
