### ISSUE TITLE
@media with nested @include load-css() creates a multitude of redundant @media queries

### ISSUE THREAD

**Issue by WebMechanic** [sass/sass#3316]
Hello,
this applies to Dart Sass 1.51.0 compiled with dart2js 2.16.2

Given something like this in a .scss the loaded files are basically concatenated:
```scss
@use "sass:meta";
// many.scss
.something-above { display: flex }

@include meta.load-css("foo");
@include meta.load-css("bar");
@include meta.load-css("bat");

.something-below { display: grid }
```
`many.css` then contains sth like that:
```css
.something-above { display: flex }

/* foo.scss */
.foo { color: red }
.stuff { opacity: 0 }
/* bar.scss */
.bar { color: green }
.things { visibility: hidden }
/* bat.scss */
.bat { color: blue; }
.clobber { display:none }

.something-below { display: grid }
```

If I want them to be **grouped** within a single `@media` query such as
```scss
@media (max-width:30em) {
  @include meta.load-css("foo");
  @include meta.load-css("bar");
  @include meta.load-css("bat");
}
```
instead of giving me the expected
```css
.something-above { display: flex }

@media (max-width:30em) {
  /* foo.scss */
  .foo { color: red }
  .stuff { opacity: 0 }
  /* bar.scss */
  .bar { color: green }
  .things { visibility: hidden }
  /* bat.scss */
  .bat { color: blue; }
  .clobber { display:none }
}

.something-below { display: grid }
```
the rendered .css contains that very `@media` query around **every single selector** that exists in and has been generated by each of the loaded source files incl. what's `@forward`ed into them, poluting the output with über-redundant code.
```css
.something-above { display: flex }

@media (max-width:30em) {
  .foo { color: red }
}
@media (max-width:30em) {
  .stuff { opacity: 0 }
}
@media (max-width:30em) {
  .bar { color: green }
}
@media (max-width:30em) {
  .things { visibility: hidden }
}
@media (max-width:30em) {
  .bat { color: blue; }
}
@media (max-width:30em) {
  .clobber { display:none }
}

.something-below { display: grid }
```
I could understand (accept) if this would result in **one** `@media` then wrapping each file's content, but not every single selector.

While this is not necessarily a bug, as the output works (poluted as it is), this behaviour / result looks utterly wrong to me nonetheless.

If the files themself also contain media queries, those are merged with the "outer" one and the selectors are kept together.
```scss
@media screen and (any-hover) {
  .dim { color: gray }
  .pop { color: hotpink }
}
// becomes
@media screen and (min-width: 30em) and (any-hover) {
  .dim { color: gray }
  .pop { color: hotpink }
}
```

I have simple workarounds, but they are annoying as they requires some structural change.

If there's some syntax sugar I have missed that'd prevent this, I'd be happy to learn about it. Otherwise I hope this can be fixed soon.

Thank you, and enjoy.

**Comment by stof** [comment]
I guess this is done this way due to the needed merging of media queries when the included css contains media queries (as `@media` could not be nested in the past, see https://caniuse.com/mdn-css_at-rules_media_nested-queries)

**Comment by WebMechanic** [comment]
I though so, but for **almost 10 years** this is supported in browsers that matter today,, 2022.
The only browser that never supported nested media was of course our old buddy Internet Explorer. I loved using this simple "hack" back in the days, but can it please R.I.P. now? Nothing remotly relevant since CSS Grid works in IE anyway.

Still: putting each and every single selector into it's own `@media` doesn't make sense, BC or not, esp. if those that actually are wrapped in a `@media` within these included files remain perfectly together. 
There's some broken stacking logic here and I believe it should be fixed.

Might be worth thinking about taking a new approach on that or provide some flag to put an end to this wasteful behaviour. Maybe check browserscope if old browsers are excluded.

**Comment by WebMechanic** [comment]
did some more quick tests
with this, **EVERY selector** in `stuff.scss` get its own `@media` wrapper, which could become _hundrets of additional, redundant lines_.
```scss
@media (min-width: 30em) {
  @include load-css("stuff");
}
```

if I wrap the whole content of `stuff.scss` into a single, simple query such as
```scss
@media any {
 .fancy {}
 .shiny {}
 // a gaziillion selectors more
}
```
the result is **ONE empty** `@media (min-width: 30em) {}` from the parent file (with possible /**/ comments inside from stuff.scss and any files it includes) followed by **ONE single** `@media any and (min-width: 30em) {}` where all selectors appear as expected.
Ain't a true bug, but broken still and inconsistent at least.

**Comment by nex3** [comment]
I can't reproduce this. If I have:

```scss
// test.scss
@use 'sass:meta';

@media (max-width: 30em) {
  @include meta.load-css('other');
  @include meta.load-css('another');
}
```

```scss
// _other.scss
a {b: c}
d {e: f}
```

```scss
// _another.scss
x {y: z}
```

I get

```scss
@media (max-width: 30em) {
  a {
    b: c;
  }

  d {
    e: f;
  }

  x {
    y: z;
  }
}
```

as expected. Can you create a repository with a minimal reproduction of this issue?
