### ISSUE TITLE
complicated strings argument bug

### ISSUE THREAD

**Issue by chiefraccoon** [sass/sass#332]
When i use the multiply values of properties, separated by comma it cause bug:

The example of real used code:

``` scss
@mixin box-shadow($params){
    -webkit-box-shadow: $params;
    -moz-box-shadow: $params;
     box-shadow: $params;
}
```

I can not use it like  
`@include box-shadow(0 1px 1px #5eb2f7, inset 0 1px 1px #5eb2f7)`
 because it looks like few separate arguments, but it stay for single.

When i try to set argument as 
`@include box-shadow("0 1px 1px #5eb2f7, inset 0 1px 1px #5eb2f7")`
 it generate not working css, because it also paste " in the css rule.

Also i tried to escape comma by backslash like
`@include box-shadow(0 1px 1px #5eb2f7\, inset 0 1px 1px #5eb2f7)`
it generate next code:
`-webkit-box-shadow: 0 1px 1px #5eb2f7 \, inset 0 1px 1px #5eb2f7;`etc.

I think you must resolve this problem, because many of properties in css3 are setted multiply, separated by comma...
