### ISSUE TITLE
Bogus "target selector not found" error with meta.load-css()

### ISSUE THREAD

**Issue by dmt0** [sass/sass#3322]
Currently this produces an error:
```scss
.animate--fade-in {
  opacity: 0;
  animation: fade-in 0.1s forwards cubic-bezier(0.19, 1, 0.22, 1);
}

@mixin animate($type: 'fade-in', $time: 1s, $delay: 0s) {
  @if $type == 'fade-in' {
    @extend .animate--fade-in;
    animation-duration: $time;
    animation-delay: $delay;
  }
```

```shell
Error: The target selector was not found.
Use "@extend .animate--fade-in !optional" to avoid this error.
    ╷
276 │     @extend .animate--fade-in;
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
```

Bumped into this after upgrading from Ruby Sass to current version `"sass": "1.52.1"`

**Comment by nex3** [comment]
It's hard to tell what's going on here without a full Sass file that reproduces the issue.

**Comment by dmt0** [comment]
It's in an open-source repo fortunately:
https://github.com/figlinq/react-chart-editor/blob/769054741922b66d3ef540a810790c2f86bafe18/src/styles/_mixins.scss#L209
I had to add `!optional` to the offending `extends`s to make Sass compile.

**Comment by nex3** [comment]
Can you provide me a *stand-alone* file that reproduces the error?

**Comment by kerryj89** [comment]
~I reported a similar issue as a reply to https://github.com/sass/dart-sass/issues/1295~

~However in my case above it's workability depends on whether or not it's within a @mixin and not conditionals.~

**Comment by kerryj89** [comment]
I am also having this problem, but I was able to distill @dmt0 setup to simplest terms and make it replicable.

It seems to be some combination of `@include meta.load-css`, `:root {}` (only through multiple `@use`/`@forward` nestings), and `@use 'mixins'` in `_index.scss` that prevents the selector from being seen even when placed in the same file as the `@extend`.  I tried making sense of it but couldn't, see the [Observations](https://github.com/kerryj89/dart-sass-issue-3322) section).

I know it doesn't make much sense to `@use 'mixins'` in `_index.scss` in my example - in @dmt0  case it makes sense as he does call a mixin within the file.  I kept it because it actually seems to be part (if not all) of the problem.

 If we are not using the system as expected I think at the very least we could get a more accurate error message than `Error: The target selector was not found.` when it is clearly listed next to the `@extend`.  Thanks!

https://github.com/kerryj89/dart-sass-issue-3322

**Comment by nex3** [comment]
I've simplified the reproduction a little more—it looks like the mixin isn't necessary. Here's the smallest reproduction I've found so far:

```scss
// index.scss
@use 'sass:meta';
@use 'target';

@include meta.load-css('extender');
```

```scss
// extender.scss
@use 'target';

.extender {
  @extend .target;
}
```

```scss
// _target.scss
@use 'midstream';

.target {x: y}
```

```scss
// _midstream.scss
@use 'upstream';
```

```scss
// _upstream.scss
@x;
```

It only reproduces if `_upstream.scss` contains _some_ concrete CSS, but what it is seem to be totally irrelevant.
