### ISSUE TITLE
Nestling with @at-root. Unexpected result when using @use in @at-root file

### ISSUE THREAD

**Issue by anton97johansson** [sass/sass#3324]
https://github.com/anton97johansson/scss-experiment 

I expect [this scss file](https://github.com/anton97johansson/scss-experiment/blob/master/css/at-root-use.scss) to generate same css as [this scss file](https://github.com/anton97johansson/scss-experiment/blob/master/css/at-root-import.scss) but it doesn't as you can see [here](https://github.com/anton97johansson/scss-experiment/blob/master/css/style.css). 

I want the `@at-root` rules to be emitted to the root when using `@use` in same file and importing file like in [my main scss file](https://github.com/anton97johansson/scss-experiment/blob/master/css/style.scss)

**Comment by jathak** [comment]
Duplicate of sass/dart-sass#1347.

**Comment by ext** [comment]
@jathak Are you sure #1347 is the right duplicate? It doesn't resemble this issue at all or at least not in a way I understand it (in which case please elaborate further).

To add more to this issue lets consider three files:

`_common.scss`:

```scss
$foo-color: red;
```

`_foo.scss`:

```scss
@import "common";

foo {	
	color: $foo-color;
}

@at-root {
	bar {	
		color: $foo-color;
	}	
}
```

and finally `main.scss`:

```scss
#app {
	@import "foo"
}
```

Executing `npm exec sass main.scss` yields the following output:

```css
#app foo {
  color: red;
}
bar {
  color: red;
}
```

Changing the import to `@use` as following:

```diff
-@import "common";
+@use "common";
 
 foo {	
-	color: $foo-color;
+	color: common.$foo-color;
 }
 
 @at-root {
 	bar {	
-		color: $foo-color;
+		color: common.$foo-color;
 	}	
 }
```

If one executes `npm exec sass main.scss` now the output for `bar` is totally different:

```css
#app foo {
  color: red;
}
#app bar {
  color: red;
}
```

I'm not sure if this is intended with `@use` or not but it caught me by surprise.
