### ISSUE TITLE
Inline comments removed on expanded style

### ISSUE THREAD

**Issue by ido-pluto** [sass/sass#3330]
How can I make inline comments stay?

```scss
div {
   border: /*! comment that suppose to stay on compressed mode */ solid 1px #000;
}
```

Output 
```css
div {
  border: solid 1px #000;
}
```

I am using the `compileStringAsync` api

```js
const scssString = `
@use './style.sass';

main {
    div {
        border: solid /* animated size */ 3px #000;
    }
}
`
const result = await sass.compileStringAsync(scssString, {
    sourceMap: true,
    syntax: 'scss',
    style: 'expanded',
    importer: createImporter(filePath),
    logger: sass.Logger.silent
});
```
### Versions

sass: 1.52.3
node: 18.3.0
