### ISSUE TITLE
Question: SassError: "&" may only used at the beginning of a compound selector.

### ISSUE THREAD

**Issue by yoyo837** [sass/sass#3332]
```scss
// How:
.nut-button {
  // SassError: "&" may only used at the beginning of a compound selector.
  &--primary&--disabled {
    opacity: 1;
    background: #ffc6b2;
  }
}

// To:
.nut-button--primary.nut-button--disabled {
  opacity: 1;
  background: #ffc6b2;
}

// Thanks! 

```

**Comment by ntkme** [comment]
``` scss
.nut-button {
  @at-root {
    #{&}--primary#{&}--disabled {
      opacity: 1;
      background: #ffc6b2;
    }
  }
}
```
