### ISSUE TITLE
sass.Exception [Error]: (en: (default: "../images/fd-logo.png")) isn't a valid CSS value.

### ISSUE THREAD

**Issue by murugeshnataraj** [sass/sass#3350]
My Code:

_functions.scss
--------------------------------------------

```scss
@function asset-url($url) {
  @return url("../#{$url}");
}
```

_FooterLinks.scss
-----------------------------------------------

```scss
$FooterLinks-brandedBackgroundImageUrl: (
en: (
    default: 'images/fd-logo.png',
  ),
  es: (
    default: 'images/fd-logo.png',
));

.footer {
 background-image: asset-url($FooterLinks-brandedBackgroundImageUrl);
@each $lang, $sizes in $FooterLinks-brandedBackgroundImageUrl {

      // Loop to output each size logo for this language
      @each $size, $url in $sizes {
        $langSelector: #{#{$FooterLinks-languagePrefix}#{$lang}};
        $sizeSelector: #{#{&}-#{$size}};

        // If site is in English or default size remove selector
        @if $lang == en { $langSelector: #{''}; }
        @if $size == default { $sizeSelector: &; }

        // Dynamically built selector with collapsed default values
        // Examples:
     
        @at-root #{$langSelector} #{$sizeSelector} {
          @include backgroundImageContain($url);
        }
      }
    }
}
```

_helper-mixin.sccs
-----------------------------------------------------------

```scss
@mixin backgroundImageContain($BackgroundImageURL) {
  background-image: asset-url($BackgroundImageURL);
  background-image: none\9;
  -ms-filter: "progid:DXImageTransform.Microsoft.AlphaImageLoader(src='/#{$BackgroundImageURL}', sizingMethod='scale')";
  :root & {
    -ms-filter: "progid:DXImageTransform.Microsoft.AlphaImageLoader(enabled=false)";
  }
}
```

Node Version: 16.13.0
"node-sass": "^6.0.1",

How to fix:
