### ISSUE TITLE
[Feature request] : color functions : support css variables

### ISSUE THREAD

**Issue by dimitri-ks2** [sass/sass#3351]
Hi,
Can you plan to support  css variables in color functions ? 

``` scss 
// CSS file : Not a sass file
:root {
  --my-color: #732d69
```
``` scss
// SCSS file
...
$a = var(--my-color, #5F2556)
...
.a {
 stroke: fade-out($a, 0.5)
}
```
> Error : var(--my-color, #5F2556) is not a color
