### ISSUE TITLE
Sass variables having arithmetic operations are converted to string

### ISSUE THREAD

**Issue by sonikasharma1403** [sass/sass#3359]
```scss
$some-variable: 100vh - 1rem - 2rem;
$other-variable: calc(#{$some-varaible})

.test {
height: $other-variable; // This get's converted to calc(100vh-1rem); since there are no spaces available the calculation's won't work
max-height: calc(100vh - 1rem);  // This works fine on browser and is computed correctly
}
```

Note that with node-sass this worked. After migrating to sass it has stopped working. I guess it should work as it is supported by the browser and the spaces should not have been trimmed.

Also, should this be considered as a breaking change and should be mentioned while converted the application from node-sass to sass?
