### ISSUE TITLE
Set global variable from a mixin ?

### ISSUE THREAD

**Issue by Anahkiasen** [sass/sass#336]
Since mixins namespace are currently not possible, is it currently possible in SASS to alter global variables ?
I'm still transposing Bootstrap to SASS and I've run into a problem. They have those two mixins :

=grid-generate($gridColumnWidth, $gridGutterWidth)
=grid-span($span)

grid-span is a companion mixin of grid-generate meant to be used inside grid-generate. The problem is, it is supposed to use the $gridGutterWidth and $gridColumnWidth parameters passed when calling grid-generate. Is there any way to set a global variable from inside grid-generate that I could later call from grid-span, without having to add parameters to grid-span ?

**Comment by chriseppstein** [comment]
Happy to help you find a good solution on the support mailing list or in IRC.

http://groups.google.com/group/sass-lang

or #sass on Freenode IRC.

**Comment by jslegers** [comment]
Any update on this issue?

I need a way to read + write global variables from a mixin. That way, I can dynamicly define, read and modify a private list of "config" data from within different mixins.

**Comment by Snugug** [comment]
Have either of you simply tried to do this? It's work just as you'd expect.

``` scss
// Input
$foo: 1;

@mixin bar($input) {
    $foo: $foo + $input;
    content: $foo;
}

@for $i from 0 through 5 {
    .baz-#{$i} {
        @include bar($i);
    }
}
```

``` css
/* Output */
.baz-0 {
  content: 1;
}

.baz-1 {
  content: 2;
}

.baz-2 {
  content: 4;
}

.baz-3 {
  content: 7;
}

.baz-4 {
  content: 11;
}

.baz-5 {
  content: 16;
}
```

**Comment by jslegers** [comment]
I'm currently doing this :

``` scss

// Definitions
@mixin setComponent($placeholder) {
  // Do stuff
  %#{$placeholder} {
      @content;
  }
}

@mixin getComponent($placeholder) {
  // Do stuff
  @extend %#{$placeholder};
}
```

``` scss

// Example use
@include setComponent(table-cell) {
    padding:4px;
    margin:4px;
}

td {
    @include getComponent(table-cell);
}

th {
    @include getComponent(table-cell);
}
```

``` css
// Output

td, th {
  padding: 4px;
  margin: 4px;
}
```

Basicly, I'm looking for ways to achieve the following :
- support mixins as an alternative implementation for 'setComponent' and 'getComponent' dynamicly, based on the value of a global variable $extendComponents
- test whether or not a certain component has already been defined, to avoid duplication. This should work for mixins in Sass 3.3, but I don't think an implementation exists for placeholders yet.

Both this and https://github.com/nex3/sass/issues/857 seem essential to allow these features and other features I have in mind for the meta-framework I'm building.

**Comment by jslegers** [comment]
I also need to be able to do this :

``` scss
// Definitions
$configKeys : ();
$configVals : ();

@mixin register($key, $rule, $value) {
  $component : $rule+'-'+$value;
  $configKeys : append($configKeys, $key);
  $configVals: append($configVals, $component );
  @include setComponent($component ) {
        $rule : $value;
   }
}

@mixin rule($key) {
  $index : index($configKeys, $key);
  $component : index($configVals, $index);
 @include getComponent($component);
}
```

``` scss
@include register(padding-table-cell, padding, 4px);
@include register(margin-table-cell, margin, 4px);
@include register(padding-box, padding, 4px);
@include register(margin-box, margin, 4px);

@include setComponent(table-cell) {
    @include rule(padding-table-cell);
    @include rule(margin-table-cell);
}

@include setComponent(box) {
    @include rule(padding-box);
    @include rule(margin-box);
}

td {
    @include getComponent(table-cell);
}

th {
    @include getComponent(table-cell);
}

box {
    @include getComponent(box);
}
```

``` css
// Output

td, th,.box {
  padding: 4px;
}

td, th,.box {
  margin: 4px;
}
```

**Comment by jslegers** [comment]
Thanks to various improvements in Sass 3.3, I can finally do what I wanted to. And not just that, but I'm now able to use a much cleaner, much more readable syntax. 

I can now use the following syntax :

## INPUT

``` scss
.s1 {
  @include rules((
    float : right,
    width : 30%,
    background : #fff,
  ));
}

.s2 {
  @include rules((
    float : right,
    width : 100%,
    background : #000,
  ));
}

.s3 {
  @include rules((
    float : left,
    width : 30%,
    background : #fff,
  ));
}

.s4 {
  @include rules((
    float : left,
    width : 30%
  ));
  @include rules((
    background : 'url(image/cool-background.jpg)'
  ));
}

.s5 {
  @include rules((
    float : none,
    width : 2em,
    background : 'url(image/cool-background2.jpg)',
  ));
}

.s6 {
  @include ruleset((
    float : right,
    width : 40%
  ));
  @include rules((
    background : 'url(image/cool-background.jpg)'
  ));
}

.s7 {
  @include rules((
    float : right,
    width : 40%,
    background : 'url(image/cool-background.jpg)',
  ));
}

.s8 {
  @include ruleset((
    float : right,
    width : 40%
  ));
  @include rules((
    background : 'url(image/cool-background2.jpg)'
  ));
}
```

## OUTPUT

``` scss
.s1, .s2, .s7 {
  float: right;
}
.s1, .s3, .s4 {
  width: 30%;
}
.s1, .s3 {
  background: white;
}

.s2 {
  width: 100%;
}
.s2 {
  background: black;
}

.s3, .s4 {
  float: left;
}

.s4, .s6, .s7 {
  background: "url(image/cool-background.jpg)";
}

.s5 {
  float: none;
}
.s5 {
  width: 2em;
}
.s5, .s8 {
  background: "url(image/cool-background2.jpg)";
}

.s6, .s8 {
  float: right;
  width: 40%;
}

.s7 {
  width: 40%;
}
```

The full code for this example (which includes the 'magic' under the hood) can be found at https://gist.github.com/jslegers/9805919 .
