### ISSUE TITLE
Multiple selectors, containing the same placeholder, on the same ruleset, are ignored

### ISSUE THREAD

**Issue by jstoller** [sass/sass#3369]
Sass is able to handle a selector with a placeholder, and it can handle multiple selectors on the same ruleset with different placeholders, but if a ruleset has more than one selector using the same placeholder, only the first one is rendered. So this scss:
```scss
.dark-box,
.dark-box %color--red,
.light-box .dark-box %color--green,
.light-box .dark-box %color--red,
.light-box .light-box .dark-box %color--blue,
.light-box .dark-box {
  color: orange;
}

.dark-box,
.dark-box %color--pink,
.light-box .dark-box %color--pink,
.light-box .light-box .dark-box %color--pink,
.light-box .dark-box {
  color: pink;
}

h2.red,
p.red {
  @extend %color--red;
}

h2.blue,
p.blue {
  @extend %color--blue;
}

h2.green,
p.green {
  @extend %color--green;
}

h2.pink,
p.pink {
  @extend %color--pink;
}
```
... will result in this css:
```css
.dark-box,
.dark-box h2.red,
.dark-box p.red,
.light-box .dark-box h2.green,
.light-box .dark-box p.green,
.light-box .light-box .dark-box h2.blue,
.light-box .light-box .dark-box p.blue,
.light-box .dark-box {
  color: orange;
}

.dark-box,
.dark-box h2.pink,
.dark-box p.pink,
.light-box .dark-box {
  color: pink;
}
```
... when I would expect this css:
```css
.dark-box,
.dark-box h2.red,
.dark-box p.red,
.light-box .dark-box h2.green,
.light-box .dark-box p.green,
.light-box .dark-box h2.red,
.light-box .dark-box p.red,
.light-box .light-box .dark-box h2.blue,
.light-box .light-box .dark-box p.blue,
.light-box .dark-box {
  color: orange;
}

.dark-box,
.dark-box h2.pink,
.dark-box p.pink,
.light-box .dark-box h2.pink,
.light-box .dark-box p.pink,
.light-box .light-box .dark-box h2. pink,
.light-box .light-box .dark-box p.pink,
.light-box .dark-box {
  color: pink;
}
```

**Comment by nex3** [comment]
The generated selector `.light-box .dark-box h2.red` matches a subset of elements already matched by `.dark-box h2.red`, and `.light-box h2.red` already has as high or higher specificity than `h2.red`, so Sass is trimming the unnecessary selector.

**Comment by jstoller** [comment]
Why is sass deciding that I don't need the specificity of the selectors that I'm including? Here's an even simpler example. This sass:
```scss
.dark-box %color--p,
.light-box .dark-box %color--p,
.light-box .light-box .dark-box %color--p {
  color: pink;
}
.light-box %color--p,
.dark-box .light-box %color--p,
.dark-box .dark-box .light-box %color--p {
  color: red;
}

p {
  @extend %color—p;
}
```

...outputs this CSS:
```css
.dark-box p {
  color: pink;
}

.light-box p {
  color: red;
}
```

...so if I have this markup:
```html
<div class="light-box">
  <p>This text should be red.</p>
  <div class="dark-box">
    <p>This text should be pink.</p>
  </div>
</div
```

...all the text will be red, because `.light-box p` comes after `.dark-box p` in the cascade, when I expect the second paragraph to be pink. But if sass rendered all the selectors, like this:
```css
.dark-box p,
.light-box .dark-box p,
.light-box .light-box .dark-box p {
  color: pink;
}

.light-box p,
.dark-box .light-box p,
.dark-box .dark-box .light-box p {
  color: red;
}
```
...then the text would appear as expected, because `.light-box .dark-box p` has greater specificity than `.light-box p`.

Of course my actual use case is far more complex, but the problem is the same. Perhaps sass is trying to be helpful, but it broke my CSS and the workaround is pretty messy. I still hold that this is a bug and ask that you consider reopening the issue.
