### ISSUE TITLE
Change $var sass in js :confused:

### ISSUE THREAD

**Issue by camila-frangp** [sass/sass#3379]
I need to change the value of a $variable from javascript (react ) according to a function x.
Example:

```js
// File.js

    if(themeContext === 'client-01'){
      root?.classList.add("client-01-theme");
      // and here change var sass $theme-init: client-01
    }
     if(themeContext === 'client-02'){
      root?.classList.add("client-02-theme");
       // and here change var sass $theme-init: client-02
    }
     if(themeContext === 'client-03'){
      root?.classList.add("client-03-theme");
       // and here change var sass $theme-init: client-03
    }
    ...etc
```

For control this:

```scss
// File.scss
   $theme-init: client-01;

    @if( $theme-init === 'client-01'){
       a: b;
    }
     @if( $theme-init === 'client-02'){
       a: c;
    }
    @if( $theme-init === 'client-03'){
       a: d;
    }
```

I tried using :root but to the sass variables I couldn't assign the value of the css variables  :worried:
