### ISSUE TITLE
Media queries are dropped by sass under certain circumstances, leading to a different result than expected

### ISSUE THREAD

**Issue by danieltroger** [sass/sass#3384]
The outmost media query is dropped when containing the `not` keyword, when nesting three media queries inside each other.

## Input:
```scss
body {
  @media not all and (hover: hover) and (pointer: fine) {
    @media (max-height: 1000px) {
      font-size: 12px;
      @media (max-width: 600px) {
        background: red;
      }
    }
  }
}
```

## Output:
```css
@media not all and (hover: hover) and (pointer: fine) {
  @media (max-height: 1000px) {
    body {
      font-size: 12px;
    }
  }
}
@media (max-height: 1000px) and (max-width: 600px) {
  body {
    background: red;
  }
}
```

As you can see the `background:red` no longer only happens on devices supporting hover and having a fine pointer.

## Expected output
```css
@media not all and (hover: hover) and (pointer: fine) {
  @media (max-height: 1000px) {
    body {
      font-size: 12px;
    }
  }
}
@media not all and (hover: hover) and (pointer: fine) {
  @media (max-height: 1000px) and (max-width: 600px) {
    body {
      background: red;
    }
  }
}
```
