### ISSUE TITLE
functions are not called in custom css properties

### ISSUE THREAD

**Issue by luciancaetano** [sass/sass#3385]
When i use a function in value of custom css properties the function is not compiled.

```scss
@function my-var($component, $var) {
  @return var(--my-project-var-#{$component}__#{$var});
}

.btn {
  --color: my-var(button, 'text-color');
}
```

I just tested in my project and on https://www.sassmeister.com/

I use sass https://www.npmjs.com/package/sass 1.54.0
