### ISSUE TITLE
Referencing first element in adjacent selector combinator

### ISSUE THREAD

**Issue by MohammadYounes** [sass/sass#3412]
I have a complex case in which I need to reference the first element in an adjacent selector combinator.  The simplest form of the case goes as follows: 

```scss
.tag, input.tag + label {
    color:red;
    &.is-blue {
        color: blue;
    }
}
```
Generates 

```css
.tag.is-blue, input.tag + label.is-blue {  color: blue; }
```

Is there a way to make it generate ?

```css
.tag.is-blue, input.tag.is-blue + label {  color: blue; }
```

**Comment by jathak** [comment]
The functions in the [`sass:selector` module](https://sass-lang.com/documentation/modules/selector) allow this.

To get the output you want here, you could do something like:
```scss
@use "sass:list";
@use "sass:selector";

@function append-first($selector-list, $append) {
  @for $i from 1 through list.length($selector-list) {
    $selector: list.nth($selector-list, $i);
    $first: list.nth($selector, 1);
    $with-blue: selector.append($first, $append);
    $modified: list.set-nth($selector, 1, list.nth($with-blue, 1));
    $selector-list: list.set-nth($selector-list, $i, $modified);
  }
  @return $selector-list;
}

.tag, input.tag + label {
  color: red;
  
  @at-root #{append-first(&, selector.parse(".is-blue"))} {
    color: blue;
  }
}
```
