### ISSUE TITLE
[Feature Request]: new syntax for variable interpolation

### ISSUE THREAD

**Issue by thecodechef** [sass/sass#3416]
could we see if this is possible for SASS/SCSS
``` scss
$color: red;

.is-#{$color} {
  color: $color;
}
```
 - to - <br />
``` scss
$color: red;

.is-${color} {
  color: $color;
}
```
just taking page out of LESS's playbook thats all 

``` less
@color: red;

.is-@{color} {
  color: @color;
}
```
