### ISSUE TITLE
Weird error message when a `@extend` is malformed

### ISSUE THREAD

**Issue by MoOx** [sass/sass#342]
Here is an snippet

``` scss
   $var: thing;
    stuff
    {
        @extend "#{$var};
    }

    $var-2: value;

    element:#{$var-2}
    {
        han: hum;
    }
```

When I compile this, I get `"Syntax error: Invalid CSS after "...#{var-2}": expected "}", was "{" on line 9`

The real error is because `@extend "#{$var};`is not closed with a double quote.
Error message should be clearer.
