### ISSUE TITLE
@use variable doesn't work with css variable

### ISSUE THREAD

**Issue by yukulele** [sass/sass#3425]
```scss
// _color.scss
$dark: #202020;
$light: #F7F7F7;
```
```scss
// style.scss
@use "color";
body{
  background: color.$dark;
  --dark: color.$dark;
}
```
expected result:
```scss
body{
  background: #202020;
  --dark: #202020;
}
```
actual result:
```scss
body{
  background: #202020;
  --dark: color.$dark;
}
```
