### ISSUE TITLE
Error: Only 0 arguments allowed, but 1 was passed. when using @content

### ISSUE THREAD

**Issue by zuffik** [sass/sass#3431]
According to [spec](https://sass-lang.com/documentation/at-rules/mixin#passing-arguments-to-content-blocks), I should be able to do this:

```scss
@mixin test {
  $arg: 1;
  @content ($arg);
}

.item {
  @include test {
    color: red;
  }
}
```

But when I try to compile the code using `sass` package (`yarn sass pages/App.scss app.css`), I get the following error:

```
Error: Only 0 arguments allowed, but 1 was passed.
    ╷
3   │   @content ($arg);
    │   ^^^^^^^^^^^^^^^ invocation
... │
7   │   @include test {
    │            ━━━━ declaration

```

**Comment by alexerlandsson** [comment]
I'm not sure what you try to accomplish, but to get your snippet to work you'll have to pass down `$arg` in the `@include` as stated in the specs.

```scss
@mixin test {
  $arg: 1;
  @content($arg);
}

.item {
  @include test using ($arg) {
    color: red;
  }
}
```

I hope this helps!
