### ISSUE TITLE
SCSS member loading does not work with @use directive

### ISSUE THREAD

**Issue by kalinkochnev** [sass/sass#3468]
In the documentation for @use, it states that 

> You can access variables, functions, and mixins from another module by writing `<namespace>.<variable>`, `<namespace>.<function>()`, or `@include <namespace>.<mixin>()`. By default, the namespace is just the last component of the module’s URL.

https://sass-lang.com/documentation/at-rules/use#loading-members

However, I could not get `@include <namespace>.<mixin>(arguments)` or `@include <namespace>.<mixin>` to work when I used the `@use` to import my mixin. I originally had this issue in Hugo, but I reproduced it in React with node-sass

post.scss
```scss
$var: yellow;
@mixin mix1($arg1, $arg2) {
  background-color: red;
}

@mixin mix2 {
  background-color: blue;
}
```

App.scss
```scss
@use "src/post" as c;

.App {
  @include c.mix2(1px, 2px);
  @include c.mix1;
  background-color: c.$var;
}
```
**Error**
![image](https://user-images.githubusercontent.com/31194806/210182251-3683afb7-2b09-43ad-9218-0bcdfd1411fd.png)
![image](https://user-images.githubusercontent.com/31194806/210182258-25a6712b-a2ce-4352-b11d-4bf775d42b2d.png)
![image](https://user-images.githubusercontent.com/31194806/210182240-c62efd7a-9e21-4499-bdda-b09edb5e9ee3.png)

**Steps to reproduce**
I'm not familiar how to minimally produce with only node-sass, so React was the quickest option for me

1. Use node-sass version
```
node-sass       8.0.0   (Wrapper)       [JavaScript]
libsass         3.5.5   (Sass Compiler) [C/C++]
```
2. Create a new react app with `npx create-react-app my-app`
3. Replace all .css files with scss and use code blocks above

**Steps taken to address**
- Tried using with and without different namespace with `@use "src/post" as c`
- Tried making `post.scss` private `_post.scss` like the example in the documentation link
