### ISSUE TITLE
Regression bug: Parser doesn't correctly resolve strings from variables for inline media queries

### ISSUE THREAD

**Issue by bjmiller** [sass/sass#347]
The example code below parses in alpha.72, and fails to parse in alpha.101 with this error :

> 'Invalid CSS after "    @media ": expected "{", was "$tablet-portrait {")' :

``` scss
$tablet-portrait: "only screen and (min-width: 530px) and (min-height: 480px)";
.myclass {
    height: 38px;
    width: 100%;
    @media $tablet-portrait {
        width: 1000px;
    }
}
```

My assumption is that something from a few weeks ago was reverted in the last batch of changes, possibly accidentally.
