### ISSUE TITLE
@container queries don't substitute variables

### ISSUE THREAD

**Issue by Meithal** [sass/sass#3471]
Hello

```scss
$bp: "foo";

@media (max-width: $bp) {  // @media (max-width: foo)

}
```

works

But

```scss
$bp: "foo";

@container (max-width: $bp) { // @container (max-width: $bp)

}
```
Doesn't work

**Comment by jathak** [comment]
This is working as intended. Allowing uninterpolated SassScript within `@media` queries has caused compatibility issues with new CSS syntax, so we don't support it for `@container`.

To use SassScript within a `@container` query, you need to use interpolation, e.g.:

```scss
$bp: "foo";

@container (max-width: #{$bp}) { // @container (max-width: $bp)

}
```
