### ISSUE TITLE
Is there any way to simplify this code?

### ISSUE THREAD

**Issue by pansong291** [sass/sass#3490]
```css
.highlight {
    color: red;
}
span.highlight {
    padding: 4px 0;
}
h5.highlight {
    padding: 6px 0;
}
h3.highlight {
    padding: 8px 0;
}
```
I want to use `&` but it's not supported to do this.
