### ISSUE TITLE
[sass] $map: "position" top is not a map.

### ISSUE THREAD

**Issue by Profesor08** [sass/sass#3495]
This error happens when I want to use a list of maps with only **one** item. I thinks this is some sort of parser issue, because if I add an comma separator it works good.

#### `error`

```
[plugin:vite:css] [sass] $map: "position" top is not a map.
   ╷
11 │       map.get($border, "position")
   │       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
```

#### `usage` example with error

```scss
.element {
  @include border.dashed(
    (("position": top, "width": 1px, "height": 1px, "space": 7px))
  );
}
```
#### `usage` example without error (comma separator)

```scss
.element {
  @include border.dashed(
    (("position": top, "width": 1px, "height": 1px, "space": 7px),)
  );
}

.element-2 {
  @include border.dashed(
    (
      ("position": top, "width": 1px, "height": 1px, "space": 7px),
      ("position": bottom, "width": 13px, "height": 13px, "space": 17px),
      ("position": left, "width": 3px, "height": 11px, "space": 17px),
      ("position": right, "width": 6px, "height": 3px, "space": 7px)
    )
  );
}
```

#### `@mixin` example

```scss
@use "sass:list";
@use "sass:map";

@mixin dashed($borders: ()) {
  @each $border in $borders {
    $position: map.get($border, "position");
  }
}
```
