### ISSUE TITLE
Weird results when using CSS --vars with rgb...

### ISSUE THREAD

**Issue by EduApps-CDG** [sass/sass#3498]
It's my first day using scss, just made a simple test to see if it works well with css vars:
```scss
$dude: 0,0,0;

:root {
    --whatever: #{$dude};
}

* {
  background: rgb(var(--whatever));
}
```
The code above throwsan error, but with native CSS it's everything okay.
But when I replace `background`'s value to `argb(var(--whatever), 1)` it doesn't throw me any error (Probably due to https://github.com/sass/sass/issues/2175).
Also saw https://github.com/sass/sass/issues/2440. It looks like it's the same issue but it was closed as completed.

I guess i'm doing something wrong, but maybe not as it's a valid css statement.

Here is my output:
![image](https://user-images.githubusercontent.com/32627482/221395661-b7d227c7-0143-489c-ba6b-0b6559aad601.png)
