### ISSUE TITLE
CSS invert and SASS invert are conflicting.

### ISSUE THREAD

**Issue by ByPikod** [sass/sass#3507]
```css
.input {

    --self-background: var(--input-background);
    --self-forecolor: var(--input-forecolor);

    background: var(--self-background);
    color: var(--self-forecolor);

    padding: var(--input-padding);
    transition: all 0.2s;
    border-radius: var(--input-border-radius);

    outline: none;
    border: none;
    
    &:focus {
        --self-background: var(--input-hover-background);
        --self-forecolor: var(--input-hover-forecolor);
    }

    &::placeholder {
        color: invert(var(--self-forecolor));
    }

}
```

![image](https://user-images.githubusercontent.com/46069238/224629051-4d557138-d1b8-46b7-8b6a-ebfe0ed2eb0d.png)

That might be a misunderstanding of mine since I am just learning SASS. But seems like, CSS invert and SASS invert are conflicting. 

Here is a workaround I found:
```css
&::placeholder {
     color: #{"invert(var(--self-forecolor))"};
}
```
