### ISSUE TITLE
How should plain CSS nesting interact with meta.load-css in a Sass nested context ?

### ISSUE THREAD

**Issue by stof** [sass/sass#3532]
Example code:

```scss
@use 'sass:meta';

a {
  @include meta.load-css('nested.css');
}
```

```css
/* nested.css file using plain CSS nesting */
b {
  .c & {
    d: e;
  }
}
```

With the plain CSS nesting proposal, nested.css would be parsed in a way preserving native CSS nesting. But what happens for the scss file loading it in a nested Sass context ? Would the proposal handle that case gracefully already or does it require more changes to the Sass nesting algorithm to handle the case of CSS nesting inside Sass nesting ?
