### ISSUE TITLE
Sass %placeholders generate duplicated rules in every selector

### ISSUE THREAD

**Issue by floroz** [sass/sass#3533]
I am creating a Component Library using Vue and Sass.

## Problem

I want to create Sass `%placeholders` to avoid creating utility classes so that I can keep my style declaration outside of my HTML.

So that I can have

```html
<button class="btn" />
<div class="modal" />
```

Instead of 

```html
<button class="btn flex-center" />
<div class="modal flex-center" />
```

## Reproduction Repo

- https://github.com/floroz/vite-css-module-treeshakable 
- `pnpm install`
- `pnpm build`
- `cat dist/styles.css`

## Setup

I am using

- Vue 3
- Vite 4
- Sass 1.58
- PostCSS 8.4

Let's imagine I have a `BaseBox.vue` and `BaseButton.vue` components

```vue
<template>
  <div class="box"></div>
</template>

<style lang="scss">
@use "../../styles/placeholders";

.box {
  @extend %flex-center;
  color: blue;
}
</style>

```

```vue
<template>
  <button class="btn">Test</button>
</template>

<style lang="scss">
@use "../../styles/placeholders";

.btn {
  @extend %flex-center;
  color: yellow;
}
</style>

```

The `_placeholders.scss` partials contains:

```scss
%flex-center {
  display: flex;
  justify-content: center;
  align-items: center;
}
```

## Expected output

Now, when I build the library, in the final bundled `style.css` I would expect to find

```css
.box, .btn {
  display: flex;
  justify-content: center;
  align-items: center;
}

.box {
 color: blue;
}

.btn {
 color: yellow;
}

```

## Received output

However, the output I am receiving is:

```css
.btn {
  display: flex;
  justify-content: center;
  align-items: center;
}
.btn {
  color: yellow;
}
.box {
  display: flex;
  justify-content: center;
  align-items: center;
}
.box {
  color: blue;
}
```

After applying `postcss` with `cssnano` to handle merging rules, the output becomes

```css
.btn {
  align-items: center;
  color: #ff0;
  display: flex;
  justify-content: center
}

.box {
  align-items: center;
  color: blue;
  display: flex;
  justify-content: center
}
```

This is still not what I want to achieve, as it means I cannot create placeholder to avoid increasing the CSS bundle size.
