### ISSUE TITLE
Dynamically add nested classes

### ISSUE THREAD

**Issue by jonatankruszewski** [sass/sass#3557]
Hi community!

The mixin is not supporting the &.[className].

It would be nice if it would.

For example:

Let's say I want to generate:
```
.root {
  &.row-cols-auto>* {
    flex: 0 0 auto;
    width: auto;
  }

  &.row-cols-1>* {
    flex: 0 0 auto;
    width: 100%;
  }

  &.row-cols-2>* {
    flex: 0 0 auto;
    width: 50%;
  }

  &.row-cols-3>* {
    flex: 0 0 auto;
    width: 33.3333333333%;
  }

  &.row-cols-4>* {
    flex: 0 0 auto;
    width: 25%;
  }

  &.row-cols-5>* {
    flex: 0 0 auto;
    width: 25%;
  }

  &.row-cols-6>* {
    flex: 0 0 auto;
    width: 16.6666666667%;
  }
}
```

For that I created the following mixin:

```
$grid-row-columns: 6;

@mixin create-row-cols () {
  &.row-cols-auto>* {
    flex: 0 0 auto;
    width: auto;
  }

  @for $i from 1 through $grid-row-columns {
    &.row-cols-#{$i}>* {
      flex: 0 0 auto;
      width: math.percentage(math.div(1, $i));
    }
  }
}
```

Then, when replacing the code:
```
.root {
 @include create-row-cols()
}
```

it doesn't work.

**Comment by nex3** [comment]
This works for me, and produces

```scss
.root.row-cols-auto > * {
  flex: 0 0 auto;
  width: auto;
}
.root.row-cols-1 > * {
  flex: 0 0 auto;
  width: 100%;
}
.root.row-cols-2 > * {
  flex: 0 0 auto;
  width: 50%;
}
.root.row-cols-3 > * {
  flex: 0 0 auto;
  width: 33.3333333333%;
}
.root.row-cols-4 > * {
  flex: 0 0 auto;
  width: 25%;
}
.root.row-cols-5 > * {
  flex: 0 0 auto;
  width: 20%;
}
.root.row-cols-6 > * {
  flex: 0 0 auto;
  width: 16.6666666667%;
}
```

What version of Sass are you using? When you say "it doesn't work", what is happening instead?
