### ISSUE TITLE
Whitespace normalization

### ISSUE THREAD

**Issue by Anahkiasen** [sass/sass#356]
Twitter just introduced their own LESS compiler to go with Bootstrap, among other things that SASS already does built-in there was just that one single feature that I thought had that cherry-on-top effect that would be nice on SASS. In particular for people that like to crawl through other people's CSS : whitespace normalization.

See [Recess](http://twitter.github.com/recess/) over here, the bit with the box-shadow; basically what it does is search for groups with similar values and core properties and align them all to a prettier output.

``` css
.avatar img {
  -webkit-box-shadow: inset 0 1px 5px rgba(0, 0, 0, 0.2);
     -moz-box-shadow: inset 0 1px 5px rgba(0, 0, 0, 0.2);
      -ms-box-shadow: inset 0 1px 5px rgba(0, 0, 0, 0.2);
       -o-box-shadow: inset 0 1px 5px rgba(0, 0, 0, 0.2);
          box-shadow: inset 0 1px 5px rgba(0, 0, 0, 0.2);
}
```

I know it's far from top-priority. Far from it. But I don't know, I thought it was a nice touch and I don't if it that's much of a big work. I mean although preprocessors make developping easier, it doesn't make the output CSS any easier to read, so I don't know, why not a little more readable along the way, could be nice.

**Comment by nex3** [comment]
Nice output is definitely something Sass strives for, and I'd love to see this. That said, functional features probably take precedence over this for near-future development energy.

**Comment by mckramer** [comment]
Here is the [prefix-whitespace.js](https://github.com/twitter/recess/blob/master/lib/compile/prefix-whitespace.js) file from [twitter/recess](https://github.com/twitter/recess) that @Anahkiasen mentioned that handles the formatting of the vendor prefixes.

I tried to look through the code a bit for Sass to see if something similar could be worked in easily, but Recess has the sibling nodes available, and I do not believe that is the case in Sass.

For the `:nested` and `:expanded` css outputs, it would be possible to at least prefix the vendor specific properties, but not the standard property, ie:

``` css
.avatar img {
  -webkit-box-shadow: inset 0 1px 5px rgba(0, 0, 0, 0.2);
     -moz-box-shadow: inset 0 1px 5px rgba(0, 0, 0, 0.2);
      -ms-box-shadow: inset 0 1px 5px rgba(0, 0, 0, 0.2);
       -o-box-shadow: inset 0 1px 5px rgba(0, 0, 0, 0.2);
  box-shadow: inset 0 1px 5px rgba(0, 0, 0, 0.2);
}
```

Check if the property name starts with a vendor prefix and add the padding. But, without access to sibling properties (or adding a `@last_node` variable), I cannot see a way to properly format it.

Hopefully someone else can look into this and find a good way to implement it, because stylistically, I really like this.
