### ISSUE TITLE
Optimization of attribute selectors in SCSS: output efficiency

### ISSUE THREAD

**Issue by rentalhost** [sass/sass#3584]
I'm not sure if this is a responsibility of SCSS, but I have the following code:

```scss
[data-color] {
  --bg-hue: 210;
  
  &[data-color="C2"] { --bg-hue: 318; }
  &[data-color="C3"] { --bg-hue: 66; }
}
```

Note that if the **attribute selector** `[data-color="C2"]` or `[data-color="C3"]` is _valid_, essentially `[data-color]` is also _valid_ (in that order, of couse).

However, the **current output** is:

```scss
[data-color] { --bg-hue: 210; }
[data-color][data-color="C2"] { --bg-hue: 318; }
[data-color][data-color="C3"] { --bg-hue: 66; }
```

Which is **perfectly valid**, but **not optimized**.

My suggestion would be to "understand this rule" and output would be just:

```scss
[data-color] { --bg-hue: 210; }
[data-color="C2"] { --bg-hue: 318; }
[data-color="C3"] { --bg-hue: 66; }
```

My actual use case is that I use the `[data-color]` selector to group the other equivalent selectors together and be able to fold them more easily within the IDE.
