### ISSUE TITLE
Proposal: Variable Media queries 

### ISSUE THREAD

**Issue by KonkenBonken** [sass/sass#3589]
Wouldn't it be useful to be able to use media queries with variables and having Sass resetting the rules for us?

Example:
**Input** 
```scss
$clr-bg: white;
$clr-txt: black;

@media (prefers-color-scheme: dark) {
  $bg: black;
  $clr-txt: white;
}

body {
  background-color: $clr-bg;
  color: $clr-txt;
}
```

**Output** 
```css
body {
  background-color: white;
  color: black;
}

@media (prefers-color-scheme: dark) {
  body {
    background-color: black;
    color: white;
  }
}
```

Why hasn't this been added? What am I missing?

**Comment by nex3** [comment]
Sass variables are _imperative_, which means that they're evaluated statement-by-statement. This allows them to do powerful things like conditionals, statements, loops, storing state in modules, and so on. But it also means that updating them lazily, or only in certain contexts, isn't feasible.

Fortunately, CSS also has variables, and those are _declarative_. They work exactly how you want here:

```css
:root {
  --clr-bg: white;
  --clr-txt: black;
}

@media (prefers-color-scheme: dark) {
  :root {
    --clr-bg: black;
    --clr-txt: white;
  }
}

body {
  background-color: var(--clr-bg);
  color: var(--clr-txt);
}
```

Use the right tool for the job. If you want declarative variables that can have different values based on `@media` contexts, use CSS variables. If you want complex build-time logic, use Sass variables.
