### ISSUE TITLE
@media bubbling for @extend

### ISSUE THREAD

**Issue by scottkellum** [sass/sass#359]
Support for `@media` bubbling with `@extend`

SCSS:

``` scss
%width-1 { width: 33.333%; }
%width-2 { width: 66.666%; }
%width-3 { width: 100%; }

article { @extend %width-2; }

@media all and (min-width: 20em) {
    article { @extend %width-3; }
}
```

Desired CSS:

``` css
article {
  width: 66.666%; }

@media all and (min-width: 20em) {
  article {
    width: 100%; }
}
```

Actual CSS:

``` css
article {
  width: 66.666%; }

article {
  width: 100%; }
```

I could have sworn this worked before but it doesn’t in the latest build.

Bubbling from inside out would be awesome but this has never worked in any version I tried.

``` scss
article { 
  @media all and (min-width: 20em) {
    @extend %width-3; 
  }
}
```

EDIT: I am on 3.2.0.alpha.101
