### ISSUE TITLE
*:psuedo { &[attr]{ ... } } appends [attr] to the end after the psuedo

### ISSUE THREAD

**Issue by donatj** [sass/sass#360]
``` scss
div:before {
    &[id] {
        content: "#" attr(id);
    }
}
```

results in 

``` css
div:before[id] { content: "#" attr(id); }
```

which is invalid and does not work. It instead should result in 

``` css
div[id]:before { content: "#" attr(id); }
```
