### ISSUE TITLE
CSS variable darken and lighten function not working when announcing.

### ISSUE THREAD

**Issue by adoin** [sass/sass#3601]
As we knodw 
```scss
.selector{
  color: darken(var(--va-color-blue),20);
}
```
Not working because compiler do not know what color "var(--va-color-blue)" is.
But why does this not working?
```scss
:root{
--va-d3-blue: darken(#446cce,30%);
}
```
The darken calculator didn't work. The compile result is --va-d3-blue: darken(#446cce,30%) and catch to be white.
What should I do to make it works?
Or this can be implement in future?
