### ISSUE TITLE
lighten inoperative

### ISSUE THREAD

**Issue by hututu-yo** [sass/sass#3614]
```scss
@use 'sass:color';

$theme-color-value: (
    light: (
        page-name: (
            color: #df3232
        ),
        modal-name: (
            color: #7ac13c
        )
    ),
    // 对应某个主题
    dark:
        (
            // 对应某个模块的颜色
            page-name:
                (
                    color: #c1d016
                ),
            modal-name: (
                color: #d6a18b
            )
        )
);

$theme-name: (
    // 对应某个模块需要的类名
    page-name:
        (
            text-color-primary: 100%,
            bg-color: 10%,
            text-coldavdor-seconsssadddary: 100%
        ),
    modal-name: (
        text-cssdsolor-primary: 100%,
        bsadshg-color: 10%,
        text-coxsdsvxlor-secondary: 100%
    )
);
$abs: #c7d016;
.color {
    color: lighten($abs, 10%);
}
@each $K, $V in $theme-color-value {
    [data-theme='#{$K}'] {
        @each $k, $v in $V {
            $color1: #{map-get(
                    $map:
                        map-get(
                            $map: $V,
                            $key: $k
                        ),
                    $key: color
                )};
            @each $K1, $V1 in map-get($map: $theme-name, $key: $k) {
                --#{$K1}: lighten(#{$color1}, #{$V1});

                // --#{$K1}: #{$color1};
            }
        }
    }
}

```
Compile will be
```scss
.color {
  color: #e0e930;
}

[data-theme=light] {
  --text-color-primary: lighten(#df3232, 100%);
  --bg-color: lighten(#df3232, 10%);
  --text-coldavdor-seconsssadddary: lighten(#df3232, 100%);
  --text-cssdsolor-primary: lighten(#7ac13c, 100%);
  --bsadshg-color: lighten(#7ac13c, 10%);
  --text-coxsdsvxlor-secondary: lighten(#7ac13c, 100%);
}

[data-theme=dark] {
  --text-color-primary: lighten(#c1d016, 100%);
  --bg-color: lighten(#c1d016, 10%);
  --text-coldavdor-seconsssadddary: lighten(#c1d016, 100%);
  --text-cssdsolor-primary: lighten(#d6a18b, 100%);
  --bsadshg-color: lighten(#d6a18b, 10%);
  --text-coxsdsvxlor-secondary: lighten(#d6a18b, 100%);
}`

**Comment by Goodwine** [comment]
(I edited your question to use the correct [codeblock markdown syntax](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))

**Comment by Goodwine** [comment]
The problem here is that your custom properties have interpolation in the wrong place. Custom property values are passed as-is to the final CSS, and `lighten` is not valid CSS. You must use interpolation `#{}` around SassScript. See:

https://sass-lang.com/documentation/style-rules/declarations#custom-properties

> “Sass parses custom property declarations differently than other property declarations. All tokens, including those that look like SassScript, are passed through to CSS as-is. The only exception is interpolation, which is the only way to inject dynamic values into a custom property.”

I notice that you _are_ using interpolation, but you are using it in the wrong place.

For example you have:
```scss
--foo: lighten(#{$color1}, #{$V1})
```
This will output `lighten()` as-is to CSS, and this is not valid.

And another issue with your example is that you are over-using interpolation when creating the `$color1` variable.

I think you want to use this:
```scss
// .. rest of your code from above
@each $K, $V in $theme-color-value {
    [data-theme='#{$K}'] {
        @each $k, $v in $V {
            $color1: map-get( // <-- no interpolation #{} anymore!
                    $map:
                        map-get(
                            $map: $V,
                            $key: $k
                        ),
                    $key: color
                );
            @each $K1, $V1 in map-get($map: $theme-name, $key: $k) {
                --#{$K1}: #{lighten($color1, $V1)}; // <-- Interpolation goes around entire function!
            }
        }
    }
}
```
