### ISSUE TITLE
Variable scoping broke when CSS layer is used

### ISSUE THREAD

**Issue by zipper** [sass/sass#3617]
When CSS Layers are used, the variables defined inside certain scope can bleed outside its scope. See attached [codepen](https://codepen.io/zipper/pen/poQbyJK), where each of the boxes should imho have a different background color. Even though the variable is scoped inside selector, it overrides the previous value for another usage. I'm not sure if it is desired behaviour, but I would expect that [shadowing](https://sass-lang.com/documentation/variables#shadowing) would happen.

Of course, when the `@layer ui` is removed, the variables behave as expected. I guess the shadowing doesn't apply, as the `$bg` is not declared as global? I reproduced this issue while using bootstrap, therefore I can't define the variables as global explicitly.

**Comment by nex3** [comment]
Your input Sass is:

```scss
@layer ui {
  $bg: red !global;

  .box--blue {
    $bg: blue;
    background: $bg;
  }

  .box {
    display: block;
    width: 100px;
    height: 100px;
    background: $bg;
  }
}
```

this produces:

```css
@layer ui {
  .box--blue {
    background: blue;
  }

  .box {
    display: block;
    width: 100px;
    height: 100px;
    background: red;
  }
}
```

This is the output I'd expect. What about it isn't what you'd expect?

**Comment by zipper** [comment]
That output is as expected, but I see different output on codepen above. There the both boxes have the same color (depending on `!global` used or not). So the output I see is:
```css
@layer ui {
  .box--blue {
    background: blue;
  }

  .box {
    display: block;
    width: 100px;
    height: 100px;
    background: blue;
  }
}
```

But even if it works with `!global`, the problem would be, that I don't have `!global` when first defining the variable. And I can't actually add that, because those variables are defined in third party library (bootstrap).

So my input is actually someting like this:
```scss
@layer ui {
    @import "bootstrap/scss/variables";

    ...

    .some-selector {
        // define some variable with same name as bootstrap uses; this variable
        // overrides the supposedly global `$border-radius` from variables file
        $border-radius: 1rem;

        ...
    }

    // from here, all components using `$border-radius` would use 1rem instead
    // the value defined in variables file
}
```
