### ISSUE TITLE
how to make loaded meta.load-css file unify with the parent class

### ISSUE THREAD

**Issue by mhamri** [sass/sass#3618]
Sorry to put this one here, but no one in [SO](https://stackoverflow.com/questions/76475533/how-to-make-loaded-meta-load-css-file-unify-with-the-parent-class) could answer, so probably this could become a feature request or maybe a little improvement in the documentation. 

I'm working with SCSS and have a style file called `popover.min.scss`.

```scss

// popover.min.css
.popover {
     color: red;
}

.popover .left {
   left: 0;
}
```

This file is from a library, so I'm unable to modify it. However, I must wrap it in another class so that every class name is prefixed with `.foo`. In other words, I want the class names to look like this:

```scss

.foo.popover {
     color: red;
}

.foo.popover .left {
   left: 0;
}
```

I've attempted various methods such as using `selector.unify` or `@extend`, but none of them have worked. For example:

```scss

@use "sass:meta";

.foo {
    @at-root & {
         @include meta.load-css("popover");
    }
}
```

or

```scss

@use "sass:meta";

%bar {
    @include meta.load-css("popover");
}

.foo {
    @extend %bar;
}
```

However, these approaches haven't produced the desired outcome.

It produces this result 

```scss
.foo .popover {
     color: red;
}

.foo .popover .left {
   left: 0;
}
```

Since the library only let me add a class at the same level as their class, having `.foo .popover` isn't desirable, and only I could achieve my goal by producing `.foo.popover` (same level)
