### ISSUE TITLE
Bogus combinator warning on nested class

### ISSUE THREAD

**Issue by EmSixTeen** [sass/sass#3621]
I'm using the following class:

```scss
.o-button-row {
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;

    > &__button {
        padding: 0.5em 1.25em;
    }
}
```

As I understand that, looking at is as a reading order, it's `.o-button-row`, then `>`, then `.o-button-row` again with `__button` attached to that.

I get the following error when doing this: 
> Deprecation Warning: The selector "> .o-button-row__button" is invalid CSS.
> This will be an error in Dart Sass 2.0.0.

I can change to `& > &__button {` and it'll work, but that doesn't feel like it should be necessary given that it's already nested inside a class.

I can't help but think that I'm either missing something very obvious, or there's a bug. _Is_ this working as intended? Or what am I doing wrongly here?

Thanks in advance.

---

**Structure:**
```
/sass/style.scss
    @use 'objects';

/sass/objects/_index.scss
    @forward 'button-row';

/sass/objects/_button-row.scss
    (… with class from previous codeblock)
```

**package.json**
```json
{
    "name": "",
    "version": "0.1",
    "description": "",
    "devDependencies": {
        "autoprefixer": "^10.4.13",
        "gulp": "^4.0.2",
        "gulp-postcss": "^9.0.1",
        "gulp-rename": "^2.0.0",
        "gulp-sass": "^5.1.0",
        "sass": "^1.56.1"
    }
}

```

**gulpfile.js**
```js
const gulp = require('gulp');
const sass = require('gulp-sass')(require('sass'));
const autoprefixer = require('autoprefixer');
const postcss = require('gulp-postcss');
const rename = require('gulp-rename');

/**
 * Build the CSS from SASS partials
 */
gulp.task('sass', () => {
    return (
        gulp
            .src('./sass/*.scss')

            // Autoprefix
            .pipe(postcss([autoprefixer()]))

            // Output expanded css
            .pipe(sass({ errLogToConsole: true, outputStyle: 'expanded' }))
            .pipe(gulp.dest('./css'))

            // Rename and output minified css
            .pipe(sass({ errLogToConsole: true, outputStyle: 'compressed' }))
            .pipe(rename({ suffix: '.min' }))
            .pipe(gulp.dest('./css'))
    );
});

/**
 * Watch SCSS files for changes
 *
 * ! Unlike many tuts, you need to put the tasks inside a .series in Gulp >4
 * - gulp.series(['foo', 'bar']) for several
 *
 * @link https://gulpjs.com/docs/en/api/watch/
 */
gulp.task('watch', () => {
    return gulp.watch(['./sass/**/*.scss'], gulp.series('sass'));
});

/**
 * Set up a default task
 */
gulp.task('default', gulp.series('watch'));
```

**Comment by nex3** [comment]
As soon as you use a `&` in a selector, it turns off the default nesting behavior. If you want the parent selector to appear twice, you need to use `&` twice:

```scss
.o-button-row {
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;

    & > &__button {
        padding: 0.5em 1.25em;
    }
}
```
