### ISSUE TITLE
Re-consider deprecating @import & global imports

### ISSUE THREAD

**Issue by ShadiestGoat** [sass/sass#3628]
Hello!

I could not find a discussion relating to this anywhere, so I started a new one. 

The [SASS @import documentation](https://sass-lang.com/documentation/at-rules/import) clearly states that @import will soon be deprecated and removed, with several reasons given for this action. However, please consider the following setup:

```scss
// main.scss

@use "vars.scss" as *;

@import "partial1.scss";
@import "partial2.scss";
@import "partial3.scss";

// vars.scss
$blue-1: #0000ff;

//partialX.scss
.foo {
    color: $blue-1;
}
```

In this setup, the partials use variables defined in `vars.scss`. With `@use`, this requires an extra line in each partial importing the variables again. This is especially annoying for conditional exports such as for themes, which require more lines to import.

Global imports have their uses - it should not be phased out from the spec. Although I do recognize that `@import` is easy to misinterpret as the non-global syntax, perhaps a new at-rule should be created that acts exactly like `@import`, but called `@global`? This way, it still allows for the desired functionality, but explicitly states that this is a global import.
