### ISSUE TITLE
JS API: Add Exception.loadedUrls

### ISSUE THREAD

**Issue by sod** [sass/sass#3629]
Consider these 3 files:

```scss
# a.scss
@import './b.scss'

# b.scss
@import './c.scss'

# c.scss
.foo { color: $unknownVariable }
```

Bundling `a.scss` would roughly throw this exception:
```
Exception {
    message: 'Undefined variable',
    span: { url: new URL('c.scss') },
}
```

The bundler now knows `a.scss` (entry file) and `c.scss` (error.span.url) but `b.scss` isn't mentioned. So trying to fix the error in `b.scss` (remove the import or add the variable) woudn't trigger a rebuild.

This could be solved by returning the [`loadedUrls`](https://sass-lang.com/documentation/js-api/interfaces/compileresult/#loadedUrls) array on the exception so the bundler can watch all files that have been touched.
