### ISSUE TITLE
Ability to store media queries in variables and use it inside a variable styling

### ISSUE THREAD

**Issue by Shaik-mohd-huzaifa** [sass/sass#3633]
Media Queries in Sass should be stored in variables and used in individual element styling whichever element is supposed to be put into that particular media queries by mentioning their respective variables inside the element and adding styling inside normal CSS styling braces <code>{ styling }</code>. After getting compiled they look like normal CSS media queries in a CSS file.

* The media query should be stored as a value inside a variable 

### Syntax    

* The syntax below is a general representation of the feature and may differ and can have changes or additions depending on further decisions.

```scss
var $mobile: (max-width: 550px);
var $tablet: (max-width: 700px);

h1{
   font-size: 50px;
   $mobile{
       font-size: 25px;
   }
   $tablet{
       font-size: 35px
   }
}

p{
  color: green;
  font-size: 3em;
  $mobile{
      font-size: 1.5em;
  }
}
```

Compile to Css from Sass

```css
h1{
  font-size: 50px;
}

p{
  font-size: 3em;
}

@media mobile and (max-width: 550px){
  h1{
    font-size: 25px;
  }
  p{
    font-size: 1.5em;
  }
}

@media tablet and (max-width: 700px){
  h1{
     font-size: 35px;
  }
}

```

### Benefits from this feature

* This feature of storing media queries into variables and adding them to a particular element will help the developer by not increasing the size of media queries where all the individual elements are mentioned with their styling. Till will lead to confusion while changing the styling properties. may lead to lengthy and unorganized code.
* Eases the developer to read, organize and change the styling.
* Rather than searching for the element to change the style in a particular media query the dev can directly go to the element which is to be styled and add the media query and style in it.

**Comment by jathak** [comment]
You can use interpolation to do this, e.g.
```scss
$mobile: "mobile and (max-width: 550px)";
$tablet: "tablet and (max-width: 700px)";

h1{
   font-size: 50px;
   @media #{$mobile} {
       font-size: 25px;
   }
   @media #{$tablet} {
       font-size: 35px
   }
}

p{
  color: green;
  font-size: 3em;
  @media #{$mobile} {
      font-size: 1.5em;
  }
}
```
