### ISSUE TITLE
Compilation failure occurs when using a string variable with the "@" character as a selector

### ISSUE THREAD

**Issue by rmnilin** [sass/sass#3636]
I'm having trouble compiling some SCSS code. The compilation process fails and I receive an error:

```
Error: expected selector.
╷
3 │ @-moz-document url-prefix(){
│ ^
╵
style.scss 3:1 root stylesheet
```

Here are the code snippets that are causing the issue:

```scss
$demo: '@media screen and (-ms-high-contrast: active), (-ms-high-contrast: none)';

#{$demo} {
  a {
    color: blue;
  }
}
```

```scss
$demo: '@-moz-document url-prefix()';

#{$demo} {
  a {
    color: blue;
  }
}
```

This error is preventing me from defining a little more complex cases, like the following example:

```scss
@mixin browsers($browsers) {
    $selectors: (
        chrome: '&:not(*:root)',
        firefox: '@-moz-document url-prefix()',
        ie: '@media screen and (-ms-high-contrast: active), (-ms-high-contrast: none)'
    );

    @each $browser in $browsers {
        #{map-get($selectors, $browser)} {
            @content;
        }
    }
}
```

I couldn't find any previous reports or additional information related to this issue. I would appreciate any assistance in verifying the correctness of the syntax and resolving this problem. If you have any guidance or suggestions, please let me know.
