### ISSUE TITLE
Feature Request: nth Parent Selector

### ISSUE THREAD

**Issue by x6eull** [sass/sass#3637]
I want to use "the parent of the current parent" in a nested selector.
A use case looks like:
```scss
#root{
    .todo-item{
        .mark{
            // some rules
        
            // I want to select "#root .todo-item:hover .mark"
            &&:hover &{
                background: gray;
            }
        }
    }
}
```
I have found no approach to make this into reality.
For now, the only way to select "#root .todo-item:hover .mark" is using `&:hover .mark` in `.todo-item`'s rules. It's a bit wordy, while a practical nth Parent Selector would make the code clearer and more reasonable as `background: gray` should belong to `.mark`.

I've read #2690, #2264 and [sass:selector module document](https://sass-lang.com/documentation/modules/selector). I ran into `$selector: Parent selectors aren't allowed here.` error when I tried to find a way out. It seems that there's no perfect workaround to achieve this (@at-root would discard `#root` in the case). It there is, please mention it. If it could be achieved using selector functions or something alike, consider adding a implement as a build-in function. It will be pretty useful!

Thanks for the time. Apologies for any mistakes as English isn't my native language.
