### ISSUE TITLE
Sort properties

### ISSUE THREAD

**Issue by Anahkiasen** [sass/sass#364]
I love Sass because of how cleaner it makes any CSS and uniformizes it ; my only request would be - could it be possible to had a  flag (off by default) to make Sass sort properties ? Like

``` css
header
{
    padding: 10px;
    background: whiteSmoke;
    text-align: center;
    margin-top: 10px;
    display: block;
}
```

to

``` css
header
{
    background: whiteSmoke;
    display: block;
    margin-top: 10px;
    padding: 10px;
    text-align: center;

}
```

Mose CSS beautifier or formatter offer that option and I found it really offer an feeling of uniformity throughout a whole CSS ; it also gets easier to spot where are each property and to see common properties (margin, padding, etc) following one another.
Of course that should be a facultative flag as it may cause properties conflict on certain edge cases.
