### ISSUE TITLE
%placeholder, mixins and @media

### ISSUE THREAD

**Issue by Anahkiasen** [sass/sass#369]
I'm trying to do something that I though was simple, but actually not. I have a set of predefined mixins, each one extend a particular placeholder. It would usually be simple but inside the case of an @media query, it doesn't go as expected, I think @extend and @media don't behave well together.
Here is a simplified test :

``` sass
=red
    @extend %red
=blue
    @extend %blue   

$media: 250px 500px
@each $m in $media
    @media all and (max-width:#{$m})
        %red
            color: red
        %blue
            color: blue

        article
            @if $m == 250px
                +red
            @else
                +blue
        aside
            @if $m == 250px
                +blue
            @else
                +red
```

Which outputs incorrectly the following :

``` css

@media all and (max-width: 250px) {
  article, aside {
    color: red; }

  aside, article {
    color: blue; } }
@media all and (max-width: 500px) {
  article, aside {
    color: red; }

  aside, article {
    color: blue; } }
```

Am I missing something or is there another way to do that ?
