### ISSUE TITLE
sass-convert places brackets after line comments

### ISSUE THREAD

**Issue by scottkellum** [sass/sass#371]
Open brackets are commented out when converting sass with a line comment after a selector.

``` sass
.foo // comment
  width: 20em
```

converts to

``` scss
.foo // comment {
  width: 20em;
}
```

The expected conversion looks like this:

``` scss
.foo { // comment
  width: 20em;
}
```
