### ISSUE TITLE
Adding CSS Variable Support

### ISSUE THREAD

**Issue by M1dnight-ofcl** [sass/sass#3751]
I'm not too sure wether this is because I am using the live sass compiler extension on vscode, but something I've notice is that my compiled sass code never uses variables. For example if I have a code like the following:
```scss
$bg1: #000;
body {
  background: $bg1;
  height: 100dvh;
  width: 100dvw;
  &, * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }
}
```
I would expect it to compile to this:
```css
:root {
  --bg1: #000;
}
body {
  background: var(--bg1);
  height: 100dvh;
  width: 100dvw;
}
body, body * {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}
``` 
but it compiles to this:
```css
body {
  background: #000;
  height: 100dvh;
  width: 100dvw;
}
body, body * {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}
```

Is there a way to implement this? I write a lot of code that sometimes requires me to change css variables through javascript but I also like to code with sass.
