### ISSUE TITLE
Feature request: @no-render to allow pre-compile/introspection

### ISSUE THREAD

**Issue by jakob-e** [sass/sass#3772]
The idea behind a **_@no-render_** (working title) feature is to allow pre-compiling of the SCSS content without rendering it to the final CSS.

Having a non-CSS-producing step will allow us to inspect the entire context of the build - e.g. mapping what @​includes and @​functions were used and use this information to set up an optimized compile. 

 _Think of it as a sanitation rule that ignores the @no-render block - similar to how comments, etc. are stripped 
 ...but allows @​content_

**Update:** alternative solution below example

Here is an example that would only render out CSS Variables if used

[Codepen Demo](https://codepen.io/jakob-e/pen/yLwYyPW )
 
```SCSS

@use 'sass:map';
@use 'sass:list';

$inspect-compile-state: false;

@mixin compile {
    // pre-compile to allow collecting information on
    // includes, function calls etc. (no CSS produced)
    @no-render {
        $inspect-compile-state: true !global;
        @content;
        $inspect-compile-state: false !global;
    }

    // compile (CSS produced)
    @content;
};


// list of used colors
$used-color-list: ();


// map holding the available project colors
$color-map: (
    'none': transparent,
    'white': white,
    'black': black,
    'red': red,
    /*.... and a whole lot more */ 
);


// mixin to produce color variables based on $color-map
@mixin color-vars {
    html {
        @each $name, $color in $color-map {
            @if $inspect-compile-state or list.index($used-color-list, $name) {
                --color-#{$name}: #{$color};
            }
        }
    }
}


// function to return a CSS variable based on color name (if it exists)
@function color($name) {
    $color: map.get($color-map, $name);
    @if not $color {
        @error 'Color #{$name} does not exist!';
    }
    // register color as used
    @if $inspect-compile-state {
        $used-color-list: list.append($used-color-list, $name) !global;
    }
    @return var(--color-#{$name});
}


// color using components
@mixin comp-1 {
    .comp-1 {
        color: color('white');
    }
}
@mixin comp-2 {
    .comp-2 {
        color: color('black');
    }
}


// assemble
@include compile {
    @include color-vars;
    @include comp-1;
    @include comp-2;
}


```

**CSS Output** 
```CSS

/* This part should not render in the CSS
@no-render {
  html {
    --color-none: transparent;
    --color-white: white;
    --color-black: black;
    --color-red: red;
  }

  .comp-1 {
    color: var(--color-white);
  }

  .comp-2 {
    color: var(--color-black);
  }
}
*/

html {
  --color-white: white;
  --color-black: black;
}

.comp-1 {
  color: var(--color-white);
}

.comp-2 {
  color: var(--color-black);
}
```

**Alternative syntax** If easier to implement the above could also be solved by allowing @​content inside comments
... maybe using **_meta.inspect_**. _Note!_ comments in @​content could cause problems 

```SCSS
@use 'sass:meta';

@mixin compile {
    $inspect-compile-state: true !global;
    /* #{@content} */   
    // or 
    /* #{meta.inspect(@content)} */    
    $inspect-compile-state: false !global;
    
    @content;
};
```

I hope it makes sense - I'll be happy to elaborate   :-)

**Comment by jakob-e** [comment]
**_Use case example 2 - re-composition/render order_** 

In this scenario, we want to ensure an _all: unset_ reset comes in earlier than our base reset regardless of include order. This could also be used to ensure base components being included before variation overrides etc.

[Codepen Demo](https://codepen.io/jakob-e/pen/xxBwVXP)
```SCSS
@use 'sass:list';

$inspect-compile-state: false;

@mixin compile {
    @no-render {
        $inspect-compile-state: true !global; 
        @content;
        $inspect-compile-state: false !global;
    }
    @content;
};

// list to keep track of what was rendered
$once-list: ();

// list to keep track of what was included
$used-mixin-list: ();


// wrapper to mark a mixin as used
@mixin mark-as-used($token) {
    @if $inspect-compile-state {
        $used-mixin-list: list.append($used-mixin-list, $token) !global;
        @content;
    }
    
    @else if not list.index($once-list, $token) {
        $once-list: list.append($once-list, $token) !global;
        @content;
    } 
    
} 

// wrapper to render mixin if used (at a later point)
@mixin render-if-used($token) {
    @if list.index($used-mixin-list, $token) {
        @content;
    }
}


// base reset
@mixin reset-base {
    // render reset-button here if included later than 
    // the base reset itself  
    @include render-if-used('reset-button') {
        @include reset-button;
    }
    *,*::before,*::after { 
        box-sizing: border-box; margin: 0; 
    }
}

// button reset
@mixin reset-button {
    @include mark-as-used('reset-button') {
        button {
            all: unset;		
        }
    }
}

// assemble 
@include compile {
    // this is where we want reset-button to render
    // to avoid overriding our base reset  
    @include reset-base;
    @include reset-button;	
}
```
**CSS Output**
```CSS
/* This part should not render in the CSS
@no-render {
    *, *::before, *::after {
      box-sizing: border-box;
      margin: 0;
    }
    button {
      all: unset;
    }
  }
*/

/* button reset ported here - even if included after base reset */
button {
  all: unset;
}

*, *::before, *::after {
  box-sizing: border-box;
  margin: 0;
}
```

**Comment by nex3** [comment]
I don't think this reaches the high bar for adding new syntax to the language. I don't see tracking which mixins would theoretically be used by a given `@content` block as something with broad utility across a wide range of use-cases.

**Comment by jakob-e** [comment]
@nex3 

What about the alternative version **_that allows printing @​content in a comment block_**? (that does not introduce new syntax)... or allow using **_meta.inspect(@​content)_** 

I've found this introspection to be quite useful (it can to some extent, pun intended, be implemented using %placeholders - but it has problems with @ rules being lifted out). IMO the ability to control composition +. linting/error handling is what makes Sass stand out from PostCSS and modern CSS features.

````Scss

/* #{@content} */   

or 

/* #{meta.inspect(@content)} */    

or 

$content-string: meta.inspect(@​content);
`````
