### ISSUE TITLE
Having a typo for lighten and darken doesn't throw an error

### ISSUE THREAD

**Issue by biast12** [sass/sass#3776]
So i just noticed that when I do a typo for lighten or darken does it not throw an error about the syntax, it just does nothing, this code below shows an example of what i mean:

```.btn-default {
  background: #0076A4;
  &:hover {
    background: lighte(#0076A4, 10%);
  }
}

**Comment by nex3** [comment]
Sass is designed to be forwards-compatible with CSS by not building in strong assumptions about which properties, type selectors, or in this case function names will exist in the future. This is one reason we've moved towards encouraging users to load Sass functions from modules, which _do_ verify that the functions you call actually exist:

```scss
@use "sass:color";

.foo {
  background: #0076A4;
  &:hover {
    background: color.scale(#0076A4, $lightness: 10%);
  }
}
```
