### ISSUE TITLE
Migration from @import to @use seems impossible with !default

### ISSUE THREAD

**Issue by hugobarragon** [sass/sass#3782]
Hi, trying to migrate and cant seem to find a way!!
basicly its a lib with default styles that the final user can override the variables to customize the theme with scss+modules

for example:
```
config.scss
/* Default variable to avoid sass loader config obligation */
$prefix-cls: xpto !default;
```

```
card.module.scss
@import '../ConfigProvider/config';

.card {
  :global(.#{$prefix-cls}-card-cover) {
    display: flex;
    justify-content: center;
    margin-top: 20px;
  }

  .avatar-card-cover {
    display: flex;
    justify-content: center;
    width: 80px;
    height: 80px;
    background-color: #1f1f99; // TODO: check this color
  }

  :global(.#{$prefix-cls}-card-meta-description) {
    margin-bottom: 20px;
  }
}
```

and then the users with sass loader do this  to override $prefix-cls 
```
 {
    loader: "sass-loader",
    options: {
       additionalData: "$prefix-cls: " + sbPrefixCls + ";",
    },
  },
```

already try everything with @use as *; and cant find a way to migrate this, and the sass-migrate plugin does not work to everything works fine with @import  

get the following error with @use  
SassError: This module and the new module both define a variable named "$prefix-cls".

**Comment by nex3** [comment]
The `additionalData` option is part of WebPack's `sass-loader` package, and not something officially supported by Sass. I don't generally recommend using it these days; there are better ways to share code and customize libraries.

To customize `!default` variables in the module system, you can use [`@use ... with`](https://sass-lang.com/documentation/at-rules/use/#configuration). If you want to use the _same_ customization across multiple files, you can use [`@forward ... with`](https://sass-lang.com/documentation/at-rules/forward/#configuring-modules) instead. For example:

```scss
// _config.scss
// Default variable to avoid sass loader config obligation
$prefix-cls: xpto !default;
```

```scss
// _config-custom.scss
@forward "config" with ($prefix-cls: something-else);
```

```scss
// card.module.scss
@use "config-custom" as config;

.card {
  :global(.#{config.$prefix-cls}-card-cover) {
    display: flex;
    justify-content: center;
    margin-top: 20px;
  }

  // ...
}
```

If you want the value of `$prefix-cls` to differ from compilation to compilation, for example to compile the same stylesheets with different configurations, you could make it a custom function. I don't know exactly how WebPack's API handles that, but using the standalone Sass API it would look like this:

```js
import * as sass from 'sass';

const result = sass.compile('card.module.scss', {
  functions: {
    'prefix-cls()': () => sass.SassString(sbPrefixCls, {quotes: false})
  }
});
```

```scss
// _config.scss
@use 'sass:meta';
// Use a sensible when run without a custom function defined.
$prefix-cls: if(meta.function-exists('prefix-cls'), prefix-cls(), xpto);
```

```scss
// card.module.scss
@use "config";

.card {
  :global(.#{config.$prefix-cls}-card-cover) {
    display: flex;
    justify-content: center;
    margin-top: 20px;
  }

  // ...
}
```

**Comment by hugobarragon** [comment]
@nex3 
Hi, thanks, maybe I cant understand but seems to not work this way, the scenario is the folowing  
Package A -> components and design system with scss modules and uses $prefix-cls on its styles 
Package B (micro fronted)- > installs package A and wants to define $prefix-cls to avoid conflicts with other micro frontends, this $prefix-cls variable must change scss modules from package A
Package C installs package A and Package B

with the above solution, how can package B define a custom $prefix-cls and make package A use it, without centralizing all styles on one file, because of scss modules

package B does not know every scss file inside each component for package A

**Comment by nex3** [comment]
That's very abstract, so it's hard to give a concrete answer without knowing more information. Does Package C load multiple micro-frontends in a single compilation, or only Package B? Does Package A have a single entrypoint that exposes all its members, or does it have a bunch of different files that users can load? If the latter, when you're using `@import`, how do you ensure that `$prefix-cls` is defined before loading _any_ of those files?

There's probably a way to make this work using `@forward ... with`, but it requires a fairly clear understanding of what the flow of loads are. If you want a one-size-fits-all solution, the easier path may be to just use mixins instead. If you're writing a complex design system, it's not a great idea to rely on global variables and top-level styles in the first place. If you put everything in a mixin, you have full control over what variables have which values when _and_ exactly where styles get emitted. For example:

```scss
// card.module.scss
@mixin styles($prefix-cls) {
  .card {
    :global(.#{$prefix-cls}-card-cover) {
      display: flex;
      justify-content: center;
      margin-top: 20px;
    }

    // ...
  }
}
```
