### ISSUE TITLE
How to use $each to set variables

### ISSUE THREAD

**Issue by zLikeMario** [sass/sass#3786]
---  Expectation ---

```scss
@use "sass:map";

// Color
$colors: () !default;

$colors: map.deep-merge(
  (
    "primary": #409eff,
  ),
  $colors
);

@each $name, $value in $colors {
  @for $i from 1 through 3 {
    // How do I add a variable to $colors here
    map-set(
      $colors,
      "#{$name}-lighten-#{$i}",
      toShallow(map-get($colors, primary), math.percentage(math.div($i, 10))) // toShallow can lighten the color，That's not the point.
    );
  }
}
```

// Final result
```scss
$colors: (
    "primary": #409eff,
    "primary-lighten-1": #aaa,
    "primary-lighten-2": #bbb,
    "primary-lighten-3": #ccc,
)
```

**Comment by zLikeMario** [comment]
```scss
@use "sass:map";
@use "sass:math";
@use "./functions.scss" as *;

// Color
$colors: () !default;
$colors: map.deep-merge(
  (
    "primary": #409eff,
  ),
  $colors
);

@mixin extend-color($name, $color, $number) {
  $colors: map.deep-merge(
    (
      "#{$name}-lighten-#{$number}":
        toShallow($color, math.percentage(math.div($number, 10))),
      "#{$name}-darken-#{$number}":
        toDarken($color, math.percentage(math.div($number, 10))),
    ),
    $colors
  ) !global;
}

@each $name, $value in $colors {
  @for $i from 1 through 3 {
    @include extend-color($name, $value, $i);
  }
}
```
