### ISSUE TITLE
Sass break a specific border-image syntax

### ISSUE THREAD

**Issue by Afif13** [sass/sass#3797]
The below code is a valid CSS code

```css
.full-background {
  border-image: conic-gradient(pink 0 0) fill 0//0 100vw;
  padding-block: 10px;
}
```

I tested here: https://sass-lang.com/playground/#eJwNyzEOwyAMBdCdU/yxHWjMmpwGMEEWrkGoaStFvXuzPumF8NgPVZ9ibnX2wxinA1KfXKaXZ6xlRe4m2dcZWYq9bkOsgUB37KIKWhZCIHp/tmuOyCxWfdKe23r5+G7u5/4LFyDu and it gives me an error.

Adding a space between the slashes won't trigger any issue

```css
.full-background {
  border-image: conic-gradient(pink 0 0) fill 0/ /0 100vw;
  padding-block: 10px;
}
```

But it would be good to also handle the first one.

I know it's not a common syntax but I use it a lot on CSS. I wrote a [detailed article about border-image](https://www.smashingmagazine.com/2024/01/css-border-image-property/) and someone commented facing such issue with Sass
