### ISSUE TITLE
& selector in SCSS and CSS behaves differently

### ISSUE THREAD

**Issue by FlorianBabel** [sass/sass#3809]
The following code produces different results if used directly as CSS or as SCSS, that compiles to CSS.
```css
.level1 {
    .level3 {
        .level2 & {
            background: red;
        }
    }
}
``` 
---
If used as CSS it gets interpreted in the following way:
```css
.level1 .level2 .level3 {
   background: red;
}
``` 
https://codepen.io/flo02468/pen/WNWGOgO

---

If used as SCSS the resulting CSS looks like this:
```css
.level2 .level1 .level3 {
   background: red;
}
``` 
https://codepen.io/flo02468/pen/eYodRKr

---
I also attached two identical codepens that only differ in that on of them uses scss instead of css
Regardless of which case is better i think this is something to talk about.
