### ISSUE TITLE
Placeholder selector @extend bug?

### ISSUE THREAD

**Issue by ghost** [sass/sass#381]
Hi,
I'm fiddling with placeholder selectors and doing simple stuff like this:

``` scss
table{
  &%simple{
    color: blue;
    font-weight: bold;
    font-size: 2em;
  }
}

.table-mod {
  @extend %simple;
  background-color: #fff;
  }
```

And this is the css output:

``` scss
table.table-mod {
  color: blue;
  font-weight: bold;
  font-size: 2em;
}

.table-mod {
  background-color: #fff;
}
```

This seems like a bug since background-color isn't within table.table-mod.
To me this should be the logical output for that kind of extend structure:

``` scss
table.table-mod {
  color: blue;
  font-weight: bold;
  font-size: 2em;
  background-color: #fff;
}
```

I'm using;
sass (3.2.0.alpha.104)
ruby 1.9.3
win 7 x64
