### ISSUE TITLE
3.1.16 sass-convert removing the + selector sometimes.

### ISSUE THREAD

**Issue by ghost** [sass/sass#383]
I'm not sure why this is happening, but it only seems to be happening in some places.

A good file to try this on is the bootstrap CSS file. http://twitter.github.com/bootstrap/

Examples: 

``` css
.radio.inline + .radio.inline,
.checkbox.inline + .checkbox.inline {
  margin-left: 10px;
}
```

to: 

``` css
.radio.inline .radio.inline, .checkbox.inline .checkbox.inline {
  margin-left: 10px; }
```

and 

``` css
legend + .control-group {
  margin-top: 18px;
  -webkit-margin-top-collapse: separate;
}
```

to:

``` css
legend .control-group {
  margin-top: 18px;
  -webkit-margin-top-collapse: separate; }
```
