### ISSUE TITLE
Make interleaved declaration semantics CSS-compatible

### ISSUE THREAD

**Issue by nex3** [sass/sass#3846]
- [x] Proposal (https://github.com/sass/sass/pull/3848)
- [x] Update full spec (https://github.com/sass/sass/pull/3885)
- **Deprecation**
  - [x] Dart Sass (https://github.com/sass/dart-sass/pull/2267)
  - [x] Tests (https://github.com/sass/sass-spec/pull/2002)
  - [x] Website (https://github.com/sass/sass-site/pull/1101)
- **Breaking change**
  - [x] Dart Sass (https://github.com/sass/dart-sass/pull/2629)
  - [x] Tests (https://github.com/sass/sass-spec/pull/2075)
  - [x] Website (https://github.com/sass/sass-site/pull/1452)

---

https://github.com/w3c/csswg-drafts/issues/8738 changes the behavior of declarations interleaved with nested rules away from behavior that matches Sass's historic behavior (hoisting all properties to the original nested rule), and instead treats those behaviors as logically appearing after the nested rule. For example, the source:

```scss
a {
  color: red;
  @media screen {color: blue}
  color: green;
}
```

currently compiles to:

```scss
a {
  color: red;
  color: green;
}

@media screen {
  a {
    color: blue;
  }
}
```

but the CSS semantics are now equivalent to:

```scss
a {
  color: red;
}

@media screen {
  a {
    color: blue;
  }
}

a {
  color: green;
}
```

...which is meaningfully different. Reportedly, Chrome will be implementing the new semantics soon.

Although our approach to full compatibility with plain CSS nesting semantics is generally fairly cautious due to Sass's strong existing semantic grounding (see https://github.com/sass/sass/issues/3030), in this case the set of styles that will need to change is fairly narrow and a workaround is easy (wrapping the properties in `& { ... }`), so it's worth changing this behavior eagerly.
