### ISSUE TITLE
add class to all top-level selectors in a block

### ISSUE THREAD

**Issue by milahu** [sass/sass#3871]
i want to mix multiple css frameworks, and avoid collision of selectors

input

```css
.some-class div { margin: 1; }
some-elem > ul { margin: 2; }
```

expected output

```css
.some-class.extra-class div { margin: 1; }
some-elem.extra-class > ul { margin: 2; }
```

input with parent selector

```css
.extra-class {
  /* Error: "&" may only used at the beginning of a compound selector. */
  .some-class& div { margin: 1; }
  some-elem& > ul { margin: 2; }
}
```

input with "reverse parent selector"

```css
/* Error: Top-level selectors may not contain the parent selector "&". */
&.extra-class {
  .some-class div { margin: 1; }
  some-elem > ul { margin: 2; }
}
```

i also tried [Add class to the most outer selector using Sass mixin](https://pantaley.com/blog/Add-class-to-the-most-outer-selector-using-Sass-mixin/)

```css
@mixin most-outer-selector($new-class) {
  $current-selector: &;
  $new-selector: [];

  @each $item in $current-selector {
    $first-item: nth($item, 1);

    $appended-item: $first-item + $new-class;

    $new-item: set-nth($item, 1, $appended-item);
    $new-selector: append($new-item, $new-selector);
  }

  @at-root #{$new-selector} {
    @content;
  }
}

* {
  @include most-outer-selector('.extra-class') { }
  .some-class div { margin: 1; }
  some-elem > ul { margin: 2; }
}
```

but that throws

```
Error: Expected identifier.
  │   @at-root #{$new-selector} {
  │              ^^^^^^^^^^^^^ 
  ╵
  ╷
  │ .parent.bold .child span [] 
  │                           ━ error in interpolated output
  ╵
```

similar question: [Sass: applying a shared class to every selector in a content block](https://stackoverflow.com/questions/65866282/sass-applying-a-shared-class-to-every-selector-in-a-content-block)

alternative?
add a prefix to all class selectors ([postcss-prefixer](https://www.npmjs.com/package/postcss-prefixer)) ([rework-class-prefix](https://github.com/johno/rework-class-prefix))
add an extra class to all element selectors ([postcss-prefixer#48](https://github.com/marceloucker/postcss-prefixer/issues/48))

```css
.customprefix-some-class div { margin: 1; }
some-elem.customprefix > ul { margin: 2; }
```

different than #1459
