### ISSUE TITLE
Recursively processing nested maps using @content fails silently after one level deep.

### ISSUE THREAD

**Issue by bnjmnrsh** [sass/sass#3890]
Hi all, 

I am attempting to recursively process a nested map of colors using [content blocks](https://sass-lang.com/documentation/at-rules/mixin/#content-blocks), and I believe I've run into a limitation. Perhaps it has to do with the lexical scoping of the values within the recursion?  

`"sass": "^1.77.4"`

TLDR  The first level works as expected, but the inner maps, while they will `@debug` the expected values from within the mixin, from the place of the `@include` any nested values are skipped.   

The nested map:
```scss
$colors: (
   // This doesn't work
  burnt-sienna: (
    "900": #7a1a14,
    "950": #420908,
  ),
   // This does
  "brand-1": #a854c0, 
  "brand-2": #fef48a,
) !default;
```

The mix-in:
```scss
@mixin compound-classes(
  $map,
  $prefix: "",
  ){
    @each $key, $value in $map {
      @if type-of($value) == 'map' {
        $key: $prefix + $key;
          @include compound-classes($value, $key);
      } @else {
          @debug "ELSE #{$prefix}#{$key} value: #{$value} ";
          @content ($key, $value, $prefix);
        }
    }
}
```

_I am using my own custom function `ends-with()` but this isn't effecting the behaviour of `@content`._

The usage:
```scss
/*
  Border colors
*/
@include compound-classes($colors, "b--") using
  ($key, $value, $prefix) {
    @debug "border-colors: #{$key} #{$value} #{$prefix}";
  .#{$prefix}#{$key} {
    border-color: var(--#{$key}, #{$value});
  }
}
```

The debug output  (nested maps are logged from within the mixin, but not the `@include`) 
```bash
scss/generators/_classes.scss:133 Debug: MAP ELSE b--burnt-sienna900 value: #7a1a14 
scss/generators/_classes.scss:133 Debug: MAP ELSE b--burnt-sienna950 value: #420908 
scss/generators/_classes.scss:133 Debug: MAP ELSE b--brand-1 value: #a854c0 
scss/modules/_border-colors.scss:25 Debug: INCLUDE: brand-1 #a854c0 b--
scss/generators/_classes.scss:133 Debug: MAP ELSE b--brand-2 value: #fef48a 
scss/modules/_border-colors.scss:25 Debug: INCLUDE: brand-2 #fef48a b--
```

Rendered CSS (nested map elements are omitted)
```css
.b--brand-1 {
  border-color: var(--brand-1, #a854c0);
}

.b--brand-2 {
  border-color: var(--brand-2, #fef48a);
}
```

I could explicitly handle nested maps `n` deep, but while it feels pretty fragile, it is perhaps manageable in my use case. Is this a bug, or is there a better approach?

I really appreciate any help you can provide.
