### ISSUE TITLE
In SCSS, is it possible to make a variable value that response to the responsive design?

### ISSUE THREAD

**Issue by hansyulian** [sass/sass#3891]
So i have the following styling code:

```

@mixin smaller-than($breakpoint) {
  @media (max-width: $breakpoint) {
    @content;
  }
}

@mixin larger-than($breakpoint) {
  @media (min-width: $breakpoint) {
    @content;
  }
}

.header{
   height: 60px;
   @include larger-than($breakpoint-md){
       height: 80px;
   }
   @include larger-than($breakpoint-xl){
       height: 120px;
   }
}
.content{
   height: calc(100vh - 60px);
   @include larger-than($breakpoint-md){
       height: calc(100vh - 80px);
   }
   @include larger-than($breakpoint-xl){
       height: calc(100vh - 120px);
   }
}
.spacer {
   padding-top: 60px;
   @include larger-than($breakpoint-md){
       padding-top: 80px;
   }
   @include larger-than($breakpoint-xl){
       padding-top: 120px;
   }
}
```

is there a way in SCSS so that i can achieve it with some minimal code and guaranteed sync between the value? maybe i am thinking on something like this:

```
function header-height(){
   return 60px;
   @include larger-than($breakpoint-md){
       return 80px;
   }
   @include larger-than($breakpoint-xl){
       return 120px;
   }
    
}

.header {
   height: header-height();
}
.content {
   height: calc(100vh - header-height());
}
.spacer {
   padding-top: header-height();
}
```

**Comment by Goodwine** [comment]
Sass variables are pre-processed values defined in your Sass code. These values are resolved during the Sass compilation stage, which happens before the CSS is sent to the browser.  Since media queries are evaluated by the browser at runtime, based on the user's screen size, Sass variables cannot inherently be "responsive design"-aware.

While Sass variables themselves can't be directly responsive, you can achieve what you want by using [CSS custom properties](https://sass-lang.com/documentation/style-rules/declarations/#custom-properties) (sometimes called CSS variables). 

For example:

```scss
:root {
   --header-height: 60px;
   @include larger-than($breakpoint-md){
       --header-height: 80px;
   }
   @include larger-than($breakpoint-xl){
       --header-height: 120px;
   }
}

.header {
   height: var(--header-height);
}
.content {
   height: calc(100vh - var(--header-height));
}
.spacer {
   padding-top: var(--header-height);
}
```
Keep in mind that CSS custom properties aren't supported in some very old browsers, and their values are determined at runtime on the browser, not during the initial code compilation. This might be a consideration depending on your target audience and performance requirements.
