### ISSUE TITLE
[Feature Request] Allow use of GTK named colors

### ISSUE THREAD

**Issue by Mikilio** [sass/sass#3896]
Gtk color themes are defined in a CSS like this: 
```css
 @define-color accent_color #89b4fa;
 @define-color accent_bg_color #89b4fa;
 @define-color accent_fg_color #1e1e2e;
 ...
```

And then I should be able to use them like:
```css
 .foo {
  background-color: @accent_color
}
```

But SASS does not want to compile these.

Is it maybe possible already? I'm by no means a styling expert.
