### ISSUE TITLE
sass :except() selector

### ISSUE THREAD

**Issue by mikesmullin** [sass/sass#392]
i should be able to do something like

``` sass
ul
  li:except(.first, .last)
    background: blue
```

and what the :except() selector should do is generate css that resets any attributes set within there like:

``` css
ul li { background: blue; }
ul li.first, ul li.last { background: transparent; }
```

so basically it acts similar to a reset-box-model() or a generic compass reset style--but only for the attributes that were set. or it could use attributes like INHERIT instead of resetting completely. just enough to override the previous style. 

i know this could be accomplished other ways, but i thought it might be useful and wanted to throw it out there.
