### ISSUE TITLE
Issue with Mixed Declarations deprecation

### ISSUE THREAD

**Issue by jeramyadadapted** [sass/sass#3956]
I've run across what appears to be an issue related to [this](https://sass-lang.com/documentation/breaking-changes/mixed-decls/) deprecation.

Sass Version: `1.79.4`

Here is an example of the SCSS that has the problem:
```
.my-class-1,
.my-class-2 .some-other-class {
    @include themify($themes) {
        background-color: themed("myBackgroundColor");
    }

    flex: 0 0 auto;
    justify-content: center;
    align-items: center;
    height: 65px;
}
```

The above SCSS throws the following warning:
```
Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Warning on line XXXXXXXX
Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls
```

As the message states, if I move it around to look like the following, the warning goes away:
```
.my-class-1,
.my-class-2 .some-other-class {
    flex: 0 0 auto;
    justify-content: center;
    align-items: center;
    height: 65px;

    @include themify($themes) {
        background-color: themed("myBackgroundColor");
    }
}
```

However, if I apply the original SCSS to both `.my-class-1` and `.my-class-2 .some-other-class` separately, I get no warning and it all works just fine:
```
.my-class-1 {
    @include themify($themes) {
        background-color: themed("myBackgroundColor");
    }
    
    flex: 0 0 auto;
    justify-content: center;
    align-items: center;
    height: 65px;
}

.my-class-2 .some-other-class {
    @include themify($themes) {
        background-color: themed("myBackgroundColor");
    }

    flex: 0 0 auto;
    justify-content: center;
    align-items: center;
    height: 65px;
}
```

I then tried removing `.some-other-class` from the `.my-class-2 .some-other-class` line to see if it would still throw the warning simply pointing to two top-level classes and it works without throwing the warning:
```
.my-class-1,
.my-class-2 {
    @include themify($themes) {
        background-color: themed("myBackgroundColor");
    }

    flex: 0 0 auto;
    justify-content: center;
    align-items: center;
    height: 65px;
}
```

Based on these results, it seems that CSS Combinators will trigger this warning when used as part of a styling group. I verified the same occurs when using other types of CSS Combinators:

- general sibling selector(~)
- adjacent sibling selector(+)
- child selector(>)
- descendant selector(space)

**Comment by nex3** [comment]
I can't easily reproduce this because I don't have access to your `themify()` mixin. Can you provide a reproduction that works in [the Sass playground](https://sass-lang.com/playground/)?

**Comment by jeramyadadapted** [comment]
@nex3 sorry, I should have included it in the original post. [Here it is.](https://sass-lang.com/playground/#eJzdVFGPmkAQfudXTD3TihE9TdoHeDG9XtJLkzM5Te4ZYUEqLBdYGs2F/97Z3RGhwOXaRB+6JsDOzDcz37ezzudDsWMJsxL3xQZexLFjGMug4J6IUg7K54+Ge3Y04dUAXMuMiSLjgAArZGJ0xk9AxTlGiSmS6BBpfBQcKSi3gT6qZMz1dmREOCYBRFEQxcg11UVuXrWrhI81p1x1FiMTPoRxunWRSz2GimGPWCovtqdq8t3MpjL+cuOC2RXPJt98QiXNCQywLUxaDkynnaXWl8yQsCxko1ZYM3TS6e9GKSRWt6nhbqzZsvZohEdX3y69lAvGhdMrthyZdqrS0E9MN5uBl8ZpBj4LIh7JscqNoTLNbbi5VcshywItgVqOQmqtjWp8tAa+m+0tZbJrqiTHr663D7O04P6dTIaS6DJaE1O/4ijcib9ALyq0KXsaw7hvwXgm/ZvvD2tY399tHlaP8G11v378tIHn1dMP8r+JnyZHy4vdPLew6/NmAdM8RclT7DvTttMNirgXFz7786qZtZHeVswsT1Ojez1osT7NMM1BELODDbf4cwuRatfPIhdYyKLRsMHDJ8u000V5uRUJluRNx45J3W348vnloP4hOpXoklBKt+7VTjlm0NCtse+WDkO6+JG5lyL5O1mSr0n0ZH3rmCjkH06KkKX8uKSk5yYvzEM+r3Y2JNq7h+XC3K/N+2r3778U8Df8yXb8)

**Comment by nex3** [comment]
@jeramyadadapted That's because in

```scss
.my-class-1,
.my-class-2 .some-other-class {
    @include themify($themes) {
        background-color: themed("myBackgroundColor");
    }

    flex: 0 0 auto;
    justify-content: center;
    align-items: center;
    height: 65px;
}
```

the specificity of the selectors generated by the `themify()` mixin overlap with the specificity of the selector for the interleaved declarations. It currently generates this CSS:

```css
.my-class-1,
.my-class-2 .some-other-class {
  flex: 0 0 auto;
  justify-content: center;
  align-items: center;
  height: 65px;
}
.theme-dark-theme .my-class-1,
.theme-dark-theme .my-class-2 .some-other-class {
  background-color: #000000;
}
.theme-light-theme .my-class-1,
.theme-light-theme .my-class-2 .some-other-class {
  background-color: #ffffff;
}
```

The selector `.my-class-2 .some-other-class` has the same specificity as `.theme-dark-theme .my-class-1`. If you had an element that matched both of those, and the properties you were setting conflicted with one another, the behavior would change when the emitted CSS changed to:

```css
.theme-dark-theme .my-class-1,
.theme-dark-theme .my-class-2 .some-other-class {
  background-color: #000000;
}
.theme-light-theme .my-class-1,
.theme-light-theme .my-class-2 .some-other-class {
  background-color: #ffffff;
}
.my-class-1,
.my-class-2 .some-other-class {
  flex: 0 0 auto;
  justify-content: center;
  align-items: center;
  height: 65px;
}
```

On the other hand, when you split the one style rule up into two, the style rule for `.my-class-2 .some-other-class` always comes after `.theme-dark-theme .my-class-1`, so this isn't an issue.
