### ISSUE TITLE
Compile sass with additionnal data to override variables

### ISSUE THREAD

**Issue by hedocode** [sass/sass#3968]
Hi, I used to `compile` sass files and override some variables by providing some data like `$main-color: red` as so :

```
sass.compile({
    file: filename,
    data: data,
    outputStyle: "compressed"
})
```

I don't see the data option in the docs anymore, how can I achieve it now ?

**Comment by nex3** [comment]
Can you provide a more thorough example? I'm confused about a few things here:

* `sass.compile()` is the modern API, but you're passing arguments as though you're invoking the legacy API.
* Passing both `file` and `data` to the legacy API doesn't allow you to "override variables", it just evaluates the `data` and uses `file` as the URL of the stylesheet.

**Comment by hedocode** [comment]
I'm confused too, I just bumped from 1.62.1 to 1.80.3, so I did migrate.

I do now use the modern API to decorate a fastify server like so :

```js
const sass = require("sass");
const fastifyPlugin = require("fastify-plugin");

async function scssConnector(fastify, options) {
    const optionnalDecorators = ["send"];
    fastify.decorateReply(
        "sass",
        function (filename, data) {
            this.header("Content-Type", "application/json; charset=utf-8");
            
            const res = JSON.stringify(
                sass.compile(
                    filename,
                    {
                        data,
                        style: "compressed" // "expanded" | "compressed" | "nested" | "compact"
                    }
                )
            );

            this.send(res);
        },
        optionnalDecorators
    );
}
module.exports = fastifyPlugin(scssConnector);
```

but the `data` option that used to evaluates the string passed as argument does not seems available anymore does it ?

I did not find it in the [Options<sync> docs](https://sass-lang.com/documentation/js-api/interfaces/options/)

**Comment by nex3** [comment]
If you want to compile a Sass string to CSS in the modern API, you need to use [`compileString()`](https://sass-lang.com/documentation/js-api/functions/compilestring/). See [the usage docs](https://sass-lang.com/documentation/js-api/#md:usage) for more detail.

**Comment by hedocode** [comment]
If I can be more precise, I used the `data` parameter to override the `!default;` variables present in the given file. The evaluated string was containing the override values.

Example : 

- I have the following button.scss file :
```scss
$primary-color: black !default;
$secondary-color: white !default;
$button-height: 48px !default;

button,
.button {
    padding: 0px 12px;
    height: $button-height;
    font-family: 'Comfortaa', cursive;
    font-weight: bold;

    background-color: $primary-color;
    color: $primary-color;
}
```

- I used to be able to compile the file with custom varaibles values like so : 
```js
sass.compile({ // Or render, idk
    file: "C://path/to/buttons.scss",
    data: "$primary-color: white; $secondary-color: black; $button-height: 32px;",
    outputStyle: "compressed"
})
```

If I understand, I now have to grab files content, prepend them with the previous `data` string, and then pass the whole thing to `compileString()` ?

I currently feel like I have lost a functionnality on the function meant to `compile` files, with the withdrawal of the `data` option.

**Comment by nex3** [comment]
That's not how `render()` ever worked. To verify, you can run this code:

```scss
const fs = require('node:fs');
const sass = require('sass');

fs.writeFileSync('example.scss', '@error "This will never be executed";');
sass.renderSync({file: 'example.scss', data: '@debug "This will be executed";'});
```

This prints:

```
Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

More info: https://sass-lang.com/d/legacy-js-api

example.scss:1 Debug: This will be executed
```

which means it did _not_ evaluate the contents of `example.scss`. Note that this matches the behavior of Node Sass.
