### ISSUE TITLE
compileString on browser with @use './src/index.scss'

### ISSUE THREAD

**Issue by aamirtestable** [sass/sass#3986]
I am playing around with compileString and thought to give a playground / storybook type thing to other developers what kind of changes i'm making. I have created an html page with vite and started building a theme for the company. 

Now in the playground, scss is working fine, just that i'm not sure how to import an scss file. which have  something like 

```scss
// /src/index.scss
@forward 'components/crm-badge';` // this have a mixin of `badge`
```

And the tools scss will be like this

```scss
@use `./src/index` as UI;

.contact_logo{
   @include UI.logo
   & > .badge {
      @include UI.badge
   }
}
```

So far my app and scss integrations all are working fine, just have an itch to do that in web browser 😸 
Can I load scss over the server and its all `forwards`? 

---- edit

Ahh one more thing, i just realized and this can be an overkill but might be good.  Taking the same example from top. I have created 3 panels. one is visual output how the badge would look, and on right side top editor where that code snippet will be, and in the right side bottom part compiled css. 

I believe that compiled css would include everything like my other components like charts and reports. 

So may be only show following in compiled one

```css
.contact_logo{
   background-color: #ddd;
   border-radius: 4px;
}

.contact_logo > .badge{
   border-radius: 4px;
   position: absolute;
   right: -5px;
   top: -5px;
   ...
}
```

In short just to show what only this component output will be instead of whole css file.
