### ISSUE TITLE
Ordering of `:dir` psuedo applied to psuedo elements

### ISSUE THREAD

**Issue by mrginglymus** [sass/sass#3993]
Given

```scss
.test::before {
  color: red;
  
  &:dir(rtl) {
    color: blue;
  }
}
```

What you get is

```css
.test::before {
  color: red;
}

.test::before:dir(rtl) {
  color: blue;
}
```

However, the `:dir()` psuedo doesn't appear to work on the `::before` pseudo 

What I need is

```css
.test::before {
  color: red;
}

.test:dir(rtl)::before {
  color: blue;
}
```

I can achieve this with

```scss
.test::before {
  color: red;
  
  @at-root #{selector.unify(&, ':dir(rtl)')} {
    color: blue;
  }
}
```

which feels a bit clunky.

Am I missing something, or is this the recommended way to achieve this behaviour?
