### ISSUE TITLE
[Feature] Add an @inject directive which is essentially the inverse of @extend

### ISSUE THREAD

**Issue by ggedde** [sass/sass#3996]
This was suggested before, but my request is different.
Also let me know if this is currently capable now?  I just could not find any solution or mention of this.

With multiple files, I would like each file to be able to `@inject` styles into a selector.
If the selector does not exist then it gets added. 
If the selector does exist then the styles get added to the existing selector.

# Example A:

### main.scss
```scss
@use 'spacing';
@use 'colors';
```

#### _spacing.scss
```scss
@inject :root {
  --padding: 1em;
  --margin: 2em;
}
```

#### _colors.scss
```scss
@inject :root {
  --error: #f00;
  --success: #0f0;
}
```

The Output should be:
```scss
:root {
  --padding: 1em;
  --margin: 2em;
  --error: #f00;
  --success: #0f0;
}
```

This would be incredibly useful when creating frameworks or other toolkits. This would allow a developer to comment out a non-needed component in main.scss and get the expected result.

---
Without this option you have to resort to having various mixins in multiple files that would break if someone commented the file out or duplicated selectors which leads to larger bundle size. 
Example: 
```scss
:root {
  --padding: 1em;
  --margin: 2em;
  }
  
:root {
  --error: #f00;
  --success: #0f0;
}
```

# Example B

Another way this can be useful is to allow developers to work on snippets almost like plugins that would work for existing components.

### main.scss
```scss
@use 'buttons';
@use 'new-buttons';
```

#### _buttons.scss
```scss
.button,
button {
  padding: .5em 1em;
  font-size: 1.2em;
}

nav ul li :is(.button, button) {
  padding: .25em;
  font-size: 0.8em;
}
```

#### new-buttons.scss
```scss
@inject .button {
  padding: .75em 1.5em;
  border-radius: .25em;
}
```

The Output  should be:
```scss
.button,
button {
  padding: .75em 1.5em; // Overrides existing style
  font-size: 1.2em;
  border-radius: .25em; // Gets added
}
nav ul li :is(.button, button) {
  padding: .25em;
  font-size: 0.8em;
}
```
---
It should also allow matching the selector exactly incase you do only want to match a specific selector.
Example: 
```scss
@inject nav ul li :is(.button, button) {
  padding: .75em 1.5em;
  border-radius: .25em;
}
```

The Output  should be:
```scss
.button,
button {
  padding: .5em 1em;
  font-size: 1.2em;
}
nav ul li :is(.button, button) {
  padding: .75em 1.5em;
  font-size: 0.8em;
  border-radius: .25em;
}
```
