### ISSUE TITLE
Need more math and number support in SASS

### ISSUE THREAD

**Issue by heygrady** [sass/sass#4]
In order to target IE-specific fixes with handy mixins, it is necessary to do some simple math that is not supported currently in SASS. For my purposes I've recently needed to do the following things:
- remove units (I think I can just divide the units away: 200px/1px = 200)
- remove the beginning hash from a color (#ffffff -> ffffff)
- use sine, cosine, tangent functions for calculating angles
- get a hex number from a decimal number

``` scss
      @mixin ie-text-shadow($x, $y, $radius:1px, $color: #000000) {
          // TODO: use sine/cosine to get the angle from the x and y
          //$angle: arctan($x/$y);
          $filter: Shadow(Color=#{$color}, Direction=#{$angle}, Strength=#{$radius/1px});
          .ielt8 & {
              filter: $filter;
          }
          .ie8 & {
              -ms-filter: quote($filter);
          }
      }
      @mixin ie-background-rgba($color: #ffffff, $alpha:1) {
          // TODO: convert the $alpha into a hex
          //$color: ($color) + hex($alpha);
          $filter: progid:DXImageTransform.Microsoft.gradient(startColorStr='#{$color}',EndColorStr='#{$color}');
          .ielt8 & {
              background: none;
              filter: $filter;
          }
          .ie8 & {
              background: none;
              -ms-filter: quote($filter);
          }
      }
```
