### ISSUE TITLE
Edit in place directive proposal

### ISSUE THREAD

**Issue by lvf23** [sass/sass#4026]
What if Sass had an `@edit` directive to replace the style in the place of original class? Imagine a scenario where you have multiple scss files (could be framework scss files and your defined scss files) that will compile into one for the entire project (style.css). Consider the example:

framework.scss
```scss

.framework-defined-class{
   line-height: 1.5em;
   font-size: 21px;
}

```

Currently, when you need to modify it, you just would modify the rule in the framework .scss file or create another class to modify the behaviour of first class. Right?

The main problem of first approach is modify losing the original style of framework in its file and the second approach creates redundancy of selectors increasing css file size.

What if you had a directive like this:

app.scss

```scss
@import 'framework' // @edit needs to be aware that the edited selector exists or be used with !optional

@edit(.framework-defined-class, 2) {
   font-size: 24px;
} !optional;

@edit(.framework-defined-class) { // priority is optional, default priority would be 1.
   font-size: 19px;
};

```

Edit directive would take as first argument the selector you want to edit and the second one could be the priority that would solve when two edit directives "collide" would prevail that one with high priority with default priority set to 1. That would render:

style.css
```css
.framework-defined-class{
  line-height: 1.5em;
  font-size: 24px;
}
````

As you can see, the other css properties that weren't edited, they were left untouched. And when if you comment out the `@edit` rule that would back to original css style of original class or selector. Would that be too complicated to implement it? Could this have any adverse effect?

---
Edit: I found a similar issue, #3996, somehow is related. I would like to implement it for a test after I get in deep in 
Sass code but before it I would like to read different opinions to reach a consensus. Wouldn't be logic to implement something would be useful for me and not for someone else in this project.
