### ISSUE TITLE
CSS nesting selectors are broken in nested contexts

### ISSUE THREAD

**Issue by nex3** [sass/sass#4055]
There's an edge-case in Sass right now that doesn't work how it should per CSS semantics. If you write:

```css
/* other.css */
& {color: red}
```

```scss
@use 'sass:meta';

div {
  @include meta.load-css('other');
}
```

Logically, this should be resolved to

```css
div {
  & {color: red}
}
```

which should either produce that exact result or the result of resolving the nesting, which is to say

```css
div {
  color: red;
}
```

However, it currently produces

```css
div & {
  color: red;
}
```

which is clearly incorrect, as it can never match any elements.

Either leaving the plain-CSS nesting as-is or resolving it using `:is()` semantics would be reasonable here, but the current behavior is clearly wrong.
