### ISSUE TITLE
Support for ::slotted(...) and :host(...) with nested selectors

### ISSUE THREAD

**Issue by Sleeckx** [sass/sass#4092]
I'd like to ask for a reconsideration of the current handling of nesting inside `::slotted()` and `:host()` selectors.

The explanation 4 years ago (#3099), that the parent selector `(&)` uses simple concatenation, made sense at the time. But I believe in 2025, developers now expect tools like Sass to support these selectors properly.

Currently, Sass produces _invalid_ CSS when nesting inside these selectors. For example:

```scss
:host {
  display: flex;

  &[vertical] {
    flex-direction: column;
  }
}
```

Compiles to:

```scss
:host[vertical] {
  flex-direction: column;
}
```

And similarly:

```scss
::slotted(input) {
  color: blue;
  &:invalid {
    color: red;
  }
  &.hidden {
    display: none;
  }
}
```

Compiles to:

```scss
::slotted(input) {
  color: blue;
}
::slotted(input):invalid {
  color: red;
}
::slotted(input).hidden {
  display: none;
}
```

I understand the original decision, but from my perspective, I don't think these are complex cases anymore. They are part of everyday frontend development. When I try to use nesting in `::slotted()` or `:host()`, and Sass outputs invalid or broken CSS, it feels like the tooling hasn’t kept up with the evolution of the platform.

Can this please be reconsidered as a missing feature rather than a deliberate design constraint? Proper support for nesting in `::slotted()` and `:host()` would bring Sass back in line with the needs of today's developers.
