### ISSUE TITLE
Style collection

### ISSUE THREAD

**Issue by scottkellum** [sass/sass#413]
Style collection and depositing. This enables users to write styles in a fashion similar to media bubbling but allows for consolidation of those media directives. Consolidation is explicit, not arbitrary, so the cascade can be preserved.
### SCSS

``` scss
.foo {
  color: #333;
  width: 100%;
  @collect breakpoint {
    width: 50%;
    float: left;
  }
}

.bar {
  width: 100%;
  @collect breakpoint {
    width: 25%;
    float: left;
  }
}

@media (min-width: 600px) {
  @deposit breakpoint
}
```
### CSS

``` css
.foo {
  color: #333;
  width: 100%;
}

.bar {
  width: 100%;
}

@media (min-width: 600px) {
  .foo {
    width: 50%;
    float: left;
  }
  .bar {
    width: 25%;
    float: left;
  }
}
```

**Comment by blackfalcon** [comment]
+1

**Comment by codingdesigner** [comment]
It seems confusing to use the $breakpoint variable in two ways.

**Comment by scottkellum** [comment]
@canarymason your right. and that isn’t really the feature I want to isolate. Updated.

**Comment by codingdesigner** [comment]
Your example is straightforward, but I'm trying to think of other uses. Since we already have media bubbling this might get used inside a bubble

```
.baz {
  @media (min-width: 600px) {
    @deposit breakpoint
  }
}
```

or perhaps multiple deposits, maybe with a @collect between them: 

```
@media (min-width: 600px) {
  @deposit breakpoint
}

.bax {
  width: 100%
  @collect breakpoint {
    color: green;
  }
}

@media (min-width: 600px) {
  @deposit breakpoint
}
```

I'm not sure how these should or could compile, but this is a cool feature worth exploring.

**Comment by scottkellum** [comment]
Collect and deposit could be used in places other than media directives as well. You could potentially recursively build then deposit styles like mixins on steroids because they absorb context and can grow.

``` scss
$background-color: #f00

@for $i from 1 through 3 {
  @collect list {
    li {
      background-color: $background-color;
      @deposit list;
    }
  }
  $background-color: lighten($background-color, 20%);
}
```

behavior of multiple deposits is tricky. Does it clear the collection or does it retain and build on previous content. Seems like there are many more opportunities if it retains and builds on itself.

Maybe we can just allow appending of mixins:

### SCSS

``` scss
.foo {
  color: #333;
  width: 100%;
}
@mixin breakpoint {
  .foo {
    width: 50%;
    float: left;
  }
}

.bar {
  width: 100%;
}
@append-mixin breakpoint {
  .bar {
    width: 25%;
    float: left;
  }
}

@media (min-width: 600px) {
  @include breakpoint
}
```

### CSS

``` css
.foo {
  color: #333;
  width: 100%;
}

.bar {
  width: 100%;
}

@media (min-width: 600px) {
  .foo {
    width: 50%;
    float: left;
  }
  .bar {
    width: 25%;
    float: left;
  }
}
```
