### ISSUE TITLE
nested media queries using interpolated variables not compiling

### ISSUE THREAD

**Issue by codingdesigner** [sass/sass#414]
Using Sass 3.2.0.alpha.244, when I nest media queries expecting them to self-assemble and I use an interpolated variable in the second query the query doesn't compile. 

Examples:

``` scss
$media: screen;
$test: "(max-width: 300px)";
.foo {
  @media #{$media} {
    @media #{$test} {
      margin: 1px;
    }
  }
}

.bar {
  @media screen {
    @media #{$test} {
      margin: 1px;
    }
  }
}
```

Neither of these compile at all. 

However using feature and value variables in the nested query works as expected. 

``` scss
$media: screen;
$feature: 'max-width';
$value: 500px;
.baz {
  @media #{$media} {
    @media ($feature : $value) {
      margin: 1px;
    }
  }
}
```

Compiles to:

``` css
@media screen and (max-width: 500px) {
  .baz {
    margin: 1px;
  }
}
```
