### ISSUE TITLE
Cannot redeclare value of global variable inside a @mixin

### ISSUE THREAD

**Issue by ngse** [sass/sass#418]
You cannot redeclare the value of a global variable inside a @mixin.

Example:

``` scss
$global: blue;

@mixin box {
  $global: red;
  color: $global; 
}

p { @include box() }
```

Expected:

``` css
p { color: red }
```

Actual:

``` css
p { blue: red; color: blue; }
```

Instead of reassigning red to the `$global` variable, it echos the value of the variable.
