### ISSUE TITLE
Script in media expressions should convert without #{}

### ISSUE THREAD

**Issue by nex3** [sass/sass#419]
``` sass
$foo: foo
@media foo and ($bar: baz)
  a: b
```

currently converts to

``` scss
$foo: foo;

@media foo and (#{$bar}: #{baz}) {
  a: b;
}
```

Instead, it should convert to

``` scss
$foo: foo;

@media foo and ($bar: baz) {
  a: b;
}
```

The reverse also converts incorrectly.
