### ISSUE TITLE
New Output Style

### ISSUE THREAD

**Issue by Goram** [sass/sass#425]
Hi,

we use 

``` css
#navbar
{
    width: 80%;
    height: 23px;
}
```

(4 Spaces in front of the attributes, dont know how to display that here correctly :))

as style in our css files, its common in php and other languages. Maybe u can consider to add it or maybe deliver a short explanation how to change the existing styles?

in thanks :)

Marc
