### ISSUE TITLE
Allow interpolation in at-rule names

### ISSUE THREAD

**Issue by dustinwilson** [sass/sass#429]
- [x] [Proposal](https://github.com/sass/language/blob/master/accepted/at-rule-interpolation.md)
- [x] [Specs](https://github.com/sass/sass-spec/pull/1298)
- [x] [Documentation](https://github.com/sass/sass-site/issues/249)
- [x] [Dart Sass](https://github.com/sass/dart-sass/issues/496)
- [ ] [LibSass](https://github.com/sass/libsass/issues/2721)

---

I'm unsure if this is an intended limitation, but I've been unable to find any documentation about it. So, here goes. I'm writing SASS, and I'm using SCSS in TextMate. I've set it to save a css file in the same location as the scss file as I save. Pretty simple. Since `@viewport` is a feature that's still in working draft but has two prefixed implementations I decided to use a mixin and a `@each` control structure to output them into a css file for easy editing later on. I've run into problems.

``` scss
@mixin viewport {
 @each $prefix in -moz-, -ms-, -o-, -webkit-, '' {
  @#{$prefix}viewport {
   width:device-width;
   zoom:1;
  }
 } 
}

@include viewport;
```

What I wrote seems to generate CSS just fine as long as what's being generated isn't an at-rule.

**Comment by nex3** [comment]
Interpolation within arbitrary directives is not currently supported, but it should be.

Changed the title to "Allow interpolation within unknown directives."

**Comment by joshuabowers** [comment]
+1

**Comment by Snugug** [comment]
At tonight's Sass meetup, it was brought up that interpolation for @directive for keyframe animations is still broken. For instance, if you wanted to write the following:

``` scss
@mixin pulse {
  0% { opacity: 0;}
  15% { opacity: .5;}
  100% { opacity: 1;}
}


@mixin keyframe($name){
  $prefixes: 'webkit' 'moz' 'ms';
  $selector: '@-';

  @each $prefix in $prefixes {
    @-#{$prefix}-keyframe #{$name} {
      @include pulse;
    }
  }
}

@include keyframe('pulse');
```

Sass errors out at the `@-#{$prefix)-keyframe #(name)` line with the following error:

``` bash
error sass/screen.scss (Line 19: Invalid CSS after "    @": expected identifier, was "-#{$prefix}-key...")
```

Having this feature pushed in Sass would make dynamic keyframes a reality, which has been an issue since [issue 46](https://github.com/nex3/sass/issues/46)

Also… +1

**Comment by chriseppstein** [comment]
It seems to work for me:

``` scss
@foo #{1 + 1} { color: red; }
```

becomes:

``` css
@foo 2 {
  color: red; }
```

**Comment by samuelvogel** [comment]
Yes, but 

``` scss
@#{1 + 1}foo { color: red; }
```

stays

``` scss
@#{1 + 1}foo { color: red; }
```

which is the problem @dustinwilson reported and @Snugug confirmed.

**Comment by chriseppstein** [comment]
What is the use case for dynamically constructing a directive name?

**Comment by samuelvogel** [comment]
As @dustinwilson mentioned for dynamic `@keyframes` or `@viewport` definitions with browser prefixes.

**Comment by tianhe** [comment]
We are on SASS.  The interpolation method for keyframe previously worked on 3.1.20, but after the 3.2.0 update it no longer worked.

**Comment by ShaneHudson** [comment]
Has there been any progress here? I attempted to write near identical code to the op and was surprised that it errors. Has anything changed in 7 months that I haven't found?

**Comment by nex3** [comment]
No; if this were fixed, the issue would be closed.

**Comment by benwtks** [comment]
This is quite a major issue, here's my experience with it:

Code: http://gyazo.com/31d7f5bca6677897c51360a06c5505e8
Error: http://gyazo.com/5ef81947cbc1e9156b146aa78f44cfd9

**Comment by chriseppstein** [comment]
As @nex3 noted, this issue is still open.

**Comment by gespinha** [comment]
@chriseppstein Are you planning a solution for this? If so, when can we expect that update?

**Comment by chriseppstein** [comment]
@Gespinha what I see here looks fine for the most part as long as the `@` is not being interpolated.

**Comment by gespinha** [comment]
@chriseppstein The code doesn't work.

``` css
@mixin viewport
  @each $prefix in '', '-moz-', '-webkit-'
    @#{$prefix}viewport
      width: device-width
      zoom: 1

@include viewport
```

generates this:

``` css
@#{$prefix}viewport {
  width: device-width;
  zoom: 1;
}
@#{$prefix}viewport {
  width: device-width;
  zoom: 1;
}
@#{$prefix}viewport {
  width: device-width;
  zoom: 1;
}
```

So the problem is still there. SASS should be able to interpolate @ directives. This would simplify interpolation and dynamic directives generation over a whole project, thus making development much easier and intuitive.

**Comment by lolmaus** [comment]
...and also future-friendly.

**Comment by gespinha** [comment]
@lolmaus indeed!

**Comment by chriseppstein** [comment]
@Gespinha Right, I was saying that it should work, that's why this issue is still open.

**Comment by gespinha** [comment]
@chriseppstein Is this something complicated (long development) to resolve? Because it is a really annoying obstacle ;)

**Comment by chriseppstein** [comment]
@Gespinha  It requires a change to the Sass parser and evaluator. It's a few hours of work. I agree it's annoying and [I feel your pain](https://github.com/Compass/compass/blob/master/core/stylesheets/compass/css3/_animation.scss#L37-L48) too.

**Comment by gespinha** [comment]
@chriseppstein Can we expect a solution to this before 3.4? That would be just great! (thanks by the compass snippet btw)

**Comment by chriseppstein** [comment]
@Gespinha No, this is not slated for 3.4 at this time.

**Comment by G0dwin** [comment]
This appears to be fixed as of at least 3.4.13. I can now do:

``` scss
@mixin keyframes($name, $prefix) {
    @#{prefix}keyframes #{$name} { @content; }
}
```

**Comment by nex3** [comment]
Keyframes are handled as a special case; this still doesn't work for directives in general.

**Comment by karstenvds** [comment]
Any updates on this?
To me it seems like this is still open when I tried to dynamically create '@support' rules.

**Comment by davidkpiano** [comment]
@KarstenBuckstegge Can you post your Sass code that's not working? This works:

``` scss
$display: flex;

@supports (display: #{$display}) {
    div { display: flex; }
}
```
