### ISSUE TITLE
some browser specific pseudo classes/elements get ignored when compiled

### ISSUE THREAD

**Issue by courtsimas** [sass/sass#445]
``` css
::-webkit-input-placeholder {
  color:#000;
}

:-moz-placeholder {
  color:#000;
}
```

Neither of these actually make it into the css.
