### ISSUE TITLE
Using relative values

### ISSUE THREAD

**Issue by caiotoon** [sass/sass#449]
It would be nice to use values relative to the current property value.

Something that would allow the following compilation: 

**SASS source file:**

``` scss
.class {

  font-size: 12pt;

  &.subclass {
    font-size: relative(-2);
  }

}
```

**CSS result file:**

``` css
.class {
  font-size: 12pt;
}

.class.subclass: {
  font-size: 10pt;
}
```
