### ISSUE TITLE
Bug involving @extend and Parent Selector "&"

### ISSUE THREAD

**Issue by noAlvaro** [sass/sass#453]
I think I found a bug using @extend and Parent Selector altogether.
As I tried to demonstrate below:

Source:

``` scss
.message-board {

    .extendable { color: red; }
    .super-caster & { @extend .extendable; }
}
```

Expected output:

``` css
.message-board .extendable,
.supercaster .message-board {

    color: red;
}
```

Actual output:

``` css
.message-board .extendable,
.message-board .super-caster .message-board,
.super-caster .message-board .message-board {

    color: red;
}
```

Is it really a bug or am I missing any point?

**Comment by nex3** [comment]
Here's what's happening. First, your SCSS is being expanded as follows:

``` scss
.message-board .extendable { color: red; }
.super-caster .message-board { @extend .extendable; }
```

The selector `.super-caster .message-board` is now extending the selector `.extendable`. This means that every element matching `.super-caster .message-board` should be styled as though it also matches `.extendable`. Now, `.extendable` is only colored red if it's within a `.message-board`, so the same should be true for `.super-caster .message-board`. The parent `.message-board` could either be outside or inside the `.super-caster`, so Sass generates two additional selectors: `.message-board .super-caster .message-board` and `.super-caster .message-board .message-board`.

So this behavior is ultimately expected.
