### ISSUE TITLE
Incorrect nestings of standard selectors

### ISSUE THREAD

**Issue by nanoSpawn** [sass/sass#454]
Hi ya. I've ran into some weird bug, or maybe it's a feature, but the behaviour is so erratic it feels like a bug, really.

In my scss file I do have the following (where the variables are declared and running, of course):  

``` scss
#editar_pacientes {
    label {
        width: 80px;
    }
    legend {
        color: $colorCorporativo;
        background-color: transparent;
        border-bottom: solid 1px $colorCorporativo;
    }
}
```

And then, the generated css markup with standard 'sass --watch' is:

``` css
#editar_pacientes label, #editar_pacientes input[type='text'], #editar_pacientes input[type='password'], #editar_pacientes textarea {
  width: 80px; }
#editar_pacientes legend {
  color: #035c68;
  background-color: transparent;
  border-bottom: solid 1px #035c68; }
```

It is true that a few lines above the first quote, I declared at once several html tags with the following code: 

``` scss
label, input[type='text'], input[type='password'], textarea {
    @include inline-block;
    width: 170px;
    margin-right: 5px;
    margin-bottom: 10px;
    line-height: 1em;
    text-align: right;
}
```

which seems to somewhat overlap with the #editar_pacientes tag. After carefully reading all the documentation and the SASS references, I didn't find anywhere this should be standard SASS proceeding, it's as if once you join several tags, when you use one of them alone it gets all the others, which is quite an annoying behaviour.

If that's expected, I'll rewrite some of my code, no big deal, but just to be sure.

**Comment by nanoSpawn** [comment]
Forgot it. Rewriting the first block of code to:

``` scss
#editar_pacientes {
    label {
        width: 70px;
    }
    input[type='text'], input[type='password'], textarea {
        width: 200px;
    } 
    legend {
        color: $colorCorporativo;
        background-color: transparent;
        border-bottom: solid 1px $colorCorporativo;
    }
}
```

of course removes the problem altogether, via overwriting the css assignments, but I'm not sure that fits into the "write less" mantra of SASS.
