### ISSUE TITLE
anonymous functions

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#472]
This code is in a patch for compass that I'm about to approve and I really feel like this can be cleaned up dramatically by adding some basic functional programming abilities to Sass.

In particular the importance of lists in css and the need to manipulate them using side-effects is causing severe pain in many of the more complex sass projects that I've seen under development recently.

Consider this code written in Sass's current syntax:

``` scss
@mixin rem($property, $values, $use-px-fallback: $rem-with-px-fallback) {
    // Create a couple of empty lists as output buffers.
    $px-values: ();
    $rem-values: ();

    // Ensure $values is a list.
    @if type-of($values) != 'list' {
        $values: join((), $values);
    }

    // Loop through the $values list
    @each $value in $values {
        // For each property value, if it's in rem or px, derive both rem and
        // px values for it and add those to the end of the appropriate buffer.
        // Ensure all pixel values are rounded to the nearest pixel.
        @if type-of($value) == number and not unitless($value) and (unit($value) == px or unit($value) == rem) {
            @if unit($value) == px {
                $px-values: join($px-values, round($value));
                $rem-values: join($rem-values, convert-length($value, rem));
            }
            @else {
                $px-values: join($px-values, round(convert-length($value, px)));
                $rem-values: join($rem-values, $value);
            }
        }
        @else {
            $px-values: join($px-values, $value);
            $rem-values: join($rem-values, $value);
        }
    }

    // Use pixel fallback for browsers that don't understand rem units.
    @if $use-px-fallback {
        #{$property}: $px-values;
    }

    // Use rem values for everyone else (overrides pixel values).
    #{$property}: $rem-values;
}
```

I'm not sure what the syntax should be, but so that we have something to throw darts at I propose that if the first statement of a ruleset is `->(<argument list>);` then the block would become an anonymous function if passed to a function. This same syntax could also be used by anonymous content blocks to receive arguments from mixins to their `@content` blocks.

``` scss
.mapped {
  foo: map-to(1 2 3) {->($v);
    @return $v * 2;
  };
}
```

which would emit:

``` css
.mapped {
  foo: 2 4 6;
}
```

This would necessitate the need for a built-in function that can be used in `@function` to call the anonymous function. Again, maybe there's a better name and semantics, but let's start with `yield`:

``` scss
@function foo($arg) {
  @return yield($arg * 2);
}

.foo {
  prop: foo(30px) {->($a); @return $a * 2; }
}
```

would compile to:

``` css
.foo {
  prop: 120px
}
```

Following this, I would like Sass to add a number of Sass functions for operating on lists to make working with them much simpler. For instance a `map-to` function for mapping each value in a list to a new value.  `reject` and `keep` could be used to filter lists, etc.

The question of whether to allow named functions to be passed to other functions is a natural follow on. I would start with no for now because an anonymous function can be used to invoke a named function and we have this same issue with content blocks and named mixins. But later on, I imagine this pointer syntax could be used in a fairly natural way:

``` scss

div {
  @include foo(10px) -> my-mixin;
  prop: map-to(10px 20px 30px) -> my-function;
}
```

With these abilities the above original code above cleans up to:

``` scss
@mixin rem($property, $values, $use-px-fallback: $rem-with-px-fallback) {
  // Use pixel fallback for browsers that don't understand rem units.
  @if $use-px-fallback {
    #{$property}: map-to($values) {->($value);
      @return if(type-of($value) == number
                 and not unitless($value)
                 and (unit($value) == px or unit($value) == rem),
                if(unit($value) == px,
                   round($value),
                   round(convert-length($value, px))),
                $value);
    }
  }

  // Use rem values for everyone else (overrides pixel values).
  #{$property}: map-to($values) {->($value);
    @return if(type-of($value) == number
               and not unitless($value)
               and (unit($value) == px or unit($value) == rem),
              if(unit($value) == px,
                 convert-length($value, rem),
                 $value)),
              $value);
  }
}
```
