### ISSUE TITLE
Conversion error in sass-convert from css to scss

### ISSUE THREAD

**Issue by NielsDoucet** [sass/sass#476]
When converting the css fragment below[1] using the SassConvert executable, it generates [2]this scss

[1]

``` css
div.class div.class2 div {
    width: 100px;
}

body .class *.test .test1 {
    width: 200px;
}

.test1 p.class .test2 {
    width: 200px;
}

.test1 p.class .test3 {
    height: 100px;
}
```

[2]

``` scss
div.class div {
  width: 100px; }

body .test1 {
  width: 200px; }

.test1 p.class {
  .test2 {
    width: 200px; }
  .test3 {
    height: 100px; } }
```

The problem arises when the css rule defines more than 2 selectors.
All selectors between the 2 outer ones are simply stripped and not included in the generated scss, unless they can be included in a nested structure.
This problem occurs in version 3.1.19 and 3.1.20 (I haven't tested this in other versions).
