### ISSUE TITLE
compiling error: multiline comment + single-line comment

### ISSUE THREAD

**Issue by clemens-klocker** [sass/sass#478]
nesting a single-line comment inside a multiline comment results in an error. It compiles to a nested multiline comment

SCSS:

<pre><code>/*
    my comment
    // my-selector {display:none;}
*/</code></pre>

is compiled to:

<pre><code>/*
    my comment
    /* my-selector {display:none} */
*/</code></pre>

**Comment by chriseppstein** [comment]
I can't reproduce this using `Sass 3.2.0.alpha.274 (Bleeding Edge)`

I get:

``` css
/*
    my comment
    // my-selector {display:none;}
*/
```
