### ISSUE TITLE
@each doesn't work with media queries

### ISSUE THREAD

**Issue by lifeiscontent** [sass/sass#480]
tried something like this, didn't work.

``` scss
@each $pixel-size in 320, 640, 960 {
  .hide-on-#{$pixel-size} {
    @media screen and (min-width: $pixel-size+0px) {
      display: none;
    }
  }
  .show-on-#{$pixel-size} {
    @media screen and (min-width: $pixel-size+0px) {
      display: block;
    }
  }
}
```

**Comment by chriseppstein** [comment]
Using sass 3.2 it works fine. I get:

``` css
@media screen and (min-width: 320px) { .hide-on-320 { display: none; } }
@media screen and (min-width: 320px) { .show-on-320 { display: block; } }
@media screen and (min-width: 640px) { .hide-on-640 { display: none; } }
@media screen and (min-width: 640px) { .show-on-640 { display: block; } }
@media screen and (min-width: 960px) { .hide-on-960 { display: none; } }
@media screen and (min-width: 960px) { .show-on-960 { display: block; } }
```
