### ISSUE TITLE
Sass 3.2: media queries with ratio values rendered incorrectly

### ISSUE THREAD

**Issue by artibella** [sass/sass#484]
In a media query I am using `-o-min-device-pixel-ratio: 3/2` as a part of the query. When parsed by Sass 3.2 the "3/2" value of the -o-min-device-pixel-ratio gets rendered as "3 / 2" (note the spaces).  **In combination with respond.js this causes wrong media queries to be applied to IE7 and IE8.**

Example:

Sass code:

``` css
$mq-retina: "screen and (-webkit-min-device-pixel-ratio: 2), screen and (min-device-pixel-ratio: 2), screen and (-o-min-device-pixel-ratio: 3/2)"

.foo
  font-size: 3em
  background: red

  @media #{$mq-retina}
    font-size: 6em
    background: yellow
```

CSS output:

``` css
.foo {
  font-size: 3em;
  background: red; }
  @media screen and (-webkit-min-device-pixel-ratio: 2), screen and (min-device-pixel-ratio: 2), screen and (-o-min-device-pixel-ratio: 3 / 2) {
    .foo {
      font-size: 6em;
      background: yellow; } }
```

Is this a bug or is there a way to prevent the addition of spaces in the media query value?
