### ISSUE TITLE
Make the parent selector perform semantically-aware selector unification

### ISSUE THREAD

**Issue by nex3** [sass/sass#490]
For example,

``` scss
div:before { &[id] { content: "#" attr(id); } }
```

should become

``` css
div[id]:before { content: "#" attr(id); }
```

since the unification should know that `:before` must come after other selectors.

Also,

``` scss
*, a { .foo { color: red; } }
```

should become

``` css
.foo, a.foo { color: red; }
```

since the unification would be able to remove the universal selector.
