### ISSUE TITLE
Is tehre a way to force variables to precompile?

### ISSUE THREAD

**Issue by noAlvaro** [sass/sass#496]
Hi,

I found SASS only compiles a range of command/variables/values in the moment it is to be attached to an rule. This kind of behaviour is causing a limitation I would like to discuss.

Consider the markup:

``` html
<ol><li></li></ol>
```

We would use this with success:

``` scss
li {
   content: "name" count(li);   // output content would be: "name1"
}
```

But trying to use this same behaviour outside a rule. In a compass helper, for example, would lead us to compile errors. Like:

``` scss
@include name-sprite( "name" count(li) );   // output content would be: "name content(li)"
```

Seems that the only way to force the expression to compile is assigning it to a rule.

Shouldn't it be reconsidered?
