### ISSUE TITLE
Subject selector unification fails

### ISSUE THREAD

**Issue by nex3** [sass/sass#497]
From #481:

``` scss
aside %part! ol {
  padding-left: 20px;
}

footer .segment! a { @extend %part; }
```

becomes:

``` css
aside footer .segment! a! ol,
footer .segment! aside a! ol {
  padding-left: 20px; }
```

but should be

``` css
aside footer .segment! a ol,
footer aside .segment! a ol,
aside footer .segment! ol a,
footer aside .segment! ol a {
  padding-left: 20px; }
```
