### ISSUE TITLE
@extend don't work in nested media queries within @mixin

### ISSUE THREAD

**Issue by michsch** [sass/sass#500]
I tried to combine @extend in nested media queries within a @mixin:

``` scss
@mixin icon() {
  .icon {
    width: 20px;
    height: 20px;
  }

  .icon-calendar {
    @extend .icon;
  }

  @media only screen and (max-width: 480px) {
    .small-icon {
      width: 12px;
      height: 12px;
    }

    .icon-calendar {
      @extend .small-icon;
    }
  }
}

@media screen, projection {
  @include icon();
}
```

So the first @extend of .icon works, but the extended .small-icon within the media query not.
Without the usage of a mixin both works correctly:

``` scss
@media screen, projection {
  .icon {
    width: 20px;
    height: 20px;
  }

  .icon-calendar {
    @extend .icon;
  }

  @media only screen and (max-width: 480px) {
    .small-icon {
      width: 12px;
      height: 12px;
    }

    .icon-calendar {
      @extend .small-icon;
    }
  }
}
```

If i define the first media query within the mixin this makes no difference.

``` scss
@mixin icon() {
  // @extend works here

  // first media query
  @media screen, projection {
    // @extend works here too

    // nested media query (2nd)
    @media only screen and (max-width: 480px) {
      // @extend won't work here
    }
  }
}
```

Reproduced in OS X 10.8 with SASS 3.2.0.alpha.275 and 3.2.1
