### ISSUE TITLE
Allow extend to work across media directives when the queries are compatible.

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#501]
Consider:

``` scss
@media screen and (min-width: 500px) {
  .foo { color: red; }
}

@media screen and (min-width: 400px) {
  .bar { @extend .foo; }
}
```

This will generate a deprecation warning. But in all cases where `.foo` is defined, the media query it is in is a propery subset of the media query where `.bar` is defined. So this it is safe for sass to perform this operation.
