### ISSUE TITLE
nested placeholders within scope of parent placeholder

### ISSUE THREAD

**Issue by djgrant** [sass/sass#506]
When writing modules using placeholders, it is often desirable to have nested styles. Currently there is no point nesting placeholders as they are scoped globally.

Could something like this be achieved?

``` scss
%m-teaser {
   border: 1px solid #ccc;

   %inner {
      background: #fff;
   }
}

.teaser1 {
   @extend %m-teaser;

   .teaser1-inner {
      @extend %inner;
   }
}
```

**Comment by djgrant** [comment]
To an extent this does work. The above example actually works ok.

The `%inner` placeholder is not available unless `%m-teaser` is extended.

So, using the placeholders from the initial example:

``` scss
.teaser2 {
    @extend %inner;
}
```

Will output nothing.

However, once `%m-teaser` is extended, `%inner` is available anywhere in the stylesheet.

``` scss
.teaser2 {
    @extend %inner;
}

.teaser1 {
    @extend %m-teaser;
}
```

Will output:

``` css
.teaser2 {
    background: #fff;
}

.teaser1 {
    border: 1px solid #ccc;
}
```

It would make much more sense if nested placeholders were only available within the scope that their parents is extended.

**Comment by nex3** [comment]
I don't get the same output you're reporting.

``` scss
%m-teaser {
   border: 1px solid #ccc;

   %inner {
      background: #fff;
   }
}

.teaser2 {
    @extend %inner;
}

.teaser1 {
    @extend %m-teaser;
}
```

gives me

``` css
.teaser1 {
  border: 1px solid #ccc;
}
.teaser1 .teaser2 {
  background: #fff;
}
```

which is what I'd expect.

**Comment by djgrant** [comment]
Sorry, copied wrong output. Yours is correct.

Still not convinced about how and why this works.

Let's take the same placeholders:

``` scss
%m-teaser {
   border: 1px solid #ccc;

   %inner {
      background: #fff;
   }
}
```

Whether or not a nested placeholder gets extended all depends on whether its parent placeholder has been extended. 

Scenario 1A:

``` scss
.teaser2 {
    @extend %inner;
}
```

Outputs nothing

``` css
```

Scenario 1B:

``` scss
.teaser2 {
    @extend %inner;
}

.teaser1 {
    @extend %m-teaser;
}
```

outputs

``` css
.teaser1 {
  border: 1px solid #ccc;
}
.teaser1 .teaser2 {
  background: #fff;
}
```

Similarly if the parent placeholder is extended, whether or not the child placeholder gets extended to the same selector all depends if that child placeholder has been explicitly extend elsewhere.

Scenario 2A:

``` scss
.teaser1 {
    @extend %m-teaser;
}
```

outputs

``` css
.teaser1 {
  border: 1px solid #ccc;
}
```

Scenario 2B:

``` scss
.teaser2 {
    @extend %inner;
}

.teaser1 {
    @extend %m-teaser;
}
```

outputs

``` css
.teaser1 {
  border: 1px solid #ccc;
}
.teaser1 .teaser2 {
  background: #fff;
}
```

That seems troubling because changes made to one selector could potentially impact the output of other unrelated selectors.

My second issue is that I just can't see how I could make this implementation useful in my workflow. The above behaviour just doesn't seem very useful.

What I can do already is nest classes within a placeholder and that is really handy - except that it means I will have to give those classes presentational names, which I am not okay with.

So this is where it would be really helpful to be able to extend a nested presentational placeholder to a nested semantic class selector.

Proposing this:

``` sass
%m-teaser {
   border: 1px solid #ccc;

   %inner {
      background: #fff;
   }
}

.teaser {
  @extend %m-teaser;

  .sematic-class {
    @extend %inner;
  }     
}

.another-teaser {
  @extend %m-teaser;
}
```

outputting

``` css
.teaser, .basic-teaser {
  border: 1px solid #ccc;
}

.teaser .sematic-class {
  background: #fff;
}
```

(What actually gets generated is really weird....)

**Comment by chriseppstein** [comment]
It seems like you don't want nested output -- so don't write nested selectors.

**Comment by djgrant** [comment]
I think my problem is that there is no namespacing/scoping going on. Without it, the extend directive is no where near as useful as it could be.

Let's say I want to make a Bootstrap component available as an extendable module.

I might have something like this:

``` scss
%nav {
  width: 100%;

  .brand {
    color: #fff;
  }

  .btn {
    background: blue;
  }
}

.myNav {
  @extend %nav;
}
```

So far all is well. But what if for some reason I can't apply `.btn` to my markup. The styles for `.btn` instead need to be applied to `.button`. No problem! That's why I made an extendable module - so I didn't have to apply presentational classes all over my markup. 

I would want do something like this:

``` scss
.myNav {
  @extend %nav;

  .button {
    @extend .btn;
  }
}
```

Although that seems like a good, familiar approach, it's not the right one.

Extend the placeholder again and you can see why.

``` scss
.subnav {
  @extend %nav;
}
```

All together generating....

``` css
.myNav, .subNav {
  width: 100%;
}
.myNav .brand, .subNav .brand {
  color: #fff;
}
.myNav .btn, .subNav .btn, .myNav .button, .subNav .myNav .button, .myNav .subNav .button {
  background: blue;
}
```

...a lot of unwanted selectors. Why would I ever want to do that?!

This works better

``` scss
.myNav {
  @extend %nav;
}

.button {
  @extend .btn;
}

.subNav {
  @extend %nav;
}
```

output:

``` css

.myNav, .subNav {
  width: 100%;
}
.myNav .brand, .subNav .brand {
  color: #fff;
}
.myNav .btn, .subNav .btn, .myNav .button, .subNav .button {
  background: blue;
}
```

...but still, I didn't want `.subNav .button`. That could potentially break something.

What's worse is that using a common class name like `.btn` is treacherous because if at any point `.btn` is extended, every `.btn` class will get extended. Basically don't extend anything unless you've namespaced it.
