### ISSUE TITLE
pseudo classes must be rendered after other selectors

### ISSUE THREAD

**Issue by ken210** [sass/sass#509]
code like:

``` sass
a.button
    color: red

    &.selected, &:hover
        color: white

        &.green
            background-color: green

        &.blue
            background-color: blue
```

is rendered like:

``` css
a.button {
  color: red;
}
a.button.selected, a.button:hover {
  color: white;
}
a.button.selected.green, a.button:hover.green {
  background-color: green;
}
a.button.selected.blue, a.button:hover.blue {
  background-color: blue;
}
```

when it must be rendered like:

``` css
a.button {
  color: red;
}
a.button.selected, a.button:hover {
  color: white;
}
a.button.selected.green, a.button.green:hover {
  background-color: green;
}
a.button.selected.blue, a.button.blue:hover {
  background-color: blue;
}
```

becaus ':hover' only works on the end of the selector
