### ISSUE TITLE
Feature: list of CSS' params

### ISSUE THREAD

**Issue by kuraga** [sass/sass#510]
Can't we right so?

``` scss
#bla {
  border: {
    top,bottom: solid 1 px black;
    /* now we have to write two lines:
    top: solid 1 px black;
    bottom: solid 1 px black; */
    }
  }
}
```

I think it will be a good feature if it possible! Thanks!
