### ISSUE TITLE
Failure to optimize away unnecessary selectors

### ISSUE THREAD

**Issue by nex3** [sass/sass#511]
``` scss
%nav {
  width: 100%;

  .brand {
    color: #fff;
  }

  .btn {
    background: blue;
  }
}

.myNav {
  @extend %nav;

  .button {
    @extend .btn;
  }
}

.subnav {
  @extend %nav;
}
```

compiles to

``` css
.myNav, .subNav {
  width: 100%;
}
.myNav .brand, .subNav .brand {
  color: #fff;
}
.myNav .btn, .subNav .btn, .myNav .button, .subNav .myNav .button, .myNav .subNav .button {
  background: blue;
}
```

but should compile to

``` css
.myNav, .subNav {
  width: 100%;
}
.myNav .brand, .subNav .brand {
  color: #fff;
}
.myNav .btn, .subNav .btn, .myNav .button {
  background: blue;
}
```

`.subNav .myNav .button` and `.myNav .subNav .button` are subselectors of `.myNav .button` and should get optimized away.
