### ISSUE TITLE
Doubled selectors when using @extend in :before and :after in a mixin

### ISSUE THREAD

**Issue by mason-stewart** [sass/sass#515]
Hey guys. I assume that this is a bug, and not the intended behavior.

I have a mixin called triangle()

``` scss
@mixin triangle($bg_color: #ffd4ce,) {
  background: $bg_color;
  border-color: darken($bg_color, 50%);

  // the arrow border
  &:before {
    @extend .extendable-arrow-class;
    border-color: transparent transparent darken($bg_color, 50%);
    top:-13px;
  }

  // the arrow itself
  &:after {
    @extend .extendable-arrow-class;
    border-color:transparent transparent $bg_color;
    top: -12px;
  }

 .extendable-arrow-class {
    border-style:solid;
    border-width:0 10px 12px;
    height:0;
    width:0;
    position:absolute;
    left:15px;
    content: " ";
  }
}
```

...and I'm calling it from inside the .error-message class

``` scss
.error-message {
  @include triangle();
}
```

but the css output has the .error-message selector twice:

``` css
.error-message .extendable-arrow-class, .error-message .error-message:before, .error-message .error-message:after {
...
}
```

Any thoughts on this?

**Comment by nex3** [comment]
This is expected. Here's a simpler version of your example:

``` scss
.error-message {
  &:before {@extend .extendable-arrow-class}
  .extendable-arrow-class {...}
}
```

This is equivalent to

``` scss
.error-message:before {@extend .extendable-arrow-class}
.error-message .extendable-arrow-class {...}
```

The selector `.extendable-arrow-class` gets replaced with the selector `.error-message:before`, causing the output you see.

If you don't want this output, I suggest you don't cause `.extendable-arrow-class` to be nested within the including class. I suggest using a [placeholder selector](http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html#placeholder_selectors_) like so:

``` scss
%arrow {
  border-style:solid;
  border-width:0 10px 12px;
  height:0;
  width:0;
  position:absolute;
  left:15px;
  content: " ";
}

@mixin triangle($bg_color: #ffd4ce,) {
  background: $bg_color;
  border-color: darken($bg_color, 50%);

  // the arrow border
  &:before {
    @extend %arrow;
    border-color: transparent transparent darken($bg_color, 50%);
    top:-13px;
  }

  // the arrow itself
  &:after {
    @extend %arrow;
    border-color:transparent transparent $bg_color;
    top: -12px;
  }
}
```
