### ISSUE TITLE
Pass multiple arguments with one variable

### ISSUE THREAD

**Issue by CyberAP** [sass/sass#518]
Since SASS 3.2 we have variable arguments `@function test($args...) {}`, but I tried to pass them with that one variable to different functions like in this example:

``` scss
@function colorHelper($args...) {
    $color: rgba($args);
    @return $color; }

.someClass {
    color: colorHepler(#fff, 0.5); }
```

And got this error:
`Syntax error: wrong number of arguments (1 for 4) for 'rgba'`
I also tried to use `nth()` function, but it does work very strange in functions, combined with conditionals and cause even more errors. Maybe there are some ways to pass multiple arguments to a function?

**Comment by nex3** [comment]
You can pass variable arguments the same way you take them:

``` scss
@function colorHelper($args...) {
    $color: rgba($args...);
    @return $color; }

.someClass {
    color: colorHelper(#fff, 0.5); }
```
