### ISSUE TITLE
Mixins don't work with sub-selectors

### ISSUE THREAD

**Issue by Philipp15b** [sass/sass#520]
I have a problem regarding sub-selectors in mixins. My scss looks like this:

``` scss
@mixin quality($quality, $color) {
  &.#{$quality} {
   color: $color;
 }
}

.item {
  background-color: green;
  @include quality(test, red);
}
```

The output should then include something like this:

``` css
.item.test {
   color: red;
}
```

But instead, there's just the `.item` directive with the background color.

---

Omitting the `&` works:

``` scss
@mixin quality($quality, $color) {
  .#{$quality} {
    border-color: $color;
  }
}

.item {
  background-color: green;
  @include quality(test, red);
}
```

Output contains:

``` css
.item .test {
  border-color: red;
}
```

But then not elements with the `.item` class _and_ `.test` class are selected, but items that are children of an element with `.item`.
