### ISSUE TITLE
Feauture-Request: auto-browser prefixes

### ISSUE THREAD

**Issue by ghost** [sass/sass#525]
A nice feauture would be, if you can write the css without need to write the same code more then once because of browser prefixes.
So If you have in your .scss file:

``` scss
.someclass {
  box-shadow: 1px 1px 3px #000;
}
```

Sass will create the following code in your css:

``` css
.someclass {
  -moz-box-shadow: 1px 1px 3px #000;
  -webkit-box-shadow: 1px 1px 3px #000;
  -o-box-shadow: 1px 1px 3px #000;
  -ms-box-shadow: 1px 1px 3px #000;
  box-shadow: 1px 1px 3px #000;
}
```

Also nice would be, if Sass could things for IE, for example the opacity property:

``` scss
.someclass {
  opacity: 0.65;
}
```

``` css
.someclass {
  filter(opacity=65);
  opacity: 0.65;
}
```
