### ISSUE TITLE
No error on missing semicolon

### ISSUE THREAD

**Issue by fbrandel** [sass/sass#529]
Not sure if bug or feature.
I would expect the following SCSS to fail with an error because of a missing semicolon after the background property:

``` css
.element {
  background: #fff

  div {
    margin-bottom: 20px;
  }
} 
```

but it is compiled to:

``` css
.element {
  background: white div;
  background-margin-bottom: 20px;
}
```

If the nested element is a class selector, it works as expected and a syntax error is thrown.

``` css
.element {
  background: #fff

  div.child {
    margin-bottom: 20px;
  }
} 
```

Sass Version: 3.2.1

**Comment by nex3** [comment]
SCSS, like CSS, is whitespace-independent. That means that

``` scss
.element {
  background: #fff

  div {
    margin-bottom: 20px;
  }
} 
```

is equivalent to

``` scss
.element {
  background: #fff div {
    margin-bottom: 20px;
  }
} 
```

which is valid SCSS, producing the output you see.
