### ISSUE TITLE
Get unitless value

### ISSUE THREAD

**Issue by flops** [sass/sass#533]
Is there any way to parseInt the values and get unitless value ?
All i`ve found that i only can get is it unitless value or not... 

For example:

``` scss
@function clear-units($value){
    @if type-of($value) == "number" {
        @if (unitless($value)) {
            @return $value;
        } @else if unit($value) == "em"{
            @return $value / 1em;
        } @else if unit($value) == "px" {
            @return $value / 1px;
        } @else if unit($value) == "pt" {
            @return $value / 1pt;
        }
    } @else {
        @warn "Not a number value: #{$value}";
        @return $value;
    }
}
```

made this function. But as you can see all units must be declared in if statement, and i don`t really like the realization.

**Comment by pdaoust** [comment]
yes, it does seem a bit verbose. I wrote a function like that myself... It would be nice to see this rolled into SASS core, along with a cast() function that converts one unit into another, without doing arithmetic on it (with the exception of %, which should be divided by 100).

**Comment by nex3** [comment]
There's a built-in [`unitless()` function](http://sass-lang.com/docs/yardoc/Sass/Script/Functions.html#unitless-instance_method) that does this.

**Comment by flops** [comment]
Not even close.
unitless - gives you Bool.
Function in example returns value without units, to convert em to px for example.

**Comment by nex3** [comment]
Sorry, you're correct. Reopening.

**Comment by robwierzbowski** [comment]
In the meanwhile, if you don't want to cycle through all of those ifs:

``` scss
@function strip-units($number) {
  @return $number / ($number * 0 + 1);
 }
```

http://stackoverflow.com/questions/12328259/how-do-you-strip-the-unit-from-any-number-in-sass/12335841#12335841

**Comment by pdaoust** [comment]
@robwierzbowski Thanks for the tip; I'll incorporate it into my own stuff and see if it works!

**Comment by chriskempson** [comment]
Would love to see this in SASS core.

**Comment by KittyGiraudel** [comment]
Function from @robwierzbowski works great. I'd love to see this native. It occurred to me it comes in handy sometimes.

**Comment by chriseppstein** [comment]
I'd like to see use cases where this is a good idea. I have doubts.

**Comment by chriseppstein** [comment]
I think too many people don't know how to work with units and will just use this to do bad things instead of proper math. :(

**Comment by KittyGiraudel** [comment]
So... a function returning a unique identifier per Sass run (https://github.com/nex3/sass/issues/771) is okay, but a function returning an integer from a length/percentage is not? :D

What I find interesting is you provide a function to return the unit from a length (`unit()`), but not a reverse function. It seems kind of odd to me.

**Comment by chriseppstein** [comment]
@HugoGiraudel I gave my concerns and I asked for use cases. Your most recent comment is unproductive and unpersuasive.

**Comment by robwierzbowski** [comment]
I used to have a real-life use case for this, but I can't find an example in my recent work. Off the top of my head: 

``` scss
@function raise($measurement, $exponent) {
  $result: $measurement;
  @for $i from 1 through ($exponent - 1) {
    $result: $result * without-unit($measurement);
  }
  @return $result;
}
```

@ericam is the original stackoverflow answer-er, and might have some in-use examples.

**Comment by KittyGiraudel** [comment]
I didn't mean to sound rude or anything Chris. Sorry if I offended in any case. I just thought this isn't a borderline feature. 

I remember having used this in a REM/PX mixin a while back (http://hugogiraudel.com/2013/03/18/ultimate-rem-mixin/). Not a key feature, but definitely useful in some cases. :)

**Comment by chriseppstein** [comment]
@robwierzbowski This actually makes my point. It's nonsense mathematically to perform and exponential operation with a dimensional value. Taking the unit off, makes the operation succeed, but it doesn't make sense. What does `2px ^ 5em` mean? By doing this, you're making something succeed that should be an error to the caller.

@HugoGiraudel That article is just another case of people who do not understand how arithmetic with dimensional values works. I want us to focus on training them on how to do the math correctly, not giving tools to enable bad behavior.

**Comment by robwierzbowski** [comment]
@chriseppstein: Note with the example function there's no way to do `2px ^ 5em`. The exponent can only be a unitless number, and the without-unit is only applied when multiplying the measurement to itself. It is correct math.

But, I would like to see some real world, in-use examples. Like I said, at one point I wanted this but haven't needed it for quite a while, and have no opinion on whether it should be part of Sass or not.

**Comment by chriseppstein** [comment]
@robwierzbowski Oh, sorry I misread that. Again, this is a misunderstanding of how dimensional values work. 2ft ^ 2 is 4 square feet (an area), not 4 ft (which would be a length). The correct thing to do in this calculation is let the units multiply along with the number. the easiest way to think how to properly do math with units is to think of a unit like it is an unknown quantity in algebra. `(2 * x) ^ 2` is `4 * x^2`. If the units at the end of a calculation don't cancel out to become the dimension you're expecting, this is a good sign that a mathematical error was made.

**Comment by mirisuzanne** [comment]
I don't have any use cases for stripping units. I just enjoy solving the puzzle. I have 3-4 more useless Sass functions if anyone wants them. 

I think we did try to manipulate units early on with Susy, and quickly realized - after a scolding from Chris :) - that it was much simpler and more reliable to keep the units in place. I agree with @chriseppstein that there is really no good reason for this, at least not one I've ever thought of.

**Comment by robwierzbowski** [comment]
@chriseppstein Thanks, that makes a lot of sense.

**Comment by KittyGiraudel** [comment]
> I have 3-4 more useless Sass functions if anyone wants them.

I do. :)

**Comment by cimmanon** [comment]
The only reason I strip the units off of a number is because I wish to use em as my fallback for rem, rather than px.  I _could_ just forget about rem since I've correctly calculated what the em equivalent is, but there may be rounding errors, depending on the browser involved.

http://codepen.io/cimmanon/pen/KfnuA

``` css
body {
  font-size: 133%;
}

.em {
  border: 0.75187em solid;
}

.rem {
  border: 1rem solid;
}
```

In Opera 12.16 (until Opera 15 has the same features as v12, this browser may as well not exist), for instance, the `.em` element border has a calculated width of 15px, while the `.rem` element border has a calculated width of 16px.

**Comment by robwierzbowski** [comment]
I think @chriseppstein's point is that you/we should be using Sass math to convert between units because it is idiomatic and less prone to accidental failure. I'm sure you can convert rem to em in your mixin without stripping the unit.

**Comment by pdaoust** [comment]
I use a little 'unitless' function all the time. My primary (actually, only) use case is for conversion between units, which I believe Sass doesn't have built in (although I know Compass has it built in). I'm in a rather unpleasant tooling environment (Visual Studio), so I can't expect Compass to reliably work, even with Web Workbench. That's why I'm doing unit conversion right in SCSS. For instance:

``` scss
// Hats off to @robwierzbowski for this; it's a lot simpler than my original function
@function strip-units($value) {
    @return $value / ($value * 0 + 1);
}

@function convert-angle($value, $unit) {
    $old-units: unit($value);
    $unitless-value: strip-units($value);

    $base-value: null;
    // Convert the angle to degrees, but without the degree unit
    @if $old-units == grad {
        $base-value: $unitless-value * 0.9;
    } @else if $old-units == turn {
        $base-value: $unitless-value * 360;
    } @else if $old-units == rad {
        $base-value: $unitless-value * (180 / 3.1415926);
    }

    // Now convert it to the desired units
    @if $unit == deg {
        @return $base-value * 1em;
    } @else if $unit == grad {
        @return $base-value / 0.9 * 1grad;
    } @else if $unit == turn {
        @return $base-value / 360 * 1turn;
    } @else if $unit == rad {
        @return $base-value * (3.1415926 / 180) * 1rad;
    }
}
```

Now I realise this doesn't constitute an ideal use case -- I'm very happy to just have my `strip-units()` function, and alternatively I suppose I could get more serious with SASS math, like so:

``` scss
@if $old-units == deg {
    $base-value: $value / 1deg;
} @else if $old-units == grad {
    $base-value: $value * 0.9 / 1grad;
} @else if $old-units == turn {
    $base-value: $value * 360 / 1turn;
} @else if $old-units == rad {
    $base-value: $value * 180 / 3.1415926rad;
}
```

(Is this an idiomatic use of SASS math? It works, but is it muddying the concept at all? For some reason it doesn't improve the meaning of the code for me, even though I do understand the basics of dimensional math. It seems like I'm just stripping the unit anyway, one way or another.)

Anyhow, after having weighed in with my support, I really don't think I prefer either way over the other. So just ignore my use case if you don't think it adds any value :)

**Comment by chriseppstein** [comment]
@pdaoust I'd do it like this:

``` scss
$convertable-units: deg grad turn rad;
$conversion-factors: 1 10grad/9deg 1turn/360deg 3.1415926rad/180deg;
@function convert-angle($value, $unit) {
  @if index($convertable-units, unit($value)) and index($convertable-units, $unit) {
    @return $value
             / nth($conversion-factors, index($convertable-units, unit($value)))
             * nth($conversion-factors, index($convertable-units, $unit));
  } @else {
    @warn "Cannot convert #{unit($value)} to #{$unit}";
  }
}
```
