### ISSUE TITLE
Media Query Bubbling not working with extends

### ISSUE THREAD

**Issue by micahgodbolt** [sass/sass#544]
http://codepen.io/micahgodbolt/pen/FvcJG

Extend works properly when selector is wrapped with the media query. But when you try to put the mq inside of the selector you get a "Extend directives may only be used within rules."

**Comment by TheDutchCoder** [comment]
I concur, it now starts throwing really odd warnings.
Consider the following:

``` css
.impact-image {
  @extend %grid-block;
  @extend %one-whole;
  @media screen and (min-width: 400px) {
    @extend %one-half;
  }
}
```

What I do is I extend the class to a 100% width item, but at a certain breakpoint, it should be 50% width. I now can't use placeholders at all anymore and since media queries are parsed in the scss file, I can't divide my code in media queries either.

Basically destroying the whole responsive grid.

**Comment by micahgodbolt** [comment]
@ReinierK I wouldn't say it destroys responsive grids, but it certainly requires using @include over @extend. The issue right now seems to be the ability to call ANY type of extend from within a media query (unless that @extend is inside that same mq directive, which doesn't make sense for your described setup).

**Comment by TheDutchCoder** [comment]
To be more clear: I use a mobile-first approach, where some elements might be 100% width. These widths are defined in a grid system with placeholders, like so:

``` css
%one-whole { width: 100%; }
%one-half { width: 50%; }
```

Now my class 'impact' for example is 100% width on mobile devices, but 50% on higher res:

``` css
.impact {
  @extend %one-whole;
}
```

What I need (obviously) is:

``` css
.impact {
  @extend %one-whole;
  @media screen and (min-width: 400px) {
    @extend %one-half;
  }
}
```

or (even better):

``` css
.impact {
  @extend %one-whole;
}

...

/* 400 and up =====================*/
@media screen and (min-width: 400px) {
  .impact {
    @extend %one-half;
  }
}
```

The way it works now I actually have to REDEFINE all my placeholders per media query in order to get them to work, which is not only silly, it's also very un-DRY.

``` css
// In some other partial
%one-whole { width: 100%; }
%one-half { width: 50%; }
...

/* 400 and up ==================================== */
@media screen and (min-width: 400px) {

  // Why? :-(
  %one-whole { width: 100%; }
  %one-half { width: 50%; }

  .impact-text,
  .impact-image {
    @extend %one-half;
  }
}
```
