### ISSUE TITLE
Referencing parent from a mixin?

### ISSUE THREAD

**Issue by mxmilkiib** [sass/sass#552]
I'm trying to achieve full browser width bars. My attempt works on [CSSDeck](http://cssdeck.com/labs/bqjumsoc) (and compiles using PHPSass) but gives me a  base-level rules error via Ruby. I'm aware there are improvements coming for [&](https://github.com/nex3/sass/issues/286), but is there another method I could use to achieve the same currently? Thanks for any advice.

**Comment by nex3** [comment]
Your example compiles fine for me:

``` scss
body {
  background: lightblue;
}

section {
  width: 300px;
  background: pink;
  margin: 0 auto;
  text-align: center;
}

#test {
  position: relative;
  background: green;
  margin-top: 0;
  box-sizing: border-box;
  padding: 1em 1em 1em 0;
  color: red;
}
#test:before, #test:after {
  content: "";
  position: absolute;
  background: green;
  /* Match the background */
  top: 0;
  bottom: 0;
  width: 9999px;
  /* Some huge width */
}
#test:before {
  right: 100%;
}
#test:after {
  /* display: none; */
}
```
