### ISSUE TITLE
@case or @switch statement?

### ISSUE THREAD

**Issue by parkerault** [sass/sass#554]
I keep finding myself wanting this when dealing with list variables in function arguments.  I can't seem to find it anywhere in the docs or source so I'm assuming it doesn't exist.

**Comment by chriseppstein** [comment]
I would like to see examples of sass code that a case statement would clean up to understand the problem space better.

**Comment by parkerault** [comment]
Here's one, although I'll be the first to admit it's totally subjective and I wouldn't blame you at all if you decided it wasn't worth implementing. :smile:

``` scss
@mixin css-arrow($size, $scheme: (#ffffff, #cccccc), $side: bottom, $position-origin: left, $position: 50%) {
  $color: nth($scheme, 1);
  $border: nth($scheme, 2);
  @switch $side {
    @when top {
      $direction: bottom;
    }
    @when right {
      $direction: left;
    }
    @when bottom {
      $direction: top;
    }
    @when left {
      $direction: right;
    }
  }
  &:before, &:after {
    content: "";
    position: absolute;
    width: 0;
    height: 0;
    border: $size solid transparent;
    #{$position-origin}: $position;
    margin-#{$position-origin}: -$size;
  }
  &:before {
    #{$side}: -$size*2 - 1px;
    border-#{$direction}: $size+1px solid $border;
  }
  &:after {
    #{$side}: -$size*2 + 1px;
    border-#{$direction}: $size solid $color;
  }
}
```

I'm not sure if it would be better or worse to include `break` statement and fall-through functionality.

**Comment by cimmanon** [comment]
Switch statements are just syntactic sugar for if/elseif/else:

``` scss
@if $side == top {
  $direction: bottom;
} @else if $side == right {
  $direction: left;
} @else if $side == bottom {
  $direction: top;
} @else {
  $direction: right;
}
```

The only time that's not the case is if you're omiting breaks for the purpose of falling through, but that's usually covered by adding expressions to the `@if` statement (eg. `@if $foo == a or $foo == b`).

**Comment by parkerault** [comment]
I agree that there is no functional requirement for `@switch`, it's just a little easier to read IMO.  It's just a "nice to have".

**Comment by swrobel** [comment]
Here's a responsive mixin I use that would be a lot cleaner if it wasn't all `if / else if`s:

``` scss
@mixin respond-to($media) {
  // Phone
  @if $media == phone {
    @media (max-width: 480px) {
      @content;
    }
  }
  // Tablet Portrait
  @else if $media == tablet-portrait {
    @media (max-width: 767px) {
      @content;
    }
  }
  // Tablet Landscape - Desktop
  @else if $media == tablet-landscape-desktop {
    @media (min-width: 768px) and (max-width: 979px) {
      @content;
    }
  }
  // Large Desktop
  @else if $media == large-desktop {
    @media (min-width: 1200px) {
      @content;
    }
  }
  // Non-Retina
  @else if $media == non-retina {
    @media screen and (-webkit-max-device-pixel-ratio: 1) {
      @content;
    }
  }
  // Retina Only
  @else if $media == retina {
    @media screen and (-webkit-min-device-pixel-ratio: 2) {
      @content;
    }
  }
  // Custom breakpoint
  @else {
    @media ($media) {
      @content;
    }
  } 
}
```

**Comment by cimmanon** [comment]
@swrobel Your mixin would be a lot cleaner if you just used variables:

``` scss
$phone: '(max-width: 480px)';
$tablet-portrait: '(max-width: 767px)';
$tablet-landscape-desktop: '(min-width: 768px) and (max-width: 979px)';
$large-desktop: '(min-width: 1200px)';
$non-retina: 'screen and (-webkit-max-device-pixel-ratio: 1)';
$retina: 'screen and (-webkit-min-device-pixel-ratio: 2)';

@mixin respond-to($media) {
    @media #{$media} {
        @content;
    }
}

@include respond-to($phone) {
    .foo {
        background: blue;
    }
}
```

**Comment by chriseppstein** [comment]
@cimmanon This is cleaner but it fails to enforce strong constraints about what breakpoints are supported, which is a key aspect of such an API. We are adding maps in 3.3 and then this will work more like this:

``` scss
$media-types: (phone: '(max-width: 480px)',
               tablet-portrait: '(max-width: 767px)',
               tablet-landscape-desktop: '(min-width: 768px) and (max-width: 979px)',
               large-desktop: '(min-width: 1200px)',
               non-retina: 'screen and (-webkit-max-device-pixel-ratio: 1)',
               retina: 'screen and (-webkit-min-device-pixel-ratio: 2)');

@mixin respond-to($media) {
    @if not map-contains($media-types, $media) {
      @warn "#{$media} is not a known media type. Using large-desktop instead.";
      $media: large-desktop;
    }
    @media #{map-get($media-types, $media)} {
        @content;
    }
}

@include respond-to(phone) {
    .foo {
        background: blue;
    }
}
```

**Comment by parkerault** [comment]
Sworbel's example can be refactored, but that's a bit of a tangent from the topic at hand.  As far as I can tell there is no functionality for `switch` in any language that couldn't be duplicated with `if else`, but it does make certain flow control easier to read.  I think we all agree that `switch` is syntactic sugar, but the question is whether or not it should be implemented.  Yes, no, maybe later.  :)

**Comment by nex3** [comment]
I'm definitely leaning towards "no".

**Comment by parkerault** [comment]
:ok_hand:

**Comment by jonathanfalkner** [comment]
For anyone looking to implement this using SASS itself, assuming you have a number of list helper functions (or have access to the more robust list and map features, which I don't have in this project), you can do something like this:

``` SCSS
// case statement functionality
$z_SwitchCaseList:() !global; 
$z_SwitchCaseFoundList: () !global;
@mixin case($case-values:default)
{
    //only for use inside a switch include, used for creating a switch case statement
    $switch-value: list_getlast($z_SwitchCaseList);
    $value-found: list_getlast($z_SwitchCaseFoundList);
    @if ( $value-found != break ) {
        $match: if($value-found == false, false, true);
        @if ($match == false ) {
            @each $case in $case-values {
                @if $case == $switch-value or $case == default {
                    @if $value-found != break {
                        $match: true;
                    }
                }
                @if $switch-value != () and $switch-value != $case and $case == default and $value-found != break
                { //case is default and switch val not found
                    @warn "#{$switch-value} not found, using default case";
                }
            }
        }
        @if $match == true {
            $z_SwitchCaseFoundList: list_replace-nth($z_SwitchCaseFoundList, length($z_SwitchCaseFoundList), $match) !global;
            @content;
        }
    }
}
@mixin switch($switch-value)
{   
    $z_SwitchCaseList: append($z_SwitchCaseList, $switch-value) !global;
    $z_SwitchCaseFoundList: append($z_SwitchCaseFoundList, false) !global;
    @content;
    $z_SwitchCaseFoundList: list_remove($z_SwitchCaseFoundList, length($z_SwitchCaseFoundList)) !global;
    $z_SwitchCaseList: list_remove($z_SwitchCaseList, length($z_SwitchCaseList)) !global;
}
@mixin BREAK {
    //include this inside the case item, not after, if you want to discontinue processing case statements once the correct one is found.
    $z_SwitchCaseFoundList: list_replace-nth($z_SwitchCaseFoundList, length($z_SwitchCaseFoundList), break) !global;
}
```

And here's a test showing a mixin that defines a selector and uses a switch case statement to do various extends... this could be easily refactored into simple extends, and would be easier to manage code, but this example is just to show that the switch case functionality works and is (I think) rather clean and intuitive to use, all things considered.

``` SCSS
//fallthrough syntax #1
@mixin button1($button-type){
    @extend %button; //all buttons extend button

    @include switch($button-type) {
    @include    case( logout ) {
                    @extend %big-button;
                    @extend %blue-button; 
    @include        BREAK; }
    @include    case( help ) {} //fall through:
    @include    case( go ) { 
                    @extend %big-button; } 
    @include    case( call ) {} //fall through:
    @include    case( download ) { 
                    @extend %green-button;
    @include        BREAK; }
    @include    case( default ){
                    @extend %beige-button;
    @include        BREAK; } 
             }
    //end switch
}
//fallthrough syntax #2 (condensed)
@mixin button2($button-type){
    @extend %button; //all buttons extend button

    @include switch($button-type){
    @include    case( logout ) {
                    @extend %big-button;
                    @extend %blue-button;
    @include        BREAK; }
    @include    case( (help, go) ) {
                    @extend %big-button; } //fall through:
    @include    case( (call, download) ) {//default button
                    @extend %green-button;
    @include        BREAK; }
    @include    case( default ) {
                    @extend %beige-button;
    @include        BREAK; }
             }
    //end switch
}
%button {

    @include border-radius(5px);
    height:44px;
    width:200px;
}
%big-button {
    height:88px;
    font-size:200%;
    width:400px;
}
%beige-button { 
    background-color: #d5d1ca;
    border: 1px solid black;
}
%green-button {
    background-color:#00ff90;
    border: 1px solid #0092ff;
}
%blue-button {
    background-color:#0092ff;
    border: 1px solid #808080;
}

.help-button { @include button2(help); }
.assist-button { @include button2(help); }
.go-button { @include button2(go); }
.upload-button { @include button2(upload); }
.logout-button { @include button2(logout); }
```

**Output:**

``` CSS
.help-button, .assist-button, .go-button, .upload-button, .logout-button {
  -webkit-border-radius: 5px;
  -moz-border-radius: 5px;
  border-radius: 5px;
  height: 44px;
  width: 200px; }

.help-button, .assist-button, .go-button, .logout-button {
  height: 88px;
  font-size: 200%;
  width: 400px; }

.upload-button {
  background-color: #d5d1ca;
  border: 1px solid black; }

.help-button, .assist-button, .go-button {
  background-color: #00ff90;
  border: 1px solid #0092ff; }

.logout-button {
  background-color: #0092ff;
  border: 1px solid #808080; }
```

Though the example is silly, I'm sure there are better use cases than I'm showing here :)

**Comment by lolmaus** [comment]
Hey @jonathanfalkner, you should totally release it on Compass/RubyGems and Bower.

**Comment by chriseppstein** [comment]
``` scss
$direction-per-side: (top: bottom, bottom: top, left: right, right: left);
$direction: map-get($direction-per-side, $side);
```

**Comment by chaos234** [comment]
@jonathanfalkner:

In NetBeans I'll get the following error: Unexpected token EXCLAMATION_MARK found
Now I want to know if your switch/case script is a sass (.scss) or an ruby script.

Lines are affected:

``` scss
$z_SwitchCaseList:() !global; 
$z_SwitchCaseFoundList:() !global;
```

Well I just tried it out with the following code:

``` scss
 @mixin getColorVal($name_val:default, $opacity_val:null) {
    @include switch($name_val) {

    //color: white
    @include    case(default) {
                    color: rgb(255,255,255);
    @include    BREAK; }

    //color: black
    @include    case(black) {
                @if $opacity_val == null {
                    color: rgb(0,0,0);
                } @else if $opacity_val == 1 {
                    color: rgba(0,0,0,0.1);
                } @else if $opacity_val == 2 {
                    color: rgba(0,0,0,0.2);
                } @else if $opacity_val == 3 {
                    color: rgba(0,0,0,0.3);
                } @else if $opacity_val == 4 {
                    color: rgba(0,0,0,0.4);
                } @else if $opacity_val == 5 {
                    color: rgba(0,0,0,0.5);
                } @else if $opacity_val == 6 {
                    color: rgba(0,0,0,0.6);
                } @else if $opacity_val == 7 {
                    color: rgba(0,0,0,0.7);
                } @else if $opacity_val == 8 {
                    color: rgba(0,0,0,0.8);
                } @else if $opacity_val == 9 {
                    color: rgba(0,0,0,0.9);
                }
    @include    BREAK; }

    //color: red
    @include    case(red) {
                @if $opacity_val == null {
                    color: rgb(255,0,0);
                } @else if $opacity_val == 1 {
                    color: rgba(255,0,0,0.1);
                } @else if $opacity_val == 2 {
                    color: rgba(255,0,0,0.2);
                } @else if $opacity_val == 3 {
                    color: rgba(255,0,0,0.3);
                } @else if $opacity_val == 4 {
                    color: rgba(255,0,0,0.4);
                } @else if $opacity_val == 5 {
                    color: rgba(255,0,0,0.5);
                } @else if $opacity_val == 6 {
                    color: rgba(255,0,0,0.6);
                } @else if $opacity_val == 7 {
                    color: rgba(255,0,0,0.7);
                } @else if $opacity_val == 8 {
                    color: rgba(255,0,0,0.8);
                } @else if $opacity_val == 9 {
                    color: rgba(255,0,0,0.9);
                }
    @include    BREAK;}
    }
}

.test { @include getColorVal(black,5);}
```

My output:

.test {
  color: white;
  color: rgba(0, 0, 0, 0.5);
  color: rgba(255, 0, 0, 0.5); }

Why I'm getting three outs instand of the requested one? Hope you or anybody can help me pls.

Oh ... yes, I want to make a mixin/function to get very fast the given color name or the default ones and, if given, the color with an opacity value.

I know ... will be a very long list, if I include all combinations ... but I've the time to do it ^^.

**Comment by jonathanfalkner** [comment]
A couple things... 
1. What I posted was a proof of concept SCSS script, not a finished/vetted/production ready solution, so it is likely to have bugs, performance issues, etc.
2. The version of SASS you're using will greatly impact the ability of this to function (your version must support the global directive, must support lists, etc.)
3. What you are trying to do is already supported natively in SASS via the rgba() function; read up on it [here](http://sass-lang.com/documentation/Sass/Script/Functions.html#rgba-instance_method).  
   Example replacement for your mixin:  

```
@mixin getColorVal($name_val:default, $opacity_val:1) {
    @if $name_val == default {
        $name_val: white;
    }
    color:rgba($name_val, $opacity_val);
}
```

Keep in mind that if you find yourself doing a lot of "copy paste" work, or doing something that seems like it should already be possible (color manipulation, math calcs, etc.) you're probably reinventing the wheel.  Definitely spend some time reading up on all that SASS (and Compass, and Breakpoint, etc.) can do before you assume you need to build some fundamental base functionality into SCSS.

Good luck with the project, and glad to see your desire to learn and improve!

**Comment by chaos234** [comment]
Thank you @jonathanfalkner for your fast feedback.

Well, I useing the latest SASS version so it can result in my problem. But with your corrected code I'll try to make it as a new version for my project.

One question: If I type "rgba($name_val, $opacity_val);" then I can also use the hex-color-code, if I've understand the documentation correctly, right?

**Comment by jonathanfalkner** [comment]
@Chaos234 yes, you are correct.  This function accepts rgb as 3 numbers (between 0 and 255), rgba as 4 numbers (3 numbers between 0 and 255, and the last number being the opacity, which requires a value between 0 and 1), color name, color name with opacity, hex code, and hex code with opacity.

**Comment by olga-demchuk** [comment]
+1

**Comment by jerry4718** [comment]
mark

**Comment by raphievila** [comment]
I think the reason for a switch statement is to avoid repeating code, the essence of Ruby. when using a if/elseif/else statement there is a lot of repetition going on...

I see many of the codes implemented in this thread and they are really a great alternative, but not a real simplistic solution... for example, you cannot say it is the same:

```
@switch $position {
    @case 'top':
        top: $unit;
    @case 'right':
        right: $unit;
    @case 'bottom': 
        bottom: $unit;
    @case 'left':
        left: $unit;
    @default:
        top: $unit;
        left: $unit;
}
```

To this:

```
@if $position == 'top' {
    top: $unit;
} @else if $position == 'right' {
    right: $unit;
} @else if $position == 'bottom' {
    bottom: $unit;
} @else if $position == 'left' {
    left: $unit;
} @else {
    top: $unit;
    left: $unit;
}
```

There is more repetition in the later that the original proposal. Less code, means faster. I cannot imagine how can this be implemented, but if curly brackets make it simple to read, this would be a great alternative:

```
@switch $position {
    @case 'top' {
        top: $unit;
    }
    @case 'right' {
        right: $unit;
    }
    @case 'bottom' {
        bottom: $unit;
    }
    @case 'left' {
        left: $unit;
    }
    @default {
        top: $unit;
        left: $unit;
    }
}
```

Just a suggestion, and just talking out of ignorance because I don't really know how to code Ruby. I have adventure a little into it, but not as to say, let me write a code to solve this... ;)

**Comment by halfnibble** [comment]
I still long for the day when every language (I'm looking at you too python) has a switch/case statement.

**Comment by KyNorthstar** [comment]
I want this as well, and want to throw in my 2¢. Switch statements can be more than just syntactic sugar for if-else statements. Just see [Swift's pattern-matching in `switch` statements](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Patterns.html#//apple_ref/doc/uid/TP40014097-CH36-ID426).

This is a very complex and difficult thing to pull off in an efficient compiler, though, so I won't wish it on the Sass team unless they carry a passion for such syntax. Instead, I'd go for something that the W3C might imagine, like this:


```SCSS
@mixin foo($bar) {
    @switch $bar {
        @case 'baz' {
            color: blue;
        }
        @case 'hoge' {
            color: red;
            @fallthrough;
        }
        @case 3 {
            background-color: black;
        }
    }
}
```

**Comment by Dan503** [comment]
**Sass Maps can be used like a Switch statement.**

If you are just modifying a variable, you can use Sass Maps in a Switch statement sort of way.

(Example taken from my answer on [Stack Overflow](https://stackoverflow.com/a/33207817/1611058))

```scss
    $newVar: map-get((
        case_1_test_name : case_1_return_value,
        case_2_test_name : case_2_return_value,
    ), $testVar);
```
So here's an example:

```scss
    $vehicle: car;

    $vehicleSeating: map-get((
        car : 4,
        bus : 20,
    ), $vehicle);

    //$vehicleSeating = 4
```

The above example translated into if/else statements:

```scss
    $vehicle: car;

	@if ($vehicle == 'car') {
		$vehicleSeating: 4;
	} @else if ($vehicle == 'bus'){
		$vehicleSeating: 20;
	}

    //$vehicleSeating = 4
```

I would still like a Switch statement though for when you need to swap out blocks of CSS rather than swapping out a value in a variable.

```scss
// @switch example
@mixin position ($side){
  position: absolute;

  @switch($side) {
     @case(top){
        top: 0;
     }
     @case(bottom) {
        bottom: 0;
     }
  }
}
```

**Comment by KyNorthstar** [comment]
Switch statements can be much more powerful than being sugar over if/else. Take a look at how Swift does it, maybe draw some inspiration: https://docs.swift.org/swift-book/LanguageGuide/ControlFlow.html#ID129

Here's one of the examples on that page:
```swift
let yetAnotherPoint = (1, -1)
switch yetAnotherPoint {
case let (x, y) where x == y:
    print("(\(x), \(y)) is on the line x == y")
case let (x, y) where x == -y:
    print("(\(x), \(y)) is on the line x == -y")
case let (x, y):
    print("(\(x), \(y)) is just some arbitrary point")
}
// Prints "(1, -1) is on the line x == -y"
```

And maybe how that could look in SCSS:
```scss
$yetAnotherPoint = 1 -1;
@switch $yetAnotherPoint {
case let ($x, $y) where $x == $y:
    color: red;
case let ($x, $y) where $x == -$y:
    color: white;
case default:
    color: gold;
}
// Outputs "color: white;"
```

That's just my most optimistic example, to prove a point about versatility. There's plenty more you could imagine being done with this "Cover all the bases" syntax!
