### ISSUE TITLE
@extend, @import and duplication

### ISSUE THREAD

**Issue by ztamizzen** [sass/sass#560]
Maybe I haven't search the issues properly or read the documentation thoroughly enough (or I just missunderstod things).
My issue is that it seems to me that if I import scss files that use @extend with placeholder selectors from a _lib_ file, to create a more OO experience, the rules are concatenated into one ruleset but that ruleset is duplicated.

for example:
I have two files, one called main.css and the other youtube.css (main.css imports youtube.css).
I use @extend %reset (sets margin: 0 and padding: 0) in both files and it turns into
html, body, hgroup, h1, h2, footer .vcard .fn, #main .split-me ul, #youtube ul, #youtube ul li .title {
  margin: 0;
  padding: 0; }
which is fine but the rule is duplicated (shows up twice) in the output file.

I'll submit a less incoherrent example if needed.

**Comment by nex3** [comment]
Yes, please submit an example of the precise input you're giving Sass and the output you're receiving.

**Comment by ztamizzen** [comment]
I'll keep it breif.

Folders: **css/scss** and **css/compiled**
scss has the files: **_lib.scss**, **main.scss**, **header.scss** and **sidebar.scss**
Content of **main.scss**:

``` css
@import 'lib';

body {
    @extend %reset;
    background-color: #fff;
    margin-bottom: 1em;
    margin-top: 1em;
}

@import 'header', 'sidebar';
```

header.scss:

``` css
@import 'lib';
header {
    @extend %reset;
    background-color: #eee;
    margin-top: 1em;
    width: 97.5%;
}
```

sidebar.scss:

``` css
@import 'lib';
aside {
    @extend %reset;
    display: block;
    float: left;
    width: 30%;
}
```

results in main.css looking like this:

``` css
body, header, aside {
  margin: 0;
  padding: 0; }

body {
  background-color: #fff;
  margin-bottom: 1em;
  margin-top: 1em; }

body, header, aside {
  margin: 0;
  padding: 0; }

header {
  background-color: #eee;
  margin-top: 1em;
  width: 97.5%; }

body, header, aside {
  margin: 0;
  padding: 0; }

aside {
  display: block;
  float: left;
  width: 30%; }
```

The issue is that "body, header, aside" is repeated on line #19 and overrides the "margin-top: 1em" for "body".

I might be doing it wrong but I want the content of the files where the import is.
If I'm wrong you are free to inform me of my error and close the bug and forget it ever existed. =)
