### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by abreu-dev** [sass/sass#567]
I think it would be amazing if there was the possibility to create namespaces like this:

``` css
@namespace btn {
  .& {
    border: 1px solid #999;
    color: #CCC;
    font-size: 14px;
  }

  .&-small {
    padding: 5px;
    font-size: 12px;
  }

  .&-large {
    padding: 10px;
    font-size: 16px;
  }
}
```

so the output would be:

``` css
.btn {
  border: 1px solid #999;
  color: #CCC;
  font-size: 14px;
}

.btn-small {
  padding: 5px;
  font-size: 12px;
}

.btn-large {
  padding: 10px;
  font-size: 16px;
}
```

**Comment by replete** [comment]
I think using a keyword is unnecessary for what is essentially an extension to `&`. It's not as important as the other keywords. For that reason I'd vote against this.

But I think that extending  `-` to `&` is a great addition that needs to be considered for future conflicts. I'd suggest that what you actually want is:

``` scss
.btn {
border: 1px solid #999;
color: #CCC;
font-size: 14px;

  .&-small {
  padding: 5px;
  font-size: 12px;
  }

  .&-large {
  padding: 10px;
  font-size: 16px;
  }
}
```

Somebody else created a new issue for what you have described here: https://github.com/nex3/sass/issues/578
