### ISSUE TITLE
border-color: must follow border:

### ISSUE THREAD

**Issue by y0mbo** [sass/sass#573]
When the `border-color` is specified separately from the `border`, the `border-color` must be set after the `border`. If not, the browser uses the `color` value.

``` scss
$background: #ccc;
$border:  red;
$color:  green;

@mixin m1 {
  border: 2px solid;
}
@mixin m2 {
  border-width: 2px;
  border-style: solid;
}

.one { /* does not work */
  background-color: $background;
  border-color: $border;
  color: $color;
  @include m1;
}
.two { /* works */
  background-color: $background;
  border: 2px solid $border;
  color: $color;
}
.three { /* works */
  background-color: $background;
  border-color: $border;
  color: $color;
  @include m2
}
.four { /* same as .one but @include moved to top, works */
  @include m1;
  background-color: $background;
  border-color: $border;
  color: $color;
}
.five { /* works */
  background-color: $background;
  border: 2px solid;
  border-color: $border;
  color: $color;
}
.six { /* doesn't work */
  background-color: $background;
  border-color: $border;
  border: 2px solid;
  color: $color;
}
```

Sample HTML:

```
<html>
<head>
<link rel="stylesheet" type="text/css" href="assets/style.css" /> 
</head>
<body>
<a href="#" class="one">One</a>
<a href="#" class="two">Two</a>
<a href="#" class="three">Three</a>
<a href="#" class="four">Four</a>
<a href="#" class="five">Five</a>
<a href="#" class="six">Six</a>
</body>
</html>
```

**Comment by replete** [comment]
Is declaration re-ordering a role of SASS? 

Or is it the role of the developer to write correct CSS syntax ordering?

``` scss
.one {
  @include m1;
  background-color: $background;
  border-color: $border;
  color: $color;
}
```
