### ISSUE TITLE
Proposing SASS Regions

### ISSUE THREAD

**Issue by replete** [sass/sass#577]
## The problem

To keep things organised in larger projects, we're using a modular system of keeping related styles and templates together as 'modules'. For example, our topbar 'module' is made up of `topbar.scss`, the template `topbar.html`, and some backend logic.

Because of this arrangement, many repeated `@media` declarations end up inside our compiled CSS file, like this:

``` css
@media only screen and (max-width: 400px) {
    .topbar {
    background:$white}
}
@media only screen and (max-width: 400px) {
    .layout {
    padding:50px}
}
```
## Proposing  SASS Regions

Define a region at some point in the SASS chain, and allow SASS content to be repeatedly appended in the order it was called. 

While this example is focussed on `@media` queries, I think Regions is a versatile and useful addition to the SASS language, in-keeping with its goals and current feature set.
### Defining a new region:

`app.scss`, our primary sass stylesheet:

``` scss
$breakpoint_medium_width: 400px;
$white: #fefefe;
// ...
body {
    background-color:$white;
}
// ...
@media only screen and (max-width: $breakpoint_medium_width) {
    //Defines a new SASS Region (needs better syntax)
    @region('breakpoint_medium');
}
```
### Appending to a region:

`topbar.scss`, one of our many modules:

``` scss
//Append this content wherever 'breakpoint_medium' was defined
@region('breakpoint_medium') {
    .topbar {
    background:$white}
}
```

`layout.scss`, one of our many modules:

``` scss
//Append this content wherever 'breakpoint_medium' was defined
@region('breakpoint_medium') {
    .layout {
    padding:50px}
}
```
### Processed output:

`app.css`, our final compiled CSS:

``` scss
body {
background-color:#fefefe}

@media only screen and (max-width: 400px) {
    .topbar {   
    background:#fefefe}

    .layout {
    padding:50px}
}
```

Please comment if you would like to see this become a part of SASS.

**Comment by replete** [comment]
This idea could also be extended to reach regions in separate sass scopes.

For instance, I want to add something to the `ie7` region inside the `ie.scss` master file:

`app.scss`:

``` scss
//...
@region('ie7', '../ie.scss') {
    .borris {
    zoom:1;
    display:inline}
}
```

`ie.scss`:

``` scss
//IE stylesheet

.ie7 {

    .some-other-thing { 
    border-top:1px solid transparent;
    //display:block;
    }

    //Define region 
    @region('ie7');
}
```

`ie.css` - rendered:

``` css
.ie7 .some-other-thing { border-top:1px solid transparent}
.ie7 .borris { zoom:1; display:inline}
```

This concept can also be applied to things more useful than just IE fixes. Also, what I've demonstrated above wouldn't be fun to work with, it would ideally be simplified into a function, that accepts `@content`.
