### ISSUE TITLE
Long decimals followed by a comment cause parsing to take too long

### ISSUE THREAD

**Issue by nex3** [sass/sass#604]
For example:

``` scss
.foo {
  padding: 4.21052631578947% 4.21052631578947% 5.631578947368421% /**/
}
```

See also @rzea's comments on #362.
