### ISSUE TITLE
classes duplicaded and disordered

### ISSUE THREAD

**Issue by xandyalexandrec** [sass/sass#610]
Hello, i found a bug in SASS, when i generated this code with sass:

``` scss
.font2 { font-size: 12px; }

.watermark {
    .watermark-text {
        @extend .font2;
    }
}

.panelExternal {
    .font2 { font-size: 14px; }

    .watermark {
        .watermark-text {
            padding: 10px;
        }
    }
}
```

this happens:

``` css
.font2, .watermark .watermark-text {
  font-size: 12px; }

.panelExternal .font2, .panelExternal .watermark .watermark-text, .watermark .panelExternal .watermark-text {
  font-size: 14px; }
.panelExternal .watermark .watermark-text {
  padding: 10px; }
```

It's should not write this part:
`watermark .panelExternal .watermark-text`
