### ISSUE TITLE
Placeholder extensions produce needlessly duplicated selectors

### ISSUE THREAD

**Issue by dleclere** [sass/sass#615]
### SASS

``` sass
%a
  margin: 1px

%b
  @extend %a
  font-size: 10px

.b1
  @extend %b
  color: yellow

.b2
  @extend %b
  color: red
```
### CSS Output

``` css
.b1, .b2 {
  margin: 1px;
}

.b1, .b2 {
  font-size: 10px;
}

.b1 {
  color: yellow;
}

.b2 {
  color: red;
}
```
### CSS Expected

``` css
.b1, .b2 {
  margin: 1px;
  font-size: 10px;
}

.b1 {
  color: yellow;
}

.b2 {
  color: red;
}
```
