### ISSUE TITLE
&:before and &:after @extend bug

### ISSUE THREAD

**Issue by firedev** [sass/sass#617]
Code:

``` scss
.article_image {

  %image-block {
    display: block;
  }
  p {
    @extend %image-block;
  }
  &:before {
    @extend %image-block;
    color: red;
  }
  &:after {
    @extend %image-block;
    color: blue;
  }
}
```

Should be:

``` css
.article_image p, .article_image:before, .article_image:after {
  display: block; }
.article_image:before {
  color: red; }
.article_image:after {
  color: blue; }
```

In fact:

``` css
.article_image p, .article_image .article_image:before, .article_image .article_image:after {
  display: block; }
.article_image:before {
  color: red; }
.article_image:after {
  color: blue; }
```

In other words only `.article_image p` extended correctly.

This example would compile correctly if I move `%image-block%` outside of the `.article_image` scope, but then it kinda looses its point.

**Comment by nex3** [comment]
This is expected.

``` scss
.article_image {
  %image-block {display: block}
  &:before {@extend %image-block}
}
```

is equivalent to

``` scss
.article_image %image-block {display: block}
.article_image:before {@extend %image-block}
```

In the second example, it should be clearer that `.article_image .article_image:before` should be generated. It doesn't make sense to merge the two `.article_image` selectors, since one of them applies to a parent element and the other applies to the target element.
