### ISSUE TITLE
Parentheses not compiling in CSS file

### ISSUE THREAD

**Issue by sharikul** [sass/sass#622]
I'm trying to create and use a gradient mixin which requires the use of brackets (parentheses). However, when I compile the SCSS file, the created CSS file doesn't include brackets where it's supposed to be. It turns out it's SASS's fault as it's now "smart enough to remove parentheses."

**Comment by nex3** [comment]
Can you give an example of the input you're giving, the output you expect, and the output you actually receive?

**Comment by sharikul** [comment]
Here's the SASS Mixin:

``` scss
@mixin gradients($val) {
  background: -webkit-linear-gradient($val);
  background: -moz-linear-gradient($val);
  background: -o-linear-gradient($val);
}
```

If I call the Mixin like this:

``` scss
.gradients {
  @include gradients(top left, blue, aqua);
}
```

I expect to get an output which resembles exactly this:

``` css
.gradients {
  background: -webkit-linear-gradient(top left, blue, aqua);
  background: -moz-linear-gradient(top left, blue, aqua);
  background: -o-linear-gradient(top left, blue, aqua);
}
```

But instead, when I view the compiled CSS file, I would get this:

``` css
.gradients {
  background: -webkit-linear-gradienttop left, blue, aqua;
  background: -moz-linear-gradienttop left, blue, aqua;
  background: -o-linear-gradienttop left, blue, aqua;
}
```

Is it an error in the way I've written the Mixin, or is it a bug? Please help!

**Comment by nex3** [comment]
What version of Sass are you using? When I try to compile your SCSS, I get an error because you're passing three arguments to "gradients", which only takes a single argument. Sass supports variable-length argument lists, as so:

``` scss
@mixin gradients($val...) {
  background: -webkit-linear-gradient($val);
  background: -moz-linear-gradient($val);
  background: -o-linear-gradient($val);
}

.gradients {
  @include gradients(top left, blue, aqua);
}
```

This produces the output you expect:

``` css
.gradients {
  background: -webkit-linear-gradient(top left, blue, cyan);
  background: -moz-linear-gradient(top left, blue, cyan);
  background: -o-linear-gradient(top left, blue, cyan); }
```
