### ISSUE TITLE
wrong number of arguments (1 for 2) for `mix'

### ISSUE THREAD

**Issue by maxime-carbonneau** [sass/sass#631]
I cannot compile (bundle exec rake assets:precompile) this code

``` scss
.reveal.tileflip .slides section.present {
    -webkit-filter: custom( url(shaders/tile-flip.vs) mix(url(shaders/tile-flip.fs) multiply source-atop), 10 10 border-box detached, transform perspective(1000) scale(1) rotateX(0deg) rotateY(0deg) rotateZ(0deg), amount 0, randomness 0, flipAxis 0 1 0, tileOutline 1 );
}
```

The code is part of reveal.js
