### ISSUE TITLE
Webkit function collision "mix"

### ISSUE THREAD

**Issue by coreymartella** [sass/sass#633]
Similar to #239 I'm seeing an issue using the [mix](http://www.opengl.org/sdk/docs/manglsl/xhtml/mix.xml) css shader function in my scss files:

``` CSS
.reveal.tileflip .slides section.present {
    -webkit-transform: none;
    -webkit-transition-duration: 800ms;

    -webkit-filter: custom( url(shaders/tile-flip.vs) mix(url(shaders/tile-flip.fs) multiply source-atop), 10 10 border-box detached, transform perspective(1000) scale(1) rotateX(0deg) rotateY(0deg) rotateZ(0deg),
        amount 0, randomness 0, flipAxis 0 1 0, tileOutline 1
    );
}
```

When I try to compile my assets:

```
[01:49:33 cmartella@~/Sites/... (master) ] bundle exec rake RAILS_ENV=production RAILS_GROUPS=assets assets:precompile
rake aborted!
wrong number of arguments (1 for 2) for `mix'
  (in /Users/cmartella/.../app/assets/stylesheets/application.css.scss)
(sass):6458
/Users/cmartella/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.2.5/lib/sass/script/funcall.rb:120:in `rescue in _perform'
/Users/cmartella/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.2.5/lib/sass/script/funcall.rb:93:in `_perform'
/Users/cmartella/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.2.5/lib/sass/script/node.rb:40:in `perform'
```

Is there any way to mark a section or whole file as not eligible for scss evaluation, the issue here is the actual file wit the function call is just plain old css but the application file has some sass usage.
