### ISSUE TITLE
@extend from within same @media scope producing errors

### ISSUE THREAD

**Issue by ghost** [sass/sass#644]
Perhaps I'm misunderstanding the imposed limitations of `@extend` with respect to `@media` but I'm seeing the following issue:

``` scss
@media all {
    %foo {
        color: blue;
    }
    @for $foo from 1 through 3 {
        .foo-#{$foo} {
            @extend %foo;
            width: #{$foo}px;
        }
    }
}
```

Behaves as expected producing:

``` scss
@media all { .foo-1, .foo-2, .foo-3 { color: blue; }
  .foo-1 { width: 1px; }
  .foo-2 { width: 2px; }
  .foo-3 { width: 3px; } }
```

However, if nested in another query:

``` scss
@media all {
    @media (orientation: landscape) {
        %foo {
            color: blue;
        }
        @for $foo from 1 through 3 {
            .foo-#{$foo} {
                @extend %foo;
                width: #{$foo}px;
            }
        }
    }
}
```

It fails to extend, and produces the deprecation error:

```
DEPRECATION WARNING on line 8 of ./test.scss:
  @extending an outer selector from within @media is deprecated.
  You may only @extend selectors within the same directive.
  This will be an error in Sass 3.3.
  It can only work once @extend is supported natively in the browser.
```

And instead yields:

``` scss
@media all and (orientation: landscape) { .foo-1 { width: 1px; }
  .foo-2 { width: 2px; }
  .foo-3 { width: 3px; } }
```

This doesn't seem correct, as the placeholder selector `%foo` being extended is within the same `@media` scope as the extender `.foo-n`.

I initially noticed this on 3.2.3, however while writing this I've updated to 3.2.5 and it remains an issue.

**Comment by robwierzbowski** [comment]
Is `%foo` also defined outside of the @media block?

**Comment by ghost** [comment]
Nope. If it were, I could see the reason for the error; unfortunately, not the case.
I've updated with a completely isolated test (I had tested in "isolation" before, but there was additional rules defined before it)
I can see where you might have thought that, the warning being on line 790-something. ;)

**Comment by robwierzbowski** [comment]
Ah, I missed that you're wrapping queries around each other. Confirming, with 

``` scss
@include breakpoint(screen) {
  @include breakpoint(20em) {
    %thisplace {
       color: red;
    }

    .redtest {
      @extend %thisplace;
    }
  }
}
```

a warning is thrown.
