### ISSUE TITLE
Special selectors inside ':not()' don't expand properly

### ISSUE THREAD

**Issue by argv-minus-one** [sass/sass#648]
The following SCSS

``` scss
foo:not(%bar) {
    color: black;
}

.baz {
    @extend %bar;
}
```

should compile to

``` css
foo:not(.baz) {
    color: black;
}
```

but instead compiles to

``` css
foo:not(%bar) {
    color: black;
}
```

It would seem that Sass does not process selectors inside `:not()` blocks.

**Comment by nex3** [comment]
This is a reasonable request, but before we do it we need to figure out what the following should compile to:

``` scss
foo:not(%bar) {color: black}
.baz .qux {@extend %bar}
```

Unfortunately, `foo:not(.baz .qux)` is invalid. This is pretty important, since nested extenders are quite common.

@chriseppstein, what do you think?
