### ISSUE TITLE
Add an unescape-string() function

### ISSUE THREAD

**Issue by kara-ryli** [sass/sass#659]
_Edited by @nex3 to change the title._

From the [documentation](http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html#import):

> Imports may contain #{} interpolation, but only with certain restrictions. It’s not possible to dynamically import a Sass file based on a variable; interpolation is only for CSS imports. As such, it only works with url() imports. For example:
> 
> ```
> $family: unquote("Droid+Sans");
> @import url("http://fonts.googleapis.com/css?family=\#{$family}");
> ```
> 
> would compile to
> 
> ```
> @import url("http://fonts.googleapis.com/css?family=Droid+Sans");
> ```

However, Sass 3.2.5 compiles to:

```
@import url("http://fonts.googleapis.com/css?family=#{$family}");
```

Some other nuances of the slash behavior, e.g. for `$foo: 83`:
- `content: "\#{$foo}"` compiles to `content: "#{$foo}"`
- `content: "\\#{$foo}"` compiles to `content: "\\83"`
- There does not appear to be a way to get simply `content: "\83"`

This makes it difficult to do things like embed unicode characters in SCSS based on variable values.

**Comment by ben-rolfe** [comment]
It seems like it's also impossible to end a quoted string with a single backslash: `content: "c:\directory\"` causes an error. Admittedly, I can't imagine many situations where having a trailing space would ruin my day.

I thought I had a cheeky workaround for you, but unfortunately `content: "" + \ + $foo` compiles to `content: "\ 83";`. `quote(\)` also throws an error. Argh! :)

**Comment by nex3** [comment]
That documentation is wrong... the backslash shouldn't be there.

As far as the other backslash behavior goes, you're right that it's weird, but I'm not sure there's a good alternative. It's important that Sass interpret strings the same way CSS does, for compatibility reasons. This means that Sass needs to interpret `"\83"` not as a string containing the three characters `\`, `8` and `3`, but as a unicode escape itself. It's conceptually the same as JavaScript not interpreting `"\\" + "n"` as a newline.

Maybe what's called for here is an `unescape-string()` function that converts escapes in a string to the characters they represent.

**Comment by ben-rolfe** [comment]
I must admit I don't understand what's going on at the whirring-cogs level, but wouldn't something like `unescape-string("My string ends in a \")` still cause an error? 
How about a universal-constant-kinda-thing containing a backslash? So RCanine could use `content: $backslash + $foo` to compile to `content: \83;` (is that a hideous/unworkable idea?)

**Comment by nex3** [comment]
You'd want to do `unescape-string("My string ends in a \\")`. Now, this string would print to CSS as `"My string ends in a \"`, which is invalid, so you'd want to be careful with it.

You could implement the `$backslash` variable using `unescape-string`:

``` scss
$backslash: unescape-string("\\");
```

**Comment by ben-rolfe** [comment]
Ah, gotcha. Sounds perfect.

**Comment by nex3** [comment]
@chriseppstein does `unescape-string` sound reasonable to you?

**Comment by chriseppstein** [comment]
I don't think this is necessary. Escape sequences are always for an authoring convenience. Why can't it just be:

``` scss
$foo: \83
```

Or if the goal is to create a unicode character from a charnum maybe we should provide a function that does specifically that:

``` scss
$foo: char-from-code(83);
```

**Comment by lunelson** [comment]
I was trying to do something like this today, hoping that the following would work:

``` scss
$alert-color: orange;
$success-color: green;
$color-types: alert, success;

%color {
    @each $type in $color-types {
        &:#{$type} { color: \$#{$type}-color; }
    }
}

.test {
    @extend %color:success;
}
```

...which is part of an experiment I'm doing concerning automated creation of `@extend` points; but the important bit is interpolating the variable name, since there's no way I could see to unescape the `\$` bit. So the result I got was:

``` scss
.test {
  color: \$success-color; }
```

...which obviously doesn't work. I can't quite remember but I think I did this using Stylus, as it does have an `unquote` or `unescape` function if I remember correctly

**Comment by nex3** [comment]
Variable interpolation is a very different issue than this. See #463.

**Comment by lunelson** [comment]
Ah, I see. Yes, that's pretty much my use case. Good to hear there's a mechanism for it in the works ;)

**Comment by KittyGiraudel** [comment]
> Or if the goal is to create a unicode character from a charnum maybe we should provide a function that does specifically that: `char-from-code(83)`

Any news regarding this? Will it be implemented? And is a `code-from-char()` function worth considering? I am current working on `sort()` and such a function would be quite cool to avoid having a matrix of characters.

**Comment by guymeyer** [comment]
+1 @hugogiraudel's comment

**Comment by f3ndot** [comment]
There is currently no way in Sass 3.4 to get `content: '\f107'` if a variable exists anywhere as a part of that string:

``` scss
// SCSS format
$code: 'f107';

content: "\#{$code}"; // outputs: content: "#{$code}";
content: "\\#{$code}"; // outputs: content: "\\f107";
content: "\005C#{$code}"; // outputs: content: "\\f107";
```

The only way for it to sortof work is to pass the entire escaped string as the variable:

``` scss
// SCSS format
$code: '\2603';

content: "#{$code}"; // outputs: content: "☃";
content: $code; // outputs: content: "☃";
```

The problem is that it actually generates the unicode character. If you wanted `content: "\2603";` you're SOL.

**Comment by dinocarl** [comment]
This seems to be a working workaround:

```
$foo: 83;
$withslash: "\"\\#{$foo}\"";

content: unquote($withslash); // outputs content: "\83";
```

[Here's a Sassmeister gist](http://sassmeister.com/gist/04f5be11c5a6b26b8ff9) showing it in action.

**Comment by KittyGiraudel** [comment]
That's very nasty. Nice catch.

**Comment by dinocarl** [comment]
Yeah, I don't think I'd recommend this, but it can get the job done. [Here's an updated gist](http://sassmeister.com/gist/44eb0fe99d946394d5e1) with a working `char-from-code` function.

**Comment by drublic** [comment]
We're using `str-slice` here.

For instance you set a default value and slice of the first char:

```
str-slice('\x', 1, 1)
```

You can than concatenate the string with a variable:

```
content: str-slice('\x', 1, 1) + $foo;
```

This does not work with the current libsass implementation though.
A possible solution with libsass could be as expected, string interpolation:

```
content: '\#{$foo}';
```

**Comment by lunelson** [comment]
Interesting. With libsass 3.0 simple interpolation works but a bit differently than above. Note the difference:

``` scss
.test {
  out: '#{\039c}';
  out: '\#{039c}';
}
```

``` css
.test {
  out: '\039c';
  out: '\39c'; }
```

However, if libsass keeps to the plan to align itself absolutely with ruby sass this will eventually change.

**Comment by drublic** [comment]
@lunelson Thanks for the test. Seems like I haven't tested this with leading zero values. Good to know.

**Comment by kaelig** [comment]
If like us you need to have your code compatible with Sass 3.3 but also 3.4, you can do so by using both techniques mentioned in this issue:

http://sassmeister.com/gist/e85de9aab9f5616281f2

``` scss
@if function-exists(selector-append) {
  // Sass 3.4
  content: unquote("\"\\#{$character-code}\"");
} @else {
  // Sass 3.3
  content: str-slice("\x", 1, 1) + $character-code;
}
```

Hope it helps.

**Comment by KittyGiraudel** [comment]
And obviously you better wrap this in a function:

``` scss
@function char($character-code) {
  @if function-exists("selector-append") {
    @return unquote("\"\\#{$character-code}\"");
  }

  @return str-slice("\x", 1, 1) + $character-code;
}

.test {
  content: char('039c');
}
```

**Comment by andrewgrewell** [comment]
For those here looking to make a mixin for font icons. (passing in the icon code and outputting the unicode string as the classes content.

http://sassmeister.com/gist/5ca22e8e6c72e27c76b9

```
// ----
// Sass (v3.4.9)
// Compass (v1.0.1)
// ----

@mixin variable-icon-font($icon-code) {
  content: #{"\"\\"}#{$icon-code + "\""};
}

.icon {
  @include variable-icon-font(e603) 
}
```

**Comment by williamboman** [comment]
Thanks @andrewgrewell!

**Comment by matejbudzel** [comment]
@andrewgrewell, you've just saved my day. Thanks a lot!

**Comment by brentdanley** [comment]
Thank you so much, @andrewgrewell. I scoured the Interwebs for this solution, after banging my head for a long time. I knew there was a solution. Cheers.

**Comment by kaelig** [comment]
Here is a workaround to make this work in LibSass (3.2.5 at the time of writing this):

``` scss
@mixin char($character-code) {
    // Escaping in Sass is a bit of a mess…
    // https://github.com/sass/sass/issues/659
    @if function-exists(random) {
        @if function-exists(selector-nest) {
            // Sass 3.4
            content: #{'\"\\' + $character-code + "\""};
        } @else {
            // LibSass
            // Escaping:
            // https://github.com/sass/libsass/issues/1271
            //
            // Outputs a unicode entity instead of a code such as "\f102":
            // https://github.com/sass/libsass/issues/1231
            content: "#{'\"\\' + $character-code + "\""}";
        }
    } @else {
        // Sass 3.3
        content: str-slice("\x", 1, 1) + $character-code;
    }
}
```

**Comment by tagliala** [comment]
We are facing this issue in Font Awesome

I just noticed that suggested solution does not work for all sass implementations

E.g, with @andrewgrewell 's approach:

Input:

``` scss
@mixin variable-icon-font($icon-code) {
  content: #{"\"\\"}#{$icon-code + "\""};
}

.icon {
  @include variable-icon-font(e603) 
}
```

Output:
http://sassmeister.com/gist/d484e00fe9243d4ba0c8 

``` css
.icon {
  content: "\e603";
}
```

## 

http://jsfiddle.net/tagliala/s4xh54k3/

``` css
    .icon {
  content: "\"\\"e603 + "\""; }
```

@kaelig 's approach doesn't work at all on jsfiddle

Refers to https://github.com/FortAwesome/Font-Awesome/pull/6728

**Comment by Anydog** [comment]
@andrewgrewell - thanks, you saved my day ! :)

**Comment by cookch10** [comment]
I was experiencing a similar issue, my solution was to do this:

``` scss
@mixin my-icon($name, $content)
{
    #{".my-icon-#{$name}"}
    {
        &:before
        {
            content: unquote("\"#{$content}\"");
        }
    }
}

@include my-icon(check-mark, \e01c);
```

Yields:

``` css
.my-icon-check-mark:before {
  content: "\e01c";
}
```

**Comment by cesarzeppini** [comment]
@andrewgrewell saved the day!

**Comment by micahgodbolt** [comment]
Sadly not working Libsass

Same code results in 

```
 content: \"\e01c\";
```

**Comment by huyen5991** [comment]
Thank you guys for saving the day for me after the entire day puzzled by this problem. I have Compass, Sass, Grunt, and Handlebars so I wasn't sure what was stripping the backslash and why when I escaped it, I had 2 of them show up. So here's my code to fix it in _settings.scss downloaded from Foundation Icons:

```
@mixin i-class($name,$pua) {
  .#{$classPrefix}#{$name}:before {
    $f: "f";
    content: unquote("\"\\#{$f}#{$pua}\"");
  }
}
```

**Comment by Dan503** [comment]
None of the previous answers worked for me. This did though:

``` scss
@function icon($character){
    @return unquote("\"")+unquote(str-insert($character,"\\", 1))+unquote("\""));
}

$icon-thing: "e60f";

.icon-thing:before {
    content: icon($icon-thing); //outputs content: "\e60f";
}
```

**Comment by seeliang** [comment]
thank you for the update,@f3ndot

**Comment by FDiskas** [comment]
:droplet:
I hope one day it will be posible syntax like this

``` scss
$style: 'default';
$body-default-bg: red;

body {
  background-color: unquote('$btn-#{$style}-disabled-border');
}

/*
body {
  background-color: red;
}
*/
```

**Comment by KittyGiraudel** [comment]
There is no reason to have variable variables in Sass; maps are there for that.

**Comment by FDiskas** [comment]
:open_mouth:
So instead you suggest me to do like so?:

``` scss
$btn-disabled-color:             silver;
$btn-disabled-bg:                gray;
$btn-disabled-border:            transparent;

$btn-default-color:              black;
$btn-default-bg:                 silver;
$btn-default-border:             transparent;
$btn-default-hover-bg:           red;
$btn-default-hover-border:       transparent;
$btn-default-active-bg:          red;
$btn-default-active-border:      transparent;

$btn-primary-color:              black;
$btn-primary-bg:                 blue;
$btn-primary-border:             transparent;
$btn-primary-hover-bg:           red;
$btn-primary-hover-border:       transparent;
$btn-primary-active-bg:          red;
$btn-primary-active-border:      transparent;

$btn-success-color:              black;
$btn-success-bg:                 green;
$btn-success-border:             transparent;
$btn-success-hover-bg:           red;
$btn-success-hover-border:       transparent;
$btn-success-active-bg:          red;
$btn-success-active-border:      transparent;

$btn-info-color:                 black;
$btn-info-bg:                    light-blue;
$btn-info-border:                transparent;
$btn-info-hover-bg:              red;
$btn-info-hover-border:          transparent;
$btn-info-active-bg:             red;
$btn-info-active-border:         transparent;

$btn-warning-color:              black;
$btn-warning-bg:                 orange;
$btn-warning-border:             transparent;
$btn-warning-hover-bg:           red;
$btn-warning-hover-border:       transparent;
$btn-warning-active-bg:          red;
$btn-warning-active-border:      transparent;

$btn-danger-color:               black;
$btn-danger-bg:                  red;
$btn-danger-border:              transparent;
$btn-danger-hover-bg:            red;
$btn-danger-hover-border:        transparent;
$btn-danger-active-bg:           red;
$btn-danger-active-border:       transparent;

$btn-dark-color:                 black;
$btn-dark-bg:                    black;
$btn-dark-border:                transparent;
$btn-dark-hover-bg:              red;
$btn-dark-hover-border:          transparent;
$btn-dark-active-bg:             red;
$btn-dark-active-border:         transparent;

$btn-inverse-color:              black;
$btn-inverse-bg:                 white;
$btn-inverse-border:             transparent;
$btn-inverse-hover-bg:           red;
$btn-inverse-hover-border:       transparent;
$btn-inverse-active-bg:          red;
$btn-inverse-active-border:      transparent;

$styles: (
  "default": (
    "color": $btn-default-color,
    "bg": $btn-default-bg,
    "border": $btn-default-border,
    "hover-bg": $btn-default-hover-bg,
    "hover-border": $btn-default-hover-border,
    "active-bg": $btn-default-active-bg,
    "active-border": $btn-default-active-border,
    "disabled-color": $btn-disabled-color,
    "disabled-bg": $btn-disabled-bg,
    "disabled-border": $btn-disabled-border
  ),
  "primary": (
    "color": $btn-primary-color,
    "bg": $btn-primary-bg,
    "border": $btn-primary-border,
    "hover-bg": $btn-primary-hover-bg,
    "hover-border": $btn-primary-hover-border,
    "active-bg": $btn-primary-active-bg,
    "active-border": $btn-primary-active-border,
    "disabled-color": $btn-disabled-color,
    "disabled-bg": $btn-disabled-bg,
    "disabled-border": $btn-disabled-border
  ),
  "success": (
    "color": $btn-success-color,
    "bg": $btn-success-bg,
    "border": $btn-success-border,
    "hover-bg": $btn-success-hover-bg,
    "hover-border": $btn-success-hover-border,
    "active-bg": $btn-success-active-bg,
    "active-border": $btn-success-active-border,
    "disabled-color": $btn-disabled-color,
    "disabled-bg": $btn-disabled-bg,
    "disabled-border": $btn-disabled-border
  ),
  "info": (
    "color": $btn-info-color,
    "bg": $btn-info-bg,
    "border": $btn-info-border,
    "hover-bg": $btn-info-hover-bg,
    "hover-border": $btn-info-hover-border,
    "active-bg": $btn-info-active-bg,
    "active-border": $btn-info-active-border,
    "disabled-color": $btn-disabled-color,
    "disabled-bg": $btn-disabled-bg,
    "disabled-border": $btn-disabled-border
  ),
  "warning": (
    "color": $btn-warning-color,
    "bg": $btn-warning-bg,
    "border": $btn-warning-border,
    "hover-bg": $btn-warning-hover-bg,
    "hover-border": $btn-warning-hover-border,
    "active-bg": $btn-warning-active-bg,
    "active-border": $btn-warning-active-border,
    "disabled-color": $btn-disabled-color,
    "disabled-bg": $btn-disabled-bg,
    "disabled-border": $btn-disabled-border
  ),
  "danger": (
    "color": $btn-danger-color,
    "bg": $btn-danger-bg,
    "border": $btn-danger-border,
    "hover-bg": $btn-danger-hover-bg,
    "hover-border": $btn-danger-hover-border,
    "active-bg": $btn-danger-active-bg,
    "active-border": $btn-danger-active-border,
    "disabled-color": $btn-disabled-color,
    "disabled-bg": $btn-disabled-bg,
    "disabled-border": $btn-disabled-border
  ),
  "dark": (
    "color": $btn-dark-color,
    "bg": $btn-dark-bg,
    "border": $btn-dark-border,
    "hover-bg": $btn-dark-hover-bg,
    "hover-border": $btn-dark-hover-border,
    "active-bg": $btn-dark-active-bg,
    "active-border": $btn-dark-active-border,
    "disabled-color": $btn-disabled-color,
    "disabled-bg": $btn-disabled-bg,
    "disabled-border": $btn-disabled-border
  ),
  "inverse": (
    "color": $btn-inverse-color,
    "bg": $btn-inverse-bg,
    "border": $btn-inverse-border,
    "hover-bg": $btn-inverse-hover-bg,
    "hover-border": $btn-inverse-hover-border,
    "active-bg": $btn-inverse-active-bg,
    "active-border": $btn-inverse-active-border,
    "disabled-color": $btn-disabled-color,
    "disabled-bg": $btn-disabled-bg,
    "disabled-border": $btn-disabled-border
  ),
);

@function color($style, $type) {
  @return map-get(map-get($styles, $style), $type);
}

button {
  background-color: color('danger', 'bg');
}
```
