### ISSUE TITLE
Switch Statement

### ISSUE THREAD

**Issue by jcampbell05** [sass/sass#663]
I have a proposal for a switch statement, I think allowing for this would make for easier management of websites that need things such as responsive design.

The code below will evaluate each block of code to see which is the first to hit true (starting from the top) if none match then @default is executed.

The one that matches gets its contents outputted inline.

``` scss
@switch {

        $screenWidth <= $mobileWidth && $orientation = 'landscape' {
            display:block;
        }

        @default {
            display:inline; 
        }

}
```

If I wanted to make it compare it to another value other than true then I could write it like this. The \* will take the value of the variable passed to the switch statement and use is part of the statement.

Each condition assumes that the variable is on the left so you can use expressions such as "<="

``` scss
@switch ( $screenWidth ) {

        <= $mobileWidth {
            display: block;
                        width: *;
        }

        @default {
            display: inline;
        }

}
```
