### ISSUE TITLE
Nested @supports blocks

### ISSUE THREAD

**Issue by cimmanon** [sass/sass#674]
Media queries already support nesting:

``` scss
@media (min-width: 20em) {
    @media (max-width: 50em) {
        .foo {
            color: red;
        }
    }
}
```

Output:

``` css
@media (min-width: 20em) and (max-width: 50em) {
  .foo {
    color: red;
  }
}
```

But what about for `@supports`?

``` scss
@supports (display: flex) {
    @supports (flex-wrap: wrap) {
        .foo {
            display: flex;
        }
    }
}
```

Output:

``` css
@supports (display: flex) {
  @supports (flex-wrap: wrap) {
    .foo {
      display: flex;
    }
}
}
```

I was expecting for something more like this for the output:

``` css
@supports (display: flex) and (flex-wrap: wrap) {
  .foo {
    display: flex;
  }
}
```

For my sample code, treating nesting as an AND works, but it is possible that I might want an OR instead.  So maybe the operand should be explicitly required:

``` scss
@supports (display: flex) {
    @supports OR (flex-wrap: wrap) {
        .foo {
            display: flex;
        }
    }
}
```

http://www.w3.org/TR/css3-conditional/#at-supports
