### ISSUE TITLE
Depreciate warning when i use @extend with classes with words separated by -

### ISSUE THREAD

**Issue by felquis** [sass/sass#678]
With this I get a warning.

``` scss
@media only screen and (max-width: 482px) {

        .slider-inicial {
                .flex-next {
                        background-position: 100% 50%;
                        right: 0;

                        @extend .slider-controls-default;
                }

                .flex-prev {
                        background-position: 0 50%;
                        left: 0;
                        @extend .slider-controls-default;
                }
        }

        .slider-controls-default {
                width: 27px;
                height: 100%;
                text-indent: -9999px;
                margin: 0 0;
                cursor: pointer;
                margin-top: 0;
                top: 0;
                background-image: image-url('layout/mobile-slide-seta.png');
                background-repeat: no-repeat;
        }
}
```

When compiling is shown in terminal

```
DEPRECATION WARNING on line 16 of c:/server/www/ecommerce-template/sas
  @extending an outer selector from within @media is deprecated.
  You may only @extend selectors within the same directive.
  This will be an error in Sass 3.3.
  It can only work once @extend is supported natively in the browser.
```

It is similar to #501 

But, this works very well.

``` scss
@media only screen and (max-width: 482px) {

    .slider-inicial {
        .flex-next {
            background-position: 100% 50%;
            right: 0;

            @extend .slidercontrolsdefault;
        }

        .flex-prev {
            background-position: 0 50%;
            left: 0;
            @extend .slidercontrolsdefault;
        }
    }

    .slidercontrolsdefault {
        width: 27px;
        height: 100%;
        text-indent: -9999px;
        margin: 0 0;
        cursor: pointer;
        margin-top: 0;
        top: 0;
        background-image: image-url('layout/mobile-slide-seta.png');
        background-repeat: no-repeat;
    }
}
```

I'm using Sass v3.2.6, Compass v0.12.2 and Ruby v1.9.3

:shipit: This is a bug?
