### ISSUE TITLE
placeholder-selectors decide on the actual selector's order, not the actual selectors

### ISSUE THREAD

**Issue by stryju** [sass/sass#682]
source:

``` scss
%foo {
    color: red;
}
%bar {
    color: blue;
}

.bar {
    @extend %bar;
}
.foo {
    @extend %foo;
}
```

expected output:

``` scss
.bar {
  color:blue
}
.foo {
  color:red
}
```

actual output:

``` scss
.foo {
  color:red
}
.bar {
  color:blue
}
```

bug or a feature?
