### ISSUE TITLE
Pseudo class + ampersand produces invalid CSS

### ISSUE THREAD

**Issue by ohcibi** [sass/sass#693]
Hi,
this snippet:

``` scss
div:before {
  &.testclass {
    font: arial;
  }
}
```

compiles to:

``` css
div:before.testclass {
  font: arial; }
```

which is invalid and should be

``` css
div.testclass:before {
  font:arial; }
```
