### ISSUE TITLE
Ability to check if parent selector exists

### ISSUE THREAD

**Issue by jjenzz** [sass/sass#711]
It would be really handy if it was possible to be able to check `@if & != null`. For example:

``` css
@mixin lt-ie9 {
  @if & != null {
    .lt-ie9 & {
      @content;
    }
  }
  @else {
    .lt-ie9 {
      @content;
    }    
  }
}

.foo {
  @include lt-ie9 {
    color: red;
  }
}

@include lt-ie9 {
  .bar {
    font-weight: bold;
  }

  .bob {
    height: 20px;
  }
}
```
