### ISSUE TITLE
Syntax error: Color value 261 must be between 0 and 255 for `rgb'

### ISSUE THREAD

**Issue by Somebi** [sass/sass#723]
Guess the parser should just replace 261 to 255, no need to throw an error because of that. Maybe a notice will be enough?

I don't want to calculate each time, to see if it will fall over 255 or not.

Here is the code i used for my gradient buttons generation:

``` scss
@import "gradient_button1";

@include gradient_button1('button1',255,179,42);
@include gradient_button1('button2',75,178,255);

@mixin gradient_button1($className,$r,$g,$b){
    .#{$className} {
        $start_color: rgb($r,$g,$b);
        $end_color: rgb(floor($r*0.9686),floor($g*0.7765),floor($b*1.0238));
        $border_color: rgb(floor($r*0.8431),floor($g*0.7765),floor($b*0.0476));
        $border_top_color: rgb(floor($r*0.9607),floor($g*0.9441),floor($b*0.7619));

        background: linear-gradient($start_color 0%, $end_color 100%);
        background: -webkit-linear-gradient($start_color 0%, $end_color 100%);
        background: -moz-linear-gradient($start_color 0%, $end_color 100%);
        background: -o-linear-gradient($start_color 0%, $end_color 100%);
        background: -ms-linear-gradient($start_color 0%, $end_color 100%);
        background: linear-gradient($start_color 0%, $end_color 100%);

        border: 1px solid $border_color;
        border-top-color: $border_top_color;

        border-radius: 3px;

        -webkit-box-shadow: inset 1px -2px 2px rgba(70,70,70,0.3);
        box-shadow: inset 1px -2px 2px rgba(70,70,70,0.3);
    }
}
```

**Comment by Somebi** [comment]
Or, whould be nice to have some limit method, to limit number to 255. Because there is no greater or less signs or any statements in sass as i understand.

**Comment by Snugug** [comment]
@Somebi thta's actually incorrect. You can do something very simple like the following:

``` scss
@function rgb_overflow($input) {
  @if $input > 255 {
    @return 255;
  @else if $input < 0 {
    @return 0;
  }
  @else {
    @return $input;
}

@mixin gradient_button1($className,$r,$g,$b){
    .#{$className} {
        $start_color: rgb($r,$g,$b);

        // In place here
        $end_color: rgb(rgb_overflow(floor($r*0.9686)),rgb_overflow(floor($g*0.7765)),rgb_overflow(floor($b*1.0238)));

        $border_color: rgb(floor($r*0.8431),floor($g*0.7765),floor($b*0.0476));
        $border_top_color: rgb(floor($r*0.9607),floor($g*0.9441),floor($b*0.7619));

        background: linear-gradient($start_color 0%, $end_color 100%);
        background: -webkit-linear-gradient($start_color 0%, $end_color 100%);
        background: -moz-linear-gradient($start_color 0%, $end_color 100%);
        background: -o-linear-gradient($start_color 0%, $end_color 100%);
        background: -ms-linear-gradient($start_color 0%, $end_color 100%);
        background: linear-gradient($start_color 0%, $end_color 100%);

        border: 1px solid $border_color;
        border-top-color: $border_top_color;

        border-radius: 3px;

        -webkit-box-shadow: inset 1px -2px 2px rgba(70,70,70,0.3);
        box-shadow: inset 1px -2px 2px rgba(70,70,70,0.3);
    }
}
```

And so on and so forth for each of your inputs. See als [Sass Number Operations](http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html#number_operations)
