### ISSUE TITLE
Viability of adding/retrieving properties via SassScript function?

### ISSUE THREAD

**Issue by lunelson** [sass/sass#727]
Are there any methods in SassScript that might allow one to construct a `@function` which could add new properties to a declaration (like mixins do) as well as retrieve the current one?

The Stylus pre-processor allows this through built-in "add-property" and "current-property" functions that can be used inside user-defined functions. I can attest that it is great for a lot stuff for which in Sass we must constantly write `@include`s, which can get tedious for oft-used utility mixins. It might look something like this:

``` scss
//input; assuming "a $base-font-size: 16px" has been set somewhere
.foo {
    width: rem(5);
}
```

``` css
/*output*/
.foo {
    width: 5rem;
    *width: 80px;
}
```

I'd really love to be able to do this with Sass cause it annoys me to have a lot of basic code made more obscure and verbose for the sake of such pedestrian stuff as prefixing or fallbacks.

**Comment by robwierzbowski** [comment]
If it's possible I'm also very into this feature. Possibly a syntax like:

``` scss
@function rem($rem-value, $base-font-size: 16) {
  @return $rem-value * $base-font-size * 1px; // value added were the function is called;
  @return-additional width: $rem-value;
}
```

With as many `@return-additional`s as needed.

**Comment by lunelson** [comment]
Yeah, that's the idea, although it would look a bit more like this:

``` scss
@function rem($rem-value, $base-font-size: 16) {
  @return $rem-value * $base-font-size * 1px; // value added where the function is called;
  @add-prop #{$current-prop}: $rem-value; // new prop-value pair added, referencing prop where function was called
}
```

this is adaptable to any property, but requires either an automatic variable `$current-prop` or a function `current-prop()` to retrieve the context where it was called

**Comment by Snugug** [comment]
I dislike this immensely as it throws away the boundaries between what a function and a mixin is. What you're asking for is for a better mixin syntax. To that extent, a better mixin syntax for SCSS has already been proposed and hopefully being worked on for Sass 3.3
https://github.com/nex3/sass/issues/366

**Comment by lunelson** [comment]
A better mixin syntax would also be good, but it's not what I'm asking for. 

I realize it extends the concept of `@function`s to allow them to output property-value declarations in addition to just simple values, but I don't think it's any more of a stretch than such recent additions as passing `@content` blocks to mixins. It's simply a convenience which allows for more flexibility. This is mainly meant for cases such as I describe above, which are just about re-outputting a transformed version of the same declaration, and are the kind of thing you want to just set and forget. Packing this capability in to a function would keep Sass code more clean and let us reserve the use of `@include` (or `+`) for larger blocks of code (parametric or not), which is the thing for which they were originally intended. Such flexibility would reduce the number of `@include` or `+` directives in our code and make it easier to scan.

**Comment by robwierzbowski** [comment]
Although they both address verbosity, this and the proposed shorthand mixin syntax are not equivalent. Using the rem example, for exact equivalency the mixin here would be "width", and you'd need another for "margin", and another for "margin-top", and another for "border-width", etc.

That they would blur the lines between mixins and functions is valid. I would still use the heck out of this though.

**Comment by robwierzbowski** [comment]
@lunelson, how does Stylus deal with `@add-prop` when functions that are only part of a value? E.g.,

``` scss
border: 1px lighten(#c0ff33, 10%) solid;
```

**Comment by lunelson** [comment]
@robwierzbowski 

it's explained on this page, near the bottom: http://learnboost.github.io/stylus/docs/bifs.html. The basic idea is that add-property() is a function which takes two arguments, one for a property name, one for the value(s), and the value argument can also contain functions. It might get hairy if you try to pass a function which also wants to add a property but in theory that could also be handled.

To translate the Stylus example with the imagined syntax we're discussing here and adding a function as value:

``` sass
@function something()
    @add-prop('bar', nth(1 2 3, 2))
    @return 'bar'

body
    foo: something()
```

would return:

``` css
body {
    bar: 2;
    foo: bar;
}
```

beyond that, you have `current-property` which allows some interesting conditions. In the "Nib" library for Stylus for example, the entire processing of linear-gradients, including prefixing and legacy webkit syntax, is done as a function not a mixin, so you simply write `background: linear-gradient(...)` in the same vanilla syntax as CSS but it's processed out to all the additional declarations. It's "set and forget" and you don't have to remember (let alone write out) a mixin syntax, it's very nice. Stylus doesn't happen to use it for vendor-prefixing but it would work there too.

**Comment by chriseppstein** [comment]
A `current-property()` function seems fine to me. We're adding `&` to SassScript and that is basically `current-selector()`.

I agree with @Snugug here. A mixins job is to emit multiple properties. But I think the point here is that a value can be represented differently when it comes to different properties or even for the same property as fallback values. In ruby extensions I accomplished this for gradients by having functions return a special object that a mixin would inspect and decide whether to emit some particular property. Here's that code: https://github.com/chriseppstein/compass/blob/stable/frameworks/compass/stylesheets/compass/css3/_images.scss#L68

And so I wonder if we can find a way to return a value that has a default representation but also has other representations that a mixin could inspect and use. It's less magical than stylus's approach but I think it's keeps the concepts more pure and hence more composable.

**Comment by chriseppstein** [comment]
Here's what I imagine:

``` scss
@function rem($rem-value, $base-font-size: 16px) {
  @if unitless($rem-value) { $rem-value: $rem-value * 1rem}
  $px-value: $rem-value * $base-font-size / 1rem; // value added where the function is called;
  $rem-value: add-aspect($rem-value, fallback, $px-value); // adds a "fallback" aspect to the $rem-value value.
  @return $rem-value;
}
@mixin fallback($property, $value) {
  @if has-aspect($value, fallback) {
    #{$property}: aspect($value, fallback);
  }
  width: $value;
}

.foo { @include fallback(width, rem(2)); }
```

There would also be:
- `aspects($value)` - returns a list of aspects stored against `$value`

This would allow for iteration over all the aspects in a particular value.

**Comment by robwierzbowski** [comment]
After reading up on Stylus, it's much closer to programatic language and is comfortable adding a lot of magic (invisible mixins, language defined variables, etc.). Since that's not the philosophy of Sass, and since without them I can't see `add-prop()` being simple or predictable (especially when a function is a single value in a value list), I don't think it's a good fit. 

@chriseppstein, `current-property()` would be awesome. Slightly OT question: does `aspect` take the place of adding [maps](#642) to Sass?

**Comment by chriseppstein** [comment]
I updated my code example, please re-read it if you read it already.

@robwierzbowski re: maps. I had the thought of whether maps make this need go away but decided they didn't. Here's how they're different: Aspects have a default value. This allows them to work with code that doesn't expect aspect values. Additionally, an aspect exists on a complex value (a list or a map) if that complex value has a value within it that has that aspect. And when you extract a particular aspect from a complex value, the values which do not have that aspect simply return their default value.

**Comment by robwierzbowski** [comment]
Glad maps are still in the works.

I was a little confused on why you would use an aspect instead of returning a list, but the complex value example clears that up. Very nice.

**Comment by chriseppstein** [comment]
Also: it would be fairly easy to have a function that returns a map from a value with aspects or vice-versa.

Maybe the term aspect is too general? What about `support`? E.g. `add-support($v, rem-fallback, $remv)` I think this term may be more obvious about what is going on.

**Comment by robwierzbowski** [comment]
Aspect seems better to me — as a "contextual values" language addition I guarantee it's going to be used for more than just fallback support. Also, don't want to create any confusion with css3 `@supports`.

**Comment by cimmanon** [comment]
The one thing I've come to appreciate from learning and writing Haskell this past year is that functions with side effects are difficult to debug.  Sass is not just for those of us with real programming backgrounds, but for people with little to no programming experience.  I'm just not seeing anything compelling here that would make me change my mind.

chriseppstein's example could have just as easily be written like this:

``` scss
@mixin rem($property, $value, $base-font-size: 16px) {
    $rem-val: if(unitless($value), $value * 1rem, $value);
    $px-value: $rem-value * $base-font-size / 1rem; // unitless check was missing in original
    width: $px-value;
    width: $rem-value;
}

.foo { @include rem(width, 2); }
```

It does the same thing but is _less_ complicated and invoking the mixin has the same verbosity.  If the issue is "I don't want to type out `@include`", it seems to me that https://github.com/nex3/sass/issues/366 addresses this.

Until I see a good use case for the proposed functionality, it looks like change for the sake of change to me.

**Comment by lunelson** [comment]
@chriseppstein I'm not sure I understand aspects: is it adding another value to a variable? How is the example above more efficient than a typical rem mixin? @cimmanon's example looks equivalent to me, at least in terms of verbosity.

However I agree that `current-property()` would be nice, and have uses beyond the use-case of adding properties from `@functions`, such as referring to map-names by property-names; though it would require variable-name interpolation which we don't have yet. FWIW, an adaptation of my maps hack from #642, imagining property-to-map reference

``` scss
// hacky function to retrive value from map matching current property
@function prop-value($key) {
  @each $pair in $#{current-property()} {
    @if index($pair, $key) {
        @return nth($pair, 2);
    }
  }
}

// map named for a property name
$color:
    body #333,
    link red,
    linkHover green;

// usage
body {
  color: prop-value(body);
}
a {
  color: prop-value(link);
  &::hover {
    color: prop-value(linkHover);
  }
}
```

**Comment by chriseppstein** [comment]
@cimmanon I agree with you about side effects. Although functions and mixins can have side effects when they change global variables, I want to keep this to a minimum. The aspect functionality is _already_ in use in compass to make the style of mixins in #366 actually viable. I think the code you wrote is better for this particular example. But when you look at what compass has done with this feature concept in the css3 mixins I think the justification for it is clear. This just gives first class status to that pattern so that sass users can do it without resorting to writing ruby code.

**Comment by chriseppstein** [comment]
@lunelson It's not adding another value to a variable, it would be adding another representation of a value to the value referenced by a variable.

**Comment by nex3** [comment]
I'm pretty squicked-out by the idea of adding invisible metadata to SassScript objects. It makes it easy to run into situations where a function or mixin works differently with inputs that look identical. Chris, can you post an overview of different ways Compass uses this sort of functionality? I'd like to try brainstorming different ways to support this use case.

As for the original feature request, I'm very much in opposition to functions adding properties. Even ignoring the manifold issues with integrating the new properties with the surrounding values, mixins explicitly exist to add properties (as has been pointed out already). Adding that capability to functions just blurs the lines between the two constructs and their use, which does no favors to users trying to figure out which to use where.

**Comment by chriseppstein** [comment]
@nex3 I understand your initial reaction to this. Happy to brainstorm to see if we can come up with something better.

**Comment by chriseppstein** [comment]
More details on how this works in compass right now.

I started with the goal that we could define a mixin that has the exact input syntax for its arguments as the css property of the same name has. Except the output of the mixin would be a fully supported set of prefixed properties and/or fallback values that adhere's to the user's specified browser support matrix. To be clear, any solution that allows me to cleanly meet these requirements is ok by me.

The complexity arises in building a mixin that sometimes has browser support requirements and sometimes doesn't depending on the value. For instance. `@include background(red)` should simply compile to `background: red`. Where as the value of `@include background(image(radial-gradient(#ddd, #aaa 100px), image-url("4x6.png"), #c00))` should emit something like:

``` css
  background: image(-webkit-radial-gradient(#dddddd, #aaaaaa 100px), url('/images/4x6.png?1234567890'), #cc0000);
  background: -moz-image(-moz-radial-gradient(#dddddd, #aaaaaa 100px), url('/images/4x6.png?1234567890'), #cc0000);
  background: image(-o-radial-gradient(#dddddd, #aaaaaa 100px), url('/images/4x6.png?1234567890'), #cc0000);
  background: image(radial-gradient(#dddddd, #aaaaaa 100px), url('/images/4x6.png?1234567890'), #cc0000);
```

Note that the need for prefixing may occur at any argument or even an argument to a function that itself doesn't require prefixing.

We have overridden several css functions that are vendor prefixed. For this example, we'll consider the [`linear-gradient` function](https://github.com/chriseppstein/compass/blob/stable/lib/compass/sass_extensions/functions/gradient_support.rb#L289-L304). The result of invoking this function is to return a [LinearGradient literal](https://github.com/chriseppstein/compass/blob/stable/lib/compass/sass_extensions/functions/gradient_support.rb#L143). This is a ruby object that acts like any other sass literal and if it is used as a [raw value](https://github.com/chriseppstein/compass/blob/stable/frameworks/compass/stylesheets/compass/css3/_images.scss#L99) then it basically returns a string that essentially looks like its construction which we've made resemble css's linear-gradient exactly.

However, there are some other ruby functions (namely, [prefixed and some prefix functions](https://github.com/chriseppstein/compass/blob/stable/lib/compass/sass_extensions/functions/cross_browser_support.rb#L30-L44)) that can inspect and coerce the ruby object to have other string representations. In the compass case, we simply implement these coercion functions in ruby.

I'd like to set a goal that Sass should be expressive enough to implement the compass css3 module without any ruby code that is not provided by Sass itself.

I don't see how to implement the nice API to these mixins without something like this aspect feature. But I am totally open to other ideas.

**Comment by nex3** [comment]
Here's a straw man: a function `add-prefix($value, $prefix, $functions...)` that find every instance of a function in `$value` whose name is in `$functions` and adds `$prefix` to that function. So you could write `background()` something like this:

``` scss
@mixin background($value) {
  if ($experimental-support-for-webkit) { background: add-prefix($value, webkit, radial-gradient); }
  if ($experimental-support-for-mozilla) { background: add-prefix($value, moz, image, radial-gradient); }
  if ($experimental-support-for-opera) { background: add-prefix($value, o, radial-gradient); }
  background: $value;
}
```

would something like this--probably more generalized--support your use cases?

**Comment by chriseppstein** [comment]
Let's talk. At the surface, this doesn't work as it's far too simplistic, but maybe you saying something more nuanced than I am getting here.

**Comment by lunelson** [comment]
@chriseppstein re: your comment above, that `&` == `current-selector()`, are you suggesting that `current-property()` might already be possible in ruby? Would you be willing to shed some light on how it would work? If the SassScript methods for it already exist I'd _really_ like to implement it in my own code.

As for core Sass, I understand all the objections above but personally regard functions and mixins as not fundamentally different. Notably, it is already possible to add a property from a function, you just can't put it on a new line. What's missing here is only an automatic way to retrieve the name of the current property, and possibly also a boolean of whether or not you are in a property declaration, as opposed to a variable declaration:

``` scss
@function rem($n, $property:false) {
    @if $property { @return unquote('#{$n*16}px; #{$property}: #{$n}rem'); }
    @else { @return $n * 1rem; }
}
.test {
    width: rem(5, width);
    height: rem(3);
}
```

``` css
.test {
  width: 80px; width: 5rem;
  height: 3rem;
}
```
