### ISSUE TITLE
background-image does not always produce the right result

### ISSUE THREAD

**Issue by joneff** [sass/sass#734]
The following:

``` scss
body {
  color: red\9;
  background-image: url("aaa.png")\9;
}
```

will render as:

``` css
body {
  color: red\9;
  background-image: url("aaa.png") \9; }
```

Notice the extra space before the slash.

**Comment by nex3** [comment]
This is expected. The way CSS is parsed, the `url()` and the `\9` are separate tokens, so the amount of whitespace between them is insignificant. Sass parses them the same way, then emits them with additional whitespace.

You can work around this using interpolation:

``` scss
body {
  color: red\9;
  background-image: url("aaa.png")#{\9};
}
```
