### ISSUE TITLE
invalid deprecation warning for @extend

### ISSUE THREAD

**Issue by jjenzz** [sass/sass#745]
When using something similar to this:

``` css
%something {
  background: red;
}

body {
  @extend %something;
}

@media (min-width: 700px) {
  %something {
    background: green;
  }

  body {
    @extend %something;
  }
}
```

I get the following deprecation warning:

```
@extending an outer selector from within @media is deprecated.
  You may only @extend selectors within the same directive.
  This will be an error in Sass 3.3.
  It can only work once @extend is supported natively in the browser.
```

The CSS is generated perfectly fine though as **I am** extending a selector within the same directive (as shown here: http://codepen.io/anon/pen/lrtHs) so I would not expect to see this deprecation warning.

**Comment by cimmanon** [comment]
That code can actually be written like this:

``` scss
%something {
  background: red;
}

@media (min-width: 700px) {
  %something {
    background: green;
  }
}

body {
  @extend %something;
}
```

Output:

``` css
body {
  background: red;
}

@media (min-width: 700px) {
  body {
    background: green;
  }
}
```

**Comment by jjenzz** [comment]
Yeah, my example was a bad one... More like this:

``` css
%something {
  background: red;
}

.module {
  @extend %something;
}

@media (min-width: 300px) {
  %something {
    background: green;
  }

  .bp1-bg {
    @extend %something;
  }
}

@media (min-width: 700px) {
  %something {
    background: blue;
  }

  .bp2-bg {
    @extend %something;
  }
}
```

Output:

``` css
.module {
  background: red;
}

@media (min-width: 300px) {
  .module, .bp1-bg {
    background: green;
  }
}

@media (min-width: 700px) {
  .module, .bp2-bg {
    background: blue;
  }
}
```

So `.bp1-bg` & `.bp2-bg` can't be declared outside the media queries as I don't want them being declared inside all media queries.

**Comment by cimmanon** [comment]
Either

``` scss
%something {
  background: red;
}

.module {
  @extend %something;
}

@media (min-width: 300px) {
  %something, %something-else {
    background: green;
  }

  .module--modifier1 {
    @extend %something-else;
  }
}

@media (min-width: 700px) {
  %something, %that-other-thing {
    background: blue;
  }

  .module--modifier2 {
    @extend %that-other-thing;
  }
}
```

Or

``` scss
%something {
  background: red;
}

.module {
  @extend %something;
}

@media (min-width: 300px) {
  %something, .module--modifier1 {
    background: green;
  }
}

@media (min-width: 700px) {
  %something, .module--modifier2 {
    background: blue;
  }
}
```

Output:

``` css
.module {
  background: red;
}

@media (min-width: 300px) {
  .module, .module--modifier1 {
    background: green;
  }
}
@media (min-width: 700px) {
  .module, .module--modifier2 {
    background: blue;
  }
}
```

**Comment by jjenzz** [comment]
It's slightly more complex than that though.... Here's a simplified version of exactly what I am trying to do (my **actual** version has a loop generating several <code>%bar</code>s):

``` css
@mixin respond($bp, $fallback:false) {
  @media (min-width: #{$bp}) {
    @content;
  }

  @if ($fallback) {
    %lt-ie9 {
      @content;
    }
  }
}

...

@include respond(300px, true) {
  %foo {
    color: green;
  }

  %bar {
    @extend %foo;
    background: blue;
  }
}
```

... which should in theory generate the following placeholders:

``` css
@media (min-width: 300px) {
  %foo {
    color: green;
  }

  %bar {
    @extend %foo;
    background: blue;
  }
}

%lt-ie9 {
  %foo {
    color: green;
  }

  %bar {
    @extend %foo;
    background: blue;
  }
}
```

... and then if I extended these as follows:

``` css
.module {
  @extend %bar;
}

.lt-ie9 {
  @extend %lt-ie9 !optional;
}
```

... it gives me my desired output:

``` css
@media (min-width: 300px) {
  .module {
    color: green;
  }

  .module {
    background: blue;
  }
}
.lt-ie9 .module {
  color: green;
}
.lt-ie9 .module {
  background: blue;
}
```

... but I get a deprecation warning because of the `@extend %foo`. Am I really overcomplicating this?

**Comment by cimmanon** [comment]
The problem is your `respond` mixin.  Let's reveal the extend classes so you can see what's actually being generated.

``` scss
@mixin respond($bp, $fallback:false) {
  @media (min-width: #{$bp}) {
    @content;
  }

  @if $fallback {
    %lt-ie9, .reveal-lt-ie9 {
      @content;
    }
  }
}

@include respond(40em, true) {
  %foo, .reveal-foo {
    color: green;
  }

  %bar, .reveal-bar {
    @extend %foo;
    background: blue;
  }
}

.module {
  @extend %bar;
  background: yellow;
}

.lt-ie9 {
  @extend %lt-ie9;
}
```

Output:

``` css
@media (min-width: 40em) {
  .module, .reveal-bar, .lt-ie9 .module, .lt-ie9 .reveal-bar, .reveal-lt-ie9 .module, .reveal-lt-ie9 .reveal-bar, .reveal-foo {
    color: green;
  }

  .module, .reveal-bar {
    background: blue;
  }
}
.lt-ie9 .module, .lt-ie9 .reveal-bar, .lt-ie9 .reveal-lt-ie9 .module, .reveal-lt-ie9 .lt-ie9 .module, .lt-ie9 .reveal-lt-ie9 .reveal-bar, .reveal-lt-ie9 .lt-ie9 .reveal-bar, .lt-ie9 .reveal-foo, .reveal-lt-ie9 .lt-ie9 .module, .lt-ie9 .reveal-lt-ie9 .module, .reveal-lt-ie9 .lt-ie9 .reveal-bar, .lt-ie9 .reveal-lt-ie9 .reveal-bar, .reveal-lt-ie9 .module, .reveal-lt-ie9 .reveal-bar, .reveal-lt-ie9 .reveal-foo {
  color: green;
}
.lt-ie9 .module, .lt-ie9 .reveal-bar, .reveal-lt-ie9 .module, .reveal-lt-ie9 .reveal-bar {
  background: blue;
}

.module {
  background: yellow;
}
```

Your fallback block is causing all the trouble here.

**Comment by jjenzz** [comment]
I am getting different output to you with that code:

``` css
@media (min-width: 40em) {
  .module, .reveal-bar, .reveal-foo {
    color: green;
  }

  .module, .reveal-bar {
    background: blue;
  }
}
.lt-ie9 .module, .lt-ie9 .reveal-bar, .lt-ie9 .reveal-foo, .reveal-lt-ie9 .module, .reveal-lt-ie9 .reveal-bar, .reveal-lt-ie9 .reveal-foo {
  color: green;
}
.lt-ie9 .module, .lt-ie9 .reveal-bar, .reveal-lt-ie9 .module, .reveal-lt-ie9 .reveal-bar {
  background: blue;
}

.module {
  background: yellow;
}
```

Which is what I would expect, no? Obviously the media query is **trying** to extend the outer `%foo` that's within the `%lt-ie9` placeholder, I assumed that must be the problem but surely it should just ignore external placeholders and only extend internal ones? It does currently do that but the deprecation warning is concerning me as I read somewhere that this deprecation warning will become an error soon and I don't want that causing everything to break.

If my thinking is incorrect, is there a better way to achieve what I'm trying to do while still keeping things DRY? I'd prefer not to have to copy and paste the placeholders within the media query and rename them all just for an IE fallback (there are a lot of them).
