### ISSUE TITLE
Invalid font-size calculation (font-size becomes zero)

### ISSUE THREAD

**Issue by ghost** [sass/sass#748]
I'm using ScoutApp (which uses Sass 3.2.1). When i change $font_size in _variables.scss, font-size in final css #breadcrumbs becomes zero. 

bugtest.scss:

``` scss
@import "variables";

#breadcrumbs
{
    font-size: $font_size * 0.7;
}
```

_variables.scss: 

``` scss
{
$font_size: 12px;
}
```

Creates bug:
1. Change $font_size in _variables.scss
2. Save file 
3. Compass autocreates new stylsheet bugtest.css
4. #breadcrumbs font-size is zero in bugtest.css

Temp bugfix when font-size is zero:
1. Invalidate bugtest.scss (add invalid css) and save
2. Remove invalid css and save
3. Font-size is back to normal
