### ISSUE TITLE
mixing call is compiled after my styles

### ISSUE THREAD

**Issue by davidmatas** [sass/sass#750]
I'm not sure if it should be in Compass repository. I'm building a website with Compass and I'm using the `delimited-list` Compass mixing in this way:

``` scss
.nav--lang {
  @include delimited-list('|');
  margin-left: 30px
}
```

And this is the compiled CSS: 

``` css
.nav--lang {
  list-style-type: none;
  margin-left: 30px;
}

.nav--lang, .nav--lang li {
  margin: 0px;
  padding: 0px;
  display: inline;
}
```

The problem is `margin: 0px` from mixing are overriding my `margin-left: 30px`style. Is it a bug or simply my fault? Is there any way to call mixin before my styles without duplicate the selector? I mean one for mixing style, one for my styles.

**Comment by nex3** [comment]
Sass will always put nested rules after the rules in which they're declared. This means that the `.nav--lang, .nav--lang li` rule that's added by the mixin has to come after the original `.nav--lang` rule, and so the `margin-left` property gets overridden. This is an unfortunately weird consequence, but it's not a bug.

You can work around it by separating the `margin-left` declaration into its own rule:

``` scss
.nav--lang {
  @include delimited-list('|');
}

.nav--lang {
  margin-left: 30px
}
```
