### ISSUE TITLE
Bug in CSS generation with multiple nested &classes

### ISSUE THREAD

**Issue by ahfeel** [sass/sass#753]
I'm using Rails 3.2.13 with sass-rails (~> 3.2.3)

My scss file has a section with :

``` scss
.profiles {
    &.choose_sizes {
        .sizerow {
            .span2, .span10 {
                padding: 6px 20px;
            }
            .span10 {
                color: #6d6d6d;
                li {
                    &.selected {
                        background: url(form/glyphicons_ok.png) 130px 15px no-repeat;
                        background-color: #efefef;
                        border: 1px solid #c9c9c9;
                        color: #000;
                    }
                    &:hover {
                        background: #efefef;
                        border: 1px solid #c9c9c9;
                        @include box-shadow(inset 0 0 3px #FFF);
                    }
                }
            }
        }
    }
}
```

Here's the genereted output :

``` css
/* line 316, ../../app/assets/stylesheets/profiles.css.scss */
.profiles.choose_sizes .sizerow .span10 li .selected {
  background: url(form/glyphicons_ok.png) 130px 15px no-repeat;
  background-color: #efefef;
  border: 1px solid #c9c9c9;
  color: #000;
}
/* line 322, ../../app/assets/stylesheets/profiles.css.scss */
.profiles.choose_sizes .sizerow .span10 li :hover {
  background: #efefef;
  border: 1px solid #c9c9c9;
  -webkit-box-shadow: inset 0 0 3px white;
  -moz-box-shadow: inset 0 0 3px white;
  box-shadow: inset 0 0 3px white;
}
```

`li .selected` and `li :hover` are wrong, they should be `li.selected` and `li:hover`.

**Comment by blackfalcon** [comment]
@ahfeel I ran your code through [SassMeister](http://sassmeister.com/), and there was no issues with the output?

``` scss
.profiles {
  &.choose_sizes {
    .sizerow {
      .span10 {
        li {
          &.selected {
            background: url(form/glyphicons_ok.png) 130px 15px no-repeat;
            background-color: #efefef;
            border: 1px solid #c9c9c9;
            color: black;
          }
          &:hover {
            background: #efefef;
            border: 1px solid #c9c9c9;
          }
        }
      }
    }
  }
}
```

had the expected return of

``` css
.profiles.choose_sizes .sizerow .span10 li.selected {
  background: url(form/glyphicons_ok.png) 130px 15px no-repeat;
  background-color: #efefef;
  border: 1px solid #c9c9c9;
  color: black;
}
.profiles.choose_sizes .sizerow .span10 li:hover {
  background: #efefef;
  border: 1px solid #c9c9c9;
}
```

I removed the dependency on Compass and processed as simply Sass just to verify if Sass related. When I added back in the Compass gem, the output was the same.
