### ISSUE TITLE
Support "transparent" as sass color name

### ISSUE THREAD

**Issue by robocoder** [sass/sass#754]
See: http://www.w3.org/TR/css3-color/#transparent-def

**Comment by blackfalcon** [comment]
What's the question/issue? The CSS `transparent` keyword is fully supported in Sass. 

``` sass
.block
  background-color: transparent 
```

will give you perfectly valid CSS like

``` css
.block {
  background-color: transparent;
}
```
