### ISSUE TITLE
improve @extend + placeholder selectors if it’s used just once

### ISSUE THREAD

**Issue by maxhoffmann** [sass/sass#756]
It would be great if Sass could check if a placeholder class is extended just once and if that’s the case work like @include instead of @extend.

``` scss
%alert { // layout
  width: 300px;
  height: 50px;
}

.alert { // default theme
  @extend %alert;
  background-color: gray;
}
```

This currently compiles to:

``` css
.alert {
  width: 300px;
  height: 50px;
}

.alert {
  background-color: gray;
}
```

It would be great if it compiles to:

``` css
.alert {
  width: 300px;
  height: 50px;
  background-color: gray;
}
```

This would improve the output if one uses OOCSS or SMACSS, as one can put layout rules into a placeholder class and theme rules into a “real” class without adding unnecessary code when there is just one theme. If there is more than one theme it works as expected.
