### ISSUE TITLE
Variable undefined error, when variable defined inside both @if and @else

### ISSUE THREAD

**Issue by adam-lynch** [sass/sass#758]
Throws error:

``` scss
@mixin triangle-animation($keyframes, $active: false){
  @if $active{
    $timing: 0.25s;
  }
  @else{
    $timing: 1.5s infinite;
  }
  -webkit-animation: $keyframes $timing ease-in-out alternate;
}
```

Works:

``` scss
@mixin triangle-animation($keyframes, $active: false){
  $timing: 1.5s infinite;
  @if $active{
    $timing: 0.25s;
  }
  -webkit-animation: $keyframes $timing ease-in-out alternate;
}
```
