### ISSUE TITLE
Any thoughts on nested variable declarations?

### ISSUE THREAD

**Issue by yckart** [sass/sass#768]
Since we can nest properties, I think it would be great if we can do the same with our variable-declarations.

Here's an example of what I mean:

``` scss
$font-size: {
    body: 16px;
    aside: 14px;
}
```

The syntax is really similar to what we do with properties, so I think it's not too hard to implement that, or? The problem I see here is the way we can access these later.
