### ISSUE TITLE
Spec for the @at-root directive

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#774]
I'd like to nail down the exact spec for how `@at-root` will work.

So here's some test cases:
### inline selector mode

``` scss
.foo { @at-root .bar { color: gray; } }
```

``` css
.bar { color: gray; }
```
### `&` still works when not in script mode

``` scss
.foo { @at-root .bar & { color: gray; } }
```

``` css
.bar .foo { color: gray; }
```
### `&` works when in script mode

``` scss
.foo { @at-root .bar #{&} { color: gray; } }
```

``` css
.bar .foo { color: gray; }
```
### `@at-root` can take a block

``` scss
.foo { @at-root { .bar #{&} { color: gray; } } }
```

``` css
.bar .foo { color: gray; }
```
### `@at-root` blocks only affect the nearest child selectors.

``` scss
.foo { @at-root { .bar { .baz { color: gray; } } } }
```

``` css
.bar .baz { color: gray; }
```
### `@at-root` doesn't remove selectors from directives by default.

``` scss
@media print {
  @supports ( transform-origin: 5% 5% ) {
    .foo {
      @at-root {
        .bar #{&} {
          color: gray; } } } } }
```

``` css
@media print { @supports ( transform-origin: 5% 5% ) { .bar .foo { color: gray; } } }
```
### `@at-root` in block form can remove a selector from all directives.

``` scss
@media print {
  @supports ( transform-origin: 5% 5% ) {
    .foo {
      @at-root without-directives {
        .bar #{&} {
          color: gray; } } } } }
```

``` css
.bar .foo { color: gray; }
```
### `@at-root` in block form can remove a selector from specific directives.

Media: 

``` scss
@media print {
  @supports ( transform-origin: 5% 5% ) {
    .foo {
      @at-root without-media {
        .bar #{&} {
          color: gray; } } } } }
```

``` css
@supports ( transform-origin: 5% 5% ) { .bar .foo { color: gray; } }
```

Supports:

``` scss
@media print {
  @supports ( transform-origin: 5% 5% ) {
    .foo {
      @at-root without-supports {
        .bar #{&} {
          color: gray; } } } } }
```

``` css
@media print { .bar .foo { color: gray; } }
```

Several directives removed:

``` scss
@media print {
  @supports ( transform-origin: 5% 5% ) {
    .foo {
      @at-root without-supports, without-media {
        .bar #{&} {
          color: gray; } } } } }
```

``` css
.bar .foo { color: gray; }
```
### Selector inheritance uses the resulting selector and directive context.

``` scss
%outside-the-media-block { color: gray }
@media print {
  @supports ( transform-origin: 5% 5% ) {
    .foo {
      @at-root without-directives {
        .bar #{&} {
          // not an error because the directives were removed.
          @extend %outside-the-media-block;  } } } } }
```

``` css
.bar .foo { color: gray; }
```

In theory we can make `without-xxx` be agnostic of directive type, but this may have issues with prefixed directives. Or we can have a whitelist of directive names.

The cases around directive removal will solve a big problem with the limitations around using `@extend` within media blocks. Specifically, this allows you to extend a selector via a mixin for all media contexts instead of just within the current media block.
