### ISSUE TITLE
Use @extend on a string?

### ISSUE THREAD

**Issue by tinganho** [sass/sass#781]
I want to make a mixin for styling placeholders:

``` ruby
@mixin input-placeholder($style) {
  &.placeholder {
    @extend "#{$style}";
  }
  &:-moz-placeholder {
    @extend "#{$style}";
  }
  &::-webkit-input-placeholder {
    @extend "#{$style}";
  }
  &:-ms-input-placeholder {
    @extend "#{$style}";
  }
}

%test {
  font-size: 26px;
  color: #fff;
}

input {
  @include input-placeholder("%test");
}
```

But I can't extend using string value. I wonder if there is an another effective way to solve this problem?

**Comment by cimmanon** [comment]
The problem is the quotes:

``` scss
@mixin input-placeholder($style) {
  &.placeholder {
    @extend #{$style};
  }
  &:-moz-placeholder {
    @extend #{$style};
  }
  &::-webkit-input-placeholder {
    @extend #{$style};
  }
  &:-ms-input-placeholder {
    @extend #{$style};
  }
}
```

Though, if I'm not mistaken, you shouldn't use `@extend` here because each of those selectors has to appear on its own.  Either way, using `@content` is better suited for this task.

``` scss
@mixin input-placeholder {
  &.placeholder {
    @content;
  }
  &:-moz-placeholder {
    @content;
  }
  &::-webkit-input-placeholder {
    @content;
  }
  &:-ms-input-placeholder {
    @content;
  }
}

input {
  @include input-placeholder {
      font-size: 26px;
      color: #fff;
  }
}
```
