### ISSUE TITLE
Ability to choose/interpolate current loop iteration number in @each loops?

### ISSUE THREAD

**Issue by benfrain** [sass/sass#783]
That title sounds a little convoluted. Given a list of items that includes duplicate list items, the index function always returns the first instance of the item. An example:

```
$colors-list: (#25765c, #6d5e4d, #556031, #6d5e4d, #708245);
@each $current-color in $colors-list {
    $i: index($colors-list, $current-color);
    .selector_#{$i} {
        background-color: $current-color;
    }
}
```

Here is the compiled CSS output (notice the duplication of **.header_2** as 2 is the first position that index finds that value at - despite it also being at position 4):

```
.header_1 {
  background-color: #25765c;
}

.header_2 {
  background-color: #6d5e4d;
}

.header_3 {
  background-color: #556031;
}

.header_2 {
  background-color: #6d5e4d;
}

.header_5 {
  background-color: #708245;
}
```

I'd like to be able to generate this CSS automagically:

```
.header_1 {
  background-color: #25765c;
}

.header_2 {
  background-color: #6d5e4d;
}

.header_3 {
  background-color: #556031;
}

.header_4 {
  background-color: #6d5e4d;
}

.header_5 {
  background-color: #708245;
}
```

Am I just thinking about this the wrong way? Is there a way to count the loop number for interpolating the selector number (or whatever in this manner)?

**Comment by Snugug** [comment]
It sounds like what you'd like is #570 (Each with Index). I agree, I'd like to see it too, hopefully the answer won't be "no" again.

**Comment by chriseppstein** [comment]
Yep, the `@for` directive is more efficient at this because index lookup is slower then index access.

``` scss
$colors-list: (#25765c, #6d5e4d, #556031, #6d5e4d, #708245);
@for $i from 1 through length($colors-list) {
    $current-color: nth($colors-list, $i)
    .selector_#{$i} {
        background-color: $current-color;
    }
}
```

Though I grant you that both of these examples are less perfect than the one @Snugug provided in #570.

Note that I think the need for index is actually going to diminish when we introduce maps. People don't want selectors named `.selector_N`. Colors like this have meaning. So expect this code will be more common:

``` scss
$colors: (car: #25765c, bicycle: #6d5e4d, scooter: #556031, skateboard: #6d5e4d, walking: #708245);
@each $transportation-mode: $color in $colors {
    .#{$transportation-mode}-bg {
        background-color: $color;
    }
}
```
