### ISSUE TITLE
Is it possible to generate @extend-Only selectors (silent placeholders) in a separate file?

### ISSUE THREAD

**Issue by ervasive** [sass/sass#793]
Hi guys.

Is there any way to generate separate file with @extend-Only selectors in it?

Lets say I want to have a separate skin layer for my system. All structural styles go into the <code>base.css.scss</code> file, which may have the following code:

``` scss
body {
    font-family: Arial, sans-serif;

    // Here is the 'skin styles' extend
    @extend %skin-body;
}

// Skin file import
@import 'skin';
```

and then this <code>@extend</code> I used, is placed in a separate file <code>skin.css.scss</code> - which I want to be generated and included in my HTML apart from structural styles file.

``` scss
%skin-body {
    background: orange;
    color: gray;
}
```

At the current state all extends are generated at the bottom of the <code>base.css.scss</code>, but the <code>skin.css.scss</code> has no any styles in it, since it doesn't seem to notice any references from the <code>base.css.scss</code>.

Cheers

**Comment by robwierzbowski** [comment]
Yes, you can do this. You just have to import the file containing the placeholders before you use it.

**_placeholders.scss**

``` scss
%myPlaceholder {
  color: red;
}
```

**base.scss**

``` scss
@import 'placeholder';

body {
  @extend %myPlaceholder;
}
```

Same goes for variables and mixins — you must make them available before you use them.

**Comment by ervasive** [comment]
Hello Rob, thank you for your quick reply.

Just tried the exact code sample you provided (except the typo with extend % mark) and I must say it didn't work for me. The output was the following:

**base.scss**

``` css
body {
  color: red;
}
```

and the **placeholders.scss** (I removed underscore from the begging of the filename since I need it to be generated as separated file) was just blank file.

Not sure if it's normal behavior or I just did something wrong.
- Sass 3.2.9

Thanks
