### ISSUE TITLE
@each or for... applied to ID's name

### ISSUE THREAD

**Issue by miguelRivero** [sass/sass#794]
I've browsing the web in search of examples of using the @each function or the "for..." loop to iterate over a list which items have an Id like #item1, #item2, etc. There's plenty of examples using classes but haven't found any with id. Any idea? Is there a notation problem maybe if I use operators like #{$i} ?

Thanks!

**Comment by chriseppstein** [comment]
``` scss
@each $id in "#item1", "#item2", "#item3" {
  #{$id} {
    color: red;
  }
}
```

In the future, please use the [mailing list](http://groups.google.com/group/sass-lang) for support.
