### ISSUE TITLE
if() function evaluates all options; fails unnecessarily

### ISSUE THREAD

**Issue by lunelson** [sass/sass#798]
I ran in to this while working on mixins which take optional arguments, that may sometimes not be given at all. If the optional arguments are under the splat `$args...`, I can't just use `nth()` on the `$args` list because it fails if the list is empty; therefore need to give `$args` some value if it is empty, so subsequent use of it doesn't fail, even if those evaluate to false. In doing this, I've noticed that the `@if` directive and the `if()` function differ in how they evaluate. 

Side note: I use the compass `blank()` function to check if `$args` is empty because I couldn't find another reliable way to do it in plain Sass; if anyone has a better suggestion please let me know.

e.g. (1) using the `@if` directive

``` scss
@mixin test1($x,$args...) {
    @if blank($args) { $args: 1; }
    $y: nth($args, 1);
    value: $x * $y;
}
.test {
    @include test1(5,5);
    @include test1(5);
}
```

works correctly:

``` css
.test {
  value: 25;
  value: 5;
}
```

e.g. (2) using the `if()` function

``` scss
@mixin test2($x,$args...) {
    value: $x * if(blank($args),1,nth($args, 1));
}
.test {
    @include test2(5);
}
```

fails; seemingly because the function still tries to evaluate everything:

``` css
List index is 1 but list has no items for `nth'
```

Thoughts?

**Comment by chriseppstein** [comment]
The `if` function in Sass is a normal function and it evaluates its arguments before running like every other function. If you need to branch execution, you should use the `@if` directive.

That said, we discussed making `if` a parser-level construct when we first built it and I'm not opposed to doing so at some point.

**Comment by lunelson** [comment]
Thanks @chriseppstein, I figured it was something like that; it's a bummer because it does make things more compact, especially for conditionally assigning a variable. 

In my recent use cases, the drawback of the `@if` directive is that it has a different scope, so a variable has to first exist outside the directive in order for the directive to be able to conditionally assign it. It would be nice to see a true branch-executing same-scope `if()` function. 

I gather then, that it simply can't be done in SassScript and has to be built at a deeper level?

**Comment by chriseppstein** [comment]
Right. If you're setting a variable for the first time the code would look like this:

``` scss
$foo: null;
@if $some-condition {
  $foo: value-when-true;
} @else {
  $foo: value-when-false;
}
```

Which is certainly more verbose.
