### ISSUE TITLE
Issue with debug information

### ISSUE THREAD

**Issue by Integralist** [sass/sass#806]
Hi,

My compiled CSS doesn't look to be displaying the debugging information correctly.

Here is my Sass content...

``` sass
body {
    border: 10px solid blue;
    p {
        border: 10px solid green;
    }
}
```

...and here is the output I get from running `sass --style expanded --watch sass:css --debug-info`...

``` css
@media -sass-debug-info{filename{}line{font-family:\000031}}
body {
  border: 10px solid blue;
}
@media -sass-debug-info{filename{}line{font-family:\000033}}
body p {
  border: 10px solid green;
}
```

...that looks broken to me.

The numbers after the first `3` are the actual line number for that particular rule but things like the filename aren't displayed?

Any ideas on whether this is a bug or I'm running things incorrectly.

Thanks.

M.
