### ISSUE TITLE
Mixin : default value for variable arguments feature

### ISSUE THREAD

**Issue by Nabellaleen** [sass/sass#810]
Actually, it's possible to have a default value for a mixin arguments

``` SCSS
@mixin sexy-font($font-family: sans-serif) {
  font-family: $font-family;
}
```

or a variable arguments (that you must fill in)

``` SCSS
@mixin sexy-font($font-family...) {
  font-family: $font-family;
}
```

But it's not possible to have a default value for a variable arguments, to not be forced to fill it

``` SCSS
@mixin sexy-font($font-family: sans-serif...) {
  font-family: $font-family;
}
// or
@mixin sexy-font($font-family...: sans-serif) {
  font-family: $font-family;
}
```

What do you think ?

**Comment by Frexuz** [comment]
+1

**Comment by Snugug** [comment]
You can do this currently the same way you define input defaults in JavaScript; with a check:

``` scss
@mixin my-font($font-family...) {
  @if length($font-family) == 0 {
    $font-family: sans-serif;
  }

  font-family: $font-family;
}
```

Or, with Sass's `if` function:

``` scss
@mixin my-font($font-family...) {
  $font-family: if(length($font-family) == 0, sans-serif, $font-family);

  font-family: $font-family;
}
```
