### ISSUE TITLE
Segmenting code with @region

### ISSUE THREAD

**Issue by sebastiandemel** [sass/sass#816]
Hi,

first of all, thanks for the great work done so far. I have a small request that would help code readability and it is present in C#.

I request we would have a @region or some other named tag, that you can use to group code with out affecting the output.

Example:

``` scss
.page {
    @region Variables {
          $smallPadding: 10px;
          $largePadding: 20px;
    }
    @region Menu styling {
          .menu li {
                padding: $smallPadding;
          }
    } 

    @region Dialog styling {
          .dialog {
                padding: $smallPadding;
                color: white;
          }
    } 
}
```

Like in C#, these regions would not effect the output in anyway. This can be beneficial in cases where you don't want to split the code into multiple section or files. The same could be done in many ways, one being:

``` css
//Relates to dialog
.page .dialog {
}

//Relates to menus
.page .menu {
}
```

But this approach can be hard to track if you have 20 elements in the file. You could also use the import but you will just risk creating many short files.

There is also an interesting feature that could be added to @region. We could include regions from all the scss files found within the files reach with a @get-regions Menu type of syntax.

This would work similar to @include. You could then easily generate css files that have specific styling code in them, without needing to change the underlying scss structure.

You could for example generate files like menu.css, dialogs.css and at the same time have an page specific sass structure like: _profile.scss, _users.scss, _homepage.scss.
