### ISSUE TITLE
sass-convert strips needed parentheses when negating vars (tested on 3.2.9)

### ISSUE THREAD

**Issue by badsyntax** [sass/sass#822]
I have a Sass file with the following contents:

``` scss
$margin: 10px;

.body {
    margin: 0 (-$margin) 20px (-$margin);
}
```

I run the following command:

`sass-convert --from scss --to scss style.scss`

I get the following output:

``` scss
$margin: 10px;

.body {
  margin: 0 -$margin 20px -$margin;
}
```

As you can see, the parenthesis around the variables is being removed, which results in a different output when compiled. I believe this to be a bug. 

Tested with Sass version 3.2.9
