### ISSUE TITLE
Suggestion: List to CSV function @explode

### ISSUE THREAD

**Issue by keeganstreet** [sass/sass#84]
I would like to see a List to CSV function (perhaps called @explode) in Sass. I would like to be able to write a mixin for "transition-property" - a property which accepts a comma separated list of properties to animate. The mixin would accept a single list parameter which is then expanded out to a comma separated list.

``` css
/* Example calls to mixin */
.animateHeight { @include transitionProperty(height); }
.animateSize { @include transitionProperty(height width); }
.animateSizeAndFade { @include transitionProperty(height width opacity); }

/* Example mixin */
@mixin transitionProperty($propertyList) {
    -webkit-transition-property: @explode(",", $propertyList);
    -moz-transition-property: @explode(",", $propertyList);
    -o-transition-property: @explode(",", $propertyList);
    transition-property: @explode(",", $propertyList);
}
```

``` css
/* Example output: */
.animateSizeAndFade {
    -webkit-transition-property: height, width, opacity;
    -moz-transition-property: height, width, opacity;
    -o-transition-property: height, width, opacity;
    transition-property: height, width, opacity;
}
```
