### ISSUE TITLE
Color names in a list return wrong values

### ISSUE THREAD

**Issue by lukaszgrolik** [sass/sass#840]
``` scss
$list: (red blue aqua green);
// =>  (red blue cyan green)

$list: (1 33% aqua 'abc' cyan);
// =>  (1 33% cyan "abc" cyan)
```

I use Sass 3.2.9
The same problem here: http://sass-lang.com/try.html

Basically _Aqua_ and _Cyan_ as a hex are equal (#00ffff), but I think it's still a bug.
There might be similar issue with other color names too.

**Comment by robwierzbowski** [comment]
That and some other color names that have equal values (gray/grey, darkgray/darkgrey, etc.) are replaced with whatever color name comes first in the Sass color list.

The only place I can see this being a problem is if you're using JavaScript to look for all nodes on a page with a certain css value. Kind of an edge case, but a case nonetheless.

This might be something to tack on to https://github.com/nex3/sass/issues/363.

**Comment by chriseppstein** [comment]
Re #363, the implementation I had planned for that was to basically record for any color, the format that was used. E.g. `named`, `hsl`, `rgb`, `hex`. And then this preferred format would be able to propagate through to any derived color values as well as the output of the same color value. However, this means that names that are redundant in the color map, would still have this issue. So we'd need to do more than just track the format, which is kind of annoying.

**Comment by robwierzbowski** [comment]
@lukaszgrolik, what issues were you experiencing because of identical color name replacement?

**Comment by lukaszgrolik** [comment]
@robwierzbowski, no serious problems, but let's assume we have tags with ids `item-blue`, `item-aqua` and `item-green` that we want to style by the `@each` depending on their names:

``` scss
$colors: (blue aqua green);

@each $color in $colors  {
  #item-#{$color} {
    background: $color;
  }
}
```

There will be backgrounds for `#item-blue`, `#item-cyan` and `#item-green`, but not for the `#item-aqua`. These color name replacement exceptions must be remembered and styled separately.

**Comment by chriseppstein** [comment]
Here's how you should do this in a way that will work, even when using compressed output:

``` scss
$colors: ("blue" blue, "aqua" aqua, "green" green);

@each $color-pair in $colors  {
  $color-name: nth($color-pair, 1);
  $color: nth($color-pair, 2);
  #item-#{$color-name} {
    background: $color;
  }
}
```
