### ISSUE TITLE
Unexpected @extend inheritance

### ISSUE THREAD

**Issue by pcdevil** [sass/sass#845]
I think there is a bug with @extend (or at least has a very unusual behavior).
Here is a _sample code_:

``` SCSS
%code-text {
    font: 12px monospace;
}

article {
    %code-text {
        @extend %code-text;
        color: #177fb7;
    }

    code {
        @extend %code-text;
    }

    pre {
        @extend %code-text;
        margin-left: 20px;
    }
}

footer {
    @extend %code-text;
}
```

What I try to achieve here is alter the %code-text in the article scope to extend with a color for later use. Later in the code I wanted to extend footer with %code-text, obviously without the color.
This is the compiled output:

``` CSS
article code, article pre, footer {
  font: 12px monospace; }

article code, article pre, article footer {
  color: #177fb7; }
article pre {
  margin-left: 20px; }
```

If you look closely, you can see there is strange selector: article footer. It's definitely  generated because of "scoped" placeholder selector.
Although the result works as it's expected, I'm not sure it's because of it has to do as I wanted or because of a bug.
