### ISSUE TITLE
Parsing bug placeholder referencing placeholder

### ISSUE THREAD

**Issue by jslegers** [sass/sass#856]
Consider the following code :

``` scss
%padding-4px {
  padding:4px;
}

%padding-none {
  padding:0;
}

%border-init {
  border:0 solid #ccc;
}

%border-1px {
  border-width:1px;
}

%border-init-1px {
  @extend %border-init;
  @extend %border-1px;
}

input {
  @extend %border-init-1px;
  @extend %padding-4px;
}

table {
  & {
    @extend %border-init;
  }

  & input {
    @extend %border-init;
    @extend %padding-none;
  }
}
```

It correctly generates the following result :

``` css
input {
  padding: 4px; }

table input {
  padding: 0; }

input, table, table input {
  border: 0 solid #ccc; }

input {
  border-width: 1px; }
```

Now, let's abstract away the "table" code into a separate module :

``` scss
%padding-4px {
  padding:4px;
}

%padding-none {
  padding:0;
}

%border-init {
  border:0 solid #ccc;
}

%border-1px {
  border-width:1px;
}

%border-init-1px {
  @extend %border-init;
  @extend %border-1px;
}

input {
  @extend %border-init-1px;
  @extend %padding-4px;
}

%component-table {
  & {
    @extend %border-init;
  }

  & input {
    @extend %border-init;
    @extend %padding-none;
  }
}

table {
  @extend %component-table;
}
```

If we now look at the result, we see that the padding for "table input" was correctly processed but the border-initialisation is skipped :

``` css
input {
  padding: 4px; }

table input {
  padding: 0; }

input, table {
  border: 0 solid #ccc; }

input {
  border-width: 1px; }
```
