### ISSUE TITLE
Confusing @import @extend %ruleset behavior

### ISSUE THREAD

**Issue by srcspider** [sass/sass#869]
_Some basic context: I came across this while trying to split the rules applied from the selectors by writing rules in a separate assets folder under %selectors and the actual selectors in an equity folder that mirrors the site page structure._

Sass 3.3.0.alpha.149 (Bleeding Edge)
Compass 0.12.2.sourcemaps (Alnilam)

To get the new source maps to work I'm combining my files in a single file by importing the relevant pages; and hence my problem.

The issue is that @import'ing %selector multiple times will duplicate the rules even when asking for compressed output. (it's clearer in the example)

Here is a basic example that reproduces the error:

```
/sass
  /rules
     test.scss
  x.scss
  y.scss
  all.scss
```

**test.scss**

``` css
%test {
    color: red;
}
```

**x.scss**

``` css
@import 'rules/test';

.x {
    @extend %test;
}
```

**y.scss**

``` css
@import 'rules/test';

.y {
    @extend %test;
}
```

**all.scss**

``` css
@import 'x';
@import 'y';
```

You will get the following faulty _all.css_

``` css
/* line 1, ../sass/rules/test.scss */
.x, .y {
  color: red;
}

/* line 1, ../sass/rules/test.scss */
.x, .y {
  color: red;
}
```

Expected: single `.x, .y` rule and if I have a rule in a file then no matter what @import structure I use it's still a single rule (since it doesn't make sense to have multiple copies). ie. the following `(%test, test.scss, color, red)` is unique.
