### ISSUE TITLE
Bubble directives that don't contain rules

### ISSUE THREAD

**Issue by srcspider** [sass/sass#870]
_Title edited by @nex3._

**Bug Report Version** (potentially simple fix)

@-webkit-keyframes needs to pop out of selectors. 

Currently it's treated as any other rule.

**Feature Version**

The following may be very desirable for short one-time uses of this particular case.

**example.scss**

``` scss
#x.y {
  .z {
     @-webkit-keyframes test {
        // ...
     }
    .example {-webkit-animation: test 5s infinite}
  }
}
```

**example.css**

``` css
@-webkit-keyframes x-y-z-test {
  /* ... */
}

#x.y .z .example {
  -webkit-animation: x-y-z-test 5s infinite
}
```
