### ISSUE TITLE
@extend should only extend the selector it's in, not the parents as well

### ISSUE THREAD

**Issue by srcspider** [sass/sass#877]
I've looked over other issues, there seems to be only one other issue but it's dealing with css4 ! semantics if I'm not mistaken.

```
.T %test {
    color: red;
}

.a {
    .b {
        @extend %test;
    }
}

.x .y {
    @extend %test;
}
```

Expected:

```
.T .a .b, .T .x .y {
    color: red;
}
```

Actual:

```
.T .a .b, .a .T .b, .T .x .y, .x .T .y {
  color: red;
}
```

**Comment by chriseppstein** [comment]
This is working as expected. I recently wrote up an explanation for why nested selectors work like they do when extended: https://gist.github.com/chriseppstein/6114279 Hopefully it will help you understand things better.

**Comment by srcspider** [comment]
@chriseppstein why doesn't the following generate all the possible selectors?

``` scss
.T {
    .a {
        .T1 & {
            color: red;
        }
        .T2 & {
            color: blue;
        }
    }
}
```

Generated:

``` css
.T1 .T .a {
  color: red;
}
.T2 .T .a {
  color: blue;
}
```

Irony would have it in practice I actually would have liked `.T .T1 .a` in such a context. :)

The use case for the example is when specifying style modifiers/context; 99% of the time I would like it to just use the immediate selector and then place the result in the context of the other selectors.

**Comment by jslegers** [comment]
@srcspider :

I also don't think it makes sense how your initial example is compiled.

Still, I prefer to use plain placeholders that don't have any ancestor elements. I also prefer to nest descendant elements into ancestor elements rather than the other way around. That way, your code is more readable and don't have the problem you're describing. Consider the following code as alternative implementations of your use cases.

CASE 1 : 

```
INPUT
```

``` scss
%test {
    color: red;
}

.T  {
    & .a {
        & .b {
            @extend %test;
        }
    }
    & .x {
        & .y {
            @extend %test;
        }
    }
}

```

```
OUTPUT
```

``` css
.T .a .b, .T .x .y {
    color: red;
}
```

CASE 2 :

```
INPUT
```

``` scss
.T {
    & .T1 {
        & .a {
            color: red;
        }
    }
    & .T2 {
        & .a {
            color: blue;
        }
    }
}

```

```
OUTPUT
```

``` css
.T .T1 .a {
  color: red;
}
.T .T2 .a {
  color: blue;
}
```

**Comment by jslegers** [comment]
@srcspider :

Personally, I very much like using the following design pattern. It might be useful for your use cases as well.

```
INPUT
```

``` scss

//Primitives
// -------------------

%color-red {
    color: red;
}

%color-blue {
    color: blue;
}

%font-24 {
    font-size: 24px;
    line-height: 24px;
}

%font-30 {
    font-size: 30px;
    line-height: 30px;
}

// Components
// -------------------

%layout1 {
    a {
        @extend %color-red;
    }

    h2 {
        @extend %font-30;
    }
}

%layout2 {
    a {
        @extend %color-blue;
    }

    h2 {
        @extend %font-24;
    }
}

%layout3 {
    a {
        @extend %color-blue;
    }

    h2 {
        @extend %font-30;
    }
}

// Selectors
// -------------------

.block {
    .layout1 {
        @extend %layout1;   
    }

    .layout2 {
        @extend %layout2;   
    }

    .layout3 {
        @extend %layout3;   
    }
}
```

```
OUTPUT
```

``` css
.block .layout1 a {
  color: red;
}

.block .layout2 a, .block .layout3 a {
  color: blue;
}

.block .layout2 h2 {
  font-size: 24px;
  line-height: 24px;
}

.block .layout1 h2, .block .layout3 h2 {
  font-size: 30px;
  line-height: 30px;
}
```
