### ISSUE TITLE
Compound selectors and @extend behavior change since 3.2.7

### ISSUE THREAD

**Issue by ghost** [sass/sass#878]
This worked on 3.2.7, but since 3.2.8 through 3.2.10, it behaves differently. ( _I didn't actually test 3.2.9_ )

```
@mixin alpha { alpha: "hello"; }
%alpha { @include alpha; }

@mixin omega {
    &:after {
        @extend %alpha;
        omega: "world";
    }
}
%omega { @include omega; }

.alpha-omega-1 {
    @extend %alpha;
    @extend %omega;
}
.alpha-omega-2 {
    @extend %alpha;
    @extend %omega;
}
```

The _expected_ result is:

```
.alpha-omega-1, .alpha-omega-2, 
.alpha-omega-1:after, .alpha-omega-2:after { alpha: "hello"; }

.alpha-omega-1:after, .alpha-omega-2:after { omega: "world"; }
```

But the _actual_ result is:

```
.alpha-omega-1, .alpha-omega-2 { alpha: "hello"; }

.alpha-omega-1:after, .alpha-omega-2:after { omega: "world"; }
```

Note that the `:after` selectors aren't extended to include the `alpha: "hello";` property. Of course, I could just `@include alpha` in the omega `@mixin`, however that changes the grouping; and besides, this _should_ work so far as I can tell.

I don't know what your position is on the correct behavior here, so perhaps this is behaving expectedly, but I can't imagine that it is.

Just to clarify, the reason for both the `@mixin` and `%rule` is I use the `%rule` in the current media scope, and redefine it using the `@mixin` in different media scopes.

**Comment by chriseppstein** [comment]
This is a real bug. The mixins are not required to reproduce it:

``` scss
%alpha { alpha: "hello"; }

%omega:after { 
        @extend %alpha;
        omega: "world";
}

.alpha-omega-1 {
    @extend %alpha;
    @extend %omega;
}
.alpha-omega-2 {
    @extend %alpha;
    @extend %omega;
}
```

Produces:

``` css
.alpha-omega-1, .alpha-omega-2 {
  alpha: "hello"; }

.alpha-omega-1:after, .alpha-omega-2:after {
  omega: "world"; }
```

But should produce:

``` css
.alpha-omega-1, .alpha-omega-2, 
.alpha-omega-1:after, .alpha-omega-2:after { alpha: "hello"; }

.alpha-omega-1:after, .alpha-omega-2:after { omega: "world"; }
```

Note that

``` scss
%alpha { alpha: "hello"; }

%omega a { 
        @extend %alpha;
        omega: "world";
}

.alpha-omega-1 {
    @extend %alpha;
    @extend %omega;
}
.alpha-omega-2 {
    @extend %alpha;
    @extend %omega;
}
```

produces

``` css
.alpha-omega-1 a, .alpha-omega-2 a, .alpha-omega-1, .alpha-omega-2 {
  alpha: "hello"; }

.alpha-omega-1 a, .alpha-omega-2 a {
  omega: "world"; }
```

as expected. But even a class attached to the main placeholder is failing:

``` scss
%alpha { alpha: "hello"; }

%omega.foo { 
        @extend %alpha;
        omega: "world";
}

.alpha-omega-1 {
    @extend %alpha;
    @extend %omega;
}
.alpha-omega-2 {
    @extend %alpha;
    @extend %omega;
}
```
