### ISSUE TITLE
Arglist - create or modify (apply)

### ISSUE THREAD

**Issue by jakob-e** [sass/sass#880]
Is it possible to create or modify an existing **arglist**?
What I'm looking for is something similar to javascript **apply**:

``` SCSS

$list:a,b,c,d;

@mixin myMixin($args...){ }
@include myMixin:apply(null, $list); 


@function myFunction($args...){ }
$value:myFunction:apply(null, $list); 

```

Best,
Jakob E
