### ISSUE TITLE
sass-convert color hex formatting inconsistencies  

### ISSUE THREAD

**Issue by badsyntax** [sass/sass#886]
Hi there

I'm using sass-convert v3.2.9, and am converting a CSS file to SCSS, and I've noticed some inconsistencies with how color hex codes are formatted.

For example, I have the following CSS:

``` css
.module {
    font: arial;
}
.module .title {
    background: #aaa url("image.jpg");
    color: #aaa;
}
```

I use sass-convert to convert to scss (`sass-convert --to scss test.css`), which results in:

``` scss
.module {
  font: arial;
  .title {
    background: #aaaaaa url("image.jpg");
    color: #aaa;
  }
}
```

(Note the background property hex code and compare to the color property hex code.)

Whereas, if I convert the following CSS:

``` css
.module {
    font: arial;
}
.module .title {
    background: #aaa;
    color: #aaa;
}
```

I get the following scss:

``` scss
.module {
  font: arial;
  .title {
    background: #aaa;
    color: #aaa;
  }
}
```

So this doesn't make a lot of sense to me, it would be great if this was consistent. 

To be honest, I wish there were some options available to control how color hex codes are formatted when converting.

Thank you for your time reading this and for creating a great and useful tool.
