### ISSUE TITLE
descendant selector + ‘@extend’ with ‘&’ parent reference compiles inaccurate selector

### ISSUE THREAD

**Issue by yoannisj** [sass/sass#892]
Sass (version 3.2.10) outputs additional and inaccurate selectors when a _descendant selector_ ( **.parent .child** ) uses **@extend** to extend another selector or silent selector that uses _parent selector references_ ( **&** sign).

example :

``` scss
%browser-color
{
    color: blue;

    .lt-ie8 & {
        color: red;
    }
}

.dialog .browser
{
    @extend %browser-color;
}
```

compiles into :

``` css
.dialog .browser
{
    color: blue;
}

.lt-ie8 .dialog .browser, .dialog .lt-ie8 .browser
{
    color: red;
}
```

while the expected result is :

``` css
.dialog .browser
{
    color: blue;
}

.lt-ie8 .dialog .browser
{
    color: red;
}
```

The bug doesn't happen when the _extending_ selector is a child selector (.parent > .child), nor when the _extended_ selector makes no use of the ‘&’ sign.
