### ISSUE TITLE
Split css into serveral files

### ISSUE THREAD

**Issue by fuddl** [sass/sass#893]
I use sass to create a huge amount of different color schemes. Maybe my problem is too specific or you have a better idea how to do this. but here's what I do:
## What I have

first i create a list of (I call it) schemes

``` css

@function scheme-list() {
  @return blue, teal, darkred, darkorchid, sand, orange, water;
}

```

after I define colors and a default color

``` css

@function color-list() {
  @return medium, light;
}

$default-scheme: blue;
```

then I create a function that returns a specific color for a give scheme and shade. (what could be done better with associative arrays) 

``` css
// Returns a color for each scheme in a defined shade. New schemes have to be
// defined here.

@function scheme-color($scheme: blue, $color: medium) {
  @if $scheme == blue   {
    @if $color == medium {    @return #005aaa;   }
    @if $color == light  {    @return #005aaa;   }
  }
  @if $scheme == teal {
    @if $color == medium {    @return #0aa5a0;   }
    @if $color == light  {    @return #005aaa;   }
  }
  @if $scheme == darkred {
    @if $color == medium {    @return #af2d2d;   }
    @if $color == light  {    @return #005aaa;   }
  }
  @if $scheme == darkorchid {
    @if $color == medium {    @return #AABF70;   }
    @if $color == light  {    @return #005aaa;   }
  }
  @if $scheme == sand   {
    @if $color == medium {   @return #d7c498;    }
    @if $color == light  {    @return #005aaa;   }
  }
  @if $scheme == orange   {
    @if $color == medium {    @return #faa503;   }
    @if $color == light  {    @return #005aaa;   }
  }
}

```

after I define every property with every scheme and color with a <code>%</code>-Selector

``` css
@each $scheme in scheme-list() {
  /* BEGINN {$scheme} */
  @each $color in color-list() {
    %color-scheme-#{$scheme}-#{$color} {
      color: scheme-color($scheme, $color);
    }
    %background-color-scheme-#{$scheme}-#{$color} {
      background-color: scheme-color($scheme, $color);
    }
    %border-color-scheme-#{$scheme}-#{$color} {
      border-color: scheme-color($scheme, $color);
    }
  }
  /* END #{$scheme} */
}

```

and for each of these properties I create also a mixin (this is for the background-color) which does nothing more then extending the <code>%</code>-selector adding a prefix (which I will use as a class in the `<body>`-element later.

``` css
@mixin background-color-scheme($color) {
  @extend %background-color-scheme-#{$default-scheme}-#{$color};
  @each $scheme in scheme-list() {
    @if($scheme != $default-scheme) {
      .scheme-#{$scheme} & {
        @extend %background-color-scheme-#{$scheme}-#{$color};
      }
    }
  }
};

```

after whenever I want an object to respect the color rules of my current scheme I use these mixins:

``` css

.button,
.form-submit {
  color: white;
  @include background-color-scheme(dark);
  padding: .5em 1em;
  border: {
    width:4px;
    style:solid;
  }
  background-clip: padding-box;
  @include border-color-scheme(darker);
  transition: all .3s ease-in-out;
  &:hover {
    @include background-color-scheme(light);
    @include border-color-scheme(medium);
  }
}

```
## The Result

this gets me a lot of code like this:

``` css
/* BEGINN darkred */
.scheme-darkred a, .scheme-darkred #page-title {
  color: #af2d2d;
}

.scheme-darkred .links > li:before, .scheme-darkred
.action-links > li:before, .scheme-darkred #breadcrumb, .scheme-darkred .button, .scheme-darkred
.form-submit {
  background-color: #af2d2d;
}

.scheme-darkred .button:hover, .scheme-darkred
.form-submit:hover {
  border-color: #af2d2d;
}

.scheme-darkred .button:hover, .scheme-darkred
.form-submit:hover {
  background-color: rgba(175, 45, 45, 0.5);
}

.scheme-darkred .links > li:before, .scheme-darkred
.action-links > li:before, .scheme-darkred .button, .scheme-darkred
.form-submit {
  border-color: rgba(175, 45, 45, 0.5);
}

.scheme-darkred a:hover {
  color: #d79696;
}

.scheme-darkred #main-wrapper {
  background-color: #d79696;
}

/* END darkred */
/* BEGINN darkorchid */
.scheme-darkorchid a, .scheme-darkorchid #page-title {
  color: #aabf70;
}

.scheme-darkorchid .links > li:before, .scheme-darkorchid
.action-links > li:before, .scheme-darkorchid #breadcrumb, .scheme-darkorchid .button, .scheme-darkorchid
.form-submit {
  background-color: #aabf70;
}

.scheme-darkorchid .button:hover, .scheme-darkorchid
.form-submit:hover {
  border-color: #aabf70;
}

.scheme-darkorchid .button:hover, .scheme-darkorchid
.form-submit:hover {
  background-color: rgba(170, 191, 112, 0.5);
}

.scheme-darkorchid .links > li:before, .scheme-darkorchid
.action-links > li:before, .scheme-darkorchid .button, .scheme-darkorchid
.form-submit {
  border-color: rgba(170, 191, 112, 0.5);
}

.scheme-darkorchid a:hover {
  color: #d4dfb7;
}

.scheme-darkorchid #main-wrapper {
  background-color: #d4dfb7;
}

/* END darkorchid */
```
## What I don't like

First of I would love to get rid of this `.scheme-[name]`-prefixes.
To do this I would like to put the different schemes into a seperate css files instead.

someone else brought that up [here](https://github.com/nex3/sass/issues/816). 

the syntax for splitting files could look like this:

``` css
@each $scheme in scheme-list() {
  @put-into-file('scheme-#{$scheme}.css') {
    @each $color in color-list() {
      %color-scheme-#{$scheme}-#{$color} {
        color: scheme-color($scheme, $color);
      }
      %background-color-scheme-#{$scheme}-#{$color} {
        background-color: scheme-color($scheme, $color);
      }
      %border-color-scheme-#{$scheme}-#{$color} {
        border-color: scheme-color($scheme, $color);
      }
    }
  }
}

```

what do you think?
