### ISSUE TITLE
Wrong parsing of Sass code when comments are combined with selectors (works well with SCSS)

### ISSUE THREAD

**Issue by hagenburger** [sass/sass#902]
Sass input (broken):

``` sass
.class-1, // a comment
.class-2,
.class-3
  color: black
```

Output:

``` css
WARNING on line 1 of test.sass:
This selector doesn't have any properties and will not be rendered.
.class-2,
.class-3 {
  color: black; }
```

SCSS input (works fine):

``` scss
.class-1, // a comment
.class-2,
.class-3 {
  color: black;
}
```

Output:

``` css
.class-1,
.class-2,
.class-3 {
  color: black; }
```

Sass 3.2.10, Ruby 2.0.0
