### ISSUE TITLE
return values of functions stored in variables.

### ISSUE THREAD

**Issue by lifeiscontent** [sass/sass#909]
``` scss
$navigationBarTextShadow: 0 -1px 0 colorOpacity($primaryBlack, 0.15);
```

I just tried this and the color function I made won't store new color value to the variable, is the expected behavior?

**Comment by nex3** [comment]
I'm not sure what you're asking. What's the definition of `colorOpacity`? What results are you seeing? What results are you expecting?

**Comment by lifeiscontent** [comment]
@nex3 

the source of `colorOpacity` looks like this

``` scss
@function colorOpacity($color, $opacity) {
  @return transparentize($color, 1 - $opacity);
}
```

I'm expecting

``` scss
body {
  box-shadow: $navigationBarTextShadow;
}
```

output: 

``` css
body {
  box-shadow: 0 -1px 0 rgba(0,0,0,0.15);
}
```

**Comment by nex3** [comment]
That's the output I get when I run your code with `$primaryBlack` set to `#000`.

**Comment by lifeiscontent** [comment]
hmm... thats odd.

I'm using version `3.2.9` and I get

``` css
body {
  box-shadow: 0 -1px 0 colorOpacity(#000, 0.15);
}
```
