### ISSUE TITLE
[wishlist] add color grouping while CSS to SCSS decompile

### ISSUE THREAD

**Issue by jpka-** [sass/sass#910]
Hi! I have CSS files with multiple instances of same colour value. I run _sass-convert style.css style.scss_ . Is there any possibility in future to automatically grouping all the same color value instances and represent at beginning of decompiled SCSS file as variables like in documentation:

``` scss
$blue: #3bbfce;

$content_navigation {
  border-color: $blue;
  another-color: $blue;
}
```

Thank you so much!
