### ISSUE TITLE
Linear inheritance

### ISSUE THREAD

**Issue by zslabs** [sass/sass#912]
Hi all,
I'll start off by saying I do understand LESS and SASS are completely different, but it is something I was interested in getting clarification on.

I noticed in LESS that you can include mixins before they are defined, like so:

```
.panel {
    padding: 15px;
    background: #fafafa;
    color: #666;
    border: 1px solid #e5e5e5;
    border-radius: 4px;
    .hook-panel;
}
.hook-panel() {
    font-weight:bold;
}
```

but you cannot do the same in SASS:

```
.panel {
    padding: 15px;
    background: #fafafa;
    color: #666;
    border: 1px solid #e5e5e5;
    border-radius: 4px;
    @include hook-panel();
}
@mixin hook-panel() {
    font-weight:bold;
}
```

So, it seems like SASS uses linear inheritance for something like this. The odd thing is it actually does work using placeholders:

```
.panel {
    padding: 15px;
    background: #fafafa;
    color: #666;
    border: 1px solid #e5e5e5;
    border-radius: 4px;
    @extend %hook-panel;
}
%hook-panel {
    font-weight:bold;
}
```

The reason I'm bringing this up is it seems the only way to plug into a selector (and not duplicate the selector by using something like a placeholder) is to define/use your mixins before including them (which may be separate from your other styles). Aside from the "micro-optimizing" point of view, I do believe it's a valid concern. Would love to get some ideas brewing. Thanks!

**Comment by Snugug** [comment]
I believe where some of the confusion may come from the fact that Sass has clearly defined mixins and extendables with different purposes whereas LESS doesn't make that distinction. In Sass, `@extend` is used for moving a copy of the selector to a new place in the cascade and comma-separating it with what it is extending. This allows for moving both up and down the cascade. `@mixin`, on the other hand, behaves like a function that "returns" properties. In LESS, there is no good comparison with what `@extend` does, and guards help to confuse the point further (there are proper [control directives](http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html#control_directives) in Sass) as they allow you to define the same mixin multiple times with different outcomes. In Sass, you would only create a single mixin and use control directives to direct it's output.

As for linear inheritance, this exists because in Sass, you can override existing mixins with new mixins, say overriding the `clearfix` mixin that comes with [Compass](http://compass-style.org/) with your own custom one. If a mixin could come from anywhere, it would be very hard to figure out exactly which one you want. This same linear inheritance doesn't exist for extendables again because of their nature of moving selectors around the cascade. 

Hope this helps.

**Comment by zslabs** [comment]
Definitely helps me understand a bit more. So it sounds like I'm better off just duplicating the selector to elements as there isn't a way to create "pluggable" areas that can be created after the fact, correct? As another example, I was almost thinking about how WordPress has `do_action()` calls, which basically says (do nothing unless you see a function that plugs into this before/after the final code is parsed by WordPress). Thanks.

**Comment by Snugug** [comment]
I don't entirely follow the usefulness of what you're trying to do in a system that boils down to raw CSS. Do you have a real-world example?

**Comment by zslabs** [comment]
So the LESS example above would compile to:

```
.panel {
    padding: 15px;
    background: #fafafa;
    color: #666;
    border: 1px solid #e5e5e5;
    border-radius: 4px;
    font-weight:bold;
}
```

While the placeholder equivalent in SASS would be:

```
.panel {
    padding: 15px;
    background: #fafafa;
    color: #666;
    border: 1px solid #e5e5e5;
    border-radius: 4px;
}

.panel {
    font-weight:bold;
}
```

With mixins (if I declared/used it before it was included) I'd be fine, but my end-goal was to make a pluggable area that wouldn't create additional selectors. Ideally we could keep our customizations (or our "hooks") with our other app SASS code in one file. Thanks.

**Comment by Snugug** [comment]
There is no way to make a hook system in Sass, but I still don't totally understand why this can't be accomplished with how mixins work now.

``` scss
@mixin bold-font {
    font-weight: bold;
}


.panel {
    padding: 15px;
    background: #fafafa;
    color: #666;
    border: 1px solid #e5e5e5;
    border-radius: 4px;
    @include bold-font;
}
```

You simply need to move the mixin declaration from after you want to use it to before. The real power in the separation of the concept of mixins and extendables that Sass makes and LESS doesn't is using the same mixin/extendable multiple times:

``` scss
@mixin bold-font {
    font-wieght: bold;
}

%italic-font {
    font-style: italic;
}

.panel {
    padding: 15px;
    background: #fafafa;
    @include bold-font;
    @extend %italic-font;
}

.block {
    padding: 20px;
    background: #060606;
    @include bold-font;
    @extend %italic-font;
}
```

This compiles to the following:

``` css
.panel, .block {
    font-style: italic;
}

.panel {
    padding: 15px;
    background: #fafafa;
    font-weight: bold;
}

.block {
    padding: 20px;
    background: #060606;
    font-weight: bold;
}
```

Notice how mixins and extendables behave differently? Mixins in Sass do exactly what they do in LESS, with the exception that they need to be declared before they're used. Extendables do something totally different. What are you actually trying to accomplish? Having a user be able to change default values of a mixin before it gets used? If so, set a globally scoped variable to a value with default, something like this:

``` scss
$font-weight: bold !default;
@mixin bold-font {
    font-weight: $font-weight;
}


$font-weight: 500;

.foo {
    @include bold-font;
}
```

This will compile to the following:

``` css
.foo {
  font-weight: 500;
}
```

Simply set the global variable to what you want before you use the mixin and it'll pick up that variable and use that. This is a pattern I use fairly extensively in [Toolkit](https://github.com/team-sass/toolkit)
