### ISSUE TITLE
Extending within the @media directive

### ISSUE THREAD

**Issue by jakob-e** [sass/sass#915]
## Extending within the @media directive

As this topic seems to pop-up quite often I decided to see if I could make it work 
without having to bother nex3 and all you other champs more than I've already done.  

Here is what I came up with:
_Please comment :)_

Best, 
Jakob E

**Note!** mediaExtend causes deprecation warning
mediaExtend Back-to-Hack-Edition added below
### Mixins and config

``` SCSS
// ====================================================================
// Breakpoints
// Define a global list of breakpoints
// (key, min-width, max-width),...
// Note! zero will omit the query
// ==================================================================== 
$breakpoints: 
     (all,0,0)
    ,(desktop,769,0)
    ,(tablet,481,768)
    ,(mobile,0,480);


// ====================================================================
// Media
// Prints out a media query from the breakpoints list 
// ==================================================================== 
@mixin media($key){ // @content
    $bp:null;
    @for $i from 1 through length($breakpoints){
        $item:nth($breakpoints,$i);
        @if(nth($item,1)==$key){ $bp:$item; }
    }
    $min:nth($bp,2) * 1px; 
    $max:nth($bp,3) * 1px;
    $mq:'screen and (min-width:'+$min+') and (max-width:'+$max+')'; 
    @if($min and $max==0px){ $mq:'screen and (min-width:'+$min+')'; }
    @if($min==0px and $max){ $mq:'screen and (max-width:'+$max+')'; }
    @if($min==0px and $max==0px){ $mq:'all'; }
    @media #{unquote($mq)}{ @content; }
}


// ==================================================================== 
// MediaExtend
// Places each extend within the each media directive of the breakpoint list
// ==================================================================== 
@mixin mediaExtend(){ // @content
    @for $i from 1 through length($breakpoints){
        $key:nth(nth($breakpoints,$i),1);
        @include media($key){ @content; };
    }
}


```
### How to use

``` SCSS

// ==================================================================== 
// Create the media extends.
// ... to test the output just add a regular extend
// @include mediaExtend(){ .test{ content:'test'}}
// 
@include mediaExtend(){
    %red { color:red; }
    %blue { color:blue; }
    %green { color:green; }
    %yellow { color:yellow; }
}


// ==================================================================== 
// Using media as wrapper 
//
@include media(all){
  .foo { @extend %red; }
  .bar { @extend %blue; }
}
@include media(mobile){
  .foo { @extend %blue; }
  .bar { @extend %yellow; }
}
@include media(tablet){
  .foo { @extend %green; }
  .bar { @extend %green; }
}

// CSS Output
// @media all {
//   .foo { color: red; }
//   .bar { color: blue; }
// }
// @media screen and (min-width: 481px) and (max-width: 768px) {
//   .foo, .bar { color: green; }
// }
// @media screen and (max-width: 480px) {
//   .foo { color: blue; }
//   .bar { color: yellow; }
// }


// ==================================================================== 
// Wrapping media
// 
.foo { @include media(tablet){ @extend %green } }
.bar { @include media(tablet){ @extend %green } }

// CSS Output
@media screen and (min-width: 481px) and (max-width: 768px) {
  .foo, .bar {  color: green; }
}


// --------------------------
// Note! when passing non-media-extend @content to the media mixin
//  - CSS Output order is set by the include order  not the order 
// of the breakpoints list... Be careful if your list contains
// overlapping breakpoints
// 
.foo { @include media(tablet){ content:'tablet'; } }
.foo { @include media(mobile){ content:'mobile'; } }
.foo { @include media(all)   { content:'all';    } }

// CSS Output
// @media screen and (min-width: 481px) and (max-width: 768px) {
//   .foo { content: 'tablet'; }
// }
// @media screen and (max-width: 480px) {
//   .foo { content: 'mobile'; }
// }
// @media all {
//   .foo { content: 'all';  }
// }


```
### mediaExtend Back-to-Hack-Edition

While the mediaExtend solution above was **nice** and **clean** and **made perfect sense**
it will cause a deprecation warning (crashed CodeKit) - **sucks big time!!!!**

It looks as if we are still allowed to extend within the media directive as long as there are
no naming conflicts with other extends. This solution uses a media prefix to create a 
sort of namespace. In no way as flexible, intuitive or as simple as the first version. 

**Note!** the breakpoints list and media mixin remains the same  

``` SCSS

// ==================================================================== 
// mediaExtend  
// ==================================================================== 
// Prevent multiple instantiations
$media-extend-first-run:true !default;
@mixin mediaExtend($args...){ 

    // Arguments passed => extend
    @if(length($args)>0){
        // Loop thru arguments to see if any matches a key in the breakpoints list 
        // - if found add to keys list
        $keys:();
        @for $i from 1 through length($args){
            @for $j from 1 through length($breakpoints){
                @if(nth(nth($breakpoints,$j),1)==nth($args,$i)){ 
                    $keys:append($keys,nth($args,$i)); 
                }
            }
        }
        // If no breakpoints were passed we'll extend all items in the breakpoints list. 
        // Note! if extending within context scope must match
        // @media all {
        //     @include mediaExtend(all, foo){ .... }
        // }
        $keys:if($keys==(),$breakpoints,$keys);
        @for $i from 1 through length($args){
            @for $j from 1 through length($keys){
                $key:nth(nth($keys,$j),1);
                @extend %#{$key+'_'+ nth($args,$i)} 
            }
        }  
    }

    // No arguments => create extends 
    @else if $media-extend-first-run {
        $media-extend-first-run:false;
        // Loop thru breakpoints
        @for $i from 1 through length($breakpoints){
            $key:nth(nth($breakpoints,$i),1);
            // 1 Place extends within a media scope
            // 2 Prefix extends to avoid conflicts
            @include media($key){
                // ==================================
                // Add your all your extends here 
                // %#{$key+_+ EXTEND_NAME }{ ... }
                // ==================================       

                %#{$key+_+ foo }{ content:'foo'; }
                %#{$key+_+ bar }{ content:'bar'; }
                %#{$key+_+ doh }{ content:'doh'; }

            }
        }
    } 
}
@include mediaExtend(); // Create extends


// ==================================================================== 
// Usage 
// Instad of using @extend %foo we use the mediaExtend to handle the prefixing.
// ==================================================================== 


// -----------------------------------------------------------
// Example 1
// Calling without a scope (extend it all)
.myClass{ @include mediaExtend(foo); }

// CSS Output 
@media all { .myClass { content: 'foo'; } }
@media screen and (min-width: 769px) { .myClass { content: 'foo'; } }
@media screen and (min-width: 481px) and (max-width: 768px) { .myClass { content: 'foo'; } }
@media screen and (max-width: 480px) { .myClass { content: 'foo'; } }


// -----------------------------------------------------------
// Example 2 
// Passing one scope 
.myClass{ @include mediaExtend(mobile, foo); }

// CSS Output
@media screen and (max-width: 480px) { .myClass { content: 'foo'; } }


// -----------------------------------------------------------
// Example 3 
// Passing multiple scopes
.myClass{ @include mediaExtend(mobile, tablet, foo); }

// CSS Output
@media screen and (min-width: 481px) and (max-width: 768px) { .myClass { content: 'foo'; } }
@media screen and (max-width: 480px) { .myClass { content: 'foo'; } }


// -----------------------------------------------------------
// Example 4
// Passing multiple scopes and extends 
.myClass{ @include mediaExtend(mobile, tablet, foo, bar); }

// CSS Output
@media screen and (min-width: 481px) and (max-width: 768px) { 
    .myClass { content: 'foo'; }
    .myClass { content: 'bar'; } 
}
@media screen and (max-width: 480px) { 
    .myClass { content: 'foo'; }
    .myClass { content: 'bar'; } 
}


// -----------------------------------------------------------
// Example 5 
// Extending within context
@media all {
    .myClass{ @include mediaExtend(all, foo); }
}

// CSS Output 
@media all { .myClass { content: 'foo'; } }


// -----------------------------------------------------------
// Example 6
// Extending within context - using media mixin
@include media(all) {
    .myClass{ @include mediaExtend(all, foo); }
}

// CSS Output 
@media all { .myClass { content: 'foo'; } }


// -----------------------------------------------------------
// Example 7 - Error
// Extending within wrong context
@media all {
    .myClass{ @include mediaExtend(mobile, foo); }
}

// No CSS Output


```
### Constants

Just a small might-be-of-some-use note - use constants

``` SCSS

$MEDIA_ALL:all;
$MEDIA_DESKTOP:desktop;
$MEDIA_TABLET:tablet;
$MEDIA_MOBILE:mobile;

$breakpoints: 
     ($MEDIA_ALL,0,0)
    ,($MEDIA_DESKTOP,769,0)
    ,($MEDIA_TABLET,481,768)
    ,($MEDIA_MOBILE,0,480);

@include media($MEDIA_ALL){ .... }
@include mediaExtend($MEDIA_ALL){ ... }

```

**Comment by lunelson** [comment]
Interesting approach using `media(all)`, to limit the scope of extension, for declarations that one would otherwise write without any media query.. `@extend` can otherwise be a bit problematic in this way, as it neither strictly obeys query scope nor source order, so that's a useful technique.

**Comment by jakob-e** [comment]
Thanks :) - media all was required to ensure the right CSS output order.

**Comment by nex3** [comment]
This isn't really an issue...

**Comment by jakob-e** [comment]
Update! mediaExtend Back-to-Hack-Edition  

And that dosn't work either :(

**Comment by jslegers** [comment]
@jakob-e & @lunelson :

You might want to try my implementation below. IMO it's one of the more readable solutions for dynamic placeholders both outside media queries and inside media queries and results in a pretty optimised CSS output.

Note, however, that you'll need Sass 3.3 for this to work. Also, you still get the repetition of the `@media` statement (which is hard to avoid unless you use a more complex architecture). 

## Configuration

``` scss
// Configuration :
// -----------------------------------------

$default-media-query : 'default';
$screensizes : (
  'default' : 0 infinity,
  'mobile' : 0 767px,
  'phone' : 0 480px,
  'tablet' : 481px 767px,
  'desktop' : 768px 979px,
  'widescreen' : 1200px infinity
);
```

---

## String functions

``` scss
// Adding some missing string functions :
// -----------------------------------------

@function str-replace($string, $old, $new : '') {
    @if type-of($string) != string {
        $string : '' + $string;
    } 
    $index: str-index($string, $old);
    @while $index and $index > 0 {
        $temp : $string;
        $string : $new;
        @if $index > 1 {
            $string : str-slice($temp, 1, $index - 1) + $string;
        }
        @if $index < str-length($string) {
            $string : $string + str-slice($temp, $index + 1);
        }
        $index: str-index($string, $old);
    }
    @return $string;
}

@function str-clean($string, $dreplacements: (
        '%' : '-perc-',
        '(' : '-l-b-',
        ')' : '-r-r-',
        '/' : '-ps-',
        '"' : '-dq-',
        "'" : '-sq-',
        '.' : '-dot-',
        ' ' : '-nbsp-'
    )) {
    @each $old, $new in $dreplacements {
        $string : str-replace($string, $old, $new);
    }
    @return $string;
}
```

---

## The magic

``` scss
// The 'magic' :
// -----------------------------------------

$dynamic-placeholders: ();
$current-media-query : $default-media-query;

@mixin generate-root-placeholder($placeholder, $styles) {
    @at-root %#{$placeholder} {
        @each $rule, $style in $styles {
            #{$rule}: $style;
        }
    }
    $dynamic-placeholders: append($dynamic-placeholders, $placeholder) !global;
}

@mixin extend-root-placeholder($placeholder) {
    @extend %#{$placeholder} !optional;
}

@mixin rules($styles) {
    @each $rule, $style in $styles {
        $value : str-clean($style);
        $placeholder : #{$current-media-query}-cascade-#{$rule}-#{$value};
        @if not index($dynamic-placeholders, $placeholder) {
            @include generate-root-placeholder($placeholder, ($rule : $style));
        }
        @include extend-root-placeholder($placeholder);
    }
}

@mixin ruleset($styles) {
    $placeholder : #{$current-media-query}-cascade;
    @each $rule, $style in $styles {
        $value : str-clean($style);
        $placeholder : #{$placeholder}-#{$rule}-#{$value};
    }
    @if not index($dynamic-placeholders, $placeholder) {
        @include generate-root-placeholder($placeholder, $styles);
    }
    @include extend-root-placeholder($placeholder);
}

@mixin respond-to($media) {
    $range : map-get($screensizes, $media);
    @if $range == null {
        @warn 'Unknown screensize "#{$media}" for @mixin respond-to';
    } @else {
        $current-media-query : $media !global;
        $min-width : nth($range, 1);
        $max-width : nth($range, 2);
        @if $min-width > 0 {
            @if $max-width != infinity {
                @media only screen and (min-width: $min-width) and (max-width: $max-width) { @content; }
            } @else {
                @media only screen and (min-width: $min-width) { @content; }
            }
        } @else {
            @if $max-width != infinity {
                @media only screen and (max-width: $max-width) { @content; }
            } @else {
                @content;
            }
        }
        $current-media-query : $default-media-query !global;
    }
}
```

---

## Examples

``` scss
// Examples :
// -----------------

// Basic examples without a media query
.s1 {
  @include rules((
    float : right,
    width : 30%,
    background : #fff,
  ));
}

.s2 {
  @include rules((
    float : right,
    width : 100%,
    background : #000,
  ));
}

.s3 {
  @include rules((
    float : left,
    width : 30%,
    background : #fff,
  ));
}

.s4 {
  @include rules((
    float : left,
    width : 40%,
    background : 'url(image/cool-background.jpg)',
  ));
}

// Here are some examples with media queries
// Note that "respond-to(default)" actually has the
// same impact as not using "respond-to" at all.
// It is actually purely optional.
// I added this feature for the sake of
// readability only.
.s5 {
  @include respond-to(default) {
    @include ruleset((
      float : right,
      width: 100%
    ));
    @include rules((
      background : 'url(image/cool-background.jpg)'
    ));
  }
  @include respond-to(mobile) {
    @include rules((
      width : 40%
    ));
  }
}

.s6 {
    @include respond-to(default) {
        @include rules((
            width: 100%
        ));
    }
    @include respond-to(mobile) {
        @include ruleset((
            float: right,
            width: 300px
        ));
    }
    @include respond-to(desktop) {
        @include rules((
            width: 125px
        ));
    }
    @include respond-to(widescreen) {
        @include rules((
            float: none
        ));
    }
}

.s7 {
    @include respond-to(default) {
        @include rules((
            float: left,
            width: 100%
        ));
    }
    @include respond-to(desktop) {
        @include rules((
            width: 125px
        ));
    }
    @include respond-to(phone) {
        @include ruleset((
            width: 400px
        ));
    }
    @include respond-to(widescreen) {
        @include rules((
            float: none
        ));
    }
}
```

---

## The output

``` css
.s1, .s2 {
  float: right;
}
.s1, .s3 {
  width: 30%;
}
.s1, .s3 {
  background: white;
}

.s2, .s6, .s7 {
  width: 100%;
}
.s2 {
  background: black;
}

.s3, .s4, .s7 {
  float: left;
}

.s4 {
  width: 40%;
}
.s4, .s5 {
  background: "url(image/cool-background.jpg)";
}

.s5 {
  float: right;
  width: 100%;
}
@media only screen and (max-width: 767px) {
  .s5 {
    width: 40%;
  }
}

@media only screen and (max-width: 767px) {
  .s6 {
    float: right;
    width: 300px;
  }
}
@media only screen and (min-width: 768px) and (max-width: 979px) {
  .s6, .s7 {
    width: 125px;
  }
}
@media only screen and (min-width: 1200px) {
  .s6, .s7 {
    float: none;
  }
}

@media only screen and (max-width: 480px) {
  .s7 {
    width: 400px;
  }
}
```

See also https://gist.github.com/jslegers/9805919
