### ISSUE TITLE
placeholder css identifier

### ISSUE THREAD

**Issue by mlarcher** [sass/sass#921]
Would it be possible to have a mechanism that would prepend a default selector that would act as an identifier to the output selectors list of an @extend?

That would help finding out in the debugger what all this list of selectors is about.

I'm thinking something along the lines of : 

``` css
%inlineBlock[#_INLINE_BLOCK] {
    display: inline-block;
    .ltie8 & {
        display: inline;
    }
}
.someClass {
    @extend %inlineBlock;
}
.someOtherClass {
    @extend %inlineBlock;
}
```

which would output

``` css
#_INLINE_BLOCK,
.someClass,
.someOtherClass {
    display: inline-block;
}

.ltie8 #_INLINE_BLOCK,
.ltie8 .someClass,
.ltie8 .someOtherClass {
    display: inline;
}
```

Of course we could directly @extend an id which would do something quite similar, but there are two advantages to the approach I'm suggesting : 
- extending a selector has already proven dangerous because we can easily pollute the output rules inadvertently due to the way @extend works. So keeping the placeholder system is a much safer bet
- more importantly, a placeholder only has existence in the CSS if it is being implemented. Thanks to that, it gets very useful to develop some functionnality snippet libraries in the form of placeholders, and we'd like to be able to keep it this way while still being able to recognize from the debugger what this bunch of selectors represents.
