### ISSUE TITLE
Adding a 100% base to percentage method

### ISSUE THREAD

**Issue by jakob-e** [sass/sass#924]
Adding a 100% base to the percentage method would make it a lot more useful. 

percentage(1, 100) => 1% 
percentage(20, 500) => 4%. 

Allowing units would make it even better 
percentage(20px, 500px) => 4% 

If implemented with a default base of 1 it would be 100% backward compatible ;)

``` SCSS

// Example
@function percentage2($value,$base:1){
    $v:if(unitless($value),$value,$value/($value*0+1));
    $b:if(unitless($base),$base,$base/($base*0+1));
    $p:($v/$b) * 100%;
    @return $p;
}

.percentage { 
    /* Existing percentage method: */
    test1:percentage(1);     

    /* New percentage              */
    /* Default                     */ 
    test2:percentage2(1);         
    /* Adding base                 */  
    test3:percentage2(1,100);   
    /* Units == unitless           */
    test4:percentage2(1px);     
    /* Units + base                */
    test5:percentage2(20px,960px);
    /* Units + unitless base        */ 
    test6:percentage2(20px,500); 
}

// CSS Output
.percentage {
  /* Existing percentage method: */
  test1: 100%;
  /* New percentage              */
  /* Default                     */
  test2: 100%;
  /* Adding base                 */
  test3: 1%;
  /* Units == unitless           */
  test4: 100%;
  /* Units + base                */
  test5: 2.08333%;
  /* Unit + unitless base        */
  test6: 4%;
}


```
