### ISSUE TITLE
Nonsensical error passing keywords as a splat after explicit keywords.

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#926]
``` scss
$adjust-by: (alpha: -10%, "blue": 30%);
.color {c: scale-color($color: purple, $red: -20%, $adjust-by...)};
```

Raises the error:

```
Syntax error: Positional arguments must come before keyword arguments.
```

At the very least, we should have a better error in this case. But the arglist contains only keywords. I think we should allow arglist passing of the form:

``` scss
something(arg1, arg2, $kwarg1: v1, $kwarg2: v2, $positional_args..., $kwargs...)
// or
something(arg1, arg2, $positional_args..., $kwarg1: v1, $kwarg2: v2, $kwargs...)
```
