### ISSUE TITLE
new scriptable `&` can't see parents defined in mixins

### ISSUE THREAD

**Issue by pdaoust** [sass/sass#930]
**Edit**: I've modified this issue because I now believe it all has to do with scriptable `&` rather than `@at-root`, because if you run the code below, the comment at the beginning of the `context` mixin shows that `&` has already lost knowledge of its parent, before `@at-root` is even used.

I've got a snippet of code in the new Sass 3.3 which is giving me a bit of trouble:

``` scss
@mixin question-mark-symbol($selector) {
    #{$selector} {
        /* In the question-mark-symbol mixin, the current context is #{&} */
        @include generated-content-context {
            &::before {
                content: '?';
            }
        }
    }
}

@mixin generated-content-context {
    /* In the context mixin, the current context is #{&} */
    $current-selector: #{&};
    @if $current-selector == "" { $current-selector: "&"; }
    @at-root .generated-content {
        #{$current-selector} {
            @content;
        }
    }
}

/* This (example 1)... */
@include question-mark-symbol('.i-have-a-question-mark');

/* I expected to be the same as this (example 2)... */
.i-have-a-question-mark {
    @include question-mark-symbol('&');
}
```

Output:

``` css
/* This (example 1)... */
.i-have-a-question-mark {
  /* In the question-mark-symbol mixin, the current context is .i-have-a-question-mark */
  /* In the context mixin, the current context is  */ }
  .generated-content::before {
    content: '?'; }

/* I expected to be the same as this (example 2)... */
.i-have-a-question-mark {
  /* In the question-mark-symbol mixin, the current context is .i-have-a-question-mark */
  /* In the context mixin, the current context is .i-have-a-question-mark */ }
  .generated-content .i-have-a-question-mark::before {
    content: '?'; }
```

Apologies for the convoluted code; this is a simplification of a real-life situation.
1. I invoke the `question-mark-symbol` mixin.
2. `question-mark-symbol` creates a rule, using the passed argument as a selector.
3. Inside that rule, it uses a simplification of my `context` mixin (which handles classes on the root element, but in real life also handles `@media` queries and other junk).
4. The `context` mixin outputs the style in a `.generated-content` class (which is a class that some feature-detecting JS puts on the `<html>` element, if you're curious).

The funny thing is that, whenever a rule is created in a mixin and then that mixin calls another mixin, the inner mixin can't see the selector from the previous mixin. I don't know if this is a design choice or a bug, but it was very unexpected to me, because I assumed that a rule was always added to the parent.

**Comment by pdaoust** [comment]
More info: it seems that the tree can normally see rules defined in a mixin, but '#{&}' can't. Check out this even simpler version, with no selectors passed as arguments and no `@at-root` directive:

``` scss
@mixin outer {
    .outer {
        /* In the outer mixin, the current context is #{&} and should be
           p .outer */
        @include inner;
    }
}

@mixin inner {
    /* In the inner mixin, the current context is #{&} and should still be
       p .outer */
    .inner & {
        /* Finally, in the inner mixin's output styles, the context is #{&} and
           should be .inner p .outer */
        color: red;
    }
    @at-root .inner #{&} {
        /* This rule's selector should be indentical to the one above. */
        color: red;
    }
}

p {
    @include outer;
}
```

This gives the output:

``` css
p .outer {
  /* In the outer mixin, the current context is p .outer and should be
     p .outer */
  /* In the inner mixin, the current context is p and should still be
     p .outer */ }
  .inner p .outer {
    /* Finally, in the inner mixin's output styles, the context is .inner p and
       should be .inner p .outer */
    color: red; }
  .inner p {
    /* This rule's selector should be indentical to the one above. */
    color: red; }
```

The `&` remembers the `.outer` selector from the previous mixin, as seen in the `.inner &` selector in the `inner` mixin. However, the `#{&}` in the same inner mixin, in the comment just above the rule, has no knowledge of that same `.outer` selector.
