### ISSUE TITLE
Using a variable within a variable

### ISSUE THREAD

**Issue by AndrejTelle** [sass/sass#933]
Hi,

I am trying to achieve the following:
I define the following variables: 

```
$primary: white;
$text-on-primary: black;
$secondary: blue;
$text-on-secondary: yellow;

@mixin button($var1)
{
background:$var1;
color:$text-on-$var1;
}

.button-primary {@include button($primary);}
.button-secondary {@include button($secondary);}
```

I was hoping that I could pass on a variable within a variable, when setting "color". So that I do not have to define all variables when writing the include segment.

However I get the message:
Syntax error: Undefined variable: "$text-on-"

I also tried using this:

```
color:$text-on-#{$var1};
```

however this also did not work.

Is there any way to achieve variables-names that use existing variables?

**Comment by nex3** [comment]
It's not possible to dynamically construct variable names. However, the master branch and alpha releases support maps, which offer similar functionality. This example could be rewritten as follows to use them:

``` scss
$color-schemes: (
  primary: (
    background: white,
    text: black
  ),
  secondary:
    background: blue,
    text: yellow
  )
);

@mixin button($scheme) {
  $scheme: map-get($color-schemes, $scheme);
  background: map-get($scheme, background);
  color: map-get($scheme, text);
}

.button-primary {@include button($primary)}
.button-secondary {@include button($secondary)}
```
