### ISSUE TITLE
Divide by zero returns Infinity, but it's not a string

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#937]
``` scss
$i: 0;
.wtf {
  wut: 10 / $i;
  the: 10 / $i == Infinity;
  f-ck: 10 / $i == 11 / $i;
}
```

generates:

``` css
.wtf {
  wut: Infinity;
  the: false;
  f-ck: true; }
```

It should raise an error.
