### ISSUE TITLE
Multiple string interpolation

### ISSUE THREAD

**Issue by mohsen1** [sass/sass#944]
I was trying to DRY and use string interpolation in my code but noticed multiple string interpolation is not working.

``` scss
@mixin product-collage{
  position: absolute;
  top: 0;
  left: $copy-wrapper-width;
  width: 1280px - $copy-wrapper-width;

  $book-1-left: 70px;
  $book-1-top: 250px;
  $book-1-rotation: 6deg;
  $book-2-left: 278px;
  $book-2-top: 340px;
  $book-2-rotation: -6deg;
  $book-3-left: 242px;
  $book-3-top: 610px;
  $book-3-rotation: 10deg;
  $magazine-top: 638px;
  $magazine-left: 70px;
  $magazine-rotation: -15deg;

  > .new-product-tile {
    position: absolute;
    /* collage here */
    @each $item in book-1, book-2, book-3, magazine {
      &.#{$item} {
        left: #{#{$item}-left};
        top:  #{#$item}-top};
        @include rotate(#{#{$item}-rotation});
      }
    }
  }
}

.test {
  @include product-collage;
}
```

Am I doing something wrong or Sass is not supporting multiple string interpolation?

**Comment by pdaoust** [comment]
Hi, @mohsen1 . Nested string interpolation works for me, using your example. However, I did notice a typo on one of the lines:

``` scss
top:  #{#$item}-top};
```

should be:

``` scss
top:  #{#{$item}-top};
```

Perhaps that was the cause of your issue?

**Comment by mohsen1** [comment]
@pdaoust Than you for your feedback.

After a lot of refactoring this is how I'm trying to solve this:

``` scss
@mixin product-collage {
  $item-1-left: 70px;
  $item-1-top: 250px;
  $item-1-rotation: 6deg;
  $item-1-z-index: 2;
  $item-2-left: 278px;
  $item-2-top: 340px;
  $item-2-rotation: -6deg;
  $item-2-z-index: 4;
  $item-3-left: 242px;
  $item-3-top: 610px;
  $item-3-rotation: 10deg;
  $item-3-z-index: 2;
  $item-4-top: 638px;
  $item-4-left: 70px;
  $item-4-rotation: -15deg;
  $item-4-z-index: 1;

  > .new-product-tile {
    position: absolute;
    @for $i from 1 through 4 {
      &.item-#{$i} {
        /* Here sir */
        $item: "$item-#{$i}";
        @include  collage-item-position( #{#{$item}-left}, #{#{$item}-top}, #{#{$item}-rotation}, #{#{$item}-z-index} );
      }
    }
  }
}
```

But generated CSS is like this:

``` css
.new-product-tile.item-3 {
  /* Here sir */
  left: $item-3-left;
  top: $item-3-top-218px;
  z-index: $item-3-z-index;
  -webkit-transform: rotate($item-3-rotation);
...
```

**Comment by mohsen1** [comment]
I think this is the same [eval variable names](https://groups.google.com/forum/#!topic/sass-lang/MI1G0jTp64k) issue.

Can I do better?

**Comment by pdaoust** [comment]
Hi -- that's correct; variable names don't get interpolated later. What's the expected output? We can work backwards from there.

**Comment by mohsen1** [comment]
We want to include `collage-item-position()` 4 times with values that we declared on top of the mixin. 

This is a chuck of what it would produce:

```
.new-product-tile.item-3 {
  left: 278px;
```

value of `$item-3-left`is passed to `collage-item-position` and it sets the `left` property. Again, in `produc-collage` level, we want to call `collage-item-position` mixin 4 times with those values.

**Comment by pdaoust** [comment]
Oh, I understand now. Right now that's not possible (although it may be possible in the future). How about using lists for the different items that need to be in the collage?

``` scss
@mixin product-collage {
  // $items is a list of item positioning values, each item consisting
  // of four values: left offset, top offset, rotation, and z-index.
  $items: (
    70px 250px 6deg 2,
    278px 340px -6deg 4,
    242px 610px 10deg 2,
    70px 638px -15deg 1
  );

  > .new-product-tile {
    position: absolute;
    @for $i from 1 through 4 {
      &.item-#{$i} {
        // Get the item from the list.
        $item: nth($items, $i);
        // Pull each of the values from the item using nth()
        @include collage-item-position( nth($item, 1), nth($item, 2), nth($item, 3), nth($item, 4) );
      }
    }
  }
}
```

I don't know what's happening in your `collage-item-position()` mixin, but you might want to also refactor it to take a list of four values, in which case line 18 in the above sample would read:

``` scss
        @include collage-item-position($item);
```

(That part doesn't matter so much, because then you're just shifting complexity from one spot to another.)

The above is slightly less clear than being able to give each value a variable name -- the developer simply has to remember that each item in `$items` is a list of four values (left, top, rotation, and z-index). In Sass 3.3 you'll be able to define hashmaps, so you could make your code more explicit:

``` scss
$items: (
  book-1: (left: 70px, top: 250px, rotation: 6deg, z-index: 2),
  book-2: (left: 278px, top: 340px, rotation: -6deg, z-index: 4),
  // etc.
);
// more code...
@each $item-name, $positioning in $items {
  &.#{$item-name} {
    @include collage-item-position(map-get($positioning, left), map-get($positioning, top), map-get($positioning, rotation), map-get($positioning, z-index));
  }
}
```
