### ISSUE TITLE
Duplicate rules in the same rule set (could this be avoided?)

### ISSUE THREAD

**Issue by viswanathct** [sass/sass#949]
## This SCSS

``` scss
@mixin float-left
{
    float: left;
}

@mixin another-float-left
{
    float: left;
}

@mixin float-none
{
    float: none;
}

.f
{
    @include float-left;
    @include another-float-left;
    @include float-none;
}
```
## Gives this CSS

``` css
.f {
  float: left;
  float: left;
  float: none;
}
```
## Desired CSS

``` css
.f {
  float: none;
}
```

I think that this could be better. 

This potentially could hinder modular development; by causing a significant overhead (both in size and in process wise) when mixins are used freely.

**Comment by pdaoust** [comment]
I think this is a potentially good idea -- with caution. Identical rules ought to be collapsed, for sure, but there are times when you don't want this behaviour, like in these two examples:

``` css
    .seethru {
        background-color: #fff; // fallback for IE8 and below
        background-color: rgba(255, 255, 255, 0.5); // for modern browsers
    }

    .enforced-height {
        height: 16px; // again, this is for poor ol' IE
        height: 1rem;
    }
```

In both cases, IE8 and below will ignore the rule they don't understand, using the previous rule they do understand. So we'd have to be awful careful to preserve ordering of property/value pairs, as well as only collapsing exact duplicates.

**Comment by nex3** [comment]
This is an optimization I've wanted to add for ages, but I've never gotten around to it. There may be another issue for it somewhere, but I was unable to dig it up, so I'll leave this one open for now.

The heuristic I was planning on using was that if two properties with the same name were defined in the same lexical scope -- that is, they're next to one another in the source file -- then both are preserved. Only when one is from a mixin and the other is not, or both are from separate mixins, would the earlier property be erased. This may not catch everything, and it is a slight violation of referential transparency, but I think it catches the most cases without being likely to cause much trouble in practice.

**Comment by pdaoust** [comment]
Interesting -- my first thought is that it isn't too transparent, but I can also see the rationale for this. It's very rare that you'd be writing declarations for the same property side-by-side if you mean for them to collapse, and conversely it's very rare that you want both declarations to apply if they're defined in two separate mixins. Makes sense to me, although it probably ought to feature largely in the documentation :-)

**Comment by viswanathct** [comment]
as **pdaoust** said: _" Identical rules ought to be collapsed"._

_Could this be implemented **after compilation** , as a first step_

This could prove helpful, when using a **mixin libray like _Bourbon_**

## Desired CSS

``` css
.f {
    float: left;
    float: none;
}
```

**Comment by pdaoust** [comment]
@viswanathct : what is the SCSS code that would produce that desired CSS in your use case?

**Comment by vinayraghu** [comment]
This would be a very useful addition that prevents repetition without making the developer worry about it. I can repeat the same style any number of times but my code won't be bloated. 

Its not too transparent, but this is pretty much how your CSS is going to work and with source maps, it should be easy to detect, where this particular **final** style is being computed from. 

I know there are many ways to overcome this problem and this is not really a limitation in sass, but I would totally :+1: this feature!

Another example, for @pdaoust is as below 
It doesn't seem too useful because we are using the mixin below only a few times. But imagine a big project, where these mixins are called over and over but overrides happen once in a while. Doesn't make sense to make it an optional parameter either. Doesn't make sense to have dual declarations. 

``` scss
@mixin something {
   ...;
   float: left; 
}

.1 {
 @include something;
}
.2 {
  @include something;
  more styles; 
}
.3 {
  @include something;
  float: right;
}
```

**Comment by viswanathct** [comment]
@pdaoust, I suggested it as a generic improvement. I trying implement OOCSS on a project. In which, I use jade for _templating out_ UI controls. I'm worried that the **weight** of the CSS would increase, as the project gets more complex.

So, I suggest that, _two **exactly identical** rules within the same scope_ could be removed from the **resulting CSS**.

And, Is there a way to label this as a "feature"?

**Comment by pdaoust** [comment]
@viswanathct Post-compilation is probably a good place to do this, you're right. I think that, if the maintainers think this issue is a good idea (and it sounds like they do), they'll give it a 'feature request' label.

I'm still curious, what would be the SCSS code that would produce your desired output:

``` scss
.f {
    float: left;
    float: none;
}
```

The intent of the code wasn't clear from your example.
