### ISSUE TITLE
Parent selector and extend produce unexpected result

### ISSUE THREAD

**Issue by georgemarshall** [sass/sass#969]
I've found an issue with parent `&` selectors and `@extend` usage together. The following example illustrates what is happening. I also looked through _extend_test.rb_ to see if this case was covered, which it is not.

``` scss
// Original SCSS
div {
  .error {
    color: red;
  }
  &:hover {
    @extend .error;
    background: grey;
  }
}

// Sass output
div .error, div div:hover {
  color: red;
}
div:hover {
  background: grey;
}

// Expected result
div .error, div:hover {
  color: red;
}
div:hover {
  background: grey;
}
```

**Comment by mturnwall** [comment]
Isn't this how @extend is supposed to work? The &:hover is pulled up to where the @extend is located. So the SASS code you end up with before it's compiled is actually:

``` css
div {
  div:hover {
    // css code
  }
}
```

I would say you need to move the location of your @extend.

**Comment by Anahkiasen** [comment]
Yup that's normal behavior, check your code again, as `.error` is scoped in `div`, so will `div:hover`. Just do this instead :

``` scss
div {
  .error, &:hover {
    color: red;
  }
  &:hover {
    background: grey;
  }
}
```
