### ISSUE TITLE
3.3.0rc1 Division in parenthesized expression does not happen when a function call is involved

### ISSUE THREAD

**Issue by monsanto** [sass/sass#973]
foo.scss:

```
@function foo() {
 @return 20px;
}

#body {
 padding-left: (foo() / 2);
}
```

Result:

```
$ sass foo.scss
#body {
  padding-left: 20px/2; }
```

Expected result by division rule 3 ("If the value is surrounded by parentheses."):

```
$ sass foo.scss
#body {
  padding-left: 10px; }
```

**Comment by lunelson** [comment]
Yeah, I'm seeing this with maps on 3.3rc1. I was also getting a similar problem with the embedded version of 3.2.12 in [Mixture 210](http://docs.mixture.io/mac/changelog) but can't seem to reproduce it now.

At Sassmeister with 3.3rc1 ([gist](http://sassmeister.com/gist/7053938)):

``` scss
$numerator: 5;
$demoninator: 8;
$test: (numerator: 5, denominator: 8);

.debug {
    out: $numerator / $demoninator;
    out: (map-get($test, numerator) / map-get($test, denominator));
}
```

``` css
.debug {
  out: 0.625;
  out: 5/8;
}
```

**Comment by lunelson** [comment]
I'm using the following to force division for now on this issue:

``` scss
@function quotient($a, $b) {
    @return $a * 1 / $b * 1;
}
// alias of above
@function q($a, $b) { @return quotient($a, $b); }

$testmap: (foo: 5, bar: 8);

.test-out {
    fail: map-get($testmap, foo) / map-get($testmap,bar);
    pass: q(map-get($testmap, foo), map-get($testmap,bar));
}
```

``` css
.test-out {
  fail: 5/8;
  pass: 0.625;
}

```
