### ISSUE TITLE
@at-root + placeholder + @extend = ?

### ISSUE THREAD

**Issue by eoneill** [sass/sass#975]
the traditional case that works

``` scss
%base {
  display: block;
}
.test {
  @extend %base;
  display: none;
}
```

generates...

``` css
.test {
  display: block;
}
.test {
  display: none;
}
```

now the slightly less trivial case that isn't behaving the way I'd expect it to (I would have expected the same result as above)...

``` scss
.test {
  @at-root %base {
    display: block;
  }
  @extend %base; // also tried wrapping this in an @at-root
  display: none;
}
```

but I get...

``` css
.test {
  display: none;
}
.test {
  display: block;
}
```

it sorta makes sense to get this result, but my gut disagreed

**Comment by nex3** [comment]
Everything within an `@at-root` will end up below its containing selector, regardless of where it is relative to its sibling rules (or `@extend`s). So this is expected, since the intermediate step looks like this:

``` scss
.test {
  @extend %base; // also tried wrapping this in an @at-root
  display: none;
}
%base {
  display: block;
}
```

**Comment by eoneill** [comment]
Thanks for the detail! I imaged that's the way it was working.

**Comment by LinboLen** [comment]
```scss
$ease-in-out: cubic-bezier(0.645, 0.045, 0.355, 1);
  
.ant-notification{  
  
  .notification-fade-effect{
    animation-duration: 0.24s;
    animation-fill-mode: both;
    animation-timing-function: $ease-in-out;
  }

  @at-root &-fade-enter,
  &-fade-appear {
    opacity: 0;
    @extend .notification-fade-effect;
    animation-play-state: paused;
  }
}
```

result 
```css
.ant-notification .notification-fade-effect, 
.ant-notification .ant-notification-fade-enter, 
.ant-notification .ant-notification-fade-appear {
  animation-duration: 0.24s;
  animation-fill-mode: both;
  animation-timing-function: cubic-bezier(0.645, 0.045, 0.355, 1);
}
.ant-notification-fade-enter, .ant-notification-fade-appear {
  opacity: 0;
  animation-play-state: paused;
}

```

why not 
```css
.ant-notification .notification-fade-effect,
.ant-notification-fade-enter, 
.ant-notification-fade-appear {
  animation-duration: 0.24s;
  animation-fill-mode: both;
  animation-timing-function: cubic-bezier(0.645, 0.045, 0.355, 1);
}
.ant-notification-fade-enter, .ant-notification-fade-appear {
  opacity: 0;
  animation-play-state: paused;
}
```

**Comment by nex3** [comment]
@LinBoLen That `@at-root` isn't actually doing anything; `@at-root` just removes the *default* nesting, but since you're using explicit nesting with `&` the default nesting doesn't apply anyway. So your style is equivalent to:

```scss
$ease-in-out: cubic-bezier(0.645, 0.045, 0.355, 1);
  
.ant-notification .notification-fade-effect {
  animation-duration: 0.24s;
  animation-fill-mode: both;
  animation-timing-function: $ease-in-out;
}

.ant-notification-fade-enter,
.ant-notification-fade-appear {
  opacity: 0;
  @extend .notification-fade-effect;
  animation-play-state: paused;
}
```

The `@extend` then replaces `.notification-fade-effect` with `.ant-notificiation-fade-enter`, which produces the output you're seeing.
