### ISSUE TITLE
Extending from inside media queries should be allowed

### ISSUE THREAD

**Issue by lolmaus** [sass/sass#984]
Hi!

I use media queries extensively. Being unable to extend from inside media queries makes me unhappy.

I don't understand why it's forbidden. I can think of how it can be possible: SASS should simply **maintain a separate extendable list of selectors for each unique media query**.

Please consider this code (it's just a synthetic example to explain a concept):

``` sass
%extendable1
  color: red

%extendable2
  width: 50%


.foo
  @extend %extendable1

.bar
  @extend %extendable1


@media (min-width: 400px)
  .foo
    @extend %extendable1

  .bar
    @extend %extendable2

  .baz
    @extend %extendable2
```

SASS should totally compile this into:

``` css
.foo, .bar {
  color: red; }

@media (min-width: 400px) {
  .foo {
    color: red; }
  .bar, .baz {
    width: 400px; }}
```

A simple approach, yet very efficient for constructing complex responsive layouts and looks.

Please consider this a feature request.
