### ISSUE TITLE
sass-convert: incorrect comment handling (Sass 3.2.12)

### ISSUE THREAD

**Issue by badsyntax** [sass/sass#986]
Hi there.

If I have the following comment in a CSS file:

``` ccc
/*
// Lorem ipsum Nisi aute velit quis.
.lorem{color:red;}
*/
```

..and then run sass-convert on that CSS file:

`sass-convert --from css --to scss test.css`

It results in the following: 

``` css
//
// Lorem ipsum Nisi aute velit quis.
.lorem{color:red;}
*/
```
