### ISSUE TITLE
@at-root parent selector doesn't work with placeholder classes

### ISSUE THREAD

**Issue by Snugug** [sass/sass#987]
I am currently experimenting with `@at-root` and placeholder classes and I've found, unexpectedly, that they don't work. I have the following code:

``` scss
%square {
    background: blue;

    @at-root #{&}--red {
        color: red;
    }
}

.foo {
    @extend %square;

    @at-root #{&}--green {
        color: green;
    }
}
```

And the output CSS I get follows:

``` scss
.foo {
  background: blue;
}
.foo--green {
  color: green;
}
```

Whereas the expected output is:

``` scss
.foo {
  background: blue;
}
.foo--red {
  background: red;
}
.foo--green {
  color: green;
}
```

However, if I `@extend %square--red;`, this works. I assume this is happening because it's creating a new silent selector, but I believe the expected output is that I would be able to extend `%square` and get the root extension as well.

**Comment by nex3** [comment]
`@at-root` and all interpolation is resolved before any `@extend`ing happens. So first the document is transformed into:

``` scss
%square {
  background: blue;
}

%square--red {
  color: red;
}

.foo {
  @extend %square;
}

.foo--green {
  color: green;
}
```

which then produces the output you're seeing.
