### ISSUE TITLE
Hyphenated map keys fail to match hyphenated arguments

### ISSUE THREAD

**Issue by mirisuzanne** [sass/sass#989]
This gives me an error:

``` scss
// $margin-before should match (margin-before: 2em)
@mixin foo(
  $width,
  $margin-before    : null
) {
  width: $width;
  margin-left: $margin-before;
}

$bar: (
  width           : 1em,
  margin-before   : 2em,
);

.baz { @include foo($bar...); }
```

output:

``` css
/* error sass/test.scss (Line 32: Mixin foo doesn't have an argument named $margin-before.) */
```

This works fine:

``` scss
// Replaced map-key underscore with hyphen: (margin_before: 2em)...
@mixin foo(
  $width,
  $margin-before    : null
) {
  width: $width;
  margin-left: $margin-before;
}

$bar: (
  width           : 1em,
  margin_before   : 2em,
);

.baz { @include foo($bar...); }
```

output:

``` css
.baz {
  width: 1em;
  margin-left: 2em;
}
```
