### ISSUE TITLE
Attached Ampersand Placement doesn't work with interpolated selector names

### ISSUE THREAD

**Issue by Snugug** [sass/sass#990]
This is something that seems to have been an issue for a while but has never come up due to Sass conventions. Previously, the most common approach to creating interpolated classes looked like the following:

``` scss
$foo: 'bar';

.foo {
  content: 'foo';
  &.#{$foo}--bar {
    content: 'bar';
  }
}
```

And that all worked fine because we were interpolating the string but had the `.` there before the interpolation to tell Sass it was a string. However, with the introduction of scripted selectors `#{&}`, we are now interpolating the whole selector, including the `.`, which causes an error:

`Invalid CSS after "    &#{&}-": expected number or function, was "-bar {"`

This, as it turns out, is an issue even without the scripted selector. This can wind up being an issue if, for some reason, you wanted to do some fairly specific SMACSS style selecting and wanted something like the following:

``` scss
.message {
  border-radius: 5px;
  &#{&}-status {
    background: green;
  }
}
```

``` css
.message {
  border-radius: 5px;
}

.message.message-status {
  background: green;
}
```

While I agree that this is bad CSS, it still is valid CSS, and shouldn't produce a parsing error.

**Comment by nex3** [comment]
A non-interpolated `&` only works in cases where the parser can figure out how to attach it to the rest of the selector. In this case it can't, because the `#{}` could produce anything.

Also, I think this case is easy enough to handle by just interpolating the other `&` as well:

``` scss
.message {
  border-radius: 5px;
  @at-root #{&}#{&}-status {
    background: green;
  }
}
```
