### ISSUE TITLE
Scripted Selector should return non-class when used in middle of compound selector

### ISSUE THREAD

**Issue by Snugug** [sass/sass#992]
When using a scripted selector as a piece of a larger selector, especially when that selector is a class or an ID, it returns the id/class identifier (`#`, `.`). When using something like SMACSS's combined state and module convention, this makes for invalid CSS:

``` scss
.tab {
  color: white;

  @at-root .is-#{&}-active {
    color: blue;
  }
}
```

This produces

``` css
.tab {
  color: white;
}

// Should be .is-tab-active
.is-.tab-active {
  color: blue;
}
```

I believe in this case, the expected result is what would be expected more often than the actual output which IIRC is an invalid selector
