### ISSUE TITLE
Placeholders on Parent Selectors compile like they're nested, not using the Parent Selector

### ISSUE THREAD

**Issue by taylortrimble** [sass/sass#993]
I'm quite new to Sass, so I could be trying to do something I'm not supposed to here. But, here goes!

Here is my (simplified) Sass:

``` scss
.btn-blue {
    color: #fff;
    &%active {
        background-color: darken(blue, 10%);
        border-color: darken(blue, 15%);
    }
    :hover,
    :focus {
        @extend %active;
    }
    :active,
    .active {
        @extend %active;
        background-image: none;
    }
}
```

You'll notice I'm trying to set the hover/focus/active state to a set of styles, and give one extra style to the set of "active" states.

Expected output:

``` css
.btn-blue {
  color: #fff;
}

.btn-blue:hover,
.btn-blue:focus,
.btn-blue:active,
.btn-blue.active {
  background-color: #0000cc;
  border-color: #0000b3;
}

.btn-blue:active,
.btn-blue.active {
  background-image: none;
}
```

Actual output:

``` css
.btn-blue {
  color: #fff;
}

.btn-blue .btn-blue:hover,
.btn-blue .btn-blue:focus,
.btn-blue .btn-blue:active,
.btn-blue .btn-blue.active {
  background-color: #0000cc;
  border-color: #0000b3;
}

.btn-blue :active,
.btn-blue .active {
  background-image: none;
}
```

Two unexpected things happen:
1. Placeholders on Parent Selectors compile like they're nested, not like they're using the Parent Selector
2. The active states only selectors (`background-image: none` is the content) `:active` and `.active` aren't abutted, but don't behave like they're nested.

My workaround:

``` scss
.btn-blue {
    color: #fff;
    &:hover,
    &:focus,
    &:active,
    &.active {
        background-color: darken(blue, 10%);
        border-color: darken(blue, 15%);
    }
    &:active,
    &.active {
        background-image: none;
    }
}
```

I'll be the first to point out that my workaround is actualyl shorter than what I want to write, but I think it's slightly inelegant that I have to duplicate `&:active, &.active` when that's what extensions are for.

Let me know what you think, or if I'm just going about this the wrong way! Thanks.

**Comment by Snugug** [comment]
They way you have this written, the output you're getting is actually expected, although the logic can be a bit weird if you haven't worked with `@extend` before.

Let's rewrite this code a little bit to get a better idea of exactly what's happening:

``` scss
.btn-blue%active {
    background-color: darken(blue, 10%);
    border-color: darken(blue, 15%);
}

.btn-blue {
    color: #fff;

    :hover,
    :focus {
        @extend %active;
    }
    :active,
    .active {
        @extend %active;
        background-image: none;
    }
}
```

Simply rewriting like this (how Sass sees it), it now becomes a little bit more clear what's happening. What you're saying for `hover`, `focus`, and `active` is that you would like to extend `.btn-blue%active` (the compound selector that gets created). Because your nested items aren't attached to `.btn-blue` (the parent selector) but are for the `.btn-blue` attached to `%active`, it appears as if you get double `.btn-blue` selectors when in reality it's just the one on `%active`. Those then get nested under the children `.btn-blue`, which is what gives you the double `.btn-blue` class.

Good news is there's a simple and easy way to get this to work! If you rewrite like the following, the extends will work fine.

``` scss
%btn-blue--active {
    background-color: darken(blue, 10%);
    border-color: darken(blue, 15%);
}

.btn-blue {
    color: #fff;

    &:hover,
    &:focus {
        @extend %btn-blue--active;
    }
    &:active,
    &.active {
        @extend %btn-blue--active;
        background-image: none;
    }
}
```

While you don't need to namespace your placeholder selector like I did, I always find it useful to.

**Comment by taylortrimble** [comment]
I totally get that! Big A+ on the response time and clear communication - thank you! :heart:

**Comment by lolmaus** [comment]
Your problem is not related to extending. You just forgot the ampersands, while you didn't forget them in the workaround.

Here you go:

``` scss
.btn-blue {
    color: #fff;
    &%active {
        background-color: darken(blue, 10%);
        border-color: darken(blue, 15%);
    }
    &:hover,
    &:focus {
        @extend %active;
    }
    &:active,
    &.active {
        @extend %active;
        background-image: none;
    }
}
```

Result:

``` css
.btn-blue {
  color: #fff;
}
.btn-blue:hover, .btn-blue:focus, .btn-blue:active, .btn-blue.active {
  background-color: #0000cc;
  border-color: #0000b3;
}
.btn-blue:active, .btn-blue.active {
  background-image: none;
}
```

Demo: http://sassmeister.com/gist/7283712

@Snugug's first example won't work either due to missing ampersands.

I think this approach violates the [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) a lot. I find your workaround to be way more readable and maintainable.
