### ISSUE TITLE
[feature suggestion] Copy property value from a given selector

### ISSUE THREAD

**Issue by rafaelrinaldi** [sass/sass#999]
I was thinking that it would be great if we had a way of copying values from other properties by passing a selector. Here's how I can imagine this being used:

``` scss
.icon {
  content: "";
  display: inline-block;
  width: 16px;
  height: 18px;
  // Since the value is the same, we can just reference it.
  line-height: &.height;
}

// Referencing body values.
.my-content {
  background: body.background;
  color: body.color;
}
```

Or maybe having something like `@value`, IDK.

I know this can be accomplished by using variables but it could be useful anyway.
